### ISSUE TITLE
[1.7.0.3] `run ios-device` fails to install cordova-plugin-meteor-webapp

### ISSUE THREAD

**Issue by jfols** [meteor/meteor#10000]
MacOS 10.13.5, XCode 9.4.1

Reproduce:

`meteor create newapp && cd newapp`
`meteor add-platform ios`
```
meteor run ios-device --verbose
Getting installed version for platform ios in Cordova project
Checking Cordova requirements for platform iOS
%% PlatformApi successfully found for platform ios
[[[[[ ~/modweb/newapp ]]]]]

=> Started proxy.
Local package version is up-to-date: allow-deny@1.1.0
Local package version is up-to-date: autopublish@1.0.7
Local package version is up-to-date: autoupdate@1.4.0
Local package version is up-to-date: babel-compiler@7.1.1
Local package version is up-to-date: babel-runtime@1.2.2
Local package version is up-to-date: base64@1.0.11
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.2
Local package version is up-to-date: blaze-html-templates@1.1.2
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.5.0
Local package version is up-to-date: caching-compiler@1.1.12
Local package version is up-to-date: caching-html-compiler@1.1.2
Local package version is up-to-date: callback-hook@1.1.0
Local package version is up-to-date: check@1.3.1
Local package version is up-to-date: ddp@1.4.0
Local package version is up-to-date: ddp-client@2.3.2
Local package version is up-to-date: ddp-common@1.4.0
Local package version is up-to-date: ddp-server@2.2.0
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.1.0
Local package version is up-to-date: dynamic-import@0.4.1
Local package version is up-to-date: ecmascript@0.11.1
Local package version is up-to-date: ecmascript-runtime@0.7.0
Local package version is up-to-date: ecmascript-runtime-client@0.7.1
Local package version is up-to-date: ecmascript-runtime-server@0.7.0
Local package version is up-to-date: ejson@1.1.0
Local package version is up-to-date: es5-shim@4.8.0
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.4.1
Local package version is up-to-date: id-map@1.1.0
Local package version is up-to-date: insecure@1.0.7
Local package version is up-to-date: jquery@1.11.11
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: logging@1.1.20
Local package version is up-to-date: meteor@1.9.0
Local package version is up-to-date: meteor-base@1.4.0
Local package version is up-to-date: minifier-css@1.3.1
Local package version is up-to-date: minifier-js@2.3.5
Local package version is up-to-date: minimongo@1.4.4
Local package version is up-to-date: mobile-experience@1.0.5
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modern-browsers@0.1.1
Local package version is up-to-date: modules@0.12.0
Local package version is up-to-date: modules-runtime@0.10.0
Local package version is up-to-date: mongo@1.5.0
Local package version is up-to-date: mongo-dev-server@1.1.0
Local package version is up-to-date: mongo-id@1.0.7
Local package version is up-to-date: npm-mongo@3.0.7
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: ordered-dict@1.1.0
Local package version is up-to-date: promise@0.11.1
Local package version is up-to-date: random@1.1.0
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.2.0
Local package version is up-to-date: retry@1.1.0
Local package version is up-to-date: routepolicy@1.0.13
Local package version is up-to-date: shell-server@0.3.1
Local package version is up-to-date: socket-stream-client@0.2.2
Local package version is up-to-date: spacebars@1.0.15
Local package version is up-to-date: spacebars-compiler@1.1.3
Local package version is up-to-date: standard-minifier-css@1.4.1
Local package version is up-to-date: standard-minifier-js@2.3.4
Local package version is up-to-date: templating@1.3.2
Local package version is up-to-date: templating-compiler@1.3.3
Local package version is up-to-date: templating-runtime@1.3.2
Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: tracker@1.2.0
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.2.0
Local package version is up-to-date: webapp@1.6.1
Local package version is up-to-date: webapp-hashing@1.0.9
Preparing Cordova project from app bundle
Copying resources for mobile apps
Writing new config.xml
WARNING: Attempting to install plugin cordova-plugin-statusbar@2.2.1, but it should have a
         minimum version of 2.3.0 to ensure compatibility with the current platform
         versions. Installing the minimum version for convenience, but you should adjust
         your dependencies.
WARNING: Attempting to install plugin cordova-plugin-splashscreen@4.0.1, but it should have
         a minimum version of 4.1.0 to ensure compatibility with the current platform
         versions. Installing the minimum version for convenience, but you should adjust
         your dependencies.
Removing plugins
cordova-plugin-meteor-webapp,cordova-plugin-whitelist,cordova-plugin-wkwebview-engine from
Cordova project
%% No scripts found for hook "before_plugin_rm".
%% Calling plugman.uninstall on plugin "cordova-plugin-meteor-webapp" for platform "ios"
%% Calling plugman.uninstall on plugin "cordova-plugin-whitelist" for platform "ios"
%% Calling plugman.uninstall on plugin "cordova-plugin-wkwebview-engine" for platform "ios"
%% Running command: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Running command: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Running command: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Command finished with error code 0: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Finding scripts for "before_plugin_uninstall" hook from plugin cordova-plugin-meteor-webapp on ios platform only.
%% No scripts found for hook "before_plugin_uninstall".
%% Uninstalling cordova-plugin-meteor-webapp from ios
%% Beginning processing of action stack for ios project...
%% Action stack processing complete.
%% Removing "cordova-plugin-meteor-webapp"
%% Deleted "cordova-plugin-meteor-webapp"
%% Removing plugin cordova-plugin-meteor-webapp from fetch.json
%% Command finished with error code 0: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Finding scripts for "before_plugin_uninstall" hook from plugin cordova-plugin-whitelist on ios platform only.
%% No scripts found for hook "before_plugin_uninstall".
%% Uninstalling cordova-plugin-whitelist from ios
%% Beginning processing of action stack for ios project...
%% Action stack processing complete.
%% Removing "cordova-plugin-whitelist"
%% Deleted "cordova-plugin-whitelist"
%% Removing plugin cordova-plugin-whitelist from fetch.json
%% Command finished with error code 0: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Finding scripts for "before_plugin_uninstall" hook from plugin cordova-plugin-wkwebview-engine on ios platform only.
%% No scripts found for hook "before_plugin_uninstall".
%% Uninstalling cordova-plugin-wkwebview-engine from ios
%% Beginning processing of action stack for ios project...
%% Action stack processing complete.
%% Removing "cordova-plugin-wkwebview-engine"
%% Deleted "cordova-plugin-wkwebview-engine"
%% Removing plugin cordova-plugin-wkwebview-engine from fetch.json
%% No scripts found for hook "after_plugin_rm".
Adding plugin cordova-plugin-whitelist@1.3.2 to Cordova project
%% No scripts found for hook "before_plugin_add".
%% Calling plugman.fetch on plugin "cordova-plugin-whitelist@1.3.2"
%% Fetching plugin "cordova-plugin-whitelist@1.3.2" via npm
%% Copying plugin "/Users/justin/.cordova/lib/npm_cache/cordova-plugin-whitelist/1.3.2/package" => "/Users/justin/modweb/newapp/.meteor/local/cordova-build/plugins/cordova-plugin-whitelist"
%% Calling plugman.install on plugin "/Users/justin/modweb/newapp/.meteor/local/cordova-build/plugins/cordova-plugin-whitelist" for platform "ios
%% Installing "cordova-plugin-whitelist" for ios
%% Running command: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
Doing HTTP request:  POST
https://www.meteor.com/oauth2/authorize?state=80398226141cb1855f839620a5ef6c62&response_type=code&client_id=LdpZEt7ubqXAfkDJ2&redirect_uri=https%3A%2F%2Factivity.meteor.com%2F_oauth%2Fmeteor-developer%3Fclose
%% Command finished with error code 0: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-whitelist on ios platform only.
%% No scripts found for hook "before_plugin_install".
%% Install start for "cordova-plugin-whitelist" on ios.
%% Beginning processing of action stack for ios project...
%% Action stack processing complete.
%% Install complete for cordova-plugin-whitelist on ios.
%% Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-whitelist on ios platform only.
%% No scripts found for hook "after_plugin_install".
%% No scripts found for hook "after_plugin_add".
Adding plugin cordova-plugin-wkwebview-engine@1.1.3 to Cordova project
%% No scripts found for hook "before_plugin_add".
%% Calling plugman.fetch on plugin "cordova-plugin-wkwebview-engine@1.1.3"
%% Fetching plugin "cordova-plugin-wkwebview-engine@1.1.3" via npm
%% Copying plugin "/Users/justin/.cordova/lib/npm_cache/cordova-plugin-wkwebview-engine/1.1.3/package" => "/Users/justin/modweb/newapp/.meteor/local/cordova-build/plugins/cordova-plugin-wkwebview-engine"
%% Calling plugman.install on plugin "/Users/justin/modweb/newapp/.meteor/local/cordova-build/plugins/cordova-plugin-wkwebview-engine" for platform "ios
%% Installing "cordova-plugin-wkwebview-engine" for ios
%% Running command: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Command finished with error code 0: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-wkwebview-engine on ios platform only.
%% No scripts found for hook "before_plugin_install".
%% Install start for "cordova-plugin-wkwebview-engine" on ios.
%% Beginning processing of action stack for ios project...
%% Adding non-custom framework to project... WebKit.framework -> {"customFramework":false,"embed":false,"link":true,"weak":true}
%% Non-custom framework added to project. WebKit.framework -> {"customFramework":false,"link":true,"weak":true}
%% Action stack processing complete.
%% Install complete for cordova-plugin-wkwebview-engine on ios.
%% Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-wkwebview-engine on ios platform only.
%% No scripts found for hook "after_plugin_install".
%% No scripts found for hook "after_plugin_add".
Adding plugin cordova-plugin-meteor-webapp@1.6.0 to Cordova project
%% No scripts found for hook "before_plugin_add".
%% Calling plugman.fetch on plugin "cordova-plugin-meteor-webapp@1.6.0"
%% Fetching plugin "cordova-plugin-meteor-webapp@1.6.0" via npm
%% Copying plugin "/Users/justin/.cordova/lib/npm_cache/cordova-plugin-meteor-webapp/1.6.0/package" => "/Users/justin/modweb/newapp/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp"
%% Calling plugman.install on plugin "/Users/justin/modweb/newapp/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp" for platform "ios
%% Installing "cordova-plugin-meteor-webapp" for ios
%% Running command: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Command finished with error code 0: /Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/version
%% Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-meteor-webapp on ios platform only.
%% No scripts found for hook "before_plugin_install".
%% Install start for "cordova-plugin-meteor-webapp" on ios.
%% Beginning processing of action stack for ios project...
%% Error during processing of action! Attempting to revert...
%% Failed to install 'cordova-plugin-meteor-webapp': Uh oh!
"/Users/justin/modweb/newapp/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/src/ios/GCDWebServer/GCDWebServer/Core/GCDWebServer.m" not found!
    at copyFile (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:319:36)
    at copyNewFile (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:348:5)
    at installHelper (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
    at install (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
    at ActionStack.process (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
=> Errors executing Cordova commands:

   While adding plugin cordova-plugin-meteor-webapp@1.6.0 to Cordova project:
   Uh oh!

   "/Users/justin/modweb/newapp/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/src/ios/GCDWebServer/GCDWebServer/Core/GCDWebServer.m"
   not found!
   at copyFile
   (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:319:36)
   at copyNewFile
   (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:348:5)
   at installHelper
   (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
   at install
   (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
   at ActionStack.process
   (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
   at PluginManager.doOperation
   (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
   at PluginManager.addPlugin
   (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
   at Api.addPlugin
   (/Users/justin/modweb/newapp/.meteor/local/cordova-build/platforms/ios/cordova/Api.js:234:10)
   at handleInstall
   (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:594:10)
   at
   /Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:357:28
   at _fulfilled
   (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:749:13)
   at
   /Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:509:49
   at flush
   (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:108:17)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
   => awaited here:
   at Function.Promise.await
   (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at Promise.asyncApply (/tools/cordova/project.js:525:9)
   at
   /Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
   at Function.Promise.await
   (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:731:14)
   at CordovaProject.addPlugin (/tools/cordova/project.js:523:12)
   at _.each (/tools/cordova/project.js:654:16)
   at Function._.each._.forEach
   (/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at buildmessage.enterJob (/tools/cordova/project.js:653:11)
   at /tools/utils/buildmessage.js:359:18
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at CordovaProject.ensurePluginsAreSynchronized (/tools/cordova/project.js:549:18)
   at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:213:10)
   at buildmessage.enterJob (/tools/cordova/runner.js:78:27)
   at /tools/utils/buildmessage.js:359:18
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at CordovaRunner.prepareProject (/tools/cordova/runner.js:77:18)
   at buildmessage.capture (/tools/runners/run-app.js:670:25)
   at /tools/utils/buildmessage.js:271:13
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at AppRunner._runOnce (/tools/runners/run-app.js:669:39)
   at AppRunner._fiber (/tools/runners/run-app.js:880:28)
   at /tools/runners/run-app.js:408:12

/Users/justin/.meteor/packages/meteor-tool/.1.7.0_3.s7tf2b.q6df++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
ExitWithCode:1
```

**Comment by jfols** [comment]
Fixed via https://github.com/meteor/meteor/issues/9300#issuecomment-341929733

**Comment by benjamn** [comment]
Congrats on opening issue #10000! 💯⨉ 💯
