### ISSUE TITLE
[1.7.0.3] Error when using custom Meteor.loginWithPassword

### ISSUE THREAD

**Issue by enzolutions** [meteor/meteor#10024]
I am trying to migrate from 1.6.1.3 to 1.7.0.3 but I got an error after calling **Meteor.loginWithPassword** from the client side

I got the error **Exception while invoking method 'login' Error: Custom EJSON type FS.File is not defined**

Maybe worth to mention that this is my current list of packages of meteor

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.5.0                   # The database Meteor supports right now
static-html             # Define static page content in .html files
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.2.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.4.1   # CSS minifier run for production mode
standard-minifier-js@2.3.4    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.11.1              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.1            # Server-side component of the `meteor shell` command
react-meteor-data
nicolaslopezj:roles
session
less
universe:i18n
accounts-password
accounts-base

````

Below the full backtrace of the error

```
I20180624-13:57:36.996(10)? Exception while invoking method 'login' Error: Custom EJSON type FS.File is not defined
I20180624-13:57:36.997(10)?     at Object.fromJSONValue (packages/ejson/ejson.js:215:15)
I20180624-13:57:36.997(10)?     at fromJSONValueHelper (packages/ejson/ejson.js:317:28)
I20180624-13:57:36.997(10)?     at Object.EJSON.fromJSONValue.item [as fromJSONValue] (packages/ejson/ejson.js:367:17)
I20180624-13:57:36.997(10)?     at replaceMongoAtomWithMeteor (packages/mongo/mongo_driver.js:65:18)
I20180624-13:57:36.998(10)?     at replaceTypes (packages/mongo/mongo_driver.js:106:30)
I20180624-13:57:36.998(10)?     at packages/mongo/mongo_driver.js:112:23
I20180624-13:57:36.998(10)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20180624-13:57:36.998(10)?     at replaceTypes (packages/mongo/mongo_driver.js:111:5)
I20180624-13:57:36.999(10)?     at packages/mongo/mongo_driver.js:112:23
I20180624-13:57:36.999(10)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20180624-13:57:36.999(10)?     at replaceTypes (packages/mongo/mongo_driver.js:111:5)
I20180624-13:57:36.999(10)?     at Promise.asyncApply (packages/mongo/mongo_driver.js:1037:13)
I20180624-13:57:36.999(10)?     at /Users/enzo/.meteor/packages/promise/.0.11.1.1jjdgfp.d6ac++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180624-13:57:36.999(10)?  => awaited here:
I20180624-13:57:37.000(10)?     at Promise.await (/Users/enzo/.meteor/packages/promise/.0.11.1.1jjdgfp.d6ac++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20180624-13:57:37.000(10)?     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1083:12)
I20180624-13:57:37.000(10)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1097:22)
I20180624-13:57:37.000(10)?     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1107:10)
I20180624-13:57:37.000(10)?     at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1131:17)
I20180624-13:57:37.001(10)?     at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:879:44)
I20180624-13:57:37.001(10)?     at MongoConnection.findOne (packages/mongo/mongo_driver.js:786:56)
I20180624-13:57:37.001(10)?     at Collection.findOne (packages/mongo/collection.js:351:29)
I20180624-13:57:37.001(10)?     at AccountsServer.Accounts._findUserByQuery (packages/accounts-password/password_server.js:139:25)
I20180624-13:57:37.002(10)?     at MethodInvocation.<anonymous> (packages/accounts-password/password_server.js:296:23)
I20180624-13:57:37.002(10)?     at packages/accounts-base/accounts_server.js:483:32
I20180624-13:57:37.002(10)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:259:14)
I20180624-13:57:37.002(10)?     at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:480:18)
I20180624-13:57:37.002(10)?     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:543:27)
I20180624-13:57:37.003(10)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20180624-13:57:37.003(10)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
```

**Comment by enzolutions** [comment]
I solved my problems by adding an extra dependency

```
meteor add cfs:ejson-file
```

Maybe is required to add **cfs:ejson-file** as dependency for **accounts-password** or
**accounts-base**
