### ISSUE TITLE
[WebApp] Middleware unable to be used

### ISSUE THREAD

**Issue by theodorDiaconu** [meteor/meteor#10039]
Let's say I want to use this:

```
  WebApp.connectHandlers.use(
    '/graphiql',
    supergraphiqlExpress({
      endpointURL: '/graphql',
    })
  );
```

It fails with:

```
E20180629-14:14:00.785(3) (webapp_server.js:882) Error running template: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.setWriteHeadHeaders (/Users/theodor/.meteor/packages/webapp/.1.6.1.3qgmge.cc90l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:82:19)
    at ServerResponse.writeHead (/Users/theodor/.meteor/packages/webapp/.1.6.1.3qgmge.cc90l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:41:36)
    at getBoilerplateAsync.then (packages/webapp/webapp_server.js:874:13)
    at /Users/theodor/.meteor/packages/promise/.0.11.1.1pfway6.6nip++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180629-14:14:00.786(3)? (STDERR) (node:55753) UnhandledPromiseRejectionWarning: Error: Can't set headers after they are sent.
W20180629-14:14:00.787(3)? (STDERR)     at validateHeader (_http_outgoing.js:491:11)
W20180629-14:14:00.787(3)? (STDERR)     at ServerResponse.setHeader (_http_outgoing.js:498:3)
W20180629-14:14:00.787(3)? (STDERR)     at ServerResponse.setWriteHeadHeaders (/Users/theodor/.meteor/packages/webapp/.1.6.1.3qgmge.cc90l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:82:19)
W20180629-14:14:00.787(3)? (STDERR)     at ServerResponse.writeHead (/Users/theodor/.meteor/packages/webapp/.1.6.1.3qgmge.cc90l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:41:36)
W20180629-14:14:00.787(3)? (STDERR)     at getBoilerplateAsync.then.catch.error (packages/webapp/webapp_server.js:883:13)
W20180629-14:14:00.788(3)? (STDERR)     at /Users/theodor/.meteor/packages/promise/.0.11.1.1pfway6.6nip++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180629-14:14:00.788(3)? (STDERR) (node:55753) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
W20180629-14:14:00.788(3)? (STDERR) (node:55753) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This happens with Apollo Server 2's playground also.

Reference (added it here as well) https://github.com/apollographql/apollo-server/issues/1172#issuecomment-401022273

**Comment by theodorDiaconu** [comment]
The culprit is this one: `next();` if I remove that it works and the error starts to make a lot of sense.

**Comment by theodorDiaconu** [comment]
The way I hacked it was to add another middleware that would simply end() the request without calling next(). I think it's a good approach.
