### ISSUE TITLE
Problems with standard-minifier-js

### ISSUE THREAD

**Issue by musemind** [meteor/meteor#10044]
Building with `standard-minifier-js@2.3.4` runs in error.
Meteor 1.7.0.3

```
Errors prevented bundling:                    
While minifying app code:                     
/Users/jl/.meteor/packages/standard-minifier-js/.2.3.4.b8cycq.lb73u++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:779:15: Unexpected token (1:248893)
at _class.raise (/Users/jl/.meteor/packages/standard-minifier-js/.2.3.4.b8cycq.lb73u++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babylon/lib/index.js:779:15)
at _class.unexpected (/Users/jl/.meteor/packages/standard-minifier-js/.2.3.4.b8cycq.lb73u++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/met

[... MUCH MORE SIMILAR ERRORS ...]

at Object.parse (/Users/jl/.meteor/packages/standard-minifier-js/.2.3.4.b8cycq.lb73u++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/reify/lib/parsers/babylon.js:40:18)
at Object.parse (packages/babel-compiler.js:46:29)
at extractModuleSizesTree (packages/minifyStdJS/plugin/stats.js:23:23)
at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:141:20)
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:118:9)
```

The problem is caused by a specific file `/cordova.js` in our project.
Uncomment the `standard-minifier-js` before building solves the problem :)

WORKS, NO ERROR
```
// cordova.js
import {Meteor} from 'meteor/meteor'
import { FlowRouter } from 'meteor/kadira:flow-router'

if (Meteor.isCordova) {
  const subscribe = () => {
    console.log('subscribe to universal links')
    if (typeof universalLinks === 'undefined') return console.log('universalLinks not defined') // eslint-disable-line
    universalLinks.subscribe(null, function (eventData) { // eslint-disable-line
      console.log('universal link detected', JSON.stringify(eventData))
      if (eventData.host === 'www.foodly.shop') FlowRouter.go(eventData.path)
    })
  }
  subscribe()
  Meteor.startup(() => subscribe())
}
```

CODE CAUSING ERROR
```
// cordova.js
import {Meteor} from 'meteor/meteor'
import {FlowRouter} from 'meteor/kadira:flow-router'
import R from 'ramda'

if (Meteor.isCordova) {
  const subscribe = () => {
    console.log('universal link: subscribed')
    if (typeof universalLinks === 'undefined') return console.log('universalLinks not defined') // eslint-disable-line
    universalLinks.subscribe(null, function (eventData) { // eslint-disable-line
      console.log('universal link: detected', JSON.stringify(eventData))
      if (eventData.host === 'www.foodly.shop') {
        const redirectLoop = setInterval(() => {
          console.log('universal link: try to redirect to', eventData.path)
          FlowRouter.go(eventData.path)
          if (R.pathOr('wronglink', ['_current', 'path'], FlowRouter) === eventData.path) {
            console.log('universal link: redirect confirmation!')
            clearInterval(redirectLoop)
          }
        }, 500)
      }
    })
  }
  subscribe()
  Meteor.startup(() => subscribe())
}
```

**Comment by benjamn** [comment]
Possible solution: https://github.com/meteor/meteor/issues/10042

**Comment by musemind** [comment]
Wow, fast reply! Anyone who already switched from **uglify-es** to  **terser** or **babel-minify**? Is it planned in an upcoming meteor patch?

Thanks and regards!

**Comment by benjamn** [comment]
Since you're already on Meteor 1.7.0.3, you should be able to run
```sh
meteor update --release 1.7.1-beta.14
```
without (m)any troubles, which will give you `minifier-js@2.4.0` and `standard-minifier-js@2.4.0` with the new `terser` minifier.

**Comment by musemind** [comment]
Works perfectly!

**Comment by adamgins** [comment]
Hi @benjamn is there something special I need to do to get this to work with `Meteor 1.7.1-beta.29`


I am still getting this issue:

```
While minifying app code:

   /Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:196:18:
   Unexpected token: operator (>)
   at new JS_Parse_Error
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:196:18)
   at js_error
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:204:11)
   at croak
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:675:9)
   at token_error
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:683:9)
   at unexpected
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:689:9)
   at expr_atom
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:1196:9)
   at maybe_unary
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:1358:19)
   at expr_ops
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:1393:24)
   at maybe_conditional
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:1398:20)
   at maybe_assign
   (/Users/adamginsburg/.meteor/packages/standard-minifiers-js/.1.0.3-modules.8.1ayknur.d3oo++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifiers-js/minifiers-js/node_modules/uglify-js/lib/parse.js:1422:20)
   

```

**Comment by yanickrochon** [comment]
Anything new with this issue? Just got this exact same error.

**Comment by yanickrochon** [comment]
Seems to be resolved with the latest release (1.8-rc.17)

**Comment by dnszero** [comment]
I had the same problem with Meteor 1.8.0.1 (coming from 1.5).

Turns out that the minifier's issue was an used server function:
```
// Due to a refactor, insertStuff() is never called anywhere
if (Meteor.isServer) {
  function insertStuff({id, position}) {
    if (! this.userId) {
      throw new Meteor.Error('not-authorized')
    }
    // ...more boring code...
  }
}
```

After commenting out that block of code, meteor was able to build once again. 

Is this the expected behavior? If so, could any errors or warnings be provided in the development phase (ie, if prod is going to fail, I'd like dev to fail too).

Also, is there any way for meteor to provide a useful error during the build? A hint regarding the line or even the file that it choked on would be great.

**Comment by xpressabhi** [comment]
Getting exact same error with Meteor 1.9 and standard-minifier-js/.2.6.0

**Comment by ajitStephen** [comment]
> Getting exact same error with Meteor 1.9 and standard-minifier-js/.2.6.0

+1
solved ?

**Comment by xpressabhi** [comment]
> > Getting exact same error with Meteor 1.9 and standard-minifier-js/.2.6.0
> 
> +1
> solved ?

Solved, deleted project and recreated again.

**Comment by nikhilgoswami** [comment]
>  Getting exact same error with Meteor 1.9 and standard-minifier-js/.2.6.0
>  
>  
>  +1
>  solved ?
> 
> Solved, deleted project and recreated again.

I am having same problem with meteor 1.10.2 and standard-minifier-js@2.6.0 
Any Idea on how to debug this.
meteor app runs in development this error is only in production

`/home/nick/.meteor/packages/standard-minifier-js/.2.6.0.1hjwx7x.pmcz++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63:
   Identifier 'O' has already been declared (1:105454)
   at Object.raise
   (/home/nick/.meteo`
