### ISSUE TITLE
prettier reformats babelrc file to json5, but meteor does not like it

### ISSUE THREAD

**Issue by macrozone** [meteor/meteor#10068]
prettier reformats .babelrc files to JSON5, which should be supported by babel according to this thread:
https://github.com/prettier/prettier/issues/4636

but meteor does not seem to understand it and throws:

```
 While processing files with ecmascript (for target web.browser):
   <anonymous>: .babelrc is not a valid JSON file: Unexpected token p in JSON at position 4
   at JSON.parse (<anonymous>)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler.js:255:16)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:244:10)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:174:10)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:111:26)
   at Array.forEach (<anonymous>)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:110:14)
```

EDIT: happening on meteor 1.6.1. Unfortunatly, I can't update to 1.7.0 atm because of pending issues

**Comment by sakulstra** [comment]
facing the same issue on 1.7.1-beta

**Comment by macrozone** [comment]
it looks like this works in current meteor
