### ISSUE TITLE
[1.7.1-beta.20] Error: Asset manifest does not have a version when running Cordova

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#10088]
When running 1.7.1-beta.20 in cordova, I got the following error:

```
I20180720-20:40:21.607(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp: Download failure
I20180720-20:40:21.612(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp: com.meteor.webapp.WebAppException: Asset manifest does not have a version
I20180720-20:40:21.613(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at com.meteor.webapp.AssetManifest.<init>(AssetManifest.java:48)
I20180720-20:40:21.614(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:112)
I20180720-20:40:21.614(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
I20180720-20:40:21.615(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20180720-20:40:21.616(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
I20180720-20:40:21.616(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
I20180720-20:40:21.617(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at java.lang.Thread.run(Thread.java:760)
I20180720-20:40:21.618(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp: Caused by: org.json.JSONException: No value for version
I20180720-20:40:21.618(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at org.json.JSONObject.get(JSONObject.java:389)
I20180720-20:40:21.619(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at org.json.JSONObject.getString(JSONObject.java:550)
I20180720-20:40:21.619(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       at com.meteor.webapp.AssetManifest.<init>(AssetManifest.java:46)
I20180720-20:40:21.620(8)? 07-20 20:40:05.111 29620 29743 W MeteorWebApp:       ... 6 more
I20180720-20:40:21.620(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp: Download failure
I20180720-20:40:21.621(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp: com.meteor.webapp.WebAppException: Asset manifest does not have a version
I20180720-20:40:21.621(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at com.meteor.webapp.AssetManifest.<init>(AssetManifest.java:48)
I20180720-20:40:21.622(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:112)
I20180720-20:40:21.622(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
I20180720-20:40:21.623(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20180720-20:40:21.623(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
I20180720-20:40:21.624(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
I20180720-20:40:21.624(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at java.lang.Thread.run(Thread.java:760)
I20180720-20:40:21.625(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp: Caused by: org.json.JSONException: No value for version
I20180720-20:40:21.625(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at org.json.JSONObject.get(JSONObject.java:389)
I20180720-20:40:21.626(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at org.json.JSONObject.getString(JSONObject.java:550)
I20180720-20:40:21.626(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       at com.meteor.webapp.AssetManifest.<init>(AssetManifest.java:46)
I20180720-20:40:21.627(8)? 07-20 20:40:05.111 29620 29743 E MeteorWebApp:       ... 6 more
I20180720-20:40:21.627(8)? 07-20 20:40:05.114 29620 29620 I chromium: [INFO:CONSOLE(37)] "Error: Asset manifest does not have a version", source: http://localhost:12224/__cordova/packages/webapp.js?hash=4451ceb25b4d4b0ff1238498e9d4161c4fdeba43 (37)
```

Not existing in 1.7.1-beta.19

**Comment by wojtkowiak** [comment]
Same here with beta.21 - at a very very first glance seems that the `meteor_autoupdate_clientVersions` publication fires when when `web.browser` is rebuilt but the legacy target is not yet ready.
This also fails with meteor-desktop as it has cordova webapp plugin ported for HCP.

**Comment by benjamn** [comment]
We will definitely fix this before the first 1.7.1 release candidate. Sorry for the wait.

**Comment by benjamn** [comment]
Can you try this again after running `meteor update --release 1.7.1-beta.32`?

**Comment by rj-david** [comment]
Confirmed fixed. Thanks Ben.
