### ISSUE TITLE
Strange dynamic import error and Galaxy

### ISSUE THREAD

**Issue by acomito** [meteor/meteor#10082]
```
Exception while invoking method '__dynamicImport' Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/imports/ui/components/common/ClientInviteForm/index.js'
```

The weird thing is, no file in my project is importing, dynamically or otherwise, from `/imports/ui/components/common/ClientInviteForm/index.js`

I at one point refactored my app, so at one point I has a `/common/ClientInviteForm/index.js`

Is this some kind of crazy caching issue with Galaxy? I search for `ClientInviteForm` in my app turns up NOTHING that imports from `/imports/ui/components/common/ClientInviteForm/index.js` and this was working normally up until now.

also, is there a command line feature like `react-native info` for printing out my dev environment quick so i can paste it here?

full log:

```
c1av1
2018-07-18 04:27:13-04:00Exception while invoking method '__dynamicImport' Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/imports/ui/components/common/ClientInviteForm/index.js'
c1av1
2018-07-18 04:27:13-04:00 at Object.fs.openSync (fs.js:646:18)
c1av1
2018-07-18 04:27:13-04:00 at fs.readFileSync (fs.js:551:33)
c1av1
2018-07-18 04:27:13-04:00 at read (packages/dynamic-import/server.js:61:24)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:38:16)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
c1av1
2018-07-18 04:27:13-04:00Exception while invoking method '__dynamicImport' Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/imports/ui/components/common/ClientInviteForm/index.js'
c1av1
2018-07-18 04:27:13-04:00 at Object.fs.openSync (fs.js:646:18)
c1av1
2018-07-18 04:27:13-04:00 at fs.readFileSync (fs.js:551:33)
c1av1
2018-07-18 04:27:13-04:00 at read (packages/dynamic-import/server.js:61:24)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:38:16)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at Object.keys.forEach.name (packages/dynamic-import/server.js:34:24)
c1av1
2018-07-18 04:27:13-04:00 at Array.forEach (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at walk (packages/dynamic-import/server.js:32:27)
c1av1
2018-07-18 04:27:13-04:00 at DDPCommon.MethodInvocation.__dynamicImport (packages/dynamic-import/server.js:43:12)
c1av1
2018-07-18 04:27:13-04:00 at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
c1av1
2018-07-18 04:27:13-04:00 at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
c1av1
2018-07-18 04:27:13-04:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
c1av1
2018-07-18 04:27:13-04:00 at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
c1av1
2018-07-18 04:27:13-04:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1134:15)
c1av1
2018-07-18 04:27:13-04:00 at Promise (packages/ddp-server/livedata_server.js:715:46)
c1av1
2018-07-18 04:27:13-04:00 at new Promise (<anonymous>)
c1av1
2018-07-18 04:27:13-04:00 at Session.method (packages/ddp-server/livedata_server.js:689:23)
c1av1
2018-07-18 04:27:13-04:00 at packages/ddp-server/livedata_server.js:559:43
2hgxa
2018-07-18 05:13:47-04:00Exception while invoking method '__dynamicImport' Error: ENOENT: no such file or directory, open '/app/bundle/programs/web.browser/dynamic/imports/ui/components/common/ClientInviteForm/index.js'
```

**Comment by benjamn** [comment]
Your stack trace suggests you're still using a version of `dynamic-import` that uses the `__dynamicImport` DDP method, rather than HTTP (#9384). In other words, you must not be using Meteor 1.6.1 yet. Is there any possibility of updating Meteor, at least to the latest 1.6.x version (`meteor update --release 1.6.1.3`)? A lot of things have changed about dynamic `import()` since the days when it used DDP, so there's a reasonable chance this bug no longer occurs. 🤞

**Comment by acomito** [comment]
That sounds like it could be it! I'll report back shortly. Thanks for your time.

**Comment by acomito** [comment]
hmm... my dynamic imports no longer work.

```
import React from 'react';
import PropTypes from 'prop-types';
import Loadable from 'react-loadable';

const Loading = () => {
  return (
    <div style={s.container}>
      <Spin />
    </div>
  );
};

const ErrorMessage = () => {
  return (
    <div style={s.container}>
      <div>
        <Title>Error loading!</Title>
      </div>
    </div>
)
}



const LoadableLoading = ({ isLoading, pastDelay, error }) => {

  if (isLoading && pastDelay) {
    return <Loading />;
  } else if (error && !isLoading) {
    return <ErrorMessage />;
  }

  return null;

};

LoadableLoading.propTypes = {
  isLoading: PropTypes.bool.isRequired,
  pastDelay: PropTypes.bool.isRequired,
  error: PropTypes.object,
};

export default function LoadableWrapper(opts) {
  return Loadable({
    loading: LoadableLoading,
    ...opts,
  });
}

```

```
const LoginPage = LoadableLoading({
  loader: () => import('/imports/ui/pages/public/login-page'),
});

class PublicLayout extends React.Component {
  render() {
    return (
      <Switch>
            <Route 
              path="/login" 
              render={() => <LoginPage {...this.props} />} 
            />
//...
```

**Comment by benjamn** [comment]
Do you see any HTTP errors in the Network panel for `/__meteor__/dynamic-import/fetch` requests?

**Comment by Rockettomatoo** [comment]
I don't really know if this relates directly to this issue but dynamic imports don't work for me on the client although they work on the server.

I have a fairly simple example:
```js
// client/test.js
console.log('loading test.js');
export default { foo: 'bar' }


// client/main.js
import { Meteor } from 'meteor/meteor'

async function loadTest() {
  console.log(await import ('./test.js'));
}

Meteor.startup(() => {
  loadTest();
});
```

If i do this exact same thing on the server, I get the `module.exports` object from `test.js` as expected.

If I run the above snippet on the client however, I get the following error:
```
OPTIONS http://localhost:3000/__meteor__/dynamic-import/fetch 0 ()
HTTP.call @ http.js?hash=d3dd208935f8ca87ff86948a53498046333fdb3b:231
(anonymous) @ dynamic-import.js?hash=466c13dad76afd19c9a5236a9302d4a8f56cfe04:160
fetchMissing @ dynamic-import.js?hash=466c13dad76afd19c9a5236a9302d4a8f56cfe04:151
(anonymous) @ dynamic-import.js?hash=466c13dad76afd19c9a5236a9302d4a8f56cfe04:80
(anonymous) @ meteor.js?hash=1f49b977b0beabbfeaa0ef0bdb87e0693971b18c:1223
Promise.then (async)
Promise.then @ promise.js?hash=badbb15e6daa4c8fb4dcd6049286a198af5008b4:130
meteorInstall.fetch @ dynamic-import.js?hash=466c13dad76afd19c9a5236a9302d4a8f56cfe04:70
(anonymous) @ modules-runtime.js?hash=7f4df5777c8321c08a58834753e5d5a010366eda:179
(anonymous) @ meteor.js?hash=1f49b977b0beabbfeaa0ef0bdb87e0693971b18c:1223
Promise.then (async)
Promise.then @ promise.js?hash=badbb15e6daa4c8fb4dcd6049286a198af5008b4:130
Module.prefetch @ modules-runtime.js?hash=7f4df5777c8321c08a58834753e5d5a010366eda:168
Module.dynamicImport @ dynamic-import.js?hash=466c13dad76afd19c9a5236a9302d4a8f56cfe04:40
loadTest @ client.js:10
Meteor.startup @ client.js:14
maybeReady @ meteor.js?hash=1f49b977b0beabbfeaa0ef0bdb87e0693971b18c:927
loadingCompleted @ meteor.js?hash=1f49b977b0beabbfeaa0ef0bdb87e0693971b18c:939

Uncaught (in promise) Error: Connection lost
    at XMLHttpRequest.xhr.onreadystatechange (http.js?hash=d3dd208935f8ca87ff86948a53498046333fdb3b:172)
xhr.onreadystatechange @ http.js?hash=d3dd208935f8ca87ff86948a53498046333fdb3b:172
async function (async)
loadTest @ client.js:9
Meteor.startup @ client.js:14
maybeReady @ meteor.js?hash=1f49b977b0beabbfeaa0ef0bdb87e0693971b18c:927
loadingCompleted @ meteor.js?hash=1f49b977b0beabbfeaa0ef0bdb87e0693971b18c:939
```

I'm currently running with `meteor@1.7.0.3`.

My packages versions:
```
accounts-base@1.4.2
accounts-password@1.5.1
allow-deny@1.1.0
autoupdate@1.4.1
babel-compiler@7.1.1
babel-runtime@1.2.2
base64@1.0.11
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.5.0
caching-compiler@1.1.12
caching-html-compiler@1.1.3
callback-hook@1.1.0
check@1.3.1
ddp@1.4.0
ddp-client@2.3.3
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.2.0
deps@1.0.12
diff-sequence@1.1.0
dynamic-import@0.4.1
ecmascript@0.11.1
ecmascript-runtime@0.7.0
ecmascript-runtime-client@0.7.1
ecmascript-runtime-server@0.7.0
ejson@1.1.0
email@1.2.3
es5-shim@4.8.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.1
id-map@1.1.0
jquery@1.11.11
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
matb33:collection-hooks@0.8.4
meteor@1.9.2
meteor-base@1.4.0
minifier-css@1.3.1
minifier-js@2.3.5
minimongo@1.4.4
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modern-browsers@0.1.2
modules@0.12.2
modules-runtime@0.10.2
mongo@1.5.1
mongo-dev-server@1.1.0
mongo-id@1.0.7
npm-bcrypt@0.9.3
npm-mongo@3.0.7
observe-sequence@1.0.16
ordered-dict@1.1.0
promise@0.11.1
random@1.1.0
rate-limit@1.0.9
react-meteor-data@0.2.16
reactive-dict@1.2.0
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
routepolicy@1.0.13
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.3.1
socket-stream-client@0.2.2
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.4.1
standard-minifier-js@2.3.4
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.2
tracker@1.2.0
ui@1.0.13
underscore@1.0.10
url@1.2.0
webapp@1.6.2
webapp-hashing@1.0.9
```

**Comment by JoschuaSchneider** [comment]
@Rockettomatoo I just ran into exactly the same issue and was going to create a new issue.

For me, dynamic imports do not work in both chrome and Samsung-Internet on my Galaxy S8+.

My chrome version is `67.0.3396.87`
Meteor version used is `1.7.0.1`
Simulated IOS/Safari works fine, desktop chrome works fine too.

Error in Console:
<img width="840" alt="bildschirmfoto 2018-07-23 um 14 50 58" src="https://user-images.githubusercontent.com/11740387/43077799-d2e7e9f0-8e88-11e8-8106-285538e21e55.png">

My DynamicImport component is just a wrapper around a dynamic import statement.
```javascript
import('./path/to/component')
```

**Comment by rjsmith** [comment]
Hi everyone,

I hit this dynamic import problem myself yesterday whilst trying to locally run my v1.7.0.3 Meteor application on my dev machine but using a browser on another machine on my local network to access the ui.  The dynamic import worked fine on the same machine as my server (accessed at http://localhost:3000/app) but failed in the same way as described in this issue thread on every browser on other devices when using my dev machine's local IP address as the url (e.g. "http://192.168.1.16:3000/app").  Note, however, I have never seen this issue on my production system hosted on Galaxy.

I think I tracked down the root cause (at least for my version of the problem) to this line of code in the dynamic import package:

https://github.com/meteor/meteor/blob/e91b3776e54ca9e1607bf89e0cebd32170eb2c1d/packages/dynamic-import/client.js#L130

It uses Meteor.absoluteUrl() for the dynamic import fetch POST request sent from the browser client.  But, by default if just using `meteor run`, the ROOT_URL is set to `localhost`. So, the clients on other machines on my network trying to POST to "http://localhost/__meteor__/dynamic-import/fetch" keeps failing. 

When I changed my meteor launch command to `ROOT_URL="http://192.168.1.16:3000" meteor run`, the dynamic import then worked perfectly on all machines on my network (because the POST requests now hit a reachable url).  That also explains why I have never seen this issue on my production instance because Galaxy always sets the correct ROOT_URL environment variable.

Note that whilst I was figuring out the above, I also tried this:

`ROOT_URL="http://192.168.1.16" meteor run --port=3000`

But that didn't work.  Looks like Meteor.absoluteUrl() ignores the `port` argument if ROOT_URL is set?

Anyhow, I hope this might help some folk coming across this issue.

**Comment by Rockettomatoo** [comment]
@rjsmith thanks a lot! Setting an appropriate ROOT_URL solved this issue for me! 
My dev environment does indeed run on a different machine than the browser I was testing in so the ROOT_URL was set to localhost which is false.

**Comment by manueltimita** [comment]
We have some Windows machines running Linux VMs, and so the Meteor app is accessed over the VMWare network. We encountered exactly this issue today, after upgrading from Meteor `1.6.1.3` to Meteor `1.7.0.3`, then the same after upgrading to `1.7.1-beta.21`. 

Running `ROOT_URL=http://<machine_ip>:3000 meteor run` fixes the problem.

Trying to run `ROOT_URL=http://<machine_ip> meteor run --port=3000` does not seem to set the port in `ROOT_URL`. Executing `meteor update dynamic-import` as in @benjamn 's advice shows that the packages is already at its latest version.

**Comment by benjamn** [comment]
Yes, the `ROOT_URL` needs to include the port, unless the port is 80 (HTTP) or 443 (HTTPS), since browsers will try those ports automatically.

**Comment by rjsmith** [comment]
Hi @benjamn .  Thanks for the clarification. It would be really useful to clarify this and the inter-relation (or not) between the PORT and ROOT_URL environment variables in the Meteor documentation [here](https://docs.meteor.com/environment-variables.html#ROOT-URL).

**Comment by kudatr** [comment]
> Yes, the `ROOT_URL` needs to include the port, unless the port is 80 (HTTP) or 443 (HTTPS), since browsers will try those ports automatically.

Hi there, I understand how the client for the server import location based on the root url.  I am hosting my apps in production using Amazon Web Services, with a load balancer and target group.  This allows traffic to be routed to multiple servers with ip addresses that can change at any time.  My dns for the url points to the load balancer, and the load balancer sends traffic to app servers in the target group.  As such there is no way to tell what the IP address of the server the client is connected to is.  How do I get dynamic imports to work in this case.
