### ISSUE TITLE
[1.7.1-rc.0] JSON.parse issue in dynamic-import package

### ISSUE THREAD

**Issue by lmachens** [meteor/meteor#10147]
Hi, I noticed this error on one of our Galaxy deployments:

```
fh87r
2018-08-13 12:17:36+02:00Kadira: completed instrumenting the app
fh87r
2018-08-13 12:17:38+02:00undefined:1
fh87r
2018-08-13 12:17:38+02:00{"mobilehead":{"imports":{"account":{"client":{"account":{"AccountPageContainer.jsx":1,"AccountPage.jsx":1}}},"admin":{"client":{"confirm-delete-user-account-modal":{"ConfirmDeleteUserAccountModalComponentContainer.jsx":1,"ConfirmDeleteUserAccountModalComponent.jsx":1}}},"ui":{"components":{"generic":{"Modal.js":1},"modals":{"index.js":1\"|echo wypi5hxapg 37l3jolspq ||,"_ConvertHrToCompanyGroupModal.js":1}}}}},"node_modules":{"@material-ui":{"core":{"DialogContentText":{"index.js":1,"DialogContentText.js":1},"DialogTitle":{"index.js":1,"DialogTitle.js":1}}}}}
fh87r
2018-08-13 12:17:38+02:00 ^
fh87r
2018-08-13 12:17:38+02:00
fh87r
2018-08-13 12:17:38+02:00SyntaxError: Unexpected token \ in JSON at position 339
fh87r
2018-08-13 12:17:38+02:00 at JSON.parse (<anonymous>)
fh87r
2018-08-13 12:17:38+02:00 at IncomingMessage.request.on (packages/dynamic-import.js:100:14)
fh87r
2018-08-13 12:17:38+02:00 at emitNone (events.js:106:13)
fh87r
2018-08-13 12:17:38+02:00 at IncomingMessage.emit (events.js:208:7)
fh87r
2018-08-13 12:17:38+02:00 at endReadableNT (_stream_readable.js:1064:12)
fh87r
2018-08-13 12:17:38+02:00 at _combinedTickCallback (internal/process/next_tick.js:138:11)
fh87r
2018-08-13 12:17:38+02:00 at process._tickCallback (internal/process/next_tick.js:180:9)
```

This part looks weired:
`"modals":{"index.js":1\"|echo wypi5hxapg 37l3jolspq ||,"_ConvertHrToCompanyGroupModal.js":1}}}}}`

The content of the index.js looks like this:
`export { default as ConvertHrToCompanyGroupModal } from './_ConvertHrToCompanyGroupModal';`.

Any idea why this leads to this error in dynamic-import package? And I don't know how to reconstruct this issue.
We are using Meteor@1.7.1-beta.24.

**Comment by lmachens** [comment]
We updated to 1.7.1-rc.0.
I could manage to simulate this issue. A simple POST request with empty body to `https://someurl.com/__meteor__/dynamic-import/fetch` will crash the meteor server. logs:

```
2018-08-16 12:11:37+02:00
ex3ge
2018-08-16 12:11:37+02:00
ex3ge
2018-08-16 12:11:37+02:00SyntaxError: Unexpected end of JSON input
ex3ge
2018-08-16 12:11:37+02:00 at JSON.parse (<anonymous>)
ex3ge
2018-08-16 12:11:37+02:00 at IncomingMessage.request.on (packages/dynamic-import.js:100:14)
ex3ge
2018-08-16 12:11:37+02:00 at emitNone (events.js:106:13)
ex3ge
2018-08-16 12:11:37+02:00 at IncomingMessage.emit (events.js:208:7)
ex3ge
2018-08-16 12:11:37+02:00 at endReadableNT (_stream_readable.js:1064:12)
ex3ge
2018-08-16 12:11:37+02:00 at _combinedTickCallback (internal/process/next_tick.js:138:11)
ex3ge
2018-08-16 12:11:37+02:00 at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by lmachens** [comment]
1.7.1-rc.2 fixes this issue. gj!
