### ISSUE TITLE
METEOR@1.7.1-rc.0 does not work with jagi:astronomy

### ISSUE THREAD

**Issue by pgiani** [meteor/meteor#10161]
if you try Meteor 1.7.1-rc.0 version, it crash on start

 
**simple to reproduce**

```
meteor create  --full test
cd test
meteor update --release 1.7.1-rc.0
meteor add jagi:astronomy
meteor run

```

here this is the log output

```
> test@ start /Users/pgiani/www/test
> meteor run

[[[[[ ~/www/test ]]]]]                        

=> Started proxy.                             
/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: ENFILE: file table overflow, open '/Users/pgiani/.meteor/packages/jagi_astronomy/2.5.8/os/lib/modules/validators/validators/logical/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at wrapper (/tools/fs/files.js:1607:35)
    at wrap.makeCacheKey (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/optimistic.js:94:15)
    at optimistic (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:65:17)
    at makeOptimistic (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/optimistic.js:308:23)
    at wrap.makeCacheKey (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/optimistic.js:94:15)
    at reallyRecompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:301:28)
    at recomputeIfDirty (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:259:12)
    at Entry.recompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:87:10)
    at optimistic (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:82:23)
    at Resolver._getPkgJsonSubsetForDir (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/resolver.js:400:17)
    at (anonymous function).args (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/resolver.js:166:45)
    at reallyRecompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:301:28)
    at recomputeIfDirty (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:259:12)
    at Entry.recompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:87:10)
    at Resolver.optimistic [as _getPkgJsonSubsetForDir] (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:82:23)
    at Resolver._findPkgJsonSubsetForPath (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/resolver.js:448:26)
    at (anonymous function).args (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/resolver.js:166:45)
    at reallyRecompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:301:28)
    at recomputeIfDirty (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:259:12)
    at Entry.recompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:87:10)
    at Resolver.optimistic [as _findPkgJsonSubsetForPath] (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:82:23)
    at Resolver._findPkgJsonSubsetForPath (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/resolver.js:469:17)
    at (anonymous function).args (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/resolver.js:166:45)
    at reallyRecompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:301:28)
    at recomputeIfDirty (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:259:12)
    at Entry.recompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:87:10)
    at Resolver.optimistic [as _findPkgJsonSubsetForPath] (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:82:23)
    at Resolver._resolve (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/resolver.js:258:32)
    at Resolver.resolve.wrap (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/resolver.js:150:19)
    at reallyRecompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:301:28)
    at recomputeIfDirty (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:259:12)
    at Entry.recompute (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:87:10)
    at Resolver.optimistic [as resolve] (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:82:23)
    at ImportScanner._resolve (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:886:36)
    at each (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:985:29)
    at _.each._.forEach (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:979:5)
    at each (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:1013:14)
    at _.each._.forEach (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:979:5)
    at outputFiles.forEach.file (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:660:14)
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:658:22)
    at sourceBatches.forEach.batch (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/compiler-plugin.js:1339:17)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/compiler-plugin.js:1307:19)
    at ServerTarget._emitResources (/tools/isobuild/bundler.js:1114:8)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:841:12)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ServerTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3097:14
    at /tools/isobuild/bundler.js:3228:24
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:3054:31)
    at files.withCache (/tools/isobuild/bundler.js:2999:32)
    at Object.withCache (/tools/fs/files.js:1710:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2999:16)
    at Profile.run (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:577:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:576:34)
    at AppRunner._runOnce (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:619:35)
    at AppRunner._fiber (/Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:933:28)
    at /Users/pgiani/.meteor/packages/meteor-tool/.1.7.1-rc.0.ggysq9.tj32r++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/runners/run-app.js:410:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@ start: `meteor run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pgiani/.npm/_logs/2018-08-16T20_03_34_912Z-debug.log
$ cat /Users/pgiani/.npm/_logs/2018-08-16T20_03_34_912Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.3.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle test@~prestart: test@
6 info lifecycle test@~start: test@
7 verbose lifecycle test@~start: unsafe-perm in lifecycle true
8 verbose lifecycle test@~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/pgiani/www/test/node_modules/.bin:/Users/pgiani/university/mongodb/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle test@~start: CWD: /Users/pgiani/www/test
10 silly lifecycle test@~start: Args: [ '-c', 'meteor run' ]
11 silly lifecycle test@~start: Returned: code: 1  signal: null
12 info lifecycle test@~start: Failed to exec start script
13 verbose stack Error: test@ start: `meteor run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid test@
15 verbose cwd /Users/pgiani/www/test
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.11.3
19 verbose npm  v6.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error test@ start: `meteor run`
22 error Exit status 1
23 error Failed at the test@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by pgiani** [comment]
It apears to be a Mac OSX problem

Yes, I used this script to fix it

https://gist.github.com/abernix/a7619b07b687bb97ab573b0dc30928a0

 Thanks to this reply to my issue here
https://github.com/jagi/meteor-astronomy/issues/682

**Comment by benjamn** [comment]
Cool, thanks for digging further!
