### ISSUE TITLE
Babel cache warning when using `meteor shell`

### ISSUE THREAD

**Issue by klaussner** [meteor/meteor#10189]
Running any command in a `meteor shell` causes the following warning to be logged in the server process because [`ECMAScript.compileForShell`](https://github.com/meteor/meteor/blob/1e34acadc06572557e7e781c0738758d017d2cf2/packages/ecmascript/ecmascript.js#L2) doesn't specify a cache directory:

```
Compiling undefined with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/home/christian/.meteor/packages/babel-compiler/.7.1.1.lkrc35.nn42i++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-babel/index.js:77:13)
    at Object.compile (packages/babel-compiler.js:44:29)
    at Object.compileForShell (packages/ecmascript/ecmascript.js:7:18)
    at REPLServer.wrappedDefaultEval [as eval] (packages/shell-server/shell-server.js:236:48)
    at REPLServer.onLine (repl.js:468:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:280:10)
    at REPLServer.Interface._line (readline.js:629:8)
    at REPLServer.Interface._ttyWrite (readline.js:910:14)
    at REPLServer.self._ttyWrite (repl.js:537:7)
    at PassThrough.onkeypress (readline.js:158:10)
    at emitTwo (events.js:126:13)
    at PassThrough.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
```

The warning isn't shown if you run Meteor from a checkout because [the `meteor` script sets `BABEL_CACHE_DIR`](https://github.com/meteor/meteor/blob/1e34acadc06572557e7e781c0738758d017d2cf2/meteor#L110), which is handled by `meteor/babel` [on these lines](https://github.com/meteor/babel/blob/58ca3a80f213bdf1cc84e458437fa6689d97a576/index.js#L59-L64) before the warning is logged.

Tested with Meteor 1.7.0.5.

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update --release 1.7.1-rc.7`. Please feel free to reopen if you discover otherwise!
