### ISSUE TITLE
v1.7.0.5 scanning package private assets

### ISSUE THREAD

**Issue by cunneen** [meteor/meteor#10191]
\[**EDIT:** the issue is not that the `private` subfolder should be special, it's that files within a package which should be ignored are being scanned\]

Files within a package under the package's `private` subfolder should be ignored by meteor's scanner but accessible via the [Assets API according to the guide](https://docs.meteor.com/api/assets.html). 

However, v1.7.5 is scanning these files (at least when the `less` package is installed). v1.6.1.4 seems to have also had this problem; v1.6.0.1 did not (with `less@2.7.12` the installed version in all cases).

### Reproduction:

```bash
meteor create --release 1.7.0.5 meteor-17-assets-bug
cd meteor-17-assets-bug
# make a package with a package.js that only adds a private asset
mkdir -p packages/meteor-assets-bug/private

cat <<EOF>packages/meteor-assets-bug/package.js
Package.describe({
  name: 'meteor-assets-bug'
});
Package.onUse(function (api) {
  api.use(['ecmascript','less','standard-app-packages']);
  api.addAssets('private/should-be-ignored.less','client');
});
EOF

# add a (empty) private asset
touch packages/meteor-assets-bug/private/should-be-ignored.less

# install our new package
meteor add meteor-assets-bug
```

Then run `meteor`.

### Error:

```
/Users/user/.meteor/packages/meteor-tool/.1.7.0_5.vfyyp0.glf5a++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at dirname (path.js:1349:5)
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:797:7)
    at ImportScanner._checkSourceAndTargetPaths (/tools/isobuild/import-scanner.js:400:31)
    at files.forEach.file (/tools/isobuild/import-scanner.js:244:12)
    at Array.forEach (<anonymous>)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:243:11)
    at sourceBatches.forEach.batch (/tools/isobuild/compiler-plugin.js:1103:15)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1074:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1066:8)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:837:12)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:828:18)
    at /tools/isobuild/bundler.js:3019:14
    at /tools/isobuild/bundler.js:3108:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/Users/user/.meteor/packages/meteor-tool/.1.7.0_5.vfyyp0.glf5a++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:3107:7
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:3000:31)
    at files.withCache (/tools/isobuild/bundler.js:2947:32)
    at Object.withCache (/tools/fs/files.js:1710:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2947:16)
    at Profile.run (/tools/runners/run-app.js:579:36)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:578:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12
```

*Edit* : modified the stack trace to a more readable version.

**Comment by cunneen** [comment]
@sebakerckhof : I agree, the name of the folder (`private`) is not the issue here.

**Comment by cunneen** [comment]
I've added a comment at the top of the issue description, thanks for your input @sebakerckhof .

**Comment by benjamn** [comment]
This appears not to be a problem any more if you run `meteor update --release 1.7.1-rc.7`.
