### ISSUE TITLE
Meteor crash after Error: already have promise?

### ISSUE THREAD

**Issue by mariusrak** [meteor/meteor#10220]
Hi, this error happens a lot. Usually when there is some error on server side. After the error meteor crashes. I guess it is not expected behavior. I don't have much info on this, since it seems to be quite random, but I'll try to gather some. Meanwhile, I'm starting issue just track it and maybe somebody has some info on it for me, why it's happening and what can I do about it (except not creating errors in my program :) ) 

```
=> Modified -- restarting.
C:\Users\Márius Rak\AppData\Local\.meteor\packages\meteor-tool\1.7.1-rc.12\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: already have promise?
    at AppRunner._runOnce (C:\tools\runners\run-app.js:693:13)
    at AppRunner._fiber (C:\tools\runners\run-app.js:908:28)
    at C:\tools\runners\run-app.js:398:12
```

**Comment by mariusrak** [comment]
I have no directory `C:\tools`. So it seems like it's some sort of emulation.

**Comment by benjamn** [comment]
This may be fixed if you update to the latest Meteor 1.8 release candidate:
```bash
meteor update --release 1.8-rc.15
```
thanks to this commit: a6e52c87b951c4315b2e1c26e487415a65e8a30d

**Comment by abernix** [comment]
@rj-david @mariusrak Are either of you able to confirm this is fixed in `1.8-rc.15`?

**Comment by mariusrak** [comment]
I didn't encounter the error recently, so I guess that it's fixed.

**Comment by rj-david** [comment]
@abernix, I did not encounter it. I was trying to help figure what the problem was all about.

**Comment by mariusrak** [comment]
I've made some pretty normal error in js ad meteor crashed:
1.8-rc.15

 ```
C:\Users\Márius Rak\AppData\Local\.meteor\packages\meteor-tool\1.8.0-rc.16\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

TypeError: C:\...\App.js: Duplicate declaration "App"

...
...
...

at File.buildCodeFrameError (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transformation\file\file.js:261:12)
    at Scope.checkBlockScopedCollisions (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\scope\index.js:347:22)
    at Scope.registerBinding (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\scope\index.js:504:16)
    at Scope.registerDeclaration (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\scope\index.js:444:14)
    at Object.BlockScoped (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\scope\index.js:189:28)
    at Object.newFn (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\visitors.js:230:17)
    at NodePath._call (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:36:14)
    at NodePath.visit (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:76:12)
    at NodePath.traverse (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\index.js:161:24)
    at Scope.crawl (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\scope\index.js:684:10)
    at Scope.init (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\scope\index.js:634:32)
    at NodePath.setScope (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:126:30)
    at NodePath.setContext (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:141:8)
    at new File (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transformation\file\file.js:104:8)
    at normalizeFile (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transformation\normalize-file.js:141:10)
    at runSync (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transformation\index.js:44:43)
    at Object.transformSync (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transform.js:43:38)
    at transform (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:103:26)
    at compile (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:113:5)
    at Cache.Cp.get (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\cache.js:101:26)
    at Object.exports.compile (C:\Users\Márius Rak\AppData\Local\.meteor\packages\ecmascript\0.12.0-rc18.16\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:51:7)
    at Object.compile (packages/babel-compiler.js:44:29)
    at packages/babel-compiler.js:211:22
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at profile (packages/babel-compiler.js:259:20)
    at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:210:20)
    at packages/babel-compiler.js:123:25
    at C:\Users\Márius Rak\AppData\Local\.meteor\packages\meteor-tool\1.8.0-rc.16\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Promise.await (C:\Users\Márius Rak\AppData\Local\.meteor\packages\meteor-tool\1.8.0-rc.16\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at JsOutputResource.finalize (C:\tools\isobuild\compiler-plugin.js:891:7)
    at JsOutputResource.hasPendingErrors (C:\tools\isobuild\compiler-plugin.js:918:10)
    at JsOutputResource.reportPendingErrors (C:\tools\isobuild\compiler-plugin.js:923:14)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:841:14)
    at each (C:\tools\isobuild\import-scanner.js:899:14)
    at _.each._.forEach (C:\Users\Márius Rak\AppData\Local\.meteor\packages\meteor-tool\1.8.0-rc.16\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:863:5)
    at outputFiles.forEach.file (C:\tools\isobuild\import-scanner.js:521:14)
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (C:\tools\isobuild\import-scanner.js:519:22)
    at sourceBatches.forEach.batch (C:\tools\isobuild\compiler-plugin.js:1287:17)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:1255:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:1114:8)
    at buildmessage.enterJob (C:\tools\isobuild\bundler.js:841:12)
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:829:18)
    at C:\tools\isobuild\bundler.js:3115:14
    at webArchs.forEach.arch (C:\tools\isobuild\bundler.js:3266:25)
    at Array.forEach (<anonymous>)
    at C:\tools\isobuild\bundler.js:3220:14
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:3096:31)
    at files.withCache (C:\tools\isobuild\bundler.js:3041:32)
    at Object.withCache (C:\tools\fs\files.js:1712:12)
    at Object.bundle (C:\tools\isobuild\bundler.js:3041:16)
    at Profile.run (C:\tools\runners\run-app.js:569:24)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:568:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:610:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:908:28)
    at C:\tools\runners\run-app.js:398:12
```

**Comment by mariusrak** [comment]
Yep, this happens anytime there's duplicate declaration.
