### ISSUE TITLE
Compiling undefined with meteor-babel without a cache

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#10236]
I'm trying to create a new version of: https://github.com/Urigo/meteor-static-html-compiler/tree/master

I updated `caching-compiler` to `1.1.12` and `babel-compiler` to `7.1.1`.

Now I'm getting:
```
Compiling undefined with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/home/seba/.meteor/packages/babel-compiler/.7.1.1.1vxfrdb.5h4o++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-babel/index.js:77:13)
    at Object.compile (packages/babel-compiler.js:44:29)
    at TemplateHtmlCompiler.compileContents (packages/urigo:static-html-compiler/build/src/template.js:35:14)
    at TemplateHtmlCompiler.addCompileResult (packages/urigo:static-html-compiler/build/src/template.js:44:27)
    at async.eachLimit (packages/caching-compiler/caching-compiler.js:319:14)
...
```

I looked into it a bit and from what I understand I needed to pass the cacheOptions to the babel compiler, which I did here: https://github.com/Urigo/meteor-static-html-compiler/blob/master/src/template.ts#L53

But it seems `setDiskCacheDirectory` is never called, since `this._diskCache` is null. So either this should be called and it isn't. Or it should not be called, but then I'd like `meteor-babel` not to show that error with stack trace since now it looks like something is terribly wrong.

**Comment by benjamn** [comment]
I think `StaticHtmlCompiler` might need to implement the `setDiskCacheDirectory` method, or inherit from a class that provides that method. The `TemplateHtmlCompiler` inherits `setDiskCacheDirectory` from `CachingCompiler` (by way of `BaseHtmlCompiler`), but it's just a private member of the `StaticHtmlCompiler` class, so if you're using `StaticHtmlCompiler` when registering your compiler plugin, [this code](https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/tools/isobuild/build-plugin.js#L42-L49) won't be able to call `setDiskCacheDirectory`.
