### ISSUE TITLE
[1.8] Error: Cannot find module '@babel/runtime/helpers/taggedTemplateLiteral'

### ISSUE THREAD

**Issue by timothyarmes** [meteor/meteor#10269]
I'm unable to get dynamic imports to work in --production mode (everything works under development).

The issues started with Meteor 1.7 (despite pinning the babel runtime to beta 55). I've now upgraded to Meteor 1.8 and the latest version of babel, but the issues persist:

````
Error: ENOENT: no such file or directory, open '/Users/.../.meteor/local/build/programs/web.browser/dynamic/node_modules/@babel/runtime/helpers/taggedTemplateLiteralLoose.js'
W20181011-12:28:21.873(2)? (STDERR)     at Object.fs.openSync (fs.js:646:18)
W20181011-12:28:21.874(2)? (STDERR)     at fs.readFileSync (fs.js:551:33)
W20181011-12:28:21.874(2)? (STDERR)     at read (packages/dynamic-import.js:214:29)
W20181011-12:28:21.874(2)? (STDERR)     at walk (packages/dynamic-import.js:165:14)
W20181011-12:28:21.874(2)? (STDERR)     at Object.keys.forEach.name (packages/dynamic-import.js:172:22)
W20181011-12:28:21.875(2)? (STDERR)     at Array.forEach (<anonymous>)
W20181011-12:28:21.875(2)? (STDERR)     at walk (packages/dynamic-import.js:170:23)
W20181011-12:28:21.875(2)? (STDERR)     at Object.keys.forEach.name (packages/dynamic-import.js:172:22)
W20181011-12:28:21.875(2)? (STDERR)     at Array.forEach (<anonymous>)
W20181011-12:28:21.875(2)? (STDERR)     at walk (packages/dynamic-import.js:170:23)
W20181011-12:28:21.875(2)? (STDERR)     at Object.keys.forEach.name (packages/dynamic-import.js:172:22)
W20181011-12:28:21.876(2)? (STDERR)     at Array.forEach (<anonymous>)
W20181011-12:28:21.876(2)? (STDERR)     at walk (packages/dynamic-import.js:170:23)
W20181011-12:28:21.876(2)? (STDERR)     at Object.keys.forEach.name (packages/dynamic-import.js:172:22)
W20181011-12:28:21.876(2)? (STDERR)     at Array.forEach (<anonymous>)
W20181011-12:28:21.876(2)? (STDERR)     at walk (packages/dynamic-import.js:170:23)
W20181011-12:28:21.876(2)? (STDERR)     at Object.keys.forEach.name (packages/dynamic-import.js:172:22)
W20181011-12:28:21.877(2)? (STDERR)     at Array.forEach (<anonymous>)
W20181011-12:28:21.877(2)? (STDERR)     at walk (packages/dynamic-import.js:170:23)
W20181011-12:28:21.877(2)? (STDERR)     at readTree (packages/dynamic-import.js:193:10)
W20181011-12:28:21.877(2)? (STDERR)     at IncomingMessage.request.on (packages/dynamic-import.js:101:37)
W20181011-12:28:21.877(2)? (STDERR)     at emitNone (events.js:106:13)
````

````
  "devDependencies": {
    "@babel/core": "^7.1.2",
    "babel-eslint": "^8.2.3",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-react-constant-elements": "^6.23.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.13",
    "babel-preset-meteor": "^7.1.2",
    "babel-preset-react": "^6.24.1",
    "chai": "^4.2.0",
    "dirty-chai": "^2.0.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-import-resolver-meteor": ">=0.4.0",
    "eslint-plugin-class-property": "^1.1.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-meteor": "^4.2.2",
    "eslint-plugin-react": "^7.9.1",
    "jsonlint": "^1.6.3",
    "rimraf": "^2.6.2",
    "stylint": "^1.5.9"
  },
  "dependencies": {
    "@babel/polyfill": "^7.0.0",
    "@babel/runtime": "^7.1.2",
    "@manaflair/redux-batch": "^0.1.0",
    "actual": "^0.4.0",
    "aws-sdk": "^2.260.1",
    "bcrypt": "^1.0.3",
    "body-parser": "^1.18.3",
    "classnames": "^2.2.6",
    "color-js": "^1.0.4",
    "cssnano": "^3.10.0",
    "dedent": "^0.7.0",
    "draft-js": "^0.10.5",
    "element-resize-detector": "^1.1.14",
    "email-regex": "^2.0.0",
    "es6-enum": "^1.1.0",
    "es6-promise": "^4.2.4",
    "express": "^4.16.3",
    "farmhash": "^2.1.0",
    "fast-url-parser": "^1.1.3",
    "file-saver": "^1.3.8",
    "fuse.js": "^3.2.1",
    "get-prefix": "^1.0.0",
    "graceful-fs": "^4.1.11",
    "gridfs-locks": "^1.3.4",
    "helmet": "^3.12.1",
    "html-minifier": "^3.5.16",
    "i18n-iso-countries": "^3.6.3",
    "immutable": "^3.8.2",
    "intercom-client": "^2.10.1",
    "intl": "^1.2.5",
    "iphone-inline-video": "^2.2.2",
    "is-retina": "^1.0.3",
    "knox": "^0.9.2",
    "lodash": "^4.17.10",
    "logatim": "^0.9.0",
    "mailchimp-api-v3": "^1.12.0",
    "mailto-link": "^1.0.0",
    "md5": "^2.2.1",
    "meteor-node-stubs": "^0.4.1",
    "moment": "^2.22.2",
    "mongodb": "^2.2.35",
    "node-holidayapi": "^1.0.2",
    "numeral": "^2.0.6",
    "object-squish": "^1.1.0",
    "paginator": "^1.0.0",
    "papaparse": "^4.5.0",
    "path-parse": "^1.0.5",
    "pino": "^4.17.3",
    "postcss-flexbugs-fixes": "^3.3.1",
    "postcss-normalize": "^4.0.0",
    "prop-types": "^15.6.2",
    "proxy-addr": "^2.0.3",
    "react": "^16.5.2",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^16.5.2",
    "react-dom-factories": "^1.0.2",
    "react-dropzone": "^4.2.11",
    "react-flip-move": "^3.0.2",
    "react-fontawesome": "^1.6.1",
    "react-ga": "^2.5.3",
    "react-helmet": "^5.2.0",
    "react-input-mask": "^1.2.2",
    "react-input-range": "^1.3.0",
    "react-intercom": "^1.0.14",
    "react-intl": "^2.4.0",
    "react-intl-redux": "^0.7.0",
    "react-loadable": "^5.4.0",
    "react-motion": "^0.5.2",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.3.1",
    "react-s-alert": "^1.4.1",
    "react-share": "^2.2.0",
    "react-stonecutter": "^0.3.9",
    "react-stripe-elements": "^2.0.0",
    "react-waypoint": "^8.0.2",
    "receptacle": "^1.3.2",
    "redux": "^3.7.2",
    "redux-form": "^5.3.6",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.3.0",
    "request": "^2.87.0",
    "sendgrid": "^5.2.3",
    "serialize-javascript": "^1.5.0",
    "simpl-schema": "^1.5.0",
    "sitemap": "^1.13.0",
    "stream-to-string": "^1.1.0",
    "stripe": "^5.10.0",
    "url-pattern": "^1.0.3",
    "useragent": "^2.3.0",
    "victory-pie": "^14.0.2",
    "web-animations-js": "^2.3.1"
  },
````

**Comment by benjamn** [comment]
What does the code look like where the `@babel/runtime/helpers/taggedTemplateLiteralLoose` import happens? Note that Babel generates the import during compilation, thanks to `@babel/plugin-transform-runtime`, so I realize you are (almost certainly) not importing that module yourself.

**Comment by timothyarmes** [comment]
Hi,

The code in question is in a Meteor method, that's dynamically imported on the client side:

````
export const updateOwnReservationCollect = new ValidatedMethod({
    ....
    if (Meteor.isServer) {
        const text = decent`
          blah blah
        `;
    }
    ....
````

The use for the tagged template litteral breaks my code in production mode. I've stopped doing it that way to avoid the problem.

I tried to create a minimal product to replicate the issue, but it worked fine, so the cause is more subtle than I'd hoped.

Tim

**Comment by benjamn** [comment]
Do you have any other tagged template literals in your code? I'm guessing the build system is getting confused about whether this module is statically bundled or only dynamic.

One other thing you can check is whether the `@babel/runtime/helpers/taggedTemplateLiteralLoose.js` module appears in the static JS bundle. I think the easiest way is to open up the monolithic `<hash>.js` file in production, in Chrome DevTools, then hit the `{}` button to auto-format the minified code, and then search for the string `taggedTemplateLiteralLoose.js":` (which should not have been minified). If you see a `function(...){...}` wrapper immediately after that, then the module is getting statically bundled. If you see an array instead, then it's a dynamic module.

**Comment by timothyarmes** [comment]
It was actually the only use of a tagged template literal in the code base, so I just converted it to a function instead.
