### ISSUE TITLE
Startup error after upgrading to meteor 1.8

### ISSUE THREAD

**Issue by peterolson** [meteor/meteor#10278]
Today I upgraded from Meteor 1.7.1 to 1.8 on Windows 10. I can start my app fine by running `meteor`, but once I edit a file and save it I get this error message:

```
=> Meteor server restarted
I20181013-17:16:48.076(-5)? Exception from task { Error: ENOENT: no such file or directory, open 'D:\Projects\Chinese\app\.meteor\local\build\programs\web.browser.legacy\head.html'
I20181013-17:16:48.110(-5)?   errno: -4058,
I20181013-17:16:48.111(-5)?   code: 'ENOENT',
I20181013-17:16:48.111(-5)?   syscall: 'open',
I20181013-17:16:48.111(-5)?   path: 'D:\\Projects\\Chinese\\app\\.meteor\\local\\build\\programs\\web.browser.legacy\\head.html' }
=> Errors prevented startup:

   While running post-startup callbacks:
   error: ENOENT: no such file or directory, open 'D:\Projects\Chinese\app\.meteor\local\build\programs\web.browser.legacy\head.html'

=> Your application has errors. Waiting for file change.
```

I tried manually putting in the `web.browser.legacy\head.html` file, but it doesn't help anything. If I edit and save again, I get this error:

```
=> Modified -- restarting.
C:\Users\Peter\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EBUSY: resource busy or locked, rmdir 'D:\Projects\Chinese\app\.meteor\local\build\programs\server'
 => awaited here:
    at Promise.await (C:\Users\Peter\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at Object.files.rm_recursive.path [as rm_recursive] (C:\tools\fs\files.js:325:7)
    at Builder.abort (C:\tools\isobuild\builder.js:778:11)
    at C:\tools\isobuild\bundler.js:2972:13
    at C:\tools\isobuild\bundler.js:3281:22
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:3096:31)
    at files.withCache (C:\tools\isobuild\bundler.js:3041:32)
    at Object.withCache (C:\tools\fs\files.js:1712:12)
    at Object.bundle (C:\tools\isobuild\bundler.js:3041:16)
    at Profile.run (C:\tools\runners\run-app.js:569:24)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:568:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:610:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:908:28)
    at C:\tools\runners\run-app.js:398:12
```

**Comment by benjamn** [comment]
If you don't mind clearing your development database, can you try running `meteor reset` to see if that helps?

**Comment by peterolson** [comment]
Thanks, that seems to be working
