### ISSUE TITLE
[Meteor 1.8] Less package - missing variable - hard crash

### ISSUE THREAD

**Issue by Wade-BuildOtto** [meteor/meteor#10285]
If any less variable in use is missing, meteor hard crashes. 1.7 handled it more gracefully with errors.

**Comment by napei** [comment]
Can you provide an example? I'm not getting a _hard_ crash just a stopped build with errors.

When I run less in 1.7, I get the following

```
[[[[[ ~/testapp ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While processing files with less (for target web.browser):
   client/main.less:11:9: variable @test-variable-1234 is undefined

   While processing files with less (for target web.browser.legacy):
   client/main.less:11:9: variable @test-variable-1234 is undefined

=> Your application has errors. Waiting for file change.
```

When run in 1.8, I get the following.

```
[[[[[ ~/testapp ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While processing files with less (for target web.browser):
   client/main.less:11:9: variable @test-variable-1234 is undefined
   error: variable @test-variable-1234 is undefined

   While processing files with less (for target web.browser.legacy):
   client/main.less:11:9: variable @test-variable-1234 is undefined
   error: variable @test-variable-1234 is undefined

=> Your application has errors. Waiting for file change.
```

**Comment by Wade-BuildOtto** [comment]
I am using the updated folder structure to import the less sheet via an imported index file, its not directly in the client: https://guide.meteor.com/structure.html

I am importing it via 
 - imports/ui/pages/index.js > import '/imports/ui/stylesheets/style.less';

error: 
/Users/$name/.meteor/packages/meteor-tool/.1.8.0.kreylv.0z31++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
undefined
....

**Comment by napei** [comment]
@benjamn I must admit, I don't know squat about meteor internals I'm just investigative.

For the less package, under `compile-less.js:97`, it appears that the e.message is somehow undefined once it gets to its destination, however when I re-throw the `e` object wrapped in an `Error()` constructor the stack trace shows the rest of the trace like it should, with the last call being inside `less.render` which makes sense. And the correct error message is shown instead of `undefined`. Maybe something to do with the change to promises? I don't know, like I said, I'm new to forking meteor. Just thought I'd add my 2 cents. :)

```
...
    }, e => {
      throw Error(e);
      // inputFile.error({
      //   message: e.message,
      //   sourcePath: decodeFilePath(e.filename),
      //   line: e.line,
      //   column: e.column
      // });

      return null;
    }); 

```

New console output:

```
=> Running Meteor from a checkout -- overrides project version (Meteor 1.8)
[[[[[ ~/testapp ]]]]]

=> Started proxy.

Changes to your project's package version selections:

deps    removed from your project
jquery  upgraded from 1.11.11 to 1.12.1

/home/napei/src/meteor/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Error: variable @test-variable-1234 is undefined
    at less.render.then.e (packages/compileLessBatch/plugin/compile-less.js:98:13)
    at /home/napei/src/meteor/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/home/napei/src/meteor/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
    at getResult (packages/caching-compiler/multi-file-caching-compiler.js:113:13)
    at Promise.asyncApply (packages/compileLessBatch/plugin/compile-less.js:51:28)
    at /home/napei/src/meteor/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/home/napei/src/meteor/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at CssOutputResource.finalize (/tools/isobuild/compiler-plugin.js:891:7)
    at CssOutputResource.hasPendingErrors (/tools/isobuild/compiler-plugin.js:918:10)
    at CssOutputResource._get (/tools/isobuild/compiler-plugin.js:949:14)
    at CssOutputResource.get data [as data] (/tools/isobuild/compiler-plugin.js:933:28)
    at jsResource.addJavaScript (/tools/isobuild/compiler-plugin.js:731:29)
    at /home/napei/src/meteor/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/home/napei/src/meteor/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at JsOutputResource.finalize (/tools/isobuild/compiler-plugin.js:891:7)
    at JsOutputResource.hasPendingErrors (/tools/isobuild/compiler-plugin.js:918:10)
    at JsOutputResource.reportPendingErrors (/tools/isobuild/compiler-plugin.js:923:14)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:849:14)
    at each (/tools/isobuild/import-scanner.js:907:14)
    at _.each._.forEach (/home/napei/src/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:871:5)
    at each (/tools/isobuild/import-scanner.js:907:14)
    at _.each._.forEach (/home/napei/src/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:871:5)
    at outputFiles.forEach.file (/tools/isobuild/import-scanner.js:529:14)
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:527:22)
    at sourceBatches.forEach.batch (/tools/isobuild/compiler-plugin.js:1287:17)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1255:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1114:8)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:841:12)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3115:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3266:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3220:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3096:31)
    at files.withCache (/tools/isobuild/bundler.js:3041:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3041:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-app.js:908:28)
    at /tools/runners/run-app.js:398:12
```
