### ISSUE TITLE
[1.8] Error: key $set must not start with '$'

### ISSUE THREAD

**Issue by ashish979** [meteor/meteor#10311]
Hi 

I just upgraded my app from 1.7.0.1 to 1.8 and I am getting the following error:

```
 Error: key $set must not start with '$'
  at serializeInto (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:912:19)
  at serializeObject (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:348:18)
  at serializeInto (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:938:17)
  at serializeObject (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:348:18)
  at serializeInto (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:938:17)
  at serializeObject (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:348:18)
  at serializeInto (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:728:17)
  at serializeObject (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:348:18)
  at serializeInto (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/parser/serializer.js:938:17)
  at BSON.serialize (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/bson.js:63:28)
  at Query.toBin (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/commands.js:146:25)
  at serializeCommands (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:1045:43)
  at Pool.write (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:1261:3)
  at executeWrite (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:147:10)
  at WireProtocol.insert (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:158:3)
  at Server.insert (/Users/home/.meteor/packages/npm-mongo/.3.1.1.1r27b0h.e974++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/topologies/server.js:815:35)
```

I am passing the modifier from one file to another for an update query.
So, my method looks like this:
```
run: ({_id, modifier})->
    Collection.update({_id: _id}, modifier)
```
Here modifier is in the below format:
```
{ $set: { name: 'John Doe' } }
```
Prior to 1.8, everything was working fine. Any idea why this is happening?

**Comment by pmcochrane** [comment]
Try putting the $set in quotes to see if it makes any difference. I have had issues in the past with javascript array not liking using a property name beginning with $.

My other suggestion would be to move the $set to the update line and only pass the name object as the modifier parameter

**Comment by ashish979** [comment]
Hi @pmcochrane 
Thanks for the prompt reply. 
I have already tried putting $set in quotes but still the same error.
The send suggestion that you gave actually works but then this was working prior to 1.8 update. I am not sure if we should do that because a modifier can be anything not just $set. For example, $push, $unset etc are valid modifiers for an update query.

**Comment by klaussner** [comment]
@ashish979 Could you please provide a reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor))?

**Comment by ashish979** [comment]
Sorry guys, we found the bug. It was something related to our code.

**Comment by vladbalan** [comment]
Hey @ashish979 ! I know it's almost a year later, but do you recall what the bug was in your case? I'm getting a similar error, but in my case it's related to `$regex`

**Comment by ashish979** [comment]
Hi @vladbalan 

It was a bug in our code where we were using a key in modifier as $set due to wrong formatting. It was not due to meteor.
