### ISSUE TITLE
[1.8.1-beta.3] Exception while invoking method 'login'; TypeError: DiffSequence.diffMaps is not a function

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#10320]
Version showing the problem: 1.8.1-beta.3
Last version without problem: 1.8.1-beta.2

Stack trace
```
===== message ===== Exception while invoking method 'login'
===== stack ===== TypeError: DiffSequence.diffMaps is not a function
    at Session._diffCollectionViews (packages/ddp-server/livedata_server.js:762:18)
    at packages/ddp-server/livedata_server.js:842:12
    at Object.Meteor._noYieldsAllowed (packages/meteor.js:848:12)
    at Session._setUserId (packages/ddp-server/livedata_server.js:840:12)
    at MethodInvocation.setUserId [as _setUserId] (packages/ddp-server/livedata_server.js:677:14)
    at MethodInvocation.setUserId (packages/ddp-common/method_invocation.js:92:10)
    at AccountsServer._loginUser (packages/accounts-base/accounts_server.js:287:22)
    at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:342:17)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
(node:20075) UnhandledPromiseRejectionWarning: TypeError: CreateListFromArrayLike called on non-object
    at Object._debug (imports/startup/server/error.js:37:32)
    at wrapInternalException (packages/ddp-server/livedata_server.js:1741:12)
    at promise.then.exception (packages/ddp-server/livedata_server.js:745:25)
    at /home/rj/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
(node:20075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20075) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Reproduction:
https://github.com/rj-david/meteor-issue-10320

**Comment by klaussner** [comment]
Could you please provide a reproduction (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor))?

**Comment by rj-david** [comment]
Here is the reproduction: https://github.com/rj-david/meteor-issue-10320

**Comment by klaussner** [comment]
Thanks, @rj-david. This issue could be related to the changes I made in #10238. However, the login works if I run your reproduction with a `devel` checkout of Meteor (903bdea790a9924692728fc8543c5965fb62a87c). :thinking:

**Comment by rj-david** [comment]
@klaussner, I checked out that commit and got the same error

I also checked out the HEAD of devel and also got the same error

**Comment by rj-david** [comment]
Ok, I might be running it wrong. I have meteor checked out on the same folder level as my reproduction. Is it right that I executed my reproduction using the following:

`../meteor/meteor npm run start`

Other things that I need to consider to ensure that I am running from the checked out code instead of the installed meteor?

**Comment by klaussner** [comment]
I think that's right, but I just tried it again and it works with my Meteor checkout: https://streamable.com/6icep.

**Comment by Antoine-O** [comment]
My stacktrace if it helps : 

    Exception while invoking method 'login' TypeError: DiffSequence.diffMaps is not a function
        at Session._diffCollectionViews (packages/ddp-server/livedata_server.js:762:18)
        at packages/ddp-server/livedata_server.js:842:12
        at Object.Meteor._noYieldsAllowed (packages\meteor.js:848:12)
        at Session._setUserId (packages/ddp-server/livedata_server.js:840:12)
        at MethodInvocation.setUserId [as _setUserId] (packages/ddp-server/livedata_server.js:677:14)
        at MethodInvocation.setUserId (packages/ddp-common/method_invocation.js:92:10)
        at AccountsServer._loginUser (packages/accounts-base/accounts_server.js:287:22)
        at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:342:17)
        at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)
        at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
        at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
        at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1304:12)
        at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
        at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1304:12)
        at Promise (packages/ddp-server/livedata_server.js:715:46)
        at new Promise (<anonymous>)

**Comment by rj-david** [comment]
Thanks, @Antoine-O.

@klaussner, running the npm script called the installed meteor. Sorry, my fault.

I can confirm that the tagged beta.3 is running without problems. There might be a problem when creating the build for download. Any suggestion how can we go on figuring this out?

**Comment by Antoine-O** [comment]
I have this issue in dev (windows) and production (docker with linux), rollback to beta.2 fixed it. Waiting for beta 4 ;)
