### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by CaptainN** [meteor/meteor#10322]
I have been having trouble with slowness on Windows - looks like it may be a memory leak. It looks like it's a node or Meteor problem and not something in my code, but I'm not 100% certain. Here is the crash message and a referenced log file:

```
=> Meteor server restarted
   Building the application                  -
<--- Last few GCs --->

[780:00000238D06C65F0] 30119956 ms: Mark-sweep 1314.6 (1440.7) -> 1314.5 (1440.7) MB, 1359.0 / 0.1 ms  allocation failure GC in old space requested
[780:00000238D06C65F0] 30121770 ms: Mark-sweep 1314.5 (1440.7) -> 1314.5 (1425.7) MB, 1813.1 / 0.1 ms  last resort GC in old space requested
[780:00000238D06C65F0] 30123638 ms: Mark-sweep 1314.5 (1425.7) -> 1314.5 (1425.2) MB, 1868.7 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000118C33A5879 <JSObject>
    1: write [C:\Users\Kevin\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\tools\isobuild\builder.js:~298] [pc=00000200920CEB74](this=0000007132382271 <Builder map = 000002BF680E3941>,/* anonymous */=0000016430561119 <String[75]: dynamic/node_modules/@material-ui/icons/SubdirectoryArrowLeftTwoTone.js.map>,/* anonymous */=0000016430561049 <Object map = 000002BF680E3DB9>)...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFixedArray
 5: v8::internal::Dictionary<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::AtPut
 6: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::IsKey
 7: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::IsKey
 8: v8::internal::LookupIterator::ApplyTransitionToDataProperty
 9: v8::internal::JSReceiver::class_name
10: v8::internal::SourcePositionTableIterator::Advance
11: v8::internal::SourcePositionTableIterator::Advance
12: 0000020090F843C1
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! pixstori-meteor@ start: `meteor run --settings development.settings.json`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the pixstori-meteor@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kevin\AppData\Roaming\npm-cache\_logs\2018-11-06T05_45_16_920Z-debug.log
```

debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Kevin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Kevin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pixstori-meteor@~prestart: pixstori-meteor@
6 info lifecycle pixstori-meteor@~start: pixstori-meteor@
7 verbose lifecycle pixstori-meteor@~start: unsafe-perm in lifecycle true
8 verbose lifecycle pixstori-meteor@~start: PATH: C:\Users\Kevin\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Kevin\repos\pixstori\node_modules\.bin;C:\Users\Kevin\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\bin;C:\Users\Kevin\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64;C:\Users\Kevin\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\tools\php72;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Kevin\AppData\Local\Microsoft\WindowsApps;C:\Users\Kevin\AppData\Local\.meteor;;C:\Users\Kevin\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Users\Kevin\AppData\Local\Yarn\bin;C:\Program Files\Oracle\VirtualBox;C:\Users\Kevin\AppData\Roaming\npm
9 verbose lifecycle pixstori-meteor@~start: CWD: C:\Users\Kevin\repos\pixstori
10 silly lifecycle pixstori-meteor@~start: Args: [ '/d /s /c',
10 silly lifecycle   'meteor run --settings development.settings.json' ]
11 silly lifecycle pixstori-meteor@~start: Returned: code: 3  signal: null
12 info lifecycle pixstori-meteor@~start: Failed to exec start script
13 verbose stack Error: pixstori-meteor@ start: `meteor run --settings development.settings.json`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Kevin\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Kevin\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid pixstori-meteor@
15 verbose cwd C:\Users\Kevin\repos\pixstori
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Users\\Kevin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe" "C:\\Users\\Kevin\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0\\mt-os.windows.x86_64\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.4
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 3
22 error pixstori-meteor@ start: `meteor run --settings development.settings.json`
22 error Exit status 3
23 error Failed at the pixstori-meteor@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]
```

**Comment by MJO9** [comment]
@CaptainN  

I stooped using meteor on windows because it is way slower than anything else.

Try installing Ubuntu subsystem on your window 10 machine and use meteor from there.

**Comment by CaptainN** [comment]
Meteor 1.8.1 is no longer terrible on Windows, and I solved this crash a while back. I'll close this issue now
