### ISSUE TITLE
Meteor 1.8 does not show 'Errors prevented startup:' any more, just `Error: Cannot find module` 

### ISSUE THREAD

**Issue by elisei-timofte** [meteor/meteor#10353]
version: Meteor 1.8
os: OSX 10.13 High Sierra
last working version: Meteor 1.7.0.5

In file members.coffee I have this query:
`peopleIds = Members.find({personId: member.personId, {fields: personId: 1}}).map (m) -> m.personId`, but it has a small bug; there is a missing curly brace.

It should be:
`peopleIds = Members.find({personId: member.personId}, {fields: personId: 1}).map (m) -> m.personId`

In older meteor version I would get in the terminal something like this:

    => Errors prevented startup:                  
       
       While building for web.browser:
       app/imports/collections/members.coffee:98:77: unexpected }
       
       While building for web.browser.legacy:
       app/imports/collections/members.coffee:98:77: unexpected }
       
       While building for os.osx.x86_64:
       app/imports/collections/members.coffee:98:77: unexpected }
       
    => Your application has errors. Waiting for file change.

    
while in 1.8 I get this unhandy message:

    /Users/user/.meteor/packages/meteor-tool/.1.8.0.1cwb5s.iak48++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
    						throw(ex);
    						^
    
    Error: Cannot find module '/app/imports/collections/members'
       at makeMissingError (packages/modules-runtime.js:208:12)
       at Module.require (packages/modules-runtime.js:227:17)
       at require (packages/modules-runtime.js:244:21)
       at groups.coffee (app/imports/collections/groups.coffee:1:1)
       at fileEvaluate (packages/modules-runtime.js:322:7)
       at Module.require (packages/modules-runtime.js:224:14)
       at require (packages/modules-runtime.js:244:21)
       at groups_methods.coffee (app/imports/methods/groups_methods.coffee:1:1)
       at fileEvaluate (packages/modules-runtime.js:322:7)
       at Module.require (packages/modules-runtime.js:224:14)
       at require (packages/modules-runtime.js:244:21)
       at index.coffee (app/imports/methods/index.coffee:1:1)
       at fileEvaluate (packages/modules-runtime.js:322:7)
       at Module.require (packages/modules-runtime.js:224:14)
       at require (packages/modules-runtime.js:244:21)
       at helpers_test.coffee (app/server/lib/server_tests/helpers_test.coffee:1:1)
    => Exited with code: 1
    => Your application is crashing. Waiting for file change.
    

This makes my development process very difficult. Is there a solution for this?

Thanks!

**Comment by benjamn** [comment]
What version of `coffeescript` and `coffeescript-compiler` are you using? Check your `.meteor/versions` file if unsure.
