### ISSUE TITLE
Fibers version in meteor bundle can't be installed on RHEL

### ISSUE THREAD

**Issue by cwohlman** [meteor/meteor#10371]
I'm trying to deploy a meteor app on RHEL following the instructions in the bundle readme, unfortunately the npm install step breaks when installing fibers (I don't have build tools and don't want to install them on this machine). As far as I can tell prebuilt binaries for fibers don't exist for node 8 on my deployment system (a binary exists, but npm install reports `Problem with the binary; manual build incoming`).

I was able to install fibers version 3.1.1 just fine, the prebuilt binaries were available and worked on my system, also this appears to be the recommended action by the package author. (The [release](https://github.com/laverdet/node-fibers/compare/4786aef736ab8285d29e9476e3615abbd3935d37...a9bb8099b20251d20f099229fec6aa49891f5be0) appears to be a major version bump only because it no longer supports older node versions such 6 and below, the author [here](https://github.com/laverdet/node-fibers/issues/378#issuecomment-409077081) mentions that he pushed precompiled binaries for node 10, I assume that he also pushed additional binaries for node 8 at the same time).

Since meteor currently runs node 8 I think it would be good to update to fibers version 3.1.1

Am I missing something?

Meteor version: METEOR@1.8.0.1 (I am not running the meteor tool, only a production bundle)
Node version: 8.11.4
OS: Red hat enterprise linux 7.6 (on aws)
Reproduction:
```sh
# on RHEL 7.6 with meteor installed for convenience of reproduction, steps could be repeated by building the bundle on a local machine and then installing the correct version of node & npm on the target machine
meteor create reproduction 
cd reproduction
meteor build --directory ../build 
cd ../build/bundle/programs/server 
meteor npm i
```
Output (for last step only):
```
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.

> fibers@2.0.0 install /home/ec2-user/build/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/ec2-user/build/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
make: g++: Command not found
make: *** [Release/obj.target/fibers/src/fibers.o] Error 127
make: Leaving directory `/home/ec2-user/build/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.meteor/packages/meteor-tool/.1.8.0_1.1fqze6b.nyph++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-957.1.3.el7.x86_64
gyp ERR! command "/home/ec2-user/.meteor/packages/meteor-tool/.1.8.0_1.1fqze6b.nyph++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/ec2-user/.meteor/packages/meteor-tool/.1.8.0_1.1fqze6b.nyph++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/ec2-user/build/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-12-10T18_39_38_282Z-debug.log
```
Expected Output (for last step, obtained by modifying fibers version to 3.1.1)
```

**Comment by georgyberdyshev** [comment]
Hello @cwohlman,

you are missing the g++ compiler:
`make: g++: Command not found`

You can run the following command to install g++:
`sudo yum install gcc-c++`

I have tested your reproduction steps and after install g++, it works without any issues on CentOS 7.6

Georgy

**Comment by abernix** [comment]
@cwohlman Thanks for reporting this! Meteor 1.8.1 includes the updates to `fibers@3`.  Do you mind giving that a try and see if it resolves your issue?  #10248 should have the details you need to get up and running on the latest pre-release.

**Comment by benjamn** [comment]
@cwohlman Version 1.8.1-beta.10 is now using `fibers@3.1.1`, for what it's worth. You can update your app by running `meteor update --release 1.8.1-beta.10`.

**Comment by imhazige** [comment]
I have the same problem when deploy to heroku.

meteor build --directory ../build 
push the bundle to the heroku git
add a package.json under the bundle folder

  "scripts": {
    "preinstall": "(cd programs/server && npm install)",
    "start": "node main.js"
  }

then when run the preinstall hook, build failed.

here is the build log:
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.13.0...
       Using default npm version: 6.12.0
       
-----> Restoring cache
       - node_modules (not cached - skipping)
       
-----> Installing dependencies
       Installing node modules (package.json)
       
       > xxx@0.0.1 preinstall /tmp/build_6c6f112d01a3c4d4aef329412cc15363
       > (cd programs/server && npm install)
       
       
       > fibers@3.1.1 install /tmp/build_6c6f112d01a3c4d4aef329412cc15363/programs/server/node_modules/fibers
       > node build.js || nodejs build.js
       
       make: Entering directory '/tmp/build_6c6f112d01a3c4d4aef329412cc15363/programs/server/node_modules/fibers/build'
         CXX(target) Release/obj.target/fibers/src/fibers.o
       ../src/fibers.cc:68:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
         Handle<String> NewLatin1String(Isolate* isolate, const char* string) {
         ^~~~~~
         rand_r
       ../src/fibers.cc:72:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
         Handle<String> NewLatin1Symbol(Isolate* isolate, const char* string) {
         ^~~~~~
         rand_r
