### ISSUE TITLE
Error: No metadata files found for isopack at: /C/Users/kashem/AppData/Local/.meteor/packages/coffeescript/1.0.17

### ISSUE THREAD

**Issue by mdkshuvo** [meteor/meteor#10387]
I have got the error to run meteor project on my PC. What is the solution? Please let me inform.

![problem](https://user-images.githubusercontent.com/30826181/50326971-300c2600-0517-11e9-89c6-df9319e39687.jpg)
Error: No metadata files found for isopack at: /C/Users/kashem/AppData/Local/.me
teor/packages/coffeescript/1.0.17
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:818:13)
    at _.each (C:\tools\packaging\tropohouse.js:521:21)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\kashem\AppData\Local\.meteor\packages
\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\u
nderscore.js:79:11)
    at buildmessage.enterJob (C:\tools\packaging\tropohouse.js:520:13)
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at enterJobAsync.then (C:\tools\utils\buildmessage.js:572:21)
    at C:\Users\kashem\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.wi
ndows.x86_64\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Promise.await (C:\Users\kashem\AppData\Local\.meteor\packages\meteor-tool
\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_s
erver.js:60:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:567:10)
    at exports.Tropohouse.downloadPackagesMissingFromMap (C:\tools\packaging\tro
pohouse.js:609:18)
    at C:\tools\project-context.js:814:25
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:813:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalo
g\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:812:
13)
    at C:\tools\project-context.js:285:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:275:18
)
    at Profile.run (C:\tools\project-context.js:267:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:266:13
)
    at C:\tools\runners\run-app.js:554:29
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89
:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundleApp (C:\tools\runners\run-app.js:553:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:622:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12_

**Comment by aliogaili** [comment]
You might try the [Meteor forum](https://forums.meteor.com/) first? you might get help there.

**Comment by benjamn** [comment]
If you just delete the `/C/Users/kashem/AppData/Local/.me
teor/packages/coffeescript/` directory, Meteor should have no trouble recreating it. You might also try updating to the latest version of CoffeeScript while you're at it (2.3.2_1).

**Comment by mdkshuvo** [comment]
> 
> 
> If you just delete the `/C/Users/kashem/AppData/Local/.me teor/packages/coffeescript/` directory, Meteor should have no trouble recreating it. You might also try updating to the latest version of CoffeeScript while you're at it (2.3.2_1).

System can't delete the coffeescript file.
