### ISSUE TITLE
 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#10391]
I just got this issue in my development application: (Meteor 1.8 + Angularjs) (System Nodejs Version:  nodejs -v
v0.10.25)

```
=> Started proxy.                             
[BABEL] Note: The code generator has deoptimised the styling of "/server/classes/serverhelperclass.js" as it exceeds the max of "100KB".
=> Started MongoDB.                           
=> Started your app.

=> App running at: http://localhost:3000

I20181226-11:32:25.820(1)? <--- Last few GCs --->
I20181226-11:32:25.821(1)?
I20181226-11:32:25.821(1)? [28272:0x4b30aa0] 149094585 ms: Mark-sweep 217.1 (238.3) -> 216.9 (238.3) MB, 407.7 / 0.7 ms  allocation failure GC in old space requested
I20181226-11:32:25.821(1)? [28272:0x4b30aa0] 149094992 ms: Mark-sweep 216.9 (238.3) -> 216.9 (238.3) MB, 406.7 / 0.7 ms  last resort GC in old space requested
I20181226-11:32:25.822(1)? [28272:0x4b30aa0] 149095399 ms: Mark-sweep 216.9 (238.3) -> 216.9 (238.3) MB, 407.4 / 0.6 ms  last resort GC in old space requested
I20181226-11:32:25.828(1)?
I20181226-11:32:25.829(1)?
I20181226-11:32:25.829(1)? <--- JS stacktrace --->
I20181226-11:32:25.829(1)?
W20181226-11:32:25.830(1)? (STDERR) FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
W20181226-11:32:25.854(1)? (STDERR)  1: node::Abort() [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.855(1)? (STDERR)  2: 0x8c21ec [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.857(1)? (STDERR)  3: v8::Utils::ReportOOMFailure(char const*, bool) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.858(1)? (STDERR)  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.860(1)? (STDERR)  5: v8::internal::Handle<v8::internal::JSFunction> v8::internal::Factory::New<v8::internal::JSFunction>(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationSpace) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.862(1)? (STDERR)  6: v8::internal::Factory::NewFunction(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::PretenureFlag) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.863(1)? (STDERR)  7: v8::internal::Factory::NewFunctionFromSharedFunctionInfo(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::PretenureFlag) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.865(1)? (STDERR)  8: v8::UnboundScript::BindToCurrentContext() [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.866(1)? (STDERR)  9: v8::ScriptCompiler::Compile(v8::Local<v8::Context>, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.867(1)? (STDERR) 10: v8::Script::Compile(v8::Local<v8::String>, v8::ScriptOrigin*) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node]
W20181226-11:32:25.868(1)? (STDERR) 11: Fiber::RunFiber(void**) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/bin/linux-x64-57/fibers.node]
W20181226-11:32:25.868(1)? (STDERR) 12: Coroutine::trampoline(void*) [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/bin/linux-x64-57/fibers.node]
W20181226-11:32:25.869(1)? (STDERR) 13: 0x72368c7fbfb7 [/home/myusers/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/bin/linux-x64-57/fibers.node]
=> Exited from signal: SIGABRT
=> Meteor server restarted
```

My server got crashed and i had to restart it. Any idea why this occured and any fix for this?

**Comment by pgiani** [comment]
What is your OS ?

**Comment by MartiniHenry1988** [comment]
@pgiani Its Ubuntu 15.10

**Comment by pgiani** [comment]
did you try 
--max-old-space-size=4096

**Comment by pgiani** [comment]
before you star meteor run this command
export TOOL_NODE_FLAGS="--max_old_space_size=4096"

**Comment by MartiniHenry1988** [comment]
@pgiani Alright I will try that and let you know.

**Comment by MartiniHenry1988** [comment]
@pgiani Ok I ran the command and this issue still persists, also now I am getting:

```
W20181227-11:32:23.594(1)? (STDERR) /home/myapp/.meteor/packages/meteor-tool/.1.8.0_1.12cbugr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20181227-11:32:23.596(1)? (STDERR) throw(ex);
W20181227-11:32:23.596(1)? (STDERR) ^
W20181227-11:32:23.597(1)? (STDERR)
W20181227-11:32:23.597(1)? (STDERR) RangeError: Out of memory
W20181227-11:32:23.598(1)? (STDERR) at processNext (packages/ddp-server/livedata_server.js:563:10)
W20181227-11:32:23.598(1)? (STDERR) at unblock (packages/ddp-server/livedata_server.js:550:11)
W20181227-11:32:23.599(1)? (STDERR) at packages/ddp-server/livedata_server.js:562:9
=> Exited with code: 1
=> Meteor server restarted
```

**Comment by klaussner** [comment]
@nelisbijl I understand that errors like this can be frustrating–especially when you are trying to run an official example app–but insulting the maintainers of this project won't help you get your issue resolved. There are many people on this repository and the Meteor forums who are willing to help if you show a constructive and
respectful attitude. Please take a look at Meteor's [Code of Conduct](https://github.com/meteor/meteor/blob/devel/CODE_OF_CONDUCT.md).

Regarding the `Allocation failed` error: I just built the `meteor/todos` app with Meteor 1.7 and 1.8 (after running `meteor update`) and didn't get an error, so this could be related to your system. Can you share your configuration (especially OS and memory), reproduction steps, and the exact error message (with stack trace)? Also, did you try @pgiani's suggestion in https://github.com/meteor/meteor/issues/10391#issuecomment-450002395?

**Comment by MartiniHenry1988** [comment]
@klaussner I tried @pgiani solution, it didnt work for me, its been 3 weeks I migrated to Meteor 1.8 and I have got this error twice. I should add again that I am running my app in development mode.
