### ISSUE TITLE
Galaxy i is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by stolinski** [meteor/meteor#10397]
Issue is only happening on Galaxy. Running production locally is fine. I'm totally lost trying to troubleshoot this.

<img width="1080" alt="screen shot 2018-12-31 at 1 59 32 pm" src="https://user-images.githubusercontent.com/669383/50567668-c35a0e00-0d04-11e9-9624-27bcd53aa268.png">

```
TypeError: i is not a function or its return value is not iterable
  at h(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:121:78195)
  at No(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:89295)
  at pa(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:105112)
  at da(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:105492)
  at Za(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:112155)
  at Xa(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:111535)
  at za(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:110556)
  at ga(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:109454)
  at Object.enqueueForceUpdate(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:74885)
  at t.T.forceUpdate(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:13405)
  at t.i.updateCurrentData(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:277532)
  at Object.next(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:277227)
  at b(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:614366)
  at g(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:614726)
  at e(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:615283)
  at ? (/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:308852)
  at Array.forEach(<anonymous>)
  at Object.next(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:308815)
  at ? (/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:322050)
  at ? (/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:327515)
  at Array.forEach(<anonymous>)
  at ? (/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:327495)
  at Map.forEach(<anonymous>)
  at t.broadcastQueries(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:327402)
  at Object.next(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:328573)
  at b(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:614366)
  at g(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:614726)
  at e(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:615283)
  at ? (/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:620837)
  at Array.forEach(<anonymous>)
  at Object.next(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:620810)
  at b(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:614366)
  at g(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:614726)
  at e(/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:615283)
  at ? (/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:11:676512)
  at ? (/9f61b3a064be4cf4487ccd13e76d6b23da444abc.js:1:8191)
```

Packages used

```
accounts-base@1.4.3
accounts-password@1.5.1
aldeed:collection2-core@2.1.2
allow-deny@1.1.0
apollo@3.0.1
autoupdate@1.5.0
babel-compiler@7.2.3
babel-runtime@1.3.0
base64@1.0.11
binary-heap@1.0.11
blaze-tools@1.0.10
boilerplate-generator@1.6.0
caching-compiler@1.2.1
caching-html-compiler@1.1.3
callback-hook@1.1.0
check@1.3.1
ddp@1.4.0
ddp-client@2.3.3
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.2.0
deps@1.0.12
diff-sequence@1.1.1
dynamic-import@0.5.1
ecmascript@0.12.3
ecmascript-runtime@0.7.0
ecmascript-runtime-client@0.8.0
ecmascript-runtime-server@0.7.1
ejson@1.1.0
email@1.2.3
es5-shim@4.8.0
fetch@0.1.0
gadicohen:robots-txt@0.0.10
gadicohen:sitemaps@0.0.26
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
id-map@1.1.0
inter-process-messaging@0.1.0
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
meteor@1.9.2
meteor-base@1.4.0
minifier-js@2.4.0
minimongo@1.4.5
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modern-browsers@0.1.3
modules@0.13.0
modules-runtime@0.10.3
mongo@1.6.0
mongo-decimal@0.1.0
mongo-dev-server@1.1.0
mongo-id@1.0.7
npm-bcrypt@0.9.3
npm-mongo@3.1.1
ordered-dict@1.1.0
promise@0.11.1
raix:eventemitter@0.1.3
random@1.1.0
rate-limit@1.0.9
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
routepolicy@1.1.0 
server-render@0.3.1
service-configuration@1.0.11
sha@1.0.9
socket-stream-client@0.2.2
spacebars-compiler@1.1.3
srp@1.0.12
standard-minifier-js@2.4.0
static-html@1.2.2
swydo:graphql@0.4.0
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.2
tracker@1.2.0
underscore@1.0.10
webapp@1.7.2
webapp-hashing@1.0.9
```

**Comment by stolinski** [comment]
Seems like it would be a React issue, but the fact that it's only happening on Galaxy and not running prod anywhere else tells me that it's something odd. Any help as to how to troubleshoot this would be appreciated.

**Comment by stolinski** [comment]
Build worked after I ran deploy locally rather than Semaphoreci. I'm really struggling to figure out where this error came from and why Semaphore was the problem here. I've always deployed from Semaphore no problem until right now.
