### ISSUE TITLE
[1.8.1-beta.15] Error While adding platform Android to Cordova project

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#10419]
When running the app in android using Meteor 1.8.1-beta.15, we are encountering this error:

```
%% Prepared android project successfully
=> Errors executing Cordova commands:

   While adding platform Android to Cordova project:
   Error: Unable to graft xml at selector "/manifest/application" from "/home/rj/Projects/Empleyo/empleyo/.meteor/local/cordova-build/platforms/android/app/src/main/res/xml/config.xml" during
   config install
   at ConfigFile_graft_child [as graft_child]
   (/home/rj/.meteor/packages/meteor-tool/.1.8.1-beta.15.hpoatm.0uy0g++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:122:19)
   at PlatformMunger_apply_file_munge [as apply_file_munge]
   (/home/rj/.meteor/packages/meteor-tool/.1.8.1-beta.15.hpoatm.0uy0g++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:81:34)
   at munge_helper
   (/home/rj/.meteor/packages/meteor-tool/.1.8.1-beta.15.hpoatm.0uy0g++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:236:14)
   at PlatformMunger.add_config_changes
   (/home/rj/.meteor/packages/meteor-tool/.1.8.1-beta.15.hpoatm.0uy0g++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:214:12)
   at
   /home/rj/.meteor/packages/meteor-tool/.1.8.1-beta.15.hpoatm.0uy0g++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/prepare.js:130:32
   at _fulfilled (/home/rj/Projects/Empleyo/empleyo/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:834:54)
   at self.promiseDispatch.done (/home/rj/Projects/Empleyo/empleyo/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:863:30)
   at Promise.promise.promiseDispatch (/home/rj/Projects/Empleyo/empleyo/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:796:13)
   at /home/rj/Projects/Empleyo/empleyo/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:604:44
   at runSingle (/home/rj/Projects/Empleyo/empleyo/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:137:13)
   at flush (/home/rj/Projects/Empleyo/empleyo/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:125:13)
   at _combinedTickCallback (internal/process/next_tick.js:132:7)
   at process._tickCallback (internal/process/next_tick.js:181:9)
   => awaited here:
   at Function.Promise.await
   (/home/rj/.meteor/packages/meteor-tool/.1.8.1-beta.15.hpoatm.0uy0g++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at Promise.asyncApply (/tools/cordova/project.js:425:7)
   at
   /home/rj/.meteor/packages/meteor-tool/.1.8.1-beta.15.hpoatm.0uy0g++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
   at Function.Promise.await
   (/home/rj/.meteor/packages/meteor-tool/.1.8.1-beta.15.hpoatm.0uy0g++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:843:14)
   at CordovaProject.addPlatform (/tools/cordova/project.js:421:10)
   at CordovaProject.ensurePlatformsAreSynchronized (/tools/cordova/project.js:452:12)
   at CordovaRunner.checkPlatformsForRunTargets (/tools/cordova/runner.js:26:25)
   at main.captureAndExit (/tools/cli/commands.js:408:23)
   at Object.capture (/tools/utils/buildmessage.js:283:5)
   at Object.main.captureAndExit (/tools/cli/main.js:273:29)
   at prepareCordovaProject (/tools/cli/commands.js:401:12)
   at Command.doRunCommand [as func] (/tools/cli/commands.js:413:5)
   at /tools/cli/main.js:1531:15
```

Did not encounter in Meteor 1.8.1-beta.14

**Comment by menelike** [comment]
I just tested our project against `1.8.1-beta.15` and it works fine. Keep in mind that `1.8.1-beta.15` introduced cordova android 7.1.4 (https://github.com/meteor/meteor/pull/10248/commits/5e26ebb6a9d68cea176869ac3a83121dcee7e925), as there has been a major change from `6.x` to `7.x` plugins may fail, so you should check your plugins for updates.

**Comment by rj-david** [comment]
Thanks for that notice, @menelike. I'll go through our plugins one by one later

**Comment by rj-david** [comment]
Drilled-down the issue to this lines in our `mobile-config.js`

```
// Android adaptive icons
App.appendToConfig(`
<platform name="android">
    <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
        <application android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" xmlns:android="http://schemas.android.com/apk/res/android" />
    </edit-config>
</platform>
`);
```

We are using this to make adaptive icons work for Android. Figuring out how to do this with new version of cordova android

**Comment by rj-david** [comment]
Found the issue with the breaking changes from cordova-android `6.x` to `7.x`
https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

```
<!-- An existing config.xml -->
<edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">

<!-- needs to change to -->
<edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">
```

I encountered a new problem but we can consider this specific issue solved.

**Comment by renish-peerlyst** [comment]
> Found the issue with the breaking changes from cordova-android `6.x` to `7.x`
> https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html
> 
> ```
> 
> <edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">
> 
> 
> <edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">
> ```
> 
> I encountered a new problem but we can consider this specific issue solved.

This works, thanks @rj-david
