### ISSUE TITLE
[1.8] nathantreid:css-modules stylesheets addJavaScript content is not reloaded on change

### ISSUE THREAD

**Issue by nathantreid** [meteor/meteor#10421]
OS: Windows 10 x64

My compiler plugin `nathantreid:css-modules` takes a stylesheet, runs it through CSS modules processing, and use `addJavaScript` to add the result. This works fine in Meteor <= 1.7, but in Meteor 1.8 this stops working properly; it no longer updates the stylesheet properly when only the stylesheet changes, instead requiring an update to a JavaScript file in order to refresh.

The expected behavior is:
1. Make a change to a stylesheet and save the change
2. The updated styles shows up in the browser

The actual behavior is:
1. Make a change to a stylesheet and save the change
2. The stylesheet's JS code is replaced by the Meteor stylesheet code
3. Make a change to a JavaScript file and save the change (for example add a blank line)
4. THe stylesheet is now displayed correctly

Actual code in app.js when it breaks:

```js
/////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                         //
// client/main.m.css                                                                       //
//                                                                                         //
/////////////////////////////////////////////////////////////////////////////////////////////
                                                                                           //
module.exports = require("meteor/modules").addStyles(
  "body {\n  padding: 10px;\n  font-family: sans-serif;\n}\n\n.foo {\n  color: orange;\n}"
);

/////////////////////////////////////////////////////////////////////////////////////////////
```

Code in app.js when it works (after changing a .js file):

```js
////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                    //
// client/main.m.css                                                                                  //
//                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                      //
module.link("./main.m.css.js", { "*": "*+" });

////////////////////////////////////////////////////////////////////////////////////////////////////////

},"main.m.css.js":function(require,exports,module){

////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                    //
// client/main.m.css.js                                                                               //
//                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                      //
var modules;
module.link("meteor/modules", {
"default": function (v) {
modules = v;
}
}, 0);
modules.addStyles("body {\n  padding: 10px;\n  font-family: sans-serif;\n}\n\n._client__main_m__foo {\n  color: green;\n}");
var module1 = module;
module1.export({
"default": function () {
return styles;
},
styles: function () {
return styles;
}
});
var styles = new Proxy({
"foo": "_client__main_m__foo"
}, {
get: function (target, name) {
var ignoredProperties = ['toJSON', 'state', '_isVue', 'render', '@@toStringTag', Symbol.toStringTag];
return name in target ? target[name] : ignoredProperties.indexOf(name) === -1 ? console.warn(name, ': CSS module class not found in client/main.m.css') : undefined;
}
});
exports.__esModule = true;
////////////////////////////////////////////////////////////////////////////////////////////////////////
```

I've narrowed this down to it only occurring when my plugin is built using Meteor 1.8. If I build the plugin using Meteor 1.7 and add it to a Meteor 1.8 app, it functions correctly.

I've published the same version with 1.7 and 1.8 to show the difference: 
`nathantreid:css-modules@3.2.2` uses 1.8 
`nathantreid:css-modules@3.2.2-meteor1.7` uses 1.7

Sample reproduction:
https://github.com/nathantreid/css-modules-125

**Comment by nathantreid** [comment]
I've been looking further into this. In the version compiled on 1.8, there is an additional main.m.css entry being processed in the Meteor `import-scanner.js`, and I'm not sure where it's coming from. This is the trace from where I'm getting the information at the moment:
```
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:887:7)
    at each (C:\tools\isobuild\import-scanner.js:941:5)
    at _.each._.forEach (C:\Users\nathantreid\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22
)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:893:9)
    at outputFiles.forEach.file (C:\tools\isobuild\import-scanner.js:542:11)
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (C:\tools\isobuild\import-scanner.js:536:22)
    at sourceBatches.forEach.batch (C:\tools\isobuild\compiler-plugin.js:1316:9)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:1281:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:1121:8)
    at buildmessage.enterJob (C:\tools\isobuild\bundler.js:847:12)
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:835:18)
    at C:\tools\isobuild\bundler.js:3146:9
    at webArchs.forEach.arch (C:\tools\isobuild\bundler.js:3295:8)
    at Array.forEach (<anonymous>)
    at C:\tools\isobuild\bundler.js:3253:9
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at bundle (C:\tools\isobuild\bundler.js:3127:29)
    at files.withCache (C:\tools\isobuild\bundler.js:3072:17)
    at Object.withCache (C:\tools\fs\files.js:1712:12)
    at Object.bundle (C:\tools\isobuild\bundler.js:3072:1)
    at Profile.run (C:\tools\runners\run-app.js:569:24)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:568:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:610:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:908:28)
    at C:\tools\runners\run-app.js:398:12
```
This is the extra `file` variable in `_scanFile`:
``` js
var data = {...file}
delete data.data;
console.log(JSON.stringify(data, null, 2))

/* output:
{
  "hash": "f4f4199c345583d936c613c2e280a885f0d60ae3",
  "dataString": "module.exports = require(\"meteor/modules\").addStyles(\n  \"body {\\n  padding: 10px;\\n  font-family: sans-serif;\\n}\\n\\n.foo {\\n  color: aquamarine;\\n}\
"\n);\n",
  "type": "js",
  "sourcePath": "client/main.m.css",
  "absModuleId": "/client/main.m.css",
  "servePath": "client/main.m.css",
  "lazy": true,
  "imported": "static",
  "deps": {
    "meteor/modules": {
      "possiblySpurious": false,
      "dynamic": false
    }
  }
*/
``` 

This file entry is being processed by `defaultExtensionHandlers.css` instead of by my plugin. Note that my plugin is also processing the file, but that is a separate entry. This one comes first and apparently overrides the entry from my plugin.

Again, this is an additional entry introduced when building my plugin using Meteor 1.8. With 1.7 there are 2 entries from my plugin calling `addJavaScript` (one for `main.m.css`, which links to `main.m.css.js`; the other for `main.m.css.js`. With 1.8, in addition to those 2 entries there is the entry displayed above.

**Comment by nathantreid** [comment]
Well, after all that digging, it turns out this was an incredibly simple issue - `CachingCompiler.processFilesForTarget` was made async in 1.8, and since I was overriding that method and calling it via `super`, I needed to await the base method. Definitely my fault for not noticing this sooner, but it would have been nice if the `caching-compiler` version had been bumped to v2 to indicate the breaking change.
