### ISSUE TITLE
TypeError: _interopRequireDefault is not a function

### ISSUE THREAD

**Issue by mariusrak** [meteor/meteor#10464]
Hi, I'm getting this error. It seems like a problem with import order.

I have quite complicated use case and I'm not sure how to create minimum repo. So maybe I could use little guidance or help on debugging or at least maybe somebody has some experience with this.

I'm getting an error  on server `TypeError: _interopRequireDefault is not a function`. This happens when i'm including stuff on server. In an `index.js` I'm importing some custom system libraries and at the end there is next import of file `server.js` utilizing `Meteor.startup`. But at the beginning of the file `server.js` is import of configuration file `server_config.js`. In the configuration file, there is imported some stuff from the libraries, some common class `Component.js` which I'm exporting from the initial `index.js`. So there is pretty circular reference 

**index.js** -> server.js -> server_config.js -> **index.js** -> Component.js 

I have tried changing order of imports in the `index.js` but it didn't help. So no matter whether first is import of `server.js` or `Component.js`.

Is there any way how to make this work?
Thanks.

```
W20190223-11:11:16.365(1)? (STDERR) TypeError: _interopRequireDefault is not a function
W20190223-11:11:16.366(1)? (STDERR)     at Component.js (packages\modules.js:378:33)
W20190223-11:11:16.369(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190223-11:11:16.371(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190223-11:11:16.372(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\Márius Rak\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190223-11:11:16.374(1)? (STDERR)     at index.js (packages\modules.js:355:8)
W20190223-11:11:16.376(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190223-11:11:16.377(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190223-11:11:16.378(1)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20190223-11:11:16.379(1)? (STDERR)     at C:\Users\Márius Rak\Desktop\App\.meteor\local\build\programs\server\app\app.js:6484:15
W20190223-11:11:16.380(1)? (STDERR)     at C:\Users\Márius Rak\Desktop\App\.meteor\local\build\programs\server\boot.js:411:36
W20190223-11:11:16.382(1)? (STDERR)     at Array.forEach (<anonymous>)
W20190223-11:11:16.383(1)? (STDERR)     at C:\Users\Márius Rak\Desktop\App\.meteor\local\build\programs\server\boot.js:220:19
W20190223-11:11:16.384(1)? (STDERR)     at C:\Users\Márius Rak\Desktop\App\.meteor\local\build\programs\server\boot.js:471:5
W20190223-11:11:16.390(1)? (STDERR)     at Function.run (C:\Users\Márius Rak\Desktop\App\.meteor\local\build\programs\server\profile.js:510:12)
W20190223-11:11:16.391(1)? (STDERR)     at C:\Users\Márius Rak\Desktop\App\.meteor\local\build\programs\server\boot.js:470:11
```

**Comment by mariusrak** [comment]
Seems, like it's not a problem of circular reference. I've removed it and it still gives the error.

**Comment by mariusrak** [comment]
Oh, maybe the important point is that the libraries are symlinked from node_modules. So there is symlink like `/node_modules/libraries` -> `/libraries/`. And the problematic file is in the `libraries` directory.

**Comment by mariusrak** [comment]
I've looked into the `packages/modules.js` and there is this code:
```javascript
meteorInstall({"node_modules":{"@babel":{"runtime":{"helpers":{"interopRequireDefault.js":function(require,exports,module){

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                   //
// node_modules/@babel/runtime/helpers/interopRequireDefault.js                                                      //
//                                                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                     //
module.useNode();
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

},"extends.js":function(require,exports,module){

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                   //
// node_modules/@babel/runtime/helpers/extends.js                                                                    //
//                                                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                     //
module.useNode();
```

Is this normal and okay?

**Comment by mariusrak** [comment]
I guess it might be an issue with https://github.com/meteor/meteor/pull/9771

**Comment by mariusrak** [comment]
I've changed import and instead `import .. form "libraries"` I now have `import ... from "/libraries"` and everything works. So i guess the problem is really with linking package to node_modules which causes that not everything is recompiled. And it can be caused by own `package.json` in the linked `libraries` folder.
