### ISSUE TITLE
Deploying to Galaxy with 1.8.1-betaX fails

### ISSUE THREAD

**Issue by ixdi** [meteor/meteor#10476]
Hi,

The deployment to Galaxy gives us an error in several versions of the beta, including the lastone, the number 20.

```js
/app/bundle/programs/server/node_modules/fibers/future.js:280
/app/bundle/programs/server/node_modules/fibers/future.js:280
2019-03-01 07:53:24+01:00	throw(ex);
2019-03-01 07:53:24+01:00	^
2019-03-01 07:53:24+01:00
2019-03-01 07:53:24+01:00 TypeError: Cannot read property 'constructor' of undefined
2019-03-01 07:53:24+01:00 at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
2019-03-01 07:53:24+01:00 at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
2019-03-01 07:53:24+01:00 at packages/meteorhacks_meteorx.js:175:1
2019-03-01 07:53:24+01:00 at packages/meteorhacks_meteorx.js:200:4
2019-03-01 07:53:24+01:00 at packages/meteorhacks_meteorx.js:208:3
2019-03-01 07:53:24+01:00 at /app/bundle/programs/server/boot.js:419:36
2019-03-01 07:53:24+01:00 at Array.forEach (<anonymous>)
2019-03-01 07:53:24+01:00 at /app/bundle/programs/server/boot.js:228:19
2019-03-01 07:53:24+01:00 at /app/bundle/programs/server/boot.js:479:5
2019-03-01 07:53:24+01:00 at Function.run (/app/bundle/programs/server/profile.js:510:12)
2019-03-01 07:53:24+01:00 at /app/bundle/programs/server/boot.js:478:11
2019-03-01 07:53:24+01:00	throw(ex);
2019-03-01 07:53:24+01:00	^
2019-03-01 07:53:24+01:00
2019-03-01 07:53:24+01:00 TypeError: Cannot read property 'constructor' of undefined
2019-03-01 07:53:24+01:00 at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
2019-03-01 07:53:24+01:00 at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
2019-03-01 07:53:24+01:00 at packages/meteorhacks_meteorx.js:175:1
2019-03-01 07:53:24+01:00 at packages/meteorhacks_meteorx.js:200:4
2019-03-01 07:53:24+01:00 at packages/meteorhacks_meteorx.js:208:3
2019-03-01 07:53:24+01:00 at /app/bundle/programs/server/boot.js:419:36
2019-03-01 07:53:24+01:00 at Array.forEach (<anonymous>)
2019-03-01 07:53:24+01:00 at /app/bundle/programs/server/boot.js:228:19
2019-03-01 07:53:24+01:00 at /app/bundle/programs/server/boot.js:479:5
2019-03-01 07:53:24+01:00 at Function.run (/app/bundle/programs/server/profile.js:510:12)
2019-03-01 07:53:24+01:00 at /app/bundle/programs/server/boot.js:478:11
```
Thanks

**Comment by jamesmillerburgess** [comment]
It could be that you are using `mdg:meteor-apm-agent` in your project, in which case there is a newer version that does not depend on `meteorhacks:meteorx`. 

You should be able to fix this by running `meteor update mdg:meteor-apm-agent` or `meteor update --all-packages`.

**Comment by ixdi** [comment]
Perfect now, thank you!
