### ISSUE TITLE
AppendToConfig Splash Path Error

### ISSUE THREAD

**Issue by davinderkumar** [meteor/meteor#10475]
Hi,

I upgraded my app to latest version 1.8.0.2 and trying to use splash images instead of launch screen using AppendToConfig but I am getting error "Source path does not exist" error whereas file does exist at given location and to avoid confusion I am using absolute path:

mobile-config.js includes this tag:

```
App.appendToConfig(`
  <splash src="/Users/davinder/Work/map/myapp/app/resources/splashes/Default@2x~universal~anyany.png" />
`);
```

And when I run project with "meteor run ios-device --settings=settings.json " then I get this exception:

  ```
 While preparing Cordova project for platform iOS:
   Error: Source path does not exist: /Users/davinder/Work/map/myapp/app/resources/splashes/Default@2x~universal~anyany.png
   at updatePathInternal
   (/Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:145:19)
   at /Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:223:19
   at Array.forEach (<anonymous>)
   at Object.updatePaths
   (/Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/FileUpdater.js:221:33)
   at updateLaunchStoryboardImages (/Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/prepare.js:847:21)
   at /Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/prepare.js:64:13
   at _fulfilled (/Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:854:54)
   at self.promiseDispatch.done (/Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:883:30)
   at Promise.promise.promiseDispatch (/Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:816:13)
   at /Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:570:49
   at runSingle (/Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:137:13)
   at flush (/Users/davinder/Work/map/myapp/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:125:13)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
```

any help would be great. 

Thanks

**Comment by davinderkumar** [comment]
I tried the same with a test app but getting same issue. 
I am on 
MacOS 10.14.1
Meteor 1.8.0.2
Node 10.6.0

[mytest.zip](https://github.com/meteor/meteor/files/2921790/mytest.zip)

**Comment by dovydaskukalis** [comment]
For us it works like this, at least in build.

`<splash src=""../../../app/resources/splashes/Default@2x~universal~anyany.png" />`

**Comment by davinderkumar** [comment]
@dovydaskukalis Thanks. It is strange that absolute path doesn't work.
