### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by 95zz** [meteor/meteor#10483]
xdeMac-mini:bundle x$ node main.js 
module.js:549
    throw err;
    ^

Error: Cannot find module 'fibers'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/x/Desktop/meteor/hjie/.build/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
xdeMac-mini:bundle x$ node -v
v8.11.4
xdeMac-mini:bundle x$ npm -v
6.4.1

**Comment by StorytellerCZ** [comment]
Are you sure you are in the correct project? That is not how you run a Meteor project.

Please refer to the tutorial:
https://www.meteor.com/tutorials/react/creating-an-app

You need to use the `meteor` command in the folder where you app is.

For any questions please use the [forums](https://forums.meteor.com). Please use GitHub only for things related to development. Also next time use a but more descriptive title please.

**Comment by 95zz** [comment]
Thank you for your answer. Next time, pay attention to this question.
