### ISSUE TITLE
Issues with wrapAsync and MongoDB Aggregates in 1.8.1-rc.1

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10513]
I just updated one of our smaller apps to the latest version from #10248, `1.8.1-rc.1` (previously `1.6.1.4`) and my MongoDB aggregate queries broke.

```
W20190329-13:09:12.840(2)? (STDERR) (node:97954) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
W20190329-13:09:12.840(2)? (STDERR)     at Object.EJSON.toJSONValue.item [as toJSONValue] (packages/ejson/ejson.js:291:21)
W20190329-13:09:12.840(2)? (STDERR)     at Object.keys.forEach.key (packages/ejson/ejson.js:188:29)
W20190329-13:09:12.841(2)? (STDERR)     at Array.forEach (<anonymous>)
W20190329-13:09:12.841(2)? (STDERR)     at Object.toJSONValue (packages/ejson/ejson.js:187:24)
W20190329-13:09:12.841(2)? (STDERR)     at toJSONValueHelper (packages/ejson/ejson.js:240:24)
W20190329-13:09:12.841(2)? (STDERR)     at Object.EJSON.toJSONValue.item [as toJSONValue] (packages/ejson/ejson.js:292:19)
W20190329-13:09:12.841(2)? (STDERR)     at Object.keys.forEach.key (packages/ejson/ejson.js:188:29)
W20190329-13:09:12.842(2)? (STDERR)     at Array.forEach (<anonymous>)
W20190329-13:09:12.842(2)? (STDERR)     at Object.toJSONValue (packages/ejson/ejson.js:187:24)
W20190329-13:09:12.843(2)? (STDERR)     at toJSONValueHelper (packages/ejson/ejson.js:240:24)
W20190329-13:09:12.843(2)? (STDERR)     at Object.EJSON.toJSONValue.item [as toJSONValue] (packages/ejson/ejson.js:292:19)
W20190329-13:09:12.843(2)? (STDERR)     at Object.keys.forEach.key (packages/ejson/ejson.js:188:29)
W20190329-13:09:12.844(2)? (STDERR)     at Array.forEach (<anonymous>)
W20190329-13:09:12.844(2)? (STDERR)     at Object.toJSONValue (packages/ejson/ejson.js:187:24)
W20190329-13:09:12.844(2)? (STDERR)     at toJSONValueHelper (packages/ejson/ejson.js:240:24)
W20190329-13:09:12.844(2)? (STDERR)     at Object.EJSON.toJSONValue.item [as toJSONValue] (packages/ejson/ejson.js:292:19)
W20190329-13:09:12.845(2)? (STDERR) (node:97954) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

The error isn't very helpful (slightly related, perhaps? https://github.com/meteor/meteor/issues/10373).

The code that used to work in `1.6.1.4`:

```js
const aggregate = Meteor.wrapAsync(Meteor.users.rawCollection().aggregate, Meteor.users.rawCollection());
const result = aggregate(pipeline);
```

I got the query working again by switching to the package `sakulstra:aggregate` and changing the code above to this:

```js
const result = Meteor.users.aggregate(pipeline);
```

**Comment by sakulstra** [comment]
Maybe that sheds some light on the issue:

I forked `meteorhacks/meteor-aggregate` to apply a patch for the native driver v3.
The issue is, that in the native driver the contract changed:
https://github.com/mongodb/node-mongodb-native/blob/master/CHANGES_3.0.0.md#collectionprototypeaggregate and `aggregate` now returns a promise instead of the result.

https://github.com/sakulstra/meteor-aggregate/commit/b040e8ec51798389ffee7f9170d7b5d74c160f65#diff-168726dbe96b3ce427e7fedce31bb0bc

**Comment by ecarlotti** [comment]
I had this exact same problem and it almost drove me crazy over the past few days. The only way I was able to make it work with 1.8.1 (all beta and rc versions, including the official one released two days ago) was to switch from Meteor.wrapAsync to Promise.await - That of course, works only on server-side code. A full example below:

```javascript
import { Promise } from 'meteor/promise';
const result = Promise.await(collection.aggregate(pipeline).toArray());
```

Hope this helps!

**Comment by arggh** [comment]
Closing, as this is not about Meteor.
