### ISSUE TITLE
Production build fails due to errors in minification

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10546]
For some reason the production build of our app now fails with this error message:

```
Property local of ExportSpecifier expected node to be of a type ["Identifier"] but instead got "FunctionExpression" while minifying
   dynamic/node_modules/@interactjs/actions/index.js
```

I just updated the [InteractJS](https://interactjs.io/) package to the recently releaed `1.4.0`, and now it seems Meteor's minifier doesn't like it one bit.

I can run the app locally, but either deploying or running with `--production` produces this error message, which is presented in detail below.

I first hit this problem running Meteor `1.8.1`, then decided to give [`1.8.2-beta.1`](https://github.com/meteor/meteor/pull/10522) a try, but to no avail.

<details>
<summary>Stack trace</summary>

```
=> Started proxy.                             
=> Errors prevented startup:                  
   
   While minifying app code:

   /Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/types/lib/definitions/utils.js:128:13:
   Property local of ExportSpecifier expected node to be of a type ["Identifier"] but instead got "FunctionExpression" while minifying
   dynamic/node_modules/@interactjs/actions/index.js
   at Object.validate
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/types/lib/definitions/utils.js:128:13)
   at Object.validate
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/types/lib/validators/validate.js:17:9)
   at NodePath._replaceWith
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/replacement.js:194:9)
   at NodePath.replaceWith
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/replacement.js:178:8)
   at replace
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:1200:10)
   at Object.enter
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:499:32)
   at Object.newFn
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:230:17)
   at NodePath._call
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:53:20)
   at NodePath.call
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:40:17)
   at NodePath.visit
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:88:12)
   at TraversalContext.visitQueue
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:118:16)
   at TraversalContext.visitMultiple
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:85:17)
   at TraversalContext.visit
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:144:19)
   at Function.traverse.node
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/index.js:94:17)
   at traverse
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/index.js:76:12)
   at NodePath.traverse
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/index.js:161:24)
   at PluginPass.exit
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-minify-dead-code-elimination/lib/index.js:1022:16)
   at newFn
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:193:21)
   at NodePath._call
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:53:20)
   at NodePath.call
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:40:17)
   at NodePath.visit
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/path/context.js:97:8)
   at TraversalContext.visitQueue
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:118:16)
   at TraversalContext.visitSingle
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:90:19)
   at TraversalContext.visit
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/context.js:146:19)
   at Function.traverse.node
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/index.js:94:17)
   at traverse
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/index.js:76:12)
   at transformFile
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transformation/index.js:88:29)
   at runSync
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transformation/index.js:45:3)
   at transformFromAstSync
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast.js:45:38)
   at Object.transformFromAst
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast.js:22:38)
   at Object.minify
   (/Users/arggh/.meteor/packages/standard-minifier-js/.2.4.1.kgkpum.idxbk++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:133:33)
   at Object.minify (packages/babel-compiler.js:59:29)
   at meteorJsMinify (packages/minifier-js.js:60:25)
   at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:126:20)
   at Array.forEach (<anonymous>)
   at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:118:9)
```

</details>

**Comment by arggh** [comment]
...after symlinking the InteractJS package from `node_modules` to `app/imports`, the build minifies just fine.

_To close or not to close?_

**Comment by benjamn** [comment]
Any luck with `1.8.2-beta.3`?

**Comment by arggh** [comment]
No luck with this one either :/

**Comment by dovydaskukalis** [comment]
I think there is something wrong with InteractJS 1.4.0 itself. We had a similar issue and updating to 1.4.1 fixed it. We are on 1.8.1.

**Comment by arggh** [comment]
@dovydaskukalis seems `1.4.1` was released some 10hrs ago, thanks for the heads up.

**Comment by arggh** [comment]
Updating InteractJS to `1.4.1` does fix the errors. @benjamn should this issue be kept open for tracking any potential improvements to Meteor that you might have in mind regardless?

**Comment by tenshis** [comment]
> ...after symlinking the InteractJS package from `node_modules` to `app/imports`, the build minifies just fine.
> 
> _To close or not to close?_

Can you explain this step a bit? Does symlinking cause the standard minifier to skip the package? Can this be done on Windows as well?

**Comment by arggh** [comment]
> Can you explain this step a bit? Does symlinking cause the standard minifier to skip the package? Can this be done on Windows as well?

It's the opposite: a package in `/imports` gets compiled by Meteor as if it were app code.



<details>
<summary>From Meteor's History.md (breaking changes in 1.7)</summary>

* Although Meteor does not recompile packages installed in `node_modules`
  by default, compilation of specific npm packages (for example, to
  support older browsers that the package author neglected) can now be
  enabled in one of two ways:

  * Clone the package repository into your application's `imports`
    directory, make any modifications necessary, then use `npm install` to
    link `the-package` into `node_modules`:
    ```sh
    meteor npm install imports/the-package
    ```
    Meteor will compile the contents of the package exposed via
    `imports/the-package`, and this compiled code will be used when you
    import `the-package` in any of the usual ways:
    ```js
    import stuff from "the-package"
    require("the-package") === require("/imports/the-package")
    import("the-package").then(...)
    ```
    This reuse of compiled code is the critical new feature that was added
    in Meteor 1.7.

  * Install the package normally with `meteor npm install the-package`,
    then create a symbolic link *to* the installed package elsewhere in
    your application, outside of `node_modules`:
    ```sh
    meteor npm install the-package
    cd imports
    ln -s ../node_modules/the-package .
    ```
    Again, Meteor will compile the contents of the package because they
    are exposed outside of `node_modules`, and the compiled code will be
    used whenever `the-package` is imported from `node_modules`.

    > Note: this technique also works if you create symbolic links to
      individual files, rather than linking the entire package directory.

  In both cases, Meteor will compile the exposed code as if it was part of
  your application, using whatever compiler plugins you have installed.
  You can influence this compilation using `.babelrc` files or any other
  techniques you would normally use to configure compilation of
  application code. [PR #9771](https://github.com/meteor/meteor/pull/9771)
  [Feature #6](https://github.com/meteor/meteor-feature-requests/issues/6)

</details>
