### ISSUE TITLE
"Only one default export allowed per module" with Meteor 1.8.2-beta.1

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10547]
I was trying out the latest beta, [`1.8.2-beta.1`](https://github.com/meteor/meteor/pull/10522), and noticed that a package ([date-fns](https://date-fns.org/)) that used to work with `1.8.1` no longer does.

_Disclaimer: I'm using the alpha version `2.0.0-alpha.27` of `date-fns`._

When building the production bundle, this happens:

```
Errors prevented startup:                  
   
   While minifying app code:
   packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error within packages/arggh_invite-views.js:
   node_modules/meteor/arggh_invite-views/node_modules/date-fns/esm/toDate/index.js
   
   Only one default export allowed per module.:
   
   export default function toDate(argument) {
   
   at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:96:26)
   at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
   at Array.forEach (<anonymous>)
   at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:118:9)
```

However, running locally in dev mode works just fine. Rolling back to Meteor `1.8.1` fixes it.

<details>
<summary>Here's the full flow of events:</summary>

```
$ meteor update --release 1.8.2-beta.1
Changes to your project's package version selections from updating the release:
                                              
ecmascript       upgraded from 0.12.4 to 0.12.7
modules-runtime  upgraded from 0.10.3 to 0.11.0-beta182.1

app: updated to Meteor 1.8.2-beta.1. 

$ meteor --production
Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use meteor build to create a
bundle for production deployment. See: https://guide.meteor.com/deployment.html

=> Started proxy.                             
=> Errors prevented startup:                  
   
   While minifying app code:
   packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error within packages/arggh_invite-views.js:
   node_modules/meteor/arggh_invite-views/node_modules/date-fns/esm/toDate/index.js
   
   Only one default export allowed per module.:
   
   export default function toDate(argument) {
   
   at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:96:26)
   at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
   at Array.forEach (<anonymous>)
   at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:118:9)
   
   
   While minifying app code:
   packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error within packages/arggh_invite-views.js:
   node_modules/meteor/arggh_invite-views/node_modules/date-fns/esm/toDate/index.js
   
   Only one default export allowed per module.:
   
   export default function toDate(argument) {
   
   at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:96:26)
   at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
   at Array.forEach (<anonymous>)
   at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:118:9)
   
   
=> Your application has errors. Waiting for file change.
^C Starting your app                         -
$ meteor update --release 1.8.1
                                              
Changes to your project's package version selections from updating the release:
                                              
modules-runtime  downgraded from 0.11.0-beta182.1 to 0.10.3

app: updated to Meteor 1.8.1.       

$ meteor --production
Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use meteor build to create a bundle for production deployment. See:
https://guide.meteor.com/deployment.html

=> Started proxy.                             
=> Started your app.

=> App running at: http://localhost:3000/
```

</details>

**Comment by arggh** [comment]
A minor detail: 

- app1 was ok, it depended on `date-fns@2.0.0-alpha.27` directly
- app2 was broken, and it depended on `date-fns@2.0.0-alpha.27` via a Meteor package

**Comment by arggh** [comment]
Still happening on `1.8.2-beta.2`

**Comment by benjamn** [comment]
Ok, how about `1.8.2-beta.3`, maybe plus a `meteor reset`?

**Comment by arggh** [comment]
Still the same error. 

```
$ meteor update --release 1.8.2-beta.3

Changes to your project's package version selections from updating the release:
                                              
modules-runtime  upgraded from 0.10.3 to 0.11.0-beta182.3
webapp           upgraded from 1.7.3 to 1.7.4

$ meteor reset
$ meteor --production
=> Started proxy.                             
=> Errors prevented startup:    
While minifying app code:
   packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error within packages/arggh_invite-views.js:
   node_modules/meteor/arggh_invite-views/node_modules/date-fns/esm/toDate/index.js
   
   Only one default export allowed per module.:
   
   export default function toDate(argument) {
   
   at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS/plugin/minify-js.js:96:26)
   at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
   at Array.forEach (<anonymous>)
   at MeteorBabelMinifier.processFilesForBundle (packages/minifyStdJS/plugin/minify-js.js:118:9)
   ...
```

**Comment by arggh** [comment]
I just re-tried with `1.8.2-beta.14` and this problem has disappeared.
