### ISSUE TITLE
Docker Compose Error at dev_bundle

### ISSUE THREAD

**Issue by richardkeller411** [meteor/meteor#10549]
Error: EISDIR: illegal operation on a directory, unlink '/opt/reaction/src/.meteor/local/dev_bundle'
   at Object.fs.unlinkSync (fs.js:1061:18)
  at exports.makeLink (/tools/cli/dev-bundle-links.js:20:8)
   at exports.ReleaseFile.ensureDevBundleLink (/tools/project-context.js:1538:7)
  at exports.ReleaseFile._readFile (/tools/project-context.js:1472:10)
    at new exports.ReleaseFile (/tools/project-context.js:1422:8)
   at /tools/cli/main.js:932:22

Windows 10 docker-compose

**Comment by filipenevola** [comment]
Ben commit should have fixed this on 1.8.2.
