### ISSUE TITLE
Users loginWithPassword schema fail

### ISSUE THREAD

**Issue by mariusrak** [meteor/meteor#10552]
Hi,
I have simple login code 
```javascript
Meteor.loginWithPassword(model.user, model.pass, cb)
```
which worked so far, but after update to v1.9-alpha.0 I get following error with valid credentials. For invalid credentials, login fails normally. I've logged the values and they're not empty, so parameters to the functions are correct.

Edit: I've downgraded to 1.8.2-beta.3 and to 1.8.1-issue-10516.0 and it didn't help, so I guess it's not about new version.

```
I20190507-14:47:52.376(2)? Exception while invoking method 'login' Error: After filtering out keys not in the schema, your modifier is now empty
I20190507-14:47:52.378(2)?     at doValidate (packages/aldeed:collection2/collection2.js:423:11)
I20190507-14:47:52.379(2)?     at Collection.Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:195:14)
I20190507-14:47:52.380(2)?     at AccountsServer._insertHashedLoginToken (packages/accounts-base/accounts_server.js:806:16)
I20190507-14:47:52.380(2)?     at AccountsServer._insertLoginToken (packages/accounts-base/accounts_server.js:815:10)
I20190507-14:47:52.381(2)?     at AccountsServer._loginUser (packages/accounts-base/accounts_server.js:270:12)
I20190507-14:47:52.382(2)?     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:342:17)
I20190507-14:47:52.383(2)?     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)
I20190507-14:47:52.386(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20190507-14:47:52.387(2)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20190507-14:47:52.388(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20190507-14:47:52.389(2)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20190507-14:47:52.390(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1234:12)
I20190507-14:47:52.391(2)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20190507-14:47:52.392(2)?     at new Promise (<anonymous>)
I20190507-14:47:52.393(2)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20190507-14:47:52.394(2)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by mariusrak** [comment]
Oh, issue was elsewhere, I've redefined schema of users collection.
