### ISSUE TITLE
standard-minifier-css minification fails after update to 1.8.1

### ISSUE THREAD

**Issue by jacob87o2** [meteor/meteor#10556]
After I updated Meteor to v.1.8.1, the build stopped working. The error says `Lexical error on line 1: Unrecognized text`. And it's not even my code that fails, probably one of the npm libs.

I tried downgrading to the previous version (from 1.5.3 to 1.4.1), but it automatically upgraded it back.

`standard-minifier-css  upgraded from 1.4.1 to 1.5.3`

What's the point of having `packages` and `versions` files then?

Anyone has an idea how to fix the issue?

Here is the full error message:

```
Errors prevented bundling:                    
While minifying app stylesheet:               
<input css 1>:4:39505: Lexical error on line 1: Unrecognized text.

Erroneous area:
1: 100% - $canvasTop
^.........^
at <input css 1>:4:39505
at Object.parseError
(/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1164:15)
at Object.lexer_parseError
(/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:2297:44)
at Object.lexer_next
(/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:3292:22)
at Object.lexer_fastLex
(/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:3367:18)
at fastLex (/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1567:27)
at Parser.parse
(/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1641:30)
at /root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:30:30
at walk (/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-value-parser/lib/walk.js:19:7)
at ValueParser.walk
(/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-value-parser/lib/index.js:18:3)
at transformValue
(/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:24:50)
at _default
(/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:59:100)
at /root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/index.js:25:51
at container.es6:110:18
at Rule.each (container.es6:76:16)
at Rule.walk (container.es6:107:17)
at container.es6:121:24
at Root.each (container.es6:76:16)
at Root.walk (container.es6:107:17)
at /root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/index.js:23:9
at initializePlugin (/root/.meteor/packages/standard-minifier-css/.1.5.3.k48v5o.e24lf++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/cssnano/dist/index.js:31:51)
at /root/.meteor/packages/meteor-tool/.1.8.1.20on4p.c5pn1++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by edwardupton** [comment]
I have a problem with the same package, although the error message is different. I also can't downgrade to `1.4.1`!

```
While minifying app stylesheet:
   <input css 1>:7216:1: Cannot read property 'toLowerCase' of undefined
   at <input css 1>:7216:1
   at hasInherit
   (/Users/edwardupton/.meteor/packages/standard-minifier-css/.1.5.3.1d9gh12.y6ux++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-merge-longhand/dist/lib/canMerge.js:16:39)
   at Array.some (<anonymous>)
   at exports.default
   (/Users/edwardupton/.meteor/packages/standard-minifier-css/.1.5.3.1d9gh12.y6ux++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-merge-longhand/dist/lib/canMerge.js:21:15)
   at
   /Users/edwardupton/.meteor/packages/standard-minifier-css/.1.5.3.1d9gh12.y6ux++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-merge-longhand/dist/lib/decl/boxBase.js:103:44
   at mergeRules
   (/Users/edwardupton/.meteor/packages/standard-minifier-css/.1.5.3.1d9gh12.y6ux++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-merge-longhand/dist/lib/mergeRules.js:53:17)
   at Object.merge
   (/Users/edwardupton/.meteor/packages/standard-minifier-css/.1.5.3.1d9gh12.y6ux++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-merge-longhand/dist/lib/decl/boxBase.js:102:38)
   at _decl2.default.forEach.p
   (/Users/edwardupton/.meteor/packages/standard-minifier-css/.1.5.3.1d9gh12.y6ux++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-merge-longhand/dist/index.js:22:19)
   at Array.forEach (<anonymous>)
   at css.walkRules.rule
   (/Users/edwardupton/.meteor/packages/standard-minifier-css/.1.5.3.1d9gh12.y6ux++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-merge-longhand/dist/index.js:20:28)
```

@benjamn is there a way to specify a previous version of `standard-minifier-css` package?

**Comment by edwardupton** [comment]
@jacob87o2 I fixed this us by swapping out standard CSS minifier for https://atmospherejs.com/juliancwirko/postcss

**Comment by jacob87o2** [comment]
@edwardupton thanks for the info, if they don't fix it in nearest time, I'll also try that

**Comment by dreich-nucleus** [comment]
Any update on this? I just upgraded to 1.8.1 and am seeing a similar error during bundling - an Unknown word" error.
