### ISSUE TITLE
try to upgrade our app from 1.7.0.4 to 1.9-alpha.5

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#10587]
~~~it keeps asking~~~

```
Unable to resolve some modules:

  "@babel/runtime/helpers/builtin/classCallCheck" in /Users/monsterstep/dev/cube19/node_modules/react-event-listener/dist/react-event-listener.cjs.js (web.browser)
  "@babel/runtime/helpers/builtin/createClass" in /Users/monsterstep/dev/cube19/node_modules/react-event-listener/dist/react-event-listener.cjs.js (web.browser)
  "@babel/runtime/helpers/builtin/possibleConstructorReturn" in /Users/monsterstep/dev/cube19/node_modules/react-event-listener/dist/react-event-listener.cjs.js (web.browser)
  "@babel/runtime/helpers/builtin/inherits" in /Users/monsterstep/dev/cube19/node_modules/react-event-listener/dist/react-event-listener.cjs.js (web.browser)
  "@babel/runtime/helpers/builtin/typeof" in /Users/monsterstep/dev/cube19/node_modules/react-event-listener/dist/react-event-listener.cjs.js (web.browser)
  "@babel/runtime/helpers/builtin/objectWithoutProperties" in /Users/monsterstep/dev/cube19/node_modules/react-event-listener/dist/react-event-listener.cjs.js (web.browser)
  "@babel/runtime/helpers/builtin/objectSpread" in /Users/monsterstep/dev/cube19/node_modules/react-event-listener/dist/react-event-listener.cjs.js (web.browser)
  "@babel/runtime/core-js/object/assign" in /Users/monsterstep/dev/cube19/node_modules/@lvfang/atlas/lib/index.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save @babel/runtime
```

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

feit:server-picker

meteor-base@1.4.0
mongo
static-html
reactive-var@1.0.11
jquery
tracker@1.2.0

standard-minifier-css@1.4.1
standard-minifier-js@2.3.4
ecmascript@0.11.1

#meteorhacks:kadira

accounts-base
accounts-password
kadira:flow-router
dburles:collection-helpers
aldeed:simple-schema@1.5.4
aldeed:collection2@2.8.0
matb33:collection-hooks
reywood:publish-composite@1.7.0
check
tmeasday:publish-counts
maximum:server-transform
coagmano:stylus
http
lvfang:aggregate
random
ccorcos:subs-cache

crapthings:cao
mikowals:batch-insert
underscore
shell-server@0.3.1
dynamic-import
lamhieu:unblock
```

```
accounts-base@1.4.4
accounts-password@1.5.1
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.4
allow-deny@1.1.0
autoupdate@1.6.0
babel-compiler@7.3.4
babel-runtime@1.3.0
base64@1.0.11
binary-heap@1.0.11
blaze-tools@1.0.10
boilerplate-generator@1.6.0
caching-compiler@1.2.1
caching-html-compiler@1.1.3
callback-hook@1.1.0
ccorcos:subs-cache@0.9.12
check@1.3.1
coagmano:stylus@1.1.0
coffeescript@1.0.17
crapthings:cao@0.0.1
dburles:collection-helpers@1.1.0
dburles:mongo-collection-instances@0.3.5
ddp@1.4.0
ddp-client@2.3.3
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.3.0
deps@1.0.12
diff-sequence@1.1.1
dynamic-import@0.5.1
ecmascript@0.12.7
ecmascript-runtime@0.7.0
ecmascript-runtime-client@0.8.0
ecmascript-runtime-server@0.7.1
ejson@1.1.0
email@1.2.3
es5-shim@4.8.0
feit:server-picker@0.0.1
fetch@0.1.1
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.2
id-map@1.1.0
inter-process-messaging@0.1.0
jquery@1.11.11
kadira:flow-router@2.12.1
lai:collection-extensions@0.2.1_1
lamhieu:meteorx@2.1.1
lamhieu:unblock@1.0.0
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
lvfang:aggregate@0.0.1
matb33:collection-hooks@0.8.4
maximum:package-base@1.1.2
maximum:server-transform@0.5.0
mdg:validation-error@0.2.0
meteor@1.9.3
meteor-base@1.4.0
mikowals:batch-insert@1.1.9
minifier-css@1.4.2
minifier-js@2.4.1
minimongo@1.4.5
modern-browsers@0.1.4
modules@0.13.0
modules-runtime@0.12.0-alpha190.5
mongo@1.6.2
mongo-decimal@0.1.1
mongo-dev-server@1.1.0
mongo-id@1.0.7
mongo-livedata@1.0.12
npm-bcrypt@0.9.3
npm-mongo@3.1.2
ordered-dict@1.1.0
peerlibrary:assert@0.2.5
peerlibrary:fiber-utils@0.6.0
peerlibrary:reactive-mongo@0.1.1
peerlibrary:server-autorun@0.5.2
promise@0.11.2
raix:eventemitter@0.1.3
random@1.1.0
rate-limit@1.0.9
reactive-dict@1.3.0
reactive-var@1.0.11
reload@1.3.0
retry@1.1.0
reywood:publish-composite@1.7.0
routepolicy@1.1.0
service-configuration@1.0.11
sha@1.0.9
shell-server@0.4.0
socket-stream-client@0.2.2
spacebars-compiler@1.1.3
srp@1.0.12
standard-minifier-css@1.5.3
standard-minifier-js@2.4.1
static-html@1.2.2
templating-tools@1.1.2
tmeasday:publish-counts@0.8.0
tracker@1.2.0
underscore@1.0.10
url@1.2.0
webapp@1.7.4
webapp-hashing@1.0.9
```

after install missing package, this error goes. but got new one

**Comment by crapthings** [comment]
new error

```
/Users/monsterstep/.meteor/packages/coffeescript/.1.0.17.1htj6g3.wxr3++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

TypeError: Cannot read property 'id' of null
    at InputFile.resolve (/tools/isobuild/compiler-plugin.js:401:61)
    at InputFile._require (/tools/isobuild/compiler-plugin.js:411:25)
    at InputFile.require (/tools/isobuild/compiler-plugin.js:405:17)
    at requireWithPrefixes (packages/babel-compiler.js:553:32)
    at requireWithPath (packages/babel-compiler.js:430:14)
    at resolveHelper (packages/babel-compiler.js:402:24)
    at packages/babel-compiler.js:375:19
    at Array.forEach (<anonymous>)
    at walkHelper (packages/babel-compiler.js:374:10)
    at walkBabelRC (packages/babel-compiler.js:355:24)
    at BabelCompiler.BCp._inferHelper (packages/babel-compiler.js:457:17)
    at BabelCompiler.BCp._inferFromPackageJson (packages/babel-compiler.js:324:14)
    at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:277:10)
    at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:196:10)
    at packages/babel-compiler.js:122:25
    at /Users/monsterstep/.meteor/packages/meteor-tool/.1.9.0-alpha.5.pn7c7i.rzodr++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by benjamn** [comment]
Can you try upgrading to 1.8.1 first?

**Comment by crapthings** [comment]
revert to 1.7.0.5 use babel-runtime@latest failed
building works by using this @babel/runtime@7.0.0-beta.55

1.8.1 works with @babel/runtime": "7.0.0-beta.55
