### ISSUE TITLE
When building  - Only one default export allowed per module error

### ISSUE THREAD

**Issue by rooch84** [meteor/meteor#10656]
Yesterday I suddenly started seeing the following error when building.  As far as I can see, I haven't changed anything.    

Just to be clear, `node_modules/@babel/runtime/helpers/esm/objectWithoutProperties.js` only has one export. 

```
>$ meteor --version
Meteor 1.8.1
>$ meteor reset
Project reset.
>$ meteor build --directory /tmp/bundle --server-only
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Errors prevented bundling:
While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error
within packages/modules.js:
node_modules/@babel/runtime/helpers/esm/objectWithoutProperties.js

Only one default export allowed per module.:

export default function _objectWithoutProperties(source, excluded) {

at maybeThrowMinifyErrorBySourceFile
(packages/minifyStdJS/plugin/minify-js.js:96:26)
at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)


While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error
within packages/modules.js:
node_modules/@babel/runtime/helpers/esm/objectWithoutProperties.js

Only one default export allowed per module.:

export default function _objectWithoutProperties(source, excluded) {

at maybeThrowMinifyErrorBySourceFile
(packages/minifyStdJS/plugin/minify-js.js:96:26)
at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)
```

**Comment by rooch84** [comment]
OK, upgrading to ` 1.8.2-beta.17` fixed it.  Any thoughts as to what caused the error in the first place?

**Comment by rooch84** [comment]
OK, follow up question, how do I install a beta version?  Since `https://install.meteor.com/?release=1.8.2-beta.17` doesn't work (stuck on 'Retrying download in 5 seconds...').

**Comment by rooch84** [comment]
OK, thanks to @abernix (https://github.com/meteor/meteor/issues/6915#issuecomment-214992066), I now understand that the Meteor tool version can be different to the project version.  So I can still use 1.8.1 to build 1.8.2-beta.17, and it will build it as 1.8.2-beta.17.

it would be still useful to know why 1.8.1 suddenly stopped building.

**Comment by rooch84** [comment]
This could be related to package versions, and can't replicate with a bare project.  Suggest closing for now.
