### ISSUE TITLE
[1.8.2-rc.1] TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by jorisroling** [meteor/meteor#10700]
This ran fine in METEOR@1.8.2-beta.17

```
/Users/joris/.meteor/packages/tap_i18n/.1.8.2.1q9t9mx.tii1++os+web.browser+web.cordova/plugin.tap-i18n-compiler.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1233:7)
    at Object.wrapper [as pathJoin] (/Users/joris/.meteor/packages/meteor-tool/.1.8.2-rc.1.huhgp2.gks2++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/tools/static-assets/server/mini-files.ts:107:14)
    at entry.files.forEach.file (/tools/isobuild/compiler-plugin.js:1494:17)
    at Array.forEach (<anonymous>)
    at jsOutputFilesMap.forEach.entry (/tools/isobuild/compiler-plugin.js:1492:19)
    at Map.forEach (<anonymous>)
    at Function._watchOutputFiles (/tools/isobuild/compiler-plugin.js:1491:22)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1486:17)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1137:8)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:856:12)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:844:18)
    at /tools/isobuild/bundler.js:3197:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3348:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3302:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3178:31)
    at files.withCache (/tools/isobuild/bundler.js:3123:32)
    at Slot.withValue (/Users/joris/.meteor/packages/meteor-tool/.1.8.2-rc.1.huhgp2.gks2++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at Object.withCache (/Users/joris/.meteor/packages/meteor-tool/.1.8.2-rc.1.huhgp2.gks2++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1647:39)
    at Object.bundle (/tools/isobuild/bundler.js:3123:16)
    at Profile.run (/tools/runners/run-app.js:572:24)
    at Function.run (/Users/joris/.meteor/packages/meteor-tool/.1.8.2-rc.1.huhgp2.gks2++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:571:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:613:35)
    at AppRunner._fiber (/tools/runners/run-app.js:929:28)
    at /tools/runners/run-app.js:401:12

```

**Comment by benjamn** [comment]
This should be fixed by `meteor update --release 1.8.2-rc.2`, thanks to commit 48d27202e70751fa7d2d624349fff36b1da8a1e9. Please feel free to reopen this issue if the problem persists.
