### ISSUE TITLE
Is it safe to use Meteor from checkout for production build and deploy?

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#10732]
Hi, I would like to know if is safe to use Meteor code built and deployed from checkout in production.

I have one important fix on Meteor build tool that I can't wait for Meteor to release a new version https://github.com/meteor/meteor/pull/10730

My question is: is it safe to run a Meteor app using code built and deployed from a fork?

Also, I would like to know if is there a way to run Meteor in development from checkout without extra warns like these below, maybe I could build it locally somehow and use it as a "released" version:
```
=> Running Meteor from a checkout -- overrides project version
   (Meteor 1.8.1-issue-10516.0)
[[[[[ ~/Documents/pathable/ws/pathable-next/pathable-app ]]]]]

=> Started proxy.

Changes to your project's package version selections:

accounts-base          downgraded from 1.4.4 to 1.4.3
coffeescript           upgraded from 2.0.3_4 to 2.3.2_1
coffeescript-compiler  upgraded from 2.0.3_4 to 2.3.2_1
webapp                 downgraded from 1.7.4 to 1.7.4-issue-10516.0

Failed to record package usage.
(This error is hidden when you are not running Meteor from a checkout.)
Error: DDP disconnected while connection in progress
    at /tools/meteor-services/service-connection.js:89:18
    at forEachCallback.callback (packages/socket-stream-client/node.js:95:9)
    at Array.forEach (<anonymous>)
    at ClientStream.forEachCallback (packages/socket-stream-client/common.js:30:31)
    at ClientStream._cleanup (packages/socket-stream-client/node.js:94:12)
    at ClientStream._lostConnection (packages/socket-stream-client/common.js:130:10)
    at clientOnIfCurrent (packages/socket-stream-client/node.js:183:12)
    at client.on.Meteor.bindEnvironment.args (packages/socket-stream-client/node.js:168:11)
    at runWithEnvironment (packages/meteor.js:1286:24)
 => awaited here:
    at Promise.await (/Users/filipenevola/Documents/filipe/ws/forks/meteor/.meteor/packages/static-html/.1.2.2.15pn7s4.ji5d++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:39:12)
    at ServiceConnection.subscribeAndWait (/tools/meteor-services/service-connection.js:169:5)
    at Object.exports.getAccountsConfiguration (/tools/meteor-services/auth.js:917:39)
    at /tools/meteor-services/stats.js:70:40
```

For sure that is possible somehow but if this is not documented yet I would like to help to document it.

**Comment by filipenevola** [comment]
We are using it for more a week already and everything is running fine, except a few logs that we didn't have with a final version, I think we can improve that in the near future.

Then I'm going to close this and assume it's safe.
