### ISSUE TITLE
Meteor cant run ios

### ISSUE THREAD

**Issue by cecilcosta** [meteor/meteor#10745]
Meteor 1.8.1
OS X 10.15 (Catalina)
Zsh
Xcode 11.1

Add the iOS platforma with `meteor add-platform ios`, then run on a simultor with `meteor run ios`

Expected result:
An ios simulator must appear

Result:
Compilation error:
`[[[[[ ~/Workspace/tutorspace ]]]]]            

=> Started proxy.                             
WARNING: Attempting to install plugin cordova-plugin-statusbar@2.2.1, but it should have a minimum version of 2.3.0 to ensure compatibility with the current platform versions. Installing the minimum version for convenience, but you
         should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-splashscreen@4.0.1, but it should have a minimum version of 4.1.0 to ensure compatibility with the current platform versions. Installing the minimum version for convenience, but you
         should adjust your dependencies.
=> Started MongoDB.                           
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform iOS with options --buildConfig,/Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/build.json,--emulator:
   Error: Command failed: /Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/platforms/ios/cordova/run --buildConfig /Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/build.json --emulator
   TypeError: Cannot read property 'toLowerCase' of undefined
   at /Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/platforms/ios/cordova/lib/list-emulator-build-targets:54:45
   at Array.forEach (<anonymous>)
   at /Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/platforms/ios/cordova/lib/list-emulator-build-targets:52:44
   at Array.reduce (<anonymous>)
   at /Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/platforms/ios/cordova/lib/list-emulator-build-targets:50:57
   at Array.reduce (<anonymous>)
   at /Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/platforms/ios/cordova/lib/list-emulator-build-targets:45:28
   at _fulfilled (/Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:854:54)
   at self.promiseDispatch.done (/Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:883:30)
   at Promise.promise.promiseDispatch (/Users/tutorspace/Workspace/tutorspace/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/q/q.js:816:13)
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:126:13)
   at ChildProcess.emit (events.js:214:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
   => awaited here:
   at Function.Promise.await
   (/Users/tutorspace/.meteor/packages/static-html/.1.2.2.1lk0afd.5wrw++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:843:14)
   at Promise.asyncApply (/tools/cordova/project.js:310:10)
   at /Users/tutorspace/.meteor/packages/static-html/.1.2.2.1lk0afd.5wrw++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
                                              
/Users/tutorspace/.meteor/packages/static-html/.1.2.2.1lk0afd.5wrw++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
    at Function.Promise.await (/Users/tutorspace/.meteor/packages/static-html/.1.2.2.1lk0afd.5wrw++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at Promise.asyncApply (/tools/cordova/run-targets.js:35:7)
    at /Users/tutorspace/.meteor/packages/static-html/.1.2.2.1lk0afd.5wrw++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
 => awaited here:
    at Function.Promise.await (/Users/tutorspace/.meteor/packages/static-html/.1.2.2.1lk0afd.5wrw++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at buildmessage.capture (/tools/cordova/runner.js:98:9)
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at CordovaRunner.startRunTargets (/tools/cordova/runner.js:97:37)
    at AppRunner._runOnce (/tools/runners/run-app.js:760:21)
    at AppRunner._fiber (/tools/runners/run-app.js:922:28)
    at /tools/runners/run-app.js:401:12`

**Comment by mattmcegg** [comment]
+1 for this.

The important part of the debug log here is "**TypeError: Cannot read property 'toLowerCase' of undefined**"

This seems to be an issue with the latest version of XCode, and happens somewhat frequently when Apple updates XCode. I think the latest version of cordova fixes it, but it's not part of Meteor yet. Downgrading XCode may be an option.

**Comment by pisacode** [comment]
This issue still persists however you can just run `meteor run ios-device --settings settings-development.json` and then open the xcode file and then built the project on any device you want.

**Comment by filipenevola** [comment]
I believe this PR #10810 is going to fix this.

**Comment by renanccastro** [comment]
Hey guys, this is fixed on this PR: https://github.com/meteor/meteor/pull/10810, but not released yet. In the meantime, you can use the `meteor run ios-device` command and run the simulator through xcode as described here https://github.com/meteor/meteor/pull/10810#issuecomment-568186020 and as @pisacode have described above(thanks!!).

Any problems, let me know.
