### ISSUE TITLE
[1.8.2-rc.7] Strange meteor tool error when trying to build a TypeScript package

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#10768]
I'm trying to update one of my old packages to TypeScript with Meteor 1.8.2 and the first few commits worked well, but then the meteor tool decided to start crapping out with a pretty cryptic error, as below.

To reproduce:

1. Checkout the branch `typescript-1.8` of https://github.com/TurkServer/turkserver-meteor
2. `meteor --release 1.8.2-rc.7 test-packages ./`

It's not clear to me that the Meteor version itself seems to be the problem. Instead, it seems like the tool has got itself into a strange state where multiple different versions, from 1.6.1.4 to 1.8.2-rc, throw the same error. Though strangely, deleting `~/.meteor` does not fix the problem.

I'm currently using Ubuntu (WSL on Windows 10).

Expected behavior: the code runs instead of crashing cryptically.

In general, can't these promise errors be parsed out and re-printed instead of failing this way?

```
$ meteor --release 1.8.2-rc.7 test-packages ./
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
/home/mao/.meteor/packages/meteor-tool/.1.8.2-rc.7.1evrqi1.795r++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getShrinkwrappedDependenciesTree (/tools/isobuild/meteor-npm.js:1015:27)
    at updateExistingNpmDirectory (/tools/isobuild/meteor-npm.js:648:5)
    at Object.meteorNpm.updateDependencies (/tools/isobuild/meteor-npm.js:112:7)
    at Object.compile (/tools/isobuild/compiler.js:128:19)
    at /tools/isobuild/isopack-cache.js:354:30
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:309:18)
    at Profile.time (/tools/isobuild/isopack-cache.js:243:16)
    at Function.time (/home/mao/.meteor/packages/meteor-tool/.1.8.2-rc.7.1evrqi1.795r++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:284:12)
    at /tools/isobuild/isopack-cache.js:242:17
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:233:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:207:12)
    at /tools/isobuild/isopack-cache.js:235:11
    at Function._.each._.forEach (/home/mao/.meteor/packages/meteor-tool/.1.8.2-rc.7.1evrqi1.795r++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:186:9)
    at /tools/isobuild/isopack-cache.js:234:11
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:233:20)
    at /tools/isobuild/isopack-cache.js:75:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/mao/.meteor/packages/meteor-tool/.1.8.2-rc.7.1evrqi1.795r++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at exports.PackageMap.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:74:24)
    at /tools/project-context.js:869:25
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:868:18)
    at /tools/project-context.js:300:9
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:290:18)
    at Profile.run (/tools/project-context.js:282:12)
    at Function.run (/home/mao/.meteor/packages/meteor-tool/.1.8.2-rc.7.1evrqi1.795r++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:281:13)
    at /tools/runners/run-app.js:547:29
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundleApp (/tools/runners/run-app.js:546:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:613:35)
    at AppRunner._fiber (/tools/runners/run-app.js:929:28)
    at /tools/runners/run-app.js:401:12
```

**Comment by mizzao** [comment]
This seems to be a WSL problem because everything works as expected on a different Linux distro on the same branch. But it is not fixable by reinstalling meteor, as suggested in https://github.com/meteor/meteor/issues/7647.

So I'm not sure what state problem occurred that could be causing this, which involve files outside of the `~/.meteor` directory.

**Comment by benjamn** [comment]
I bet the shrinkwrap JSON file is not fully written by the time we try to read it with getShrinkwrappedDependenciesTree, due to file system inconsistencies/delays in WSL.

**Comment by benjamn** [comment]
That said, if we can make WSL support "good enough" with a little bit of extra debugging, then we could drop native Windows support completely, which would be a huge maintainability win for the Meteor project. I'm very interested in any thoughts you have about that possibility!

**Comment by mizzao** [comment]
> I suspect the shrinkwrap JSON file is not fully written by the time we try to read it with `getShrinkwrappedDependenciesTree`, due to file system inconsistencies/delays in WSL.

Interesting twist: I checked out the repo in a separate location and it worked fine. Then I realized the problem was not with the Meteor distro or the code, but with one of the local directories. I deleted `.npm` and then everything worked. Note this is an Atmosphere package, not a Meteor app. This was probably caused by the BSOD (see below).

> That said, if we can make WSL support "good enough" with a little bit of extra debugging, then we could drop native Windows support completely, which would be a huge maintainability win for the Meteor project. I'm very interested in any thoughts you have about that possibility!

I am a heavy Linux user but use Windows 10 at home. In the course of doing work I have come to strongly prefer WSL to using a VM, because it's much faster (as long as you disable Windows Defender) and allows me to use native VSCode in Windows to edit code I've checked out and am running in WSL (through the black magic that is https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl). I run `meteor` in the built in VSCode console, so the Linux under the hood is practically invisible: 

![image](https://user-images.githubusercontent.com/2080084/68548605-c0b45480-03bc-11ea-8887-6700e35456bb.png)

Generally everything works as you'd expect if you were running native Linux, however, here are the two main issues I have:

1. You can't run two meteor tools at the same time: meteor/meteor-feature-requests#154
2. Running NPM on WSL seems to cause random BSODs, so starting a Meteor app can randomly crash the entire computer. The BSOD refers to `LXCORE.SYS` which is a WSL library. This is probably not a problem that Meteor can fix, and is something that started happening only recently (see another user's example: https://stackoverflow.com/questions/57952780/npm-install-makes-windows-crash)

I'd love to help make WSL the first-class supported Windows environment for Meteor. Having used Meteor since 0.6.5 and on all envs including OS X, Linux, and Windows, I think the VSCode-WSL environment is by far the best option for Windows support.

**Comment by heberallred** [comment]
@benjamn We use Meteor with Electron, and we have to build the Windows packages using the windows console.  Using WSL sounds great if it can work correctly, but some Meteor projects that use Windows API's (like ours) might not work.

**Comment by heberallred** [comment]
I just want to re-iterate a recommendation for Meteor to consider native Electron support for Windows/Mac/Linux, along with the existing Cordova support (which includes keeping Windows compatibility alive for the Meteor server).  This way apps can be developed with Meteor to have compatibility for all major platforms and is a huge plus for using Meteor.  We're doing this currently with a variation of the "meteor-desktop" package, but it would be nifty if it was all built into Meteor.
