### ISSUE TITLE
`meteor update --release 1.9-beta.2` fails

### ISSUE THREAD

**Issue by pihentagy** [meteor/meteor#10778]
Trying to upgrade a working 1.8.1 project, got this log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
1 verbose cli   '/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm',
1 verbose cli   'rebuild',
1 verbose cli   '--update-binary'
1 verbose cli ]
2 info using npm@6.13.0
3 info using node@v12.13.0
4 info readInstalled object
5 verbose rebuild path, id [
5 verbose rebuild   '/home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/v8-profiler-node8',
5 verbose rebuild   'v8-profiler-node8@6.0.0'
5 verbose rebuild ]
6 silly rebuild set [
6 silly rebuild set   '/home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/v8-profiler-node8'
6 silly rebuild set ]
7 info build /home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/v8-profiler-node8
8 info lifecycle v8-profiler-node8@6.0.0~preinstall: v8-profiler-node8@6.0.0
9 verbose lifecycle v8-profiler-node8@6.0.0~preinstall: unsafe-perm in lifecycle true
10 verbose lifecycle v8-profiler-node8@6.0.0~preinstall: PATH: /home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/v8-profiler-node8/node_modules/.bin:/home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/.bin:/home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin:/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64:/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/.bin:/home/pihentagy/.asdf/shims:/home/pihentagy/.asdf/bin:/home/pihentagy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/pihentagy/bin:/home/pihentagy/go/bin
11 verbose lifecycle v8-profiler-node8@6.0.0~preinstall: CWD: /home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/v8-profiler-node8
12 silly lifecycle v8-profiler-node8@6.0.0~preinstall: Args: [ '-c', "node -e 'process.exit(0)'" ]
13 silly lifecycle v8-profiler-node8@6.0.0~preinstall: Returned: code: 0  signal: null
14 info linkStuff v8-profiler-node8@6.0.0
15 silly linkStuff v8-profiler-node8@6.0.0 has /home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules as its parent node_modules
16 info lifecycle v8-profiler-node8@6.0.0~install: v8-profiler-node8@6.0.0
17 verbose lifecycle v8-profiler-node8@6.0.0~install: unsafe-perm in lifecycle true
18 verbose lifecycle v8-profiler-node8@6.0.0~install: PATH: /home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/v8-profiler-node8/node_modules/.bin:/home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/.bin:/home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin:/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64:/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/.bin:/home/pihentagy/.asdf/shims:/home/pihentagy/.asdf/bin:/home/pihentagy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/pihentagy/bin:/home/pihentagy/go/bin
19 verbose lifecycle v8-profiler-node8@6.0.0~install: CWD: /home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op/node_modules/v8-profiler-node8
20 silly lifecycle v8-profiler-node8@6.0.0~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
21 silly lifecycle v8-profiler-node8@6.0.0~install: Returned: code: 1  signal: null
22 info lifecycle v8-profiler-node8@6.0.0~install: Failed to exec install script
23 verbose stack Error: v8-profiler-node8@6.0.0 install: `node-pre-gyp install --fallback-to-build`
23 verbose stack Exit status 1
23 verbose stack     at EventEmitter.<anonymous> (/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
23 verbose stack     at EventEmitter.emit (events.js:210:5)
23 verbose stack     at ChildProcess.<anonymous> (/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
23 verbose stack     at ChildProcess.emit (events.js:210:5)
23 verbose stack     at maybeClose (internal/child_process.js:1021:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
24 verbose pkgid v8-profiler-node8@6.0.0
25 verbose cwd /home/pihentagy/.meteor/packages/qualia_profile/.0.0.12.uuf9dw.tmsak++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.temp-b9h9zw.m6op
26 verbose Linux 4.15.0-70-generic
27 verbose argv "/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/pihentagy/.meteor/packages/meteor-tool/.1.9.0-beta.2.1m6mbqb.5086++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--update-binary"
28 verbose node v12.13.0
29 verbose npm  v6.13.0
30 error code ELIFECYCLE
31 error errno 1
32 error v8-profiler-node8@6.0.0 install: `node-pre-gyp install --fallback-to-build`
32 error Exit status 1
33 error Failed at the v8-profiler-node8@6.0.0 install script.
33 error This is probably not a problem with npm. There is likely additional logging output above.
34 verbose exit [ 1, true ]

```

**Comment by benjamn** [comment]
Pretty sure this is just saying that `v8-profiler-node8` no longer works with Node.js 12.x? Might want to remove `qualia:profile` package for now.

**Comment by benjamn** [comment]
Please feel free to reopen if removing `qualia:profile` does not solve the problem.
