### ISSUE TITLE
NPM package dependency left out on production bulid, when force-added, Windows build crashes

### ISSUE THREAD

**Issue by SimonSimCity** [meteor/meteor#10783]
I wanted to create a production build of my application when I discovered that the system failed, telling me that the npm package `resolve` could not be found. To fix it quickly, I added it as a direct dependency of the Meteor package it was failing at (of which I had a local fork of): https://github.com/SimonSimCity/meteor-elastic-apm/commit/a5a48221e9a56699eca898c831d969280fee9ff4

This allows me to create a build on a mac for my production system.

Strangely, I now receive the following error, when compiling this project on windows:

```
C:\projects\server>meteor --settings settings-development.json
[[[[[ C:\projects\server ]]]]]

=> Started proxy.
=> Started MongoDB.
C:\Users\Simon\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EPERM: operation not permitted, unlink 'C:\projects\server\packages\meteor-elastic-apm\.npm\package\node_modules\normalize-package-data\lib'
 => awaited here:
    at Promise.await (C:\Users\Simon\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at Object.files.rm_recursive.path [as rm_recursive] (C:\tools\fs\files.js:348:7)
    at Object.files.rename (C:\tools\fs\files.js:1829:13)
    at Object.files.renameDirAlmostAtomically.Profile [as renameDirAlmostAtomically] (C:\tools\fs\files.js:1046:13)
    at C:\tools\isobuild\meteor-npm.js:407:11
    at Array.forEach (<anonymous>)
    at Object.rebuildIfNonPortable (C:\tools\isobuild\meteor-npm.js:382:17)
    at NodeModulesDirectory.rebuildIfNonPortable (C:\tools\isobuild\bundler.js:276:22)
    at _.each.nmd (C:\tools\isobuild\compiler.js:655:13)
    at Function._.each._.forEach (C:\Users\Simon\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at C:\tools\isobuild\compiler.js:648:7
    at files.withCache (C:\tools\isobuild\compiler.js:186:28)
    at Object.withCache (C:\tools\fs\files.js:1744:12)
    at C:\tools\isobuild\compiler.js:185:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\Simon\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Object.compile (C:\tools\isobuild\compiler.js:180:5)
    at C:\tools\isobuild\isopack-cache.js:354:30
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at IsopackCache._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:309:18)
    at Profile.time (C:\tools\isobuild\isopack-cache.js:243:16)
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at C:\tools\isobuild\isopack-cache.js:242:17
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:233:20)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\OMS\AppData\Local\.meteor\packages\meteor-tool\1.8.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at exports.PackageMap.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74:24)
    at C:\tools\project-context.js:869:25
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._buildLocalPackages (C:\tools\project-context.js:868:18)
    at C:\tools\project-context.js:300:9
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:290:18)
    at Profile.run (C:\tools\project-context.js:282:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:281:13)
    at C:\tools\runners\run-app.js:547:29
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at bundleApp (C:\tools\runners\run-app.js:546:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:613:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:922:28)
    at C:\tools\runners\run-app.js:401:12
```

When I remove the direct npm-dependency `resolve`, I added, it works.

Either way it's weird to me. Firstly, it's a dependency of one of the packages within `elastic-apm-node` - so the system should always include it. Secondly, the windows version should never crash when adding an npm dependency.

I'll try to narrow it down and try to reproduce it with a minimal package.

**Comment by SimonSimCity** [comment]
This issue is still relevant to us.

**Comment by SimonSimCity** [comment]
This issue is still relevant to us.

**Comment by italojs** [comment]
abandoned, let us know if it happens in Meteor 3.x
