### ISSUE TITLE
1.9-rc.0 Help required with Babel

### ISSUE THREAD

**Issue by paulincai** [meteor/meteor#10834]
Hi,
I migrate from 1.8.3 to 1.9 -rc.0. I was able to build production in 1.83. Now I get JS minification errors as if ... the minifier doesn't recognize error functions (or something like that).

Could you please help / suggest why this might happen and whether I need any extra settings in my .babelrc or else.

```
standard-minifier-js@2.6.0-rc190.0        # JS minifier run for production mode
```

My dev .babelrc:
```
{
  "plugins": [
    "transform-class-properties",
    "lodash",
    "@babel/plugin-proposal-optional-chaining",
    ["react-intl", {
      "messagesDir": "./imports/ui/translations/"
    }]
  ],
  "presets": [["@babel/env", { "targets": { "node": 12 } }]]
}

```
My babel plugins set:
```
  "@babel/core": "^7.7.7",
    "@babel/plugin-proposal-optional-chaining": "^7.7.5",
    "@babel/plugin-syntax-dynamic-import": "^7.7.4",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@babel/preset-env": "^7.7.7",
    "@babel/preset-react": "^7.7.4",
    "@babel/runtime": "^7.7.7",
```

Server console errors while building:

```
While minifying app code:

   /Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63:
   Unexpected token (1:8) while minifying
   dynamic/node_modules/meteor/react-meteor-data/index.js
   at Object.raise
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63)
   at Object.unexpected
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/util.js:160:16)
   at Object.parseIdentifierName
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/expression.js:2160:18)
   at Object.parseIdentifier
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/expression.js:2127:23)
   at Object.parseFunctionId
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:1095:52)
   at Object.parseFunction
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:1047:22)
   at Object.parseFunctionStatement
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:555:17)
   at Object.parseStatementContent
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:185:21)
   at Object.parseStatement
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:141:17)
   at Object.parseStatement
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/plugins/flow.js:1675:28)
   at Object.parseBlockOrModuleBlockBody
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:860:25)
   at Object.parseBlockBody
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:836:10)
   at Object.parseTopLevel
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/statement.js:47:10)
   at Object.parseTopLevel
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/plugins/flow.js:2913:30)
   at Object.parse
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/index.js:43:10)
   at Object.parse
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/index.js:58:38)
   at parse
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/parser.js:7:22)
   at Object.minify
   (/Users/paulailincai/.meteor/packages/standard-minifier-js/.2.6.0-rc190.0.1tkagbi.6gdg++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:184:5)
   at Object.minify (packages/babel-compiler.js:59:29)
   at meteorJsMinify (packages/minifier-js.js:60:25)
   at packages/minifyStdJS/plugin/minify-js.js:126:20
   at Array.forEach (<anonymous>)
   at MeteorBabelMinifier.processFilesForBundle
   (packages/minifyStdJS/plugin/minify-js.js:118:9)
```

**Comment by paulincai** [comment]
https://github.com/meteor/meteor/issues/10044#issue-337540447
Similarly, when I comment the ```standard-minifier-js``` the build succeeds.

**Comment by paulincai** [comment]
Ok,  react-meteor-data 2.0.1 worked fine with Meteor 1.8.3 but not with 1.9-rc.0. Just reverted to a previous version and I am able to build production now.

While selecting package versions:
   error: Potentially incompatible change required to top-level dependency:
   react-meteor-data 2.0.1, was 0.2.16.
   Constraints on package "react-meteor-data":
   * react-meteor-data@2.0.0 <- top level
   
   To allow potentially incompatible changes to top-level dependencies, you
   must pass --allow-incompatible-update on the command line.

**Comment by s7dhansh** [comment]
@paulincai `meteor reset` will actually solve this problem without downgrading anything.

**Comment by evolross** [comment]
I'm having an error building for Galaxy all the sudden on Meteor `1.10.2.` and `standard-minifier-js@2.6.0`.  Getting the error:
```
/Users/---/.meteor/packages/standard-minifier-js/.2.6.0.8ppzn5.ep8gt++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63:
Identifier 'r' has already been declared (1:76023)
at Object.raise
(/Users/---/.meteor/packages/standard-minifier-js/.2.6.0.8ppzn5.ep8gt++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63)
```

`meteor reset` didn't fix it.

**Comment by nikhilgoswami** [comment]
> I'm having an error building for Galaxy all the sudden on Meteor `1.10.2.` and `standard-minifier-js@2.6.0`. Getting the error:
> 
> ```
> /Users/---/.meteor/packages/standard-minifier-js/.2.6.0.8ppzn5.ep8gt++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63:
> Identifier 'r' has already been declared (1:76023)
> at Object.raise
> (/Users/---/.meteor/packages/standard-minifier-js/.2.6.0.8ppzn5.ep8gt++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/parser/src/parser/location.js:41:63)
> ```
> 
> `meteor reset` didn't fix it.

Did you find solution?
