### ISSUE TITLE
getting error in rand_r when try to run meteor npm install

### ISSUE THREAD

**Issue by Tainan404** [meteor/meteor#10847]
Meteor 1.9-rc.2
Node 12.14.0

I'm trying to run the meteor I'm getting these errors:
```
[[[[[ ~/src/bigbluebutton/bigbluebutton-html5 ]]]]]
=> Started proxy.
=> Errors prevented startup:
   While processing files with nathantreid:css-modules (for target
   web.browser):
   fs.js:854:3: ENOENT: no such file or directory, scandir
   '/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/vendor'
   at Object.readdirSync (fs.js:854:3)
   at Object.getInstalledBinaries
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/extensions.js:132:13)
   at foundBinariesList
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:20:15)
   at foundBinaries
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:15:5)
   at Object.module.exports.missingBinary
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:45:5)
   at module.exports
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/binding.js:15:30)
   at Object.<anonymous>
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/index.js:14:35)
   at Module._compile (internal/modules/cjs/loader.js:959:30)
   at Module.Mp._compile (/tools/static-assets/server/runtime.js:41:21)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
   at Module.load (internal/modules/cjs/loader.js:815:32)
   at Module.Mp.load (/tools/static-assets/server/runtime.js:13:29)
   at Function.Module._load (internal/modules/cjs/loader.js:727:14)
   at Module.require (internal/modules/cjs/loader.js:852:19)
   at require (internal/modules/cjs/helpers.js:74:18)
   at Object.require (/tools/isobuild/bundler.js:2130:22)
   at makeInstallerOptions.fallback (packages/modules-runtime.js:618:18)
   at Module.require (packages/modules-runtime.js:244:14)
   at require (packages/modules-runtime.js:258:21)
   at new ScssProcessor (packages/mss/scss-processor.js:12:55)
   at CssModulesBuildPlugin._setupPreprocessors
   (packages/mss/css-modules-build-plugin.js:127:31)
   at packages/mss/css-modules-build-plugin.js:76:10
   at
   /home/bbb/.meteor/packages/static-html/.1.2.2.1l64tqd.kqhtl++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
   While processing files with nathantreid:css-modules (for target
   web.browser.legacy):
   fs.js:854:3: ENOENT: no such file or directory, scandir
   '/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/vendor'
   at Object.readdirSync (fs.js:854:3)
   at Object.getInstalledBinaries
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/extensions.js:132:13)
   at foundBinariesList
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:20:15)
   at foundBinaries
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:15:5)
   at Object.module.exports.missingBinary
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:45:5)
   at module.exports
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/binding.js:15:30)
   at Object.<anonymous>
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/index.js:14:35)
   at Module._compile (internal/modules/cjs/loader.js:959:30)
   at Module.Mp._compile (/tools/static-assets/server/runtime.js:41:21)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
   at Module.load (internal/modules/cjs/loader.js:815:32)
   at Module.Mp.load (/tools/static-assets/server/runtime.js:13:29)
   at Function.Module._load (internal/modules/cjs/loader.js:727:14)
   at Module.require (internal/modules/cjs/loader.js:852:19)
   at require (internal/modules/cjs/helpers.js:74:18)
   at Object.require (/tools/isobuild/bundler.js:2130:22)
   at makeInstallerOptions.fallback (packages/modules-runtime.js:618:18)
   at Module.require (packages/modules-runtime.js:244:14)
   at require (packages/modules-runtime.js:258:21)
   at new ScssProcessor (packages/mss/scss-processor.js:12:55)
   at CssModulesBuildPlugin._setupPreprocessors
   (packages/mss/css-modules-build-plugin.js:127:31)
   at packages/mss/css-modules-build-plugin.js:76:10
   at
   /home/bbb/.meteor/packages/static-html/.1.2.2.1l64tqd.kqhtl++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
=> Your application has errors. Waiting for file change.
=> Started MongoDB.[[[[[ ~/src/bigbluebutton/bigbluebutton-html5 ]]]]]
=> Started proxy.
=> Errors prevented startup:
   While processing files with nathantreid:css-modules (for target
   web.browser):
   fs.js:854:3: ENOENT: no such file or directory, scandir
   '/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/vendor'
   at Object.readdirSync (fs.js:854:3)
   at Object.getInstalledBinaries
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/extensions.js:132:13)
   at foundBinariesList
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:20:15)
   at foundBinaries
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:15:5)
   at Object.module.exports.missingBinary
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:45:5)
   at module.exports
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/binding.js:15:30)
   at Object.<anonymous>
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/index.js:14:35)
   at Module._compile (internal/modules/cjs/loader.js:959:30)
   at Module.Mp._compile (/tools/static-assets/server/runtime.js:41:21)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
   at Module.load (internal/modules/cjs/loader.js:815:32)
   at Module.Mp.load (/tools/static-assets/server/runtime.js:13:29)
   at Function.Module._load (internal/modules/cjs/loader.js:727:14)
   at Module.require (internal/modules/cjs/loader.js:852:19)
   at require (internal/modules/cjs/helpers.js:74:18)
   at Object.require (/tools/isobuild/bundler.js:2130:22)
   at makeInstallerOptions.fallback (packages/modules-runtime.js:618:18)
   at Module.require (packages/modules-runtime.js:244:14)
   at require (packages/modules-runtime.js:258:21)
   at new ScssProcessor (packages/mss/scss-processor.js:12:55)
   at CssModulesBuildPlugin._setupPreprocessors
   (packages/mss/css-modules-build-plugin.js:127:31)
   at packages/mss/css-modules-build-plugin.js:76:10
   at
   /home/bbb/.meteor/packages/static-html/.1.2.2.1l64tqd.kqhtl++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
   While processing files with nathantreid:css-modules (for target
   web.browser.legacy):
   fs.js:854:3: ENOENT: no such file or directory, scandir
   '/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/vendor'
   at Object.readdirSync (fs.js:854:3)
   at Object.getInstalledBinaries
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/extensions.js:132:13)
   at foundBinariesList
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:20:15)
   at foundBinaries
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:15:5)
   at Object.module.exports.missingBinary
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/errors.js:45:5)
   at module.exports
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/binding.js:15:30)
   at Object.<anonymous>
   (/home/bbb/src/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/index.js:14:35)
   at Module._compile (internal/modules/cjs/loader.js:959:30)
   at Module.Mp._compile (/tools/static-assets/server/runtime.js:41:21)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
   at Module.load (internal/modules/cjs/loader.js:815:32)
   at Module.Mp.load (/tools/static-assets/server/runtime.js:13:29)
   at Function.Module._load (internal/modules/cjs/loader.js:727:14)
   at Module.require (internal/modules/cjs/loader.js:852:19)
   at require (internal/modules/cjs/helpers.js:74:18)
   at Object.require (/tools/isobuild/bundler.js:2130:22)
   at makeInstallerOptions.fallback (packages/modules-runtime.js:618:18)
   at Module.require (packages/modules-runtime.js:244:14)
   at require (packages/modules-runtime.js:258:21)
   at new ScssProcessor (packages/mss/scss-processor.js:12:55)
   at CssModulesBuildPlugin._setupPreprocessors
   (packages/mss/css-modules-build-plugin.js:127:31)
   at packages/mss/css-modules-build-plugin.js:76:10
   at
   /home/bbb/.meteor/packages/static-html/.1.2.2.1l64tqd.kqhtl++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
=> Your application has errors. Waiting for file change.
=> Started MongoDB.
```

I always fixed it by running the `meteor npm install` command, but it is currently causing more errors:

```
../src/fibers.cc:166:27: note: suggested alternative: ‘rand_r’
  void* GetInternalPointer(Handle<T> handle, int index) {
                           ^~~~~~
                           rand_r
../src/fibers.cc:166:35: error: expected primary-expression before ‘>’ token
  void* GetInternalPointer(Handle<T> handle, int index) {
                                   ^
../src/fibers.cc:166:37: error: ‘handle’ was not declared in this scope
  void* GetInternalPointer(Handle<T> handle, int index) {
                                     ^~~~~~
../src/fibers.cc:166:37: note: suggested alternative: ‘rand_r’
  void* GetInternalPointer(Handle<T> handle, int index) {
                                     ^~~~~~
                                     rand_r
../src/fibers.cc:166:45: error: expected primary-expression before ‘int’
  void* GetInternalPointer(Handle<T> handle, int index) {
                                             ^~~
../src/fibers.cc:166:54: error: expression list treated as compound expression in initializer [-fpermissive]
  void* GetInternalPointer(Handle<T> handle, int index) {
                                                      ^
../src/fibers.cc:166:56: error: expected ‘;’ before ‘{’ token
  void* GetInternalPointer(Handle<T> handle, int index) {
                                                        ^
../src/fibers.cc:171:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
  Handle<T> Deref(Isolate* isolate, Persistent<T>& handle) {
  ^~~~~~
  rand_r
../src/fibers.cc:176:14: error: variable or field ‘Return’ declared void
  void Return(Handle<T> handle, const Arguments& args) {
              ^~~~~~
../src/fibers.cc:176:14: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:176:14: note: suggested alternative: ‘rand_r’
  void Return(Handle<T> handle, const Arguments& args) {
              ^~~~~~
              rand_r
../src/fibers.cc:176:22: error: expected primary-expression before ‘>’ token
  void Return(Handle<T> handle, const Arguments& args) {
                      ^
../src/fibers.cc:176:24: error: ‘handle’ was not declared in this scope
  void Return(Handle<T> handle, const Arguments& args) {
                        ^~~~~~
../src/fibers.cc:176:24: note: suggested alternative: ‘rand_r’
  void Return(Handle<T> handle, const Arguments& args) {
                        ^~~~~~
                        rand_r
../src/fibers.cc:176:32: error: expected primary-expression before ‘const’
  void Return(Handle<T> handle, const Arguments& args) {
                                ^~~~~
../src/fibers.cc:180:14: error: variable or field ‘Return’ declared void
  void Return(Handle<T> handle, GetterCallbackInfo info) {
              ^~~~~~
../src/fibers.cc:180:14: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:180:14: note: suggested alternative: ‘rand_r’
  void Return(Handle<T> handle, GetterCallbackInfo info) {
              ^~~~~~
              rand_r
../src/fibers.cc:180:22: error: expected primary-expression before ‘>’ token
  void Return(Handle<T> handle, GetterCallbackInfo info) {
                      ^
../src/fibers.cc:180:24: error: ‘handle’ was not declared in this scope
  void Return(Handle<T> handle, GetterCallbackInfo info) {
                        ^~~~~~
../src/fibers.cc:180:24: note: suggested alternative: ‘rand_r’
  void Return(Handle<T> handle, GetterCallbackInfo info) {
                        ^~~~~~
                        rand_r
../src/fibers.cc:180:51: error: expected primary-expression before ‘info’
  void Return(Handle<T> handle, GetterCallbackInfo info) {
                                                   ^~~~
../src/fibers.cc:188:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
  Handle<Value> ThrowException(Isolate* isolate, Handle<Value> exception) {
  ^~~~~~
  rand_r
../src/fibers.cc:192:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
  Handle<Context> GetCurrentContext(Isolate* isolate) {
  ^~~~~~
  rand_r
../src/fibers.cc:196:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
  Handle<Primitive> Undefined(Isolate* isolate) {
  ^~~~~~
  rand_r
../src/fibers.cc:200:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
  Handle<Boolean> NewBoolean(Isolate* isolate, bool value) {
  ^~~~~~
  rand_r
../src/fibers.cc:204:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
  Handle<Number> NewNumber(Isolate* isolate, double value) {
  ^~~~~~
  rand_r
../src/fibers.cc:208:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
  Handle<FunctionTemplate> NewFunctionTemplate(
  ^~~~~~
  rand_r
../src/fibers.cc:218:2: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
  Handle<Signature> NewSignature(
  ^~~~~~
  rand_r
../src/fibers.cc:408:17: error: expected ‘;’ at end of member declaration
   static Fiber& Unwrap(Handle<Object> handle) {
                 ^~~~~~
../src/fibers.cc:408:30: error: expected ‘)’ before ‘<’ token
   static Fiber& Unwrap(Handle<Object> handle) {
                              ^
../src/fibers.cc:414:15: error: expected ‘)’ before ‘<’ token
   Fiber(Handle<Object> handle, Handle<Function> cb, Handle<Context> v8_context) :
               ^
../src/fibers.cc:680:3: error: ‘Handle’ does not name a type; did you mean ‘rand_r’?
   Handle<Value> ReturnYielded() {
   ^~~~~~
   rand_r
../src/fibers.cc:842:20: error: ‘Handle’ has not been declared
   static void Init(Handle<Object> target) {
                    ^~~~~~
../src/fibers.cc:842:26: error: expected ‘,’ or ‘...’ before ‘<’ token
   static void Init(Handle<Object> target) {
                          ^
In file included from ../src/fibers.cc:3:0:
../src/fibers.cc: In static member function ‘static void Fiber::WeakCallback(void*)’:
../src/fibers.cc:458:23: error: ‘class v8::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
    assert(that.handle.IsNearDeath());
                       ^
../src/fibers.cc: In static member function ‘static void Fiber::DestroyOrphans()’:
../src/fibers.cc:495:22: error: ‘Deref’ is not a member of ‘uni’
      auto stack(uni::Deref(that.isolate, fatal_stack));
                      ^~~~~
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::New(const Arguments&)’:
../src/fibers.cc:10:45: error: ‘ThrowException’ is not a member of ‘uni’
 #define THROW(x, m) return uni::Return(uni::ThrowException(Isolate::GetCurrent(), x(uni::NewLatin1String(Isolate::GetCurrent(), m))), args)
                                             ^
../src/fibers.cc:517:5: note: in expansion of macro ‘THROW’
     THROW(Exception::TypeError, "Fiber expects 1 argument");
     ^~~~~
../src/fibers.cc:10:90: error: ‘NewLatin1String’ is not a member of ‘uni’
 #define THROW(x, m) return uni::Return(uni::ThrowException(Isolate::GetCurrent(), x(uni::NewLatin1String(Isolate::GetCurrent(), m))), args)
                                                                                          ^
../src/fibers.cc:517:5: note: in expansion of macro ‘THROW’
     THROW(Exception::TypeError, "Fiber expects 1 argument");
     ^~~~~
../src/fibers.cc:10:139: error: return-statement with a value, in function returning 'void' [-fpermissive]
 #define THROW(x, m) return uni::Return(uni::ThrowException(Isolate::GetCurrent(), x(uni::NewLatin1String(Isolate::GetCurrent(), m))), args)
                                                                                                                                           ^
../src/fibers.cc:517:5: note: in expansion of macro ‘THROW’
     THROW(Exception::TypeError, "Fiber expects 1 argument");
     ^~~~~
../src/fibers.cc:10:45: error: ‘ThrowException’ is not a member of ‘uni’
 #define THROW(x, m) return uni::Return(uni::ThrowException(Isolate::GetCurrent(), x(uni::NewLatin1String(Isolate::GetCurrent(), m))), args)
                                             ^
../src/fibers.cc:519:5: note: in expansion of macro ‘THROW’
     THROW(Exception::TypeError, "Fiber expects a function");
     ^~~~~
../src/fibers.cc:10:90: error: ‘NewLatin1String’ is not a member of ‘uni’
 #define THROW(x, m) return uni::Return(uni::ThrowException(Isolate::GetCurrent(), x(uni::NewLatin1String(Isolate::GetCurrent(), m))), args)
                                                                                          ^
../src/fibers.cc:519:5: note: in expansion of macro ‘THROW’
     THROW(Exception::TypeError, "Fiber expects a function");
     ^~~~~
../src/fibers.cc:10:139: error: return-statement with a value, in function returning 'void' [-fpermissive]
 #define THROW(x, m) return uni::Return(uni::ThrowException(Isolate::GetCurrent(), x(uni::NewLatin1String(Isolate::GetCurrent(), m))), args)
                                                                                                                                           ^
../src/fibers.cc:519:5: note: in expansion of macro ‘THROW’
     THROW(Exception::TypeError, "Fiber expects a function");
     ^~~~~
../src/fibers.cc:521:5: error: ‘Handle’ was not declared in this scope
     Handle<Value> argv[1] = { args[0] };
     ^~~~~~
../src/fibers.cc:521:5: note: suggested alternative: ‘handle’
     Handle<Value> argv[1] = { args[0] };
     ^~~~~~
     handle
../src/fibers.cc:521:17: error: expected primary-expression before ‘>’ token
     Handle<Value> argv[1] = { args[0] };
                 ^
../src/fibers.cc:521:19: error: ‘argv’ was not declared in this scope
     Handle<Value> argv[1] = { args[0] };
                   ^~~~
../src/fibers.cc:521:19: note: suggested alternative: ‘args’
     Handle<Value> argv[1] = { args[0] };
                   ^~~~
                   args
../src/fibers.cc:522:29: error: ‘NewInstance’ is not a member of ‘uni’
     return uni::Return(uni::NewInstance(Isolate::GetCurrent(), uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction(), 1, argv), args);
                             ^~~~~~~~~~~
../src/fibers.cc:522:69: error: ‘Deref’ is not a member of ‘uni’
     return uni::Return(uni::NewInstance(Isolate::GetCurrent(), uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction(), 1, argv), args);
                                                                     ^~~~~
../src/fibers.cc:522:134: error: return-statement with a value, in function returning 'void' [-fpermissive]
     return uni::Return(uni::NewInstance(Isolate::GetCurrent(), uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction(), 1, argv), args);
                                                                                                                                      ^
../src/fibers.cc:525:4: error: ‘Handle’ was not declared in this scope
    Handle<Function> fn = Handle<Function>::Cast(args[0]);
    ^~~~~~
../src/fibers.cc:525:4: note: suggested alternative: ‘handle’
    Handle<Function> fn = Handle<Function>::Cast(args[0]);
    ^~~~~~
    handle
../src/fibers.cc:525:19: error: expected primary-expression before ‘>’ token
    Handle<Function> fn = Handle<Function>::Cast(args[0]);
                   ^
../src/fibers.cc:525:21: error: ‘fn’ was not declared in this scope
    Handle<Function> fn = Handle<Function>::Cast(args[0]);
                     ^~
../src/fibers.cc:525:41: error: expected primary-expression before ‘>’ token
    Handle<Function> fn = Handle<Function>::Cast(args[0]);
                                         ^
../src/fibers.cc:525:44: error: ‘::Cast’ has not been declared
    Handle<Function> fn = Handle<Function>::Cast(args[0]);
                                            ^~~~
../src/fibers.cc:526:36: error: ‘GetCurrentContext’ is not a member of ‘uni’
    new Fiber(args.This(), fn, uni::GetCurrentContext(Isolate::GetCurrent()));
                                    ^~~~~~~~~~~~~~~~~
../src/fibers.cc:527:40: error: no matching function for call to ‘Return(v8::Local<v8::Object>, const Arguments&)’
    return uni::Return(args.This(), args);
                                        ^
../src/fibers.cc:184:7: note: candidate: template<class T> void uni::Return(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, uni::GetterCallbackInfo)
  void Return(Persistent<T>& handle, GetterCallbackInfo info) {
       ^~~~~~
../src/fibers.cc:184:7: note:   template argument deduction/substitution failed:
../src/fibers.cc:527:40: note:   ‘v8::Local<v8::Object>’ is not derived from ‘v8::P...
```
I found a issue relating it to package g++ is missing, but I have this package in the host.

**Comment by sebakerckhof** [comment]
What's in your package.json file? This is likely related to a dependency not being compatible with node 12. Try using the latest node-sass or create a minimal reproduction.

**Comment by Tainan404** [comment]
Yes @sebakerckhof, I updated my package.json and the meteor started normally.
