### ISSUE TITLE
[1.9] Unable to run cordova after updating

### ISSUE THREAD

**Issue by wreiske** [meteor/meteor#10865]
After updating to 1.9, the whitelist plugin seems to have an issue fetching. I'm going to try downgrading and seeing if the build works in 1.8.3.

Throwing this here for now and I'll update this as I know more / debug.

```
Processing mobile-config.js                   
Copying resources for mobile apps             
Writing new config.xml                        
WARNING: Attempting to install plugin cordova-plugin-statusbar@2.2.1, but it should have a minimum version of 2.3.0 to ensure compatibility with the current platform versions. Installing the
         minimum version for convenience, but you should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-splashscreen@4.0.1, but it should have a minimum version of 4.1.0 to ensure compatibility with the current platform versions. Installing
         the minimum version for convenience, but you should adjust your dependencies.
Plugin cordova-plugin-whitelist version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-wkwebview-engine version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-meteor-webapp version have changed or it was added, will perform cordova plugins reinstall
Plugin phonegap-plugin-push version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-device version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-statusbar version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-splashscreen version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-appversion version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-camera version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-customurlscheme version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-dialogs version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-file version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-inappbrowser version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-ionic-keyboard version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-media version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-nativestorage version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-network-information version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-qrscanner version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-useragent version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-vibration version have changed or it was added, will perform cordova plugins reinstall
Adding plugin cordova-plugin-whitelist@1.3.4 to Cordova project
%% No scripts found for hook "before_plugin_add".
%% Calling plugman.fetch on plugin "cordova-plugin-whitelist@1.3.4"
%% Fetching plugin "cordova-plugin-whitelist@1.3.4" via npm
=> Errors executing Cordova commands:         
                                              
   While adding plugin cordova-plugin-whitelist@1.3.4 to Cordova project:
   Cordova error: Failed to fetch plugin cordova-plugin-whitelist@1.3.4 via registry.
   Probably this is either a connection problem, or plugin spec is incorrect.
   Check your connection and plugin name/version/URL.
   RangeError: Maximum call stack size exceeded
   at
   /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:215:37
   at _rejected
   (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:797:24)
   at
   /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:823:30
   at Promise.when
   (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:1035:31)
   at Promise.promise.promiseDispatch
   (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:741:41)
   at
   /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:557:44
   at flush
   (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:108:17)
   at processTicksAndRejections (internal/process/task_queues.js:75:11)
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to help diagnose the
   issue.)
                                              
/Users/username/.meteor/packages/coffeescript/.1.0.17.12bvfse.4o3a++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
ExitWithCode { code: 1 }
/Users/username/prj/app-mobile/node_modules/mongodb/lib/topologies/server.js:301
          throw err;
          ^

Error: Command failed: meteor run ios-device --port 5000 --mobile-server=https://hostname --verbose --settings settings.json
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at /Users/username/prj/app-mobile/bin/run_ios.js:28:3
    at /Users/username/prj/app-mobile/node_modules/mongodb/lib/operations/execute_operation.js:75:17
    at executeCallback (/Users/username/prj/app-mobile/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at /Users/username/prj/app-mobile/node_modules/mongodb/lib/operations/connect.js:204:7
    at connectCallback (/Users/username/prj/app-mobile/node_modules/mongodb/lib/operations/connect.js:369:5)
    at /Users/username/prj/app-mobile/node_modules/mongodb/lib/operations/connect.js:462:5
    at Server.connectHandler (/Users/username/prj/app-mobile/node_modules/mongodb/lib/topologies/server.js:298:9)
    at Object.onceWrapper (events.js:300:26) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 38018,
  stdout: null,
  stderr: null
}
```

**Comment by rj-david** [comment]
Seems like a connection issue to the npm registry

**Comment by KoenLav** [comment]
This happens all the time, is probably not related to 1.9, can be fixed by referring to the GitHub URL of cordova-plugin-whitelist in your cordova-plugins file.

**Comment by wreiske** [comment]
I'm still having problems with meteor downloading from wherever it pulls cordova packages....

I don't have any issues running this manually
```
vpn0-user14:test wreiske$ npm i npm i cordova-plugin-whitelist
vpn0-user14:test wreiske$ npm i cordova-plugin-whitelist
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ cordova-plugin-whitelist@1.3.4
added 1 package from 1 contributor and audited 1 package in 0.604s
found 0 vulnerabilities
```

**Comment by wreiske** [comment]
Made some progress. Looks like the maximum call stack size exceeded goes away when I remove Meteor Desktop.

Now I'm here:
```
Adding plugin cordova-plugin-meteor-webapp@1.7.1 to Cordova project                
%% No scripts found for hook "before_plugin_add".                                  
%% Calling plugman.fetch on plugin "cordova-plugin-meteor-webapp@1.7.1"            
%% Fetching plugin "cordova-plugin-meteor-webapp@1.7.1" via npm                    
%% Copying plugin "/Users/username/.cordova/lib/npm_cache/cordova-plugin-meteor-webapp/1.7.1/package" => "/Users/username/prj/app/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp"
%% Calling plugman.install on plugin "/Users/username/prj/app/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp" for platform "android
%% Installing "cordova-plugin-meteor-webapp" for android                           
%% Running command: /Users/username/prj/app/.meteor/local/cordova-build/platforms/android/cordova/version 
%% Command finished with error code 0: /Users/username/prj/app/.meteor/local/cordova-build/platforms/android/cordova/version 
%% Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-meteor-webapp on android platform only.
%% No scripts found for hook "before_plugin_install".                              
%% Install start for "cordova-plugin-meteor-webapp" on android.                    
%% Beginning processing of action stack for android project...                     
%% Installing Android library: src/android/build-extras.gradle                     
%% Installing Android library: com.squareup.okhttp3:okhttp:3.9.1                   
%% Action stack processing complete.                                               
%% Updating build files since android plugin contained <framework>                 
%% Subproject Path: CordovaLib                                                     
%% Subproject Path: app                                                            
%% Install complete for cordova-plugin-meteor-webapp on android.                   
%% Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-meteor-webapp on android platform only.
%% No scripts found for hook "after_plugin_install".                               
%% Calling plugman.install on plugin "/Users/username/prj/app/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp" for platform "ios
%% Installing "cordova-plugin-meteor-webapp" for ios                               
%% Running command: /Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/version 
%% Command finished with error code 0: /Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/version 
%% Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-meteor-webapp on ios platform only.
%% No scripts found for hook "before_plugin_install".                              
%% Install start for "cordova-plugin-meteor-webapp" on ios.                        
%% Beginning processing of action stack for ios project...                         
%% Error during processing of action! Attempting to revert...                      
%% Failed to install 'cordova-plugin-meteor-webapp': Uh oh!                        
"/Users/username/prj/app/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/src/ios/GCDWebServer/GCDWebServer/Core/GCDWebServer.m" not found!
    at copyFile (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:319:36)
    at copyNewFile (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:348:5)
    at installHelper (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
    at install (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
    at ActionStack.process (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/Api.js:234:10)
    at handleInstall (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:816:30
    at Promise.promise.promiseDispatch (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:509:49
    at flush (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
=> Errors executing Cordova commands:                                              
                                                                                   
   While adding plugin cordova-plugin-meteor-webapp@1.7.1 to Cordova project:      
   Uh oh!                                                                          
   "/Users/username/prj/app/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/src/ios/GCDWebServer/GCDWebServer/Core/GCDWebServer.m" not found!
   at copyFile (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:319:36)
   at copyNewFile (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:348:5)
   at installHelper (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:269:13)
   at install (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/lib/plugman/pluginHandlers.js:35:13)
   at ActionStack.process (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
   at PluginManager.doOperation (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
   at PluginManager.addPlugin (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
   at Api.addPlugin (/Users/username/prj/app/.meteor/local/cordova-build/platforms/ios/cordova/Api.js:234:10)
   at handleInstall
   (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:594:10)
   at
   /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:357:28
   at _fulfilled
   (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:787:54)
   at
   /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:816:30
   at Promise.promise.promiseDispatch
   (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:749:13)
   at
   /Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:509:49
   at flush
   (/Users/username/.meteor/packages/meteor-tool/.1.9.0.1lpg62k.6s1p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/q/q.js:108:17)
   at processTicksAndRejections (internal/process/task_queues.js:75:11)
                                                                                   
/Users/username/.meteor/packages/coffeescript/.1.0.17.12bvfse.4o3a++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
ExitWithCode { code: 1 }
```

**Comment by filipenevola** [comment]
Hi @wreiske I believe cordova-plugin-meteor-webapp@1.7.1 was published without GCDWebServer submodule. 

I just published 1.7.3 (https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/CHANGELOG.md#v173-2020-01-16) now with the GCDWebServer submodule. 

If you run again you should be able to fix this issue. Sorry about that.

**Comment by filipenevola** [comment]
Hi @wreiske `cordova-plugin-meteor-webapp@1.7.1` should not be used with Meteor 1.9, we fixed that in the version 1.8.2 of `webapp` package. Please run `meteor update` again to update `webapp` package then your app will use `cordova-plugin-meteor-webapp@1.7.0`

**Comment by wreiske** [comment]
> Please run `meteor update` again to update `webapp` package then your app will use `cordova-plugin-meteor-webapp@1.7.0`

Woo! Thank you 👍 Everything is working now. It builds and runs! Closing this ticket.

p.s., it seems like the viewport on iOS has a huge bottom padding? I'm going to do more testing but putting here as an FYI.
![image](https://user-images.githubusercontent.com/6295044/72549300-6f15c380-385e-11ea-9ac0-5b1b89b20806.png)

That wasn't there before.

**Comment by filipenevola** [comment]
@wreiske great 😉 

We shouldn't have any change on mobile stuff in this release. If you find any problem please open another issue.
