### ISSUE TITLE
Error loading npm module named 'config' on meteor 1.9

### ISSUE THREAD

**Issue by claudiosdc** [meteor/meteor#10892]
I have a project that was using meteor version 1.8.2, and I updated it to use meteor version 1.9. After the update, when I tried to run the application, I got the following error message: ***Error: Cannot find module 'config'***.

The referred module, named 'config', is one of the several npm modules that are included in my application.

I double checked to make sure that the 'config' module was properly installed, and it was. The error, however, still persisted.

Then I have decided to create a simple meteor project to try and investigate what was going on, and I have come to the following conclusion:

1. The issue is associated with the fact that the module being loaded is named 'config'. I have tested loading the exact same module, only renaming it to something different than 'config' (e.g. 'app-config' or 'config1'), and it works.

2. The error occurs no matter what loading mechanism is used: either 'require' or 'import'.

3. The error does **NOT** take place if the 'config' module is referenced by a path instead of by its name. In other words:
```javascript
    import config from 'config' // Error
    const config = require('config') // Error
    import config from '../node_modules/config' // Success
    const config = require('../node_modules/config') // Success
```

4. Looking at the built package, I have noticed that the root of the problem is that, for some reason, the 'config' module does not get added to the '/programs/server/packages/modules.js' file. So the issue is in the build process.

5. The issue only occurs on meteor 1.9. On meteor 1.8.3 (and 1.8.2 for that matter), the 'config' module is correctly loaded.

All my tests were run on macOS 10.15.3.

To make it easier to reproduce the error, I have created a [Github project](https://github.com/claudiosdc/meteor-load-config-module-bug). Just follow the script below to reproduce it.

```shell
CSC-MacBookProRetina:GitHub claudio$ git clone https://github.com/claudiosdc/meteor-load-config-module-bug.git
Cloning into 'meteor-load-config-module-bug'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 23 (delta 0), reused 23 (delta 0), pack-reused 0
Unpacking objects: 100% (23/23), done.
CSC-MacBookProRetina:GitHub claudio$ cd meteor-load-config-module-bug/meteor_app
CSC-MacBookProRetina:meteor_app claudio$ meteor npm i
added 83 packages from 70 contributors and audited 620 packages in 1.366s
found 0 vulnerabilities

CSC-MacBookProRetina:meteor_app claudio$ meteor
[[[[[ ~/Projects/GitHub/meteor-load-config-module-bug/meteor_app ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
W20200131-15:07:56.801(-3)? (STDERR) /Users/claudio/.meteor/packages/meteor-tool/.1.9.0.vmlu86.ea0x++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20200131-15:07:56.844(-3)? (STDERR) 						throw(ex);
W20200131-15:07:56.844(-3)? (STDERR) 						^
W20200131-15:07:56.844(-3)? (STDERR) 
W20200131-15:07:56.844(-3)? (STDERR) Error: Cannot find module 'config'
W20200131-15:07:56.844(-3)? (STDERR)     at makeMissingError (packages/modules-runtime.js:222:12)
W20200131-15:07:56.845(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:241:17)
W20200131-15:07:56.845(-3)? (STDERR)     at Module.moduleLink [as link] (/Users/claudio/.meteor/packages/modules/.0.15.0.181c3y9.icrq++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20200131-15:07:56.845(-3)? (STDERR)     at module (server/main.js:1:19)
W20200131-15:07:56.845(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20200131-15:07:56.845(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20200131-15:07:56.845(-3)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20200131-15:07:56.845(-3)? (STDERR)     at /Users/claudio/Projects/GitHub/meteor-load-config-module-bug/meteor_app/.meteor/local/build/programs/server/app/app.js:34:15
W20200131-15:07:56.846(-3)? (STDERR)     at /Users/claudio/Projects/GitHub/meteor-load-config-module-bug/meteor_app/.meteor/local/build/programs/server/boot.js:398:38
W20200131-15:07:56.846(-3)? (STDERR)     at Array.forEach (<anonymous>)
W20200131-15:07:56.846(-3)? (STDERR)     at /Users/claudio/Projects/GitHub/meteor-load-config-module-bug/meteor_app/.meteor/local/build/programs/server/boot.js:226:21
W20200131-15:07:56.846(-3)? (STDERR)     at /Users/claudio/Projects/GitHub/meteor-load-config-module-bug/meteor_app/.meteor/local/build/programs/server/boot.js:461:7
W20200131-15:07:56.846(-3)? (STDERR)     at Function.run (/Users/claudio/Projects/GitHub/meteor-load-config-module-bug/meteor_app/.meteor/local/build/programs/server/profile.js:280:14)
W20200131-15:07:56.846(-3)? (STDERR)     at /Users/claudio/Projects/GitHub/meteor-load-config-module-bug/meteor_app/.meteor/local/build/programs/server/boot.js:460:13
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by claudiosdc** [comment]
After further investigation, I found out that the issue is caused by the fact that the build process (or more specifically the 'resolver.ts' module) is incorrectly identifying the 'config' npm module as a Node.js' internal/native module.

A pull request (#10896) has been issued as a proposed fix.
