### ISSUE TITLE
source compile with node-gyp fails (node-gyp outdated?)

### ISSUE THREAD

**Issue by JamesPHoughton** [meteor/meteor#10928]
Trying to build a package from source, when the package version does not have a prebuilt binary gives a node-gyp error:

```
 if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
```

Likely due to the fact that meteor is using node-gyp v5.0.5 within `.meteor/packages/meteor-tool/.1.9.0-rc.1.1ykj4qn.fg7j++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js`

This version has a known bug (https://github.com/nodejs/node-gyp/issues/1917) patched in node-gyp 6.0.1. 

Env:
- Meteor 1.9.0 or 1.9-rc.1     
- Node v12.16.1
- npm 6.13.4
- OSX Catalina 10.15.3
- Xcode 11.3.1, Build version 11C504

Replication steps: (This replicates because (as of 2/19/20) bcrypt@3.0.3 has no binaries built for Catalina.)
```
$ meteor create test 
$ cd test
$ meteor npm install bcrypt@3.0.3   
```
Yields 
```
  File "/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/jameshoughton/Desktop/test/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/jameshoughton/Desktop/test/node_modules/bcrypt/lib/binding" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72" "--python=/usr/bin/python3" "--nodedir=/Users/jameshoughton/.meteor/packages/meteor-tool/1.9.1/mt-os.osx.x86_64/dev_bundle"
gyp ERR! cwd /Users/jameshoughton/Desktop/test/node_modules/bcrypt
gyp ERR! node -v v12.16.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/jameshoughton/.meteor/packages/meteor-tool/.1.9.1.u3le4z.md04++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/jameshoughton/Desktop/test/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/jameshoughton/Desktop/test/node_modules/bcrypt/lib/binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 --python=/usr/bin/python3 --nodedir=/Users/jameshoughton/.meteor/packages/meteor-tool/1.9.1/mt-os.osx.x86_64/dev_bundle' (1)
```

**Comment by afrokick** [comment]
Did you try to update bcrypt to 3.0.6+ ?
https://www.npmjs.com/package/bcrypt#version-compatibility

**Comment by jamesgibson14** [comment]
This happening to me as well, I can't install fibers. It seems that MacOs Catalina does not have the correct build tools for node-gyp.  I have tried following the steps here and the tests pass but I still can't install meteor fibers, id `meteor npm i` fails. 
Side note: I did successfully install a Beta of Meteor 1.10 a couple of weeks ago, I am pretty sure it was before my upgrade to Catalina.
