### ISSUE TITLE
EJSON Crashing Server In Meteor 1.9.3

### ISSUE THREAD

**Issue by ramzauchenna** [meteor/meteor#10962]
After updating to meteor 1.9.3 my server started crashing. I checked and could not find any reason for the crash.

Server is hosted on Amazon ECS using docker containers and Aws cloud watch for logs. 

I checked the logs and every time the server restarts and runs for 1 minute it crashes with the  error below 

`message: Maximum call stack size exceeded
stack:
RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (<anonymous>)
    at hasOwn (packages/ejson/utils.js:9:70)
    at Object.matchObject (packages/ejson/ejson.js:166:20)
    at toJSONValueHelper (packages/ejson/ejson.js:244:19)
    at packages/ejson/ejson.js:276:21
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)
    at packages/ejson/ejson.js:283:5
    at Array.forEach (<anonymous>)
    at adjustTypesToJSONValue (packages/ejson/ejson.js:269:15)`

I have reverted back to 1.9.2 and everything is working perfectly fine again. 

I also found another issue that crashed the server 

`
3[server-crash] invalid ObjectId, ObjectId.id must be either a string or a Buffer, but is [{"$escape":{"$escape":{"$escape":{"$escape":{"$escape":{"$escape":{"$escape":{"$escape":{"$escape":{"$escape":{"$escape":{"$e`

The $escape goes on and on and on and everything seems to come from the ejson.js file. 

i also checked my packages and the ejson version used is ejson@1.1.1

I have no idea why this issue only occurs in 1.9.3. I have reverted my app to avoid the problem.

**Comment by filipenevola** [comment]
Hi @ramzauchenna were you able to identify what query that is producing this output? ESJON can crash very easily if you have circular dependencies. 

Also, what is your MongoDB Version?

**Comment by ramzauchenna** [comment]
@filipenevola  Mongo version is 3.6.17.

I haven't been able to identify it. the stack trace does not say much or were the problem is from. 

I just rolled back to 1.9.2 where everything works fine. i later tried 1.9.3 and it failed.
