### ISSUE TITLE
meteor 1.5 build issue: SyntaxError: Unexpected token { 

### ISSUE THREAD

**Issue by david-soyez** [meteor/meteor#10977]
Meteor 1.5  build issue brought me here. 
Can you block tough-cookie to the previous version so that my meteor 1.5 and 1.4 apps build properly?

```
W20200320-20:35:52.502(0)? (STDERR) const { fromCallback } = require("universalify");
W20200320-20:35:52.503(0)? (STDERR)       ^
W20200320-20:35:52.503(0)? (STDERR)
W20200320-20:35:52.504(0)? (STDERR) SyntaxError: Unexpected token {
W20200320-20:35:52.504(0)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20200320-20:35:52.505(0)? (STDERR)     at /var/app/.meteor/local/build/programs/server/boot.js:287:30
W20200320-20:35:52.506(0)? (STDERR)     at Array.forEach (native)
```

https://github.com/salesforce/tough-cookie/blob/master/lib/cookie.js#L40
`const { fromCallback } = require("universalify");`

**Comment by mynameiskyleok** [comment]
@david-soyez I'm having the same issue. Were you able to resolve it?
