### ISSUE TITLE
"Exception while polling query"

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#10989]
This morning I returned to my laptop and noticed this error in the terminal (I always leave Meteor running for the night in dev mode...): 

```Exception while polling query {"collectionName":"galleryItems","selector":{"userId":"32BJgsbFQrRDD24oz","galleryId":"myedCXbeLeBX7Ccxz","status":1},"options":{"transform":null}} MongoError: Cursor not found, cursor id: 396014238069```

I've never seen this error before and I recently upgraded to Meteor `1.9.2`.

The app seemed to be running just fine though.

Maybe it's a random fluke due to mac OS sleeping or something similar, but I thought to report it anyway.

<details>
<summary>stack</summary>

```
I20200328-07:45:00.641(2)? Exception while polling query {"collectionName":"galleryItems","selector":{"userId":"32BJgsbFQrRDD24oz","galleryId":"myedCXbeLeBX7Ccxz","status":1},"options":{"transform":null}} MongoError: Cursor not found, cursor id: 396014238069
I20200328-07:45:00.654(2)?     at Connection.<anonymous> (/Users/arggh/.meteor/packages/npm-mongo/.3.3.0.1g0k5db.76ej++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:443:61)
I20200328-07:45:00.655(2)?     at Connection.emit (events.js:311:20)
I20200328-07:45:00.960(2)?     at Connection.EventEmitter.emit (domain.js:482:12)
I20200328-07:45:00.960(2)?     at processMessage (/Users/arggh/.meteor/packages/npm-mongo/.3.3.0.1g0k5db.76ej++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:364:10)
I20200328-07:45:00.962(2)?     at Socket.<anonymous> (/Users/arggh/.meteor/packages/npm-mongo/.3.3.0.1g0k5db.76ej++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:533:15)
I20200328-07:45:00.962(2)?     at Socket.emit (events.js:311:20)
I20200328-07:45:00.962(2)?     at Socket.EventEmitter.emit (domain.js:482:12)
I20200328-07:45:00.962(2)?     at addChunk (_stream_readable.js:294:12)
I20200328-07:45:00.962(2)?     at readableAddChunk (_stream_readable.js:275:11)
I20200328-07:45:00.963(2)?     at Socket.Readable.push (_stream_readable.js:209:10)
I20200328-07:45:00.963(2)?     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
I20200328-07:45:00.963(2)?  => awaited here:
I20200328-07:45:00.963(2)?     at Function.Promise.await (/Users/arggh/.meteor/packages/promise/.0.11.2.1xavwef.9sbp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20200328-07:45:00.963(2)?     at packages/mongo/mongo_driver.js:1037:14
I20200328-07:45:00.963(2)?     at /Users/arggh/.meteor/packages/promise/.0.11.2.1xavwef.9sbp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20200328-07:45:00.963(2)?  => awaited here:
I20200328-07:45:00.963(2)?     at Promise.await (/Users/arggh/.meteor/packages/promise/.0.11.2.1xavwef.9sbp++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20200328-07:45:00.964(2)?     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1086:38)
I20200328-07:45:00.964(2)?     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1100:22)
I20200328-07:45:00.964(2)?     at SynchronousCursor.getRawObjects (packages/mongo/mongo_driver.js:1149:12)
I20200328-07:45:00.964(2)?     at PollingObserveDriver._pollMongo (packages/mongo/polling_observe_driver.js:156:44)
I20200328-07:45:00.964(2)?     at Object.task (packages/mongo/polling_observe_driver.js:93:12)
I20200328-07:45:00.964(2)?     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
I20200328-07:45:00.964(2)?     at packages/meteor.js:894:12 {
I20200328-07:45:00.964(2)?   ok: 0,
I20200328-07:45:00.964(2)?   errmsg: 'Cursor not found, cursor id: 396014238069',
I20200328-07:45:00.965(2)?   code: 43,
I20200328-07:45:00.965(2)?   codeName: 'CursorNotFound',
I20200328-07:45:00.965(2)?   name: 'MongoError',
I20200328-07:45:00.965(2)?   [Symbol(mongoErrorContextSymbol)]: { isGetMore: true }
I20200328-07:45:00.965(2)? }
```

</details>

**Comment by filipenevola** [comment]
Hi, I believe you don't have a way to reproduce this, right?

So I think it would be better to close it for now and we can check later if more users report the same issue in the future.
