### ISSUE TITLE
Exception in HTTP response when error status code

### ISSUE THREAD

**Issue by hassansardarbangash** [meteor/meteor#10987]
How do I get HTTP status code in case of 401?

Here is my code:

```
var result = HTTP.call("POST", 'http://example.com', { data:{"key": "value"}, headers:{'Content-Type' : 'application/json'}});
console.dir(result );
```

In case of error i get this exception:

```
I20200326-22:23:49.080(5)? 'Error: failed [401] {"data":null,"description":"Invalid Password!","status":"ERROR","statusCode":4012}\n' +
I20200326-22:23:49.080(5)?   '    at Object.exports.makeErrorByStatus (packages/http.js:176:10)\n' +
I20200326-22:23:49.080(5)?   '    at Request._callback (packages/http.js:140:24)\n' +
I20200326-22:23:49.080(5)?   '    at Request.self.callback (/home/my-server/.meteor/packages/http/.1.4.2.8kf6jd.1nsqm++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:185:22)\n' +
I20200326-22:23:49.080(5)?   '    at Request.emit (events.js:311:20)\n' +
I20200326-22:23:49.081(5)?   '    at Request.EventEmitter.emit (domain.js:482:12)\n' +
I20200326-22:23:49.081(5)?   '    at Request.<anonymous> (/home/my-server/.meteor/packages/http/.1.4.2.8kf6jd.1nsqm++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1161:10)\n' +
I20200326-22:23:49.081(5)?   '    at Request.emit (events.js:311:20)\n' +
I20200326-22:23:49.082(5)?   '    at Request.EventEmitter.emit (domain.js:482:12)\n' +
I20200326-22:23:49.082(5)?   '    at IncomingMessage.<anonymous> (/home/my-server/.meteor/packages/http/.1.4.2.8kf6jd.1nsqm++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1083:12)\n' +
I20200326-22:23:49.082(5)?   '    at Object.onceWrapper (events.js:417:28)\n' +
I20200326-22:23:49.082(5)?   '    at IncomingMessage.emit (events.js:323:22)\n' +
I20200326-22:23:49.082(5)?   '    at IncomingMessage.EventEmitter.emit (domain.js:482:12)\n' +
I20200326-22:23:49.082(5)?   '    at endReadableNT (_stream_readable.js:1204:12)\n' +
I20200326-22:23:49.083(5)?   '    at processTicksAndRejections (internal/process/task_queues.js:84:21)'
```
How can I get error status code from this?

**Comment by filipenevola** [comment]
Hi @hassansardarbangash, did you try to use a `try/catch` block around your `HTTP.call` code?

**Comment by hassansardarbangash** [comment]
@filipenevola This is what I get in catch too. Its the same for asynchronous too

**Comment by filipenevola** [comment]
Maybe I'm not understanding your issue, the `statusCode` is in your error object.

**Comment by filipenevola** [comment]
Let's proceed with this in the forums https://forums.meteor.com/t/get-http-error-status-code/52239/3
