### ISSUE TITLE
accounts_base 1.6.0 error

### ISSUE THREAD

**Issue by fjmr68** [meteor/meteor#11016]
File **accounts_server.js,** line ### 1323 cause an exception.

```
  let user = accounts.users.findOne(
    {"services.resume.loginTokens.hashedToken": hashedToken},
    {fields: {"services.resume.loginTokens.$": 1}});
```

I think the solution is to replace "services.resume.loginTokens.$" by **"services.resume.loginTokens"**.

_Exception while invoking method 'login' MinimongoError: Minimongo doesn't support $ operator in projections yet.
    at MinimongoError (packages/minimongo/common.js:1087:17)
    at packages/minimongo/local_collection.js:836:13
    at Array.forEach (<anonymous>)
    at Function.LocalCollection._checkSupportedProjection (packages/minimongo/local_collection.js:834:23)
    at Function.LocalCollection._compileProjection (packages/minimongo/local_collection.js:868:19)
    at new Cursor (packages/minimongo/cursor.js:30:42)
    at LocalCollection.find (packages/minimongo/local_collection.js:68:12)
    at LocalCollection.findOne (packages/minimongo/local_collection.js:86:17)
    at ns.Collection.findOne (packages/mongo/collection.js:356:29)
    at MethodInvocation.defaultResumeLoginHandler (packages/accounts-base/accounts_server.js:1321:29)
    at MethodInvocation.<anonymous> (packages/accounts-base/accounts_server.js:1305:38)
    at packages/accounts-base/accounts_server.js:462:31
    at tryLoginMethod (packages/accounts-base/accounts_server.js:1291:14)
    at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:460:22)
    at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:31)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)_

**Comment by menelike** [comment]
The change has been introduced in https://github.com/meteor/meteor/commit/413565ba6c5a5a4a8e31f66122c4cc20bd026204

@fjmr68 I could not reproduce this issue, it should happen upon the second visit where the resume happens right? I have tested this with a dedicated MongoDB `v4.0.12`, not sure if this might be the reason since I don't use the MongoDB provided by Meteor.

**Comment by fjmr68** [comment]
Is is a dedicated MongoDB, version .6.4.
```
root@a066faf10f09:/data# mongod --version
db version v3.6.4
git version: d0181a711f7e7f39e60b5aeb1dc7097bf6ae5856
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
```

**Comment by menelike** [comment]
@fjmr68 This might be exactly your problem.

I don't think that Meteor has any interest in supporting backwards compatibility with older mongo versions. Since Mongo uses `4.2.1` (see https://github.com/meteor/meteor/blob/devel/History.md#v1101-2020-03-12) you should either update your MongoDB to 4.x or downgrade Accounts-Base.

**Comment by fjmr68** [comment]
Thank you for your reply. I will upgrade my database.
