### ISSUE TITLE
Error removing cordova plugins on subsequent builds

### ISSUE THREAD

**Issue by sajhu** [meteor/meteor#11021]
When running meteor build for cordova for a second time, sometimes throws the following error. Deleting project/.meteor/local/cordova_build and trying again works everytime, but this adds a lot of overhead development time.

`=> Errors executing Cordova commands:         
   While removing plugins                     
   cordova-annotated-plugin-android,cordova-plugin-googleplus,cordova-plugin-inappbrowser,cordova-plugin-keyboard,cordova-plugin-meteor-webapp,cordova-plugin-purchases,cordova-plugin-screen-orientation,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-taptic-engine,cordova-plugin-whitelist,cordova-plugin-wkwebview-engine,phonegap-plugin-push
   from Cordova project:
   Cordova error: The plugin 'cordova-annotated-plugin-android' is required by (cordova-plugin-purchases), skipping
   uninstallation. (try --force if trying to update)
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You
   can try running again with the --verbose option to help diagnose the issue.)`

Meteor version 1.10.1, previous version without the error 1.8.0.2, running on macOS 10.15.3

**Comment by BrianMulhall** [comment]
I have seen this too, where I will have to go in an manually delete them from the plugins folder

**Comment by menelike** [comment]
I think that this is a duplicate or at least highly related to https://github.com/meteor/meteor/issues/11005.
The Cordova dependency system is completely unreliable right now.

**Comment by skirunman** [comment]
Not stale.

**Comment by filipenevola** [comment]
Hi guys, have you tried to reproduce this on 1.10.3-beta.0? 

https://github.com/meteor/meteor/pull/11052

**Comment by hexsprite** [comment]
Running 1.10.3-beta.0, still having a problem on 2nd time.

I'm using `cordova-plugin-purchases` (for iOS IAP) and it depends on `cordova-annotated-plugin-android` (which I don't use, not sure why it would get installed.

```
While removing plugin cordova-annotated-plugin-android   from Cordova project:
Cordova error: The plugin 'cordova-annotated-plugin-android' is required by (cordova-plugin-purchases), skipping uninstallation.
```

<details>
<summary>Full traceback</summary>

```
Plugin cordova-plugin-purchases version have changed or it was added, will perform cordova plugins reinstall
Plugin cordova-plugin-wkwebviewxhrfix version have changed or it was added, will perform cordova plugins reinstall
Removing plugin cordova-annotated-plugin-android   from Cordova project
%% No scripts found for hook "before_plugin_rm".
%% Calling plugman.uninstall on plugin "cordova-annotated-plugin-android" for platform "ios"
%% Running command: /Users/jbb/co/myapp/.meteor/local/cordova-build/platforms/ios/cordova/version 
%% Command finished with error code 0: /Users/jbb/co/myapp/.meteor/local/cordova-build/platforms/ios/cordova/version 
=> Errors executing Cordova commands:         
                                              
   While removing plugin cordova-annotated-plugin-android   from Cordova project:
   Cordova error: The plugin 'cordova-annotated-plugin-android' is required by (cordova-plugin-purchases), skipping uninstallation. (try --force if trying to update)
   at runUninstallPlatform
   (/Users/jbb/.meteor/packages/meteor-tool/.1.10.3-beta.0.qkzewt.3g0i++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:259:35)
   at
   /Users/jbb/.meteor/packages/meteor-tool/.1.10.3-beta.0.qkzewt.3g0i++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/uninstall.js:90:16
   at
   /Users/jbb/.meteor/packages/meteor-tool/.1.10.3-beta.0.qkzewt.3g0i++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
   at Function.Promise.await
   (/Users/jbb/.meteor/packages/meteor-tool/.1.10.3-beta.0.qkzewt.3g0i++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:880:22)
   at /tools/cordova/project.js:609:12
   at Array.forEach (<anonymous>)
   at CordovaProject.removePlugins (/tools/cordova/project.js:605:13)
   at /tools/cordova/project.js:740:14
   at Object.enterJob (/tools/utils/buildmessage.js:388:12)
   at CordovaProject.ensurePluginsAreSynchronized (/tools/cordova/project.js:622:18)
   at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:270:10)
   at /tools/cordova/runner.js:78:27
   at Object.enterJob (/tools/utils/buildmessage.js:388:12)
   at CordovaRunner.prepareProject (/tools/cordova/runner.js:77:18)
   at /tools/runners/run-app.js:661:25
   at Object.capture (/tools/utils/buildmessage.js:283:5)
   at AppRunner._runOnce (/tools/runners/run-app.js:660:39)
   at AppRunner._fiber (/tools/runners/run-app.js:927:28)
   at /tools/runners/run-app.js:401:12
```
</details>

**Comment by Nauzer** [comment]
I am having the same issue with cordova-plugin-file in relation to cordova-plugin-file-transfer.

```
=> Errors executing Cordova commands:         
                                              
   While removing plugins                     
   com.wikitude.phonegap.wikitudeplugin,cordova-android-support-gradle-release,cordova-custom-config,cordova-plugin-add-swift-support,cordova-plugin-camera,cordova-plugin-device,cordova-plugin-file,cordova-plugin-file-transfer,cordova-plugin-geolocation,cordova-plugin-inappbrowser,cordova-plugin-keyboard,cordova-plugin-media-capture,cordova-plugin-meteor-webapp,cordova-plugin-qrscanner,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-vibration,cordova-plugin-whitelist,cordova-plugin-wkwebview-engine
   from Cordova project:
   Cordova error: The plugin 'cordova-plugin-file' is required by (cordova-plugin-file-transfer, cordova-plugin-media-capture), skipping uninstallation. (try --force if trying to update)
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to help diagnose the issue.)
                                              
/Users/Nauzer/.meteor/packages/coffeescript/.1.0.17.imrcpv.7ig1q++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
ExitWithCode { code: 1 }

```

```
.meteor/local/cordova-build 
```
Does the trick but as @sajhu says it add a lot of unnecessary build time.

Tried moving the 'blocking' plugin to the bottom of the .meteor/cordova-plugins file but that doesn't seem to resolve it. In the list of plugins it tries to remove (logs above) its position remains unchanged...

**Comment by flean** [comment]
I run this and it fixes the problem
```rm -R .meteor/local/cordova-build/plugins/*/```

**Comment by hexsprite** [comment]
@flean yes, it's a good workaround but not ideal since it requires downloading and configuring the plugins fresh every time (slower than it needs to be)

**Comment by filipenevola** [comment]
Hey @hexsprite, @flean, @sajhu, @skirunman could you try on 1.10.3-beta.2? 

`meteor update --release 1.10.3-beta.2`

**Comment by hexsprite** [comment]
@filipenevola looks like it's fixed for me! thanks so much! 🚀
