### ISSUE TITLE
[1.10.1] No MongoDB writes possible after replica set failover

### ISSUE THREAD

**Issue by gbhrdt** [meteor/meteor#11037]
After a replica set failover and re-election of the primary node, we are getting the following error in the console.
Reads continue to work but all writes are timing out without any further errors.
We are not using Oplog tailing.

```
00:26:49
Exception while invoking method 'login' MongoError: Pool was force destroyed
00:26:49
at Pool.destroy (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:678:21)
00:26:49
at Server.destroy (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js:902:15)
00:26:49
at ReplSetState.update (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset_state.js:558:18)
00:26:49
at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:466:36
00:26:49
at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:404:18
00:26:49
at processTicksAndRejections (internal/process/task_queues.js:79:11)
00:26:49
=> awaited here:
00:26:49
at Function.Promise.await (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
00:26:49
at packages/mongo/mongo_driver.js:1049:14
00:26:49
at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
00:26:49
=> awaited here:
00:26:49
at Promise.await (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
00:26:49
at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1098:38)
00:26:49
at SynchronousCursor.SyncronousCursor._nextObject (packages/montiapm:agent/lib/hijack/db.js:235:33)
00:26:49
at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1112:22)
00:26:49
at SynchronousCursor.map (packages/mongo/mongo_driver.js:1122:10)
00:26:49
at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1146:17)
00:26:49
at Cursor.<computed> (packages/mongo/mongo_driver.js:894:44)
00:26:49
at Cursor.cursorProto.<computed> (packages/montiapm:agent/lib/hijack/db.js:144:32)
00:26:49
at Cursor.kadira_Cursor_fetch [as fetch] (packages/montiapm:agent/lib/hijack/set_labels.js:65:32)
00:26:49
at MongoConnection.findOne (packages/mongo/mongo_driver.js:801:56)
00:26:49
at Collection.findOne (packages/mongo/collection.js:356:29)
00:26:49
at userId (server/methods/sendEmail.js:41:18)
00:26:49
at packages/rate-limit/rate-limit.js:49:19
00:26:49
at Array.every (<anonymous>)
00:26:49
at Rule.match (packages/rate-limit/rate-limit.js:44:8)
00:26:49
at packages/rate-limit/rate-limit.js:249:58
00:26:49
at Array.filter (<anonymous>)
00:26:49
at RateLimiter._findAllMatchingRules (packages/rate-limit/rate-limit.js:249:38)
00:26:49
at RateLimiter.increment (packages/rate-limit/rate-limit.js:228:31)
00:26:49
at Object.DDPRateLimiter._increment (packages/ddp-rate-limiter.js:111:15)
00:26:49
at packages/ddp-server/livedata_server.js:703:26
00:26:49
at new Promise (<anonymous>)
00:26:49
at Session.method (packages/ddp-server/livedata_server.js:689:23)
00:26:49
at packages/montiapm:agent/lib/hijack/wrap_session.js:64:38
00:26:49
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
00:26:49
at Session.sessionProto.protocol_handlers.method (packages/montiapm:agent/lib/hijack/wrap_session.js:63:44)
00:26:49
at packages/ddp-server/livedata_server.js:559:43
```

```
Exception in setInterval callback: MongoError: Pool was force destroyed
at Pool.destroy (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:678:21)
at Server.destroy (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js:902:15)
at ReplSetState.update (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset_state.js:558:18)
at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:466:36
at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:404:18
at processTicksAndRejections (internal/process/task_queues.js:79:11)
=> awaited here:
at Function.Promise.await (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at packages/mongo/mongo_driver.js:1042:14
at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Promise.await (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1091:38)
at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1105:22)
at Cursor.<computed> [as forEach] (packages/mongo/mongo_driver.js:887:44)
at JobCollection._promote_jobs (packages/simonsimcity_job-collection/src/server.coffee:191:10)
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at packages/meteor.js:550:25
at runWithEnvironment (packages/meteor.js:1286:24) {
name: 'MongoError',
[Symbol(mongoErrorContextSymbol)]: {}
}
```

**Comment by filipenevola** [comment]
Hi @gbhrdt I know many projects in production where the failover is happening without any issues.

It seems to me this is a problem in your specific settings or in your MongoDB hosting.

Also the stacktrace shows MongoDB node driver code throwing the error and not Meteor specific code so I believe it would be better to open this issue here https://github.com/mongodb/node-mongodb-native

**Comment by haunguyen90** [comment]
Just curious why does it close without any solution ?
