### ISSUE TITLE
[1.10.2] ENOMEM building in CI

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#11050]
Been getting this error while building Meteor

```
Step #10 - "build-meteor": Error: spawn ENOMEM
Step #10 - "build-meteor":     at ChildProcess.spawn (internal/child_process.js:407:11)
Step #10 - "build-meteor":     at spawn (child_process.js:548:9)
Step #10 - "build-meteor":     at execFile (child_process.js:232:17)
Step #10 - "build-meteor":     at /builder/home/.meteor/packages/meteor-tool/.1.10.2.1rhc6rt.72i6++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:141:7
Step #10 - "build-meteor":     at new Promise (<anonymous>)
Step #10 - "build-meteor":     at Object.findGitCommitHash (/builder/home/.meteor/packages/meteor-tool/.1.10.2.1rhc6rt.72i6++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:138:10)
Step #10 - "build-meteor":     at /tools/isobuild/bundler.js:2942:66
Step #10 - "build-meteor":     at /tools/isobuild/bundler.js:3349:22
Step #10 - "build-meteor":     at Object.capture (/tools/utils/buildmessage.js:283:5)
Step #10 - "build-meteor":     at bundle (/tools/isobuild/bundler.js:3164:31)
...
```

I believe this did not occur in versions of Meteor that did not use Node 12 (< 1.9)

My suspicion is that when Meteor calls `execFile` to run git to get the commit hash this ends up exhausting memory due to this open Node bug: https://github.com/nodejs/node/issues/25382

Possible solutions:

- `exec` earlier to get Git Commit hash so that memory usage is lower.
- allow passing the git commit hash via a environment variable eg. `METEOR_GIT_COMMIT_HASH`
- Just read the .git directory directly to get the git hash. There's a simple JS-only library that should work seamlessly for that.

**Comment by hexsprite** [comment]
Looks like that environment variable already exists. Using it solved the issue for me...
