### ISSUE TITLE
Unable to start app following upgrade from v1.8.1 to v1.8.2

### ISSUE THREAD

**Issue by Ajaay** [meteor/meteor#11067]
Mac OS 10.13.2
Meteor working version 1.8.1
Broken version 1.8.2. Have tried upgrading to 1.8.3 but same issue.

When starting the app i get the following errors:

```
Alexs-MacBook-Pro:interview-platform alex$ meteor --mobile-server=127.0.0.1:3000 --settings settings-development.json
[[[[[ ~/interview-platform ]]]]]              

=> Started proxy.                             
/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at makeOptimistic (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/optimistic.ts:321:17)
    at wrap.makeCacheKey (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/optimistic.ts:36:15)
    at recomputeNewValue (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:182:31)
    at Slot.withValue (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at reallyRecompute (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:165:19)
    at Entry.recompute (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:85:9)
    at optimistic (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:101:25)
    at wrap (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/optimistic.ts:363:19)
    at recomputeNewValue (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:182:31)
    at Slot.withValue (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at reallyRecompute (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:165:19)
    at Entry.recompute (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:85:9)
    at optimistic (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:101:25)
    at find (/tools/isobuild/package-source.js:1286:25)
    at subdirectories.forEach.subdir (/tools/isobuild/package-source.js:1333:27)
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1312:22)
    at subdirectories.forEach.subdir (/tools/isobuild/package-source.js:1333:27)
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1312:22)
    at subdirectories.forEach.subdir (/tools/isobuild/package-source.js:1333:27)
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1312:22)
    at subdirectories.forEach.subdir (/tools/isobuild/package-source.js:1333:27)
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1312:22)
    at find (/tools/isobuild/package-source.js:1344:25)
    at files.withCache (/tools/isobuild/package-source.js:1356:34)
    at Object.withCache (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1647:18)
    at PackageSource._findSources (/tools/isobuild/package-source.js:1356:18)
    at SourceArch.getFiles (/tools/isobuild/package-source.js:912:32)
    at /tools/isobuild/compiler.js:406:23
    at files.withCache (/tools/isobuild/compiler.js:186:28)
    at Object.withCache (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1647:18)
    at /tools/isobuild/compiler.js:185:11
    at Function._.each._.forEach (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:186:9)
    at Object.compile (/tools/isobuild/compiler.js:180:5)
    at /tools/isobuild/bundler.js:3238:24
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3185:31)
    at files.withCache (/tools/isobuild/bundler.js:3130:32)
    at Slot.withValue (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at Object.withCache (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1647:39)
    at Object.bundle (/tools/isobuild/bundler.js:3130:16)
    at Profile.run (/tools/runners/run-app.js:572:24)
    at Function.run (/Users/alex/.meteor/packages/meteor-tool/.1.8.3.1qucsvl.k7om++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:571:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:613:35)
    at AppRunner._fiber (/tools/runners/run-app.js:929:28)
    at /tools/runners/run-app.js:401:12
```

I have tried `meteor reset` and removing and reinstalling Meteor with `curl https://install.meteor.com/ | sh` but no luck...

Thanks

**Comment by lnufnu** [comment]
Have you validated your `package.json` file? Do you have any trailing commas from removing a package?

**Comment by Ajaay** [comment]
Double checked and package.json is clean. All I did was `meteor update --release 1.8.2`

**Comment by Ajaay** [comment]
I started a fresh project and gradually added packages back in and looks to have been an issue with the version of meteor-desktop I was running.

Upgraded to the latest and app is now working.

Thanks
