### ISSUE TITLE
[1.9.2] MongoDB replica set failover caused production outage

### ISSUE THREAD

**Issue by MastroLindus** [meteor/meteor#11073]
I have a mongodb replica hosted on Atlas. Yesterday they did some maintance to the cluster and rolling restarted causing an election and a secondary becoming a new primary.
My production app got two errors from which it crashed without recovering:

```
message: connection 0 to ADDRESS:PORT closed
stack:
MongoNetworkError: connection 0 toADDRESS:PORT  closed
    at TLSSocket.<anonymous> (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:352:9)
    at Object.onceWrapper (events.js:418:26)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at net.js:668:12
    at TCP.done (_tls_wrap.js:556:7)
```

and 
```
message: not master and slaveOk=false
stack:
MongoError: not master and slaveOk=false
    at Connection.<anonymous> (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:443:61)
    at Connection.emit (events.js:311:20)
    at Connection.EventEmitter.emit (domain.js:482:12)
    at processMessage (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at TLSSocket.<anonymous> (/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
 => awaited here:
    at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at packages/mongo/mongo_driver.js:1037:14
    at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1086:38)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1100:22)
    at SynchronousCursor.map (packages/mongo/mongo_driver.js:1110:10)
    at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1134:17)
    at Cursor.<computed> (packages/mongo/mongo_driver.js:882:44)
    at Cursor.cursorProto.<computed> (packages/mdg:meteor-apm-agent/lib/hijack/db.js:131:32)
    at Cursor.kadira_Cursor_fetch [as fetch] (packages/mdg:meteor-apm-agent/lib/hijack/set_labels.js:72:32)
    at MongoConnection.findOne (packages/mongo/mongo_driver.js:789:56)
    at Collection.findOne (packages/mongo/collection.js:356:29)
    at isUserAllowedToSubscribe (imports/api/utils/server/PublicationUtils.ts:8:29)
    at Subscription.<anonymous> (imports/api/orders/server/OrdersPublications.ts:15:8)
    at packages/universe:i18n/server/syncServerWithClient.js:33:29
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Subscription._handler (packages/universe:i18n/server/syncServerWithClient.js:32:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
```

It seems related to this discussion, that never got some final answers:
https://forums.meteor.com/t/what-happens-to-meteor-during-a-mongodb-failover-event/9022/3

(in one of the comments there's a very similar error to mine)

**Comment by hexsprite** [comment]
Also running Atlas, had similar errors yesterday, was probably an automatic version update. It looks like the automatic retry is not working as this exception should not get raised at the application level...

<details>
<summary><code>MongoNetworkError: connection 9 to xxx.mongodb.net:27017 closed</code>
</summary>

```
MongoNetworkError: connection 9 to xxx.mongodb.net:27017 closed
1
at TLSSocket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js, line 372 col 8)
new MongoNetworkError(`connection ${conn.id} to ${conn.address} closed`),
2
at Object.onceWrapper (events.js, line 418 col 25)
3
at TLSSocket.emit (events.js, line 311 col 19)
4
at TLSSocket.EventEmitter.emit (domain.js, line 482 col 11)
5
at <unknown> (net.js, line 668 col 11)
6
at TCP.done (_tls_wrap.js, line 556 col 6)
7
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js, line 56 col 11)
return awaitPromise(this.resolve(arg));
8
at <unknown> (packages/mongo/mongo_driver.js, line 1073 col 13)
9
at <unknown> (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js, line 43 col 39)
entry.resolve(entry.callback.apply(
10
at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js, line 60 col 11)
return awaitPromise(this);
11
at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js, line 1122 col 37)
12
at SynchronousCursor.SyncronousCursor._nextObject (packages/montiapm:agent/lib/hijack/db.js, line 235 col 32)
13
at SynchronousCursor.forEach (packages/mongo/mongo_driver.js, line 1136 col 21)
14
at SynchronousCursor.map (packages/mongo/mongo_driver.js, line 1146 col 9)
15
at SynchronousCursor.fetch (packages/mongo/mongo_driver.js, line 1170 col 16)
16
at Cursor.<computed> (packages/mongo/mongo_driver.js, line 918 col 43)
17
at Cursor.MeteorCursor.<computed> (packages/peerlibrary_reactive-mongo/server.coffee, line 66 col 21)
18
at Cursor.cursorProto.<computed> (packages/montiapm:agent/lib/hijack/db.js, line 144 col 31)
19
at Cursor.kadira_Cursor_fetch [as fetch] (packages/montiapm:agent/lib/hijack/set_labels.js, line 65 col 31)
20
at MongoConnection.findOne (packages/mongo/mongo_driver.js, line 825 col 55)
21
at OptimizedApply (packages/montiapm:agent/lib/utils.js, line 47 col 16)
22
at Object.ret.<computed> [as findOne] (packages/montiapm:agent/lib/hijack/db.js, line 20 col 15)
23
at Collection.findOne (packages/mongo/collection.js, line 356 col 28)
....
```
</details>

<details>
<summary><code>MongoNetworkError: write EPIPE</code></summary>

```
MongoNetworkError: write EPIPE
1
at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js, line 92 col 15)
2
at writevGeneric (internal/stream_base_commons.js, line 132 col 25)
3
at TLSSocket.Socket._writeGeneric (net.js, line 778 col 10)
4
at TLSSocket.Socket._writev (net.js, line 787 col 7)
5
at doWrite (_stream_writable.js, line 439 col 11)
6
at clearBuffer (_stream_writable.js, line 557 col 4)
7
at onwrite (_stream_writable.js, line 492 col 6)
8
at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js, line 101 col 9)
9
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js, line 56 col 11)
return awaitPromise(this.resolve(arg));
10
at <unknown> (packages/mongo/mongo_driver.js, line 1073 col 13)
11
at <unknown> (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js, line 43 col 39)
entry.resolve(entry.callback.apply(
12
at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js, line 60 col 11)
return awaitPromise(this);
13
at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js, line 1122 col 37)
14
at SynchronousCursor.SyncronousCursor._nextObject (packages/montiapm:agent/lib/hijack/db.js, line 235 col 32)
15
at SynchronousCursor.forEach (packages/mongo/mongo_driver.js, line 1136 col 21)
16
at SynchronousCursor.map (packages/mongo/mongo_driver.js, line 1146 col 9)
17
at SynchronousCursor.fetch (packages/mongo/mongo_driver.js, line 1170 col 16)
18
at Cursor.<computed> (packages/mongo/mongo_driver.js, line 918 col 43)
19
at Cursor.MeteorCursor.<computed> (packages/peerlibrary_reactive-mongo/server.coffee, line 66 col 21)
20
at Cursor.cursorProto.<computed> (packages/montiapm:agent/lib/hijack/db.js, line 144 col 31)
21
at Cursor.kadira_Cursor_fetch [as fetch] (packages/montiapm:agent/lib/hijack/set_labels.js, line 65 col 31)
22
at MongoConnection.findOne (packages/mongo/mongo_driver.js, line 825 col 55)
23
at Collection.findOne (packages/mongo/collection.js, line 356 col 28)
```
</details>

<details>
<summary><code>MongoError: not master and slaveOk=false</code></summary>

```
MongoError: not master and slaveOk=false
1
at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js, line 450 col 60)
return handleOperationCallback(self, workItem.cb, new MongoError(responseDoc));
2
at Connection.emit (events.js, line 311 col 19)
3
at Connection.EventEmitter.emit (domain.js, line 482 col 11)
4
at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js, line 384 col 9)
conn.emit(
5
at TLSSocket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js, line 553 col 14)
processMessage(conn, emitBuffer);
6
at TLSSocket.emit (events.js, line 311 col 19)
7
at TLSSocket.EventEmitter.emit (domain.js, line 482 col 11)
8
at addChunk (_stream_readable.js, line 294 col 11)
9
at readableAddChunk (_stream_readable.js, line 275 col 10)
10
at TLSSocket.Readable.push (_stream_readable.js, line 209 col 9)
11
at TLSWrap.onStreamRead (internal/stream_base_commons.js, line 186 col 22)
12
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js, line 56 col 11)
return awaitPromise(this.resolve(arg));
13
at <unknown> (packages/mongo/mongo_driver.js, line 1073 col 13)
14
at <unknown> (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js, line 43 col 39)
entry.resolve(entry.callback.apply(
15
at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js, line 60 col 11)
return awaitPromise(this);
16
at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js, line 1122 col 37)
17
at SynchronousCursor.SyncronousCursor._nextObject (packages/montiapm:agent/lib/hijack/db.js, line 235 col 32)
18
at SynchronousCursor.forEach (packages/mongo/mongo_driver.js, line 1136 col 21)
19
at SynchronousCursor.map (packages/mongo/mongo_driver.js, line 1146 col 9)
20
at SynchronousCursor.fetch (packages/mongo/mongo_driver.js, line 1170 col 16)
21
at Cursor.<computed> (packages/mongo/mongo_driver.js, line 918 col 43)
22
at Cursor.MeteorCursor.<computed> (packages/peerlibrary_reactive-mongo/server.coffee, line 66 col 21)
23
at Cursor.cursorProto.<computed> (packages/montiapm:agent/lib/hijack/db.js, line 144 col 31)
24
at Cursor.kadira_Cursor_fetch [as fetch] (packages/montiapm:agent/lib/hijack/set_labels.js, line 65 col 31)
25
at MongoConnection.findOne (packages/mongo/mongo_driver.js, line 825 col 55)
26
at OptimizedApply (packages/montiapm:agent/lib/utils.js, line 47 col 16)
27
at Object.ret.<computed> [as findOne] (packages/montiapm:agent/lib/hijack/db.js, line 20 col 15)
28
at Collection.findOne (packages/mongo/collection.js, line 356 col 28)
```
</details>

**Comment by obonyojimmy** [comment]
I can assert to this too , in production server when replica-set does a re-election, meteor instance crashes and requires a reboot.

**Comment by hexsprite** [comment]
I'm still seeing these issues.

**Comment by cfnelson** [comment]
@hexsprite What version of MongoDB are you running on atlas?

I believe I had a similar related issue (couldn't get meteor to restart/reconnect after crash/redeploy) which was resolved by updating to [v1.9.3](https://github.com/meteor/meteor/blob/devel/History.md#v193-2020-03-09) which updated the mongodb drivers. 

The initial problem I experienced may have been triggered by a primary failing and a new primary being elected.

Not sure if it's relevant but we don't have any apm agent's installed which I noticed both stack traces contain.

**Comment by filipenevola** [comment]
I don't believe this is a Meteor issue as I don't have these issues on my apps when my primary changes. 

We need some reproduction steps and versions here to be able to narrow down this issue but I believe if this was a Meteor issue many would be facing this problem every week, at least my clusters on Atlas have different primaries at least once a week.

If we don't have more details I would have to close this issue.

**Comment by evolross** [comment]
> at least my clusters on Atlas have different primaries at least once a week.

Using Atlas here too. How do you detect this? Would be curious to see if my Atlas cluster's primary changes.

**Comment by gbhrdt** [comment]
> > at least my clusters on Atlas have different primaries at least once a week.
> 
> Using Atlas here too. How do you detect this? Would be curious to see if my Atlas cluster's primary changes.

You can see it in your Project's Activity Feed ("Replica set elected a new primary…").

**Comment by hexsprite** [comment]
This problem may be exacerbated by the issues with incomplete mongo tracebacks in Meteor. I opened issue #10941 about this. It's possible that solving that may allow us to see which DB operations in application code are erroring out in the failover situation.

**Comment by applew** [comment]
Anyone figure out how to resolve this? I had this problem on our production app today, and we are also hosted on Atlas.
At the time this happened I noticed in the activity feed "Replica set elected a new primary". 

Thank you for your feedback!

Our ec2 errors produced this message:
Got exception while reading last entry MongoError: Pool was force destroyed
    at Pool.destroy (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:678:21)
    at Server.destroy (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/server.js:902:15)
    at Timeout._onTimeout (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:356:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
 => awaited here:
    at Function.Promise.await (/var/app/current/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at packages/mongo/mongo_driver.js:1073:14
    at /var/app/current/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/var/app/current/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1122:38)
    at SynchronousCursor.SyncronousCursor._nextObject (packages/montiapm:agent/lib/hijack/db.js:235:33)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1136:22)
    at SynchronousCursor.map (packages/mongo/mongo_driver.js:1146:10)
    at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1170:17)
    at Cursor.<computed> (packages/mongo/mongo_driver.js:918:44)
    at Cursor.cursorProto.<computed> (packages/montiapm:agent/lib/hijack/db.js:144:32)
    at Cursor.kadira_Cursor_fetch [as fetch] (packages/montiapm:agent/lib/hijack/set_labels.js:65:32)
    at MongoConnection.findOne (packages/mongo/mongo_driver.js:825:56)
    at OplogHandle.waitUntilCaughtUp (packages/mongo/oplog_tailing.js:147:52)
    at OplogObserveDriver._doneQuerying (packages/mongo/oplog_observe_driver.js:798:36)
    at packages/mongo/oplog_observe_driver.js:700:14
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24) {
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {}
}

**Comment by slowdownitsfine** [comment]
Seeing the same error with hosted mongo at Atlas too, when election happened or a cluster update is started.

Currently on 1.9.2.

**Comment by applew** [comment]
Forgot to mention that I was running Meteor 1.10.1.

**Comment by po-jo** [comment]
Hello @applew, out of curiosity do you have this problem when you launch an Atlas 'test failover' ?

**Comment by KoenLav** [comment]
We're running Meteor 1.10.1 and are not experiencing this issue.

I believe it was related to the variant of the MONGO_URL used (we're using mongodb:// without +srv, explicitly mentioning all shards/replicas).

**Comment by MastroLindus** [comment]
We added &readPreference=primaryPreferred to the mongo_url and that allowed our app to survive several failovers in the recent weeks. If that's the solution I think it should be documented somewhere in the meteor guide

**Comment by applew** [comment]
Update, I ran the Atlas 'test failover' and everything worked just fine. I've set up some notifications for Atlas to notify me in the event of a failover, so I will continue to monitor this problem. 

I did revert away from using +svr in my MONGO_URL and listing out shards/replicas.

**Comment by slowdownitsfine** [comment]
> We added &readPreference=primaryPreferred to the mongo_url and that allowed our app to survive several failovers in the recent weeks. If that's the solution I think it should be documented somewhere in the meteor guide

this has worked for us in an election, thank you @MastroLindus!
