### ISSUE TITLE
choco install does not work for non priveliged users

### ISSUE THREAD

**Issue by bessw** [meteor/meteor#11070]
You recommend on your web page chocolatey to install meteor on windows but it only installs it for the user executing the command.

Running the installer as non privileged user does not work, thus it is not working on non privileged user accounts.

choco package version 0.0.2

# expected:
works on non privileged user accounts

**Comment by bessw** [comment]
I switched to WSL and the linux version, because the .exe installer also didn't work out of the box as non privileged user (probably it didn't set path, but I didn't want to investigate again)

**Comment by denihs** [comment]
Hi, it's expected to be a privileged user to install Meteor on Windows, but then later you can run without the privileges.

**Comment by bessw** [comment]
Running it later without privileges did not work for me, because it was not in my path and I couldn't just add the executable that was in admins path to my path because it was in its appdata.

**Comment by zodern** [comment]
@bessw would you be willing to try https://github.com/zodern/windows-meteor-installer/? It should work for users that are not admins.

**Comment by bessw** [comment]
I tried it, but got an error while installing:
```
npm i -g @zodern/windows-meteor-installer
C:\Users\<user>\AppData\Roaming\npm\meteorz -> C:\Users\<user>\AppData\Roaming\npm\node_modules\@zodern\windows-meteor-installer\meteor.bat

> @zodern/windows-meteor-installer@0.1.0 install C:\Users\<user>\AppData\Roaming\npm\node_modules\@zodern\windows-meteor-installer
> node install.js

=> Meteor Downloaded in 49.981s
=> Meteor Decompressed in 7.519s
Extracting |████████████████████████████████████████| 99% - 107671 files completedevents.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Can not create symbolic link : Dem Client fehlt ein erforderliches Recht. : C:\Users\<user>\AppData\Local\.meteor-z\.meteor\packages\webapp\1.9.1\npm\node_modules\.bin\mime
    at Object.fromBuffer (C:\Users\<user>\AppData\Roaming\npm\node_modules\@zodern\windows-meteor-installer\node_modules\node-7z\src\error.js:30:13)
    at C:\Users\<user>\AppData\Roaming\npm\node_modules\@zodern\windows-meteor-installer\node_modules\node-7z\src\events.js:25:19
    at Socket.stream._childProcess.stderr.on.chunk (C:\Users\<user>\AppData\Roaming\npm\node_modules\@zodern\windows-meteor-installer\node_modules\node-7z\src\lifecycle.js:64:51)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
    at C:\Users\<user>\AppData\Roaming\npm\node_modules\@zodern\windows-meteor-installer\node_modules\node-7z\src\events.js:90:12
    at ChildProcess.stream._childProcess.on (C:\Users\<user>\AppData\Roaming\npm\node_modules\@zodern\windows-meteor-installer\node_modules\node-7z\src\lifecycle.js:66:42)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.cp.emit (C:\Users\<user>\AppData\Roaming\npm\node_modules\@zodern\windows-meteor-installer\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @zodern/windows-meteor-installer@0.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @zodern/windows-meteor-installer@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2020-06-02T18_27_28_584Z-debug.log
```
