### ISSUE TITLE
can't upgrade to 1.11.1 from 1.8.1

### ISSUE THREAD

**Issue by yuwiggin** [meteor/meteor#11185]
My app can't start locally when upgraded to 1.11 (or 1.11.1). It can start successfully in the release METEOR@1.8.1, or 1.9.x
My operating system: macOS 10.12.6 .  The console logged the following:

```
=> Started proxy.                             
=> Started MongoDB.                           
/Users/viking/.meteor/packages/static-html/.1.2.2.71jg1a.aihwh++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: already recomputing
    at assert (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:13:11)
    at Entry.recompute (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:82:5)
    at Resolver.optimistic [as resolve] (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:101:25)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/resolver.ts:168:20
    at Array.some (<anonymous>)
    at Resolver.resolve (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/resolver.ts:160:59)
    at Resolver.resolve.wrap.makeCacheKey (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/resolver.ts:82:22)
    at recomputeNewValue (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:182:31)
    at Slot.withValue (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at reallyRecompute (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:165:19)
    at Entry.recompute (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:85:9)
    at Resolver.optimistic [as resolve] (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:101:25)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/resolver.ts:168:20
    at Array.some (<anonymous>)
    at Resolver.resolve (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/resolver.ts:160:59)
    at Resolver.resolve.wrap.makeCacheKey (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/resolver.ts:82:22)
    at recomputeNewValue (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:182:31)
    at Slot.withValue (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at reallyRecompute (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:165:19)
    at Entry.recompute (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:85:9)
    at Resolver.optimistic [as resolve] (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:101:25)
    at ImportScanner.resolve (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1002:36)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1114:29
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1156:12
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1156:12
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1156:12
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1156:12
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1156:12
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1156:12
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1142:14
    at _.each._.forEach (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at ImportScanner.scanFile (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:1105:5)
    at /Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:740:14
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/isobuild/tools/isobuild/import-scanner.ts:738:22)
    at /tools/isobuild/compiler-plugin.js:1360:17
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1325:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1137:8)
    at /tools/isobuild/bundler.js:856:12
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:844:18)
    at /tools/isobuild/bundler.js:3188:14
    at /tools/isobuild/bundler.js:3340:25
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3294:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3169:31)
    at /tools/isobuild/bundler.js:3113:32
    at Slot.withValue (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at Object.withCache (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1659:39)
    at Object.bundle (/tools/isobuild/bundler.js:3113:16)
    at /tools/runners/run-app.js:572:24
    at Function.run (/Users/viking/.meteor/packages/meteor-tool/.1.11.0.1naq3wu.kxks++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:571:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:931:28)
    at /tools/runners/run-app.js:401:12
```
Here is the `package.json` :

```
{
  "name": "crex828",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --once --driver-package meteortesting:mocha",
    "test-app": "TEST_WATCH=1 meteor test --full-app --driver-package meteortesting:mocha",
    "visualize": "meteor --production --extra-packages bundle-visualizer"
  },
  "dependencies": {
    "@babel/runtime": "^7.10.5",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@truffle/contract": "^4.2.20",
    "bcrypt": "^5.0.0",
    "bs58": "^4.0.1",
    "eth-sig-util": "^2.5.3",
    "ipfs-http-client-lite": "^0.3.0",
    "material-table": "^1.69.0",
    "meteor-node-stubs": "^1.0.1",
    "mmmagic": "^0.5.3",
    "react": "^16.13.1",
    "react-copy-to-clipboard": "^5.0.2",
    "react-dom": "^16.13.1",
    "react-intl": "^5.7.2",
    "react-number-format": "^4.4.1",
    "react-redux": "^7.2.1",
    "react-router-dom": "^5.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "simpl-schema": "^1.9.0",
    "web3": "^1.2.11"
  },
  "meteor": {
    "mainModule": {
      "client": "client/main.jsx",
      "server": "server/main.js"
    },
    "testModule": "tests/main.js"
  }
}
```

**Comment by filipenevola** [comment]
Hi @yuwiggin are you still unable to upgrade to latest Meteor?
