### ISSUE TITLE
HTTP.call content type validation

### ISSUE THREAD

**Issue by Sikhi** [meteor/meteor#11195]
https://github.com/meteor/meteor/blob/7427525de2d0b6b68e3b73d50e885c396c291fd1/packages/http/httpcall_server.js#L42

Pls make content type validation. without validation in some cases we can throw ugly error from vault, like errors bellow.
It happened when put object in content, not in params with POST request.
>req.grant_type = "authorization_code";
>req.client_id = "someid";

> HTTP.post(endpoint, {
>        content: req,
>        headers: _headers
>    }, callback);

Throw error:
>W20201002-19:15:48.934(3)? (STDERR) _http_outgoing.js:653
>W20201002-19:15:48.936(3)? (STDERR)     throw new ERR_INVALID_ARG_TYPE('first argument',
>W20201002-19:15:48.937(3)? (STDERR)     ^
>W20201002-19:15:48.938(3)? (STDERR)
>W20201002-19:15:48.939(3)? (STDERR) TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received an instance of Object
>W20201002-19:15:48.940(3)? (STDERR)     at write_ (_http_outgoing.js:653:11)
>W20201002-19:15:48.941(3)? (STDERR)     at ClientRequest.write (_http_outgoing.js:621:15)
>W20201002-19:15:48.945(3)? (STDERR)     at Request.write (/home/grimnir/.meteor/packages/http/.1.4.2.1fotq9x.lz1d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1500:27)
>W20201002-19:15:48.945(3)? (STDERR)     at end (/home/grimnir/.meteor/packages/http/.1.4.2.1fotq9x.lz1d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:549:18)
>W20201002-19:15:48.946(3)? (STDERR)     at Immediate._onImmediate (/home/grimnir/.meteor/packages/http/.1.4.2.1fotq9x.lz1d++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:578:7)
>W20201002-19:15:48.947(3)? (STDERR)     at processImmediate (internal/timers.js:456:21) {
>W20201002-19:15:48.947(3)? (STDERR)   code: 'ERR_INVALID_ARG_TYPE'
>W20201002-19:15:48.948(3)? (STDERR) }

**Comment by Sikhi** [comment]
thx. to my mind better (from performance point of view, but I'm not an expert in JS)
> var content;
> somevalidation { content = stringify }
> else content = options.content
but thx again:)
