### ISSUE TITLE
Build issue with meteor production build and npm devDependency

### ISSUE THREAD

**Issue by dolle39** [meteor/meteor#11234]
I have struggled with a build issue of meteor after upgrading to Meteor 1.11.1. Last version I ran was 1.8.0 so I am not sure if this is related to 1.11.1 or if it came earlier.

I have made a simple project at [here at gitlab](https://github.com/dolle39/meteor-build-issue ) which reproduces the issue.

The problem occurs if I add a devDependency such as puppeteer in **package.json**  as follows:

```
{
  "name": "app",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --once --driver-package meteortesting:mocha",
    "test-app": "TEST_WATCH=1 meteor test --full-app --driver-package meteortesting:mocha",
    "visualize": "meteor --production --extra-packages bundle-visualizer"
  },
  "dependencies": {
    "@babel/runtime": "^7.11.2",
    "jquery": "^3.5.1",
    "meteor-node-stubs": "^1.0.1"
  },
  "meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "testModule": "tests/main.js"
  },
  "devDependencies": {
    "puppeteer": "^1.20.0"
  }
}

```

When I then build a bundle of the app I run the following:

* meteor npm install
* After this the package-lock.json is created
* meteor npm ci --only=production  (for the production bundle I dont want to include dev dependencies)
* meteor build ~/builds --architecture os.linux.x86_64

This fails with the following error:

``` TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at Object.relative (path.js:1054:5)
    at Object.wrapper [as pathRelative] (~/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/static-assets/server/tools/static-assets/server/mini-files.ts:107:14)
...
...
```

After many hours of investigation I found a solution for this:

* First delete the node_modules folder. (this makes the trick)
* meteor npm ci --only=production  (for the production bundle I dont want to include dev dependencies)
* meteor build ~/builds --architecture os.linux.x86_64

This will work. However I dont understand why it works. `meteor npm ci --only=production` logs the following message:

```
npm WARN prepare removing existing node_modules/ before installation
``` 
but that does not seem to be true since it only works if I manually remove it.

So the solution is to manually remove the node_modules folder before I can bundle the app.  **NOTE:** The problem only occurs if I first run `meteor npm install` and the run the bundle procedure above.

Also, if I only run 
* meteor npm install
* meteor build ~/builds --architecture os.linux.x86_64

it also builds. So the problem only arises if I try to exclude the devDepency using the `production` flag after first having run meteor npm install.

I have a workaround solution to always remove the `node_modules` folder but I previously never had to do that so this looks like some kind of bug to me. I dont know if it is meteor or if it has something to do with node/npm itself.

To reproduce. Checkout the repo above.
Run:
* cd meteor-build-issue/app
* meteor npm install
* meteor npm ci --only=production  (for the production bundle I dont want to include dev dependencies)
* meteor build ~/builds --architecture os.linux.x86_64

I wanted to list this as a issue since I guess more users might experience this issue. It tooked me a whole day to understand when the problem occurred and why.

**Comment by italojs** [comment]
Closing the issue until we have a reproducible script or project for Meteor 3.x.
