### ISSUE TITLE
SSR import css in component

### ISSUE THREAD

**Issue by eugle** [meteor/meteor#11289]
we try to to setup a meteor app with server side rendering, now we get a unexpected token error when we try to load a css file from a node module in a component like this.

```
import 'antd/dist/antd.css';
```

error

```
/Users/eugle/Documents/git/jimuku/client/node_modules/antd/dist/antd.css:13
[class^=ant-]::-ms-clear,
      ^^

SyntaxError: Unexpected token '^='
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.Mp._compile (/Users/eugle/Documents/git/jimuku/client/.meteor/local/build/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Module.Mp.load (/Users/eugle/Documents/git/jimuku/client/.meteor/local/build/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at npmRequire (/Users/eugle/Documents/git/jimuku/client/.meteor/local/build/programs/server/npm-require.js:133:12)
    at Module.useNode (packages/modules-runtime.js:664:18)
    at module (packages/modules.js:1610:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/eugle/.meteor/packages/modules/.0.15.0.f7iysk.fjit++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
    at module (imports/ui/layout/App.jsx:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/eugle/.meteor/packages/modules/.0.15.0.f7iysk.fjit++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
    at module (imports/startup/server/ssr.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

is it not possible to do this with ssr? do I need to copy the css files into the project ?

A similar problem: [9758](https://github.com/meteor/meteor/issues/9758)

We have always used the lifecycle and client-side approach to solve this problem：

```
//ant style
	useEffect(() => {
		if (Meteor.isClient) {
			import 'antd/dist/antd.css';
		}
	}, []);
```

However, this leads to another problem, which is that the server, for reasons I don't understand, gets this path. But if you look at the URL, you see that you've got the wrong address, This should be caused by importing CSS in the clever way above
 
```
console.log(sink.request.url);
```

```
I20210117-11:31:54.754(8)? Url {
I20210117-11:31:54.755(8)?   protocol: null,
I20210117-11:31:54.755(8)?   slashes: null,
I20210117-11:31:54.755(8)?   auth: null,
I20210117-11:31:54.755(8)?   host: null,
I20210117-11:31:54.756(8)?   port: null,
I20210117-11:31:54.756(8)?   hostname: null,
I20210117-11:31:54.756(8)?   hash: null,
I20210117-11:31:54.756(8)?   search: null,
I20210117-11:31:54.756(8)?   query: [Object: null prototype] {},
I20210117-11:31:54.756(8)?   pathname: '/antd.css.map',
I20210117-11:31:54.756(8)?   path: '/antd.css.map',
I20210117-11:31:54.756(8)?   href: '/antd.css.map'
I20210117-11:31:54.757(8)? }
```
This is weird

I think there should be a correct way to exclude CSS, window, document and other APIs that cannot be executed on the server side under the condition that SSR is enabled. I pleas there can be a common method for judging the server side and the client side. If there is one, I pleas someone will tell me to know，thank you ver mach.

**Comment by filipenevola** [comment]
Hi @eugle I believe you are right but could you provide a reproduction?

So we can know more sure when this is solved. Thanks.

**Comment by eugle** [comment]
Thank you for reply，I don't know how to provide that, but it's easy to reproduce the problem, just try to use window,document, or CSS files in any Meteor project that contains SSRs and you get an error, right

**Comment by macrozone** [comment]
same issue was raised some years ago: https://github.com/meteor/meteor/issues/9758

**Comment by eugle** [comment]
I know that post, and I’ve read it several times, everyone’s answers

I don’t know how you solved it, I did solve this problem through this method, maybe this is the only solution

```
    useEffect(() => {
        if (Meteor.isClient) {
            import 'antd/lib/progress/style';
        }
    }, [])
```

**Comment by eugle** [comment]
But this solution is very bad for ssr, as said, it will cause the page to re-render

So here, there is a similar discussion [54012](https://forums.meteor.com/t/css-files-in-meteor-react-ssr/54012/25)

**Comment by eugle** [comment]
@filipenevola  see [9758](https://github.com/meteor/meteor/issues/9758) :)

This is in fact quite easy to reproduce and will affect anybody trying to use SSR with a CSS framework.
Here is how I reproduced it using bulma as an example:

meteor create ssr-example
meteor npm i bulma
meteor add server-render
in server/main.js add the following:
import { onPageLoad } from 'meteor/server-render'
onPageLoad((sink) => {
import('bulma/css/bulma.css').then((bulma) => {
sink.appendToHead(`<style>${bulma.default}</style>`);
sink.appendToBody('<button class="button is-primary">Bulma button</button>')
})
})
open localhost:3000 in your browser
=> error thrown in the server console
UnhandledPromiseRejectionWarning: ~/ssr-example/node_modules/bulma/css/bulma.css:2
@-webkit-keyframes spinAround {

I think most devs would assume this to work in an SSR scenario.

**Comment by minhna** [comment]
I have the same issue when trying to import
```
  import 'react-phone-input-2/lib/material.css';
```
Had to do this to fix SSR issue
```
if (Meteor.isClient) {
  import 'react-phone-input-2/lib/material.css';
}
```

**Comment by nathanschwarz** [comment]
CSS files are not compiled server side, so you wont be able to use it there.
Either use `styled-components`, inline styling, or put your css files in the public directory and import them through a link.

**Comment by Saeeed-B** [comment]
@filipenevola @nathanschwarz @minhna @eugle 
This issue must be resolved because ssr violates.
The user experience in ssr is good when it sees the right styles
See what happens when the server does not compile the styles.
The server only renders the styles in my main.css file.
And this is very bad because we have to put all the styles in this file, which slows down the site.

**Comment by italojs** [comment]
[Abandoned]  
Please inform us if this occurs in Meteor 3.x.
