### ISSUE TITLE
Meteor run crashes when public has any file over 1.7gb in it

### ISSUE THREAD

**Issue by queso** [meteor/meteor#1129]
When I put a file that is over 1.7gb into public, it seems that meteor tries to read the file into memory and crashes.  I have attached the output from the crash and you can also see the line where it crashes: https://github.com/meteor/meteor/blob/a33fcf6d8cef8486ffd4bce549645624fb23a0e3/tools/files.js#L370.  Note the comment mentioning the lameness :)

````
=> Errors prevented startup:
Exception while bundling application:
RangeError: length > kMaxLength
    at new Buffer (buffer.js:243:21)
    at Object.fs.readFileSync (fs.js:200:14)
    at _.extend.cp_r (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/tools/files.js:370:40)
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object._.extend.cp_r (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/tools/files.js:352:7)
    at _.extend.cp_r (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/tools/files.js:362:34)
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object._.extend.cp_r (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/tools/files.js:352:7)
    at _.extend.write_to_directory (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/tools/bundler.js:661:17)
    at Object.exports.bundle (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/tools/bundler.js:887:12)
    at /Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/tools/run.js:694:26
    at exports.inFiber (/Users/josh/.meteorite/meteors/meteor/meteor/5d736d4bf0448c7db1f9b47124dfafc34a9631bb/tools/fiber-helpers.js:24:12)
=> Your application is crashing. Waiting for file change.
````

**Comment by glasser** [comment]
This is a special case of #3014 (though this one is a "doesn't work" and that one is "performs poorly").

**Comment by ThomasArbona** [comment]
I don't understand how to have more than 1.7gb accessible from client ? 
Personally i have more than 2gb of pictures in /public folder for the client, and meteor crash with ENOMEM error, where should I put this pictures ?

**Comment by dcsan** [comment]
@ThomasArbona you could put the files on a different server or a CDN. meteor should not be used for serving just static images anyway, its not that efficient. 
you could even post them on github pages and just use github hosting, and easy repo control, for free :)

**Comment by ChristianKniep** [comment]
I got the same issue. How to cope with that now? 
```
root@c87963b11b14:/var/www/rocket.chat# meteor build --server "$HOST" --directory .
rocketchat:file: updating npm dependencies -- mkdirp, gridfs-stream, gm...

/root/.meteor/packages/meteor-tool/.1.1.4.fmoxzs++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EXDEV, rename '/var/www/rocket.chat/packages/rocketchat-file/.npm/package'
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.4.fmoxzs++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
```

**Comment by laosb** [comment]
1.7gb is really something unexpected in `/public`. For larger statics, we should just use other services to do that.
