### ISSUE TITLE
Importing Meteor packages from /src/node_modules fails on server

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#11319]
I noticed importing any Meteor packages from modules in nested `node_modules` folders (_I'm talking about a file in `/app/src/node_modules/my-pkg/`, not the `node_modules` in project's root_) will throw

```
Error: Cannot find module 'meteor/meteor'
```

...when imported on the server side. On the client it seems to work fine.

- The version of Meteor showing the problem: **2.0.0**
- The operating system you're running Meteor on: **Mac OS Mojave**
- The expected behavior: **I'd expect to be able to import `{ Meteor }`**
- The actual behavior: **I'm not able to import `{ Meteor }`**
- Reproduction: https://github.com/arggh/meteor-node-modules-import-issue

## How to

1. Clone the repo
2. npm install
3. npm start

**Comment by filipenevola** [comment]
@arggh I didn't find your `auth` node module declared in your package.json, where is it coming from?

If I try to run your project I got errors saying that I don't have `errors` module in the client and `auth` module in the server. Maybe the reproduction is missing a commit?


```txt
➜  meteor-node-modules-import-issue git:(master) meteor npm install
added 79 packages from 64 contributors and audited 79 packages in 1.685s
found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
➜  meteor-node-modules-import-issue git:(master) meteor npm start

> meteor-node-modules-import-issue@ start /Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue
> meteor run

[[[[[ ~/Documents/meteor/ws/tests/meteor-node-modules-import-issue ]]]]]

=> Started proxy.                             
=> Meteor 2.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
                                              
Unable to resolve some modules:

  "errors" in                                 
/Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/client/main.js
(web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save errors            
                                              
                                              
Unable to resolve some modules:

  "errors" in                                 
/Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/client/main.js
(web.browser.legacy)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save errors            
                                              
                                              
Unable to resolve some modules:

  "auth" in                                   
/Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/server/main.js
(os.osx.x86_64)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save auth              
                                              
W20210318-19:28:47.938(-4)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20210318-19:28:48.033(-4)? (STDERR) While this implementation will work correctly, it is known to be
W20210318-19:28:48.033(-4)? (STDERR) approximately three times slower than the native implementation.
W20210318-19:28:48.034(-4)? (STDERR) In order to use the native implementation instead, run
W20210318-19:28:48.034(-4)? (STDERR) 
W20210318-19:28:48.034(-4)? (STDERR)   meteor npm install --save bcrypt
W20210318-19:28:48.034(-4)? (STDERR) 
W20210318-19:28:48.034(-4)? (STDERR) in the root directory of your application.
W20210318-19:28:48.568(-4)? (STDERR) /Users/filipe/.meteor/packages/meteor-tool/.2.0.0.19012qi.lyz8++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20210318-19:28:48.569(-4)? (STDERR) 						throw(ex);
W20210318-19:28:48.569(-4)? (STDERR) 						^
W20210318-19:28:48.569(-4)? (STDERR) 
W20210318-19:28:48.569(-4)? (STDERR) Error: Cannot find module 'auth'
W20210318-19:28:48.570(-4)? (STDERR) Require stack:
W20210318-19:28:48.570(-4)? (STDERR) - /Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/boot.js
W20210318-19:28:48.570(-4)? (STDERR) - /Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/main.js
W20210318-19:28:48.570(-4)? (STDERR)     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
W20210318-19:28:48.570(-4)? (STDERR)     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
W20210318-19:28:48.570(-4)? (STDERR)     at Object.require (/Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/boot.js:286:34)
W20210318-19:28:48.570(-4)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:618:18)
W20210318-19:28:48.571(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:244:14)
W20210318-19:28:48.571(-4)? (STDERR)     at Module.moduleLink [as link] (/Users/filipe/.meteor/packages/modules/.0.16.0.hebza9.gspxj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210318-19:28:48.571(-4)? (STDERR)     at module (server/main.js:1:161)
W20210318-19:28:48.571(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210318-19:28:48.571(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210318-19:28:48.571(-4)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20210318-19:28:48.571(-4)? (STDERR)     at /Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/app/app.js:66:15
W20210318-19:28:48.572(-4)? (STDERR)     at /Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/boot.js:401:38
W20210318-19:28:48.572(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20210318-19:28:48.572(-4)? (STDERR)     at /Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/boot.js:226:21
W20210318-19:28:48.572(-4)? (STDERR)     at /Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/boot.js:464:7
W20210318-19:28:48.572(-4)? (STDERR)     at Function.run (/Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/profile.js:280:14)
W20210318-19:28:48.572(-4)? (STDERR)     at /Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/boot.js:463:13 {
W20210318-19:28:48.572(-4)? (STDERR)   code: 'MODULE_NOT_FOUND',
W20210318-19:28:48.572(-4)? (STDERR)   requireStack: [
W20210318-19:28:48.573(-4)? (STDERR)     '/Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/programs/server/boot.js',
W20210318-19:28:48.573(-4)? (STDERR)     '/Users/filipe/Documents/meteor/ws/tests/meteor-node-modules-import-issue/.meteor/local/build/main.js'
W20210318-19:28:48.573(-4)? (STDERR)   ]
W20210318-19:28:48.573(-4)? (STDERR) }
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by arggh** [comment]
> @arggh I didn't find your auth node module declared in your package.json, where is it coming from?

Sorry, an over-eager `.gitignore` rule had caused those files to be omitted from the repo and I was too hasty & didn't notice. Fixed now.

**Comment by filipenevola** [comment]
Hmm, this is the first time I see `node_modules` in sub-folder of an application.

Is this expected by other builders/compilers? Did you have any documentation about this usage?

**Comment by arggh** [comment]
> Is this expected by other builders/compilers? Did you have any documentation about this usage?

It was initially discussed and implemented by @benjamn here: https://github.com/meteor/meteor/issues/10664

**Comment by StorytellerCZ** [comment]
I have checked and @benjamn's code is still there so the issue has to be somewhere else. A wild guess is that it might be related to some changes @zodern made for HMR or other optimization efforts hat have been done since...

**Comment by italojs** [comment]
abandoned, let us know if it happens in Meteor 3.x
