### ISSUE TITLE
Cannot read property 'constructor' of undefined 

### ISSUE THREAD

**Issue by yuniit** [meteor/meteor#11326]
After update meteor from version 1.8.2 to 2.0 I got the following error when run meteor:

```js
W20210222-16:15:40.085(7)? (STDERR) /home/rabbit/.meteor/packages/meteor-tool/.2.0.0.rntudk.bjt8m++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20210222-16:15:40.125(7)? (STDERR) 						throw(ex);
W20210222-16:15:40.125(7)? (STDERR) 						^
W20210222-16:15:40.125(7)? (STDERR) 
W20210222-16:15:40.126(7)? (STDERR) TypeError: Cannot read property 'constructor' of undefined
W20210222-16:15:40.126(7)? (STDERR)     at packages/peerlibrary_subscription-scope.js:79:32
W20210222-16:15:40.126(7)? (STDERR)     at packages/peerlibrary_subscription-scope.js:119:4
W20210222-16:15:40.126(7)? (STDERR)     at packages/peerlibrary_subscription-scope.js:523:3
W20210222-16:15:40.126(7)? (STDERR)     at /home/rabbit/Desktop/new-restaurant/.meteor/local/build/programs/server/boot.js:401:38
W20210222-16:15:40.127(7)? (STDERR)     at Array.forEach (<anonymous>)
W20210222-16:15:40.127(7)? (STDERR)     at /home/rabbit/Desktop/new-restaurant/.meteor/local/build/programs/server/boot.js:226:21
W20210222-16:15:40.127(7)? (STDERR)     at /home/rabbit/Desktop/new-restaurant/.meteor/local/build/programs/server/boot.js:464:7
W20210222-16:15:40.127(7)? (STDERR)     at Function.run (/home/rabbit/Desktop/new-restaurant/.meteor/local/build/programs/server/profile.js:280:14)
W20210222-16:15:40.127(7)? (STDERR)     at /home/rabbit/Desktop/new-restaurant/.meteor/local/build/programs/server/boot.js:463:13
```

run **meteor list** show:
```js

accounts-base                    1.8.0  A user account system
accounts-password                1.7.0  Password support for accounts
akryum:vue-component             0.15.2  VueJS single-file components that hot-reloads
akryum:vue-less                  0.2.1  Add less support for vue components
akryum:vue-sass                  0.1.2  Add sass and scss support for vue components
alanning:roles                   1.2.19* Authorization package for Meteor
aldeed:collection2-core          2.1.2  Core package for aldeed:collection2
aldeed:schema-deny               3.0.0  Deny inserting or updating certain properties through schema options
aldeed:schema-index              3.0.0  Control some MongoDB indexing with schema options
cfs:filesystem                   0.1.2* Filesystem storage adapter for CollectionFS
cfs:standard-packages            0.5.10* Filesystem for Meteor, collectionFS
check                            1.3.1  Check whether a value matches a pattern
cultofcoders:grapher             1.3.9_1* Grapher is a data fetching layer on top of Meteor
cultofcoders:mocha               2.4.6  Write package tests with mocha and run them in the browser or from the command line with spacejam.
cultofcoders:persistent-session  0.4.5  Persistently store Session data on the client
ddp-rate-limiter                 1.0.9  The DDPRateLimiter allows users to add rate limits to DDP methods and subscriptions.
didericis:callpromise-mixin      0.0.1  A mixin for the mdg:validated-method package that adds a callPromise method
dynamic-import                   0.6.0  Runtime support for Meteor 1.5 dynamic import(...) syntax
ecmascript                       0.15.0  Compiler plugin that supports ES2015+ in all .js files
ejson                            1.1.1  Extended and Extensible JSON library
es5-shim                         4.8.0  Shims and polyfills to improve ECMAScript 5 support
fourseven:scss                   4.12.0  Style with attitude. Sass and SCSS support for Meteor.js.
http                             1.4.3  Make HTTP calls to remote servers
less                             2.8.0* Leaner CSS language
mdg:validated-method             1.2.0  A simple wrapper for Meteor.methods
meteor-base                      1.4.0  Packages that every Meteor app needs
mobile-experience                1.1.0  Packages for a great mobile user experience
mongo                            1.10.1  Adaptor for using MongoDB and Minimongo over DDP
nathantreid:static-assets        0.1.0  Import any static assets you like!
ongoworks:security               2.1.0  Logical security for client-originated MongoDB collection operations
ostrio:meteor-root               1.0.8  [Server] Get path on a server where Meteor application is currently running
pfafman:filesaver                1.3.2  filesaver.js packaged for use in Meteor.
reywood:publish-composite        1.7.3  Publish a set of related documents from multiple collections with a reactive join
sakulstra:aggregate              1.4.3  Proper MongoDB aggregations support for Meteor
session                          1.2.0  Session variable
shell-server                     0.5.0  Server-side component of the `meteor shell` command.
simple:json-routes               2.1.0  The simplest way to define server-side routes that return JSON
standard-minifier-css            1.7.2  Standard css minifier used with Meteor apps by default.
standard-minifier-js             2.6.0  Standard javascript minifiers used with Meteor apps by default.
static-html                      1.2.2  Define static page content in .html files
theara:collection-behaviours     0.0.5+ Extends Mongo.Collection with behaviour patterns
tracker                          1.2.0  Dependency tracker to allow reactive callbacks
xolvio:cleaner                   0.4.0  Gives you methods to clear your Mongo database and collections for testing purposes
zuuk:stale-session               1.0.9  Stale session and session timeout handling for meteorjs

```
I can't reproduce a repository but I hope the information above is enough.

**Comment by yuniit** [comment]
I got it worked from  [here](https://forums.meteor.com/t/solved-get-error-after-upgrade-to-meteor1-8-cannot-read-property-constructor-of-undefined-at-packages-peerlibrary-subscription-scope/46868)
