### ISSUE TITLE
Gettig issue in fresh install meteor 2.1 in windows 10

### ISSUE THREAD

**Issue by wekex35** [meteor/meteor#11337]
Errors prevented isopacket load:

While loading isopacket `combined`:

C:\Users\wekex\AppData\Local\.meteor\packages\meteor-tool\2.1.0\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1183:25:
sourcemapConsumer.destroy is not a function
at
C:\Users\wekex\AppData\Local\.meteor\packages\meteor-tool\2.1.0\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1183:25
at Function.time
(C:\Users\wekex\AppData\Local\.meteor\packages\meteor-tool\2.1.0\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:284:12)
at Object.runJavaScript
(C:\Users\wekex\AppData\Local\.meteor\packages\meteor-tool\2.1.0\mt-os.windows.x86_64\tools\fs\tools\fs\files.ts:1160:18)
at C:\tools\isobuild\bundler.js:2228:15
at Function._.each._.forEach
(C:\Users\wekex\AppData\Local\.meteor\packages\meteor-tool\2.1.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:186:9)
at JsImage.load (C:\tools\isobuild\bundler.js:2088:7)
at C:\tools\tool-env\isopackets.js:312:17
at Object.capture (C:\tools\utils\buildmessage.js:283:5)
at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:309:31)
at C:\tools\tool-env\isopackets.js:113:9
at loadIsopackage (C:\tools\tool-env\isopackets.js:104:21)
at new ServiceConnection (C:\tools\meteor-services\service-connection.js:28:21)
at Object.exports.openServiceConnection (C:\tools\meteor-services\auth-client.js:12:10)
at openPackageServerConnection (C:\tools\packaging\package-client.js:23:21)
at _updateServerPackageData (C:\tools\packaging\package-client.js:151:14)
at C:\tools\packaging\package-client.js:129:12
at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
at Object.exports.updateServerPackageData (C:\tools\packaging\package-client.js:128:23)
at C:\tools\packaging\catalog\catalog-remote.js:782:36
at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
at RemoteCatalog.refresh (C:\tools\packaging\catalog\catalog-remote.js:781:18)
at Object.catalog.refreshOrWarn (C:\tools\packaging\catalog\catalog.js:48:22)
at catalog.Refresh.OnceAtStart.beforeCommand (C:\tools\packaging\catalog\catalog.js:21:16)
at C:\tools\cli\main.js:1523:32
at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
at C:\tools\cli\main.js:1522:20

C:\Users\wekex\AppData\Local\.meteor\packages\meteor-tool\2.1.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: isopacket load failed?
    at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:320:11)
    at C:\tools\tool-env\isopackets.js:113:9
    at loadIsopackage (C:\tools\tool-env\isopackets.js:104:21)
    at new ServiceConnection (C:\tools\meteor-services\service-connection.js:28:21)
    at Object.exports.openServiceConnection (C:\tools\meteor-services\auth-client.js:12:10)
    at openPackageServerConnection (C:\tools\packaging\package-client.js:23:21)
    at _updateServerPackageData (C:\tools\packaging\package-client.js:151:14)
    at C:\tools\packaging\package-client.js:129:12
    at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
    at Object.exports.updateServerPackageData (C:\tools\packaging\package-client.js:128:23)
    at C:\tools\packaging\catalog\catalog-remote.js:782:36
    at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
    at RemoteCatalog.refresh (C:\tools\packaging\catalog\catalog-remote.js:781:18)
    at Object.catalog.refreshOrWarn (C:\tools\packaging\catalog\catalog.js:48:22)
    at catalog.Refresh.OnceAtStart.beforeCommand (C:\tools\packaging\catalog\catalog.js:21:16)
    at C:\tools\cli\main.js:1523:32
    at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
    at C:\tools\cli\main.js:1522:20

**Comment by filipenevola** [comment]
Hi, it seems like Meteor was not correctly installed in your machine.

Could you try the new Meteor installer on Windows?

https://forums.meteor.com/t/meteor-installer-for-windows-beta/55432

Please respond here if you still get the same error so we can re-open the issue.

**Comment by preyash29** [comment]
getting the same error

**Comment by preyash29** [comment]
Error: isopacket load failed?
    at loadIsopacketFromDisk (C:\tools\tool-env\isopackets.js:319:11)
    at C:\tools\tool-env\isopackets.js:112:9
    at loadIsopackage (C:\tools\tool-env\isopackets.js:121:4)
    at ProjectContext._buildResolver (C:\tools\project-context.js:902:34)
    at C:\tools\project-context.js:594:29
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\project-context.js:593:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._resolveConstraints (C:\tools\project-context.js:592:13)
    at C:\tools\project-context.js:365:35
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:355:18)
    at C:\tools\project-context.js:325:12
    at Function.run (C:\Users\Dharmesh\AppData\Local\.meteor\packages\meteor-tool\2.14.0\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:289:14)
    at ProjectContext.resolveConstraints (C:\tools\project-context.js:324:13)
    at C:\tools\runners\run-all.js:82:27
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at new Runner (C:\tools\runners\run-all.js:81:18)
    at Object.exports.run (C:\tools\runners\run-all.js:399:16)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:449:17)
    at C:\tools\cli\main.js:1534:15
