### ISSUE TITLE
METEOR@2.1 cordova build failed

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#11338]
```
Executing script found in plugin cordova-plugin-meteor-webapp for hook "after_plugin_install": plugins/cordova-plugin-meteor-webapp/scripts/iosAddBridgingHeader.js
%% Failed to install 'cordova-plugin-meteor-webapp': Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/monsterstep/dev/sandbox2021/cube/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/scripts/iosAddBridgingHeader.js:2:20)
    at runScriptViaModuleLoader (/Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at /Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
=> Errors executing Cordova commands:

   While adding plugin cordova-plugin-meteor-webapp@1.7.0 to Cordova project:
   Cordova error: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
   at Context.requireCordovaModule
   (/Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/Context.js:57:15)
   at module.exports (/Users/monsterstep/dev/sandbox2021/cube/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/scripts/iosAddBridgingHeader.js:2:20)
   at runScriptViaModuleLoader
   (/Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
   at runScript (/Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
   at /Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
   at /Users/monsterstep/.meteor/packages/meteor-tool/.2.1.0.1dqzg3f.ajeal++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to help diagnose the issue.)

/Users/monsterstep/.meteor/packages/coffeescript/.1.0.17.1wqea3d.5qut++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
ExitWithCode { code: 1 }
```

**Comment by crapthings** [comment]
cordova-plugin-meteor-webapp@1.7.0 

to

cordova-plugin-meteor-webapp@1.9.1
