### ISSUE TITLE
[2.1.1] SpacebarsCompiler is not defined

### ISSUE THREAD

**Issue by diavrank** [meteor/meteor#11387]
Hello,  I have just updated to **Meteor 2.1.1** (from 2.1) and when I start my app, throws this error:

```shell

/usr/local/bin/meteor --settings ./settings/settings-development.json
[[[[[ ~/Documents/versus-api-player ]]]]]

=> Started proxy.
=> [HMR] Dev server listening on port 3003.
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
W20210414-13:56:18.307(-5)? (STDERR) (node:18255) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
W20210414-13:56:18.905(-5)? (STDERR) /Users/diavrank/.meteor/packages/meteor-tool/.2.1.1.15mtdai.legg++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20210414-13:56:18.905(-5)? (STDERR) 						throw(ex);
W20210414-13:56:18.905(-5)? (STDERR) 						^
W20210414-13:56:18.906(-5)? (STDERR) 
W20210414-13:56:18.906(-5)? (STDERR) ReferenceError: SpacebarsCompiler is not defined
W20210414-13:56:18.906(-5)? (STDERR)     at packages/meteorhacks_ssr.js:195:18
W20210414-13:56:18.906(-5)? (STDERR)     at packages/meteorhacks_ssr.js:226:4
W20210414-13:56:18.906(-5)? (STDERR)     at packages/meteorhacks_ssr.js:235:3
W20210414-13:56:18.906(-5)? (STDERR)     at /Users/diavrank/Documents/versus-api-player/.meteor/local/build/programs/server/boot.js:401:38
W20210414-13:56:18.906(-5)? (STDERR)     at Array.forEach (<anonymous>)
W20210414-13:56:18.907(-5)? (STDERR)     at /Users/diavrank/Documents/versus-api-player/.meteor/local/build/programs/server/boot.js:226:21
W20210414-13:56:18.907(-5)? (STDERR)     at /Users/diavrank/Documents/versus-api-player/.meteor/local/build/programs/server/boot.js:464:7
W20210414-13:56:18.907(-5)? (STDERR)     at Function.run (/Users/diavrank/Documents/versus-api-player/.meteor/local/build/programs/server/profile.js:280:14)
W20210414-13:56:18.907(-5)? (STDERR)     at /Users/diavrank/Documents/versus-api-player/.meteor/local/build/programs/server/boot.js:463:13
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

These are updates of the release change:

```shell

(base) ➜  versus-api-player git:(dev) meteor update
versus-api-player: updated to Meteor 2.1.1.   
                                                                                   
Changes to your project's package version selections from updating package versions:
                                              
blaze-tools            upgraded from 1.0.10 to 1.1.0
caching-html-compiler  upgraded from 1.1.3 to 1.2.0
deps                   removed from your project
html-tools             upgraded from 1.0.11 to 1.1.0
htmljs                 upgraded from 1.0.11 to 1.1.0
http                   upgraded from 1.4.1 to 1.4.3
spacebars-compiler     upgraded from 1.1.3 to 1.2.0
static-html            upgraded from 1.2.2 to 1.3.0
templating-tools       upgraded from 1.1.2 to 1.2.0

                                              
Newer versions of the following indirect dependencies are available:
 * aldeed:collection2 3.1.0 (3.2.1 is available)
 * blaze 2.3.4 (2.4.0 is available)           
 * meteortesting:mocha-core 8.0.1 (8.1.2 is available)
 * raix:eventemitter 0.1.3 (1.0.0 is available)
 * spacebars 1.0.15 (1.1.0 is available)      
 * tmeasday:check-npm-versions 0.3.2 (1.0.1 is available)
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.

```

Maybe this is caused by `meteorhacks:ssr` package, which is a package that I use to send emails in **HTML** format. So, I wonder if exists another package (**not deprecated**) that I can to use? Or can I modify the version of this package in **versions file**?

**Comment by guncebektas** [comment]
Yes, the issue is caused by ```meteorhacks:ssr``` You can remove that package and use this code snippet for your emails. This will work in many cases or you can customize the package locally. Check [the forum](https://forums.meteor.com/t/spacebarscompiler-is-undefined/55685/3)

```
import {SpacebarsCompiler} from 'meteor/spacebars-compiler';
import {Blaze} from 'meteor/blaze';

class ssrService
{
  render(templateName, data)
  {
    const renderFunc = (data) ? Blaze.toHTMLWithData : Blaze.toHTML;
    const template = Blaze.Template[templateName];
    
    if(!template)
    {
      throw new Error(`Template ${templateName} not found`);
    }
    else
    {
      return renderFunc(template, data);
    }
  }
  
  compileTemplate(name, content)
  {
    const renderFunction = eval(`(function(view)
    {
      return ${SpacebarsCompiler.compile(content)}();
    })`);
    
    const template = new Blaze.Template(name, function()
    {
      return renderFunction(this);
    });
    
    Blaze.Template[name] = template;
    
    return template;
  }
}

export const SSR = new ssrService();
```

**Comment by zodern** [comment]
This is related to https://github.com/meteor/blaze/issues/327

**Comment by diavrank** [comment]
Perfect! It works this snippet.

I had to add these other packages:

- blaze
- spacebars

**Comment by filipenevola** [comment]
Fixed https://github.com/meteor/blaze/pull/328#issuecomment-821703330

**Comment by diavrank** [comment]
Thank you, now it works again with `meteorhacks:ssr` package. Have a nice weekend :) .

```shell

(base) ➜  versus-api-player git:(dev) ✗ meteor update
This project is already at Meteor 2.2, the latest release.
                                                                                   
Changes to your project's package version selections from updating package versions:
                                              
blaze-tools         upgraded from 1.1.0 to 1.1.1
html-tools          upgraded from 1.1.0 to 1.1.1
spacebars-compiler  upgraded from 1.2.0 to 1.2.1

```
