### ISSUE TITLE
npm i -g meteor fails with a 403 error

### ISSUE THREAD

**Issue by batchu** [meteor/meteor#11390]
Steps to reproduce
```npm i -g meteor```

Environment
Windows
C:\Users\user>node -v
v15.14.0
C:\Users\user>npm -v
7.10.0

Expected Behavior
Meteor should install successfully

Actual Behvior
403 error. Installation fails

Stacktrace

```
C:\Users\user>npm i -g meteor
npm ERR! code 1
npm ERR! path D:\downloads\node-v15.14.0-win-x64\node_modules\meteor
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node cli.js install
npm ERR! node:events:346
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR!
npm ERR! Error: Response status was 403
npm ERR!     at ClientRequest.<anonymous> (D:\downloads\node-v15.14.0-win-x64\node_modules\meteor\node_modules\node-downloader-helper\dist\index.js:1:7153)
npm ERR!     at Object.onceWrapper (node:events:476:26)
npm ERR!     at ClientRequest.emit (node:events:369:20)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:646:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:512:22)
npm ERR!     at TLSSocket.emit (node:events:369:20)
npm ERR!     at addChunk (node:internal/streams/readable:313:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:288:9)
npm ERR!     at TLSSocket.Readable.push (node:internal/streams/readable:227:10)
npm ERR! Emitted 'error' event on b instance at:
npm ERR!     at ClientRequest.<anonymous> (D:\downloads\node-v15.14.0-win-x64\node_modules\meteor\node_modules\node-downloader-helper\dist\index.js:1:7284)
npm ERR!     at Object.onceWrapper (node:events:476:26)
npm ERR!     [... lines matching original stack trace ...]
npm ERR!     at TLSSocket.Readable.push (node:internal/streams/readable:227:10) {
npm ERR!   status: 403,
npm ERR!   body: ''
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-04-17T15_04_40_415Z-debug.log

C:\Users\user>npm install -g meteor
npm ERR! code 1
npm ERR! path D:\downloads\node-v15.14.0-win-x64\node_modules\meteor
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node cli.js install
npm ERR! node:events:346
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR!
npm ERR! Error: Response status was 403
npm ERR!     at ClientRequest.<anonymous> (D:\downloads\node-v15.14.0-win-x64\node_modules\meteor\node_modules\node-downloader-helper\dist\index.js:1:7153)
npm ERR!     at Object.onceWrapper (node:events:476:26)
npm ERR!     at ClientRequest.emit (node:events:369:20)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:646:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:512:22)
npm ERR!     at TLSSocket.emit (node:events:369:20)
npm ERR!     at addChunk (node:internal/streams/readable:313:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:288:9)
npm ERR!     at TLSSocket.Readable.push (node:internal/streams/readable:227:10)
npm ERR! Emitted 'error' event on b instance at:
npm ERR!     at ClientRequest.<anonymous> (D:\downloads\node-v15.14.0-win-x64\node_modules\meteor\node_modules\node-downloader-helper\dist\index.js:1:7284)
npm ERR!     at Object.onceWrapper (node:events:476:26)
npm ERR!     [... lines matching original stack trace ...]
npm ERR!     at TLSSocket.Readable.push (node:internal/streams/readable:227:10) {
npm ERR!   status: 403,
npm ERR!   body: ''
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-04-17T15_10_24_930Z-debug.log

C:\Users\user>node -v
v15.14.0

C:\Users\user>npm -v
7.10.0
```

**Comment by leoncvlt** [comment]
Same issue here. Worth noting I installed it on a separate machine yesterday and it went fine.

**Comment by gottaloveit** [comment]
same here

C:\Users\gotta\Desktop\project\app>node -v
v14.16.0

C:\Users\gotta\Desktop\project\app>npm -v
7.10.0

**Comment by juliomax** [comment]
While the installer it is not fixed, you can use this way:

In windows:
set INSTALL_METEOR_VERSION=2.2
npm install -g meteor --force

In Linux:
export INSTALL_METEOR_VERSION=2.2
npm install -g meteor --force

The bug is in the installer config, that is pointing to version 2.2.0 that is not deployed correctly yet.

**Comment by StorytellerCZ** [comment]
@juliomax @batchu Can you check now, that version 2.2 is deployed that this is still an issue?
