### ISSUE TITLE
Unable to install Meteor on Windows 10

### ISSUE THREAD

**Issue by QCTW** [meteor/meteor#11415]
Hi,

I am following the steps to install Meteor on Windwos 10 with the following version of NodeJs
`$ node -v
v14.16.1
`
`$ npm -v
6.14.12`

I installed the NodeJs from node-v14.16.1-x64.msi . But I got the following error

```
npm install -g meteor --force
npm WARN using --force I sure hope you know what you are doing.
C:\Users\quincy.hsieh\AppData\Roaming\npm\meteor -> C:\Users\quincy.hsieh\AppData\Roaming\npm\node_modules\meteor\meteor.bat
C:\Users\quincy.hsieh\AppData\Roaming\npm\meteor-installer -> C:\Users\quincy.hsieh\AppData\Roaming\npm\node_modules\meteor\cli.js

> meteor@2.2.1 install C:\Users\quincy.hsieh\AppData\Roaming\npm\node_modules\meteor
> node cli.js install

Downloading |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0%events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Emitted 'error' event on b instance at:
    at ClientRequest.<anonymous> (C:\Users\quincy.hsieh\AppData\Roaming\npm\node_modules\meteor\node_modules\node-downloader-helper\dist\index.js:1:10025)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
+ meteor@2.2.1
added 46 packages from 25 contributors in 2.16s`
```

Could someone help me with this? I am block with the installation.

Thank you

**Comment by StorytellerCZ** [comment]
Hi @QCTW could you try it with Meteor 2.3 beta? Let's see if we can eliminate differing node versions as an issue.

**Comment by QCTW** [comment]
> Hi @QCTW could you try it with Meteor 2.3 beta? Let's see if we can eliminate differing node versions as an issue.

Thanks for the reply @StorytellerCZ But how can I install a beta version with npm install? Sorry I am new to npm on Windows...

Thank you.

**Comment by QCTW** [comment]
Same issue in 2.3.3

C:\Users\quincy.hsieh\AppData\Roaming\npm\meteor -> C:\Users\quincy.hsieh\AppData\Roaming\npm\node_modules\meteor\meteor.bat
C:\Users\quincy.hsieh\AppData\Roaming\npm\meteor-installer -> C:\Users\quincy.hsieh\AppData\Roaming\npm\node_modules\meteor\cli.js

> meteor@2.3.3 install C:\Users\quincy.hsieh\AppData\Roaming\npm\node_modules\meteor
> node cli.js install

Downloading |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0%events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:375:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)
Emitted 'error' event on b instance at:
    at ClientRequest.<anonymous> (C:\Users\quincy.hsieh\AppData\Roaming\npm\node_modules\meteor\node_modules\node-downloader-helper\dist\index.js:1:10025)
    at ClientRequest.emit (events.js:375:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
+ meteor@2.3.3
updated 1 package in 3.798s

**Comment by QCTW** [comment]
For someone who encountered the same issue on Windows, the best way is to disable rejecting unknown CA by

> export NODE_TLS_REJECT_UNAUTHORIZED=0

Now the command 'npm install -g meteor' works on Windows under the Git bash with NodeJS installed.

**Comment by StorytellerCZ** [comment]
Adding this fix to documentation.
