### ISSUE TITLE
[2.3-beta.1] Exception in queued task TypeError: data.size is not a function

### ISSUE THREAD

**Issue by diavrank** [meteor/meteor#11448]
When I updated to Meteor 2.3-beta.1, I got this error:

```shell
/usr/local/bin/meteor --settings ./settings/settings-development.json
[[[[[ ~/Documents/versus-api-player ]]]]]

=> Started proxy.
=> [HMR] Dev server listening on port 3003.
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
W20210527-13:07:04.146(-5)? (STDERR) Default value for player time for valid match was configured
W20210527-13:07:04.223(-5)? (STDERR) Default value for number of players for valid match was configured
I20210527-13:07:05.009(-5)? Monti APM: completed instrumenting the app
=> Started your app.

=> App running at: http://localhost:3000/
I20210527-13:07:10.017(-5)? Exception in queued task TypeError: data.size is not a function
I20210527-13:07:10.017(-5)?     at DocSzCache.getSize (packages/montiapm:agent/lib/docsize_cache.js:19:52)
I20210527-13:07:10.018(-5)?     at PollingObserveDriver.proto._pollMongo (packages/montiapm:agent/lib/hijack/wrap_observers.js:117:35)
I20210527-13:07:10.018(-5)?     at Object.task (packages/mongo/polling_observe_driver.js:93:12)
I20210527-13:07:10.018(-5)?     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
I20210527-13:07:10.018(-5)?     at packages/meteor.js:894:12
I20210527-13:07:14.911(-5)? Exception in queued task TypeError: data.size is not a function
I20210527-13:07:14.911(-5)?     at DocSzCache.getSize (packages/montiapm:agent/lib/docsize_cache.js:19:52)
I20210527-13:07:14.911(-5)?     at PollingObserveDriver.proto._pollMongo (packages/montiapm:agent/lib/hijack/wrap_observers.js:117:35)
I20210527-13:07:14.912(-5)?     at Object.task (packages/mongo/polling_observe_driver.js:93:12)
I20210527-13:07:14.912(-5)?     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
I20210527-13:07:14.912(-5)?     at packages/meteor.js:894:12
... (Continues showing the same error each 4 seconds )

```

**Notes:**

- Mac 11.3.1
- Node 14.17.0
- METEOR@2.3-beta.1

**Comment by zodern** [comment]
This error is fixed in `montiapm:agent@2.42.0`. Though I'm not sure what changed in Meteor to start causing this error.

**Comment by diavrank** [comment]
True, I had montiapm:agent@2.41.2, so, I updated it and the error has gone. Thanks.
