### ISSUE TITLE
Removing a file/node module causes server to stop running

### ISSUE THREAD

**Issue by ajaypillay** [meteor/meteor#11455]
Hi, when I remove any file or node module, it breaks the server for some reason. Here's the error message in my terminal. Here I removed the package `react-color` (this happens when I remove any arbitrary package):
```
=> Client modified -- refreshing (x8)/home/XXX/.meteor/packages/meteor-tool/.2.2.0.1dtcdj9.bux6++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/home/XXX/Desktop/project2/node_modules/tinycolor2/docs/tinycolor.html'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /home/XXX/.meteor/packages/meteor-tool/.2.2.0.1dtcdj9.bux6++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1642:23
...
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/XXX/Desktop/project/node_modules/tinycolor2/docs/tinycolor.html'
```
Meteor Version: 2.2
OS: Fedora 34, 64-bit

This is just (I think) a minor QOL thing, as I can restart the server and everything works fine. Although it would be nice to understand why this is happening, and a fix for this would be great :-)

Thanks!

**Comment by StorytellerCZ** [comment]
@zodern I think you have been recently working around these parts, any thoughts?

**Comment by zodern** [comment]
Even if this issue didn't exist, you should restart Meteor when adding or removing npm dependencies, due to how Meteor handles in-memory caches for them. One of the caches (I'm guessing the same one causing this error) would have been fixed by https://github.com/meteor/meteor/pull/8165

**Comment by ajaypillay** [comment]
> Even if this issue didn't exist, you should restart Meteor when adding or removing npm dependencies, due to how Meteor handles in-memory caches for them. One of the caches (I'm guessing the same one causing this error) would have been fixed by #8165

Interesting, will take note of this. Adding npm dependencies works and never causes a crash, and I can access the newly installed dependencies immediately after Meteor restarts. It's only removals that cause the crash.

**Comment by italojs** [comment]
[Abandoned]  
Please inform us if this occurs in Meteor 3.x.
