### ISSUE TITLE
Meteor Cordova: Non-success status code 404 for asset: /

### ISSUE THREAD

**Issue by jasongrishkoff** [meteor/meteor#11496]
Running Meteor 2.2 on a Mac.  When I update my code, the automatic refresh on Cordova fails.  Works fine on web.

This might be related to https://github.com/meteor/cordova-plugin-meteor-webapp/issues/26.

The router I'm using is `meteor/ostrio:flow-router-extra`.

```
Loading asset bundle from directory file:///data/user/0/localhost.mobile/files/meteor/Downloading
Download failure
com.meteor.webapp.WebAppException: Non-success status code 404 for asset: /
      at com.meteor.webapp.AssetBundleDownloader.verifyResponse(AssetBundleDownloader.java:159)
      at com.meteor.webapp.AssetBundleDownloader$1.onResponse(AssetBundleDownloader.java:90)
      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      at java.lang.Thread.run(Thread.java:923)
chromium: [INFO:CONSOLE(37)] "Error: Non-success status code 404 for asset: /", source: http://localhost:12760/__cordova/packages/webapp.js?hash=1b0eb4b502ab8149f4b77aa36a3ab7362d8b590f (37)
```

**Comment by StorytellerCZ** [comment]
Hi @jasongrishkoff could you check that the route to the asset is correct? It is complaining about asset `/` which suggests to me that you might have some strange route or something along those lines and that the web version is just more permissive towards those errors. If you could isolate that and provide a reproduction that would be great!

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
