### ISSUE TITLE
Errors while creating your project  While loading package webapp@1.11.0

### ISSUE THREAD

**Issue by nsinfoPRO** [meteor/meteor#11518]
Running latest meteor version 2.3, node v14.17.1 and npm 6.14.13 on windows 10 10.0.19041 Build 19041. When creating project I'm getting error "Errors while creating your project  While loading package webapp@1.11.0"

`Errors while creating your project

While loading package webapp@1.11.0:
error: Command failed: C:\Windows\system32\cmd.exe /c
C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd
rebuild --update-binary
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual
Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\2.3.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command...`

**Comment by StorytellerCZ** [comment]
@nsinfoPRO can you please try with the latest 2.3.1 beta?

**Comment by nsinfoPRO** [comment]
@StorytellerCZ which command line should I run to install latest 2.3.1 beta with npm? 4 hours ago new meteor version 2.2.2 was published, is that beta maybe?

**Comment by StorytellerCZ** [comment]
I think this might be just a duplicate of #11497
Updating to `2.3.1-rc.0` will tell us if it is or isn't.
On Windows it works the same as everywhere else. The npm package is just an installer. So try `meteor update --release 2.3.1-beta.3` in the app.

**Comment by StorytellerCZ** [comment]
Or just try to update to `webapp@1.11.1` which should fix the issue.

**Comment by nsinfoPRO** [comment]
In ...meteor\local\resolver-result-cache.json I changed webapp@1.11.0 to webapp@1.11.1 and its working now
