### ISSUE TITLE
Updating from 2.0 to 2.3.2 fails with 502 error

### ISSUE THREAD

**Issue by wreiske** [meteor/meteor#11546]
Today I went to run a meteor update and the update failed with a 502. 

Running on macOS Big Sur 11.4 (20F71). 
<img width="698" alt="Screen Shot 2021-07-17 at 2 28 51 PM" src="https://user-images.githubusercontent.com/6295044/126049752-33b4eb62-2564-4828-bb19-982af0c928d9.png">

```
% meteor --version
Meteor 2.0                       

% meteor update

/Users/user/.meteor/packages/meteor-tool/.2.0.0.k3veb1.ktpth++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Could not get https://warehouse.meteor.com/builds/a2Szie8zrmp8gCxP7/1626205210839/LoWN7STPni/meteor-tool-2.3.2-os.osx.x86_64+web.browser+web.browser.legacy+web.cordova.tgz; server returned [502]
    at Object.getUrlWithResuming (/tools/utils/http-helpers.js:502:13)
    at /tools/packaging/tropohouse.js:483:34
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:470:47
    at Function._.each._.forEach (/Users/user/.meteor/packages/meteor-tool/.2.0.0.k3veb1.ktpth++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:186:9)
    at /tools/packaging/tropohouse.js:469:11
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:600:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:597:20)
    at /tools/cli/main.js:463:28
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at /tools/cli/main.js:462:15
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at /tools/cli/main.js:459:33
    at Console.withProgressDisplayVisible (/tools/console/console.js:638:14)
    at springboard (/tools/cli/main.js:458:11)
    at /tools/cli/main.js:1548:7
```

**Comment by wreiske** [comment]
For what it's worth, I visited the URL several times and it returned a 502. I just tried it again and it downloaded the update bundle. 

I'll leave this open for now so the appropriate parties are notified that there was an intermittent issue with the warehouse they may want to investigate. 

Thanks!

**Comment by renanccastro** [comment]
Thanks @wreiske 
We fixed it in this issue: https://github.com/meteor/meteor/issues/11543#issue-946076145

**Comment by wreiske** [comment]
> Thanks @wreiske 
> We fixed it in this issue: https://github.com/meteor/meteor/issues/11543#issue-946076145

I don't think this is the same issue. A 502 doesn't have anything to do with a bad certificate, unless of course the bad certificate lived on a backend server behind warehouse and warehouse was validating certificates itself. It looks like this issue occured after the SSL certificate was fixed as well.

I was getting a valid certificate when trying to download the latest bundle.

Are you sure they are related?

**Comment by renanccastro** [comment]
You are right! They are not, sorry.
I assumed it was the same thing as we had a lot of reports because of the certificate issue.
Sorry for that.
---
We do serve every file from the warehouse with a CDN. This error might be a temporary issue on their side, as there is no status page opened on it. I will dig some more and let you know.
Please let us know if this happens again anytime at support@meteor.com, which we will surely follow this through.
