### ISSUE TITLE
[2.3.2] TypeError: this.unblock is not a function in Test mode

### ISSUE THREAD

**Issue by diavrank** [meteor/meteor#11561]
When I run my meteor app in **test mode**, some tests fail because it doesn't recognize **unblock** function from meteor method, however, it works well for development/production environment. The error is the following:

```shell
I20210728-16:43:50.216(-5)?   1) verificationCode.generate
I20210728-16:43:50.217(-5)?        Send SMS successfully for signup usage:
I20210728-16:43:50.217(-5)?      TypeError: this.unblock is not a function
I20210728-16:43:50.217(-5)?       at imports/api/VerificationCode/VerificationCodesCtrl.ts:71:8
I20210728-16:43:50.217(-5)?       at /Users/diavrank/.meteor/packages/promise/.0.12.0.1wugqny.30ko++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20210728-16:43:50.217(-5)?    => awaited here:
I20210728-16:43:50.217(-5)?       at Function.Promise.await (/Users/diavrank/.meteor/packages/promise/.0.12.0.1wugqny.30ko++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20210728-16:43:50.217(-5)?       at tests/server/VerificationCodes/VerificationCodeCtrl.test.ts:47:24
I20210728-16:43:50.217(-5)?       at /Users/diavrank/.meteor/packages/promise/.0.12.0.1wugqny.30ko++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

I am using Validated Methods, so in the unit test I have this:

```js
it('Send SMS successfully for signup usage', async function() {
    const responseMessage = await generateVerificationCodeMethod._execute({}, {
	    phoneNumber: faker.phone.phoneNumber('+52##########')
    });
    chai.assert.equal(responseMessage.message, 'SMS sent successfully', 'SMS sent successfully');
});
```

And this is the endpoint definition:

```js
export const generateVerificationCodeMethod = new ValidatedMethod({
	name: 'verificationCode.generate',
	beforeHooks: [Binnacle.checkIn],
	afterHooks: [Binnacle.checkOut],
	validate(verificationMean: VerificationMeanType) {
		//...<more code>
	},
	async run(verificationMean: VerificationMeanType) {
		this.unblock();
		let responseMessage = new ResponseMessage();
		//...<more code>
		return responseMessage;
	}
});
```

I'm not sure if this error is related to Meteor or to `mdg:validated-method` package.

**Notes:**

- Node 14.17.0
- Meteor 2.3.2
- Mocha 2.0.2
- Validated Method 1.2.0
- Command test: `TEST_WATCH=1 meteor test --settings ./settings/settings-development.json --full-app --driver-package meteortesting:mocha`

**Comment by rj-david** [comment]
Seems like you need to bind the method instance object to itself (first params of _execute()) to get access to the properties.

Here is the _execute() function
https://github.com/meteor/validated-method/blob/daa4374f192b2f4424617511e6b120a2a3f369be/validated-method.js#L88

**Comment by diavrank** [comment]
Thank you @rj-david , I tried with this but I didn't have luck:

>binding method instance object to the run() function (first params of _execute())

```js
it.only('Send SMS successfully for signup usage', async function() {
		console.log('method instance: ',generateVerificationCodeMethod.run);
		const responseMessage = await generateVerificationCodeMethod._execute(generateVerificationCodeMethod, {
			phoneNumber: faker.phone.phoneNumber('+52##########')
		});
		chai.assert.equal(responseMessage.message, 'SMS sent successfully', 'SMS sent successfully');
	});
```

I got the same error. I guess is due to method instance doesn't have the **unblock** function in its root properties:

```shell

I20210729-12:39:43.400(-5)? method instance:  ValidatedMethod {
I20210729-12:39:43.401(-5)?   name: 'verificationCode.generate',
I20210729-12:39:43.401(-5)?   beforeHooks: [ [Function: checkIn] ],
I20210729-12:39:43.401(-5)?   afterHooks: [ [Function: checkOut] ],
I20210729-12:39:43.402(-5)?   validate: [Function: validate],
I20210729-12:39:43.402(-5)?   run: [Function: run],
I20210729-12:39:43.402(-5)?   mixins: [],
I20210729-12:39:43.402(-5)?   connection: {
I20210729-12:39:43.402(-5)?     isProduction: false,
I20210729-12:39:43.402(-5)?     isDevelopment: true,
I20210729-12:39:43.402(-5)?     isClient: false,
I20210729-12:39:43.402(-5)?     isServer: true,
I20210729-12:39:43.402(-5)?     isCordova: false,
I20210729-12:39:43.403(-5)?     isModern: true,
I20210729-12:39:43.403(-5)?     settings: { private: [Object], public: [Object] },
I20210729-12:39:43.403(-5)?     gitCommitHash: 'db504fd3bb9ed34aeb0903f7ac2e499ff5da1860',
I20210729-12:39:43.403(-5)?     release: 'METEOR@2.3.2',
I20210729-12:39:43.403(-5)?     _get: [Function (anonymous)],
I20210729-12:39:43.403(-5)?     _ensure: [Function (anonymous)],
I20210729-12:39:43.403(-5)?     _delete: [Function (anonymous)],
I20210729-12:39:43.403(-5)?     wrapAsync: [Function (anonymous)],
I20210729-12:39:43.403(-5)?     _inherits: [Function (anonymous)],
I20210729-12:39:43.403(-5)?     _wrapAsync: [Function (anonymous)],
I20210729-12:39:43.403(-5)?     _setImmediate: [Function: setImmediate] { implementation: 'setImmediate' },
I20210729-12:39:43.404(-5)?     setTimeout: [Function (anonymous)],
I20210729-12:39:43.404(-5)?     setInterval: [Function (anonymous)],
I20210729-12:39:43.404(-5)?     clearInterval: [Function (anonymous)],
I20210729-12:39:43.404(-5)?     clearTimeout: [Function (anonymous)],
I20210729-12:39:43.404(-5)?     defer: [Function (anonymous)],
I20210729-12:39:43.404(-5)?     makeErrorType: [Function (anonymous)],
I20210729-12:39:43.404(-5)?     Error: [Function: errorClass] {
I20210729-12:39:43.404(-5)?       stackTraceLimit: 10,
I20210729-12:39:43.404(-5)?       prepareStackTrace: [Function: prepareStackTrace],
I20210729-12:39:43.405(-5)?       __super__: {}
I20210729-12:39:43.405(-5)?     },
I20210729-12:39:43.405(-5)?     _noYieldsAllowed: [Function (anonymous)],
I20210729-12:39:43.405(-5)?     _DoubleEndedQueue: [Function: Deque],
I20210729-12:39:43.405(-5)?     _SynchronousQueue: [Function (anonymous)],
I20210729-12:39:43.405(-5)?     _sleepForMs: [Function (anonymous)],
I20210729-12:39:43.405(-5)?     startup: [Function: startup],
I20210729-12:39:43.405(-5)?     _debug: [Function (anonymous)],
I20210729-12:39:43.405(-5)?     _suppress_log: [Function (anonymous)],
I20210729-12:39:43.405(-5)?     _suppressed_log_expected: [Function (anonymous)],
I20210729-12:39:43.405(-5)?     _escapeRegExp: [Function (anonymous)],
I20210729-12:39:43.405(-5)?     isTest: false,
I20210729-12:39:43.406(-5)?     isAppTest: true,
I20210729-12:39:43.406(-5)?     isPackageTest: false,
I20210729-12:39:43.406(-5)?     _nodeCodeMustBeInFiber: [Function (anonymous)],
I20210729-12:39:43.406(-5)?     EnvironmentVariable: [Function (anonymous)],
I20210729-12:39:43.406(-5)?     bindEnvironment: [Function (anonymous)],
I20210729-12:39:43.406(-5)?     absoluteUrl: [Function (anonymous)] { defaultOptions: [Object] },
I20210729-12:39:43.406(-5)?     _relativeToSiteRootUrl: [Function (anonymous)],
I20210729-12:39:43.406(-5)?     server: Server {
I20210729-12:39:43.406(-5)?       options: [Object],
I20210729-12:39:43.406(-5)?       onConnectionHook: [Hook],
I20210729-12:39:43.406(-5)?       onMessageHook: [Hook],
I20210729-12:39:43.406(-5)?       publish_handlers: [Object],
I20210729-12:39:43.407(-5)?       universal_publish_handlers: [Array],
I20210729-12:39:43.407(-5)?       method_handlers: [Object],
I20210729-12:39:43.407(-5)?       sessions: Map(0) {},
I20210729-12:39:43.407(-5)?       stream_server: [StreamServer]
I20210729-12:39:43.407(-5)?     },
I20210729-12:39:43.407(-5)?     refresh: [Function (anonymous)],
I20210729-12:39:43.407(-5)?     publish: [Function (anonymous)],
I20210729-12:39:43.407(-5)?     methods: [Function: bound methods],
I20210729-12:39:43.407(-5)?     call: [Function: bound call],
I20210729-12:39:43.407(-5)?     apply: [Function: bound apply],
I20210729-12:39:43.407(-5)?     onConnection: [Function: bound onConnection],
I20210729-12:39:43.407(-5)?     onMessage: [Function: bound onMessage],
I20210729-12:39:43.407(-5)?     Collection: [Function (anonymous)] {
I20210729-12:39:43.408(-5)?       _publishCursor: [Function: _publishCursor],
I20210729-12:39:43.408(-5)?       _rewriteSelector: [Function: _rewriteSelector],
I20210729-12:39:43.408(-5)?       Cursor: [class Cursor],
I20210729-12:39:43.408(-5)?       ObjectID: [class ObjectID],
I20210729-12:39:43.408(-5)?       apply: [Function: apply]
I20210729-12:39:43.408(-5)?     },
I20210729-12:39:43.408(-5)?     userId: [Function (anonymous)],
I20210729-12:39:43.408(-5)?     user: [Function (anonymous)],
I20210729-12:39:43.408(-5)?     users: Collection {
I20210729-12:39:43.408(-5)?       _makeNewID: [Function (anonymous)],
I20210729-12:39:43.408(-5)?       _transform: [Function (anonymous)],
I20210729-12:39:43.408(-5)?       _connection: [Server],
I20210729-12:39:43.409(-5)?       _collection: [Object],
I20210729-12:39:43.409(-5)?       _name: 'users',
I20210729-12:39:43.409(-5)?       _driver: [Object],
I20210729-12:39:43.409(-5)?       _restricted: true,
I20210729-12:39:43.409(-5)?       _insecure: undefined,
I20210729-12:39:43.409(-5)?       _validators: [Object],
I20210729-12:39:43.409(-5)?       _prefix: '/users/',
I20210729-12:39:43.409(-5)?       before: [Object],
I20210729-12:39:43.409(-5)?       _hookAspects: [Object],
I20210729-12:39:43.409(-5)?       after: [Object],
I20210729-12:39:43.409(-5)?       hookOptions: [Object],
I20210729-12:39:43.409(-5)?       direct: [Object],
I20210729-12:39:43.409(-5)?       upsert: [Function (anonymous)],
I20210729-12:39:43.410(-5)?       _c2: [Object]
I20210729-12:39:43.410(-5)?     },
I20210729-12:39:43.410(-5)?     roles: Collection {
I20210729-12:39:43.410(-5)?       _makeNewID: [Function (anonymous)],
I20210729-12:39:43.410(-5)?       _transform: null,
I20210729-12:39:43.410(-5)?       _connection: [Server],
I20210729-12:39:43.410(-5)?       _collection: [Object],
I20210729-12:39:43.410(-5)?       _name: 'roles',
I20210729-12:39:43.410(-5)?       _driver: [Object],
I20210729-12:39:43.410(-5)?       _restricted: false,
I20210729-12:39:43.410(-5)?       _insecure: undefined,
I20210729-12:39:43.410(-5)?       _validators: [Object],
I20210729-12:39:43.410(-5)?       _prefix: '/roles/'
I20210729-12:39:43.411(-5)?     },
I20210729-12:39:43.411(-5)?     roleAssignment: Collection {
I20210729-12:39:43.411(-5)?       _makeNewID: [Function (anonymous)],
I20210729-12:39:43.411(-5)?       _transform: null,
I20210729-12:39:43.411(-5)?       _connection: [Server],
I20210729-12:39:43.411(-5)?       _collection: [Object],
I20210729-12:39:43.411(-5)?       _name: 'role-assignment',
I20210729-12:39:43.411(-5)?       _driver: [Object],
I20210729-12:39:43.411(-5)?       _restricted: false,
I20210729-12:39:43.411(-5)?       _insecure: undefined,
I20210729-12:39:43.411(-5)?       _validators: [Object],
I20210729-12:39:43.411(-5)?       _prefix: '/role-assignment/'
I20210729-12:39:43.411(-5)?     },
I20210729-12:39:43.412(-5)?     _NewCollectionContructor: [Function (anonymous)] {
I20210729-12:39:43.412(-5)?       _publishCursor: [Function: _publishCursor],
I20210729-12:39:43.412(-5)?       _rewriteSelector: [Function: _rewriteSelector],
I20210729-12:39:43.412(-5)?       Cursor: [class Cursor],
I20210729-12:39:43.412(-5)?       ObjectID: [class ObjectID],
I20210729-12:39:43.412(-5)?       apply: [Function: apply]
I20210729-12:39:43.412(-5)?     },
I20210729-12:39:43.412(-5)?     sync: [Function (anonymous)]
I20210729-12:39:43.412(-5)?   },
I20210729-12:39:43.412(-5)?   applyOptions: { returnStubValue: true, throwStubExceptions: true }
I20210729-12:39:43.412(-5)? }
```

**Comment by diavrank** [comment]
I think, as you mention, this error is related to `validated-method` package, since I found this issue in its [repository](https://github.com/meteor/validated-method/issues/11). By the moment,  I resolved this issue by adding **Meteor.isAppTest** condition to run that code line.
