### ISSUE TITLE
Not able to install the meteor on linux machine

### ISSUE THREAD

**Issue by ravisd77** [meteor/meteor#11691]
### I am getting the LOCALAPPDATA env var is not set. error while installing the meteor on linux machine
```/usr/local/lib/node_modules/meteor/config.js:8
  throw new Error('LOCALAPPDATA env var is not set.');
  ^

Error: LOCALAPPDATA env var is not set.
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor/config.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor/install.js:9:59)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor@2.2.0 install: `node cli.js install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-11T08_42_12_746Z-debug.log

[Container] 2021/10/11 08:42:12 Command did not exit successfully npm install -g meteor@$METEOR_VERSION exit status 1
[Container] 2021/10/11 08:42:12 Phase complete: INSTALL State: FAILED
[Container] 2021/10/11 08:42:12 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm install -g meteor@$METEOR_VERSION. Reason: exit status 1
```

**Comment by StorytellerCZ** [comment]
@ravisd77 can you please give me more details on your OS?

**Comment by ravisd77** [comment]
Hi,

I am using aws code build the machine is *amazonlinux2-x86_64-standard:2.0*
aws/codebuild/amazonlinux2-x86_64-standard:2.0

**Comment by ravisd77** [comment]
Hi,
we are using meteor since 3 years. from long time we were ok with the
curl,But the curl installation is throwing certificate expiry error. So we
tried to install the meteor via npm -g this is giving the localappdata
error. I am able to install meteor on my local machine and also on the ec2
instance.But the error is throwing only when i tried to run the build
pipeline
