### ISSUE TITLE
ENOENT: no such file or directory, mkdir 'undefined/.files/'

### ISSUE THREAD

**Issue by Bullden** [meteor/meteor#11690]
when i started meteor i get this error:
 

[[[[[ ~\D\Folder\project ]]]]]

=> Started proxy.
=> Started MongoDB.

W20211011-17:04:42.106(3)? (STDERR) C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\2.4.0_1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20211011-17:04:42.116(3)? (STDERR)                                             ^
W20211011-17:04:42.121(3)? (STDERR) Error: ENOENT: no such file or directory, mkdir 'undefined/.files/'
W20211011-17:04:42.123(3)? (STDERR)     at Object.mkdirSync (fs.js:1009:3)
W20211011-17:04:42.125(3)? (STDERR)     at module (server/config.ts:10:8)
W20211011-17:04:42.127(3)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20211011-17:04:42.129(3)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20211011-17:04:42.131(3)? (STDERR)     at require (packages\modules-runtime.js:258:21)
W20211011-17:04:42.132(3)? (STDERR)     at D:\Folder\project\ .meteor\local\build\programs\server\app\app.js:9758:1
W20211011-17:04:42.134(3)? (STDERR)     at D:\Folder\project\ .meteor\local\build\programs\server\boot.js:401:38
W20211011-17:04:42.137(3)? (STDERR)     at Array.forEach (<anonymous>)
W20211011-17:04:42.140(3)? (STDERR)     at D:\Folder\project\ .meteor\local\build\programs\server\boot.js:226:21
W20211011-17:04:42.142(3)? (STDERR)     at D:\Folder\project\ .meteor\local\build\programs\server\boot.js:464:7
W20211011-17:04:42.144(3)? (STDERR)     at Function.run (D:\Folder\project\ .meteor\local\build\programs\server\profile.js:280:14)
W20211011-17:04:42.147(3)? (STDERR)     at D:\Folder\project\ .meteor\local\build\programs\server\boot.js:463:13 {                W20211011-17:04:42.147(3)? (STDERR) 
W20211011-17:04:42.149(3)? (STDERR)   errno: -4058,
W20211011-17:04:42.152(3)? (STDERR)   syscall: 'mkdir',
W20211011-17:04:42.156(3)? (STDERR)   code: 'ENOENT',
W20211011-17:04:42.158(3)? (STDERR)   path: 'undefined/.files/'
W20211011-17:04:42.163(3)? (STDERR) }

**Comment by Bullden** [comment]
@StorytellerCZ  thank you a lot
