### ISSUE TITLE
meteor 2.4 install: chown: missing operand after '/home/.meteor'

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#11694]
I'm trying to install meteor 2.4 in a Dockerfile, but I'm getting the following error:

```sh
#6 68.18 > meteor@2.4.1 install /usr/local/lib/node_modules/meteor
#6 68.18 > node cli.js install
#6 68.18 
#6 104.7 => Meteor Downloaded in 36.369s
#6 104.7 => Extracting the tarball, this may take some time
#6 119.9 => Meteor extracted in 15.181s
#6 119.9 chown: missing operand after '/home/.meteor'
#6 119.9 Try 'chown --help' for more information.
#6 119.9 /usr/local/lib/node_modules/meteor/install.js:29
#6 119.9   throw err;
#6 119.9   ^
#6 119.9 
#6 119.9 Error: Command failed: chown -R  "/home/.meteor"
#6 119.9 chown: missing operand after '/home/.meteor'
#6 119.9 Try 'chown --help' for more information.
#6 119.9 
#6 119.9     at checkExecSyncError (child_process.js:640:11)
#6 119.9     at Object.execSync (child_process.js:676:15)
#6 119.9     at setupExecPath (/usr/local/lib/node_modules/meteor/install.js:234:17)
#6 119.9     at async setup (/usr/local/lib/node_modules/meteor/install.js:208:3)
#6 119.9     at async b.<anonymous> (/usr/local/lib/node_modules/meteor/install.js:138:5) {
```

The Dockerfile is as follows: 

```js
ARG METEOR_NPM_VERSION=2.4.1
ARG NODE_VERSION=14.17.3

FROM cypress/base:$NODE_VERSION

RUN true \
  # Install dependencies (apt).
  && apt-get update \
  && apt-get install --no-install-recommends -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    netcat \
    python-pip \
    python-setuptools \
  # Install dependencies (npm).
  && npm install --no-audit --global --unsafe-perm \
    meteor@$METEOR_NPM_VERSION 
```

Any idea what might be going on here?

**Comment by StrictlySkyler** [comment]
Two reasons I can think of why this should work as root:
1. Using the `curl https://install.meteor.com/ | sh` script works as root without issue, so feature parity for the `npm` method should not cause a failure here
2. Forcing this change breaks existing build pipelines with a very opinionated way regarding how docker images are built and how Meteor should be used

Isn't Meteor meant to be "batteries included but removable"?  If so, would it make more sense for this to log a warning rather than to fail the build?

**Comment by renanccastro** [comment]
Hello, everyone.

Root install support was added to latest npm installer.

Let me know if you find any trouble with it
