### ISSUE TITLE
NPM Install fails behind corporate proxy 

### ISSUE THREAD

**Issue by njneer** [meteor/meteor#11718]
Version: 2.4 
OS: Windows 10 64-bit 
Expected behavior: Npm install should respect proxy environment variables 
Actual behavior: While NPM packages successfully install, the installer runs a node script to download meteor distribution: node cli.js install; this node script does not use the proxy environment variables set for npm, so meteor installer never installs, hangs at 0% 
How to reproduce: Sit behind proxy, set proxy variables and run npm install -g meteor 

Thanks

**Comment by NicoP-S** [comment]
having the same problem on an debian server. 
system & npm proxy is set.

The `cli.js` requires the `install.js`
And thisone seems to use the node-downloader-helper
https://github.com/meteor/meteor/blob/devel/npm-packages/meteor-installer/install.js#L105 

I did't find anything proxy releated to the downloaderHelper

**Comment by renanccastro** [comment]
Hello!

> this node script does not use the proxy environment variables set for npm

Can you describe more which env vars are you referring to? How are you using a proxy with npm?

**Comment by NicoP-S** [comment]
Hi @renanccastro 
i can share my proxy issue which seems to be the same problem .

` env |grep  proxy`
```
https_proxy=http://MYPROXYSERVER:3128
http_proxy=http://MYPROXYSERVER:3128
```

`npm config list`
```
...
http-proxy = "http://MYPROXYSERVER:3128/"
https-proxy = "http://MYPROXYSERVER:3128/"
proxy = "http://MYPROXYSERVER:3128/"
...
```

Error which ignores proxy and tries a direct connection to `3.225.194.45`
``` npm install -g meteor
/usr/bin/meteor-installer -> /usr/lib/node_modules/meteor/cli.js

> meteor@2.5.4 install /usr/lib/node_modules/meteor
> node cli.js install

You are running the install script as root, without SUDO. This is not recommended and should be avoided. Continuing.
Downloading |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0%/usr/lib/node_modules/meteor/install.js:43
  throw err;
  ^

Error: connect ECONNREFUSED 3.225.194.45:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
Emitted 'error' event on b instance at:
    at /usr/lib/node_modules/meteor/node_modules/node-downloader-helper/dist/index.js:1:10036
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '3.225.194.45',
  port: 443
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor@2.5.4 install: `node cli.js install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor@2.5.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by yanickrochon** [comment]
I'm not sure if this is relevant, here, but I found that when I started using Meteor, a few years ago, that there's a difference between `npm install` and `meteor npm install`. The latter should be used.

In short, instead of `npm config list`, run `meteor npm config list`.

**Comment by yanickrochon** [comment]
My bad. Then the problem isn't `npm`, but the `cli.js` script, which uses [node-downloader-helper](https://www.npmjs.com/package/node-downloader-helper) module. The `install.js` script ignores proxy settings.

**Comment by italojs** [comment]
The reported behavior (downloading the distribution bypassing the proxy) is **not reproducible** in the meteor 3.x because it has been **fixed**: since commit [6c72eea406](https://github.com/meteor/meteor/commit/6c72eea406) (2022-08-17), `install.js` has built an `https-proxy-agent` from `https_proxy`/`HTTPS_PROXY` and passes it to `DownloaderHelper`. 

today we already handle the proxy

`npm-packages/meteor-installer/install.js` (v3.4.1):
```js
function generateProxyAgent() {
  const proxyUrl = process.env.https_proxy || process.env.HTTPS_PROXY;
  if (!proxyUrl) return undefined;
  const HttpsProxyAgent = require('https-proxy-agent');
  return new HttpsProxyAgent(proxyUrl);
}

function download() {
  ...
  const dl = new DownloaderHelper(url, tempPath, {
    retry: { maxRetries: 5, delay: 5000 },
    override: true,
    fileName: tarGzName,
    httpsRequestOptions: { agent: generateProxyAgent() },   // <- proxy aplicado ao download
  });
  ...
}
```
