### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rioadrian** [meteor/meteor#11752]
Hi, I found Error when trying to run aggregate on large data in my meteor project using npm-mongo 3.9.1

`RangeError: Maximum call stack size exceeded at JSON.stringify (<anonymous>) at ObjectID.toHexString
(/Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/objectid.js:103:14)
at ObjectID.toString (/Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/objectid.js:198:15)
    at ObjectID.equals (/Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/bson/lib/bson/objectid.js:230:17)
    at ServerDescription.equals (/Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/sdam/server_description.js:152:47)
    at NativeTopology.serverUpdateHandler (/Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/sdam/topology.js:539:62)
    at Server.emit (events.js:400:28)
    at Server.emit (domain.js:475:12)
    at Monitor.<anonymous> (/Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/sdam/server.js:153:12)
    at Monitor.emit (events.js:412:35)
    at Monitor.emit (domain.js:475:12)
    at /Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/sdam/monitor.js:235:15
    at MessageStream.messageHandler (/Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/connection.js:281:5)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (/Users/rio/.meteor/packages/npm-mongo/.3.9.1.zn8p9o.3o4fj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
Exited with code: 1
Your application is crashing. Waiting for file change.`

It running smoothly before update meteor
I consider this is because of new version npm-mongo, please help me, thanks in advance.

best regards
Rio

**Comment by filipenevola** [comment]
Hi @rioadrian npm-mongo is just a wrapper for Node.js MongoDB Driver.

The problem is probably not related to Meteor.

How large is your aggregation result?

And if you are doing an aggregation you are already using the rawCollection right? So Meteor is not involved in this process.

**Comment by rioadrian** [comment]
Hi @filipenevola thanks for respond. I already found the problem, it is because there is a method that return aggregate directly. It was running in meteor 1.2 that we used before, and start showing error after We upgrade meteor to 2
The error was solved by adding .toArray() in aggregate. Once again thanks for you quick respond I hope it can help others with simillar issue. 

Thanks & Regards
Rio

**Comment by filipenevola** [comment]
Great, thank you for the feedback @rioadrian
