### ISSUE TITLE
`(node:67890) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency` on meteor run

### ISSUE THREAD

**Issue by welkinwong** [meteor/meteor#11761]
I receive the following error message on the console following (node:67890) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency

Full trace

```
=> Started proxy.                             
=> Started HMR server.                        
=> Started MongoDB.                           
W20211114-16:19:01.106(8)? (STDERR) (node:67890) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
W20211114-16:19:01.118(8)? (STDERR)     at emitCircularRequireWarning (internal/modules/cjs/loader.js:675:11)
W20211114-16:19:01.118(8)? (STDERR)     at Object.get (internal/modules/cjs/loader.js:689:5)
W20211114-16:19:01.118(8)? (STDERR)     at Object.<anonymous> (/Users/welkin/code/superdocs-next/node_modules/mongodb/lib/operations/operation.js:4:38)
W20211114-16:19:01.118(8)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1085:14)
W20211114-16:19:01.118(8)? (STDERR)     at Module.Mp._compile (/Users/welkin/code/superdocs-next/.meteor/local/build/programs/server/runtime.js:99:23)
W20211114-16:19:01.118(8)? (STDERR)     at Object.Module._extensions..js (/Users/welkin/code/superdocs-next/.meteor/local/build/programs/server/runtime.js:131:23)
W20211114-16:19:01.118(8)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:950:32)
W20211114-16:19:01.119(8)? (STDERR)     at Module.Mp.load (/Users/welkin/code/superdocs-next/.meteor/local/build/programs/server/runtime.js:46:33)
W20211114-16:19:01.119(8)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
W20211114-16:19:01.119(8)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:974:19)
W20211114-16:19:01.119(8)? (STDERR)     at require (internal/modules/cjs/helpers.js:93:18)
W20211114-16:19:01.119(8)? (STDERR)     at Object.<anonymous> (/Users/welkin/code/superdocs-next/node_modules/mongodb/lib/operations/execute_operation.js:4:16)
W20211114-16:19:01.119(8)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1085:14)
W20211114-16:19:01.119(8)? (STDERR)     at Module.Mp._compile (/Users/welkin/code/superdocs-next/.meteor/local/build/programs/server/runtime.js:99:23)
W20211114-16:19:01.119(8)? (STDERR)     at Object.Module._extensions..js (/Users/welkin/code/superdocs-next/.meteor/local/build/programs/server/runtime.js:131:23)
W20211114-16:19:01.120(8)? (STDERR)     at Module.load (internal/modules/cjs/loader.js:950:32)
W20211114-16:19:01.120(8)? (STDERR)     at Module.Mp.load (/Users/welkin/code/superdocs-next/.meteor/local/build/programs/server/runtime.js:46:33)
W20211114-16:19:01.120(8)? (STDERR)     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
W20211114-16:19:01.120(8)? (STDERR)     at Module.require (internal/modules/cjs/loader.js:974:19)
W20211114-16:19:01.120(8)? (STDERR)     at require (internal/modules/cjs/helpers.js:93:18)
W20211114-16:19:01.120(8)? (STDERR)     at Object.<anonymous> (/Users/welkin/code/superdocs-next/node_modules/mongodb/lib/core/cursor.js:10:26)
W20211114-16:19:01.120(8)? (STDERR)     at Module._compile (internal/modules/cjs/loader.js:1085:14)
=> Started your app.

=> App running at: http://localhost:3000/
```

METEOR@2.5
```
# Meteor packages used by this project, one per line.

# Check this file (and the other files in this directory) into your repository.

#

# 'meteor add' and 'meteor remove' will edit this file for you,

# but you can also edit it by hand.

meteor-base@1.5.1 # Packages every Meteor app needs to have
mobile-experience@1.1.0 # Packages for a great mobile UX
mongo@1.13.0 # The database Meteor supports right now
reactive-var@1.0.11 # Reactive variable for tracker

standard-minifier-css@1.7.4 # CSS minifier run for production mode
standard-minifier-js@2.7.1 # JS minifier run for production mode
es5-shim@4.8.0 # ECMAScript 5 compatibility for older browsers
ecmascript@0.16.0 # Enable ECMAScript2015+ syntax in app code
typescript@4.4.0 # Enable TypeScript syntax in .ts and .tsx modules
shell-server@0.5.0 # Server-side component of the `meteor shell` command

static-html@1.3.2 # Define static page content in .html files
react-meteor-data # React higher-order component for reactively tracking Meteor data
aldeed:collection2
aldeed:schema-index
welkinwong:accounts-phone
reywood:publish-composite
mdg:validated-method
natestrauser:publish-performant-counts
ostrio:files
hot-module-replacement@0.4.0
communitypackages:fast-render
```

**Comment by welkinwong** [comment]
my npm package is old...
