### ISSUE TITLE
[2.2] I cannot build on DigitalOcean App Platform due to SQLITE_IOERR error

### ISSUE THREAD

**Issue by abdagli** [meteor/meteor#11778]
I am trying to deploy using Dockerfile on DigitalOcean App Platform. But I am getting `SQLITE_IOERR` error during build. Even though I set it to `METEOR_SQLITE_JOURNAL_MODE: TRUNCATE`, nothing changes (METEOR@2.2).

As far as I understand from the documentation, the `METEOR_SQLITE_JOURNAL_MODE` env variable only works in the development environment. Unfortunately I can't deploy!

Some related links;
- https://www.digitalocean.com/community/questions/can-i-use-litestream-sqlite-replication-with-app-platform
- https://github.com/rjyo/next-boost/issues/46#issuecomment-958738656

```Dockerfile
FROM meteor/meteor-base:latest

WORKDIR /home/mt/app
COPY --chown=mt . ./

RUN meteor npm install --production \
    && meteor build --headless --directory ../build

CMD ["node", "../build/main.js"]
```

```OUTPUT
[2021-11-21 19:09:44] Error: SQLITE_IOERR: disk I/O error
[2021-11-21 19:09:45] Retrying after error Error: SQLITE_IOERR: disk I/O error
[2021-11-21 19:09:45] => awaited here:
[2021-11-21 19:09:45] at Promise.await
[2021-11-21 19:09:45] (/home/mt/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser .legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
[2021-11-21 19:09:45] at Db._execute (/tools/packaging/catalog/catalog-remote.js:361:8)
[2021-11-21 19:09:45] at /tools/packaging/catalog/catalog-remote.js:150:10
[2021-11-21 19:09:45] at Db._retry (/tools/packaging/catalog/catalog-remote.js:162:16)
[2021-11-21 19:09:45] at new Db (/tools/packaging/catalog/catalog-remote.js:149:8)
[2021-11-21 19:09:45] at RemoteCatalog.initialize
[2021-11-21 19:09:45] (/tools/packaging/catalog/catalog-remote.js:699:15)
[2021-11-21 19:09:45] at /tools/cli/main.js:875:20 {
[2021-11-21 19:09:45] errno: 10,
[2021-11-21 19:09:45] code: 'SQLITE_IOERR'
[2021-11-21 19:09:45] }
[2021-11-21 19:09:45] Retrying after error Error: SQLITE_IOERR: disk I/O error
[2021-11-21 19:09:45] => awaited here:
[2021-11-21 19:09:45] at Promise.await
[2021-11-21 19:09:45] (/home/mt/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser .legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
[2021-11-21 19:09:45] at Db._execute (/tools/packaging/catalog/catalog-remote.js:361:8)
[2021-11-21 19:09:45] at /tools/packaging/catalog/catalog-remote.js:150:10
[2021-11-21 19:09:45] at Db._retry (/tools/packaging/catalog/catalog-remote.js:162:16)
[2021-11-21 19:09:45] at new Db (/tools/packaging/catalog/catalog-remote.js:149:8)
[2021-11-21 19:09:45] at RemoteCatalog.initialize
[2021-11-21 19:09:45] (/tools/packaging/catalog/catalog-remote.js:699:15)
[2021-11-21 19:09:45] at /tools/cli/main.js:875:20 {
[2021-11-21 19:09:45] errno: 10,
[2021-11-21 19:09:45] code: 'SQLITE_IOERR'
[2021-11-21 19:09:45] }
[2021-11-21 19:09:46] /home/mt/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser+web.browser. legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
[2021-11-21 19:09:46] throw error;
[2021-11-21 19:09:46] ^
[2021-11-21 19:09:46]
[2021-11-21 19:09:46] Error: SQLITE_IOERR: disk I/O error
[2021-11-21 19:09:46] => awaited here:
[2021-11-21 19:09:46] at Promise.await (/home/mt/.meteor/packages/meteor-tool/.2.4.0_1.1ysxd7i.qhi2++os.linux.x86_64+web.browser +web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
[2021-11-21 19:09:46] at Db._execute (/tools/packaging/catalog/catalog-remote.js:361:8)
[2021-11-21 19:09:46] at /tools/packaging/catalog/catalog-remote.js:150:10
[2021-11-21 19:09:46] at Db._retry (/tools/packaging/catalog/catalog-remote.js:162:16)
[2021-11-21 19:09:46] at new Db (/tools/packaging/catalog/catalog-remote.js:149:8)
[2021-11-21 19:09:46] at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:699:15)
[2021-11-21 19:09:46] at /tools/cli/main.js:875:20 {
[2021-11-21 19:09:46] errno: 10,
[2021-11-21 19:09:46] code: 'SQLITE_IOERR'
[2021-11-21 19:09:46] }
[2021-11-21 19:09:46] error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
[2021-11-21 19:09:46]
[2021-11-21 19:09:46] command exited with code 1
[2021-11-21 19:09:56] ! Build failed (exit code 1)
[]
```

**Comment by renanccastro** [comment]
Hi @abdagli .

This is not the recommended way to run production applications on digital ocean. That's why your app is trying to use SQLITE, as you are running an actual meteor build, which in turn requires the feature that is not supported on DO docker instances.

You should take a look at MUP if you want to deploy to digital ocean, or only run the built package using node, if you want to have a barebone setup.

Or, you can also use Galaxy for an easier setup.

I'm closing this issue as this doesn't seem like something we can fix, unfortunately.
