### ISSUE TITLE
Can't run app after updating to 2.5.2 (SyntaxError: Unexpected end of JSON input)

### ISSUE THREAD

**Issue by markdowney** [meteor/meteor#11830]
- was running meteor 2.5.1. on macOS Bigsur.
- updated app to 2.5.2
- running the app throws the following error :

```
/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/optimistic.ts:321:17
    at wrap.makeCacheKey (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/optimistic.ts:36:15)
    at recomputeNewValue (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:198:31)
    at Slot.withValue (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at reallyRecompute (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:181:19)
    at Entry.recompute (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:91:9)
    at optimistic (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:150:25)
    at /Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/optimistic.ts:366:19
    at recomputeNewValue (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:198:31)
    at Slot.withValue (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at reallyRecompute (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:181:19)
    at Entry.recompute (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:91:9)
    at optimistic (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:150:25)
    at find (/tools/isobuild/package-source.js:1344:30)
    at /tools/isobuild/package-source.js:1400:27
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1379:22)
    at /tools/isobuild/package-source.js:1400:27
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1379:22)
    at /tools/isobuild/package-source.js:1400:27
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1379:22)
    at /tools/isobuild/package-source.js:1400:27
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1379:22)
    at find (/tools/isobuild/package-source.js:1411:25)
    at /tools/isobuild/package-source.js:1423:34
    at Object.withCache (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1662:18)
    at PackageSource._findSources (/tools/isobuild/package-source.js:1423:18)
    at SourceArch.getFiles (/tools/isobuild/package-source.js:965:32)
    at /tools/isobuild/compiler.js:406:23
    at /tools/isobuild/compiler.js:186:28
    at Object.withCache (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1662:18)
    at /tools/isobuild/compiler.js:185:11
    at Function.each (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at Object.compile (/tools/isobuild/compiler.js:180:5)
    at /tools/isobuild/bundler.js:3295:24
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3241:31)
    at /tools/isobuild/bundler.js:3184:32
    at Slot.withValue (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1662:39)
    at Object.bundle (/tools/isobuild/bundler.js:3184:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/Users/me/.meteor/packages/meteor-tool/.2.5.1.19xclpn.3tu3++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12
```

I tried without success:
- uninstalling and re-installing meteor tool 
- downgrading back to 2.5.1
- deleting `app/.meteor/*`
- removing and re-installing all npm modules

See forum thread here: https://forums.meteor.com/t/unable-to-run-after-update-to-2-5-2/57266/3

**Comment by dovydaskukalis** [comment]
Had same issue. For me deleting `.meteor` and `npm_modules` helped.

**Comment by renanccastro** [comment]
Can you please try running `meteor reset`? This usually happens if you keep old isobuild caches from older versions.

**Comment by markdowney** [comment]
`meteor reset` doesn't help. Nor does removing `~/.meteor` and reinstalling. I'm running out of ideas.

**Comment by zodern** [comment]
From the stack trace, it seems to be caused by a `package.json` file that is not valid json.

**Comment by rouftom** [comment]
I also have the same problem after updating two Meteor projects from version 2.5 to 2.5.2. The package.json files are however valid.

**Comment by markdowney** [comment]
As schapiro pointed out [here](https://forums.meteor.com/t/unable-to-run-after-update-to-2-5-2/57266/5), the problem seems to come from the [resolve package](https://www.npmjs.com/package/resolve), which has a malformed package.json for test purposes. 

Removing `/node_modules/resolve/test/resolver/malformed_package_json/` allows me to run my app locally. I'm not sure if this should be fixed in the resolve package or in the meteor-tool...

**Comment by rouftom** [comment]
@markdowney on the other hand my applications run without problem locally. The error occurs when I try to deploy the apps with a ci/cd pipeline.

**Comment by markdowney** [comment]
@rouftom the latest version of [resolve](https://github.com/browserify/resolve) with the malformed package.json was released yesterday. You might have the issue if you reinstall your node_modules ?

**Comment by rouftom** [comment]
Ok @markdowney , I will reinstall meteor and try to reproduce the issue.

**Comment by Nauzer** [comment]
Same here.
Reinstalled meteor with

```
sudo rm /usr/local/bin/meteor
rm -rf ~/.meteor
```

Only second line was not enough.

**Comment by johnwils** [comment]
Experiencing the same issue after a fresh `node_modules` install. The issue persists for me after running `meteor reset`.

**Comment by Nauzer** [comment]
> Same here. Reinstalled meteor with
> 
> ```
> sudo rm /usr/local/bin/meteor
> rm -rf ~/.meteor
> curl "https://install.meteor.com/?release=2.2" | sh
> ```
> 
> Only second line was not enough.

Worked once... not working anymore.

**Comment by Nauzer** [comment]
I have the issue running 2.2, 2.3.2 & 2.5.2 projects now after a clean install of meteor.

**Comment by renanccastro** [comment]
I can't reproduce in a fresh meteor application/installation. Is there any kind of specific step I need to do?

What I've tried so far:

Installing meteor from NPM/installing meteor from curl, creating a new meteor app - works
Upgrading an app - works

Also, can you check if there is any upper level library requiring resolve in your package.json? With `npm list` you can see the complete tree

**Comment by Nauzer** [comment]
I just tried again as well...
No more issues even when removing node_modules & reinstalling works fine.
Folder /node_modules/resolve/test/resolver/malformed_package_json/ was not present though

So I did an meteor npm update and there it was again

**Comment by markdowney** [comment]
@renanccastro  Also seems to come from `jest` module.
```
[1/4] 🤔  Why do we have the module "app/node_modules/resolve"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "app#resolve@1.21.0"
info Reasons this module exists
   - "_project_#app#babel-plugin-module-resolver" depends on it
   - Hoisted from "_project_#app#babel-plugin-module-resolver#resolve"
   - Hoisted from "_project_#app#@babel#plugin-transform-runtime#babel-plugin-polyfill-corejs2#@babel#helper-define-polyfill-provider#resolve"
   - Hoisted from "_project_#app#jest#@jest#core#jest-resolve#resolve"
   ```

**Comment by filipenevola** [comment]
I believe this PR #11832 fixes the problem now and also helps to identify and workaround similar issues in the future.

Let me know what you think.

**Comment by filipenevola** [comment]
I'm starting the release process of Meteor 2.5.3 including this fix.

**Comment by rouftom** [comment]
Thanks @filipenevola , it works. I made a pull request to the resolve package to fix the bug that cause the issue.

**Comment by filipenevola** [comment]
Meteor 2.5.3 is released now!

**Comment by YusufKolcuk** [comment]
Can we solve it in a different way than updating to version 2.5.3? Upgrading didn't work for me.

**Comment by rouftom** [comment]
@YusufKolcuk try to delete your **node_modules** directory and reinstall with `meteor npm install`

**Comment by YusufKolcuk** [comment]
I found a workaround to the problem using
"rm -rf ./node_modules/resolve/test/resolver/malformed_package_json/package.json"

**Comment by mrpehlivan** [comment]
When I add the resolve 1.20 version, the issue has gone.

**Comment by filipenevola** [comment]
Hi @YusufKolcuk what was the error that you got after upgrading it?

In the case of a similar problem at least in version 2.5.3, you should have a clear log showing what is the problematic directory.

And yes, removing this malformed package.json file manually should work as well.

**Comment by simplecommerce** [comment]
I have the same issue on all my projects that run meteor 1.9.2, I updated to 2.5.3 and it works.
Downgraded to 2.5.2 I get the same error above.

I am hoping there can be a fix for this other than updating to the latest version? For my current apps I can't update to 1.9.2 until another issue is solved.

**Comment by rouftom** [comment]
As @mrpehlivan mentioned [here](https://github.com/meteor/meteor/issues/11830#issuecomment-1005712797), an alternative would be to install for example resolve v1.20 with `meteor npm install resolve@1.20.0` to correct the issue.

**Comment by simplecommerce** [comment]
> As @mrpehlivan mentioned [here](https://github.com/meteor/meteor/issues/11830#issuecomment-1005712797), an alternative would be to install for example resolve v1.20 with `meteor npm install resolve@1.20.0` to correct the issue.

I will try that for now, thanks!

**Comment by damienfa** [comment]
Same issue here.
I use an old Meteor 1.12 (with Nodejs 14.20.0).

As pointed out above, the issue comes from the library `resolve`.
The  `rm -rf ./node_modules/resolve/test/resolver/malformed_package_json/package.json` didn't worked in my case because I've more than 26 dependencies using with `resolve`.
For example : 
- `./node_modules/eslint-plugin-import/node_modules/resolve/test/resolver/malformed_package_json`
- `./node_modules/apollo-codegen/node_modules/resolve/test/resolver/malformed_package_json`
- `./node_modules/read-pkg/node_modules/resolve/test/resolver/malformed_package_json`
etc.

(It's insane. I'm really tired of NodeJs / NPM copying sooo many times the same library, because every package use a different version of `revolve` as a dependency).

My only solution is to launch this command in my CI/CD just before my `meteor build …` : 

```
find ./node_modules -name malformed_package_json -type d -prune -exec rm  -rf "{}" \;`
```
(this command removes every folder named `malformed_package_json` in the `node_modules` folder).

**Comment by rouftom** [comment]
@damienfa try this alternative https://github.com/meteor/meteor/issues/11830#issuecomment-1005900459

**Comment by damienfa** [comment]
@rouftom, thanks. I've tried to installed the `resolve@1.20.0` but if 26 of my dependencies use an other version of `resolve` the "malformed files" are still present in my folders and the error happens… :(

**Comment by onepointconsulting** [comment]
@damienfa Your suggestion works well. Here is an extract of my Dockerfile that now works:

```
#Install dependencies and build image
RUN meteor npm install
RUN find ./node_modules -name malformed_package_json -type d -prune -exec rm  -rf "{}" \;
RUN meteor build --verbose --directory /usr/build --architecture 'os.linux.x86_64'
```

**Comment by idhowardgj94** [comment]
@damienfa's solution work for me.
And BTW, it seems to have typo that one ` after that command.
it should be 
`find ./node_modules -name malformed_package_json -type d -prune -exec rm  -rf "{}" \;`

**Comment by lcampanis** [comment]
To avoid running additional steps in Docker, it seems cleaner to add the command as a **package.json** `postinstall` script.

In your **package.json**:
```json
{
  "scripts": {
    "postinstall": "find ./node_modules -name malformed_package_json -type d -prune -exec rm  -rf \"{}\" \\;"
  },
  ...
}    
```
Now every time you do `meteor npm install` or `meteor npm i` or `npm i` it will remove those files.
Nicely done @damienfa!

**Comment by ljharb** [comment]
If that’s still needed after v2.5.3 of meteor, then this should be reopened.
