### ISSUE TITLE
npm install -D tailwindcss then result : SyntaxError: Unexpected end of JSON input.

### ISSUE THREAD

**Issue by asgaraliyev** [meteor/meteor#11881]
<!--

### This bug report should include:
- [ ] Tailwind config SyntaxError: Unexpected end of JSON input.
- [ ] The version of Meteor showing the problem: METEOR@2.2.2.
- [ ] The operating system you're running Meteor on:Linux ubuntu 20
- [ ] The expected behavior.runing meteor app 
- [ ] The actual behavior.SyntaxError: Unexpected end of JSON input.Cant run due to error
- [ ] A **simple** reproduction! repo: https://github.com/asgaraliyev/meteor-react-konstaui-tailwind

### Independent packages
https://github.com/asgaraliyev/meteor-react-konstaui-tailwind/blob/master/.meteor/packages

Full Error:
asgaraliyev@Lenovo-V15-ADA:~/Desktop/projects/ustam-project/client$ meteor
[[[[[ ~/Desktop/projects/ustam-project/client ]]]]]

=> Started proxy.                             
=> Started HMR server.                        
                                              
Changes to your project's package version selections:
                                              
juliancwirko:postcss         added, version 2.0.6
standard-minifier-css        removed from your project
tmeasday:check-npm-versions  added, version 1.0.2

WARNING: npm peer requirements (for juliancwirko:postcss) not installed:
   - postcss@8.2.x not installed.
 - postcss-load-config@3.1.1 installed, postcss-load-config@3.0.x needed

  Read more about installing npm peer dependencies:
    http://guide.meteor.com/using-packages.html#peer-npm-dependencies
  
/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:321:17
    at wrap.makeCacheKey (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:36:15)
    at recomputeNewValue (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:182:31)
    at Slot.withValue (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at reallyRecompute (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:165:19)
    at Entry.recompute (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:85:9)
    at optimistic (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:101:25)
    at /home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:366:19
    at recomputeNewValue (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:182:31)
    at Slot.withValue (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at reallyRecompute (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:165:19)
    at Entry.recompute (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:85:9)
    at optimistic (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:101:25)
    at find (/tools/isobuild/package-source.js:1344:30)
    at /tools/isobuild/package-source.js:1400:27
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1379:22)
    at /tools/isobuild/package-source.js:1400:27
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1379:22)
    at /tools/isobuild/package-source.js:1400:27
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1379:22)
    at /tools/isobuild/package-source.js:1400:27
    at Array.forEach (<anonymous>)
    at find (/tools/isobuild/package-source.js:1379:22)
    at find (/tools/isobuild/package-source.js:1411:25)
    at /tools/isobuild/package-source.js:1423:34
    at Object.withCache (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1663:18)
    at PackageSource._findSources (/tools/isobuild/package-source.js:1423:18)
    at SourceArch.getFiles (/tools/isobuild/package-source.js:965:32)
    at /tools/isobuild/compiler.js:406:23
    at /tools/isobuild/compiler.js:186:28
    at Object.withCache (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1663:18)
    at /tools/isobuild/compiler.js:185:11
    at Function._.each._.forEach (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:186:9)
    at Object.compile (/tools/isobuild/compiler.js:180:5)
    at /tools/isobuild/bundler.js:3268:24
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3214:31)
    at /tools/isobuild/bundler.js:3157:32
    at Slot.withValue (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at Object.withCache (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1663:39)
    at Object.bundle (/tools/isobuild/bundler.js:3157:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/home/asgaraliyev/.meteor/packages/meteor-tool/.2.2.2.1vgp5p8.l3o2++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:948:28)
    at /tools/runners/run-app.js:410:12

**Comment by renanccastro** [comment]
This seems related to https://github.com/meteor/meteor/issues/11839, but we need a better issue description to move forward.

I'm closing it for the moment.

**Comment by vojdan** [comment]
Pls reopen, I'm getting the same issue when upgrading to TailwindCSS v3 (from v2)

**Comment by renanccastro** [comment]
Hello @vojdan for reopening this issue we need more details.

Which Meteor version are you running? This bug is fixed on the latest Meteor, 2.6.1. We also need a reproduction with clear steps.

In any case, if you want to bring this info for analysis it will be better to open a new issue. Thanks.

**Comment by vojdan** [comment]
Meteor update to 2.6 fixed this, thanks!
