### ISSUE TITLE
"npm ERR! cb() never called" when installing npm dependencies

### ISSUE THREAD

**Issue by mitar** [meteor/meteor#1190]
When trying to install a large npm tarball dependency (7.9 MB) I get an error:

```
Error: Command failed: npm http GET https://github.com/peerlibrary/pdf.js/tarball/d48097845fa4fb4e00fe895d0412872535ad0730

at Object.Future.wait (/home/travis/.meteor/tools/cc18dfef9e/lib/node_modules/fibers/future.js:322:15)
at Object._.extend._execFileSync (/home/travis/.meteor/tools/cc18dfef9e/tools/meteor_npm.js:231:10)
at Object._.extend._installNpmModule (/home/travis/.meteor/tools/cc18dfef9e/tools/meteor_npm.js:342:10)
at _.extend._createFreshNpmDirectory (/home/travis/.meteor/tools/cc18dfef9e/tools/meteor_npm.js:192:12)
at Function._.each._.forEach (/home/travis/.meteor/tools/cc18dfef9e/lib/node_modules/underscore/underscore.js:86:24)
at Object._.extend._createFreshNpmDirectory (/home/travis/.meteor/tools/cc18dfef9e/tools/meteor_npm.js:191:7)
at Object._.extend.updateDependencies (/home/travis/.meteor/tools/cc18dfef9e/tools/meteor_npm.js:85:14)
at _.extend.installNpmDependencies (/home/travis/.meteor/tools/cc18dfef9e/tools/packages.js:317:17)
at _.extend._maybeUpdateNpmDependencies (/home/travis/.meteor/tools/cc18dfef9e/tools/bundler.js:422:13)
at _.extend.includeTests (/home/travis/.meteor/tools/cc18dfef9e/tools/bundler.js:484:10)
at exports.bundle (/home/travis/.meteor/tools/cc18dfef9e/tools/bundler.js:878:16)
at Array.forEach (native)
at Function._.each._.forEach (/home/travis/.meteor/tools/cc18dfef9e/lib/node_modules/underscore/underscore.js:78:11)
at Object.exports.bundle (/home/travis/.meteor/tools/cc18dfef9e/tools/bundler.js:877:9)
at /home/travis/.meteor/tools/cc18dfef9e/tools/run.js:697:26
at exports.inFiber (/home/travis/.meteor/tools/cc18dfef9e/tools/fiber-helpers.js:24:12)
- - - - -
npm http 200 https://github.com/peerlibrary/pdf.js/tarball/d48097845fa4fb4e00fe895d0412872535ad0730

npm ERR! cb() never called!
npm ERR! not ok code 0

at ChildProcess.exithandler (child_process.js:540:15)
at ChildProcess.EventEmitter.emit (events.js:99:17)
at maybeClose (child_process.js:638:16)
at Process._handle.onexit (child_process.js:680:5)
```

**Comment by timhaines** [comment]
@n1mmy I'm see this again today.  Have node v0.10.33 installed.

**Comment by shawnmclean** [comment]
Also getting this error. I tried `npm cache clean`. I deleted the node_modules, etc. Out of 10 builds, `npm install` worked 2 times. This is happening on both my dev and build machine.

    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
    ed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
    npm\node_modules\node-gyp\lib\build.js:269:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
    :12)
    gyp ERR! System Windows_NT 6.3.9600
    gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
    les\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Projects\MyApp\node_modules\grunt-styleguide\
    node_modules\kss\node_modules\node-sass
    gyp ERR! node -v v0.12.2
    gyp ERR! node-gyp -v v1.0.3
    gyp ERR! not ok
    Build failed
    npm ERR! cb() never called!
