### ISSUE TITLE
Adding Package: RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be <= -3. Received 18

### ISSUE THREAD

**Issue by chasemaier** [meteor/meteor#11918]
See also: https://meteor-community.slack.com/archives/CUDJF42HL/p1640029358290400 (same error under a different context, but the below is a brand new app)

Opening an issue since I now have a concise reproduction with one bash chain of commands (encountered trying to reproduce an unrelated error):

---

Environment:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

---

Command to create app and immediately encounter error:

```
meteor create --blaze --release 2.6 out-of-range-repro \
 && cd out-of-range-repro \
 && meteor update \
 && meteor add iron:router
```

* **Note:** Same chain without the meteor update step produces same result.
* **Note:** Same commands invoked repeatedly produce the same output consistently

---

Produces:

```
$ meteor create --blaze --release 2.6 out-of-range-repro \
>  && cd out-of-range-repro \
>  && meteor update \
>  && meteor add iron:router
Created a new Meteor app in 'out-of-range-repro'.

To run your new app:                          
  cd out-of-range-repro                       
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials            
                                              
When you’re ready to deploy and host your new Meteor application, check out Cloud:
  https://www.meteor.com/cloud                
                                              
To start with a different app template, try one of the following:

  meteor create --bare       # to create an empty app
  meteor create --minimal    # to create an app with as few Meteor packages as possible
  meteor create --full       # to create a more complete scaffolded app
  meteor create --react      # to create a basic React-based app
  meteor create --vue        # to create a basic Vue-based app
  meteor create --apollo     # to create a basic Apollo + React app
  meteor create --svelte     # to create a basic Svelte app
  meteor create --typescript # to create an app using TypeScript and React
  meteor create --blaze      # to create an app using Blaze
                                              
This project is already at Meteor 2.6, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
Newer versions of the following indirect dependencies are available:
 * caching-html-compiler 1.2.0 (1.2.1 is available)
 * spacebars-compiler 1.2.1 (1.3.0 is available)
 * templating-tools 1.2.0 (1.2.1 is available)
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.
If the packages do not upgrade after this, this could mean
that there is a newer version of Meteor which the package
requires, but it not yet recommended or that some package
dependencies are not up to date and don't allow you to get
the latest package version.
/home/cmaier/.meteor/packages/meteor-tool/.2.6.0.1vpxp2a.e3wg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be <= -3. Received 18
    at Object.readSync (fs.js:607:3)
    at /home/cmaier/.meteor/packages/meteor-tool/.2.6.0.1vpxp2a.e3wg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1493:23
    at Object.readBufferWithLengthAndOffset (/home/cmaier/.meteor/packages/meteor-tool/.2.6.0.1vpxp2a.e3wg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1405:21)
    at /tools/isobuild/unibuild.js:123:26
    at Function.each (/home/cmaier/.meteor/packages/meteor-tool/.2.6.0.1vpxp2a.e3wg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at Function.fromJSON (/tools/isobuild/unibuild.js:120:7)
    at /tools/isobuild/isopack.js:921:33
    at Function.each (/home/cmaier/.meteor/packages/meteor-tool/.2.6.0.1vpxp2a.e3wg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:908:7)
    at /tools/packaging/tropohouse.js:521:21
    at Function.each (/home/cmaier/.meteor/packages/meteor-tool/.2.6.0.1vpxp2a.e3wg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at /tools/packaging/tropohouse.js:520:13
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:515:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:600:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:597:20)
    at /tools/project-context.js:921:25
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/project-context.js:920:20
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:919:13)
    at /tools/project-context.js:365:9
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:355:18)
    at /tools/project-context.js:347:12
    at Function.run (/home/cmaier/.meteor/packages/meteor-tool/.2.6.0.1vpxp2a.e3wg++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:346:13)
    at /tools/cli/commands-packages.js:2291:20
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Command.func (/tools/cli/commands-packages.js:2290:27)
    at /tools/cli/main.js:1534:15 {
  code: 'ERR_OUT_OF_RANGE'
}
```

**Comment by vrizo** [comment]
Thank you for the detailed description, @chasemaier!

The same problem to me on macOS Big Sur 11.5.2. Tried `meteor npm cache clean --force && rm -Rf node_modules && meteor npm install` with no luck.

I also tried to connect via VPN because of the presence of "download" and "packaging" in the logs. Nothing works.

A coworker of mine tried to run the project under Windows 10, and it starts without any issues.

**Comment by anantonton** [comment]
same problem on Catalina. Nothing works.

**Comment by anantonton** [comment]
i pinpointed that iron:router is the offender. if you exclude iron:router from .meteor/packages, everything runs properly.

**Comment by vrizo** [comment]
Hello guys,

I was investigating this issue the whole day. I was debugging unibuild.js, bundler.js, files.js, trying to find why there are two `head`s in `unibuildJson`. One of them has length 18 with offset 21 for some reason. That’s why we're getting negative length.

```js
{
    resources: [
        { type: 'head', file: 'web.browser/head', length: 20, offset: 0 },
        { type: 'head', file: 'web.browser/head', length: 18, offset: 21 },
        …
    ],
    …
}
```

And a straightforward fix helped me.

```bash
sudo rm /usr/local/bin/meteor
rm -rf ~/.meteor
curl https://install.meteor.com/ | sh
```
_(note: this may differ depending on your configuration)_

I tried reinstalling Meteor without manual cleaning, but it didn’t help. Then I decided to delete everything meteor-related from my laptop and install Meteor again. It works!!

**Comment by StorytellerCZ** [comment]
@vrizo I'm glad that you have found your solution. Still would be good to know why this has happened in the first place.

**Comment by nachocodoner** [comment]
This appears to have been caused by local cache corruption inside `~/.meteor` (as confirmed by commenters who fixed it via a clean install). Attempting this in Meteor 3 simply throws a standard dependency version conflict for `iron:router`. Closing as obsolete.

Regarding iron:router compatibility in Meteor 3, please check out the community forum post on its succesor: https://forums.meteor.com/t/galvanized-iron-router-2-0-0-released-rust-resistant-routing-for-meteor-2-0-3-0/63703
