### ISSUE TITLE
Meteor 2.6: Error in oplog callback RangerError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#11924]
Overnight, our newly deployed Meteor 2.6 + Mongo 5.0 test deployment had filled the logs with these errors

```
Error in oplog callback RangerError: Maximum call stack size exceeded
```

<details>
<summary>Full stacktrace</summary>

```
[aurora]Error in oplog callback RangeError: Maximum call stack size exceeded
[aurora]    at String.match (<anonymous>)
[aurora]    at packages/mongo/oplog_v2_converter.js:27:78
[aurora]    at Array.find (<anonymous>)
[aurora]    at isArrayOperator (packages/mongo/oplog_v2_converter.js:27:46)
[aurora]    at packages/mongo/oplog_v2_converter.js:35:9
[aurora]    at Array.forEach (<anonymous>)
[aurora]    at nestedOplogEntryParsers (packages/mongo/oplog_v2_converter.js:34:27)
[aurora]    at packages/mongo/oplog_v2_converter.js:50:9
[aurora]    at Array.forEach (<anonymous>)
[aurora]    at nestedOplogEntryParsers (packages/mongo/oplog_v2_converter.js:34:27)
[aurora]    at packages/mongo/oplog_v2_converter.js:50:9
[aurora]    at Array.forEach (<anonymous>)
[aurora]    at nestedOplogEntryParsers (packages/mongo/oplog_v2_converter.js:34:27)
[aurora]    at packages/mongo/oplog_v2_converter.js:50:9
[aurora]    at Array.forEach (<anonymous>)
[aurora]    at nestedOplogEntryParsers (packages/mongo/oplog_v2_converter.js:34:27)
[aurora]    at packages/mongo/oplog_v2_converter.js:50:9
[aurora]    at Array.forEach (<anonymous>)
[aurora]    at nestedOplogEntryParsers (packages/mongo/oplog_v2_converter.js:34:27)
[aurora]    at packages/mongo/oplog_v2_converter.js:50:9
[aurora]    at Array.forEach (<anonymous>)
[aurora]    at nestedOplogEntryParsers (packages/mongo/oplog_v2_converter.js:34:27)
```

</details>

I've no idea what this is about and cannot provide a reproduction, but I thought this might be valuable information regarding the recent transition to the new Mongo 5.0 version and potential hiccups in the process.

**Comment by renanccastro** [comment]
Hello, @arggh .
I'm introducing in 2.6.1 verbose debug messages for the oplog converter.
This will help to understand which kind of oplog messages are causing this issue in this method.
I will let you know when it's released.


When it's released, can you please add it to your project and let it run until the error shows again? Then, you can post the logs here for our analysis.
