### ISSUE TITLE
run android-device, cordova version error

### ISSUE THREAD

**Issue by BernardoBCabrita** [meteor/meteor#11952]
_**On Meteor version 2.6.1.**_

**My OS information:** 
- Edition: Windows 11
- Version: 21H2
- SO Compilation: 22000.527

To test meteor cordova integration I created a new app with meteor,  I ran the command:
`meteor create cordova-test`

After installing all prerequisites, I ran the command: 
`"meteor add-platform android"` 

This is the output:

```
Creating a new cordova project.              -
Using cordova-fetch for cordova-android@10.1.1
Adding android project...                    \
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.idxzkb4emvp4i.w6l0r2jh65qq
        Name: cordova-test
        Activity: MainActivity
        Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.1
android: added platform
```

Consequently, I tried to run the command 
`"meteor run android-device --mobile-server 192.168.56.1"` 

This is the output:

```
C:\Users\berna\SATO-Meteor-Projects\meteor-cordova-version-bug\cordova-test>meteor run android-device --mobile-server 192.168.56.1
C:\Users\berna\AppData\Local\.meteor\packages\meteor-tool\2.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: Command failed: C:\Users\berna\SATO-Meteor-Projects\meteor-cordova-version-bug\cordova-test\.meteor\local\cordova-build\platforms\android\cordova\version
'C:\Users\berna\SATO-Meteor-Projects\meteor-cordova-version-bug\cordova-test\.meteor\local\cordova-build\platforms\android\cordova\version' is not recognized as an internal or external command,
operable program or batch file.
    at ChildProcess.exitCallback (C:\Users\berna\AppData\Local\.meteor\packages\meteor-tool\2.6.1\mt-os.windows.x86_64\tools\utils\tools\utils\processes.ts:174:23)
    at ChildProcess.emit (events.js:412:35)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
 => awaited here:
    at Function.Promise.await (C:\Users\berna\AppData\Local\.meteor\packages\meteor-tool\2.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:56:12)
    at execFileSync (C:\Users\berna\AppData\Local\.meteor\packages\meteor-tool\2.6.1\mt-os.windows.x86_64\tools\utils\tools\utils\processes.ts:60:24)
    at CordovaProject.installedVersionForPlatform (C:\tools\cordova\project.js:434:9)
    at C:\tools\cordova\project.js:135:39
    at Function.some (C:\Users\berna\AppData\Local\.meteor\packages\meteor-tool\2.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore-node-f-pre.js:1406:9)
    at CordovaProject.createIfNeeded (C:\tools\cordova\project.js:129:26)
    at new CordovaProject (C:\tools\cordova\project.js:118:10)
    at C:\tools\cli\commands.js:419:32
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.main.captureAndExit (C:\tools\cli\main.js:279:29)
    at prepareCordovaProject (C:\tools\cli\commands.js:418:12)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:433:5)
    at C:\tools\cli\main.js:1534:15 {
  pid: 11540,
  stdout: '',
  stderr: "'C:\\Users\\berna\\SATO-Meteor-Projects\\meteor-cordova-version-bug\\cordova-test\\.meteor\\local\\cordova-build\\platforms\\android\\cordova\\version' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  status: 1,
  signal: null
}
```

The expected behaviour is for the application to run on my connected device, but that's not working.

Github repo with my project files:
https://github.com/BernardoBCabrita/meteor-cordova-version-bug/tree/main/cordova-test

<!--
Before reporting a bug, please check for existing or closed issues
first and read the instructions for filing a bug report:
https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor

### This bug report should include:
- [ ] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [ ] The version of Meteor showing the problem.
- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
- [ ] The operating system you're running Meteor on.
- [ ] The expected behavior.
- [ ] The actual behavior.
- [ ] A **simple** reproduction! (Must include the Github repository and steps to reproduce the issue on it.)

If you don't include a reproduction the issue is probably going to be closed.

**Comment by edu2969** [comment]
Same here in Meteor 2.6.1
node v14.18.3
gradle 7.1.1 (tried 6.8.3 too)
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)

My cordova-plugins file:

`cordova-custom-config@5.1.0
cordova-plugin-app-version@0.1.9
cordova-plugin-compat@1.2.0
cordova-plugin-device@2.0.3
cordova-plugin-geolocation@4.0.2
cordova-plugin-inappbrowser@5.0.0
cordova-plugin-splashscreen@5.0.3
cordova-plugin-statusbar@2.4.3
phonegap-plugin-push@2.3.0
skwas-cordova-plugin-datetimepicker@2.1.1
cordova-plugin-androidx-adapter@1.1.3`

Some update?

**Comment by v1934** [comment]
Same here at meteor 2.7.1, first build goes fine but next one yields this error about `cordova\version` not being recognized, I need to do `meteor reset` everytime.
I thought it's because I had meteor installed by choco, but after uninstalling and installing with `npm install -g meteor`, cleaning everything in my project (`.meteor/local, node_modules`) it's the same.

But it only happens in Windows. I have exactly the same environment running on MacOS and it doesn't occur there, subsequent builds/runs work fine.
The specified path is present, I can see the version file there. I think it's some problem with launching it, since I can see the file starts with:
```
#!/usr/bin/env node
```
That's a linux shebang and it's ignored on Windows. Since the file has no extension at all, no file association is there to launch it automatically with node. It's just weird that it works the first time.

**Comment by nachocodoner** [comment]
Is this issue still applicable on Meteor 3? Because Meteor 3 has recieved lot of fixes even for native flows. I'm going to close this but I would like a proper reproduction on Meteor 3, since Meteor 2 reached its end of life. Reopen if a Meteor 3 reproduction is provided. We are working nowadays towards the native build stack overhaul and any issue is welcome to considered to be fixed. Also as we transit to CapacitorJS many of these will become obsolete. But we still plan to fix Cordova issues as reproducible.
