### ISSUE TITLE
Accounts.changePassword server stacktrace when oldPassword is empty

### ISSUE THREAD

**Issue by mdede** [meteor/meteor#11961]
- [When calling Accounts.changePassword() on the client, the callback returns Error: Internal server error [500] and there is a stacktrace on the server. See below.]
- [2.6.1 ] The version of Meteor showing the problem.
- [2.6.1] The last version of Meteor where the problem did _not_ occur, if applicable.
- [ubuntu 20.04] The operating system you're running Meteor on.
- [Function shall pass without errors, since the user does not have a password. ] The expected behavior.
- [Stacktrace on the server.] The actual behavior.
- [On a client, just call: Accounts.changePassword('', 'newpassword') ] A **simple** reproduction! (Must include the Github repository and steps to reproduce the issue on it.)

I20220307-16:25:42.548(1)? Exception while invoking method 'changePassword' TypeError: Cannot read property 'algorithm' of null
I20220307-16:25:42.549(1)?     at getPasswordString (packages/accounts-password/password_server.js:37:18)
I20220307-16:25:42.550(1)?     at Accounts._checkPassword (packages/accounts-password/password_server.js:82:29)
I20220307-16:25:42.550(1)?     at MethodInvocation.changePassword (packages/accounts-password/password_server.js:262:18)
I20220307-16:25:42.551(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
I20220307-16:25:42.551(1)?     at packages/ddp-server/livedata_server.js:769:19
I20220307-16:25:42.551(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220307-16:25:42.552(1)?     at packages/ddp-server/livedata_server.js:767:46
I20220307-16:25:42.552(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220307-16:25:42.552(1)?     at packages/ddp-server/livedata_server.js:765:46
I20220307-16:25:42.553(1)?     at new Promise (<anonymous>)
I20220307-16:25:42.553(1)?     at Session.method (packages/ddp-server/livedata_server.js:739:23)
I20220307-16:25:42.553(1)?     at packages/ddp-server/livedata_server.js:603:43

**Comment by bcluyse** [comment]
I have taken the liberty to look into this issue.
I do not think changePassword was meant to work when an empty string was passed as the first object but I will leave that up for discussion. It does seem like at server-side the oldPassword is transformed from an empty string to null, which probably is related to how passwords are sent over the websocket connection.

However, it seems like the passwordValidator is incorrectly allowing null as a value for oldPassword.
After some short investigation, it seems like the following change for the passwordValidtor resolves the internal server error.

https://github.com/bcluyse/meteor/commit/4f1190546b0deb81567276e7251d8afdd3f4598b

I have not written any tests since there dont seem to be any tests related to matchers in the accounts-password package but those can be added. If any of the maintainers can chime on this issue, I can make a pull request and add unit tests if necessary.

**Comment by mdede** [comment]
Looking at client side implementation, oldPassword may clearly be empty string. Passed as `null` to the call.
[See Line 164](https://github.com/meteor/postgres-packages/blob/694a96f406b2387b146cb36f353fa00e5b0c6342/packages/accounts-password/password_client.js#L164).

**Comment by bcluyse** [comment]
The method documentation does clearly state that the front-end does not block it but by default back-end should not support it, [See line 137](https://github.com/meteor/postgres-packages/blob/694a96f406b2387b146cb36f353fa00e5b0c6342/packages/accounts-password/password_client.js#L137)

Of course, I will leave this up to the maintainers on how they want to resolve this issue.
But to me it seems that the only issue is the fact that the back-end validation does not fail.

**Comment by StorytellerCZ** [comment]
If there is anything that talks about compatibility with Meteor bellow 1.0, then that is no longer available in Meteor since 2.3. I'm seeing that you are referencing the meteor/postgres-packages. Is that by mistake or are you trying to use that project?

**Comment by mdede** [comment]
Uuups, was not intention, here is current devel link: https://github.com/meteor/meteor/blob/73b538fe201cbfe89dd0c709689023f9b3eab1ec/packages/accounts-password/password_client.js#L157

**Comment by nachocodoner** [comment]
The underlying operator precedence bug in `passwordValidator` that allowed `null` passwords to crash the server was fixed in commit `d037fe6b6e` https://github.com/meteor/meteor/pull/14075. The server now correctly throws a Match error.
