### ISSUE TITLE
Error: missing tool for os.osx.arm64 in meteor-tool@2.7.1 in Mac M1

### ISSUE THREAD

**Issue by foyzulkarim** [meteor/meteor#12012]
Recently we upgraded meteor to version 2.7.1 and my project stopped working. Below are the detailed info.

- **Operating system**: Apple Mac M1
- **Meteor version**: `Meteor 2.7.1` (Ran using rosetta)
- **Last working version** (I was using): 2.5.3 / 2.5.1 (forgot the last digit)
- **Expected behavior**: Should run properly 😀
- **Actual behavior**: Error missing some packages (stack trace and logs are below)
- **Reproduction steps**: Can't provide as it is broken 
- **Alternative / bypass solution**: Working fine when I run using rosetta terminal

## Terminal error stack trace

```
> [company_name]@[version] start /Users/foyzul/github/[company_name]/app
> npm run dev


> [company_name]@[version] dev /Users/foyzul/github/[company_name]/app
> meteor run --inspect --settings local.settings.json --exclude-archs web.browser.legacy

/Users/foyzul/.meteor/packages/meteor-tool/.2.5.3.ky7a59.111y++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: missing tool for os.osx.arm64 in meteor-tool@2.7.1
    at springboard (/tools/cli/main.js:504:11)
    at /tools/cli/main.js:1165:7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [company_name]@[version] dev: `meteor run --inspect --settings local.settings.json --exclude-archs web.browser.legacy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the [company_name]@[version] dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/foyzul/.npm/_logs/2022-04-21T01_32_40_263Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [company_name]@[version] start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the [company_name]@[version] start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/foyzul/.npm/_logs/2022-04-21T01_32_40_290Z-debug.log
```

## Debug log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/foyzul/.nvm/versions/node/v14.18.3/bin/node',
1 verbose cli   '/Users/foyzul/.nvm/versions/node/v14.18.3/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle [company_name]@[version]~prestart: [company_name]@[version]
6 info lifecycle [company_name]@[VERSION]~start: [company_name]@[version]
7 verbose lifecycle [company_name]@[VERSION]~start: unsafe-perm in lifecycle true
8 verbose lifecycle [company_name]@[VERSION]~start: PATH: /Users/foyzul/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/foyzul/github/[company_name]/app/node_modules/.bin:/Users/foyzul/.nvm/versions/node/v14.18.3/bin:/Users/foyzul/.meteor:/Users/foyzul/.nvm/versions/node/v17.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/foyzul/.meteor:/Users/foyzul/.nvm/versions/node/v17.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin
9 verbose lifecycle [company_name]@[VERSION]~start: CWD: /Users/foyzul/github/[company_name]/app
10 silly lifecycle [company_name]@[VERSION]~start: Args: [ '-c', 'npm run dev' ]
11 silly lifecycle [company_name]@[VERSION]~start: Returned: code: 1  signal: null
12 info lifecycle [company_name]@[VERSION]~start: Failed to exec start script
13 verbose stack Error: [company_name]@[VERSION] start: `npm run dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/foyzul/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/foyzul/.nvm/versions/node/v14.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid [company_name]@[VERSION]
15 verbose cwd /Users/foyzul/github/[company_name]/app
16 verbose Darwin 21.4.0
17 verbose argv "/Users/foyzul/.nvm/versions/node/v14.18.3/bin/node" "/Users/foyzul/.nvm/versions/node/v14.18.3/bin/npm" "start"
18 verbose node v14.18.3
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error [company_name]@[VERSION] start: `npm run dev`
22 error Exit status 1
23 error Failed at the [company_name]@[VERSION] start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by denihs** [comment]
Hi @foyzulkarim, are you still having this problem? I've checked our published files, and they seem correct. I'll try to reproduce it, but as you were the only one reporting this error, it doesn't seem to be happening with everybody.

**Comment by foyzulkarim** [comment]
Hi @denihs Thanks for your reply.
I did some digging why it was not working. I deleted my `node_modules` and `.meteor` directories. Then I was getting error saying `python2` not found. After some searching, I came to know that python2 is not preinstalled in latest MacOS 
 [[news source](https://developer.apple.com/documentation/macos-release-notes/macos-catalina-10_15-release-notes)]. I guess it is the root cause. 
As a solution, I installed `python2` and reinstalled meteor and the code was working again. 
Below is the working installation log (check line number 2 where it is checking the `python2` 

```
...
...
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
gyp verb check python version `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2 -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir compiling against specified --nodedir dev files: /Users/foyzul/.meteor/packages/meteor-tool/.2.7.1.1ad0i45.8b42++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle
gyp verb build dir attempting to create "build" dir: /Users/foyzul/fk/temp/[company_name]/app/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/foyzul/fk/temp/[company_name]/app/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/foyzul/fk/temp/[company_name]/app/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/foyzul/fk/temp/[company_name]/app/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/foyzul/fk/temp/[company_name]/app/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
...
...
```

I believe if you remove your `python2` installation directory, you can reproduce this error.

**Comment by denihs** [comment]
Hi @foyzulkarim, good to know you were able to fix it. But to be sure, can we close this issue? It doesn't seem to be a problem on the Meteor side...

**Comment by foyzulkarim** [comment]
Yes, we can close it.
I thought meteor somehow using python2, so may be meteor can start using python3 as a solution.

**Comment by repetitioestmaterstudiorum** [comment]
Had the same problem, and I had to
- Install the latest Meteor version https://www.meteor.com/developers/install installed (I had an older version installed - not sure if the upgrade would've happened automatically)
- I use Pyenv and had version 3 set up globally. So I had to `pyenv install 2.7` then `pyenv local 2.7` to set Python 2 in the current directory
- Then I also had to make sure I had the correct node version (14) using NVM
- Then meteor reset, remove node_modules and then `meteor npm i`
