### ISSUE TITLE
Android Cordova Build Has errors and App is not Loading completely

### ISSUE THREAD

**Issue by hgarcia101685** [meteor/meteor#12025]
Meteor Version 2.7.1, Mac OS 10.15.7, Android 11, SDK target and min version 31

**Expected Behavior:**
I expect my metoer build resulting apk to load on my device and for the app to look at least similar to my web build in the browser.  

**Actual Behavior:**
My app seems to load "half way", it seems that after the javascript is loaded it fails and the remainder of my app just doesn't render.  Header seems to load fine, and body does not.  I was able to connect the app to the Chrome Android debugging tool and I grabbed this stack trace.  

```
Uncaught TypeError: G.values is not a function or its return value is not iterable
    at Y (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:164:2115)
    at Oe (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:261:19)
    at e (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:261:163)
    at g (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:7:1094)
    at d.n [as require] (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:7:3652)
    at d.i [as link] (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:9:4030)
    at e (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:130:86505)
    at g (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:7:1094)
    at d.n [as require] (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:7:3652)
    at d.i [as link] (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:9:4030)
b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:1581 Uncaught TypeError: Cannot read properties of undefined (reading 'public')
    at b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:1581:3782
    at a (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:1:5756)
    at Channel.s (b12a56a9ec3e7086e5e026710e72aee8e8f80440.js?meteor_js_resource=true:1:5692)
    at Channel.fire (cordova.js:872:23)
    at cordova.js:232:49

```
**Additional Notes:**
I grabbed the stacktrace by running the chrome Android debugging.  
I've attempted to get this working by both using the generated apk in meteor build and also loading the resulting project into Android Studio and building a signed APK and the same thing happens.  

Steps to Reproduce
meteor build <directoryWhereIsaveTheBuilds> --server=<myserverurl> --packageType=apk

**Comment by hgarcia101685** [comment]
I removed the firebase npm package and the error went away.  
Is there a known issue with meteor and the firebase package?

**Comment by denihs** [comment]
Hi, maybe this could [help](https://forums.meteor.com/t/firebase-cordova-plugin-not-working/48867/21). It's from 2019, so maybe it's not the same problem. What's the Firebase version you're running? Could you provide a repository with a reproduction?

Also, did you check the issues on their repository to see if they have something related to this?

**Comment by hgarcia101685** [comment]
At first glance it doesn't look like the same problem as the link, and that issue from the link still remains unsolved.  

    "firebase": "^9.6.1",
    "firebase-admin": "^10.0.1",
    
 I have not checked the issues in the firebase repository, but that's a good idea!

**Comment by hgarcia101685** [comment]
I am renaming this post so that its more aligned with what the root cause is as I feel like this is still a legit compatibility issue between meteor and firebase module.

**Comment by paulincai** [comment]
Hi @hgarcia101685, may I please ask what do you use Firebase for. Firebase-admin is a server-side library and, in theory, should not affect your client. So I wander what do you use Firebase for. Tx

**Comment by hgarcia101685** [comment]
I use firebase to store image files on the backend.

**Comment by hgarcia101685** [comment]
I found something out this week I'd like to share.  Will be trying these in the next couple of weeks and if I'm able to resolve, I'll update and close this ticket then.


The following does not break my app:
* installing firebase npm package
* importing firebase from isServer()

The following does break:
* importing firebase from client side(which is how my app was set up originally)

I'm going to try to move the firebase logic to server only and retry.  
The interesting thing is that the web/browser version does not complain about this, and I'm pretty sure this worked on mobile a few years ago.  Either way, if this is a good solution, and preferred design pattern, I'm fine by that.

**Comment by paulincai** [comment]
I noticed many times in our Meteor forum that people prefer the "slingshot" concept. The client uploads the file to the cloud storage without passing by the Meteor Server.

I maintain a package that uploads files to AWS S3 and the client signs an upload on the Meteor server and uses the signature to upload the file directly to S3.

If you send the file from client to the server the problem is that you load the server bandwidth twice, once to transfer from client to server and once from server to your cloud while you block Fibers. It is inefficient.

Moreover, I check the Firebase 9 APi and I see you don't need Firebase (like in the version 8). You probably need "firebase/storage" which will give you a considerably smaller kb impact on your bundle.

https://firebase.google.com/docs/storage/web/upload-files#web-version-9

**Comment by hgarcia101685** [comment]
Thanks for the advice!

**Comment by hgarcia101685** [comment]
I attempted the following and still have been unable to get this working:

- Making firebase calls from server side api using isServer()
- Moving calls to firebase-admin
- Exploring a restful API approach(this could still work but its a huge change and workaround, not really a solution)

I'm going to continue to leave this open in case anyone comes along with a solution. I'm also going to poke around the firebase repo and file a ticket there.

**Comment by nachocodoner** [comment]
Since no reproduction repository was provided and Meteor 3 has transitioned away from the legacy Cordova bundle architecture to modern webviews, this compatibility issue with Firebase v9 is likely obsolete. Closing this issue.
