### ISSUE TITLE
Error: Uncaught TypeError: Cannot destructure property 'ServiceConfiguration' of 'Package.service-configuration' as it is undefined.

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#12036]
- [x] A short, but descriptive title. The title doesn't need "Meteor" in it.
- [x] The version of Meteor showing the problem.
Meteor 2.6.1
- [x] The last version of Meteor where the problem did _not_ occur, if applicable.
Unknown
- [x] The operating system you're running Meteor on.
Ubuntu 20.04
- [ ] A **simple** reproduction! (Must include the Github repository and steps to reproduce the issue on it.)
No reproduction is available. Found the errors through montiapm.

```
Error: Uncaught TypeError: Cannot destructure property 'ServiceConfiguration' of 'Package.service-configuration' as it is undefined.

TypeError: Cannot destructure property 'ServiceConfiguration' of 'Package.service-configuration' as it is undefined.
    at ServiceConfiguration (meteor://💻app/packages/accounts-base/accounts_common.js:83:14)
    at meteor://💻app/packages/meteor.js:943:4
    at maybeReady (meteor://💻app/packages/meteor.js:955:4)
```

**Comment by denihs** [comment]
Hi @rj-david, dumb question: Is the package `service-configuration` added to your project?

**Comment by rj-david** [comment]
@denihs we are not using the package.

**Comment by denihs** [comment]
Could you add it to see if it solves it?

`meteor add service-configuration`

**Comment by rj-david** [comment]
Is that package required? We only use `accounts-base` as all our logins are customized to our needs.

No problem adding it if it is required

**Comment by denihs** [comment]
Yes, it seems like it is, as it's being [called](https://github.com/meteor/meteor/blob/13ebd25134988b0152a9e3ee8cccb36dee4cadb7/packages/accounts-base/accounts_common.js#L83) in the constructor of the AccounsBase class.

**Comment by zodern** [comment]
@rj-david if you are using a paid plan for Monti APM, when viewing the error you can check the insights tab for the error to see if there are any patterns to help with reproducing, such as if it only happens in the legacy client or a specific browser.

service-configuration is already a dependency of accounts-base, so you shouldn't need to add it: https://github.com/meteor/meteor/blob/13ebd25134988b0152a9e3ee8cccb36dee4cadb7/packages/accounts-base/package.js#L20 It is an unordered dependency, so it could load after accounts-base, but all packages should be loaded before the startup hooks are run, which is where accounts-base uses it.

I'm not very familiar with this part of Meteor to know what could cause the hook to run before the package is loaded. A couple possibilities are:
- there is another error in a package that loads inbetween accounts-base and service-configuration, which could cause packages after it to not run, though I'm not sure if startup hooks would still be run
- for some reason Meteor might run the startup hooks before all packages are loaded. Meteor uses different logic for this for some older browsers. Maybe there is a browser where it doesn't work correctly?

Does your app use a js minifier package? Do you ever deploy your app with `--debug` enabled?

**Comment by rj-david** [comment]
@zodern, I just checked the Insights tab for the error and did not find any pattern. It is all over the place, e.g. different URLs from different app sections but majority 31.14% from the homepage. On average, it happens 2 times a day.

We are using your minifier: `zodern:standard-minifier-js@4.1.1`

We never deploy with `--debug` enabled.

**Comment by rj-david** [comment]
> * for some reason Meteor might run the startup callbacks before all packages are loaded. Meteor uses different logic for this for some older browsers. Maybe there is a browser where it doesn't work correctly?

Browsers were all recent: Chrome and Edge 10x.x

**Comment by nachocodoner** [comment]
This was resolved when OAuth was decoupled from `accounts-base` (https://github.com/meteor/meteor/pull/12273). The package now properly uses defensive `if (Package['service-configuration'])` checks before destructuring.
