### ISSUE TITLE
Deploying default Meteor app not working due to incompatibility with Fibers

### ISSUE THREAD

**Issue by ajaypillay** [meteor/meteor#12056]
Hi, I'm trying to set up a production site on [Uberspace](https://uberspace.de/en/) and I've tried just deploying the default Meteor app but I can't run the built version due to Fibers.

I ran `meteor build --architecture os.linux.x86_64 ../build` and subsequently extracted the tarred file, and ran `meteor npm install` in the `build/bundle/programs/server`. However, when I tried to start the server with `node main.js` in `bundle/`, this is the error trace:

```
## There is an issue with `node-fibers` ##
`/home/ajay/build/bundle/programs/server/node_modules/fibers/bin/linux-x64-93-glibc/fibers.node` is missing.

Try running this to fix the issue: /home/ajay/.nvm/versions/node/v16.15.1/bin/node /home/ajay/build/bundle/programs/server/node_modules/fibers/build
Error: Cannot find module '/home/ajay/build/bundle/programs/server/node_modules/fibers/bin/linux-x64-93-glibc/fibers'
Require stack:
- /home/ajay/build/bundle/programs/server/node_modules/fibers/fibers.js
- /home/ajay/build/bundle/programs/server/boot.js
- /home/ajay/build/bundle/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ajay/build/bundle/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.Mp._compile (/home/ajay/build/bundle/programs/server/runtime.js:99:23)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module.Mp.load (/home/ajay/build/bundle/programs/server/runtime.js:46:33)
/home/ajay/build/bundle/programs/server/node_modules/fibers/fibers.js:23
		throw new Error('Missing binary. See message above.');
		^

Error: Missing binary. See message above.
    at Object.<anonymous> (/home/ajay/build/bundle/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.Mp._compile (/home/ajay/build/bundle/programs/server/runtime.js:99:23)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module.Mp.load (/home/ajay/build/bundle/programs/server/runtime.js:46:33)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ajay/build/bundle/programs/server/boot.js:2:15)
```
I tried the suggestion to fix the issue with `node-gyp` but that then threw an error that `gyp: binding.gyp not found (cwd: /home/ajay/build/bundle) while trying to load binding.gyp`. I'm not sure if I should be having to do this in the first place.

I understand that Fibers are broken for Node versions >= 16. I tried downgrading the Node version when doing this too but I don't think I did it correctly. Would anyone be able to suggest how to proceed?

A new user with the latest version of Node (or any version >= 16) and Meteor would not be able to successfully deploy the barebones example application made with `meteor create test-app` because of this (that was my approach)

Thanks.

EDIT: I tried doing everything from scratch again, this time in node v13.14.0 (switched using `nvm`) but I got the following error:
```
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> fibers@5.0.1 install /home/ajay/build/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-83-glibc` exists; testing
Problem with the binary; manual build incoming
/home/ajay/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin/node-gyp: line 5: /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js: No such file or directory
node-gyp exited with code: 127
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fibers@5.0.1 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@5.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ajay/.npm/_logs/2022-06-03T07_18_48_840Z-debug.log
```
When I try to install `node-gyp` the same error is thrown.

**Comment by xet7** [comment]
@ajaypillay

Newest Meteor 2.7.3 is only compatible with Node.js 14.x and MongoDB 5.x

Before uploading bundle to Uberspace you should install newest Node.js 14.x https://nodejs.org/dist/latest-v14.x/ and then:
```
sudo npm -g uninstall node-pre-gyp

sudo npm -g install @mapbox/node-pre-gyp
```
And build fibers like this:

https://github.com/wekan/wekan/blob/master/rebuild-wekan.sh#L96

Then you could start bundle with ROOT_URL etc options like this:

https://github.com/wekan/wekan/blob/master/start-wekan.sh

Also see https://github.com/wekan/wekan/issues/2009

On non-amd64 platforms, like arm64/s390x/ppc64le, fibers needs to be built on each platform similarly, see maintainer-make-bundle (a=arm64, s=s390x, o=ppc64le)  scripts at:

https://github.com/wekan/wekan/tree/master/releases

**Comment by xet7** [comment]
If converting Linux amd64 bundle to run on Windows, you may need to reinstall bcrypt:

https://github.com/wekan/wekan/wiki/Offline#b-how-to-fix-errors-on-linux-bundle-to-create-windows-bundle

**Comment by Grubba27** [comment]
Hey @ajaypillay this have worked?

**Comment by ajaypillay** [comment]
Hi @Grubba27 and @xet7 thanks for getting back to me and sorry for the late reply. I figured it out but neglected to update this post. My solution was to build the file locally, and then send the built file over to the server, unpackage it and run `npm i` on the server's end and it seems to work without any issue.

Locally, I'm on `npm: v8.1.4` and `nodejs: v16.14.0` and `meteor: 2.7.3`.

On the server, I'm on `npm: v7.7.6` and `nodejs: v15.14.0` and `meteor: 2.7.3`.

When I try this with different versions on the server (including the same version as what I have locally!), it breaks. I've not spent time troubleshooting this, but I did not have to build fibers at any point manually.

**Comment by ajaypillay** [comment]
> But Meteor is only compatible with Node.js 14.x and MongoDB 5.x, versions are listed at https://wekan.github.io Download section.
I'm not sure exactly why I had to do that, maybe it defaults to the internal Meteor node/npm versions that come along with Meteor instead of whatever is globally available.

**Comment by nachocodoner** [comment]
Fibers is inherently incompatible with Node 16 and above. Meteor 3 has completely removed Fibers in favor of native Node `async/await`, making this deployment compilation error obsolete. (Migrate to Meteor 3: https://v3-migration-docs.meteor.com/) Closing.
