### ISSUE TITLE
Error while compiling in tag <script> using lang ts Cannot read property 'data' of null

### ISSUE THREAD

**Issue by diavrank** [meteor/meteor#12052]
Hi, recently I got this error in my Meteor + Vue project, while running tests:

````shell
Run meteor npm test

> spa-cover-dealer@ test /home/runner/work/spa-cover-dealer/spa-cover-dealer
> meteor test --once --full-app --driver-package meteortesting:mocha

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
vue-component-sass: updating npm dependencies -- node-sass,
meteor-project-path...

=> [HMR] Dev server listening on port 3003.
[vue-component] Error while compiling in tag <script> using lang ts Cannot read property 'data' of null
TypeError: Cannot read property 'data' of null
    at typescriptHandler (packages/vue-component-typescript-babel/vue-typescript.js:22:22)
    at packages/meteor.js:306:21
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:91:26)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:541:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:140:12)
    at packages/vue-component/plugin/vue-compiler.js:57:34
    at /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3110:16
    at replenish (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1011:17)
    at /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1016:9
    at Object.eachLimit$1 (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3196:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:41:11)
    at __bottom_mark__ (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/utils/tools/utils/parse-stack.ts:92:14)
    at /tools/isobuild/compiler-plugin.js:212:27
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/isobuild/compiler-plugin.js:199:22
    at Function.time (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:284:12)
    at /tools/isobuild/compiler-plugin.js:198:15
    at Function.each (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:188:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1154:22)
    at /tools/isobuild/bundler.js:858:34
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:852:18)
    at /tools/isobuild/bundler.js:3262:14
    at /tools/isobuild/bundler.js:3422:25
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3376:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3243:31)
    at /tools/isobuild/bundler.js:3186:32
    at Slot.withValue (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:39)
    at Object.bundle (/tools/isobuild/bundler.js:3186:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12
[vue-component] Error while compiling in tag <script> using lang ts Cannot read property 'data' of null
TypeError: Cannot read property 'data' of null
    at typescriptHandler (packages/vue-component-typescript-babel/vue-typescript.js:22:22)
    at packages/meteor.js:306:21
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:91:26)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:541:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:140:12)
    at packages/vue-component/plugin/vue-compiler.js:57:34
    at /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3110:16
    at replenish (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1011:17)
    at /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1016:9
    at Object.eachLimit$1 (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3196:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:41:11)
    at __bottom_mark__ (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/utils/tools/utils/parse-stack.ts:92:14)
    at /tools/isobuild/compiler-plugin.js:212:27
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/isobuild/compiler-plugin.js:199:22
    at Function.time (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:284:12)
    at /tools/isobuild/compiler-plugin.js:198:15
    at Function.each (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:188:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1154:22)
    at /tools/isobuild/bundler.js:858:34
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:852:18)
    at /tools/isobuild/bundler.js:3262:14
    at /tools/isobuild/bundler.js:3422:25
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3376:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3243:31)
    at /tools/isobuild/bundler.js:3186:32
    at Slot.withValue (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:39)
    at Object.bundle (/tools/isobuild/bundler.js:3186:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12
[vue-component] Error while compiling in tag <script> using lang ts Cannot read property 'data' of null
TypeError: Cannot read property 'data' of null
    at typescriptHandler (packages/vue-component-typescript-babel/vue-typescript.js:22:22)
    at packages/meteor.js:306:21
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:91:26)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:541:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:140:12)
    at packages/vue-component/plugin/vue-compiler.js:57:34
    at /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3110:16
    at replenish (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1011:17)
    at /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1016:9
    at Object.eachLimit$1 (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3196:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:41:11)
    at __bottom_mark__ (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/utils/tools/utils/parse-stack.ts:92:14)
    at /tools/isobuild/compiler-plugin.js:212:27
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/isobuild/compiler-plugin.js:199:22
    at Function.time (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:284:12)
    at /tools/isobuild/compiler-plugin.js:198:15
    at Function.each (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:188:7)
    at ServerTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1154:22)
    at /tools/isobuild/bundler.js:858:34
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ServerTarget.make (/tools/isobuild/bundler.js:852:18)
    at /tools/isobuild/bundler.js:3287:14
    at /tools/isobuild/bundler.js:3428:24
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3243:31)
    at /tools/isobuild/bundler.js:3186:32
    at Slot.withValue (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1543:39)
    at Object.bundle (/tools/isobuild/bundler.js:3186:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/home/runner/.meteor/packages/meteor-tool/.2.7.2.f538ay.0rlfj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12
=> Started your app.

=> App running at: http://localhost:3000/
=> Build failed:
   
   While processing files with akryum:vue-component (for target web.browser):
   packages/vue-component/plugin/utils.js:200:15: TemplatingTools is not
   defined
   at throwCompileError (packages/vue-component/plugin/utils.js:200:15)
   at VueComponentTagHandler.getResults
   (packages/vue-component/plugin/tag-handler.js:104:11)
   at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
   at compileOneFileWithContents
   (packages/vue-component/plugin/vue-compiler.js:541:12)
   at VueCompo.compileOneFile
   (packages/vue-component/plugin/vue-compiler.js:140:12)
   at packages/vue-component/plugin/vue-compiler.js:57:34
   at
   /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3110:16
   at replenish
   (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1011:17)
   at
   /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1016:9
   at Object.eachLimit$1
   (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3196:24)
   at VueCompo.processFilesForTarget
   (packages/vue-component/plugin/vue-compiler.js:41:11)
   
   
   While processing files with akryum:vue-component (for target
   web.browser.legacy):
   packages/vue-component/plugin/utils.js:200:15: TemplatingTools is not
   defined
   at throwCompileError (packages/vue-component/plugin/utils.js:200:15)
   at VueComponentTagHandler.getResults
   (packages/vue-component/plugin/tag-handler.js:104:11)
   at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
   at compileOneFileWithContents
   (packages/vue-component/plugin/vue-compiler.js:541:12)
   at VueCompo.compileOneFile
   (packages/vue-component/plugin/vue-compiler.js:140:12)
   at packages/vue-component/plugin/vue-compiler.js:57:34
   at
   /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3110:16
   at replenish
   (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1011:17)
   at
   /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1016:9
   at Object.eachLimit$1
   (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3196:24)
   at VueCompo.processFilesForTarget
   (packages/vue-component/plugin/vue-compiler.js:41:11)
   
   
   While processing files with akryum:vue-component (for target
   os.linux.x86_64):
   packages/vue-component/plugin/utils.js:200:15: TemplatingTools is not
   defined
   at throwCompileError (packages/vue-component/plugin/utils.js:200:15)
   at VueComponentTagHandler.getResults
   (packages/vue-component/plugin/tag-handler.js:104:11)
   at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
   at compileOneFileWithContents
   (packages/vue-component/plugin/vue-compiler.js:541:12)
   at VueCompo.compileOneFile
   (packages/vue-component/plugin/vue-compiler.js:140:12)
   at packages/vue-component/plugin/vue-compiler.js:57:34
   at
   /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3110:16
   at replenish
   (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1011:17)
   at
   /home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1016:9
   at Object.eachLimit$1
   (/home/runner/.meteor/packages/akryum_vue-component/.0.15.2.ymxsd2.9ws9j++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3196:24)
   at VueCompo.processFilesForTarget
   (packages/vue-component/plugin/vue-compiler.js:41:11)
   
   
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
````

I found that @babel/plugin-transform-typescript was updated to **7.18.1** and this update provokes that error. The last stable version that I had was **7.16.8**.  So, I was wondering if we can support/update this [package](https://github.com/akanix42/meteor-vue-typescript-babel) to resolve this issue.

Meteor 2.7.2

**Comment by nachocodoner** [comment]
This issue is related to a legacy 3rd-party community compiler (`akryum:vue-component`). In Meteor 3, [Vue is officially supported and integrated via Rspack](https://docs.meteor.com/about/modern-build-stack/rspack-bundler-integration.html) these days (`meteor create --release 3.4.1 --vue`), rendering these legacy Isobuild compiler plugins obsolete. Closing.
