### ISSUE TITLE
Importing a non-existent file from a Meteor package throws an incorrect error

### ISSUE THREAD

**Issue by radekmie** [meteor/meteor#12164]
It looks like there's a slightly incorrect misleading message, when you import a non-existent file from a Meteor package. For example:
```ts
import 'meteor/mongo/x';
```
throws
```
~/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:280
            throw(ex);
            ^

Error: Cannot find package "mongo". Try "meteor add mongo".
    at makeInstallerOptions.fallback (packages/modules-runtime.js:611:13)
    at Module.require (packages/modules-runtime.js:244:14)
    at Module.moduleLink [as link] (~/example/.meteor/local/isopacks/modules/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:52:22)
    at module (server/main.js:1:8)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at ~/example/.meteor/local/build/programs/server/app/app.js:28:15
    at ~/example/.meteor/local/build/programs/server/boot.js:407:38
    at Array.forEach (<anonymous>)
    at ~/example/.meteor/local/build/programs/server/boot.js:232:21
    at ~/example/.meteor/local/build/programs/server/boot.js:470:7
    at Function.run (~/example/.meteor/local/build/programs/server/profile.js:280:14)
    at ~/example/.meteor/local/build/programs/server/boot.js:469:13
```

Suggesting that the `mongo` package is not installed, even though it is.

**Comment by Grubba27** [comment]
I've started working on this matter(error messages), and I have good news. https://github.com/meteor/meteor/pull/12117
when this one is merged, we will have a centralized way of adjusting and adding errors guess we just need to discuss how it should look like the error messages

**Comment by radekmie** [comment]
It's still valid.

**Comment by radekmie** [comment]
AFAIK nobody did anything around it, so yes.
