### ISSUE TITLE
@react-pdf/renderer: module.runSetters is not a function

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#12179]
Updating the npm package `@react-pdf/renderer` to version 2.1.2 and above seems to cause a Meteor-only bug that I'm having a hard time understanding. The error seems to come from this file `node_modules/normalize-svg-path/index.mjs`, but the `runSetters` function is nowhere to be found.

```sh
index.mjs:118 Uncaught TypeError: module.runSetters is not a function
    at buildCallerFunction (index.mjs:118:2)
    at Object.makeCaller (index.mjs:118:2)
    at BindClass.registerMethods (index.mjs:118:2)
    at BindClass.registerSuperMethods (index.mjs:118:2)
    at BindClass.finish (index.mjs:118:2)
    at __nbind_finish (index.mjs:118:2)
    at $A (index.mjs:118:2)
    at _A (index.mjs:118:2)
    at Object.ccallFunc [as ccall] (index.mjs:118:2)
    at Object.onRuntimeInitialized (index.mjs:118:2)
```

It's been raised here: https://github.com/diegomura/react-pdf/issues/2011

Here you can find a reproduction: https://github.com/Floriferous/react-pdf-meteor-error

**Comment by paulincai** [comment]
Hei @Floriferous, I answered to you on their repo. Could you please try to remove from your local node_modules, from this package, the dependency on " rollup-plugin-polyfill-node" and see if anything changes. Also check this and see if anything from the package is imported anywhere. Will have to do this in a /dist or /lib folder in the package (the compiled version, not the src folder with vanilla js). Then restart Meteor and see if the issue persist. This is the only think I can think of that might conflict with Meteor's build system.

**Comment by StorytellerCZ** [comment]
You can also try recompiling the package: https://guide.meteor.com/using-npm-packages.html#recompile
