### ISSUE TITLE
"MongoError: no primary found in replicaset" when trying to connect to IBM cloud database after migration from Compose.io

### ISSUE THREAD

**Issue by nsiegmundtol** [meteor/meteor#12224]
I have read through all the solutions on this issue and none have seemed to help: [https://github.com/meteor/meteor/issues/7450](https://github.com/meteor/meteor/issues/7450)

I have successfully gotten our .Net applications to connect to our new ibm hosted mongo DB, but am getting an error whenever i try with meteor locally or through our galaxy server:

```

2022-10-14 11:00:53-04:00 MongoError: no primary found in replicaset
2022-10-14 11:00:53-04:00  at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
2022-10-14 11:00:53-04:00  at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
2022-10-14 11:00:53-04:00  at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
2022-10-14 11:00:53-04:00  at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
2022-10-14 11:00:53-04:00  at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
2022-10-14 11:00:53-04:00  at new Mongo.Collection (packages/mongo/collection.js:99:40)
2022-10-14 11:00:53-04:00  at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
2022-10-14 11:00:53-04:00  at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
2022-10-14 11:00:53-04:00  at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
2022-10-14 11:00:53-04:00  at fileEvaluate (packages/modules-runtime.js:197:9)
```

Here is the current way i am calling my connection string with a "npm run win-start" command defined in our package.json:

```
"win-start": "mongodb://admin:[PASSWORD]@url1.databases.appdomain.cloud:31928,url2.databases.appdomain.cloud:31928,url3.databases.appdomain.cloud:31928/dyo?authSource=admin^&tls=true^&tlsInsecure=true^&connect=replicaSet^&replicaSet=replset && meteor --settings settings.json"
```
(notice the ^&, thats the only way i could escape the ampersands and get the command to not error out. maybe that's part of the problem)

even trying to connect to our old compose server locally throws this same error. Any help is appreciated

- MongoDB Version: 4.4
- Meteor Version: 1.4.4.1

**Comment by radekmie** [comment]
Meteor 1.4.4.1 uses MongoDB driver 2.2.24 (it was updated in [1.4.3.2](https://github.com/meteor/meteor/blob/devel/docs/history.md#v1432-2017-03-14)), and the latest MongoDB version it supports is [3.4](https://www.mongodb.com/docs/drivers/node/current/compatibility/). You'd have to update to at least Meteor [1.11](https://github.com/meteor/meteor/blob/devel/docs/history.md#v111-2020-08-18) (driver 3.6).

**Comment by radekmie** [comment]
Well, MongoDB is rather safe to use with an unsupported version in most cases, and the table I linked shows "full compatibility", i.e., it _may_ work, but some features may be unavailable (because the driver doesn't understand them or the database no longer supports them).

Now, being realistic, these versions are _really_ old, and nobody will ever touch it, so if it works, it most likely will ~indefinitely~ for a _long_ time. I think it's fine as long as you test it thoroughly.

**Comment by nachocodoner** [comment]
Meteor 1.4.4.1 uses an obsolete MongoDB Node.js driver that cannot connect to modern MongoDB 4.4 replica sets. Meteor 3 upgrades the MongoDB driver to v6, which fully supports modern connection strings and topologies. Closing as obsolete.
