### ISSUE TITLE
RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by kakadais** [meteor/meteor#12305]
I think this is caused by WebSocket connection with the specific client as I googled.
But I can't figure this out exactly so ask it here.

Ubuntu 20.04 LTS
CPU/MEM: stable
Running single application on the server and no other activity.
Reproduce: None. Just once happened. Looks like occuring by some client or specific environment.

Log:

RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (/root/.meteor/packages/meteor-tool/.2.2.0.1doxl9d.80sj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/receiver.js:170:14)
    at Receiver.startLoop (/root/.meteor/packages/meteor-tool/.2.2.0.1doxl9d.80sj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/receiver.js:130:22)
    at Receiver._write (/root/.meteor/packages/meteor-tool/.2.2.0.1doxl9d.80sj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at Socket.socketOnData (/root/.meteor/packages/meteor-tool/.2.2.0.1doxl9d.80sj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/root/.meteor/packages/meteor-tool/.2.2.0.1doxl9d.80sj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/websocket.js:780:13)
    at Receiver.emit (events.js:314:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at Receiver.startLoop (/root/.meteor/packages/meteor-tool/.2.2.0.1doxl9d.80sj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/receiver.js:151:5)
    at Receiver._write (/root/.meteor/packages/meteor-tool/.2.2.0.1doxl9d.80sj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/receiver.js:77:10)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  [Symbol(status-code)]: 1002
}

**Comment by Grubba27** [comment]
It looks like an issue with Meteor v2.2, and since it has not had any movement in this issue(other reports or reproduction) I think it is okay to close this one for now.
If this still happens, please report and I will happily open this issue again.

**Comment by Oyshoboy** [comment]
I have this error happening to me randomly when loading page or changing the page on client:

```
events.js:377
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (/home/boss/.meteor/packages/meteor-tool/.2.12.0.1i4q5j8.kxpuj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/receiver.js:171:14)
    at Receiver.startLoop (/home/boss/.meteor/packages/meteor-tool/.2.12.0.1i4q5j8.kxpuj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/home/boss/.meteor/packages/meteor-tool/.2.12.0.1i4q5j8.kxpuj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/home/boss/.meteor/packages/meteor-tool/.2.12.0.1i4q5j8.kxpuj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/websocket.js:910:35)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/home/boss/.meteor/packages/meteor-tool/.2.12.0.1i4q5j8.kxpuj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/ws/lib/websocket.js:815:13)
    at Receiver.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
```
