### ISSUE TITLE
During installing meteor globally I've got "Error: Cannot find module 'https-proxy-agent'"

### ISSUE THREAD

**Issue by unsigned6** [meteor/meteor#12307]
I was installing globally latest meteor version and received missing `'https-proxy-agent'` error (using nodejs v14.19.3 npm v6.14.17). Previously it was working and started to fail in our github actions yesterday. Maybe something broken with packages list in latest version?

```npm install -g meteor                                                                                                                                                                    13:15:48
/Users/yuriivlasiuk/.nvm/versions/node/v14.19.3/bin/meteor-installer -> /Users/yuriivlasiuk/.nvm/versions/node/v14.19.3/lib/node_modules/meteor/cli.js

> meteor@2.8.1 install /Users/yuriivlasiuk/.nvm/versions/node/v14.19.3/lib/node_modules/meteor
> node cli.js install

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'https-proxy-agent'
Require stack:
- /Users/yuriivlasiuk/.nvm/versions/node/v14.19.3/lib/node_modules/meteor/install.js
- /Users/yuriivlasiuk/.nvm/versions/node/v14.19.3/lib/node_modules/meteor/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/yuriivlasiuk/.nvm/versions/node/v14.19.3/lib/node_modules/meteor/install.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/yuriivlasiuk/.nvm/versions/node/v14.19.3/lib/node_modules/meteor/install.js',
    '/Users/yuriivlasiuk/.nvm/versions/node/v14.19.3/lib/node_modules/meteor/cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor@2.8.1 install: `node cli.js install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor@2.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yuriivlasiuk/.npm/_logs/2022-11-18T11_17_14_738Z-debug.log```

**Comment by afrokick** [comment]
As a workaround you can manually install a missing module `npm i -g https-proxy-agent` before installing meteor

**Comment by afrokick** [comment]
Seems like a bug https://github.com/meteor/meteor/pull/12149#discussion_r1026295031

**Comment by denihs** [comment]
Hi, thanks for reporting this. It should be all good now!
