### ISSUE TITLE
Support ES modules new features

### ISSUE THREAD

**Issue by alextaaa** [meteor/meteor#12324]
I try use a new ES module but catch the error

```
SyntaxError: Cannot use 'import.meta' outside a module
W20221129-01:33:22.402(3)? (STDERR)     at new Script (vm.js:102:7)
W20221129-01:33:22.402(3)? (STDERR)     at createScript (vm.js:262:10)
W20221129-01:33:22.402(3)? (STDERR)     at Object.runInThisContext (vm.js:310:10)
```

**Comment by afrokick** [comment]
Try to recompile module

package.json:
```json
 "meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "nodeModules": {
      "recompile": {
        "your-esm-module": true
      }
    }
  }
```

More info: https://github.com/meteor/meteor/blob/4442d0e0bf66d890c9dc1bf04f371cfcb82519d7/guide/source/using-npm-packages.md#recompiling-npm-packages

**Comment by alextaaa** [comment]
Thx, but I try to use external modern npm module and catch the error in the module

```
meteor npm i modern_module
```

It's not work for me
Same problem

```
W20221129-11:00:25.589(3)? (STDERR) /Users/devpro/app/my_project/.meteor/local/build/programs/server/packages/modules.js:531

SyntaxError: Cannot use 'import.meta' outside a module
W20221129-01:33:22.402(3)? (STDERR)     at new Script (vm.js:102:7)
W20221129-01:33:22.402(3)? (STDERR)     at createScript (vm.js:262:10)
W20221129-01:33:22.402(3)? (STDERR)     at Object.runInThisContext (vm.js:310:10)
```

**Comment by zodern** [comment]
I changed the issue name to make it more clear. Meteor has never supported `import.meta`, and is something we should add.

**Comment by alextaaa** [comment]
ok cool

Could you add the thing to the next release 2.9 ?

**Comment by ra2ge** [comment]
I have the same problem with a module that uses `import.meta`. I cannot use the new version of the module because of this. It would be great to have support for `import.meta` in future releases. Thanks.

**Comment by juanpmd** [comment]
I have the same issue with import.meta. Im trying to use `@pdfslick/react` but it is not currently possible with Meteor (tried the `meteor.nodeModules.recompile` also).

**Comment by MaxTwentythree** [comment]
This is still relevant

**Comment by colynb** [comment]
Can't even use React Router.  If anyone knows of any workarounds until this gets resolved, that would be helpful. As is, I have to tell my clients we can't use Meteor.

**Comment by nachocodoner** [comment]
@colynb: There’s a detailed workaround for using React Router 7+ in this issue comment: https://github.com/meteor/meteor/issues/13504#issuecomment-2521276664

You can also avoid the problem by sticking with React Router 6 or earlier, since those versions are supported, but the newer workaround works too.

For an official fix, one option is adding the contribution of package.json export fields to Meteor’s core (see [PR #13520](https://github.com/meteor/meteor/pull/13520)) and we’ll support its inclusion once the implementation is ready. At the same time, we’re building a permanent solution [via the Meteor-Rspack integration](https://forums.meteor.com/t/meteor-rspack-integration-a-modern-bundler-meets-meteor-3-4/63696?u=nachocodoner). As part of the Meteor Core team efforts, we're actively working on this and a beta of the new bundler setup will be available for testing before full support in next Meteor 3.4.

**Comment by nachocodoner** [comment]
Meteor 3.4 is already released. [With Rspack support](https://docs.meteor.com/about/modern-build-stack/rspack-bundler-integration.html), it gives compatibility when using React Router v7, and other ESM-only packages or packages that require a modern bundler.

I am marking this issue as `legacy-build-stack` to track issues still present in the Meteor bundler. Since Rspack is the default for new apps and recommended for modern setups, we redirect users there. We still accept contributions to the Meteor bundler, and this issue will stay open with the tag until it is fixed or fully deprecated in favor of the [modern build stack](https://docs.meteor.com/about/modern-build-stack.html).

**Comment by MaxTwentythree** [comment]
I can confirm: with Meteor 3.4 and Rspack, React-Router V7 works now without workarounds 🥳
