### ISSUE TITLE
Failed dynamic imports cause corrupt state for clients

### ISSUE THREAD

**Issue by arggh** [meteor/meteor#12390]
Our app seems to have clients stuck in a bad state, caused by failed dynamic imports due to bad configuration.

The dynamic import errors were caused by the app being served from multiple different subdomains, but all trying to use a single domain for dynamic imports (thus not sending sticky session cookies), until we found _the undocumented_  setting `dynamic-import.useLocationOrigin`.

More about the issue here #12041.

_TL;DR_

During rolling deployments, a client could get version X of the app from the server, but subsequent dynamic import requests could be directed to another server, causing the client to either get the wrong code or fail to import entirely.

This seems to cause a persistent bad state in the IndexedDB storage that is housing the dynamically imported modules.

From there on, the client seems to be trying to import modules/code that does not exist on servers, and doesn't get past that error.

Even though this originated from a misconfiguration, I consider this a bug more than a feature request. I'd expect dynamic imports to handle any errors scenarios gracefully, potentially resorting to clearing the IndexedDB storage if required.

The only fix available to use currently seems to be clearing the IndexedDB storage from our users' browsers, but that's obviously not an _actual solution_.

**Comment by Grubba27** [comment]
Hello, there @arggh. Good to see you here!

I will tag this one as docs, and I understood what you mentioned about having a bad state. In that case, I would ask for a repo or code sample so that it has all it needs when someone tries to solve this issue. 

For those who come to solve this one, here is the [package](https://github.com/meteor/meteor/blob/36d9bc12bb897a1e30423a68d4dca4e0c5b0cf32/packages/dynamic-import/cache.js) that needs some attention.

IMO, this looks like a feature because the implementation of this may solve this matter, but it may change some of its behavior.

For the docs part, do you mean that we should have ``disableLocationOriginIframe`` and ``useLocationOrigin`` documented?

**Comment by arggh** [comment]
I'm unable to provide a repo, since I don't fully understand the steps needed to reproduce the issue even on our own infrastructure. A repo with reproduction of the problem would also require setting up some infrastructure with multiple servers, deployment scripts etc.

However, I'd like to add, that these error messages appear also when the originally mentioned configuration error in #12041  is taken care of.

So, something seems to be broken regarding the dynamic import feature & (my guess) rolling deployments. I don't fully understand the issue myself, I'm merely reporting that

**a)** our logs indicate that after a deployment, lots of clients are trying to import code that doesn't exist
**b)** I've managed to get a client into this "bad state" once myself and noticed that there's no way out of that state, except by clearing browser storage.

This seems like a problem worth inverstigating by someone who understands how the `dynamic-import` package works, and the fix would make sense in any case: _if dynamic import fails to fetch code it thinks should exist, maybe the manifest is corrupted/broken/bad? → reset!_

**Comment by arggh** [comment]
Today I also managed to cause this locally during development using an iPhone connected to my dev instance:

```
W20230323-12:48:05.898(2)? (STDERR) Error: ENOENT: no such file or directory, open '/Users/arggh/Develop/app/@next/.meteor/local/build/programs/web.browser/dynamic/node_modules/meteor/arggh_dates/node_modules/date-fns/esm/_lib/getUTCDayOfYear/index.js'
W20230323-12:48:05.898(2)? (STDERR)     at Object.openSync (fs.js:497:3)
W20230323-12:48:05.898(2)? (STDERR)     at readFileSync (fs.js:393:35)
W20230323-12:48:05.898(2)? (STDERR)     at read (packages/dynamic-import.js:209:29)
W20230323-12:48:05.898(2)? (STDERR)     at walk (packages/dynamic-import.js:160:14)
W20230323-12:48:05.898(2)? (STDERR)     at packages/dynamic-import.js:167:22
W20230323-12:48:05.898(2)? (STDERR)     at Array.forEach (<anonymous>)
W20230323-12:48:05.898(2)? (STDERR)     at walk (packages/dynamic-import.js:165:23)
W20230323-12:48:05.898(2)? (STDERR)     at packages/dynamic-import.js:167:22
W20230323-12:48:05.898(2)? (STDERR)     at Array.forEach (<anonymous>)
W20230323-12:48:05.898(2)? (STDERR)     at walk (packages/dynamic-import.js:165:23)
W20230323-12:48:05.898(2)? (STDERR)     at packages/dynamic-import.js:167:22
W20230323-12:48:05.898(2)? (STDERR)     at Array.forEach (<anonymous>)
W20230323-12:48:05.898(2)? (STDERR)     at walk (packages/dynamic-import.js:165:23)
W20230323-12:48:05.898(2)? (STDERR)     at packages/dynamic-import.js:167:22
W20230323-12:48:05.898(2)? (STDERR)     at Array.forEach (<anonymous>)
W20230323-12:48:05.898(2)? (STDERR)     at walk (packages/dynamic-import.js:165:23)
W20230323-12:48:05.898(2)? (STDERR)     at packages/dynamic-import.js:167:22
W20230323-12:48:05.898(2)? (STDERR)     at Array.forEach (<anonymous>)
W20230323-12:48:05.898(2)? (STDERR)     at walk (packages/dynamic-import.js:165:23)
W20230323-12:48:05.898(2)? (STDERR)     at packages/dynamic-import.js:167:22
W20230323-12:48:05.898(2)? (STDERR)     at Array.forEach (<anonymous>)
W20230323-12:48:05.898(2)? (STDERR)     at walk (packages/dynamic-import.js:165:23)
```

...hundreds of error messages like this when I made a code change and the server tried to reload clients.

Seems completely random when it happens and when it doesn't. I wouldn't say this issue is a "feature", more like a bug.
