### ISSUE TITLE
Some npm modules missing in built bundle

### ISSUE THREAD

**Issue by dovydaskukalis** [meteor/meteor#12397]
Meteor version: 2.9.0, tested on Mac and Ubuntu

Installing `@sentry/react` module works just fine except in the generated bundle where it seems to be missing some of it's dependencies. I am not sure if the issue is with Meteor or the Sentry module, maybe someone with more knowledge about it could help here. Simple steps to reproduce:

1. `meteor create --bare`
2. `meteor npm i @sentry/react` (current version 7.28.0)
3. `node_modules/@sentry/replay/cjs/node_modules` folder will have `lodash.debounce` and  `rrweb` folders.
4. `meteor build ./sentry-test`
5. Extracted archive's `bundle/programs/server/npm/node_modules/@sentry/replay/cjs/node_modules` will be an empty folder with `lodash.debounce` and `rrweb` modules missing which crashes the module.

Expected behavior: `lodash.debounce` and `rrweb` should be in `bundle/programs/server/npm/node_modules/@sentry/replay/cjs/node_modules`.

**Comment by johnwils** [comment]
I experienced a failed galaxy deployment due to this issue. Using Meteor 2.9.0 and @sentry/react 7.28.1

<details>
  <summary>Galaxy Error Logs</summary>
  
```
2023-01-03 20:48:58-08:00/app/bundle/programs/server/node_modules/fibers/future.js:28038qxs
2023-01-03 20:48:58-08:00 throw(ex);38qxs
2023-01-03 20:48:58-08:00 ^38qxs
2023-01-03 20:48:58-08:0038qxs
2023-01-03 20:48:58-08:00Error: Cannot find module './node_modules/rrweb/es/rrweb/packages/rrweb/src/entries/all.js'38qxs
2023-01-03 20:48:58-08:00Require stack:38qxs
2023-01-03 20:48:58-08:00- /app/bundle/programs/server/npm/node_modules/@sentry/replay/cjs/replay.js38qxs
2023-01-03 20:48:58-08:00- /app/bundle/programs/server/npm/node_modules/@sentry/replay/cjs/integration.js38qxs
2023-01-03 20:48:58-08:00- /app/bundle/programs/server/npm/node_modules/@sentry/replay/cjs/index.js38qxs
2023-01-03 20:48:58-08:00- /app/bundle/programs/server/npm/node_modules/@sentry/browser/cjs/index.js38qxs
2023-01-03 20:48:58-08:00- /app/bundle/programs/server/npm/node_modules/@sentry/react/cjs/index.js38qxs
2023-01-03 20:48:58-08:00- /app/bundle/programs/server/npm-require.js38qxs
2023-01-03 20:48:58-08:00- /app/bundle/programs/server/boot.js38qxs
2023-01-03 20:48:58-08:00- /app/bundle/main.js38qxs
2023-01-03 20:48:58-08:00 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)38qxs
2023-01-03 20:48:58-08:00 at Function.Module._load (internal/modules/cjs/loader.js:746:27)38qxs
2023-01-03 20:48:58-08:00 at Module.require (internal/modules/cjs/loader.js:974:19)38qxs
2023-01-03 20:48:58-08:00 at require (internal/modules/cjs/helpers.js:101:18)38qxs
2023-01-03 20:48:58-08:00 at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/@sentry/replay/cjs/replay.js:10:1)38qxs
2023-01-03 20:48:58-08:00 at Module._compile (internal/modules/cjs/loader.js:1085:14)38qxs
2023-01-03 20:48:58-08:00 at Module.Mp._compile (/app/bundle/programs/server/runtime.js:77:23)38qxs
2023-01-03 20:48:58-08:00 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)38qxs
2023-01-03 20:48:58-08:00 at Module.load (internal/modules/cjs/loader.js:950:32)38qxs
2023-01-03 20:48:58-08:00 at Module.Mp.load (/app/bundle/programs/server/runtime.js:37:33)38qxs
2023-01-03 20:48:58-08:00 at Function.Module._load (internal/modules/cjs/loader.js:790:12)38qxs
2023-01-03 20:48:58-08:00 at Module.require (internal/modules/cjs/loader.js:974:19)38qxs
2023-01-03 20:48:58-08:00 at require (internal/modules/cjs/helpers.js:101:18)38qxs
2023-01-03 20:48:58-08:00 at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/@sentry/replay/cjs/integration.js:5:16)38qxs
2023-01-03 20:48:58-08:00 at Module._compile (internal/modules/cjs/loader.js:1085:14)38qxs
2023-01-03 20:48:58-08:00 at Module.Mp._compile (/app/bundle/programs/server/runtime.js:77:23) {38qxs
2023-01-03 20:48:58-08:00 code: 'MODULE_NOT_FOUND',38qxs
2023-01-03 20:48:58-08:00 requireStack: [38qxs
2023-01-03 20:48:58-08:00 '/app/bundle/programs/server/npm/node_modules/@sentry/replay/cjs/replay.js',38qxs
2023-01-03 20:48:58-08:00 '/app/bundle/programs/server/npm/node_modules/@sentry/replay/cjs/integration.js',38qxs
2023-01-03 20:48:58-08:00 '/app/bundle/programs/server/npm/node_modules/@sentry/replay/cjs/index.js',38qxs
2023-01-03 20:48:58-08:00 '/app/bundle/programs/server/npm/node_modules/@sentry/browser/cjs/index.js',38qxs
2023-01-03 20:48:58-08:00 '/app/bundle/programs/server/npm/node_modules/@sentry/react/cjs/index.js',38qxs
2023-01-03 20:48:58-08:00 '/app/bundle/programs/server/npm-require.js',38qxs
2023-01-03 20:48:58-08:00 '/app/bundle/programs/server/boot.js',38qxs
2023-01-03 20:48:58-08:00 '/app/bundle/main.js'38qxs
2023-01-03 20:48:58-08:00 ]38qxs
2023-01-03 20:48:58-08:00}38qxs
2023-01-03 20:48:59-08:00Application exited with code: 1
```
</details>


No issue using Meteor 2.9.0 and @sentry/react 7.26.0

Sentry has a few open [issues](https://github.com/getsentry/sentry-javascript/issues?q=is%3Aissue+is%3Aopen+rrweb) related to rrweb.

**Comment by dovydaskukalis** [comment]
Seems fine with the latest module version. Guess it was issue on their end.
