### ISSUE TITLE
Unable to build production bundle using standard-minifier-css and Bootstrap 5.3.0-alpha1

### ISSUE THREAD

**Issue by wreiske** [meteor/meteor#12561]
Version: Meteor 2.11.0
OS: MacOS, Windows, and Linux Debian GitHub Action Builds

Example reproduction: https://github.com/wreiske/break-css-bundle

```
git clone https://github.com/wreiske/break-css-bundle.git
cd break-css-bundle
meteor npm install
meteor build ~/build/example-master --directory --server=https://example.com --allow-superuser --architecture os.linux.x86_64 --server-only --verbose
```

<img width="1840" alt="Screenshot 2023-03-14 at 3 31 41 PM" src="https://user-images.githubusercontent.com/6295044/225156783-2ac077b6-1072-4ef0-b132-7600f3ef70d5.png">

```
Errors prevented bundling:                    inifying                                              
While minifying app stylesheet:               
<input css 6FRlW2>:1470:3: Lexical error on line 1: Unrecognized text.

Erroneous area:
1: $table-border-width * 2
^..^
at <input css 6FRlW2>:1470:3
at Object.parseError
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1200:15)
at Object.lexer_parseError
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:2333:44)
at Object.lexer_next
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:3328:22)
at Object.lexer_fastLex
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:3403:18)
at fastLex
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1603:27)
at Parser.parse
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1677:30)
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:33:30
at walk
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-value-parser/lib/walk.js:7:16)
at ValueParser.walk
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-value-parser/lib/index.js:18:3)
at transformValue
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:24:50)
at _default
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:66:100)
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/index.js:27:32
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:55:18
at Rule.each
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:41:16)
at Rule.walk
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:52:17)
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:60:24
at Root.each
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:41:16)
at Root.walk
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:52:17)
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/index.js:23:9
at initializePlugin
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/cssnano/dist/index.js:31:51)
at
/Users/wreiske/.meteor/packages/meteor-tool/.2.11.0.261xw9.jfyws++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40


While minifying app stylesheet:
<input css i0N1Nr>:1470:3: Lexical error on line 1: Unrecognized text.

Erroneous area:
1: $table-border-width * 2
^..^
at <input css i0N1Nr>:1470:3
at Object.parseError
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1200:15)
at Object.lexer_parseError
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:2333:44)
at Object.lexer_next
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:3328:22)
at Object.lexer_fastLex
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:3403:18)
at fastLex
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1603:27)
at Parser.parse
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/parser.js:1677:30)
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:33:30
at walk
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-value-parser/lib/walk.js:7:16)
at ValueParser.walk
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-value-parser/lib/index.js:18:3)
at transformValue
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:24:50)
at _default
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/lib/transform.js:66:100)
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/index.js:27:32
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:55:18
at Rule.each
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:41:16)
at Rule.walk
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:52:17)
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:60:24
at Root.each
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:41:16)
at Root.walk
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss/lib/container.js:52:17)
at
/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/postcss-calc/dist/index.js:23:9
at initializePlugin
(/Users/wreiske/.meteor/packages/standard-minifier-css/.1.9.0.pbh8ht.2mkv++os+web.browser+web.browser.legacy+web.cordova/plugin.minifyStdCSS.os/npm/node_modules/meteor/minifier-css/node_modules/cssnano/dist/index.js:31:51)
at
/Users/wreiske/.meteor/packages/meteor-tool/.2.11.0.261xw9.jfyws++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
```

It seems the following breaks it:
```css
.table-group-divider {
  border-top: calc($table-border-width * 2) solid $table-group-separator-color; // stylelint-disable-line function-disallowed-list
}
```

https://github.com/twbs/bootstrap/blob/474bf2aed1c03cf53e2d2c48b30c5e689dd9e6bc/scss/_tables.scss#L45

**Comment by wreiske** [comment]
I get a different error when using the devel build https://github.com/meteor/meteor/tree/devel/packages/standard-minifier-css

```
inifyStdCSS: updating npm dependencies -- @babel/runtime, source-map, lru-cache, micromatch...
Errors prevented bundling:                    inifying                                              
While minifying app stylesheet:               
<input css NYyU9H>:1737:3: Lexical error on line 1: Unrecognized text.

Erroneous area:
1: 1.5em + 0.5rem + calc($input-border-width * 2)
^........................^
at <input css NYyU9H>:1737:3
at Object.parseError (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:1200:15)
at Object.lexer_parseError (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:2333:44)
at Object.lexer_next (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:3328:22)
at Object.lexer_fastLex (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:3403:18)
at fastLex (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:1603:27)
at Parser.parse (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:1677:30)
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/lib/transform.js:33:30
at walk (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-value-parser/lib/walk.js:7:16)
at ValueParser.walk (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-value-parser/lib/index.js:18:3)
at transformValue (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/lib/transform.js:24:50)
at _default (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/lib/transform.js:66:100)
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/index.js:27:32
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:55:18
at Rule.each (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:41:16)
at Rule.walk (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:52:17)
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:60:24
at Root.each (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:41:16)
at Root.walk (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:52:17)
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/index.js:23:9
at initializePlugin (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/cssnano/dist/index.js:31:51)
at
/Users/wreiske/.meteor/packages/meteor-tool/.2.11.0.261xw9.jfyws++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40


While minifying app stylesheet:
<input css TwgC48>:1737:3: Lexical error on line 1: Unrecognized text.

Erroneous area:
1: 1.5em + 0.5rem + calc($input-border-width * 2)
^........................^
at <input css TwgC48>:1737:3
at Object.parseError (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:1200:15)
at Object.lexer_parseError (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:2333:44)
at Object.lexer_next (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:3328:22)
at Object.lexer_fastLex (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:3403:18)
at fastLex (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:1603:27)
at Parser.parse (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/parser.js:1677:30)
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/lib/transform.js:33:30
at walk (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-value-parser/lib/walk.js:7:16)
at ValueParser.walk (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-value-parser/lib/index.js:18:3)
at transformValue (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/lib/transform.js:24:50)
at _default (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/lib/transform.js:66:100)
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/index.js:27:32
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:55:18
at Rule.each (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:41:16)
at Rule.walk (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:52:17)
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:60:24
at Root.each (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:41:16)
at Root.walk (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss/lib/container.js:52:17)
at /Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/postcss-calc/dist/index.js:23:9
at initializePlugin (/Users/wreiske/.meteor/packages/minifier-css/.1.6.2.3wicv2.7qjj6++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/cssnano/dist/index.js:31:51)
at
/Users/wreiske/.meteor/packages/meteor-tool/.2.11.0.261xw9.jfyws++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by wreiske** [comment]
Looks like bumping the NPM versions fixed this build issue for me! I submitted a PR here: https://github.com/meteor/meteor/pull/12562
