### ISSUE TITLE
Error: Could not get https://warehouse.meteor.com [2.11.0]

### ISSUE THREAD

**Issue by diavrank** [meteor/meteor#12576]
Hi, I have an app with Meteor 2.7.2 and I added recently some modifications in the FE, so, when I wanted to do a new build, I got this error:

````shell
Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

/root/.meteor/packages/meteor-tool/.2.11.0.1n3mjr4.uxyr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Could not get https://warehouse.meteor.com/builds/EXSxwGqYjjJKh3WMJ/1568919164171/sR49rp9yRF/coffeescript-2.4.1-os+web.browser+web.browser.legacy+web.cordova.tgz; server returned [522]
    at Object.getUrlWithResuming (/tools/utils/http-helpers.js:502:13)
    at /tools/packaging/tropohouse.js:480:34
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:467:47
    at Function.each (/root/.meteor/packages/meteor-tool/.2.11.0.1n3mjr4.uxyr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at /tools/packaging/tropohouse.js:466:11
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:424:20)
    at /tools/packaging/tropohouse.js:610:18
    at /tools/utils/buildmessage.js:609:21
    at /root/.meteor/packages/meteor-tool/.2.11.0.1n3mjr4.uxyr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/root/.meteor/packages/meteor-tool/.2.11.0.1n3mjr4.uxyr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Object.forkJoin (/tools/utils/buildmessage.js:641:6)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:606:18)
    at /tools/project-context.js:921:25
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/project-context.js:920:20
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:919:13)
    at /tools/project-context.js:365:35
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:355:18)
    at /tools/project-context.js:347:12
    at Function.run (/root/.meteor/packages/meteor-tool/.2.11.0.1n3mjr4.uxyr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:346:13)
    at /tools/cli/commands.js:1050:20
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.main.captureAndExit (/tools/cli/main.js:281:29)
    at buildCommand (/tools/cli/commands.js:1047:8)
    at /tools/cli/commands.js:988:25
    at Function.run (/root/.meteor/packages/meteor-tool/.2.11.0.1n3mjr4.uxyr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at /tools/cli/commands.js:986:18
    at /root/.meteor/packages/meteor-tool/.2.11.0.1n3mjr4.uxyr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/root/.meteor/packages/meteor-tool/.2.11.0.1n3mjr4.uxyr++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at /tools/cli/main.js:1535:7
ERROR: Service 'app' failed to build: The command '/bin/sh -c bash $SCRIPTS_FOLDER/build-meteor-bundle.sh' returned a non-zero code: 1
````

When I do the build in local machine (I use Macbook Pro M1 Pro), it is built correctly but if I do the build with disney docker image, it fails. Maybe it's the docker image, but I think that it could be also the O.S, since the docker image uses a Linux, so, maybe with Linux is failing as well.

**Comment by mitar** [comment]
This looks like something temporary (522 http error code). Have you tried again at a later time?
