### ISSUE TITLE
Version 2.12.0 results in a 403 error when installing in Docker container

### ISSUE THREAD

**Issue by thomastab** [meteor/meteor#12609]
Installing Meteor@2.12.0 in a container results in a 403 error crashing the installation script:
```
 > [2/2] RUN npm install -g meteor@2.12.0 --unsafe-perm:                                                                                          
#5 4.988 /usr/local/bin/meteor-installer -> /usr/local/lib/node_modules/meteor/cli.js                                                             
#5 4.996                                                                                                                                          
#5 4.996 > meteor@2.12.0 install /usr/local/lib/node_modules/meteor                                                                               
#5 4.996 > node cli.js install                                                                                                                    
#5 4.996 
#5 5.388 You are running the install script as root, without SUDO. This is not recommended and should be avoided. Continuing.
#5 6.543 events.js:377
#5 6.543       throw er; // Unhandled 'error' event
#5 6.543       ^
#5 6.543 
#5 6.543 Error: Response status was 403
#5 6.543     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/meteor/node_modules/node-downloader-helper/dist/index.js:1:7055)
#5 6.543     at Object.onceWrapper (events.js:520:26)
#5 6.543     at ClientRequest.emit (events.js:400:28)
#5 6.543     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
#5 6.543     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
#5 6.543     at TLSSocket.socketOnData (_http_client.js:515:22)
#5 6.543     at TLSSocket.emit (events.js:400:28)
#5 6.543     at addChunk (internal/streams/readable.js:293:12)
#5 6.543     at readableAddChunk (internal/streams/readable.js:267:9)
#5 6.543     at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
#5 6.543 Emitted 'error' event on b instance at:
#5 6.543     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/meteor/node_modules/node-downloader-helper/dist/index.js:1:7186)
#5 6.543     at Object.onceWrapper (events.js:520:26)
#5 6.543     [... lines matching original stack trace ...]
#5 6.543     at TLSSocket.Readable.push (internal/streams/readable.js:206:10) {
#5 6.543   status: 403,
#5 6.543   body: ''
#5 6.543 }
#5 6.657 npm ERR! code ELIFECYCLE
#5 6.657 npm ERR! errno 1
#5 6.662 npm ERR! meteor@2.12.0 install: `node cli.js install`
#5 6.662 npm ERR! Exit status 1
#5 6.662 npm ERR! 
#5 6.662 npm ERR! Failed at the meteor@2.12.0 install script.
#5 6.662 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#5 6.667 
#5 6.667 npm ERR! A complete log of this run can be found in:
#5 6.667 npm ERR!     /root/.npm/_logs/2023-05-03T08_13_32_510Z-debug.log
------
executor failed running [/bin/sh -c npm install -g meteor@2.12.0 --unsafe-perm]: exit code: 1
```

When using Meteor@2.11.0 the issue does not occur.
Meteor is running in a Debian 10 slim container and this container is built on a Mac M1 processor using Rosetta to emulate an amd64 arch if this is relevant.

Here is a simple Dockerfile reproducing this issue:

```
FROM node:14.21.3-slim
ENV METEOR_ALLOW_SUPERUSER=true
RUN npm install -g meteor@2.12.0 --unsafe-perm
```

You only need to save it and run `docker build --platform linux/amd64 .` to reproduce the error

**Comment by Grubba27** [comment]
We have made a new release. This is probably solved!
Can you try again?

**Comment by thomastab** [comment]
The installer seems to be working again with the new release, thanks for the quick fix !
