### ISSUE TITLE
bson@5.2.0 does not work - await is not defined at module node_byte_utils.ts

### ISSUE THREAD

**Issue by gustawdaniel** [meteor/meteor#12615]
I installed newest Meteor `METEOR@2.12` and newest `bson@5.2.0` and i seen error:

```
Uncaught ReferenceError: await is not defined
    at module (node_byte_utils.ts:49:1)
```

Fixed by downgrade `bson` to `^4.7.2`.

Problem is in this function:

https://github.com/mongodb/js-bson/blob/main/src/utils/node_byte_utils.ts#L34-L55

because require is converted to import in browser, but await is used in place without async.

```
/**
 * @internal
 * WARNING: REQUIRE WILL BE REWRITTEN
 *
 * This code is carefully used by require_rewriter.mjs any modifications must be reflected in the plugin.
 *
 * @remarks
 * "crypto" is the only dependency BSON needs. This presents a problem for creating a bundle of the BSON library
 * in an es module format that can be used both on the browser and in Node.js. In Node.js when BSON is imported as
 * an es module, there will be no global require function defined, making the code below fallback to the much less desireable math.random bytes.
 * In order to make our es module bundle work as expected on Node.js we need to change this `require()` to a dynamic import, and the dynamic
 * import must be top-level awaited since es modules are async. So we rely on a custom rollup plugin to seek out the following lines of code
 * and replace `require` with `await import` and the IIFE line (`nodejsRandomBytes = (() => { ... })()`) with `nodejsRandomBytes = await (async () => { ... })()`
 * when generating an es module bundle.
 */
const nodejsRandomBytes: (byteLength: number) => Uint8Array = (() => {
  try {
    return require('crypto').randomBytes;
  } catch {
    return nodejsMathRandomBytes;
  }
})();
```

**Comment by paulincai** [comment]
Mongo in Meteor 2.12 is at v4.* https://github.com/meteor/meteor/blob/devel/packages/npm-mongo/package.js
It is not supposed to work with bson v5.*

https://github.com/mongodb/node-mongodb-native#component-support-matrix

**Comment by adiabatic** [comment]
I got this error with Meteor **3**.1.2, too.

Here's what I got in the browser console:

```
Uncaught ReferenceError: await is not defined
    at module (node_byte_utils.ts:53:1)
    ⋮
```

Downgrading from `"bson": "^6.2.0",` to `"bson": "^4",` makes the error go away, even though `bson` 4.7.2 isn't supposed to work with 3.1.2.

<https://github.com/meteor/meteor/blob/release/METEOR%403.1.2/packages/npm-mongo/package.js> specifies MongoDB 6.9.0, while <https://github.com/mongodb/node-mongodb-native#component-support-matrix> says I should be using `bson` `^6`.

I'm only using `new ObjectId()` and `ObjectId.isValid(o: string | ObjectId)` on the frontend (or anywhere else), so I doubt I'll get bitten by any incompatibilities between 4 and 6, but I wanted to chime in and say that this is still happening with current versions of Meteor.

**Comment by italojs** [comment]
@adiabatic is it possible to create a simple and reproducible sample? I could work on it
