### ISSUE TITLE
mongo@1.16.6 continuous exceptions while polling query

### ISSUE THREAD

**Issue by azambranogalbis** [meteor/meteor#12642]
Issue refers to mongo v1.16.6 package.
We identified that when both mongodb database and our application are started simultaneously (i.e. upon server restart), and connection to mongo is established when the mongodb server is still performing some boot actions.

Application is configured without MONGO_OPLOG env variable (i.e. polling strategy is used to retrieve data from subscriptions).
Relevant code from application is as follows:
```
col.find(query, { fields: _fields }).observe({
      added(p) {
        self.add(p._id, p);
        if (callback) callback('added', p);
      },
      changed(p) {
        self.mod(p._id, p);
        if (callback) callback('changed', p);
      },
      removed(p) {
        self.del(p._id);
        if (callback) callback('removed', p);
      },
    });
```

*col* being a Mongo.Collection instance.

We observe that the following log is displayed every 10 seconds

```
2023-05-19T05:21:08.249447113Z Exception while polling query {"collectionName":"_transformations","selector":{},"options":{"transform":null,"projection":{"_id":1,"template":1,"functions":1,"code":1}}} MongoTopologyClosedError: Topology is closed
2023-05-19T05:21:08.249530945Z     at processWaitQueue (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:550:46)
2023-05-19T05:21:08.249542167Z     at Topology.selectServer (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:297:9)
2023-05-19T05:21:08.249549679Z     at Topology.<anonymous> (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:43:94)
2023-05-19T05:21:08.249558513Z     at internal/util.js:308:30
2023-05-19T05:21:08.249566571Z     at new Promise (<anonymous>)
2023-05-19T05:21:08.249574764Z     at Topology.selectServerAsync (internal/util.js:307:12)
2023-05-19T05:21:08.249583543Z     at executeOperationAsync (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/execute_operation.js:94:35)
2023-05-19T05:21:08.249590881Z     at /usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/execute_operation.js:12:45
2023-05-19T05:21:08.249601234Z     at maybeCallback (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:337:21)
2023-05-19T05:21:08.249609626Z     at executeOperation (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/execute_operation.js:12:38)
2023-05-19T05:21:08.249616987Z     at FindCursor._initialize (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/find_cursor.js:54:50)
2023-05-19T05:21:08.249624232Z     at FindCursor.[kInit] (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/abstract_cursor.js:444:14)
2023-05-19T05:21:08.249631453Z     at next (/usr/app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cursor/abstract_cursor.js:512:22)
2023-05-19T05:21:08.249686340Z     at internal/util.js:308:30
2023-05-19T05:21:08.249695383Z     at new Promise (<anonymous>)
2023-05-19T05:21:08.249702634Z     at next (internal/util.js:307:12)
2023-05-19T05:21:08.249712398Z  => awaited here:
2023-05-19T05:21:08.249721571Z     at Function.Promise.await (/usr/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
2023-05-19T05:21:08.249729751Z     at packages/mongo/mongo_driver.js:1134:14
2023-05-19T05:21:08.249738694Z     at /usr/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
2023-05-19T05:21:08.249746864Z  => awaited here:
2023-05-19T05:21:08.249755726Z     at Promise.await (/usr/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
2023-05-19T05:21:08.249764604Z     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1183:38)
2023-05-19T05:21:08.249773430Z     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1198:22)
2023-05-19T05:21:08.249783903Z     at SynchronousCursor.getRawObjects (packages/mongo/mongo_driver.js:1248:12)
2023-05-19T05:21:08.249793515Z     at PollingObserveDriver._pollMongo (packages/mongo/polling_observe_driver.js:156:44)
2023-05-19T05:21:08.249816641Z     at Object.task (packages/mongo/polling_observe_driver.js:93:12)
2023-05-19T05:21:08.249826011Z     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
2023-05-19T05:21:08.249833743Z     at packages/meteor.js:1003:12 {
2023-05-19T05:21:08.249841510Z   [Symbol(errorLabels)]: Set(0) {}
2023-05-19T05:21:08.249849431Z }
```

Application keeps alive, but remains inoperative due to this issue. We would expect the mongo package to be able to automatically recover from this situation, or kill the application. If we restart application once the mongo database is fully started, it works fine.

Happy to share more details if required. Thanks!

**Comment by yrambler2001** [comment]
the same issue after updating to meteor 1.12. Looks like Mongo is connecting now way more than 100 connections defined by the connection string
![image](https://github.com/meteor/meteor/assets/8398353/a6126ee0-bcae-4bdb-b5b6-b79e076506c9)
<img width="424" alt="Screenshot 2023-05-29 at 15 35 27" src="https://github.com/meteor/meteor/assets/8398353/2113b8b6-ed81-4005-8db0-b59881d6ec90">

**Comment by yrambler2001** [comment]
issue is reproducible only if 
MONGO_URL have mongodb+srv:// (not mongodb://)
and
const Collection = new Mongo.Collection('collection');
Collection.rawCollection().createIndex({  a:1 }) 
Collection.rawCollection().createIndex({  b:1 }) 
Collection.rawCollection().createIndex({  c:1 }) 
Collection.rawCollection().createIndex({  d:1 }) 
Collection.rawCollection().createIndex({  e:1 }) 
Collection.rawCollection().createIndex({  f:1 })

**Comment by yrambler2001** [comment]
steps to reproduce: 

1. create cloud.mongodb.com free tier cluster
2. clone https://github.com/yrambler2001/meteor-1.12-many-connections
3. open package json and change connection string to cluster created in step 1. **KEEP THE** `mongodb+srv` **PART AND** `&maxPoolSize=100&minPoolSize=100` **PART**
4. `npm run start` on main branch, 
5. after 1-2 minutes, on the cloud.mongodb.com you can see 300-500 connections
6. `npm run start` on 2.11 branch
7. after 1-2 minutes, on the cloud.mongodb.com you can see 100 connections

**Comment by yrambler2001** [comment]
This is clearly an issue with 2.12. It works well with 2.11. Deployment is unusable on 2.12
<img width="1662" alt="Screenshot 2023-05-29 at 20 12 51" src="https://github.com/meteor/meteor/assets/8398353/377ee398-8465-4724-8d55-e789af55cead">

**Comment by yrambler2001** [comment]
youtube link with repro https://youtu.be/E0enE3nyvW8

**Comment by yrambler2001** [comment]
this arrow is continuously being re-executed
![image](https://github.com/meteor/meteor/assets/8398353/1449a745-e895-487e-bf9c-a043cb2fbaf2)

this await on 123 line is the point when execution of `connect` (from prev screenshot) ends, and new `connect` is executed
![image](https://github.com/meteor/meteor/assets/8398353/2022f7d3-4d57-45f2-af53-3d953f8fb3b1)

**Comment by yrambler2001** [comment]
related pr(?) https://github.com/meteor/meteor/pull/12593/files

**Comment by yrambler2001** [comment]
related issue https://jira.mongodb.org/browse/NODE-5316

**Comment by yrambler2001** [comment]
for me - the solutions are

- add some await client.connect() before any operation will be executed
- revert pr #12593 
- revert pr #12593 and wait for MongoDB team to fix a bug
- use mongodb@5

**Comment by Grubba27** [comment]
> use mongodb@5 
This is a breaking change. I tried last year, and because they change from callbacks to promises, it broke in many places and would be a breaking change as well :/

**Comment by yrambler2001** [comment]
I can confirm that [repro I have posted in prev message](https://github.com/meteor/meteor/issues/12642#issuecomment-1567347613), works well after updating to 2.13-beta.0 with `meteor update --release 2.13-beta.0`

<img width="2560" alt="Screenshot 2023-05-31 at 19 47 45" src="https://github.com/meteor/meteor/assets/8398353/35ab05db-6e97-458d-8ea9-fcb38117a6a7">

**Comment by StorytellerCZ** [comment]
@Grubba27 if possible can we maybe just have this patch as Meteor v2.12.1? That way we don't have to rush any of the other features.

**Comment by danopia** [comment]
Is there a timeline for when this fix would be in a stable release?

I have a deployment which has started stumbling into `MongoTopologyClosedError` which is not resolved until the application server is restarted, and sometimes the application server doesn't even start up successfully. I am now running `2.13-beta.0` 'in production' because rolling back to `2.11.0` is undesirable for other reasons.

**Comment by Grubba27** [comment]
Hey, @danopia, we have `2.13-rc.0` and `2.13-rc.2`. The difference between these two is the existence of the security node patch in the latter.

**Comment by danopia** [comment]
> The difference between these two is the existence of the security node patch in the latter.

interesting, in that, `14.21.4` doesn't seem to be a real nodejs release, which complicates containerized deployments such as Dockerfiles. So Meteor 2.13 could be tricky to properly deploy for some folk. (Really looking forward to Meteor 3!!)

I'm now running `2.13-rc.0` to vet this fix :)
