### ISSUE TITLE
Mongo Transaction Throws - Error: Unknown command { "o": { "drop": ... }}

### ISSUE THREAD

**Issue by rebound-software** [meteor/meteor#12727]
I'm also seeing a similar issue to [#12627](https://github.com/meteor/meteor/issues/12627) as follows:

Exception in defer callback: Error: Unknown command
{
  "op":"c",
  "ns": "admin.$cmd",
  "ui": {
    "sub_type":4,
    "buffer": {
      "$binary":"16KKxoL+TtCTzvmpeGPA+w=="
    },
    "position":16
  },
  "o": {
    "drop": "pbmRUsers"
  },
  "o2": {
    "numRecords":5
  },
  "ts": {
    "$timestamp":"7261642129519149061"
  },
  "t":37,
  "v":2,
  "wall": {
    "$date":1690732811979
  }
}

 at handleDoc (packages/mongo/oplog_tailing.js:287:17)
 at packages/mongo/oplog_tailing.js:349:11
 at packages/meteor.js:365:18
 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
 at packages/meteor.js:613:25
 at runWithEnvironment (packages/meteor.js:1486:24)

I'm using a local install of mongo (Percona) because my app must be able to run on a local network without internet access. I have also enabled a periodic backup which I believe is the source of these oplog operations.

This issue occurs on the current v2.12 release of Meteor and I've also updated to v2.13 rc and am still seeing these exceptions so I'm guessing the drop? operation should also be safely ignored?

I can reproduce this issue easily on my target system running Ubuntu 20.04 with an install of Mongo 4.4 from Persona, but it's not straightforward to reproduce. Happy to help verify a fix.

**Comment by StorytellerCZ** [comment]
Can you check on the released version of Meteor 2.13?

**Comment by rebound-software** [comment]
I already have and I get the same behaviour.

I grabbed the Meteor source and is a simple fix assuming drop can be ignored in this situation (oplog_tailing.js line 272):

if (doc.ns === "admin.$cmd") {
if (doc.o.applyOps) {
// This was a successful transaction, so we need to apply the
// operations that were involved.
let nextTimestamp = doc.ts;
doc.o.applyOps.forEach(op => {
// See https://github.com/meteor/meteor/issues/10420.
if (!op.ts) {
op.ts = nextTimestamp;
nextTimestamp = nextTimestamp.add(Long.ONE);
}
handleDoc(op);
});
return;
} else if (doc.o.drop) {
// Safely ignore drop
return;
}
throw new Error("Unknown command " + EJSON.stringify(doc));
}

However, I’m not knowledgeable enough of the details in this area to be confident it’s as simple as just ignoring the drop, though I see no issues with my app when running due to this. Also, not sure if there are other cases that should be handled and ignored?


On 2 Aug 2023, at 08:01, Jan Dvorak ***@***.***> wrote:



Can you check on the released version of Meteor 2.13?

**Comment by radekmie** [comment]
@rebound-software While your fix is totally fine, I have a hard time reproducing this issue. The problem is that no matter how I `drop` the collection, it always originates from the database it was dropped in (`example.$cmd`), not from admin (`admin.$cmd`).

In that case, I'd ask you to provide a reproduction. I set up Percona's MongoDB but couldn't easily set up the backups. Until then, I consider this not a bug but a Percona-specific issue.

**Comment by nachocodoner** [comment]
Apparently this will be delivered in next Meteor 3.5.1 official so that we will be able to close it then.
