### ISSUE TITLE
Cannot extract any version of meteor tool

### ISSUE THREAD

**Issue by conorstrejcek** [meteor/meteor#12731]
## Details

- Meteor version: Any version lower than the most recent version
- Operating System: `MacOS 13.4.1 (c) (22F770820d)`
- Processor: `2.6 GHz 6-Core Intel Core i7`
- Local Node version: I have attempted this with the latest patch versions of `14`, `16`, and `18` with the same results

## Expected Behavior

I should be able to specify a release of `meteor` to install when running my meteor application locally, and the `meteor-tool` should be downloaded, and `meteor` should run in the expected version.

## Actual Behavior

I was attempting to upgrade my `meteor` version for a project locally, and started running into an issue where I could not get past extracting the `meteor-tool`. I have reverted my release version back to it's original working version, but the issue persists. When I try to start the application, after downloading the `meteor` tool, I get this error:

```bash
/Users/conorstrejcek/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: incorrect data check
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17)
 => awaited here:
    at Promise.await (/Users/conorstrejcek/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Object.extractTarGz (/Users/conorstrejcek/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:791:11)
    at Object.exports._extractAndConvert (/tools/packaging/tropohouse.js:47:9)
    at /tools/packaging/tropohouse.js:502:42
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:499:24
    at Function.each (/Users/conorstrejcek/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at /tools/packaging/tropohouse.js:466:11
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:424:20)
    at /tools/packaging/tropohouse.js:597:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:594:20)
    at /tools/cli/main.js:469:28
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at /tools/cli/main.js:468:15
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at /tools/cli/main.js:465:33
    at Console.withProgressDisplayVisible (/tools/console/console.js:639:14)
    at springboard (/tools/cli/main.js:464:11)
    at /tools/cli/main.js:1165:7 {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

I have tried removing my local `~/.meteor` directory, reinstalling `meteor`, cleared out my `node_modules` (not sure that it is relevant) and removed my local project `.meteor/local` files.

I think this may be related to my OS and/or some temporary files which may have gotten left behind by a previous install of `meteor`. The issue started happening when I did an upgrade to the `meteor` version, but now all of my local `meteor` projects are experiencing it, as they need to download fresh versions of the `meteor-tool` (since I cleared out `~/.meteor`).

Unfortunately I can't provide a reliable reproduction, because it appears to be local to my machine. I was hoping the stack trace above might help in identifying the issue. I'm happy to provide any additional information necessary.

**Comment by paragcopods** [comment]
Facing similar error on M1 MacBook Air.

**Comment by StorytellerCZ** [comment]
What Meteor versions are we talking about here?

**Comment by Grubba27** [comment]
Hey @StorytellerCZ that is version 2.13, I'm still looking into this matter

**Comment by conorstrejcek** [comment]
Some additional info, if helpful:

To test, I just change the meteor release in the `release` file and start the project, or run `meteor update --release <version.number>`. After downloading the `meteor-tool`, it fails after extraction with the stack trace I included in the description.

In my own debugging, I couldn't get much further than looking at where the error comes from: 
- https://github.com/meteor/meteor/blob/master/tools/fs/files.ts#L819-L854
- [Gunzip Class](https://nodejs.org/api/zlib.html#class-zlibgunzip)
- Z_DATA_ERROR [Node](https://nodejs.org/api/zlib.html#zlib-constants), [zlib](https://zlib.net/manual.html#Constants)

**Comment by conorstrejcek** [comment]
Ah, I didn't realize you could specify a release version when downloading the meteor install script, so I've managed to work around this by re-installing a previous version of meteor. Hopefully this is helpful to anyone currently experiencing this:

```bash
curl https://install.meteor.com/\?release\=2.11.0 | sh
```

**Comment by wolasss** [comment]
I am getting the same error after upgrading to `2.13` via `meteor update` command.

**Comment by silverbuggy** [comment]
I am facing this Z_DATA_ERROR also when trying to do "meteor update" from 2.12 to 2.13

**Comment by edwardupton** [comment]
Same issue going from 2.11 to 2.13

**Comment by jirikrepl** [comment]
I have the same error (with the same stack trace) on Intel MacBook when updating from 2.12 to 2.13.

Maybe some package - installation file is missing, when the install process tries to extract it with the function call `Object.extractTarGz` And then gets some zlib error.

**Comment by llihund19git** [comment]
> Ah, I didn't realize you could specify a release version when downloading the meteor install script, so I've managed to work around this by re-installing a previous version of meteor. Hopefully this is helpful to anyone currently experiencing this:
> 
> ```shell
> curl https://install.meteor.com/\?release\=2.11.0 | sh
> ```

It works on my side (Mac m2). 
Make sure to install python2:
-brew install pyenv
-pyenv install 2.7.18
-export PATH="$(pyenv root)/shims:${PATH}"

**Comment by danopia** [comment]
I was finding this as a general NPM issue since `meteor npm` was suddenly unable to untar some of my dependencies no matter what I tried 💀

It sounds like this zlib bug happened on nodejses compiled in a specific way:

* https://github.com/nodejs/node/issues/39313

so I hope meteor manages to address this incompatibility issue with their next ESM build of NodeJS v14. (And I also look forward to NodeJS v18)

**Comment by rjalili** [comment]
Same issue here, FWIW: 2.7 GHz Dual-Core Intel Core i5, Early 2015, macOS Monterey
since Meteor 2.13, node 14.21.3  even with npm 6.14.17 and after disabling all other node versions and removing .meteor and .nvm and node_modules and resetting everything with fresh installs, unable to build *certain* npm packages. App almost builds entirely, but not entirely. At least 2 packages have the zlib error on installation.  Thanks to @llihund19git for your guidance.  Am trying that now.

First result:
running meteor is again automatically downloading tool @ 2.13 although I though I had just installed 2.11.

Have not yet taken the python steps.

**Comment by rjalili** [comment]
Now having tried the python steps advised by @llihund19git , I see this line in the installation of python 

python-build: use zlib from xcode sdk

So, I wonder if the error is with my xcode zlip version being incompatible or "behind" what node is expecting.

I realize I'm surrounded by experts; I am not an expert in this. I hope my info might be helpful to someone who is solving this issue. 

Really stuck otherwise and cannot continue product development.

**Comment by wreiske** [comment]
This is also impacting my development on MacBook Pro Apple M2 Max.

```
meteor update
/Users/wreiske/.meteor/packages/meteor-tool/.2.13.0.1vtky79.k09v++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: incorrect data check
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17)
 => awaited here:
    at Promise.await (/Users/wreiske/.meteor/packages/meteor-tool/.2.13.0.1vtky79.k09v++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Object.extractTarGz (/Users/wreiske/.meteor/packages/meteor-tool/.2.13.0.1vtky79.k09v++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:791:11)
    at Object.exports._extractAndConvert (/tools/packaging/tropohouse.js:47:9)
    at /tools/packaging/tropohouse.js:502:42
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:499:24
    at Function.each (/Users/wreiske/.meteor/packages/meteor-tool/.2.13.0.1vtky79.k09v++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at /tools/packaging/tropohouse.js:466:11
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:424:20)
    at /tools/packaging/tropohouse.js:597:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:594:20)
    at /tools/packaging/updater.js:187:26
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at updateMeteorToolSymlink (/tools/packaging/updater.js:186:33)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1558:3)
    at Command.func (/tools/cli/commands-packages.js:1794:29)
    at /tools/cli/main.js:1534:15 {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
```

**Comment by milanzigmond** [comment]
same error trying to add older version of vuetify, installed latest vuetify  and then changed to 2.6.14 and 'meteor npm i'
<img width="909" alt="Screenshot 2023-08-31 at 18 03 34" src="https://github.com/meteor/meteor/assets/4190850/27afa51b-4d2d-4280-9ed3-b030cfbef8dc">
<img width="1188" alt="Screenshot 2023-08-31 at 18 03 54" src="https://github.com/meteor/meteor/assets/4190850/b4779bee-8d77-4d54-bda3-91f69202f2fc">

**Comment by xiatian12345** [comment]
when i create the app, i got the similar error;
`meteor create --svelte simple-todos-svelte --prototype`
/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: incorrect data check
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17)
 => awaited here:
    at Promise.await (/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Object.extractTarGz (/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:791:11)
    at Object.exports._extractAndConvert (/tools/packaging/tropohouse.js:47:9)
    at /tools/packaging/tropohouse.js:502:42
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:499:24
    at Function.each (/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at /tools/packaging/tropohouse.js:466:11
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:424:20)
    at /tools/packaging/tropohouse.js:597:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:594:20)
    at /tools/project-context.js:921:25
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/project-context.js:920:20
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:919:13)
    at /tools/project-context.js:365:35
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:355:18)
    at /tools/project-context.js:347:12
    at Function.run (/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:346:13)
    at /tools/cli/commands.js:872:20
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.main.captureAndExit (/tools/cli/main.js:281:29)
    at Command.func (/tools/cli/commands.js:846:8)
    at /tools/cli/main.js:1534:15 {
  errno: -3,
  code: 'Z_DATA_ERROR'
}

node version v16.3.0
mac13.2.1 (22D68) 2.6 GHz 六核Intel Core i7 Intel UHD Graphics 630 1536 MB 16 GB 2667 MHz DDR4
python version 3.10.11

**Comment by fredmaiaarantes** [comment]
I've heard that @Grubba27 found a solution for hits. It will be released soon. 🎉

**Comment by Grubba27** [comment]
I think I've solved this matter!

you can test it by running the following command:

```bash

meteor update --release 2.13.1

```

**Comment by xiatian12345** [comment]
There seems to be an update error.

➜  Desktop meteor update --release 2.13.1
/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: incorrect data check
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17)
 => awaited here:
    at Promise.await (/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Object.extractTarGz (/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:791:11)
    at Object.exports._extractAndConvert (/tools/packaging/tropohouse.js:47:9)
    at /tools/packaging/tropohouse.js:502:42
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:499:24
    at Function.each (/Users/xiatian/.meteor/packages/meteor-tool/.2.13.0.yk4rw8.bheh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at /tools/packaging/tropohouse.js:466:11
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:424:20)
    at /tools/packaging/tropohouse.js:597:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:594:20)
    at /tools/cli/main.js:469:28
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at /tools/cli/main.js:468:15
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at /tools/cli/main.js:465:33
    at Console.withProgressDisplayVisible (/tools/console/console.js:639:14)
    at springboard (/tools/cli/main.js:464:11)
    at /tools/cli/main.js:1165:7 {
  errno: -3,
  code: 'Z_DATA_ERROR'
}

**Comment by Grubba27** [comment]
Hey @xiatian12345 try using the `curl` command it will replace your meteor tool and probably will make it work.

```bash

curl https://install.meteor.com/\?release\=2.13.1 | sh

```

**Comment by xiatian12345** [comment]
> Hey @xiatian12345 try using the `curl` command it will replace your meteor tool and probably will make it work.
> 
> ```shell
> curl https://install.meteor.com/\?release\=2.13.1 | sh
> ```

Thanks, the issue has been resolved. :)

**Comment by jinglisen** [comment]
MacBook Pro 2019 i9，运行vuepress项目需要nodejs16，不想升级到最新版本nodejs，完美解决了问题，可以运行啦，开心开心 


请参考https://blog.csdn.net/JingLisen/article/details/138953482?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22138953482%22%2C%22source%22%3A%22JingLisen%22%7D

**Comment by jinglisen** [comment]
![Uploading QQ20240516-162954@2x.png…]()

**Comment by jinglisen** [comment]
<img width="1792" alt="QQ20240516-162954@2x" src="https://github.com/meteor/meteor/assets/46705164/2635bad4-2675-4727-91e2-3953e0f2ce64">

**Comment by paulincai** [comment]
> <img alt="QQ20240516-162954@2x" width="1792" src="https://private-user-images.githubusercontent.com/46705164/331117085-2635bad4-2675-4727-91e2-3953e0f2ce64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDg2NzYsIm5iZiI6MTcxNTg0ODM3NiwicGF0aCI6Ii80NjcwNTE2NC8zMzExMTcwODUtMjYzNWJhZDQtMjY3NS00NzI3LTkxZTItMzk1M2UwZjJjZTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MzI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZmQ5OWYyMTNiZjAzMTZhMTkyMTVhMDNhMDdkODZhNGYxNjQ5NzUyYWE2YTcyNDQ1Njc4ZDViOGE1NWVlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z8-EXCAy5TvKYgR8UvQMfCSOr0u8UFkE50qLaJLUaNo">

Hi @jinglisen I don't understand your code and editor in English. Could you please post an image with everything in Chinese?

**Comment by jinglisen** [comment]
你应该先参考一下上面这个哥们的方法，然后再试试我的，应该就可以了，亲测有效，亲
> Make sure to install python2:
> -brew install pyenv
> -pyenv install 2.7.18
> -export PATH="$(pyenv root)/shims:${PATH}"

**Comment by jinglisen** [comment]
<img width="1668" alt="001" src="https://github.com/meteor/meteor/assets/46705164/00e4107c-a81f-4e09-9150-ea17573a3e92">
<img width="1667" alt="002" src="https://github.com/meteor/meteor/assets/46705164/88e5a968-a895-431b-ac0b-5b33bbb818de">
拿出来了我的旧电脑MacBook Pro (15-inch, 2016)、MacOS Monterey 、Processor 2.7 GHz Quad-Core Intel Core i7 九代CPU重现了这个问题，最终还是解决了：
方法一：
https://blog.csdn.net/JingLisen/article/details/138953482?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22138953482%22%2C%22source%22%3A%22JingLisen%22%7D
方法二：
下载了新版本的Nodejs，然后yarn install，乖乖没报错，然后安装了低版本的Nodejs node-v16.20.2，可以运行了，应该是新版本修复了bug，哪里有存新版本中的代码吧，我也不是很清楚，但是问题确实解决啦，希望可以帮到你
