### ISSUE TITLE
Upgrading from 2.13 to 2.13.1 fails with Error: Incorrect Data Check

### ISSUE THREAD

**Issue by generalleger** [meteor/meteor#12774]
MacOS: 12.6.8

### Reproduction:

`meteor create upgrade-test --version 2.13 --bare`

`cd upgrade-test`

`meteor update`

### Output
```
/Users/me/.meteor/packages/meteor-tool/.2.13.0.i0zzvl.fkve9++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: incorrect data check
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17)
 => awaited here:
    at Promise.await (/Users/me/.meteor/packages/meteor-tool/.2.13.0.i0zzvl.fkve9++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Object.extractTarGz (/Users/me/.meteor/packages/meteor-tool/.2.13.0.i0zzvl.fkve9++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:791:11)
    at Object.exports._extractAndConvert (/tools/packaging/tropohouse.js:47:9)
    at /tools/packaging/tropohouse.js:502:42
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at /tools/packaging/tropohouse.js:499:24
    at Function.each (/Users/me/.meteor/packages/meteor-tool/.2.13.0.i0zzvl.fkve9++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1316:7)
    at /tools/packaging/tropohouse.js:466:11
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.download (/tools/packaging/tropohouse.js:424:20)
    at /tools/packaging/tropohouse.js:597:22
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at exports.Tropohouse.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:594:20)
    at /tools/cli/main.js:469:28
    at /tools/packaging/catalog/catalog.js:100:5
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at /tools/cli/main.js:468:15
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at /tools/cli/main.js:465:33
    at Console.withProgressDisplayVisible (/tools/console/console.js:639:14)
    at springboard (/tools/cli/main.js:464:11)
    at /tools/cli/main.js:1554:7 {
  errno: -3,
  code: 'Z_DATA_ERROR'
}

```

**Comment by generalleger** [comment]
I just tested with 2.13.3, and it is throwing the same error. Any ideas?

**Comment by generalleger** [comment]
@Grubba27 bingo bango, time to tango! That did the trick.
