### ISSUE TITLE
fourseven:scss 404 on darwin-arm64-83_binding.node

### ISSUE THREAD

**Issue by generalleger** [meteor/meteor#12777]
Meteor version 2.13.3
MacOS 12.6.9
Apple silicon - (might be relevant)

## Reproduction 

`meteor create test --bare`
`cd test`
`meteor install fourseven:scss`

Looks like it is trying to find a version of node-sass that is not there.

```
  => Errors while adding packages:             
                                              
While loading package fourseven:scss@4.15.0:
error: Command failed:
/Users/me/.meteor/packages/meteor-tool/.2.13.3.s3zrs7.qh67o++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/npm
rebuild --update-binary
Cannot download
"https://github.com/sass/node-sass/releases/download/v4.14.1/darwin-arm64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g. 

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli
'/Users/me/.meteor/packages/meteor-tool/.2.13.3.s3zrs7.qh67o++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node',
gyp verb cli
'/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.21.4 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the
PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous>
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:16)
gyp ERR! stack     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp ERR! stack     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp ERR! stack     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp ERR! stack     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Darwin 21.6.0
gyp ERR! command
"/Users/me/.meteor/packages/meteor-tool/.2.13.3.s3zrs7.qh67o++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node"
"/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1wne1v.5ii8k/node_modules/node-sass
gyp ERR! node -v v14.21.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional
logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2023-09-13T12_30_17_246Z-debug.log
Cannot download
"https://github.com/sass/node-sass/releases/download/v4.14.1/darwin-arm64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g. 

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli
'/Users/me/.meteor/packages/meteor-tool/.2.13.3.s3zrs7.qh67o++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node',
gyp verb cli
'/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.21.4 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the
PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous>
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:68:16)
gyp ERR! stack     at E
(/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:80:29)
gyp ERR! stack     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/which/which.js:89:16
gyp ERR! stack     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/index.js:42:5
gyp ERR! stack     at
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Darwin 21.6.0
gyp ERR! command
"/Users/me/.meteor/packages/meteor-tool/.2.13.3.s3zrs7.qh67o++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/bin/node"
"/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/Users/me/.meteor/packages/fourseven_scss/.4.15.0.hur6n6.wgawj++os+web.browser+web.browser.legacy+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-1wne1v.5ii8k/node_modules/node-sass
gyp ERR! node -v v14.21.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional
logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2023-09-13T12_30_17_246Z-debug.log
```

**Comment by Grubba27** [comment]
I had this issue before in another project(I'm in a m2), to solve this run this command:

```bash
brew install pyenv
pyenv install 2.7.18
pyenv global 2.7.18
```
then add to your `.zshrc`

```bash
export PATH="$HOME/.pyenv/shims:$PATH"
```

**Comment by generalleger** [comment]
Is there no limit to your awesomeness? Thank you!

**Comment by paulincai** [comment]
Note of Python deprecation: https://www.freecodecamp.org/news/python-version-on-mac-update/#:~:text=MacOS%20comes%20with%20Python%20pre,of%20writing%20this%20is%203.9).
