### ISSUE TITLE
v3 alpha release builds require glibc version change

### ISSUE THREAD

**Issue by DeciderWill** [meteor/meteor#12790]
As seen [recently for 2.13.1 ](https://github.com/meteor/meteor/issues/12771) a new glibc version seems to be required with the new built versions of Meteor. A hotfix was made to fix 2.13.1 but still affects v3 alpha builds.

Error:
```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /root/.meteor/packages/meteor-tool/.3.0.0-alpha.15.1dcmqfr.86zy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/vscode-nsfw/build/Release/nsfw.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Module.mod.require (/root/.meteor/packages/meteor-tool/.3.0.0-alpha.15.1dcmqfr.86zy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/root/.meteor/packages/meteor-tool/.3.0.0-alpha.15.1dcmqfr.86zy++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/vscode-nsfw/js/src/index.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.Mp._compile (/tools/static-assets/server/runtime.js:78:21) {
  code: 'ERR_DLOPEN_FAILED'
```

A new default GCP 20.04 OS image has
```
5.15.0-1042-gcp #50~20.04.1-Ubuntu SMP Mon Sep 11 03:30:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
````

```
ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

Just an FYI so the builds can be available to the most common glibc to prevent upgrade issues!

**Comment by denihs** [comment]
This should be fixed already. If not, we can re-open this issue.

**Comment by Shelagh-Lewins** [comment]
Hiya, I am seeing this issue with Meteor 3.1 (just upgraded from 2.16 and trying to get things working).

```
=> Started proxy.                             
                                              
/home/username/.meteor/packages/meteor-tool/.3.1.0.tsf1gs.dtdj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by
/home/username/.meteor/packages/meteor-tool/.3.1.0.tsf1gs.dtdj++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/mongodb/bin/mongod)
```

I am running Linux Mint 20 Ulyana, and it's on the highest supported version:

```
sudo apt-get install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.31-0ubuntu9.16).
```

I've opened a new bug https://github.com/meteor/meteor/issues/13536 as this bug is quite old?
