### ISSUE TITLE
Meteor 3.0-alpha.15  mongo driver has no findOne method

### ISSUE THREAD

**Issue by copleykj** [meteor/meteor#12831]
In 3.0-alpha.15 release if you create a new collection and then call the `findOne` method it throws the following error:
```sh
I20231016-23:10:58.789(-4)? error on boot.js TypeError: this._collection.findOne is not a function
I20231016-23:10:58.789(-4)?     at Collection.findOne (packages/mongo/collection.js:558:29)
I20231016-23:10:58.789(-4)?     at server/main.ts:45:32
I20231016-23:10:58.790(-4)?     at Function.time (/home/copleykj/projects/freelance-work/Next Level Sports/marathon/.meteor/local/build/programs/server/profile.js:277:30)
I20231016-23:10:58.790(-4)?     at /home/copleykj/projects/freelance-work/Next Level Sports/marathon/.meteor/local/build/programs/server/boot.js:389:21
I20231016-23:10:58.790(-4)?     at /home/copleykj/projects/freelance-work/Next Level Sports/marathon/.meteor/local/build/programs/server/boot.js:438:9
I20231016-23:10:58.790(-4)?     at startServerProcess (/home/copleykj/projects/freelance-work/Next Level Sports/marathon/.meteor/local/build/programs/server/boot.js:435:5)
I20231016-23:10:58.790(-4)? TypeError: this._collection.findOne is not a function
I20231016-23:10:58.790(-4)?     at Collection.findOne (packages/mongo/collection.js:558:29)
I20231016-23:10:58.790(-4)?     at server/main.ts:45:32
I20231016-23:10:58.790(-4)?     at Function.time (/home/copleykj/projects/freelance-work/Next Level Sports/marathon/.meteor/local/build/programs/server/profile.js:277:30)
I20231016-23:10:58.790(-4)?     at /home/copleykj/projects/freelance-work/Next Level Sports/marathon/.meteor/local/build/programs/server/boot.js:389:21
I20231016-23:10:58.790(-4)?     at /home/copleykj/projects/freelance-work/Next Level Sports/marathon/.meteor/local/build/programs/server/boot.js:438:9
```
It looks as if the mongo driver that's stored at `this._collection` does not have a `findOne` method.

I've not created a reproduction repo for this as it's simple enough to reproduce by creating a new app and then creating a new test collection and calling findOne on it.

**Comment by Grubba27** [comment]
In 3.0 you should use findOneAsync in the server, instead of findOne, in the next release, we will have a clearer error message. 

The pr that solved this is this one: https://github.com/meteor/meteor/pull/12802

**Comment by copleykj** [comment]
Thanks. 👍
