### ISSUE TITLE
Problem with Meteor version METEOR@2.13.3

### ISSUE THREAD

**Issue by nesbtesh** [meteor/meteor#12857]
I am getting a weird behavior when I upgrade to Meteor@2.13.2

It started when I deployed to production in heroku, I got this:

```
/tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.2.13.3.ntl153.rfqwm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
errorClass [Error]: Internal server error [500]
    at Connection._livedata_result (packages/ddp-client/common/livedata_connection.js:1650:9)
    at Connection.onMessage (packages/ddp-client/common/livedata_connection.js:1812:12)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/socket-stream-client/node.js:202:9
    at Array.forEach (<anonymous>)
    at ClientStream.forEachCallback (packages/socket-stream-client/common.js:30:31)
    at packages/socket-stream-client/node.js:201:12
    at packages/socket-stream-client/node.js:179:11
    at runWithEnvironment (packages/meteor.js:1486:24)
 => awaited here:
    at Promise.await (/tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.2.13.3.ntl153.rfqwm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at ServiceConnection.apply (/tools/meteor-services/service-connection.js:131:32)
    at ServiceConnection.call (/tools/meteor-services/service-connection.js:103:17)
    at loadRemotePackageData (/tools/packaging/package-client.js:105:15)
    at getSomeData (/tools/packaging/package-client.js:176:22)
    at _updateServerPackageData (/tools/packaging/package-client.js:223:7)
    at /tools/packaging/package-client.js:129:12
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Object.exports.updateServerPackageData (/tools/packaging/package-client.js:128:23)
    at /tools/packaging/catalog/catalog-remote.js:782:36
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at RemoteCatalog.refresh (/tools/packaging/catalog/catalog-remote.js:781:18)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:123:22)
    at ProjectContext._resolveConstraints (/tools/project-context.js:592:13)
    at /tools/project-context.js:365:35
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:355:18)
    at /tools/project-context.js:347:12
    at Function.run (/tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.2.13.3.ntl153.rfqwm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:346:13)
    at /tools/cli/commands.js:1050:20
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.main.captureAndExit (/tools/cli/main.js:281:29)
    at buildCommand (/tools/cli/commands.js:1047:8)
    at /tools/cli/commands.js:988:25
    at Function.run (/tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.2.13.3.ntl153.rfqwm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at /tools/cli/commands.js:986:18
    at /tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.2.13.3.ntl153.rfqwm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/tmp/codon/tmp/cache/meteor/.meteor/packages/meteor-tool/.2.13.3.ntl153.rfqwm++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at /tools/cli/main.js:1535:7 {
  isClientSafe: true,
  error: 500,
  reason: 'Internal server error',
  details: undefined,
  errorType: 'Meteor.Error'
}


```

Now when I run meteor update I get this:
```
meteor update                    
                                              
/Users/nessimbtesh/.meteor/packages/meteor-tool/.2.13.3.6banig.e1j7++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
errorClass [Error]: Internal server error [500]
    at Connection._livedata_result (packages/ddp-client/common/livedata_connection.js:1650:9)
    at Connection.onMessage (packages/ddp-client/common/livedata_connection.js:1812:12)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/socket-stream-client/node.js:202:9
    at Array.forEach (<anonymous>)
    at ClientStream.forEachCallback (packages/socket-stream-client/common.js:30:31)
    at packages/socket-stream-client/node.js:201:12
    at packages/socket-stream-client/node.js:179:11
    at runWithEnvironment (packages/meteor.js:1486:24)
 => awaited here:
    at Promise.await (/Users/nessimbtesh/.meteor/packages/meteor-tool/.2.13.3.6banig.e1j7++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at ServiceConnection.apply (/tools/meteor-services/service-connection.js:131:32)
    at ServiceConnection.call (/tools/meteor-services/service-connection.js:103:17)
    at loadRemotePackageData (/tools/packaging/package-client.js:105:15)
    at getSomeData (/tools/packaging/package-client.js:176:22)
    at _updateServerPackageData (/tools/packaging/package-client.js:223:7)
    at /tools/packaging/package-client.js:129:12
    at Object.enterJob (/tools/utils/buildmessage.js:356:14)
    at Object.exports.updateServerPackageData (/tools/packaging/package-client.js:128:23)
    at /tools/packaging/catalog/catalog-remote.js:782:36
    at Object.enterJob (/tools/utils/buildmessage.js:356:14)
    at RemoteCatalog.refresh (/tools/packaging/catalog/catalog-remote.js:781:18)
    at Object.catalog.refreshOrWarn (/tools/packaging/catalog/catalog.js:48:22)
    at catalog.Refresh.OnceAtStart.beforeCommand (/tools/packaging/catalog/catalog.js:21:16)
    at /tools/cli/main.js:1529:32
    at Object.enterJob (/tools/utils/buildmessage.js:356:14)
    at /tools/cli/main.js:1528:20 {
  isClientSafe: true,
  error: 500,
  reason: 'Internal server error',
  details: undefined,
  errorType: 'Meteor.Error'
}

```

**Comment by gbhrdt** [comment]
Same issue here in our CI

**Comment by simplecommerce** [comment]
I have the same issue here, could be related to: https://status.meteor.com/

**Comment by nesbtesh** [comment]
Yes but this is a major problem,

Why is the deployment of our systems dependent on your servers?

**Comment by Grubba27** [comment]
>Why is the deployment of our systems dependent on your servers?

Meteor.js updates its internal catalog by calling a [method](https://github.com/meteor/meteor/blob/f1bb0ea9f9aa628d9ff8a8980a01223899b7eb23/tools/packaging/package-client.js#L105) from [packages.meteor.com](http://packages.meteor.com/). Unfortunately, the service is currently down due to an issue with OVHCloud, where the database hosting takes place. Consequently, the catalog cannot be updated, resulting in the error. Since the resolution is taking longer than expected, we are actively working on an alternative solution to fix it without relying on OVH’s timeline.

**Comment by fredmaiaarantes** [comment]
Meteor.js updates its internal catalog (database) by calling a [method](https://github.com/meteor/meteor/blob/f1bb0ea9f9aa628d9ff8a8980a01223899b7eb23/tools/packaging/package-client.js#L105) from [packages.meteor.com](http://packages.meteor.com/). Unfortunately, this service is currently down due to an issue with our provider, OVHCloud, where the database hosting takes place.  As a result, the catalog cannot be updated, leading to an error.

Many components of Meteor.js rely on the underlying infrastructure provided by Meteor Software. However, considering the significant delay in resolving the issue, our DevOps team is actively working on an alternative solution to fix it independently of OVH's timeline.

**Comment by jeffreyflynt** [comment]
While this is in the works, is there anything we can do on our end to bypass this? @fredmaiaarantes

**Comment by nesbtesh** [comment]
It would be great if this could be running a community service that is not dependent on the Meteor Company

**Comment by fredmaiaarantes** [comment]
> While this is in the works, is there anything we can do on our end to bypass this? @fredmaiaarantes
> 
> I can build locally, but GH Actions fails

Not that I know. Our team will prioritize these services first in the restoration plan.

**Comment by zodern** [comment]
You can use the environment variable `METEOR_OFFLINE_CATALOG=true` to avoid the error, though it will only work if the offline catalog is adequately up to date (should work locally, and maybe in CI if ~/.meteor is cached).

The error handling should probably be improved in the meteor-tool for this. It already works when offline, so errors with syncing probably shouldn't break it either.

**Comment by fredmaiaarantes** [comment]
Our team was able to restore [packages.meteor.com](packages.meteor.com). 
Meteor deployments and commands should now work without any issues.

I'm closing this issue, but feel free to reopen it if you encounter any new issues.

**Comment by wyq09** [comment]
邮件已收到   ~3Q~

**Comment by nesbtesh** [comment]
@fredmaiaarantes it would be great if we could have a secondary packages.meteor.com either hosted on an open distro or on our own personal data center. Is that possible? Similar to how we do it with NPM

**Comment by zodern** [comment]
@fredmaiaarantes I wouldn't mind hosting a read only mirror of the packages api. I already have a few projects that store a copy of the package metadata using https://github.com/Meteor-Community-Packages/meteor-packages. It seems the main thing a mirror would need to provide is the `syncNewPackageData` method, and I seem to remember there also being a couple subscriptions.

**Comment by rpong** [comment]
> [fredmaiaarantes](/fredmaiaarantes)

this is happening again, was able to replicate both locally and from our remote CI servers.

**Comment by lc3t35** [comment]
@fredmaiaarantes 

It happens again 

```
meteor update

/Users/laurent/.meteor/packages/meteor-tool/.2.14.0.syn6jj.l63p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
errorClass [Error]: Internal server error [500]
    at Connection._livedata_result (packages/ddp-client/common/livedata_connection.js:1650:9)
    at Connection.onMessage (packages/ddp-client/common/livedata_connection.js:1812:12)
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at packages/socket-stream-client/node.js:202:9
    at Array.forEach (<anonymous>)
    at ClientStream.forEachCallback (packages/socket-stream-client/common.js:30:31)
    at packages/socket-stream-client/node.js:201:12
    at packages/socket-stream-client/node.js:179:11
    at runWithEnvironment (packages/meteor.js:1486:24)
 => awaited here:
    at Promise.await (/Users/laurent/.meteor/packages/meteor-tool/.2.14.0.syn6jj.l63p++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at ServiceConnection.apply (/tools/meteor-services/service-connection.js:131:32)
    at ServiceConnection.call (/tools/meteor-services/service-connection.js:103:17)
    at loadRemotePackageData (/tools/packaging/package-client.js:105:15)
    at getSomeData (/tools/packaging/package-client.js:176:22)
    at _updateServerPackageData (/tools/packaging/package-client.js:223:7)
    at /tools/packaging/package-client.js:129:12
    at Object.enterJob (/tools/utils/buildmessage.js:356:14)
    at Object.exports.updateServerPackageData (/tools/packaging/package-client.js:128:23)
    at /tools/packaging/catalog/catalog-remote.js:782:36
    at Object.enterJob (/tools/utils/buildmessage.js:356:14)
    at RemoteCatalog.refresh (/tools/packaging/catalog/catalog-remote.js:781:18)
    at Object.catalog.refreshOrWarn (/tools/packaging/catalog/catalog.js:48:22)
    at catalog.Refresh.OnceAtStart.beforeCommand (/tools/packaging/catalog/catalog.js:21:16)
    at /tools/cli/main.js:1529:32
    at Object.enterJob (/tools/utils/buildmessage.js:356:14)
    at /tools/cli/main.js:1528:20 {
  isClientSafe: true,
  error: 500,
  reason: 'Internal server error',
  details: undefined,
  errorType: 'Meteor.Error'
}
```
