### ISSUE TITLE
Unable to publish a new version of a Meteor package

### ISSUE THREAD

**Issue by jamauro** [meteor/meteor#12868]
Hi,

I created a new Meteor package and published it last week. I've made some updates and would like to publish a new version. When I run `meteor publish` I see this error:

```
=> Errors while publishing:                   
                                              
While pre-publishing package jam:method:
error: Unknown Package
```

Also for some reason the package isn't showing up on Atmosphere but it does show up on Packosphere. I'm not sure if that is related or not.

I thought maybe Atmosphere didn't pick it up because of the outage around the same time. But when I run `meteor publish --create`, I see

```
Package already exists. To create a new version of an existing package, do not
use the --create flag!
```

Any ideas?

**Comment by StorytellerCZ** [comment]
Interesting. Can't find it even with `meteor show` command. How does your `package.js` look like?

**Comment by StorytellerCZ** [comment]
@Grubba27 could this be a potential issue with the infrastructure somewhere?

**Comment by jamauro** [comment]
Here's my `package.js`. The version originally published was `1.0.0-beta`.

```js
Package.describe({
  name: 'jam:method',
  version: '1.0.0',
  summary: 'An easy way to create Meteor methods',
  git: 'https://github.com/jamauro/method',
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('2.8.1');
  api.use('ecmascript');
  api.use('ddp-rate-limiter');
  api.use('check');
  api.use('mongo');
  api.mainModule('method.js');
});

Package.onTest(function(api) {
  api.use('ecmascript');
  api.use('tinytest');
  api.use('mongo');
  api.use('jam:easy-schema');
  api.use('jam:method');
  api.addFiles('test-methods.js', 'server');
  api.mainModule('method-tests.js');
});
```

Interestingly, I tried `meteor publish` this morning and now I see
```
/Users/jam/.meteor/packages/meteor-tool/.2.13.3.in6tmb.0n3ts++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Found multiple packages matching name: jam:method
    at RemoteCatalog.getPackage (/tools/packaging/catalog/catalog-remote.js:602:13)
    at Object.exports.publishPackage (/tools/packaging/package-client.js:612:39)
    at /tools/cli/commands-packages.js:445:21
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.main.captureAndExit (/tools/cli/main.js:279:29)
    at Command.func (/tools/cli/commands-packages.js:441:8)
    at /tools/cli/main.js:1534:15
```

Also, now I can find `jam:method` on atmosphere but its page is empty – it isn't showing the `README` or the Github link.

**Comment by StorytellerCZ** [comment]
Now getting this when running `meteor show jam:method`:
```
Package: jam:method                           
/home/storyteller/.meteor/packages/meteor-tool/.2.13.3.1v0ulsd.ninw++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property 'deprecated' of undefined
    at PackageQuery._displayPackage (/tools/cli/commands-packages-query.js:914:29)
    at PackageQuery.print (/tools/cli/commands-packages-query.js:485:10)
    at Command.func (/tools/cli/commands-packages-query.js:1467:9)
    at /tools/cli/main.js:1534:15
```

**Comment by jamauro** [comment]
Hi @aquinoit, thanks for investigating.

I updated the version and ran `meteor publish` and now I see this error:

```
/Users/jam/.meteor/packages/meteor-tool/.2.13.3.in6tmb.0n3ts++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Found multiple packages matching name: jam:method
    at RemoteCatalog.getPackage (/tools/packaging/catalog/catalog-remote.js:602:13)
    at Object.exports.publishPackage (/tools/packaging/package-client.js:612:39)
    at /tools/cli/commands-packages.js:445:21
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at Object.main.captureAndExit (/tools/cli/main.js:279:29)
    at Command.func (/tools/cli/commands-packages.js:441:8)
    at /tools/cli/main.js:1534:15
```

How should I resolve?

**Comment by jamauro** [comment]
Philippe helped me resolve this issue. Our best guess is something went awry when I originally published and Atmosphere and Accounts happened to be experiencing some availability issues. I wouldn't expect anyone to run into this issue going forward but I believe Philippe removed the packages all together and I had to remove the meteor cli on my machine and reinstall to resolve it.

Thank you Philippe!
