### ISSUE TITLE
Unable to use Meteor.callAsync from async method stub

### ISSUE THREAD

**Issue by zodern** [meteor/meteor#12889]
Reproduction: with Meteor 2.13.3, add this code to both the client and server:

```
Meteor.methods({
  async asyncMethod() {
    await 0
    console.log('async method');
    return 'result';
  },
  async asyncFromAsync() {
    console.log('async from async');
    return Meteor.callAsync('asyncMethod');
  }
});

if (Meteor.isClient) {
  Meteor.callAsync('asyncFromAsync').then(console.log, console.log);
}

```

This errors with:
```
Uncaught (in promise) Error: Called saveOriginals twice without retrieveOriginals
    at LocalCollection.saveOriginals (local_collection.js:338:13)
    at Object.saveOriginals (collection.js:302:26)
    at store.<computed> [as saveOriginals] (livedata_connection.js:312:38)
    at livedata_connection.js:949:13
    at Array.forEach (<anonymous>)
    at Connection._saveOriginals (livedata_connection.js:948:33)
    at Connection.applyAsync (livedata_connection.js:683:14)
    at livedata_connection.js:609:12
    at new Promise (<anonymous>)
    at Connection.callAsync (livedata_connection.js:608:12)
```

It seems the problem might be from https://github.com/meteor/meteor/blob/c9e3551b9673a7ed607f18cb1128563ff49ca96f/packages/ddp-client/common/livedata_connection.js#L606

When it later checks if running in a stub, the CurrentMethodInvocation is undefined, so it thinks it is not inside a simulation:
https://github.com/meteor/meteor/blob/c9e3551b9673a7ed607f18cb1128563ff49ca96f/packages/ddp-client/common/livedata_connection.js#L878

**Comment by AvinRai** [comment]
I'll be working on this!

**Comment by nachocodoner** [comment]
Reproduced. Taking a note for a task in the future.

![image](https://github.com/meteor/meteor/assets/2581993/d64910f0-3653-401f-83a0-1498b8965a8e)

However, it doesn't happen on Meteor 3.0, and as its launch is immediate we may consider delay any only-fix on Meteor 2.0 in favor of the new version.

![image](https://github.com/meteor/meteor/assets/2581993/6602078a-bb95-4da0-b692-4b08fb282dce)

**Comment by AvinRai** [comment]
Sounds good, I'll be working on an issue for Meteor 3.0 instead.
