### ISSUE TITLE
Upgrade to Alpha 18 / 19  fails with error: command failed npm rebuild --update-binary

### ISSUE THREAD

**Issue by jankapunkt** [meteor/meteor#12890]
When updating an existing Meteor 2.x project to Alpha 18 I get the following error:

```shell
$ meteor update --release=3.0-alpha.18


=> Errors while initializing project:                                              
                                              
While extracting standard-minifier-css@1.9.3-alpha300.18...:
error: Command failed: /home/username/.meteor/packages/meteor-tool/.3.0.0-alpha.18.qkhq6g.v8u2m++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild --update-binary
npm ERR! code 1
npm ERR! path /tmp/mt-gq8jmr.6v24c/npm/node_modules/.temp-1k1sf.3aktbv/node_modules/posix
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/tmp/mt-gq8jmr.6v24c/npm/node_modules/.temp-1k1sf.3aktbv/node_modules/posix/build'
npm ERR!   CXX(target) Release/obj.target/posix/src/posix.o
npm ERR! make: Leaving directory '/tmp/mt-gq8jmr.6v24c/npm/node_modules/.temp-1k1sf.3aktbv/node_modules/posix/build'
npm ERR! make: g++: No such file or directory
npm ERR! make: *** [posix.target.mk:113: Release/obj.target/posix/src/posix.o] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/username/.meteor/packages/meteor-tool/.3.0.0-alpha.18.qkhq6g.v8u2m++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Linux 5.15.0-88-generic
npm ERR! gyp ERR! command "/home/username/.meteor/packages/meteor-tool/.3.0.0-alpha.18.qkhq6g.v8u2m++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/username/.meteor/packages/meteor-tool/.3.0.0-alpha.18.qkhq6g.v8u2m++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /tmp/mt-gq8jmr.6v24c/npm/node_modules/.temp-1k1sf.3aktbv/node_modules/posix
npm ERR! gyp ERR! node -v v20.9.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /home/username/.npm/_logs/2023-11-17T08_43_29_479Z-debug-0.log
npm ERR! code 1
npm ERR! path /tmp/mt-gq8jmr.6v24c/npm/node_modules/.temp-1k1sf.3aktbv/node_modules/posix
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/tmp/mt-gq8jmr.6v24c/npm/node_modules/.temp-1k1sf.3aktbv/node_modules/posix/build'
npm ERR!   CXX(target) Release/obj.target/posix/src/posix.o
npm ERR! make: Leaving directory '/tmp/mt-gq8jmr.6v24c/npm/node_modules/.temp-1k1sf.3aktbv/node_modules/posix/build'
npm ERR! make: g++: No such file or directory
npm ERR! make: *** [posix.target.mk:113: Release/obj.target/posix/src/posix.o] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/username/.meteor/packages/meteor-tool/.3.0.0-alpha.18.qkhq6g.v8u2m++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Linux 5.15.0-88-generic
npm ERR! gyp ERR! command "/home/username/.meteor/packages/meteor-tool/.3.0.0-alpha.18.qkhq6g.v8u2m++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/username/.meteor/packages/meteor-tool/.3.0.0-alpha.18.qkhq6g.v8u2m++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /tmp/mt-gq8jmr.6v24c/npm/node_modules/.temp-1k1sf.3aktbv/node_modules/posix
npm ERR! gyp ERR! node -v v20.9.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /home/username/.npm/_logs/2023-11-17T08_43_29_479Z-debug-0.log
```

Reproduction:

- create new Meteor 2.x project `meteor create --blaze` (in my case it was a Blaze project but idk if this is relevant)
- run the project at least once
- then update this project immediately to Alpha 2.18
- the above error shows up

Addtional Info

- OS Ubuntu 22.04 LTS
- Meteor release `2.13.3`
- I also have a global Node and NPM installed
  - node `18.17.1`
  - npm `9.6.7`

**Comment by jankapunkt** [comment]
Same with Alpha 19

**Comment by jankapunkt** [comment]
Weirdly I can't reproduce on my second machine so there must be an issue with my setup.

**Comment by jankapunkt** [comment]
Fix is here: https://github.com/meteor/meteor/issues/12940

**Comment by denihs** [comment]
I'll close this one as it should be fixed now.
