### ISSUE TITLE
[3.0-rc.0]  error on boot.js TypeError: next.runImage.call is not a function

### ISSUE THREAD

**Issue by jankapunkt** [meteor/meteor#13105]
On Ubuntu 22.04 LTS I have upgraded a project ([our tests project in Collection2](https://github.com/Meteor-Community-Packages/meteor-collection2/tree/30e3b904dc3b2e70a4b7d3a2cb424b95759984b5/tests)) to 3.0-rc.0 and I neither can run the project using the `meteor` command nor the tests. I always get

```shell
$ meteor
[[[[[ ~/dev/github/mcp/meteor-collection2/tests ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
I20240422-17:10:55.599(2)? error on boot.js TypeError: next.runImage.call is not a function
I20240422-17:10:55.604(2)?     at processNext (packages/core-runtime.js:127:30)
I20240422-17:10:55.604(2)?     at Object.queue (packages/core-runtime.js:111:3)
I20240422-17:10:55.604(2)?     at packages/meteor-base.js:1:47
I20240422-17:10:55.604(2)?     at /tools/static-assets/server/boot.js:432:36
I20240422-17:10:55.604(2)?     at /tools/static-assets/server/boot.js:503:13
I20240422-17:10:55.604(2)?     at AsyncLocalStorage.run (node:async_hooks:346:14)
I20240422-17:10:55.604(2)?     at /tools/static-assets/server/boot.js:502:37
I20240422-17:10:55.604(2)?     at Function.run (/home/jankapunkt/dev/github/mcp/meteor-collection2/tests/.meteor/local/build/programs/server/tools/tool-env/profile.ts:315:14)
I20240422-17:10:55.604(2)?     at startServerProcess (/tools/static-assets/server/boot.js:501:17)
I20240422-17:10:55.604(2)?     at Object.<anonymous> (/tools/static-assets/server/boot.js:508:2)
I20240422-17:10:55.605(2)? TypeError: next.runImage.call is not a function
I20240422-17:10:55.605(2)?     at processNext (packages/core-runtime.js:127:30)
I20240422-17:10:55.605(2)?     at Object.queue (packages/core-runtime.js:111:3)
I20240422-17:10:55.605(2)?     at packages/meteor-base.js:1:47
I20240422-17:10:55.605(2)?     at /tools/static-assets/server/boot.js:432:36
I20240422-17:10:55.605(2)?     at /tools/static-assets/server/boot.js:503:13
I20240422-17:10:55.605(2)?     at AsyncLocalStorage.run (node:async_hooks:346:14)
I20240422-17:10:55.605(2)?     at /tools/static-assets/server/boot.js:502:37
I20240422-17:10:55.605(2)?     at Function.run (/home/jankapunkt/dev/github/mcp/meteor-collection2/tests/.meteor/local/build/programs/server/tools/tool-env/profile.ts:315:14)
I20240422-17:10:55.605(2)?     at startServerProcess (/tools/static-assets/server/boot.js:501:17)
I20240422-17:10:55.605(2)?     at Object.<anonymous> (/tools/static-assets/server/boot.js:508:2)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by nachocodoner** [comment]
Have you run `rm -rf .meteor/local/bundler-cache` or `rm  -rf .meteor/local` to clear the build cache [after last package loading tweaks](https://github.com/meteor/meteor/pull/13095)?

According to the stack, the project is within `/home/jankapunkt/dev/github/mcp/meteor-collection2/tests/.meteor/local` context.

Let me know, but if this doesn't work, specially as test environment build cache populates on global context as well, could you try to `rm -rf ~/.meteor` and reinstall Meteor?

**Comment by jankapunkt** [comment]
Hey @nachocodoner thank you I forgot to run `meteor reset` as I never used it when updating projects, my bad. It worked after resetting using `meteor reset`. All fine!
