### ISSUE TITLE
Meteor 3: Error: Meteor.userId can only be invoked in method calls or publications with collection helpers

### ISSUE THREAD

**Issue by aboire** [meteor/meteor#13257]
Hello,

I am encountering an issue while updating an application from Meteor 2 to Meteor 3. I use the [collection-helpers](https://github.com/dburles/meteor-collection-helpers/blob/master/collection-helpers.js) package to define helpers on my collections. In these helpers, I use `Meteor.userId()`.

Under Meteor 2, everything worked correctly. However, after updating to Meteor 3, I receive the following error when trying to use `Meteor.userId()` in the helpers, even when they are called within methods or publications:

```
Error: Meteor.userId can only be invoked in method calls or publications.
```

### Steps to Reproduce

1. Update an application from Meteor 2 to Meteor 3.
2. Add helpers to a collection using the [collection-helpers](https://github.com/dburles/meteor-collection-helpers/blob/master/collection-helpers.js) package.
3. In the helpers, use `Meteor.userId()`.
4. Call the helpers within a method or a publication.

### Expected Behavior

`Meteor.userId()` should work correctly in helpers when they are called within methods or publications.

### Actual Behavior

The following error is generated:

```
Error: Meteor.userId can only be invoked in method calls or publications.
```

### Code Snippet

```javascript
import { Meteor } from 'meteor/meteor';
import { Mongo } from 'meteor/mongo';

const MyCollection = new Mongo.Collection('myCollection');

MyCollection.helpers({
  myHelper() {
    return Meteor.userId(); // Causes the error in Meteor 3
  }
});

Meteor.publish('myPublication', function() {
  return MyCollection.find();
});

Meteor.methods({
  async myMethod() {
    const result = await MyCollection.findOneAsync();
    const resultHelper = result.myHelper();
    console.log(resultHelper);
  }
});
```

### Additional Information

- **Meteor version used**: 3.0.1

Thank you for your help.

**Comment by aboire** [comment]
After further consideration, I believe the issue might be related to the publish-composite package. I will investigate this possibility further.

For now, I am closing this issue. I will reopen it or create a new one with more detailed information if needed.

`
I20240728-11:21:51.899(4)? Exception from sub directoryListProjects id bRYqDwF73uysDgDev Error: Meteor.userId can only be invoked in method calls or publications.
I20240728-11:21:51.899(4)?     at AccountsServer.userId (packages/accounts-base/accounts_server.js:124:13)
I20240728-11:21:51.899(4)?     at Object.Meteor.userId (packages/accounts-base/accounts_common.js:437:32)
I20240728-11:21:51.900(4)?     at Document.isAdmin (imports/api/helper/organizations.js:39:41)
I20240728-11:21:51.900(4)?     at Document.listProjectsCreator (imports/api/helper/organizations.js:445:22)
I20240728-11:21:51.900(4)?     at processTicksAndRejections (node:internal/process/task_queues:95:5)
I20240728-11:21:51.900(4)?     at Subscription.find (imports/api/server/publish.js:1341:20)
I20240728-11:21:51.900(4)?     at Publication._getCursor (packages/reywood:publish-composite/lib/publication.js:95:12)
I20240728-11:21:51.900(4)?     at Publication.publish (packages/reywood:publish-composite/lib/publication.js:26:19)
I20240728-11:21:51.900(4)?     at packages/reywood:publish-composite/lib/publication.js:110:7
I20240728-11:21:51.900(4)?     at async Promise.all (index 3)
I20240728-11:21:51.900(4)?     at Publication._publishChildrenOf (packages/reywood:publish-composite/lib/publication.js:106:5)
I20240728-11:21:51.900(4)?     at Publication._handleAddedAsync (packages/reywood:publish-composite/lib/publication.js:77:7)
I20240728-11:21:51.900(4)?     at async Promise.all (index 0)
I20240728-11:21:51.900(4)?     at Publication.awaitPromises (packages/reywood:publish-composite/lib/publication.js:175:5)
I20240728-11:21:51.900(4)?     at async Promise.all (index 0)
I20240728-11:21:51.900(4)?     at Subscription.publish (packages/reywood:publish-composite/lib/publish_composite.js:23:5)
I20240728-11:21:51.900(4)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1210:36)
I20240728-11:21:51.900(4)?     at Session.sub (packages/ddp-server/livedata_server.js:733:7)
`
