### ISSUE TITLE
Build failure on 3.0.2-beta.4 - RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3094623708) is greater than 2 GiB

### ISSUE THREAD

**Issue by wreiske** [meteor/meteor#13276]
Just tried building and got this error:

Debian 12.6

```
bluehive@bluehive-ai:~/bluehiveai$ meteor build ~/build/bluehiveai --directory --server=https://ai.bluehive.com --allow-superuser --architecture os.linux.x86_64 --server-only --verbose
Local package version is up-to-date: allow-deny@2.0.0
Local package version is up-to-date: autoupdate@2.0.0
Local package version is up-to-date: babel-compiler@7.11.0
Local package version is up-to-date: babel-runtime@1.5.2
Local package version is up-to-date: base64@1.0.13
Local package version is up-to-date: binary-heap@1.0.12
Local package version is up-to-date: blaze@3.0.0
Local package version is up-to-date: blaze-hot@2.0.0
Local package version is up-to-date: blaze-html-templates@3.0.0
Local package version is up-to-date: blaze-tools@2.0.0
Local package version is up-to-date: boilerplate-generator@2.0.0
Local package version is up-to-date: caching-compiler@2.0.0
Local package version is up-to-date: caching-html-compiler@2.0.0
Local package version is up-to-date: callback-hook@1.6.0
Local package version is up-to-date: check@1.4.2
Local package version is up-to-date: core-runtime@1.0.0
Local package version is up-to-date: ddp@1.4.2
Local package version is up-to-date: ddp-client@3.0.1-beta302.4
Local package version is up-to-date: ddp-common@1.4.4-beta302.4
Local package version is up-to-date: ddp-server@3.0.1-beta302.4
Local package version is up-to-date: diff-sequence@1.1.3
Local package version is up-to-date: dynamic-import@0.7.4
Local package version is up-to-date: ecmascript@0.16.9
Local package version is up-to-date: ecmascript-runtime@0.8.2
Local package version is up-to-date: ecmascript-runtime-client@0.12.2
Local package version is up-to-date: ecmascript-runtime-server@0.11.1
Local package version is up-to-date: ejson@1.1.4
Local package version is up-to-date: es5-shim@4.8.1
Local package version is up-to-date: facts-base@1.0.2
Local package version is up-to-date: fetch@0.1.5
Local package version is up-to-date: geojson-utils@1.0.12
Local package version is up-to-date: hot-code-push@1.0.5
Local package version is up-to-date: hot-module-replacement@0.5.4
Local package version is up-to-date: html-tools@2.0.0
Local package version is up-to-date: htmljs@2.0.1
Local package version is up-to-date: id-map@1.2.0
Local package version is up-to-date: inter-process-messaging@0.1.2
Local package version is up-to-date: jquery@3.0.0
Local package version is up-to-date: launch-screen@2.0.1
Local package version is up-to-date: leonardoventurini:scss@2.0.0
Local package version is up-to-date: logging@1.3.5
Local package version is up-to-date: meteor@2.0.0
Local package version is up-to-date: meteor-base@1.5.2
Local package version is up-to-date: minifier-css@2.0.0
Local package version is up-to-date: minifier-js@3.0.0
Local package version is up-to-date: minimongo@2.0.1-beta302.4
Local package version is up-to-date: mobile-experience@1.1.2
Local package version is up-to-date: mobile-status-bar@1.1.1
Local package version is up-to-date: modern-browsers@0.1.11
Local package version is up-to-date: modules@0.20.1
Local package version is up-to-date: modules-runtime@0.13.2
Local package version is up-to-date: modules-runtime-hot@0.14.3
Local package version is up-to-date: mongo@2.0.1-beta302.4
Local package version is up-to-date: mongo-decimal@0.1.4-beta300.7
Local package version is up-to-date: mongo-dev-server@1.1.1
Local package version is up-to-date: mongo-id@1.0.9
Local package version is up-to-date: npm-mongo@4.17.4-beta302.4
Local package version is up-to-date: observe-sequence@2.0.0
Local package version is up-to-date: ordered-dict@1.2.0
Local package version is up-to-date: ostrio:flow-router-extra@3.11.0-rc300.1
Local package version is up-to-date: promise@1.0.0
Local package version is up-to-date: random@1.2.2
Local package version is up-to-date: react-fast-refresh@0.2.9
Local package version is up-to-date: reactive-dict@1.3.2
Local package version is up-to-date: reactive-var@1.0.13
Local package version is up-to-date: reload@1.3.2
Local package version is up-to-date: retry@1.1.1
Local package version is up-to-date: routepolicy@1.1.2
Local package version is up-to-date: shell-server@0.6.0
Local package version is up-to-date: socket-stream-client@0.5.3
Local package version is up-to-date: spacebars@2.0.0
Local package version is up-to-date: spacebars-compiler@2.0.0
Local package version is up-to-date: standard-minifier-css@1.9.3
Local package version is up-to-date: standard-minifier-js@3.0.0
Local package version is up-to-date: templating@1.4.4
Local package version is up-to-date: templating-compiler@2.0.0
Local package version is up-to-date: templating-runtime@2.0.0
Local package version is up-to-date: templating-tools@2.0.0
Local package version is up-to-date: tracker@1.3.4
Local package version is up-to-date: typescript@5.4.3
Local package version is up-to-date: underscore@1.6.4
Local package version is up-to-date: webapp@2.0.1-beta302.4
Local package version is up-to-date: webapp-hashing@1.1.2
 > 462k > minifying > 365kt                  /                                   
minifyStdCSS: Total CSS 462k, minified 365k, reduction 21%
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3094623708) is greater than 2 GiB
    at tryCreateBuffer (node:fs:410:13)
    at Object.readFileSync (node:fs:463:14)
    at /storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/files.ts:1520:23
    at wrap.makeCacheKey (/storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:36:15)
    at optimistic (/storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:138:31)
    at /storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:283:17
    at wrap.makeCacheKey (/storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/fs/tools/fs/optimistic.ts:36:15)
    at recomputeNewValue (/storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:198:31)
    at Slot.withValue (/storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at reallyRecompute (/storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:181:19)
    at Entry.recompute (/storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/entry.ts:91:9)
    at optimistic (/storage/home/bluehive/.meteor/packages/meteor-tool/.3.0.2-beta.4.8ogh0b.ypclf++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/src/index.ts:150:25)
    at walk (/tools/isobuild/builder.js:765:24)
    at walk (/tools/isobuild/builder.js:738:17)
    at walk (/tools/isobuild/builder.js:738:11)
    at walk (/tools/isobuild/builder.js:738:11)
    at walk (/tools/isobuild/builder.js:738:11)
    at Builder._copyDirectory (/tools/isobuild/builder.js:792:5)
    at JsImage.write (/tools/isobuild/bundler.js:2577:9)
    at ServerTarget.write (/tools/isobuild/bundler.js:2789:5)
    at /tools/isobuild/bundler.js:2959:23
    at /tools/isobuild/bundler.js:3100:11
    at /tools/isobuild/bundler.js:3469:22
    at Object.capture (/tools/utils/buildmessage.js:282:5)
    at bundle (/tools/isobuild/bundler.js:3274:18)
    at buildCommand (/tools/cli/commands.js:1382:22)
    at /tools/cli/commands.js:1211:18
    at Command.func (/tools/cli/commands.js:1209:10)
    at /tools/cli/main.js:1546:15 {
  code: 'ERR_FS_FILE_TOO_LARGE'
}
```

**Comment by leonardoventurini** [comment]
@wreiske does this happen with previous Meteor 3 releases or only this one?

**Comment by wreiske** [comment]
> @wreiske does this happen with previous Meteor 3 releases or only this one?

to be honest, i'm not sure. I couldn't get my meteor 3 app to run at all with flowrouter without moving to this beta.4 release 🙈

**Comment by leonardoventurini** [comment]
Ok, we'll investigate and let you know if we need any other info

**Comment by nachocodoner** [comment]
Can you provide more details on your setup, such as the Meteor and npm packages you use?

One debugging approach is to incrementally remove content and dependencies from your app and try to rebuild, to see if the issue is related to your dependencies.

Have you tested a minimal version of your app? Does the issue persist as you add more content?

We could assist better with a minimal reproducible example as a repository.

**Comment by wreiske** [comment]
I'll work on getting a simple git repo to reproduce it after work today. 

Here's what I've got currently:
```
  "dependencies": {
    "@babel/runtime": "^7.17.9",
    "@fortawesome/fontawesome-free": "^6.6.0",
    "animate.css": "^4.1.1",
    "bootstrap": "^5.3.3",
    "dompurify": "^3.1.6",
    "jquery": "^3.6.0",
    "luxon": "^3.4.4",
    "marked": "^13.0.3",
    "meteor-node-stubs": "^1.2.1",
    "nodejs-whisper": "^0.1.18",
    "openai": "^4.52.7",
    "wav-encoder": "^1.3.0",
    "ws": "^8.18.0"
  },
```

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.5.2             # Packages every Meteor app needs to have
mobile-experience@1.1.2       # Packages for a great mobile UX
mongo@2.0.1-beta302.4                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
jquery                  # Wrapper package for npm-installed jquery
reactive-var@1.0.13            # Reactive variable for tracker
tracker@1.3.4                 # Meteor's client-side reactive programming library

standard-minifier-css@1.9.3   # CSS minifier run for production mode
standard-minifier-js@3.0.0    # JS minifier run for production mode
es5-shim@4.8.1                # ECMAScript 5 compatibility for older browsers
ecmascript@0.16.9              # Enable ECMAScript2015+ syntax in app code
typescript@5.4.3              # Enable TypeScript syntax in .ts and .tsx modules
shell-server@0.6.0            # Server-side component of the `meteor shell` command



hot-module-replacement@0.5.4  # Update code in development without reloading the page
blaze-hot               # Update files using Blaze's API with HMR

leonardoventurini:scss@2.0.0
ostrio:flow-router-extra@3.11.0-rc300.1
```

```
allow-deny@2.0.0
autoupdate@2.0.0
babel-compiler@7.11.0
babel-runtime@1.5.2
base64@1.0.13
binary-heap@1.0.12
blaze@3.0.0
blaze-hot@2.0.0
blaze-html-templates@3.0.0
blaze-tools@2.0.0
boilerplate-generator@2.0.0
caching-compiler@2.0.0
caching-html-compiler@2.0.0
callback-hook@1.6.0
check@1.4.2
core-runtime@1.0.0
ddp@1.4.2
ddp-client@3.0.1-beta302.4
ddp-common@1.4.4-beta302.4
ddp-server@3.0.1-beta302.4
diff-sequence@1.1.3
dynamic-import@0.7.4
ecmascript@0.16.9
ecmascript-runtime@0.8.2
ecmascript-runtime-client@0.12.2
ecmascript-runtime-server@0.11.1
ejson@1.1.4
es5-shim@4.8.1
facts-base@1.0.2
fetch@0.1.5
geojson-utils@1.0.12
hot-code-push@1.0.5
hot-module-replacement@0.5.4
html-tools@2.0.0
htmljs@2.0.1
id-map@1.2.0
inter-process-messaging@0.1.2
jquery@3.0.0
launch-screen@2.0.1
leonardoventurini:scss@2.0.0
logging@1.3.5
meteor@2.0.0
meteor-base@1.5.2
minifier-css@2.0.0
minifier-js@3.0.0
minimongo@2.0.1-beta302.4
mobile-experience@1.1.2
mobile-status-bar@1.1.1
modern-browsers@0.1.11
modules@0.20.1
modules-runtime@0.13.2
modules-runtime-hot@0.14.3
mongo@2.0.1-beta302.4
mongo-decimal@0.1.4-beta300.7
mongo-dev-server@1.1.1
mongo-id@1.0.9
npm-mongo@4.17.4-beta302.4
observe-sequence@2.0.0
ordered-dict@1.2.0
ostrio:flow-router-extra@3.11.0-rc300.1
promise@1.0.0
random@1.2.2
react-fast-refresh@0.2.9
reactive-dict@1.3.2
reactive-var@1.0.13
reload@1.3.2
retry@1.1.1
routepolicy@1.1.2
shell-server@0.6.0
socket-stream-client@0.5.3
spacebars@2.0.0
spacebars-compiler@2.0.0
standard-minifier-css@1.9.3
standard-minifier-js@3.0.0
templating@1.4.4
templating-compiler@2.0.0
templating-runtime@2.0.0
templating-tools@2.0.0
tracker@1.3.4
typescript@5.4.3
underscore@1.6.4
webapp@2.0.1-beta302.4
webapp-hashing@1.1.2
```

**Comment by wreiske** [comment]
I removed     "nodejs-whisper": "^0.1.18" and    "wav-encoder": "^1.3.0", and it built!!! 

I'm unstuck now! Not sure if you want to look into the bundler code since that single readFileSync can fill up. https://stackoverflow.com/questions/53464755/what-is-the-most-efficient-way-to-read-heavy-files10gb-using-node-jslts/53464795#53464795

I'm happy to close this out if you want. Sorry for the fire drill.

**Comment by nachocodoner** [comment]
Great to hear you found the cause. Now that you're unstuck, is your app still incomplete or malfunctioning after removing "nodejs-whisper" and "wav-encoder"?

I'm unsure what's trying to compile. It might just be some assets in those npm packages that can be ignored and aren't providing any feature in. What exactly did you import from "nodejs-whisper" and "wav-encoder," and how did you import them?
