### ISSUE TITLE
[Meteor 3]: bundle-visualizer is not working with meteor 3

### ISSUE THREAD

**Issue by acemtp** [meteor/meteor#13319]
When running a project with `meteor --extra-packages bundle-visualizer --production`

It first failed on client because `assert` npm package is missing (not in the package dependencies).

When adding the package manually, it then crashs on server:

client log:

```GET http://localhost:3040/__meteor__/bundle-visualizer/stats?cacheBuster=xni646qu0zs 500 (Internal Server Error)```

server log:

```W20240828-10:51:28.140(2)? (STDERR) TypeError: Cannot convert undefined or null to object
W20240828-10:51:28.140(2)? (STDERR)     at Function.keys (<anonymous>)
W20240828-10:51:28.141(2)? (STDERR)     at getStatBundles (packages/bundle-visualizer/server.js:44:17)
W20240828-10:51:28.141(2)? (STDERR)     at statsMiddleware (packages/bundle-visualizer/server.js:116:23)
W20240828-10:51:28.141(2)? (STDERR)     at Layer.handle [as handle_request] (/Users/vialec75/.meteor/packages/webapp/.2.0.1.19wan7x.ok0h++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/express/lib/router/layer.js:95:5)
W20240828-10:51:28.141(2)? (STDERR)     at trim_prefix (/Users/vialec75/.meteor/packages/webapp/.2.0.1.19wan7x.ok0h++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/express/lib/router/index.js:328:13)
W20240828-10:51:28.141(2)? (STDERR)     at /Users/vialec75/.meteor/packages/webapp/.2.0.1.19wan7x.ok0h++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/express/lib/router/index.js:286:9
W20240828-10:51:28.141(2)? (STDERR)     at Function.process_params (/Users/vialec75/.meteor/packages/webapp/.2.0.1.19wan7x.ok0h++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/express/lib/router/index.js:346:12)
W20240828-10:51:28.141(2)? (STDERR)     at next (/Users/vialec75/.meteor/packages/webapp/.2.0.1.19wan7x.ok0h++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/express/lib/router/index.js:280:10)
W20240828-10:51:28.141(2)? (STDERR)     at packages/sakod:core/sk-route.server.js:50:5
W20240828-10:51:28.141(2)? (STDERR)     at zalgoSafe (/Users/vialec75/sakod/copost/meteor/.meteor/local/isopacks/sakod_core/npm/node_modules/dezalgo/dezalgo.js:20:10)
W20240828-10:51:28.141(2)? (STDERR)     at f (/Users/vialec75/sakod/copost/meteor/.meteor/local/isopacks/sakod_core/npm/node_modules/once/once.js:25:25)
W20240828-10:51:28.141(2)? (STDERR)     at IncomingForm.<anonymous> (/Users/vialec75/sakod/copost/meteor/.meteor/local/isopacks/sakod_core/npm/node_modules/formidable/dist/index.cjs:1210:7)
W20240828-10:51:28.141(2)? (STDERR)     at IncomingForm.emit (node:events:519:28)
W20240828-10:51:28.141(2)? (STDERR)     at IncomingForm.emit (node:domain:488:12)
W20240828-10:51:28.141(2)? (STDERR)     at IncomingForm._maybeEnd (/Users/vialec75/sakod/copost/meteor/.meteor/local/isopacks/sakod_core/npm/node_modules/formidable/dist/index.cjs:1661:10)
W20240828-10:51:28.141(2)? (STDERR)     at DummyParser._flush (/Users/vialec75/sakod/copost/meteor/.meteor/local/isopacks/sakod_core/npm/node_modules/formidable/dist/index.cjs:993:23)```

**Comment by jankapunkt** [comment]
It should be `node:assert` instead of `assert` to avoid namespace conflict between nodejs core packages and npm packages.

Node assert: https://nodejs.org/api/assert.html
NPM assert: https://www.npmjs.com/package/assert

PR: https://github.com/meteor/meteor/pull/13390

**Comment by jankapunkt** [comment]
Okay I missed the fact that using `node:assert` should not be necessary since `meteor-node-stubs` should take care of making this available on the client. Let me investigate a bit more here.

Edit: what's your Meteor release and which version of `meteor-node-stubs` do you have installed?

**Comment by acemtp** [comment]
it was Meteor 3.0.2

**Comment by jankapunkt** [comment]
I just run the bundle visualizer [in this 3.0.2 repo](https://github.com/blazeui/starter) and it ran without issues:

Browser:

![image](https://github.com/user-attachments/assets/c5a3b1dd-f78a-404d-9e13-6fd11827aa44)

Terminal:

```shell
$ meteor npm run visualize

> visualize
> meteor --production --extra-packages bundle-visualizer

Warning: The --production flag should only be used to simulate production bundling for testing purposes. Use meteor build to create a bundle for production deployment. See: https://guide.meteor.com/deployment.html
[[[[[ ~/dev/github/blazeui/starter ]]]]]      

=> Started proxy.                             
                                              
Changes to your project's package version selections:
                                              
bundle-visualizer  added, version 1.2.5       

=> Meteor 3.0.3 is available. Check the changelog https://docs.meteor.com/changelog.html and update this project with 'meteor update'.
=> Started MongoDB.                           
W20241007-10:33:12.147(2)? (STDERR) => The "bundle-visualizer" package is currently enabled. Visit your application in a web browser to view the client bundle analysis and 'meteor remove' the package before building/deploying the final bundle.
=> Started your app.

=> App running at: http://localhost:3000/
```


You can reproduce this via

```shell
$ git clone git@github.com:blazeui/starter.git
$ cd starter
$ meteor npm install
$ meteor npm run visualize
```

Its using `"meteor-node-stubs": "^1.2.7"`, can you confirm you have this version installed?

**Comment by acemtp** [comment]
I retried and it works now, perhaps it was during 3.0.0 rc time.

Thanks for your help
