### ISSUE TITLE
Using Meteor 1.9.2 version and the compatible node version but facing the below error. Cant update meteor as my application is running on 1.9.2 version

### ISSUE THREAD

**Issue by Deepak2851** [meteor/meteor#13360]
C:\Users\<Username>>meteor create meteorapp
C:\Users\<Username>\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

TypeError: semver is not a constructor
    at Function.PV.compare (C:\Users\<Username>\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:215:26)
    at C:\tools\packaging\catalog\catalog-remote.js:581:28
    at Array.sort (<anonymous>)
    at RemoteCatalog.getSortedVersionRecords (C:\tools\packaging\catalog\catalog-remote.js:580:20)
    at LayeredCatalog._returnFirst (C:\tools\packaging\catalog\catalog.js:190:12)
    at LayeredCatalog.getSortedVersionRecords (C:\tools\packaging\catalog\catalog.js:202:17)
    at CS.CatalogLoader._getSortedVersionRecords (packages/constraint-solver.js:333:20)
    at CS.CatalogLoader.loadAllVersions (packages/constraint-solver.js:362:26)
    at CS.CatalogLoader.loadAllVersionsRecursive (packages/constraint-solver.js:395:10)
    at CS.Input.loadFromCatalog (packages/constraint-solver.js:562:17)
    at packages/constraint-solver.js:2285:15
    at Function.time (C:\Users\<Username>\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:284:12)
    at CS.PackagesResolver.resolve (packages/constraint-solver.js:2282:13)
    at C:\tools\project-context.js:561:35
    at Function.time (C:\Users\<Username>\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:284:12)
    at C:\tools\project-context.js:557:19
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at C:\tools\project-context.js:529:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._resolveConstraints (C:\tools\project-context.js:528:13)
    at C:\tools\project-context.js:300:9
    at Object.enterJob (C:\tools\utils\buildmessage.js:388:12)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:290:18)
    at C:\tools\project-context.js:282:12
    at Function.run (C:\Users\<Username>\AppData\Local\.meteor\packages\meteor-tool\1.9.2\mt-os.windows.x86_64\tools\tool-env\tools\tool-env\profile.ts:289:14)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:281:13)
    at C:\tools\cli\commands.js:817:20
    at Object.capture (C:\tools\utils\buildmessage.js:283:5)
    at Object.main.captureAndExit (C:\tools\cli\main.js:275:29)
    at Command.func (C:\tools\cli\commands.js:791:8)
    at C:\tools\cli\main.js:1528:15

**Comment by denihs** [comment]
Could you try the same thing proposed here? https://forums.meteor.com/t/solved-windows-meteor-create-fails-semver-is-not-a-constructor/54195

**Comment by Deepak2851** [comment]
Thanks a ton for your support!!! 
My issue is now resolved.

Also, I am curious to know how that folder being in a different path, affecting my application ?

**Comment by denihs** [comment]
I believe it has to do with the way Node.js resolves dependencies. It follows a hierarchy from top to bottom, and those dependencies were at the top, so it could solve the ones for Meteor.

But I'm glad this helped you!

I'm closing this now.
