### ISSUE TITLE
Meteor 3.0.3 Fails to publish package with --update flag

### ISSUE THREAD

**Issue by filipenevola** [meteor/meteor#13398]
I was trying to just update the metadata of quave:synced-cron but got this error:

``` 
synced-cron git:(main) ✗ meteor publish --update
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Promise
    at Object.statSync (node:fs:1664:10)
    at Object.stat (/Users/filipe/.meteor/packages/meteor-tool/.3.0.3.q60237.sdn3++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/tools/fs/tools/fs/files.ts:1520:23)
    at uploadFile (/tools/packaging/package-client.js:330:20)
    at /tools/packaging/package-client.js:546:16
    at Object.enterJob (/tools/utils/buildmessage.js:387:12)
    at Object.exports.updatePackageMetadata (/tools/packaging/package-client.js:539:3)
    at /tools/cli/commands-packages.js:208:9
    at Object.capture (/tools/utils/buildmessage.js:282:5)
    at Object.main.captureAndExit (/tools/cli/main.js:273:16)
    at updatePackageMetadata (/tools/cli/commands-packages.js:204:5)
    at Command.func (/tools/cli/commands-packages.js:358:12)
    at /tools/cli/main.js:1546:15 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I didn't check the code in Meteor failing but it should be a simple fix.

**Comment by filipenevola** [comment]
BTW, regular publishes are working fine:

```
➜  synced-cron git:(main) ✗ meteor publish         
Published quave:synced-cron@2.1.0.  
```

**Comment by StorytellerCZ** [comment]
This seems to be duplicate of #13394
