### ISSUE TITLE
[Cordova] Mongo Error: Topology is closed

### ISSUE THREAD

**Issue by StorytellerCZ** [meteor/meteor#13410]
Meteor: 3.0.4-beta.0

When I tried to run Cordova Android today I got the following error:
```
W20241011-15:18:22.859(2)? (STDERR) MongoTopologyClosedError: Topology is closed
W20241011-15:18:22.869(2)? (STDERR)     at /home/storyteller/.meteor/packages/npm-mongo/.4.17.4.753zsa.d3xfg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/src/sdam/topology.ts:515:42 {
W20241011-15:18:22.869(2)? (STDERR)   [Symbol(errorLabels)]: Set(0) {}
W20241011-15:18:22.869(2)? (STDERR) }         
W20241011-15:18:22.869(2)? (STDERR) MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
W20241011-15:18:22.870(2)? (STDERR)     at Timeout._onTimeout (/home/storyteller/.meteor/packages/npm-mongo/.4.17.4.753zsa.d3xfg++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/src/sdam/topology.ts:591:30)
W20241011-15:18:22.870(2)? (STDERR)     at listOnTimeout (node:internal/timers:581:17)
W20241011-15:18:22.870(2)? (STDERR)     at processTimers (node:internal/timers:519:7) {
W20241011-15:18:22.870(2)? (STDERR)   reason: TopologyDescription {
W20241011-15:18:22.870(2)? (STDERR)     type: 'Unknown',
W20241011-15:18:22.870(2)? (STDERR)     servers: Map(1) { 'localhost:27017' => [ServerDescription] },
W20241011-15:18:22.871(2)? (STDERR)     stale: false,
W20241011-15:18:22.871(2)? (STDERR)     compatible: true,
W20241011-15:18:22.871(2)? (STDERR)     heartbeatFrequencyMS: 10000,
W20241011-15:18:22.871(2)? (STDERR)     localThresholdMS: 15,
W20241011-15:18:22.871(2)? (STDERR)     setName: null,
W20241011-15:18:22.872(2)? (STDERR)     maxElectionId: null,
W20241011-15:18:22.872(2)? (STDERR)     maxSetVersion: null,
W20241011-15:18:22.872(2)? (STDERR)     commonWireVersion: 0,
W20241011-15:18:22.872(2)? (STDERR)     logicalSessionTimeoutMinutes: null
W20241011-15:18:22.872(2)? (STDERR)   },      
W20241011-15:18:22.872(2)? (STDERR)   code: undefined,
W20241011-15:18:22.872(2)? (STDERR)   [Symbol(errorLabels)]: Set(0) {}
W20241011-15:18:22.872(2)? (STDERR) }         
W20241011-15:18:22.872(2)? (STDERR)           
W20241011-15:18:22.873(2)? (STDERR) packages/core-runtime.js:189
W20241011-15:18:22.873(2)? (STDERR)             throw error;
W20241011-15:18:22.873(2)? (STDERR)             ^
W20241011-15:18:22.906(2)? (STDERR) errorClass [Error]: [An error occurred when creating an index for collection "users: Topology is closed]
W20241011-15:18:22.907(2)? (STDERR)     at Collection.createIndexAsync (packages/mongo/collection.js:1140:15)
W20241011-15:18:22.907(2)? (STDERR)     at module.wrapAsync.self (packages/accounts-password/password_server.js:1107:1) {
W20241011-15:18:22.907(2)? (STDERR)   isClientSafe: true,
W20241011-15:18:22.907(2)? (STDERR)   error: 'An error occurred when creating an index for collection "users: Topology is closed',
W20241011-15:18:22.907(2)? (STDERR)   reason: undefined,
W20241011-15:18:22.907(2)? (STDERR)   details: undefined,
W20241011-15:18:22.907(2)? (STDERR)   errorType: 'Meteor.Error'
W20241011-15:18:22.907(2)? (STDERR) }         
W20241011-15:18:22.907(2)? (STDERR)           
W20241011-15:18:22.908(2)? (STDERR) Node.js v20.18.0
```

Starting then the on device or in emulator keeps on spinning forever.

**Comment by italojs** [comment]
Is it still relevant @StorytellerCZ ?
