### ISSUE TITLE
3.0.4 - Npm package devlop breaks app - Module not found - Support of exports in package.json

### ISSUE THREAD

**Issue by vparpoil** [meteor/meteor#13436]
Here is a repro repo : 
https://github.com/vparpoil/meteor-devlop-bug

Steps to reproduce : 
```bash
meteor create --react meteorDevlop
cd meteorDevlop
meteor npm install --save devlop
```

add this in client/main.jsx 
```javascript
import { deprecate, ok } from "devlop";
var c = deprecate;
```

App breaks with the following error in client console
```
Uncaught Error: Cannot find module 'devlop'
    at makeMissingError (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:232:12)
    at Module.resolve (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:247:17)
    at Module.moduleLink [as link] (modules.js?hash=4b1808092a5a19c8b57845dde04c4a786e6113c9:349:25)
    at app.js?hash=29a0a12e54b02747db3b1e35e18b35c6c59a27bb:194:11
    at module (main.jsx:12:3)
    at fileEvaluate (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:386:7)
    at Module.require (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:268:27)
    at mod.require (modules.js?hash=4b1808092a5a19c8b57845dde04c4a786e6113c9:284:33)
    at require (modules-runtime-hot.js?hash=740f2079be9cde2bf010e27ef9713c36c6491a66:308:21)
    at app.js?hash=29a0a12e54b02747db3b1e35e18b35c6c59a27bb:224:1
```

This appeared while wanting to use `remark`, `remark-gfm` and `remark-parse`, depending on `unified`, which depends on `devlop`

This is related to the following issue : https://github.com/wooorm/devlop/issues/1
> The package.json omits `main` in favor of `exports`

Seems also related to https://github.com/meteor/meteor/discussions/11727

Can meteor support Npm package.json which use `exports` and not `main`? 

Form[ Node documentation](https://nodejs.org/api/packages.html#exports), the use of exports is legit 
> The "exports" field allows defining the [entry points](https://nodejs.org/api/packages.html#package-entry-points) of a package when imported by name loaded either via a node_modules lookup or a [self-reference](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name) to its own name. It is supported in Node.js 12+ as an alternative to the ["main"](https://nodejs.org/api/packages.html#main) that can support defining [subpath exports](https://nodejs.org/api/packages.html#subpath-exports) and [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) while encapsulating internal unexported modules.

**Comment by leonardoventurini** [comment]
Yes, `exports` support is in our roadmap. Thanks!

**Comment by vparpoil** [comment]
Hi @leonardoventurini thanks for the update. Can you share on which release we should expect this to land ? 
Thanks

**Comment by StorytellerCZ** [comment]
See #11727
It probably won't be in v3.1

**Comment by vparpoil** [comment]
Hi Everyone, 
Can this issue be prioritised for a future release ? (maybe the next one ?) 
This is blocking more and more NPM dependencies : 
https://forums.meteor.com/t/when-can-we-expect-meteor-3-0-to-support-svelte-5/62596/7

**Comment by vparpoil** [comment]
Referencing the PR that will fix this issue here : https://github.com/meteor/meteor/pull/13520

**Comment by nachocodoner** [comment]
That PR is definitely worth it, though there’s still work to do before merging, including several regressions in the tool's test coverage. Hopefully, it can move forward and be added soon in a future minor version.

**Comment by rtrevisanlectra** [comment]
Hello, same issue with react-markdow that uses devlop. Also I can't use markdown-to-jsx with Meteor 3.3 as it causes a syntax error during transpilation....

**Comment by Vetnametz** [comment]
Hi, looks like I have same problem.

I am wiling to use [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk)
After `npm i matrix-js-sdk@39.4.0 --save-exact` and using it in `server/main.ts` like this: 
```
import * as sdk from "matrix-js-sdk";
const client = sdk.createClient({ baseUrl: "https://matrix.org" });
```
on server restart I am getting this error.



```
packages/core-runtime.js:189
            throw error;
            ^

Error: Cannot find module 'uuid'
    at makeMissingError (packages/modules-runtime.js:221:12)
    at Module.require (packages/modules-runtime.js:240:17)
    at Module.mod.require (/Users/../.meteor/packages/modules/.0.20.3.q6uew9xqars++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
    at Module.moduleLink [as link] (/Users/../.meteor/packages/modules/.0.20.3.q6uew9xqars++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:102:22)
    at module (packages/modules.js:61527:656)
    at fileEvaluate (packages/modules-runtime.js:335:7)
    at Module.require (packages/modules-runtime.js:237:14)
    at Module.mod.require (/Users/../.meteor/packages/modules/.0.20.3.q6uew9xqars++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
    at Module.moduleLink [as link] (/Users/../.meteor/packages/modules/.0.20.3.q6uew9xqars++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:102:22)
    at module (packages/modules.js:49893:1652)
    at fileEvaluate (packages/modules-runtime.js:335:7)
    at Module.require (packages/modules-runtime.js:237:14)
    at Module.mod.require (/Users/../.meteor/packages/modules/.0.20.3.q6uew9xqars++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
    at Module.moduleLink [as link] (/Users/../.meteor/packages/modules/.0.20.3.q6uew9xqars++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:102:22)
    at module (packages/modules.js:39739:656)
    at fileEvaluate (packages/modules-runtime.js:335:7)
    at Module.require (packages/modules-runtime.js:237:14)
    at Module.mod.require (/Users/../.meteor/packages/modules/.0.20.3.q6uew9xqars++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
    at Module.moduleLink [as link] (/Users/../.meteor/packages/modules/.0.20.3.q6uew9xqars++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:102:22)
    at module (packages/modules.js:38128:1173)
    at fileEvaluate (packages/modules-runtime.js:335:7)
    at Module.require (packages/modules-runtime.js:237:14)

Node.js v22.21.1
```

**Comment by StorytellerCZ** [comment]
@Vetnametz can you try with the new build tool in Meteor v3.4 rc?

**Comment by Vetnametz** [comment]
> [@Vetnametz](https://github.com/Vetnametz) can you try with the new build tool in Meteor v3.4 rc?

I did with 3.4-rc.2, same error.

**Comment by nachocodoner** [comment]
@Vetnametz: Did you properly add the rspack Atmosphere package and [configure Rspack as described in the docs](https://docs.meteor.com/about/modern-build-stack/rspack-bundler-integration.html)?

I tested a small app with Rspack and got a weird issue. That npm package behaves oddly ([matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk?rgh-link-date=2025-12-26T08%3A27%3A13.000Z)), and it even requires yarn. I still could not get it to work.

I will keep this issue open to investigate your use case.

@vparpoil: The reproduction repository you provided, including the `devlop` npm dependency, passed the test. With Rspack it can be imported correctly and still integrates with Meteor specifics.

**Comment by vparpoil** [comment]
Thanks a lot, I hope if this unlocks our integration of `remark` 🚀  
Unfortunately I don't know yet when we get time to look into this
~Should I close this issue since the reproduction repo passes the test?~  (just properly read your comment, leaving this open)

**Comment by italojs** [comment]
@vparpoil you can let is open until you test it or someone test it

**Comment by nachocodoner** [comment]
I will leave this open. While the main issue was solved, [another report came later](https://github.com/meteor/meteor/issues/13436#issuecomment-3692468104) that seems close to the same issue. I'd like to confirm that one next. If it turns out to be a different problem, I will address it in 3.4.1.
