### ISSUE TITLE
Accounts.createUserAsync issues on Meteor 3.0.4

### ISSUE THREAD

**Issue by wreiske** [meteor/meteor#13435]
I'm working on porting more meteor 2 projects to meteor 3.0.4 today. This little bit of code is never finishing the Accounts.createUserAsync.

```
            console.log('before await Accounts.createUserAsync')
            userId = await Accounts.createUserAsync({
                email: payload.email,
                profile: userTemp.profile,
            });
            console.log('after await Accounts.createUserAsync', userId);
```

```
console.log('before await Accounts.createUserAsync')
// output createUserAsync function as a string so we can see what it's doing
console.log(Accounts.createUserAsync.toString());

I20241029-11:43:49.577(-7)? before await Accounts.createUserAsync
I20241029-11:43:49.577(-7)? async (options, callback) => {
I20241029-11:43:49.577(-7)?       options = _objectSpread({}, options);
I20241029-11:43:49.578(-7)?
I20241029-11:43:49.578(-7)?       // XXX allow an optional callback?
I20241029-11:43:49.578(-7)?       if (callback) {
I20241029-11:43:49.578(-7)?         throw new Error("Accounts.createUser with callback not supported on the server yet.");
I20241029-11:43:49.578(-7)?       }
I20241029-11:43:49.579(-7)?       return createUser(options);
I20241029-11:43:49.579(-7)?     }
```

```
meteor update --all-packages
This project is already at Meteor 3.0.4, the latest release.

Changes to your project's package version selections from updating package versions:

aldeed:simple-schema*  upgraded from 1.13.1 to 2.0.0


* These packages have been updated to new versions that are not backwards
compatible.

The following top-level dependencies were not updated to the very latest version available:
 * mizzao:timesync 0.5.5 (0.6.0 is available)
 * tmeasday:publish-counts 0.2.1 (0.8.0 is available)

Newer versions of the following indirect dependencies are available:
 * http 1.4.4 (2.0.0 is available)
 * raix:eventemitter 1.0.0 (2.0.0 is available)
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.
If the packages do not upgrade after this, this could mean
that there is a newer version of Meteor which the package
requires, but it not yet recommended or that some package
dependencies are not up to date and don't allow you to get
the latest package version.
```

My project is using accounts-password@3.0.2 which shows as latest here https://github.com/meteor/meteor/blob/devel/packages/accounts-password/package.js#L8

```
            console.log('before await Accounts.createUser');


            try {
                let userId = await Accounts.createUserAsync({
                    email: payload.email,
                    profile: userTemp.profile,
                })
            } catch (error) {
                console.error('!!! Error creating user', error);
            }


            console.log('after await Accounts.createUserAsync', userId);
```

```
I20241029-12:10:26.165(-7)? before await Accounts.createUser
W20241029-12:10:26.213(-7)? (STDERR) !!! Error creating user errorClass [Error]: Something went wrong. Please check your credentials. [403]
W20241029-12:10:26.214(-7)? (STDERR)     at AccountsServer._handleError (packages/accounts-base/accounts_server.js:1523:19)
W20241029-12:10:26.214(-7)? (STDERR)     at AccountsServer._checkForCaseInsensitiveDuplicates (packages/accounts-base/accounts_server.js:1491:14)
W20241029-12:10:26.215(-7)? (STDERR)     at processTicksAndRejections (node:internal/process/task_queues:95:5)
W20241029-12:10:26.215(-7)? (STDERR)     at AccountsServer._createUserCheckingDuplicates (packages/accounts-base/accounts_server.js:1505:5)
W20241029-12:10:26.216(-7)? (STDERR)     at createUser (packages/accounts-password/password_server.js:996:12)
W20241029-12:10:26.216(-7)? (STDERR)     at MethodInvocation.Login.withGoogle (api/users/server/methods.js:132:30) {   
W20241029-12:10:26.216(-7)? (STDERR)   isClientSafe: true,
W20241029-12:10:26.217(-7)? (STDERR)   error: 403,
W20241029-12:10:26.217(-7)? (STDERR)   reason: 'Something went wrong. Please check your credentials.',
W20241029-12:10:26.217(-7)? (STDERR)   details: undefined,
W20241029-12:10:26.217(-7)? (STDERR)   errorType: 'Meteor.Error'
W20241029-12:10:26.218(-7)? (STDERR) }
I20241029-12:10:26.218(-7)? after await Accounts.createUserAsync undefined
W20241029-12:10:26.219(-7)? (STDERR) Error creating user. (ErrorID: oGc34)
```

**Comment by leonardoventurini** [comment]
We'll take a look, thanks!

**Comment by leonardoventurini** [comment]
@wreiske I believe it's omitting the real reason for the failure, the user is already registered, if you check the line numbers in the trace it matches exactly here:

<img width="565" alt="image" src="https://github.com/user-attachments/assets/60aed378-6772-4485-bf9e-2f2e2a49cd6f">

**Comment by leonardoventurini** [comment]
After this PR https://github.com/meteor/meteor/pull/13277, you need to set `ambiguousErrorMessages` to false (in development only) to see the actual errors.

<img width="541" alt="image" src="https://github.com/user-attachments/assets/e0ae7503-0d3b-47f8-a3b5-078be27eddf3">

**Comment by leonardoventurini** [comment]
Added a test here just in case:

https://github.com/meteor/meteor/pull/13437

**Comment by wreiske** [comment]
That was it. Wow. Huge face palm from my side. Order of operations issue while migrating this over to Meteor 3.0 I missed updating the user async with the id from google login, and my code checked when registering a new user with google based on that id. 

I appreciate you looking into this for me. Apologies for the fire drill, but also good to know about ambiguousErrorMessages ! Also happy to see a new test case :)

**Comment by leonardoventurini** [comment]
Great! Glad to be of help :)
