### ISSUE TITLE
Send password recovery email fails

### ISSUE THREAD

**Issue by wackazong** [meteor/meteor#1346]
Email sending works fine otherwise. But for password recovery emails I get this upon calling Accounts.forgotPassword():

Exception while invoking method 'forgotPassword' DeliveryError: Message delivery failed
    at Object.Future.wait (/root/willmit/programs/server/node_modules/fibers/future.js:326:15)
    at smtpSend (packages/email/email.js:82)
    at Object.Email.send (packages/email/email.js:144)
    at Object.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:244)
    at Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:215)
    at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1358)
    at packages/livedata/livedata_server.js:606
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:31)
    at packages/livedata/livedata_server.js:605
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:31)
    - - - - -
    at SMTPConnectionPool._onConnectionReady (/root/willmit/programs/server/npm/email/main/node_modules/simplesmtp/lib/pool.js:261:21)
    at SMTPClient.EventEmitter.emit (events.js:98:17)
    at SMTPClient._actionStream (/root/willmit/programs/server/npm/email/main/node_modules/simplesmtp/lib/client.js:824:14)
    at SMTPClient._onData (/root/willmit/programs/server/npm/email/main/node_modules/simplesmtp/lib/client.js:252:29)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:738:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at _stream_readable.js:401:7
    at process._tickCallback (node.js:415:13)

**Comment by AnvarTurobov** [comment]
Hi @wackazong, could you please elaborate on your answer, I'm having similar issue- went through tons of solutions, so far couldn't get it working.

**Comment by wackazong** [comment]
The from address I was using was not registered for sending emails with my email provider (amazon SES).
