### ISSUE TITLE
Meteor v3.1, `util._extend` API is deprecated

### ISSUE THREAD

**Issue by minhna** [meteor/meteor#13491]
The warning shows when `webapp` serves the first request.
To show the full warning, we need to use `TOOL_NODE_FLAGS=--trace-warnings` environment  variable.

```
(node:2181344) Warning: The `util._extend` API is deprecated. Please use Object.assign() instead.
    at node:internal/util:116:11
    at deprecated (node:internal/util:163:7)
    at ProxyServer.<anonymous> (/home/minhna/.meteor/packages/meteor-tool/.3.1.0.irpbm0.oxkl++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/index.js:50:26)
    at /tools/runners/run-proxy.js:214:41
    at attempt (/tools/runners/run-proxy.js:194:16)
    at Proxy._tryHandleConnections (/tools/runners/run-proxy.js:214:9)
    at Server.<anonymous> (/tools/runners/run-proxy.js:56:12)
    at Server.emit (node:events:518:28)
    at parserOnIncoming (node:_http_server:1150:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
```

**permb** in forum said `The warning indicates that there’s an old version of http-proxy in meteor’s bootstrap dev-bundle` 
https://forums.meteor.com/t/meteor-v3-1-provide-node-options/62615/5?u=minhna
I'm not sure.

- Version Meteor 3.1
- The operation system: Linux Ubuntu 24.04

**Comment by StorytellerCZ** [comment]
Got this as well, but did not have a chance to investigate yet. Recently most of the dependencies were upgraded so it is strange that this would be the issue, but we can't rule this out.

**Comment by StorytellerCZ** [comment]
Maybe #13323 could solve it. Anyhow I will look into this while I'm working on that issue.

**Comment by lc3t35** [comment]
Maybe here is the solution : https://github.com/http-party/node-http-proxy/issues/1674 

http-proxy is used here : https://github.com/meteor/meteor/blob/a03b2d22ad0606820b5b62322b57d81b772a70ea/scripts/dev-bundle-tool-package.js#L46

**Comment by StorytellerCZ** [comment]
@lc3t35 good find! We might need to look for an alternative to `http-proxy` as that one has not been updated for years.

**Comment by nachocodoner** [comment]
Thank you for the catch of this annoying message.

We can either replace this library with a compatible alternative or fork the fixed version and include it in our dev_bundle. We will asset any of this for next versions.

Does you know any alternative?

**Comment by lc3t35** [comment]
https://www.npmjs.com/package/express-http-proxy ?

**Comment by StorytellerCZ** [comment]
@nachocodoner I think we should look at the express-http-proxy as an alternative. That one should integrate more into Express itself, but it won't be a drop-in replacement.
I think one extra thing here in the replacement we should also look at is if there is anything that can also provide SSL easily (if that is anywhere in the competency here, probably not though, but worth a look).

**Comment by nachocodoner** [comment]
Yes, I don't think the replacement will be easy since Express is used only for the Webapp/Meteor runtime, not the tool itself. To avoid an annoying message and save work, I would prefer the fork approach. It’s better to focus our efforts on other tasks.

**Comment by demangejeremy** [comment]
I just proposed a PR to correct this :)

**Comment by katerberg** [comment]
Still seems relevant

**Comment by vlasky** [comment]
Yep, I saw this when running my app under Meteor 3.2.2.

**Comment by StorytellerCZ** [comment]
Confirmed on 3.3 as well.

**Comment by xet7** [comment]
Confirmed on 3.3.1 as well.

**Comment by StorytellerCZ** [comment]
I believe this is our solution: https://www.npmjs.com/package/http-proxy-3

**Comment by manueltimita** [comment]
> I believe this is our solution: https://www.npmjs.com/package/http-proxy-3

A-ha! I have to try this one. I've been relying on `http-proxy-node16` all this time because of the godawful leaks in the original `http-proxy`. Speaking of which, I observed that, if I have a `proxy.web()` call in Meteor in some handler which I then pass to `WebApp.rawHandlers.use()` the leaks still happen, and now I understand why - Meteor uses the same buggy version of `http-proxy` underneath, and our proxied requests go through it regardless. 

Funny business. I used to have those gradual memory increases as many have reported on the Meteor Forums; so, to mitigate the problem, I create a separate Express app as `const app = WebApp.express();`, pass the proxy handler to it, then proxy all the outside requests that are supposed to go to `http-proxy-node16` to the Express app port via our reverse NGINX (while in development I do a crude 307 redirect to it). Can't wait until Meteor replaces the old `http-proxy`. Count me in for testing. I am very eager to get rid of all the Express + NGINX voodoo above.

EDIT: If anyone hits this issue, they have lots of requests being proxied, and they are suspecting memory leaks due to `http-proxy`, it could likely be this issue: https://github.com/http-party/node-http-proxy/issues/1586. I noticed in those cases that `CLOSE_WAIT` socket connections seem to be piling up until the memory explodes or the Meteor HTTP server simply stops accepting any requests. Diagnostics in Linux:
```
lsof -i -n -P | grep node
watch -n 1 "netstat -n | grep CLOSE_WAIT | wc -l"
```

EDIT 2: The memory leaks caused by `http-proxy` become apparent when the handler passed to it is an `async` function, which is why I suspect the memory leak reports have increased since Meteor v3.

**Comment by StorytellerCZ** [comment]
@manueltimita yes, we have a PR for this #13916 that I hope to get into Meteor 3.4.

**Comment by manueltimita** [comment]
> [@manueltimita](https://github.com/manueltimita) yes, we have a PR for this [#13916](https://github.com/meteor/meteor/pull/13916) that I hope to get into Meteor 3.4.

This is really good news! Thanks for this :)

**Comment by juanpmd** [comment]
This warning message is still present in Meteor 3.5 (Official release).

**Comment by nachocodoner** [comment]
This was fixed by updating the outdated `http-proxy` dependency that was triggering the deprecated `util._extend` warning.

Available in Meteor 3.5.1:

`meteor update --release 3.5.1`

Closing this as resolved.
