### ISSUE TITLE
ROOT_URL confusing error message

### ISSUE THREAD

**Issue by paralin** [meteor/meteor#1404]
I'm getting this error when trying to start a bundled app:

`2013-09-06T16:47:11.103046+00:00 app[web.1]: }).run();
2013-09-06T16:47:11.130650+00:00 app[web.1]: Error: a route URL prefix must begin with a slash
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at _.extend.declare (packages/routepolicy/routepolicy.js:95)
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at new StreamServer (packages/livedata/stream_server.js:23)
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at new Server (packages/livedata/livedata_server.js:1029)
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at Package (packages/livedata/server_convenience.js:10)
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at mains (/app/.meteor/heroku_build/app/programs/server/boot.js:153:10)
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at packages/livedata.js:3907:4
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at packages/livedata.js:3918:3
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at Array.forEach (native)
2013-09-06T16:47:11.130650+00:00 app[web.1]:     at Function._.each._.forEach (/app/.meteor/heroku_build/app/programs/server/node_modules/underscore/underscore.js:79:11)
2013-09-06T16:47:11.130849+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:80:5`

What is the issue?

**Comment by QHose** [comment]
ok, somehow this does not work anymore...

**Comment by polonski** [comment]
yup setting it to the tld with no https:// or http:// doesn't work, still getting the same error
