### ISSUE TITLE
WARNING Error: No primary found in set 

### ISSUE THREAD

**Issue by awatson1978** [meteor/meteor#1422]
Hi there!
Got a Replica Set error this morning with our teleconferencing application!  :)
http://vonvo-opentok-demo.meteor.com/

Application was working fine last night, but this morning we got the following:

```
[Fri Sep 13 2013 14:14:22 GMT+0000 (UTC)] WARNING packages/mongo-livedata.js:141
[Fri Sep 13 2013 14:14:22 GMT+0000 (UTC)] WARNING Error: No primary found in set
    at _connectHandler (/meteor/containers/8b601a06-d701-5331-6610-051a1d9f41d5/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:437:45)
    at Server.connect.connectionPool.on.server._serverState (/meteor/containers/8b601a06-d701-5331-6610-051a1d9f41d5/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/server.js:546:7)
    at EventEmitter.emit (events.js:126:20)
    at connection.on._self._poolState (/meteor/containers/8b601a06-d701-5331-6610-051a1d9f41d5/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at EventEmitter.emit (events.js:99:17)
    at Socket.errorHandler (/meteor/containers/8b601a06-d701-5331-6610-051a1d9f41d5/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket._destroy.self.errorEmitted (net.js:329:14)
    at process.startup.processNextTick.process._tickCallback (node.js:245:9)
[Fri Sep 13 2013 14:14:22 GMT+0000 (UTC)] ERROR Application crashed with code: 1
[Fri Sep 13 2013 14:14:22 GMT+0000 (UTC)] NOTICE Starting application on port 9633
[Fri Sep 13 2013 14:14:22 GMT+0000 (UTC)] INFO STATUS running -> starting
[Fri Sep 13 2013 14:14:22 GMT+0000 (UTC)] INFO STATUS starting -> running
[Fri Sep 13 2013 14:15:35 GMT+0000 (UTC)] INFO HIT /_GALAXY_ 108.6.125.116
[Fri Sep 13 2013 14:15:46 GMT+0000 (UTC)] INFO STATUS running -> killed
[Fri Sep 13 2013 14:15:46 GMT+0000 (UTC)] NOTICE Starting application on port 9633
[Fri Sep 13 2013 14:15:46 GMT+0000 (UTC)] INFO STATUS killed -> starting
[Fri Sep 13 2013 14:15:46 GMT+0000 (UTC)] INFO STATUS starting -> running

```

Any ideas?

**Comment by grigio** [comment]
I had this exact problem yesterday

**Comment by grigio** [comment]
```
I can't event delete the app :(

```

**Comment by grigio** [comment]
```
meteor deploy todomvc-meteor-react --delete
Couldn't delete application: <!DOCTYPE html>  
<html>
<head>
<title>Error</title>
<style type="text/css">
body {
font-family: 'Helvetica Neue', Helvetica, Arial, san-serif;
padding: 0;
```

**Comment by lfac-pt** [comment]
Hi guys, I'm having this same problem right now. Is this something that is likely due to an outage? Is there anywhere where the status is available? I couldn't find anything...

**Comment by Slava** [comment]
This was a database outrage on our free hosting. It looks like it is all good now.
