### ISSUE TITLE
Creating capped collection in Meteor

### ISSUE THREAD

**Issue by mattuuh7** [meteor/meteor#1478]
Is there an existing API for creating capped collection in Meteor? Thanks.

**Comment by FGM** [comment]
FWIW, on 1.3.2.4, the link is now at https://github.com/meteor/meteor/blob/release-1.3.2.4/packages/mongo/mongo_driver.js#L1281

**Comment by yched** [comment]
Note - this seems to be broken after Meteor 1.11 and the update to mongodb driver 3.6.0 :

```
var coll = new Meteor.Collection("myCollection");
coll._createCappedCollection(3000);
```
This runs fine the very first time, when the collection doesn't actually exist. After that, you'll get an exception: 

```
MongoError: a collection 'meteor.logger' already exists
     at Connection.<anonymous> (HOME/.meteor/packages/npm-mongo/.3.8.0.1u7psm6.649z++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/pool.js:451:61)
     at Connection.emit (events.js:315:20)
     at Connection.EventEmitter.emit (domain.js:483:12)
     at processMessage (HOME/.meteor/packages/npm-mongo/.3.8.0.1u7psm6.649z++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/connection.js:452:10)
     at Socket.<anonymous> (HOME/.meteor/packages/npm-mongo/.3.8.0.1u7psm6.649z++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/core/connection/connection.js:621:15)
     at Socket.emit (events.js:315:20)
     at Socket.EventEmitter.emit (domain.js:483:12)
     at addChunk (_stream_readable.js:295:12)
     at readableAddChunk (_stream_readable.js:271:9)
     at Socket.Readable.push (_stream_readable.js:212:10)
     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) 
```

I suspect it's because of the "Changes in behavior of Db.prototype.createCollection" section in
https://github.com/mongodb/node-mongodb-native/releases/tag/v3.6.0

**Comment by yched** [comment]
As suggested in the [Meteor forums](https://forums.meteor.com/t/capped-collections-in-meteor-1-3-1-4/29403/13),
the following workaround works:

```
const db = Meteor.users.rawDatabase();
const collectionExists = db.listCollections({ name: 'myCollection' }).hasNext().await();
if (!collectionExists) {
  db.createCollection('myCollection', { capped: true, max: 100 }).await();
}
const coll = new Mongo.Collection('myCollection');
```
