### ISSUE TITLE
MongoError: invalid query should be more specific about the query string

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#1633]
Recently I started observing the below cryptic error when trying to log in with a user on my app. It may or may not have to do with a very simple "username only" login handler that I've been using for testing on various apps (https://github.com/mizzao/meteor-accounts-testing), which has been working fine on 0.6.5 thorough 0.6.6.3 as far as I know.

Has there been some changes to the `Accounts.registerLoginHandler` API or something that would cause this? I have no idea where to start debugging.

```
I2049-11:52:21.304(-5)? Exception while invoking method 'login' MongoError: invalid query
I2049-11:52:21.304(-5)?     at Object.Future.wait (/home/mao/.meteor/tools/0b2f28e18b/lib/node_modules/fibers/future.js:326:15)
I2049-11:52:21.304(-5)?     at _.extend.runTask (packages/meteor/fiber_helpers.js:79)
I2049-11:52:21.304(-5)?     at _.extend._addFirstObserveHandle (packages/mongo-livedata/mongo_driver.js:1007)
I2049-11:52:21.304(-5)?     at MongoConnection._observeChanges (packages/mongo-livedata/mongo_driver.js:866)
I2049-11:52:21.304(-5)?     at Cursor.observeChanges (packages/mongo-livedata/mongo_driver.js:655)
I2049-11:52:21.305(-5)?     at Function.Meteor.Collection._publishCursor (packages/mongo-livedata/collection.js:232)
I2049-11:52:21.305(-5)?     at Cursor._publishCursor (packages/mongo-livedata/mongo_driver.js:636)
I2049-11:52:21.305(-5)?     at packages/livedata/livedata_server.js:835
I2049-11:52:21.305(-5)?     at Array.forEach (native)
I2049-11:52:21.305(-5)?     at Function._.each._.forEach (packages/underscore/underscore.js:79)
I2049-11:52:21.306(-5)?     - - - - -
I2049-11:52:21.306(-5)?     at Object.Future.wait (/home/mao/.meteor/tools/0b2f28e18b/lib/node_modules/fibers/future.js:326:15)
I2049-11:52:21.306(-5)?     at _.extend._nextObject (packages/mongo-livedata/mongo_driver.js:721)
I2049-11:52:21.306(-5)?     at _.extend.forEach (packages/mongo-livedata/mongo_driver.js:750)
I2049-11:52:21.306(-5)?     at _.extend.getRawObjects (packages/mongo-livedata/mongo_driver.js:799)
I2049-11:52:21.306(-5)?     at _.extend._pollMongo (packages/mongo-livedata/mongo_driver.js:1075)
I2049-11:52:21.307(-5)?     at packages/mongo-livedata/mongo_driver.js:1008
I2049-11:52:21.307(-5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:76)
I2049-11:52:21.307(-5)?     at Object.task (packages/meteor/dynamics_nodejs.js:86)
I2049-11:52:21.307(-5)?     at _.extend._run (packages/meteor/fiber_helpers.js:144)
I2049-11:52:21.307(-5)?     at packages/meteor/fiber_helpers.js:122
I2049-11:52:21.307(-5)?     - - - - -
I2049-11:52:21.308(-5)?     at Object.toError (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
I2049-11:52:21.308(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:634:54
I2049-11:52:21.309(-5)?     at Cursor.close (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:903:5)
I2049-11:52:21.309(-5)?     at commandHandler (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:634:21)
I2049-11:52:21.309(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/db.js:1670:9
I2049-11:52:21.309(-5)?     at Server.Base._callHandler (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
I2049-11:52:21.309(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
I2049-11:52:21.309(-5)?     at MongoReply.parseBody (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I2049-11:52:21.310(-5)?     at null.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
I2049-11:52:21.310(-5)?     at EventEmitter.emit (events.js:95:17)
I2049-11:52:31.225(-5)? Exception in queued task: MongoError: invalid query
I2049-11:52:31.225(-5)?     at Object.Future.wait (/home/mao/.meteor/tools/0b2f28e18b/lib/node_modules/fibers/future.js:326:15)
I2049-11:52:31.225(-5)?     at _.extend._nextObject (packages/mongo-livedata/mongo_driver.js:721)
I2049-11:52:31.225(-5)?     at _.extend.forEach (packages/mongo-livedata/mongo_driver.js:750)
I2049-11:52:31.225(-5)?     at _.extend.getRawObjects (packages/mongo-livedata/mongo_driver.js:799)
I2049-11:52:31.225(-5)?     at _.extend._pollMongo (packages/mongo-livedata/mongo_driver.js:1075)
I2049-11:52:31.226(-5)?     at Object.task (packages/mongo-livedata/mongo_driver.js:1019)
I2049-11:52:31.226(-5)?     at _.extend._run (packages/meteor/fiber_helpers.js:144)
I2049-11:52:31.226(-5)?     at packages/meteor/fiber_helpers.js:122
I2049-11:52:31.226(-5)?     - - - - -
I2049-11:52:31.226(-5)?     at Object.toError (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
I2049-11:52:31.227(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:634:54
I2049-11:52:31.227(-5)?     at Cursor.close (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:903:5)
I2049-11:52:31.228(-5)?     at commandHandler (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:634:21)
I2049-11:52:31.228(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/db.js:1670:9
I2049-11:52:31.228(-5)?     at Server.Base._callHandler (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
I2049-11:52:31.228(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
I2049-11:52:31.228(-5)?     at MongoReply.parseBody (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I2049-11:52:31.228(-5)?     at null.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
I2049-11:52:31.229(-5)?     at EventEmitter.emit (events.js:95:17)
I2049-11:52:41.226(-5)? Exception in queued task: MongoError: invalid query
I2049-11:52:41.226(-5)?     at Object.Future.wait (/home/mao/.meteor/tools/0b2f28e18b/lib/node_modules/fibers/future.js:326:15)
I2049-11:52:41.226(-5)?     at _.extend._nextObject (packages/mongo-livedata/mongo_driver.js:721)
I2049-11:52:41.227(-5)?     at _.extend.forEach (packages/mongo-livedata/mongo_driver.js:750)
I2049-11:52:41.227(-5)?     at _.extend.getRawObjects (packages/mongo-livedata/mongo_driver.js:799)
I2049-11:52:41.227(-5)?     at _.extend._pollMongo (packages/mongo-livedata/mongo_driver.js:1075)
I2049-11:52:41.227(-5)?     at Object.task (packages/mongo-livedata/mongo_driver.js:1019)
I2049-11:52:41.227(-5)?     at _.extend._run (packages/meteor/fiber_helpers.js:144)
I2049-11:52:41.227(-5)?     at packages/meteor/fiber_helpers.js:122
I2049-11:52:41.228(-5)?     - - - - -
I2049-11:52:41.228(-5)?     at Object.toError (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
I2049-11:52:41.228(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:634:54
I2049-11:52:41.240(-5)?     at Cursor.close (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:903:5)
I2049-11:52:41.241(-5)?     at commandHandler (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:634:21)
I2049-11:52:41.241(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/db.js:1670:9
I2049-11:52:41.241(-5)?     at Server.Base._callHandler (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
I2049-11:52:41.241(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
I2049-11:52:41.241(-5)?     at MongoReply.parseBody (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I2049-11:52:41.241(-5)?     at null.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
I2049-11:52:41.242(-5)?     at EventEmitter.emit (events.js:95:17)
I2049-11:52:51.226(-5)? Exception in queued task: MongoError: invalid query
I2049-11:52:51.226(-5)?     at Object.Future.wait (/home/mao/.meteor/tools/0b2f28e18b/lib/node_modules/fibers/future.js:326:15)
I2049-11:52:51.226(-5)?     at _.extend._nextObject (packages/mongo-livedata/mongo_driver.js:721)
I2049-11:52:51.227(-5)?     at _.extend.forEach (packages/mongo-livedata/mongo_driver.js:750)
I2049-11:52:51.227(-5)?     at _.extend.getRawObjects (packages/mongo-livedata/mongo_driver.js:799)
I2049-11:52:51.227(-5)?     at _.extend._pollMongo (packages/mongo-livedata/mongo_driver.js:1075)
I2049-11:52:51.227(-5)?     at Object.task (packages/mongo-livedata/mongo_driver.js:1019)
I2049-11:52:51.227(-5)?     at _.extend._run (packages/meteor/fiber_helpers.js:144)
I2049-11:52:51.227(-5)?     at packages/meteor/fiber_helpers.js:122
I2049-11:52:51.227(-5)?     - - - - -
I2049-11:52:51.228(-5)?     at Object.toError (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
I2049-11:52:51.228(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:634:54
I2049-11:52:51.228(-5)?     at Cursor.close (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:903:5)
I2049-11:52:51.229(-5)?     at commandHandler (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/cursor.js:634:21)
I2049-11:52:51.229(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/db.js:1670:9
I2049-11:52:51.229(-5)?     at Server.Base._callHandler (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
I2049-11:52:51.229(-5)?     at /home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
I2049-11:52:51.229(-5)?     at MongoReply.parseBody (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I2049-11:52:51.229(-5)?     at null.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/45bb567dec/npm/node_modules/mongodb/lib/mongodb/connection/server.js:430:20)
I2049-11:52:51.230(-5)?     at EventEmitter.emit (events.js:95:17)
```

**Comment by ericchen0121** [comment]
@tmeasday @glasser Came across this same issue in my app in development where a broken publisher basically required a full app server restart. Hard to debug what was happening or why my app was freezing until I read that @tmeasday identified that it does take down the whole app.

 +1 on better error handling of this type of bug.

**Comment by glasser** [comment]
@tmeasday Thanks for the reproduction. I'm going to consider the "once a polling observe driver starts erroring, nothing ever works again" as the bug #2534, and consider this issue (#1633) to just be about the error message being too vague to help you ever find which query is the problem.

**Comment by glasser** [comment]
BTW #2534 is now fixed too.
