### ISSUE TITLE
Oplog Issue

### ISSUE THREAD

**Issue by jamesfebin** [meteor/meteor#2092]
I was trying to scale meteor. 
I connected my meteor instance to a MONGOHQ instance with OPLOG enabled
The meteor app works fine for sometime.  Later when i try to login into my meteor app . The login doesn't work. It keeps me waiting . But after like 10-20 minutes. Again the meteor site functions as normal.
I logged the error this is what i get
Exception in defer callback: Error: failed to connect to [candidate.17.mongolayer.com:10238]
    at Object.Future.wait (/home/febin/bundle/programs/server/node_modules/fibers/future.js:326:15)
    at _.extend._nextObject (packages/mongo-livedata/mongo_driver.js:805)
    at _.extend.forEach (packages/mongo-livedata/mongo_driver.js:836)
    at _.extend.map (packages/mongo-livedata/mongo_driver.js:846)
    at _.extend.fetch (packages/mongo-livedata/mongo_driver.js:870)
    at Cursor.(anonymous function) [as fetch](packages/mongo-livedata/mongo_driver.js:695)
    at MongoConnection.findOne (packages/mongo-livedata/mongo_driver.js:601)
    at _.extend.waitUntilCaughtUp (packages/mongo-livedata/oplog_tailing.js:107)
    at packages/mongo-livedata/oplog_observe_driver.js:136
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:37)
    - - - - -
    at null.<anonymous> (/home/febin/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/server.js:540:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/febin/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/febin/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)

**Comment by HedgeShot** [comment]
Hi @glasser ,

I am facing this bug too. I have a replicaSet on CentOS (on Azure VMs). I use MUPX to setup my meteor prod environment (which fails at deployment stage once in a while, probably related to this issue).

After restarting the app, everything works fine. After some idle time, the app keeps me waiting and eventually resolves after some minutes. The error log show either:

```
Exception while invoking method 'login' Error: failed to connect to [name.cloudapp.net:27017]
[ip]     at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
[ip]     at [object Object]._.extend._nextObject (packages/mongo/packages/mongo.js:994:1)
[ip]     at [object Object]._.extend.forEach (packages/mongo/packages/mongo.js:1028:1)
[ip]     at [object Object]._.extend.map (packages/mongo/packages/mongo.js:1038:1)
[ip]     at [object Object]._.extend.fetch (packages/mongo/packages/mongo.js:1062:1)
[ip]     at [object Object].Cursor.(anonymous function) [as fetch] (packages/mongo/packages/mongo.js:877:1)
[ip]     at [object Object].MongoConnection.findOne (packages/mongo/packages/mongo.js:784:1)
[ip]     at [object Object]._.extend.findOne (packages/mongo/packages/mongo.js:3710:1)
[ip]     at [object Object].defaultResumeLoginHandler (accounts_server.js:971:29)
[ip]     at [object Object].<anonymous> (accounts_server.js:955:38)
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
     at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)

```
or 
```
Got exception while reading last entry: Error: failed to connect to 

```

It might be related to the auth package as this bug occurs on Logout too (and not when I navigate the pages of my website).

Maybe related: when I shutdown my PRIMARY mongo server to test my replicaSet, Meteor throws those errors as well and my app becomes unresponsive.

Any idea?

**Comment by HedgeShot** [comment]
Hey,

I solved connection problems by adding some option to MONGOURL. In particular, I added some timeout as Azure is creating problem on IDLE.

Here is my solution:
```
"MONGO_URL": "mongodb://username:password@url1:27018,url2:27019/dbName?replicaSet=replicaName&readPreference=primaryPreferred&w=majority&connectTimeoutMS=60000&socketTimeoutMS=60000
```
