### ISSUE TITLE
Handle connection errors gracefully otherwise meteor app stops working

### ISSUE THREAD

**Issue by jamesfebin** [meteor/meteor#2196]
I am using MongoHQ to host my MongoDb. 

My meteor server occasionally goes down because of the following error
message : failed to connect to [candidate.17.mongolayer.com:10238]
Detailed error given at the bottom.

I have to reboot it every time to get my server back in function. 

Well am not an expert but i saw the following in a blog post of Mongo HQ. I think my error is related to this. If someone can fix this issue or tell me a solution it will be great. Because my startup is going for production next week. It will be really horrible if my server goes down for any reason.I  have mentioned this earlier but people just close down the issue without giving relevant solutions.Someone please help me up with this.

Blog Post on MongoHqQ
Rule #2: Handle Connection Failure Exceptions
<
Secondaries are most commonly promoted when the primary becomes completely inaccessible. This can happen for a number of reasons, anything from a routine mongod restart to a helicopter “landing” in the middle of your datacenter. Drivers will generally raise a failed connection exception when they send an op to a missing replica set member, then leave the rest up to you. You can choose to either retry the operation (a good idea for critical writes) or just give up and wish your users better luck next time (a good idea if you don’t like your users).

Detailed Error Message
message : failed to connect to [candidate.17.mongolayer.com:10238]
stack :
Error: failed to connect to [candidate.17.mongolayer.com:10238]
    at Object.Future.wait (/home/timekeeper/bundle/programs/server/node_modules/fibers/future.js:326:15)
    at _.extend._nextObject (packages/mongo-livedata/mongo_driver.js:839)
    at _.extend.forEach (packages/mongo-livedata/mongo_driver.js:870)
    at _.extend.map (packages/mongo-livedata/mongo_driver.js:880)
    at _.extend.fetch (packages/mongo-livedata/mongo_driver.js:904)
    at Cursor.(anonymous function) (packages/mongo-livedata/mongo_driver.js:729)
    at cursorProto.(anonymous function) [as fetch](packages/apm/lib/hijack/db.js:101)
    at MongoConnection.findOne (packages/mongo-livedata/mongo_driver.js:635)
    at _.extend.findOne (packages/mongo-livedata/collection.js:238)
    at Object.Meteor.user (packages/accounts-base/accounts_server.js:27)
    - - - - -
    at null. (/home/timekeeper/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)
    at EventEmitter.emit (events.js:106:17)
    at null. (/home/timekeeper/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket. (/home/timekeeper/bundle/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/connection.js:516:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)

**Comment by fjaguero** [comment]
Is there any update on this? It keeps happening on Meteor 1.1.0.2. Almost same setup as @jamesfebin, but Mongo DB is on Compose. It just disconnects after a night without using the app.

**Comment by glasser** [comment]
@fjaguero Can you show the full error you're seeing?

**Comment by fjaguero** [comment]
I have a setInterval() on the server that writes in the DB every 30 seconds (see the bottom of the log "Updating to maintain connection"). That makes the db to connect again.

I'm trying to log in after a disconnection:

![log](http://cl.ly/image/2y3T410l3M1v/Image%202015-04-28%20at%208.31.27%20a.%20m..png)

I tried the app in Azure with my own Mongo 3.0.1, in Amazon EC2 with Compose and in another VM in Azure with Compose. Connecting to a single mongo instance seems to work.

**Comment by HedgeShot** [comment]
Hi @fjaguero ,

I am facing the same problem. Any luck on solving this?

**Comment by fjaguero** [comment]
Hi @HedgeShot,

No, I didn't found the way of solving that, I just used that setInterval and since that I am not using that code anymore I didn't keep trying to fix it.

**Comment by HedgeShot** [comment]
Hi @fjaguero ,

Thanks for your answer. I finally fixed it. I added some options to the MONGO URL. The problem was coming from Azure after some idle time. Here it is:

```
"MONGO_URL": "mongodb://username:password@url1:27018,url2:27019/dbName?replicaSet=replicaName&readPreference=primaryPreferred&w=majority&connectTimeoutMS=60000&socketTimeoutMS=60000
```

**Comment by fjaguero** [comment]
Thanks for sharing the fix!
