### ISSUE TITLE
bcrypt error breaking production site after upgrade to 0.8.2

### ISSUE THREAD

**Issue by flippyhead** [meteor/meteor#2257]
Now fails to startup with: 

> ./bundle/programs/server/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header

And the full error:

```
Error: /home/meteor/bundle/programs/server/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/meteor/bundle/programs/server/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/meteor/bundle/programs/server/node_modules/bcrypt/bcrypt.js:1:97)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
Failed to load c++ bson extension, using pure JS version
```

**Comment by Helmi** [comment]
I'd also be interested in a handy solution. Running into the same problem after bundling on OSX. Does installing manually mean completely removing it from the programs/server/npm folder?

**Comment by qasimzee** [comment]
I have solved this problem and blogged. http://www.qasimzeeshan.com/how-to-deploy-meteor-telescope-on-centos/

I am also building the bundle on OSX and deploying on centos 7

You need to make sure you installed bcrypt (npm install bcrypt) and then

cp -r /home/yourapp_prod/bundle/programs/server/node_modules/bcrypt /home/yourapp_prod/bundle/programs/server/npm/npm-bcrypt/node_modules/

**Comment by glasser** [comment]
Actually, it's simpler (as of Meteor 0.9.0).  Just pass `--architecture os.linux.x86_64` to `meteor build` (or `meteor bundle`).  (Or `os.linux.x86_32` if your server is 32-bit.)

**Comment by CocaColaCat** [comment]
@glasser Saw your suggest and solved the problem. You saved my day!

**Comment by vood** [comment]
@glasser thanks! solved my problem.
