### ISSUE TITLE
Path reservation conflict? (0.9)

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#2406]
My app was working fine and I haven't touched `mrt:bootstrap-3`, but there is a reservation conflict for it. All I've done is switch from a local to a published version of `mizzao:bootboxjs`:

The app is just dead now; won't even start.

```
$ meteor --settings settings-private.json
[[[[[ ~/projects/CrisisMapping/CrowdMapper ]]]]]

=> Started proxy.
=> Started MongoDB.     
=> Starting your app...
/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Path reservation conflict: packages/mrt:bootstrap-3.js
  at [object Object]._.extend.reserve (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/builder.js:249:15)
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:886:15
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:878:11
  at Array.forEach (native)
  at Function._.each._.forEach (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:877:11
  at Array.forEach (native)
  at Function._.each._.forEach (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at eachResource (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:876:9)
  at [object Object]._.extend.write (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:885:5)
  at writeTargetToPath (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:1467:12)
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:1570:26
  at Function._.each._.forEach (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
  at writeSiteArchive (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:1569:7)
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:1955:20
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:186:11
  at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:112:14)
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:183:27
  at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:112:14)
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:181:16
  at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/fiber-helpers.js:112:14)
  at Object.capture (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/buildmessage.js:172:21)
  at Object.exports.bundle (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/bundler.js:1670:31)
  at bundleApp (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:469:28)
  at [object Object]._.extend._runOnce (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:487:24)
  at [object Object]._.extend._fiber (/home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:667:28)
  at /home/mao/.meteor/packages/meteor-tool/.1.0.10.1vz91ll++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:360:12
```

**Comment by appshore** [comment]
Run into this error message. It was a duplicate declaration of a file in a local package.js.

**Comment by glasser** [comment]
@appshore Can you be more clear about what you mean?  I tried to replicate what I thought you meant but it worked (with Meteor 1.0.5): https://github.com/glasser/meteor-duplicate-path-error https://github.com/glasser/meteor-duplicate-path-error/blob/master/packages/dupe/package.js

**Comment by appshore** [comment]
This is exactly what you did. 

I made a mistake (duplicated line) in the package.js of https://github.com/appshore/leaflet-awesome-markers.git

check the line below      'dist/images/markers-shadow@2x.png',

Package.describe({
    name: "appshore:leaflet-awesome-markers",
    summary: "Adds support for drawing and editing vectors and markers on Leaflet maps",
    version: "1.0.3",
    git: "https://github.com/appshore/leaflet-awesome-markers.git"
});

Package.onUse(function (api) {
    api.addFiles([
        'dist/leaflet-awesome-markers.min.js',
        'dist/leaflet-awesome-markers.css',
        'dist/images/markers-matte.png',
        'dist/images/markers-matte@2x.png',
        'dist/images/markers-plain.png',
        'dist/images/markers-shadow.png',
        'dist/images/markers-shadow@2x.png',
        'dist/images/markers-shadow@2x.png',
        'dist/images/markers-soft.png',
        'dist/images/markers-soft@2x.png'
    ], 'client');
}); 

and I got this error:

/Users/Brice/.meteor/packages/meteor-tool/.1.0.45.1ue0kgm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Path reservation conflict: packages/appshore_leaflet-awesome-markers/dist/images/markers-shadow@2x.png
    at [object Object]._.extend.reserve (/Users/Brice/.meteor/packages/meteor-tool/.1.0.45.1ue0kgm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/builder.js:236:15)

**Comment by glasser** [comment]
Ah, I see. This particular error is really specific to client assets.

**Comment by glasser** [comment]
@appshore Thanks, this should be fixed in 89c22bf.

**Comment by appshore** [comment]
@glasser Thank to you for the awesome work with Meteor!

**Comment by alithemindfirm** [comment]
@glasser is #89c22bf solved? I am having the same problem. Have been trying to fix it but no progress. I  am trying to "bower install quantumui --save" with my .bowerrc reffering to "directory":"./client/bower/dependencies/". But getting "bower path reservation conflict ". Stucked with it.

**Comment by glasser** [comment]
Bower is not part of Meteor, so I'm not sure what you're describing --- an error from running the `bower` command-line tool manually (not part of Meteor) or some Bower-providing third-party Atmosphere package? Either way, it seems like a similar error message from an entirely different source.

**Comment by MiroHibler** [comment]
I'm having this problem in v1.2.1:

```javascript
Package.onUse( function ( api ) {
  api.addFiles([
    ...
    'assets/css/tools.css',
    ...
  ], 'client' );
...
  api.addAssets([
    ...
    'assets/css/tools.css',
    ...
  ], 'client' );
});
```
```shell
Error: Path reservation conflict: packages/miro_tools/assets/css/tools.css
```
