### ISSUE TITLE
_id picking and retries in latency-compensated methods can throw duplicate key errors under heavy load

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#2407]
When subjecting my app to a high load from a lot of users I occasionally see **a lot** (specifically, 46 cases from 100 active users over the course of an hour) of errors like the following:

```
I20140813-14:25:57.471(-4)? Exception while invoking method 'createDocument' MongoError: E11000 duplicate key error index: meteor.documents.$_id_  dup key: { : "r6FBkbPqdwxfsQjdC" }
I20140813-14:25:57.471(-4)?     at Object.Future.wait (/home/mao/.meteor/packages/meteor-tool/.1.0.9.198pnby++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:326:15)
I20140813-14:25:57.471(-4)?     at null.<anonymous> (packages/meteor/helpers.js:111)
I20140813-14:25:57.471(-4)?     at MongoConnection.(anonymous function) [as insert] (packages/mongo-livedata/mongo_driver.js:607)
I20140813-14:25:57.472(-4)?     at Object.CollectionHooks.defineAdvice.self (packages/matb33:collection-hooks/insert.js:39)
I20140813-14:25:57.472(-4)?     at Object.collection.(anonymous function) [as insert] (packages/matb33:collection-hooks/collection-hooks.js:105)
I20140813-14:25:57.472(-4)?     at Meteor.Collection.(anonymous function) [as insert] (packages/mongo-livedata/collection.js:481)
I20140813-14:25:57.472(-4)?     at Meteor.methods.createDocument (lib/data.coffee:323:22)
I20140813-14:25:57.472(-4)?     at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1492)
I20140813-14:25:57.472(-4)?     at packages/livedata/livedata_server.js:643
I20140813-14:25:57.472(-4)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20140813-14:25:57.473(-4)?     at packages/livedata/livedata_server.js:642
I20140813-14:25:57.473(-4)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20140813-14:25:57.473(-4)?     at _.extend.protocol_handlers.method (packages/livedata/livedata_server.js:641)
I20140813-14:25:57.473(-4)?     at packages/livedata/livedata_server.js:541
I20140813-14:25:57.473(-4)?     - - - - -
I20140813-14:25:57.473(-4)?     at Object.toError (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
I20140813-14:25:57.473(-4)?     at /home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:599:22
I20140813-14:25:57.473(-4)?     at Server.Base._callHandler (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
I20140813-14:25:57.474(-4)?     at /home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
I20140813-14:25:57.474(-4)?     at MongoReply.parseBody (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20140813-14:25:57.474(-4)?     at null.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
I20140813-14:25:57.474(-4)?     at emit (events.js:95:17)
I20140813-14:25:57.474(-4)?     at null.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
I20140813-14:25:57.474(-4)?     at emit (events.js:98:17)
I20140813-14:25:57.474(-4)?     at Socket.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:422:22)
I20140813-14:25:57.475(-4)?     at Socket.emit (events.js:95:17)
I20140813-14:25:57.475(-4)?     at Socket.<anonymous> (_stream_readable.js:748:14)
I20140813-14:25:57.475(-4)?     at Socket.emit (events.js:92:17)
I20140813-14:25:57.475(-4)?     at emitReadable_ (_stream_readable.js:410:10)
I20140813-14:25:57.475(-4)?     at emitReadable (_stream_readable.js:406:5)
I20140813-14:25:57.475(-4)?     at readableAddChunk (_stream_readable.js:168:9)
I20140813-14:25:57.475(-4)?     at Socket.Readable.push (_stream_readable.js:130:10)
I20140813-14:25:57.475(-4)?     at TCP.onread (net.js:528:21)
I20140813-14:25:57.495(-4)? Exception while invoking method 'createEvent' MongoError: E11000 duplicate key error index: meteor.events.$_id_  dup key: { : "sY2d5vyQBLSmSDGHn" }
I20140813-14:25:57.495(-4)?     at Object.Future.wait (/home/mao/.meteor/packages/meteor-tool/.1.0.9.198pnby++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:326:15)
I20140813-14:25:57.496(-4)?     at null.<anonymous> (packages/meteor/helpers.js:111)
I20140813-14:25:57.496(-4)?     at MongoConnection.(anonymous function) [as insert] (packages/mongo-livedata/mongo_driver.js:607)
I20140813-14:25:57.496(-4)?     at Object.CollectionHooks.defineAdvice.self (packages/matb33:collection-hooks/insert.js:39)
I20140813-14:25:57.496(-4)?     at Object.collection.(anonymous function) [as insert] (packages/matb33:collection-hooks/collection-hooks.js:105)
I20140813-14:25:57.496(-4)?     at Meteor.Collection.(anonymous function) [as insert] (packages/mongo-livedata/collection.js:481)
I20140813-14:25:57.496(-4)?     at Meteor.methods.createEvent (lib/data.coffee:161:11)
I20140813-14:25:57.496(-4)?     at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1492)
I20140813-14:25:57.496(-4)?     at packages/livedata/livedata_server.js:643
I20140813-14:25:57.497(-4)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20140813-14:25:57.497(-4)?     at packages/livedata/livedata_server.js:642
I20140813-14:25:57.497(-4)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:56)
I20140813-14:25:57.497(-4)?     at _.extend.protocol_handlers.method (packages/livedata/livedata_server.js:641)
I20140813-14:25:57.497(-4)?     at packages/livedata/livedata_server.js:541
I20140813-14:25:57.497(-4)?     - - - - -
I20140813-14:25:57.497(-4)?     at Object.toError (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:110:11)
I20140813-14:25:57.498(-4)?     at /home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:599:22
I20140813-14:25:57.498(-4)?     at Server.Base._callHandler (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
I20140813-14:25:57.498(-4)?     at /home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
I20140813-14:25:57.498(-4)?     at MongoReply.parseBody (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
I20140813-14:25:57.498(-4)?     at null.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
I20140813-14:25:57.498(-4)?     at emit (events.js:95:17)
I20140813-14:25:57.498(-4)?     at null.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
I20140813-14:25:57.498(-4)?     at emit (events.js:98:17)
I20140813-14:25:57.499(-4)?     at Socket.<anonymous> (/home/mao/.meteor/packages/mongo-livedata/.1.0.0.1955zgq++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:422:22)
I20140813-14:25:57.499(-4)?     at Socket.emit (events.js:95:17)
I20140813-14:25:57.499(-4)?     at Socket.<anonymous> (_stream_readable.js:748:14)
I20140813-14:25:57.499(-4)?     at Socket.emit (events.js:92:17)
I20140813-14:25:57.499(-4)?     at emitReadable_ (_stream_readable.js:410:10)
I20140813-14:25:57.499(-4)?     at emitReadable (_stream_readable.js:406:5)
I20140813-14:25:57.499(-4)?     at readableAddChunk (_stream_readable.js:168:9)
I20140813-14:25:57.500(-4)?     at Socket.Readable.push (_stream_readable.js:130:10)
I20140813-14:25:57.500(-4)?     at TCP.onread (net.js:528:21)
```

These methods are fairly simple, with the following client/server code:

```
Meteor.methods
  createDocument: (docName) ->
    TurkServer.checkNotAdmin()
    check(docName, String)

    docId = Documents.insert
      title: docName

    if @isSimulation
      Mapper.events.emit("document-create")
    else
      @unblock()
      TurkServer.log
        action: "document-create"
        docId: docId
        name: docName

    return docId

  createEvent: (eventId, fields) ->
    TurkServer.checkNotAdmin()
    check(eventId, String)

    obj = {
      _id: eventId
      sources: []
    # location: undefined
    }

    _.extend(obj, fields)

    # On server, increment number based on highest numbered event (including deleted)
    unless @isSimulation
      maxEventIdx = Events.findOne({}, sort: {num: -1})?.num || 0
      obj.num = maxEventIdx + 1

    Events.insert(obj)

    if @isSimulation
      Mapper.events.emit("event-create")
    else
      @unblock()
      TurkServer.log
        action: "event-create"
        eventId: eventId
    return
```

The error appears to be triggered by client retries or re-attempts on either a laggy connection or under server load. It is essentially a no-op in my app as the operation fails and no side effects happen (as all the other operations happen after the insert). However, what's surprising is that the errors re-cur with the same key over the span of several minutes.

Note that in `createEvent` I am pre-choosing my own `_id` on the client side, but in `createDocument` I am letting the method pick its own `_id`. Hence there seem to be two problems.
- First, where I've picked my own `_id` methods that have turned out to be successful are being retried by the client - `Meteor.methods` should guarantee they are only called once.
- Second, the case where an `_id` is picked on the client and sent to the server for latency compensation, there appear to be either some randomization errors or the retry problem above.

In particular, the `createDocument` operation with the key `r6FBkbPqdwxfsQjdC` appeared with the duplicate key error **19** times over the course of 16 minutes. So it certainly seems to be a problem with the methods implementation and not just someone's laggy connection.

I can share the log from this run if it would help.

**Comment by hwillson** [comment]
There hasn't been any interest/activity on this issue in quite some time. Since this is a difficult issue to replicate and troubleshoot, there isn't much else that can be done to move this issue forward. Since this issue was created, documentation has been added to the [Methods](https://docs.meteor.com/api/methods.html) section of the API docs, explaining that methods can be re-tried on reconnect:

> If a client calls a method and is disconnected before it receives a response, it will re-call the method when it reconnects. This means that a client may call a method multiple times when it only means to call it once. If this behavior is problematic for your method, consider attaching a unique ID to each method call on the client, and checking on the server whether a call with this ID has already been made. Alternatively, you can use Meteor.apply with the noRetry option set to true.

As mentioned above, a [Meteor.apply](https://docs.meteor.com/api/methods.html#Meteor-apply) `noRetry` option has also been added, that can be used to prevent method retries.

Closing - thanks for reporting this originally!
