### ISSUE TITLE
Meteor Cordova Preview 3 error on meteor run iOS after upgrading an app

### ISSUE THREAD

**Issue by shrop** [meteor/meteor#2436]
I have an app that I thought I would try upgrading to Cordova Preview 3. I reined the error below after updating the app to Meteor 0.9.0-rc12, updated to Cordova Preview 3, and added the iOS platform.

The file `__PROJECT_NAME__-Info.plist` didn't exist. I did see `__PROJECT_NAME__` in `./meteor/local/cordova-build/ios/www/`

```
$meteor run ios
simple-schema: updating npm dependencies -- string...
fast-render: updating npm dependencies -- connect...
iron-router: updating npm dependencies -- connect...
kadira: updating npm dependencies -- debug, usage...
Initializing Cordova plugins...
mv: rename /Users/shrop/Projects/www/.meteor/local/cordova-build/platforms/ios/www/__PROJECT_NAME__-Info.plist to /Users/shrop/Projects/www/.meteor/local/cordova-build/platforms/ios/www/www-Info.plist: No such file or directory
Error: /Users/shrop/.meteor/packages/meteor-tool/.1.0.14-cordova4.1rxnz5i++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/android_bundle/.cordova/lib/ios/cordova/3.5.0/bin/create: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/shrop/.meteor/packages/meteor-tool/.1.0.14-cordova4.1rxnz5i++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**Comment by ianserlin** [comment]
Same error with an app originally written in Meteor 0.6.5.1 but continually updated, now at 1.0.2.1

I'll keep investigating of course but any thoughts welcome. I'm assuming meteor links it's own cordova and that use of nvm wouldn't make a difference.

```
$ : PACKAGE_DIRS=../private-packages meteor run ios --verbose
% Parsing the --port option
% Will compile mobile builds
Local package version is up-to-date: accounts-google@1.0.3
Local package version is up-to-date: accounts-password@1.0.5
Local package version is up-to-date: blaze@2.0.4
Local package version is up-to-date: percolatestudio:percolatestudio-migrations@0.7.2
Local package version is up-to-date: random@1.0.2
Local package version is up-to-date: mobile-status-bar@1.0.2
Local package version is up-to-date: aldeed:geocoder@0.3.3
Local package version is up-to-date: mrt:server-deps@0.1.2
Local package version is up-to-date: deps@1.0.6
Local package version is up-to-date: softwarerero:accounts-t9n@1.0.5
Local package version is up-to-date: useraccounts:bootstrap@1.4.1
Local package version is up-to-date: follower-livedata@1.0.3
Local package version is up-to-date: spacebars@1.0.4
Local package version is up-to-date: spacebars-compiler@1.0.4
Local package version is up-to-date: facebook@1.1.3
Local package version is up-to-date: mrt:reactive-publish@0.1.6
Local package version is up-to-date: launch-screen@1.0.1
Local package version is up-to-date: iron:location@1.0.6
Local package version is up-to-date: chuangbo:cookie@1.1.0
Local package version is up-to-date: http@1.0.9
Local package version is up-to-date: useraccounts:core@1.4.1
Local package version is up-to-date: json@1.0.2
Local package version is up-to-date: check@1.0.3
Local package version is up-to-date: retry@1.0.2
Local package version is up-to-date: standard-app-packages@1.0.4
Local package version is up-to-date: tmeasday:publish-with-relations@0.2.0
Local package version is up-to-date: dandv:caret-position@2.1.0-3
Local package version is up-to-date: id-map@1.0.2
Local package version is up-to-date: reactive-dict@1.0.5
Local package version is up-to-date: mrt:moment@2.8.1
Local package version is up-to-date: callback-hook@1.0.2
Local package version is up-to-date: sha@1.0.2
Local package version is up-to-date: meteor@1.1.4
Local package version is up-to-date: fastclick@1.0.2
Local package version is up-to-date: accounts-twitter@1.0.3
Local package version is up-to-date: minifiers@1.1.3
Local package version is up-to-date: accounts-facebook@1.0.3
Local package version is up-to-date: mrt:minimongoid@0.8.8
Local package version is up-to-date: webapp@1.1.5
Local package version is up-to-date: ejson@1.0.5
Local package version is up-to-date: joshowens:simple-form@0.2.2
Local package version is up-to-date: iron:controller@1.0.6
Local package version is up-to-date: kevbuk:moment-range@1.0.1
Local package version is up-to-date: npm-bcrypt@0.7.7
Local package version is up-to-date: alanning:roles@1.2.13
Local package version is up-to-date: base64@1.0.2
Local package version is up-to-date: url@1.0.3
Local package version is up-to-date: mongo-livedata@1.0.7
Local package version is up-to-date: cwohlman:pickadate@1.0.0
Local package version is up-to-date: localstorage@1.0.2
Local package version is up-to-date: accounts-oauth@1.1.3
Local package version is up-to-date: blaze-tools@1.0.2
Local package version is up-to-date: ddp@1.0.13
Local package version is up-to-date: srp@1.0.2
Local package version is up-to-date: iron:core@1.0.6
Local package version is up-to-date: momentjs:moment@2.8.4
Local package version is up-to-date: manuelschoebel:wait-on-lib@0.2.0
Local package version is up-to-date: observe-sequence@1.0.4
Local package version is up-to-date: arunoda:npm@0.2.6
Local package version is up-to-date: meteorhacks:fast-render@1.2.1
Local package version is up-to-date: reactive-var@1.0.4
Local package version is up-to-date: twitter@1.1.3
Local package version is up-to-date: webapp-hashing@1.0.2
Local package version is up-to-date: mongo@1.0.11
Local package version is up-to-date: useful:email-mailgun@0.0.1
Local package version is up-to-date: htmljs@1.0.3
Local package version is up-to-date: ui@1.0.5
Local package version is up-to-date: meteor-platform@1.2.1
Local package version is up-to-date: cwohlman:emails@0.3.0
Local package version is up-to-date: timmyg13:mandrill@0.0.6
Local package version is up-to-date: ordered-dict@1.0.2
Local package version is up-to-date: schnie:uploader@2.0.3
Local package version is up-to-date: session@1.0.5
Local package version is up-to-date: livedata@1.0.12
Local package version is up-to-date: anti:i18n@0.4.3
Local package version is up-to-date: oauth@1.1.3
Local package version is up-to-date: templating@1.0.10
Local package version is up-to-date: coffeescript@1.0.5
Local package version is up-to-date: binary-heap@1.0.2
Local package version is up-to-date: accounts-base@1.1.3
Local package version is up-to-date: mizzao:autocomplete@0.4.10
Local package version is up-to-date: tracker@1.0.4
Local package version is up-to-date: autoupdate@1.1.4
Local package version is up-to-date: html-tools@1.0.3
Local package version is up-to-date: reload@1.1.2
Local package version is up-to-date: less@1.0.12
Local package version is up-to-date: google@1.1.3
Local package version is up-to-date: application-configuration@1.0.4
Local package version is up-to-date: matb33:collection-hooks@0.7.3
Local package version is up-to-date: oauth1@1.1.3
Local package version is up-to-date: cwohlman:templating-server@1.0.8_2
Local package version is up-to-date: underscore@1.0.2
Local package version is up-to-date: iron:dynamic-template@1.0.6
Local package version is up-to-date: oauth2@1.1.2
Local package version is up-to-date: mrt:underscore-string-latest@2.3.3
Local package version is up-to-date: routepolicy@1.0.3
Local package version is up-to-date: peerlibrary:async@0.9.0_3
Local package version is up-to-date: accounts-ui@1.1.4
Local package version is up-to-date: iron:router@1.0.6
Local package version is up-to-date: aslagle:reactive-table@0.5.9
Local package version is up-to-date: iron:layout@1.0.6
Local package version is up-to-date: email@1.0.5
Local package version is up-to-date: geojson-utils@1.0.2
Local package version is up-to-date: minimongo@1.0.6
Local package version is up-to-date: iron:url@1.0.6
Local package version is up-to-date: accounts-ui-unstyled@1.1.5
Local package version is up-to-date: chriswessels:glyphicons-halflings@1.0.2
Local package version is up-to-date: jquery@1.0.2
Local package version is up-to-date: meteorhacks:ssr@2.1.2
Local package version is up-to-date: service-configuration@1.0.3
Local package version is up-to-date: boilerplate-generator@1.0.2
Local package version is up-to-date: iron:middleware-stack@1.0.6
Local package version is up-to-date: logging@1.0.6
% Running build for platforms: [ 'ios' ]
Running command  /usr/bin/xcrun cc --version
% Building the cordova build project
% Bundling the web.cordova program of the app
% Ensuring the cordova build project
% Reading the mobile control file
% Running the mobile control file
% Copying resources for mobile apps
% Writing new config.xml
% Ensuring that platforms in cordova build project are in sync
Using (built-in) Android SDK at /Users/ian/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
% The output of `cordova platforms list`: Installed platforms: ios
Available platforms: amazon-fireos, android, blackberry10, firefoxos

% Ensuring plugins in the cordova build project are in sync { 'org.apache.cordova.console': '0.2.10',
  'org.apache.cordova.inappbrowser': '0.5.1',
  'org.apache.cordova.file': '1.3.0',
  'org.apache.cordova.file-transfer': '0.4.4',
  'org.apache.cordova.device': '0.2.11',
  'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2',
  'org.apache.cordova.statusbar': '0.1.7',
  'org.apache.cordova.splashscreen': '0.3.3' }
% Getting installed plugins for project
Using (built-in) Android SDK at /Users/ian/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'list' ]
% The output of `cordova plugins list`: No plugins added. Use `cordova plugin add <plugin>`.

% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins file was not found.
% Getting installed plugins for project
Using (built-in) Android SDK at /Users/ian/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'list' ]
% The output of `cordova plugins list`: No plugins added. Use `cordova plugin add <plugin>`.

% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins file was not found.
% Ensuring that platforms in cordova build project are in sync
Using (built-in) Android SDK at /Users/ian/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
% The output of `cordova platforms list`: Installed platforms:
Available platforms: amazon-fireos, android, blackberry10, firefoxos, ios

% The platform is not in the Cordova project: ios
Running command  /usr/bin/xcrun cc --version
% Adding a platform ios
Using (built-in) Android SDK at /Users/ian/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'add', 'ios' ]
Error while running for mobile platforms: Error running
/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
mv: rename /www/.meteor/local/cordova-build/platforms/ios/www/__PROJECT_NAME__-Info.plist to
/www/.meteor/local/cordova-build/platforms/ios/www/www-Info.plist: No such file or directory
Error: /Users/ian/.meteor/android_bundle/.cordova/lib/ios/cordova/3.5.0/bin/create: Command failed with exit code 1
at ChildProcess.whenDone
(/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Process.ChildProcess._handle.onexit (child_process.js:823:5)


Creating ios project...


Error: Error running /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
mv: rename /www/.meteor/local/cordova-build/platforms/ios/www/__PROJECT_NAME__-Info.plist to /www/.meteor/local/cordova-build/platforms/ios/www/www-Info.plist: No such file or directory
Error: /Users/ian/.meteor/android_bundle/.cordova/lib/ios/cordova/3.5.0/bin/create: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)


Creating ios project...


  at execFileSyncOrThrow (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:263:11)
  at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:414:7
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at ensureCordovaPlatforms (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:408:5)
  at uninstallAllPlugins (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:638:7)
  at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:642:7
  at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:327:18
  at [object Object]._.extend.withValue (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
  at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:326:36
  at [object Object]._.extend.withValue (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
  at Object.enterJob (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:317:26)
  at ensureCordovaPlugins (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:641:18)
  at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:773:5
  at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:327:18
  at [object Object]._.extend.withValue (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
  at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:326:36
  at [object Object]._.extend.withValue (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
  at Object.enterJob (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:317:26)
  at buildCordova (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:749:16)
  at Object.cordova.buildTargets (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:128:3)
  at Command.doRunCommand [as func] (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands.js:274:15)
  at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1285:23

$ : meteor list-platforms
browser
ios
server
$ : cat .meteor/release
METEOR@1.0.2.1
```

**Comment by ianserlin** [comment]
This is the point at which the existing project and a brand new project created with METEOR@1.0.2.1 begin to diverge when running `meteor run ios --verbose`.

Works: `% The output of `cordova platforms list`: Installed platforms: ios 3.5.0`
Doesn't Work: `% The output of `cordova platforms list`: Installed platforms: ios`

This happens even when running `meteor run ios --release cordova-41.0 --verbose`

**Comment by ianserlin** [comment]
More hunting.

If I log out the arguments (`$@`) or the env (stuffing `printenv` into a file) in `/tools/cordova-scripts/cordova.sh` right before the `exec "${DEV_BUNDLE}/lib/node_modules/cordova/bin/cordova" "$@"` line I see the same env and the same arguments for both the go-right and the fail case.

I haven't figured out where the `3.5.0` is coming from yet.

**Comment by ianserlin** [comment]
Add in reality the `meteor add-platform ios` command bombs out too, expectedly.

Here is the output:

```
/code/usefulio/healthly/www mobile * : PACKAGE_DIRS=../private-packages meteor add-platform ios --verbose
Running command  /usr/bin/xcrun cc --version
Doing HTTP request:  GET https://warehouse.meteor.com/cordova/license_cordova_ios.txt
% Ensuring the cordova build project
% Ensuring that platforms in cordova build project are in sync
Using (built-in) Android SDK at /Users/ian/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
% The output of `cordova platforms list`: Installed platforms:
Available platforms: amazon-fireos, android, blackberry10, firefoxos, ios

% The platform is not in the Cordova project: ios
Running command  /usr/bin/xcrun cc --version
% Adding a platform ios
Using (built-in) Android SDK at /Users/ian/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'add', 'ios' ]

/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: Error running /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
mv: rename /Users/ian/code/usefulio/healthly/www/.meteor/local/cordova-build/platforms/ios/www/__PROJECT_NAME__-Info.plist to /Users/ian/code/usefulio/healthly/www/.meteor/local/cordova-build/platforms/ios/www/www-Info.plist: No such file or directory
Error: /Users/ian/.meteor/android_bundle/.cordova/lib/ios/cordova/3.5.0/bin/create: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)


Creating ios project...


    at execFileSyncOrThrow (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:263:11)
    at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:414:7
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at ensureCordovaPlatforms (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:408:5)
    at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2909:5
    at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.enterJob (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Command.main.registerCommand.name [as func] (/Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:2904:16)
    at /Users/ian/.meteor/packages/meteor-tool/.1.0.38.1ujxn11++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1285:23
```

**Comment by ianserlin** [comment]
Well that was a fancy f*ck. 

The problem occurs when your top level meteor project folder is named `www` because that conflicts with the cordova generated `www` folder in the build output.

Most of our complicated apps are actually multiple meteor apps, and we name the www.domain.com one `www` under a suite level directory with the domain's name (e.g. there might also be a services and an admin app).

**Comment by avital** [comment]
Crazy. @Slava, should we consider checking for this particular case and printing an explicit error message?

**Comment by Slava** [comment]
@ianserlin sorry you had to go through such pain. Can you please open a separate ticket with a repro? Was the name of your app "www" or one of the folders inside? I would like to look at it but it looks unrelated to the original issue.
