### ISSUE TITLE
publish-for-arch does not springboard and needs the correct --release to be specified

### ISSUE THREAD

**Issue by tanis2000** [meteor/meteor#2539]
I'm trying to build an already published package (nemo64:cldr) for a different architecture (OSX 64, the originally published is Linux 64).

Trying the publish-for-arch route it gives the following error:

```
$ meteor publish-for-arch nemo64:cldr@2.2.1

/Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: Version lock for nemo64:cldr should never change. Recorded as {"pluginDependencies":{},"dependencies":{"meteor":"1.0.3","underscore":"1.0.0"},"toolVersion":"meteor-tool@1.0.27"}, calculated as {"dependencies":{"underscore":"1.0.0","meteor":"1.0.3"},"pluginDependencies":{},"toolVersion":"meteor-tool@1.0.28"}
    at _.extend.recordDependencyVersions (/Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-source.js:1438:13)
    at Object.determineBuildTimeDependencies (/Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:266:19)
    at /Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:408:20
    at /Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:186:11
    at _.extend.withValue (/Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:183:27
    at _.extend.withValue (/Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:181:16
    at _.extend.withValue (/Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.capture (/Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:172:21)
    at main.registerCommand.name [as func] (/Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:380:31)
    at /Users/tanis/.meteor/packages/meteor-tool/.1.0.28.rxm3wo++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1224:23
```

**Comment by glasser** [comment]
The way that publish-for-arch springboards works much better as of 1.0.2.
