### ISSUE TITLE
Recover or crash on initial mongo connection failure

### ISSUE THREAD

**Issue by pward123** [meteor/meteor#3038]
I'm getting the error below when the mongodb is down when meteor first starts. Any chance we can get a fix like http://bites.goodeggs.com/post/35878004826/reconnecting-to-mongodb-when-mongoose-connect-fails-at/ ?

```
Exception in callback of async function: Error: failed to connect to [127.0.0.1:27017]
    at null.<anonymous> (/Users/pward/.meteor/packages/mongo/.1.0.8.1kr7rhx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/pward/.meteor/packages/mongo/.1.0.8.1kr7rhx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/pward/.meteor/packages/mongo/.1.0.8.1kr7rhx++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:516:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
```

**Comment by glasser** [comment]
This should be fixed on devel.
