### ISSUE TITLE
Could not start the app in the iOS simulator

### ISSUE THREAD

**Issue by dabvid** [meteor/meteor#3245]
```
** BUILD SUCCEEDED **
2014-12-06 23:34:41.965 ios-sim[30427:2738043] stderrPath: /Users/davidaberg/Desktop/localmarket/.meteor/local/cordova-build/platforms/ios/cordova/console.log
2014-12-06 23:34:41.966 ios-sim[30427:2738043] stdoutPath: /Users/davidaberg/Desktop/localmarket/.meteor/local/cordova-build/platforms/ios/cordova/console.log
Session could not be started: Error Domain=DTiPhoneSimulatorErrorDomain Code=2 "Simulator session timed out." UserInfo=0x7fc415a017d0 {NSLocalizedDescription=Simulator session timed out.}
Command finished with error code 1: /Users/davidaberg/Desktop/localmarket/.meteor/local/cordova-build/platforms/ios/cordova/run --emulator
Error: /Users/davidaberg/Desktop/localmarket/.meteor/local/cordova-build/platforms/ios/cordova/run: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/davidaberg/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```
Could not start the app in the iOS simulator.

**Comment by Slava** [comment]
Closing this as we track problems with ios-sim in #2878.
