### ISSUE TITLE
.npm path collision inside ~

### ISSUE THREAD

**Issue by 127** [meteor/meteor#3305]
Got yosemite 10.10.1, brew with nodejs NOT installed and packages.json like that
```
{
  "pg-query":"0.10.1",
  "pg":"4.0.0",
  "process-pwd": "0.1.2",
  "fibers":"1.0.2"  
}
```
Everything goes fine except package installation goes to ~/.npm after the very first meteor install. And running meteor fails to require any package installed.
```
/Users/trm/.meteor/packages/meteor-tool/.1.0.35.btulse++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20141217-14:36:18.683(3)? (STDERR) 						throw(ex);
W20141217-14:36:18.683(3)? (STDERR) 						      ^
W20141217-14:36:18.683(3)? (STDERR) Error: Cannot find module 'pg-query'
W20141217-14:36:18.683(3)? (STDERR)     at Function.Module._resolveFilename (module.js:338:15)
W20141217-14:36:18.684(3)? (STDERR)     at Function.Module._load (module.js:280:25)
W20141217-14:36:18.684(3)? (STDERR)     at Module.require (module.js:364:17)
W20141217-14:36:18.684(3)? (STDERR)     at require (module.js:380:17)
W20141217-14:36:18.684(3)? (STDERR)     at Object.Npm.require (/Users/trm/Development/prj/.meteor/local/build/programs/server/boot.js:95:18)
W20141217-14:36:18.684(3)? (STDERR)     at app/server/fixture.js:62:19
W20141217-14:36:18.685(3)? (STDERR)     at /Users/trm/Development/prj/.meteor/local/build/programs/server/boot.js:175:5
=> Exited with code: 8

```

**Comment by avital** [comment]
Meteor comes bundled with its own version of Node, so the steps you described aren't the right way to get an NPM library to be used within Meteor.

Here's a blog post about using NPM libraries within Meteor packages: https://www.discovermeteor.com/blog/wrapping-npm-packages/

Another option is to use @arunoda's NPM library: https://github.com/meteorhacks/npm.

Hope this helps, or let me know if I'm misunderstanding your problem.
