### ISSUE TITLE
[1.0.2] TypeError: Unable to watch path

### ISSUE THREAD

**Issue by amitrahav** [meteor/meteor#3336]
after update from 1.0.1 to 1.0.2 I'm getting error on running meteor :

```
/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
TypeError: Unable to watch path
  at HandleWatcher.start (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/pathwatcher/lib/main.js:179:12)
  at Object.watch (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/safe-pathwatcher.js:27:28)
  at [object Object]._.extend._watchFileOrDirectory (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/watch.js:417:35)
  at /home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/watch.js:384:14
  at Function._.each._.forEach (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
  at [object Object]._.extend._startFileWatches (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/watch.js:379:7)
  at new Watcher (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/watch.js:309:8)
  at [object Object]._.extend._runOnce (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:653:23)
  at [object Object]._.extend._fiber (/home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:758:28)
  at /home/user/.meteor/packages/meteor-tool/.1.0.37.6l7jjh++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:365:12
```

 i'm running arch linux.

```
 meteor run --release 1.0.1
```

is working fine.

**Comment by bgbhavesh** [comment]
meteor --release 1.0.2.1-rc.2

works for me.
Thanks

**Comment by nooitaf** [comment]
I got this error with meteor 1.4.1 and fixed it by installing the npm packages ;)
`````bash
meteor npm install
`````
