### ISSUE TITLE
Cordova build hangs after meteor update

### ISSUE THREAD

**Issue by stormbkk87** [meteor/meteor#3398]
```
% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins lock: {}                
% Uninstalling a plugin org.apache.cordova.file
Using (built-in) Android SDK at /Users/storm/.meteor/android_bundle/android-sdk
% Running synchronously:  /Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'rm', 'org.apache.cordova.file' ]
% Plugin removal threw an error: Error running /Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: ENOENT, no such file or directory '/Users/storm/Documents/Dev/KC/.meteor/local/cordova-build/plugins/plugin.http.request/plugin.xml'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.module.exports.parseElementtreeSync (/Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/util/xml-helpers.js:121:27)
    at /Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/dependencies.js:62:35
    at Array.forEach (native)
    at Object.module.exports.package.generate_dependency_info (/Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/dependencies.js:61:45)
    at runUninstallPlatform (/Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/uninstall.js:203:53)
    at Function.module.exports.uninstallPlatform (/Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/uninstall.js:79:12)
    at /Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/plugin.js:187:58
    at _fulfilled (/Users/storm/.meteor/packages/meteor-tool/.1.0.38.yeyq03++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:798:54)
```

**Comment by Slava** [comment]
Hi @stormbkk87,

sorry for getting to this that late. Good to hear that you could fix your original issue. This is true, if you stop the Cordova build mid-way through, Meteor doesn't have a good way to identify this and fix automatically. This happens by accident as well, this is why Meteor prefers to refetch and reinstall all Cordova plugins on any error.

In the future, Meteor cli tool could be smarter and cache the Cordova plugins sources in some centralized place.
