### ISSUE TITLE
Exception in queued task: MongoError: Can't canonicalize query: BadValue bad sort specification

### ISSUE THREAD

**Issue by SachaG** [meteor/meteor#3414]
People have reported running into this error when using [Telescope](http://telesc.pe):

- [Error while inserting new post or comment](http://meta.telesc.pe/posts/GZcQcP6iK8fjhCoqm)
- [MongoError: Can't canonicalize query](https://github.com/TelescopeJS/Telescope/issues/534)
- [Spinning gif of death](http://meta.telesc.pe/posts/3PTyWcNF9xykaBRd9)

Here's the full trace from the first report:

```
Exception in queued task: MongoError: Can't canonicalize query: BadValue bad sort specific
ation 
at Object.Future.wait (bundle/programs/server/node_modules/fibers/future.js:326:15) 
at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:885:1) 
at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:919:1) 
at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:968:1) 
at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:144:1) 
at [object Object].proto._pollMongo (packages/meteorhacks:kadira/lib/hijack/wrap_observers.js:23:1) 
at Object.task (packages/mongo/polling_observe_driver.js:85:1) 
at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:145:1) 
at packages/meteor/fiber_helpers.js:123:1 
at Object.toError (bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:110:11) 
at bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:686:54 
at Cursor.close (bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:969:5) 
at commandHandler (bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:686:21) 
at bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1843:9 
at Server.Base._callHandler (bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41) 
at bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18 
at [object Object].MongoReply.parseBody (bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5) 
at [object Object].<anonymous> (bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20) 
at [object Object].emit (events.js:95:17)
```

That user stated that rebooting the server makes the error go away for a while, which would hint at some kind of performance or memory leak issue?

**Comment by hakanu** [comment]
I'm one of the people who is having this issue.
The thing is that there is no problem with saving comments or posts into db. It saves but it stucks there, doesn't redirect to the new post's page or posted comment's page. It just stays there. If I refresh the page I can see my new post in the post list.

This both happened in the in-house mongo instance and 3rd party mongo service. Don't really think moving the db solves the issue.

**Comment by hakanu** [comment]
Asked this in meteor-talk group:

https://groups.google.com/forum/#!topic/meteor-talk/MmuxryMMOXw

**Comment by Kikobeats** [comment]
I have this error too with the last telescope version :(

**Comment by glasser** [comment]
It sounds like there's a bad sort specification? The error is coming from the Mongo server.  If you have a reproduction, I could try to add some logging to figure out which query is throwing.  But it sounds like you're specifying a sort to Mongo weirdly somehow...

**Comment by hakanu** [comment]
It's really hard to reproduce. for some time it works fine (like 12-15 hours) after that it starts to throw this error. It actually saves stuff into db without problem, but throws this error as well.
What can I do to provide more information?

**Comment by shtefcs** [comment]
Any solutions to fix this ? I have social app where I can't register when it's deployed on server.

**Comment by McBainCO** [comment]
I too am one of the people with this error. It's looking like a modulus/server error. I'm about to export my mongoDB and see if I can see anything there.

**Comment by seanpat09** [comment]
@McBainCO and I were monitoring the logs to see what action would cause this error to get thrown and clicking the Digest view caused the issue for us. This is just a guess, but from my understanding, the Digest view is a relatively new feature. Maybe posts that existed before this feature was created are missing data or have the wrong format that causes the Digest view to cause this sorting problem? That would explain why we can't replicate it in the test org that we have because the data has all been created AFTER the Digest feature was added.

Thoughts @SachaG?

**Comment by SachaG** [comment]
Oh, that sounds plausible. Can you reproduce that reliably with a specific post?

**Comment by McBainCO** [comment]
@SachaG We removed the digest link and it seems to have taken care of the problem now. All Hail @seanpat09 for figuring out what is happening.

**Comment by glasser** [comment]
So this seems to not be a Meteor bug?

If we had an example of exactly what code caused this, maybe we could improve Meteor to make debugging this situation easier.

**Comment by SachaG** [comment]
If it really is the digest (a.k.a. single day) view causing the problem, then the relevant Mongo code would be here: 

https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-singleday/lib/singleday.js#L7-L19

I'm not 100% convinced though, because other people mentioned only seeing the error after letting their instance run for a couple days, which would point at something else.

**Comment by glasser** [comment]
*nod*, though that file is a couple levels of abstraction away from core Meteor code :)

**Comment by seanpat09** [comment]
We'll try exporting the database to a sandbox and see if we can reproduce the issue.

**Comment by richkuo** [comment]
http://www.code4foodblog.com/errors/mongo-cant-canonicalize-query-badvalue-bad-sort-specification/
