### ISSUE TITLE
meteor cordova "no domrange" crash

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#3416]
Is there a specific repo to deal with Meteor / phonegap issues?

does the settings file get passed into a meteor build that is running with phonegap?

for android, I have an app which will seem to run with "meteor run-android" but not when I make a standalone build. I get the meteor splash screen, then just a white screen where my app should load.

below is the output from `adb logcat`
there are a few clues, but not really sure.

my app is hosted at meteor.com but using a custom domain http://XGram.org 
yet I see this:

```
D/meteor.cordova.updater(13440): Host is not intercepted: xgram.org
D/CordovaLog(13440): http://meteor.local/: Line 0 : XMLHttpRequest cannot load http://xgram.org/__cordova/manifest.json. 
Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.
```

```
W/PluginManager(13440): THREAD WARNING: exec() call to File.requestAllPaths blocked the main thread for 17ms. Plugin should use CordovaInterface.getThreadPool().
I/chromium(13440): [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
I/chromium(13440): [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
```
I think this maybe the facebook ads tracking pixel. will remove this

```
W/System.err(13440): java.io.FileNotFoundException
W/System.err(13440): 	at org.apache.cordova.file.LocalFilesystem.getEntryForLocalURL(LocalFilesystem.java:138)
W/System.err(13440): 	at org.apache.cordova.file.FileUtils.resolveLocalFileSystemURI(FileUtils.java:617)
W/System.err(13440): 	at org.apache.cordova.file.FileUtils.access$300(FileUtils.java:52)
W/System.err(13440): 	at org.apache.cordova.file.FileUtils$13.run(FileUtils.java:374)
W/System.err(13440): 	at org.apache.cordova.file.FileUtils$24.run(FileUtils.java:540)
W/System.err(13440): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(13440): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(13440): 	at java.lang.Thread.run(Thread.java:841)
```
^ what's this?

```
D/CordovaLog(13440): file:///android_asset/www/meteor_cordova_loader.js: Line 12 : METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///data/data/com.idzuwrh51cfq0nn1vsdajq/files/meteor/version
I/chromium(13440): [INFO:CONSOLE(12)] "METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///data/data/com.idzuwrh51cfq0nn1vsdajq/files/meteor/version", source: file:///android_asset/www/meteor_cordova_loader.js (12)
D/CordovaLog(13440): file:///android_asset/www/meteor_cordova_loader.js: Line 12 : METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets.
I/chromium(13440): [INFO:CONSOLE(12)] "METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets.", source: file:///android_asset/www/meteor_cordova_loader.js (12)
W/meteor.cordova.updater(13440): startServer(/android_asset/www/application/,/android_asset/www/)
W/meteor.cordova.updater(13440): Filesystem root not found; falling back to assets: /android_asset/www/application/
D/meteor.cordova.updater(13440): Doing assetManager list on www
W/PluginManager(13440): THREAD WARNING: exec() call to CordovaUpdate.startServer blocked the main thread for 270ms. Plugin should use CordovaInterface.getThreadPool().
D/CordovaLog(13440): file:///android_asset/www/meteor_cordova_loader.js: Line 12 : METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local
I/chromium(13440): [INFO:CONSOLE(12)] "METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local", source: file:///android_asset/www/meteor_cordova_loader.js (12)
D/CordovaWebViewClient(13440): onPageStarted(http://meteor.local/)
V/meteor.cordova.updater(13440): remapUri http://meteor.local/
D/meteor.cordova.updater(13440): Doing assetManager list on www/application
D/CordovaActivity(13440): onMessage(onPageStarted,http://meteor.local/)
W/EDMNativeHelper(  257): EDMNativeHelperService is published
D/STATUSBAR-NetworkController(12235): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger(12235): checkOverflow(216), More:true, Req:true Child:12
D/lights  (11884): button : 0 +
D/meteor.cordova.updater(13440): Found asset, but was directory: file:///android_asset/www/application/
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/application/index.html
D/lights  (11884): button : 0 -
V/meteor.cordova.updater(13440): remapUri http://meteor.local/7dbc3fd500f7ce16126c8aeb924f77ba4ca4f0e4.css?meteor_css_resource=true
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/application/7dbc3fd500f7ce16126c8aeb924f77ba4ca4f0e4.css
V/meteor.cordova.updater(13440): remapUri http://meteor.local/cordova.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/cordova.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/cordova.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/application/1f11c011f89c6e451ef198115fef62790f6d525c.js
V/meteor.cordova.updater(13440): remapUri http://fonts.googleapis.com/css?family=Oswald
D/meteor.cordova.updater(13440): Host is not intercepted: fonts.googleapis.com
V/meteor.cordova.updater(13440): remapUri http://fonts.googleapis.com/css?family=Mouse%20Memoirs
D/meteor.cordova.updater(13440): Host is not intercepted: fonts.googleapis.com
V/meteor.cordova.updater(13440): remapUri http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css
D/meteor.cordova.updater(13440): Host is not intercepted: maxcdn.bootstrapcdn.com
V/meteor.cordova.updater(13440): remapUri http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,300italic,400italic,600italic
D/meteor.cordova.updater(13440): Host is not intercepted: fonts.googleapis.com
V/meteor.cordova.updater(13440): remapUri http://fonts.googleapis.com/css?family=Kaushan+Script
D/meteor.cordova.updater(13440): Host is not intercepted: fonts.googleapis.com
V/meteor.cordova.updater(13440): remapUri http://meteor.local/cordova_plugins.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/cordova_plugins.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/cordova_plugins.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/DirectoryEntry.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/DirectoryEntry.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/DirectoryEntry.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/DirectoryReader.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/DirectoryReader.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/DirectoryReader.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/Entry.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/Entry.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/Entry.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/File.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/File.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/File.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/FileEntry.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/FileEntry.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/FileEntry.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/FileError.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/FileError.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/FileError.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/FileReader.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/FileReader.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/FileReader.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/FileSystem.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/FileSystem.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/FileSystem.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/FileUploadOptions.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/FileUploadOptions.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/FileUploadOptions.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/FileUploadResult.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/FileUploadResult.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/FileUploadResult.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/FileWriter.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/FileWriter.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/FileWriter.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/Flags.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/Flags.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/Flags.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/LocalFileSystem.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/LocalFileSystem.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/LocalFileSystem.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/Metadata.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/Metadata.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/Metadata.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/ProgressEvent.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/ProgressEvent.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/ProgressEvent.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/fileSystems.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/fileSystems.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/fileSystems.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/requestFileSystem.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/requestFileSystem.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/requestFileSystem.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/resolveLocalFileSystemURI.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/resolveLocalFileSystemURI.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/resolveLocalFileSystemURI.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/android/FileSystem.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/android/FileSystem.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/android/FileSystem.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/fileSystems-roots.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/fileSystems-roots.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/fileSystems-roots.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file/www/fileSystemPaths.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file/www/fileSystemPaths.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file/www/fileSystemPaths.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file-transfer/www/FileTransferError.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file-transfer/www/FileTransferError.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file-transfer/www/FileTransferError.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.file-transfer/www/FileTransfer.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.file-transfer/www/FileTransfer.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.file-transfer/www/FileTransfer.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.device/www/device.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.device/www/device.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.device/www/device.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/com.meteor.cordova-update/www/CordovaUpdate.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/com.meteor.cordova-update/www/CordovaUpdate.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/com.meteor.cordova-update/www/CordovaUpdate.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.inappbrowser/www/inappbrowser.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.inappbrowser/www/inappbrowser.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.inappbrowser/www/inappbrowser.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.statusbar/www/statusbar.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.statusbar/www/statusbar.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.statusbar/www/statusbar.js
V/meteor.cordova.updater(13440): remapUri http://meteor.local/plugins/org.apache.cordova.splashscreen/www/splashscreen.js
V/meteor.cordova.updater(13440): Detected cordova URI: http://meteor.local/plugins/org.apache.cordova.splashscreen/www/splashscreen.js
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/plugins/org.apache.cordova.splashscreen/www/splashscreen.js
E/SMD     (  261): DCD OFF
D/STATUSBAR-NetworkController(12235): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger(12235): checkOverflow(216), More:true, Req:true Child:12
D/CordovaActivity(13440): onMessage(spinner,stop)
V/meteor.cordova.updater(13440): remapUri http://connect.facebook.net/en_US/fbds.js
D/meteor.cordova.updater(13440): Host is not intercepted: connect.facebook.net
V/meteor.cordova.updater(13440): remapUri http://meteor.local/headersHelper.js?token=1420365973544.418
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/application/headersHelper.js
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 115 : regex.start teststring
I/chromium(13440): [INFO:CONSOLE(115)] "regex.start teststring", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (115)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 136 : Loco load
I/chromium(13440): [INFO:CONSOLE(136)] "Loco load", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (136)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 136 : lib/config
I/chromium(13440): [INFO:CONSOLE(136)] "lib/config", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (136)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 140 : PubSubMan.init
I/chromium(13440): [INFO:CONSOLE(140)] "PubSubMan.init", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (140)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 156 : Trix.get
V/meteor.cordova.updater(13440): remapUri https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-1.3-min.js
I/chromium(13440): [INFO:CONSOLE(156)] "Trix.get", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (156)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 156 : TRIX| created Trix
D/meteor.cordova.updater(13440): Host is not intercepted: d24n15hnbwhuhn.cloudfront.net
I/chromium(13440): [INFO:CONSOLE(156)] "TRIX| created Trix", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (156)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 156 : Uncaught TypeError: Cannot read property 'public' of undefined
I/chromium(13440): [INFO:CONSOLE(156)] "Uncaught TypeError: Cannot read property 'public' of undefined", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (156)
V/StatusBar(13440): Executing action: _ready
W/CordovaPlugin(13440): Attempted to send a second callback for ID: StatusBar271678594
W/CordovaPlugin(13440): Result was: "Invalid action"
D/CordovaActivity(13440): onMessage(spinner,stop)
D/STATUSBAR-NetworkController(12235): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger(12235): checkOverflow(216), More:true, Req:true Child:12
V/meteor.cordova.updater(13440): remapUri http://xgram.org/sockjs/info?cb=lrscurmpi_
D/meteor.cordova.updater(13440): Host is not intercepted: xgram.org
I/ThermalEngine(  286): Mitigation:CPU[2]:2265600 Khz
V/meteor.cordova.updater(13440): remapUri https://www.facebook.com/tr/?id=null&ev=6023828243452&dl=http%3A%2F%2Fmeteor.local%2F&rl=&ts=1420365974056&cd[value]=0.00&cd[currency]=USD
D/meteor.cordova.updater(13440): Host is not intercepted: www.facebook.com
W/System.err(13440): java.io.FileNotFoundException
W/System.err(13440): 	at org.apache.cordova.file.LocalFilesystem.getEntryForLocalURL(LocalFilesystem.java:138)
W/System.err(13440): 	at org.apache.cordova.file.FileUtils.resolveLocalFileSystemURI(FileUtils.java:617)
W/System.err(13440): 	at org.apache.cordova.file.FileUtils.access$300(FileUtils.java:52)
W/System.err(13440): 	at org.apache.cordova.file.FileUtils$13.run(FileUtils.java:374)
W/System.err(13440): 	at org.apache.cordova.file.FileUtils$24.run(FileUtils.java:540)
W/System.err(13440): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(13440): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(13440): 	at java.lang.Thread.run(Thread.java:841)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 69 : Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined
I/chromium(13440): [INFO:CONSOLE(69)] "Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (69)
W/Settings(13589): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
W/Settings(13589): Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
D/dalvikvm(13440): GC_CONCURRENT freed 1474K, 10% free 23890K/26292K, paused 2ms+4ms, total 43ms
D/dalvikvm(13440): WAIT_FOR_CONCURRENT_GC blocked 9ms
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 136 : @Loco init
I/chromium(13440): [INFO:CONSOLE(136)] "@Loco init", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (136)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 136 : Uncaught ReferenceError: Session is not defined
I/chromium(13440): [INFO:CONSOLE(136)] "Uncaught ReferenceError: Session is not defined", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (136)
D/CordovaWebViewClient(13440): onPageFinished(http://meteor.local/)
D/CordovaActivity(13440): onMessage(onPageFinished,http://meteor.local/)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 91 : Uncaught ReferenceError: Spacebars is not defined
I/chromium(13440): [INFO:CONSOLE(91)] "Uncaught ReferenceError: Spacebars is not defined", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (91)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 3 : Exception in defer callback: Error: no domrange
D/CordovaLog(13440):     at m._attachEvents (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:89:5046)
D/CordovaLog(13440):     at m.events (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:89:4886)
D/CordovaLog(13440):     at d (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:101:2033)
D/CordovaLog(13440):     at new e.extend.constructor (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:103:538)
D/CordovaLog(13440):     at o (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:87:1576)
D/CordovaLog(13440):     at Function.c.createController (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:103:10578)
D/CordovaLog(13440):     at Function.c.dispatch (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:103:15805)
D/CordovaLog(13440):     at r (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:103:16705)
D/CordovaLog(13440):     at n.Computation._compute (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:15:1783)
D/CordovaLog(13440):     at new n.Computation (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:15:1038)
I/chromium(13440): [INFO:CONSOLE(3)] "Exception in defer callback: Error: no domrange
I/chromium(13440):     at m._attachEvents (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:89:5046)
I/chromium(13440):     at m.events (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:89:4886)
I/chromium(13440):     at d (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:101:2033)
I/chromium(13440):     at new e.extend.constructor (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:103:538)
I/chromium(13440):     at o (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:87:1576)
I/chromium(13440):     at Function.c.createController (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:103:10578)
I/chromium(13440):     at Function.c.dispatch (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:103:15805)
I/chromium(13440):     at r (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:103:16705)
I/chromium(13440):     at n.Computation._compute (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:15:1783)
I/chromium(13440):     at new n.Computation (http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js:15:1038)", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (3)
V/meteor.cordova.updater(13440): remapUri http://meteor.local/favicon.ico
D/meteor.cordova.updater(13440): Remapping to file:///android_asset/www/application/favicon.ico
V/meteor.cordova.updater(13440): remapUri http://xgram.org/__cordova/manifest.json
D/meteor.cordova.updater(13440): Host is not intercepted: xgram.org
D/CordovaLog(13440): http://meteor.local/: Line 0 : XMLHttpRequest cannot load http://xgram.org/__cordova/manifest.json. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.
I/chromium(13440): [INFO:CONSOLE(0)] "XMLHttpRequest cannot load http://xgram.org/__cordova/manifest.json. Origin http://meteor.local is not allowed by Access-Control-Allow-Origin.", source: http://meteor.local/ (0)
D/CordovaLog(13440): http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js: Line 45 : METEOR CORDOVA DEBUG (autoupdate_cordova.js) Failed to download the manifest network undefined
I/chromium(13440): [INFO:CONSOLE(45)] "METEOR CORDOVA DEBUG (autoupdate_cordova.js) Failed to download the manifest network undefined", source: http://meteor.local/1f11c011f89c6e451ef198115fef62790f6d525c.js (45)
E/SMD     (  261): DCD OFF
W/EDMNativeHelper(  257): EDMNativeHelperService is published
D/STATUSBAR-NetworkController(12235): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger(12235): checkOverflow(216), More:true, Req:true Child:12
D/SSRMv2:Monitor(11884): SIOP:: AP = 310, Prev AP = 300, Duration = 10066, PST = 302
D/SSRMv2:AmoledAdjustTimer(11884): prevTemp = 265, currTemp = 265, prevStep = 4, currStep = 4
D/STATUSBAR-NetworkController(12235): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger(12235): checkOverflow(216), More:true, Req:true Child:12
D/BatteryService(11884): level:83, scale:100, status:2, health:2, present:true, voltage: 4153, temperature: 265, technology: Li-ion, AC powered:false, USB powered:true, Wireless powered:false, icon:17303409, invalid charger:0, online:4, current avg:450, charge type:1
D/BatteryService(11884): Sending ACTION_BATTERY_CHANGED.
D/KeyguardUpdateMonitor(12235): received broadcast android.intent.action.BATTERY_CHANGED
D/KeyguardUpdateMonitor(12235): handleBatteryUpdate
I/Tethering(11884): BATTERY_CHANGED, level = 83lowBatteryThreshold = 15
D/UiModeManager(11884): mCoverManager.getCoverState() : true
I/BusinessExecutor(12603): registered Task#10834 : BatteryEventSource$1
I/BusinessExecutor(12603): Task#10834 : #run() called
I/BusinessExecutor(12603): Task#10834 : #run() ended
D/STATUSBAR-PhoneStatusBar(12235):  mBrightnessEnablebySettings = true mBrightnessEnablebyBattery = true mBrightnessEnablebyDisableFlag = true mPmsBrightnessEnablebySettings = true
D/HeadsetStateMachine(12914): Disconnected process message: 10
D/STATUSBAR-IconMerger(12235): checkOverflow(216), More:true, Req:true Child:12
D/BatteryMeterView(12235): ACTION_BATTERY_CHANGED : level:83 status:2 health:2

```

**Comment by dcsan** [comment]
basically working now, this was an issue with mobile-settings

**Comment by fucazu** [comment]
How did u solve this?

**Comment by dcsan** [comment]
sorry this was months ago, can't recall. maybe that the settings were not in a file called "mobile-settings"?

**Comment by fungilation** [comment]
I'm also seeing my Cordova app stuck with "no domrange", although not with same console outputs otherwise: https://github.com/meteor/meteor/issues/4038

**Comment by glasser** [comment]
Glad to see this was fixed.  @fungilation we'll track that on #4038.
