### ISSUE TITLE
Update to version 1.0.2.1 causes "can't find npm module css-parse" error on run

### ISSUE THREAD

**Issue by d33z** [meteor/meteor#3432]
I updated to version 1.0.2.1, from version 1.0. Now, all new projects (and old) throw this error on run:

```
=> Started proxy.
=> Started MongoDB.
W20150106-11:50:16.306(-8)? (STDERR)
W20150106-11:50:16.378(-8)? (STDERR) /Users/mdelaney/src/scratch/css-parse-testcase/.meteor/local/build/programs/server/boot.js:212
W20150106-11:50:16.379(-8)? (STDERR) }).run();
W20150106-11:50:16.379(-8)? (STDERR)    ^
W20150106-11:50:16.379(-8)? (STDERR) Error: Can't find npm module 'css-parse'. Did you forget to call 'Npm.depends' in package.js within the 'minifiers' package?
W20150106-11:50:16.379(-8)? (STDERR)     at Object.Npm.require (/Users/mdelaney/src/scratch/css-parse-testcase/.meteor/local/build/programs/server/boot.js:117:17)
W20150106-11:50:16.379(-8)? (STDERR)     at Package (packages/minifiers/minifiers.js:1:1)
W20150106-11:50:16.379(-8)? (STDERR)     at /Users/mdelaney/src/scratch/css-parse-testcase/.meteor/local/build/programs/server/packages/minifiers.js:318:4
W20150106-11:50:16.380(-8)? (STDERR)     at /Users/mdelaney/src/scratch/css-parse-testcase/.meteor/local/build/programs/server/packages/minifiers.js:329:3
W20150106-11:50:16.380(-8)? (STDERR)     at /Users/mdelaney/src/scratch/css-parse-testcase/.meteor/local/build/programs/server/boot.js:175:10
W20150106-11:50:16.380(-8)? (STDERR)     at Array.forEach (native)
W20150106-11:50:16.380(-8)? (STDERR)     at Function._.each._.forEach (/Users/mdelaney/.meteor/packages/meteor-tool/.1.0.38.1jb5yzn++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150106-11:50:16.380(-8)? (STDERR)     at /Users/mdelaney/src/scratch/css-parse-testcase/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
```

Note: Running against version 1.0 works just fine still.

**Comment by glasser** [comment]
Can you show a cloneable reproduction? https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

This sounds like you're using the `minifiers` package in your app for some reason, which is surprising to me (as opposed to it just being used at build time).  Will need more details to help understand why.

**Comment by tom2strobl** [comment]
For the record: I'm experiencing the same issue right now. Investigating.

**Comment by think01** [comment]
I'm having the same issue. It happens in a freshly created project with `meteor create test`.
```
>meteor --version
Meteor 1.0.3.1
```

Full error log is:
```
W20150130-15:20:11.077(1)? (STDERR)           
W20150130-15:20:11.079(1)? (STDERR) /home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/boot.js:246
W20150130-15:20:11.079(1)? (STDERR) }).run();
W20150130-15:20:11.079(1)? (STDERR)    ^
W20150130-15:20:11.079(1)? (STDERR) SyntaxError: Error parsing /home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/npm/minifiers/node_modules/css-parse/package.json: Unexpected end of input
W20150130-15:20:11.079(1)? (STDERR)     at Object.parse (native)
W20150130-15:20:11.079(1)? (STDERR)     at readPackage (module.js:113:52)
W20150130-15:20:11.079(1)? (STDERR)     at tryPackage (module.js:123:13)
W20150130-15:20:11.079(1)? (STDERR)     at Function.Module._findPath (module.js:190:18)
W20150130-15:20:11.079(1)? (STDERR)     at Function.Module._resolveFilename (module.js:336:25)
W20150130-15:20:11.080(1)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150130-15:20:11.080(1)? (STDERR)     at Module.require (module.js:364:17)
W20150130-15:20:11.080(1)? (STDERR)     at require (module.js:380:17)
W20150130-15:20:11.080(1)? (STDERR)     at Object.Npm.require (/home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/boot.js:136:18)
W20150130-15:20:11.080(1)? (STDERR)     at Package (packages/minifiers/minifiers.js:1:1)
=> Exited with code: 8
W20150130-15:20:13.030(1)? (STDERR)           
W20150130-15:20:13.032(1)? (STDERR) /home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/boot.js:246
W20150130-15:20:13.032(1)? (STDERR) }).run();
W20150130-15:20:13.032(1)? (STDERR)    ^
W20150130-15:20:13.037(1)? (STDERR) SyntaxError: Error parsing /home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/npm/minifiers/node_modules/css-parse/package.json: Unexpected end of input
W20150130-15:20:13.037(1)? (STDERR)     at Object.parse (native)
W20150130-15:20:13.037(1)? (STDERR)     at readPackage (module.js:113:52)
W20150130-15:20:13.037(1)? (STDERR)     at tryPackage (module.js:123:13)
W20150130-15:20:13.037(1)? (STDERR)     at Function.Module._findPath (module.js:190:18)
W20150130-15:20:13.037(1)? (STDERR)     at Function.Module._resolveFilename (module.js:336:25)
W20150130-15:20:13.037(1)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150130-15:20:13.037(1)? (STDERR)     at Module.require (module.js:364:17)
W20150130-15:20:13.037(1)? (STDERR)     at require (module.js:380:17)
W20150130-15:20:13.037(1)? (STDERR)     at Object.Npm.require (/home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/boot.js:136:18)
W20150130-15:20:13.037(1)? (STDERR)     at Package (packages/minifiers/minifiers.js:1:1)
=> Exited with code: 8
W20150130-15:20:14.880(1)? (STDERR)           
W20150130-15:20:14.883(1)? (STDERR) /home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/boot.js:246
W20150130-15:20:14.883(1)? (STDERR) }).run();
W20150130-15:20:14.883(1)? (STDERR)    ^
W20150130-15:20:14.885(1)? (STDERR) SyntaxError: Error parsing /home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/npm/minifiers/node_modules/css-parse/package.json: Unexpected end of input
W20150130-15:20:14.886(1)? (STDERR)     at Object.parse (native)
W20150130-15:20:14.886(1)? (STDERR)     at readPackage (module.js:113:52)
W20150130-15:20:14.886(1)? (STDERR)     at tryPackage (module.js:123:13)
W20150130-15:20:14.886(1)? (STDERR)     at Function.Module._findPath (module.js:190:18)
W20150130-15:20:14.886(1)? (STDERR)     at Function.Module._resolveFilename (module.js:336:25)
W20150130-15:20:14.886(1)? (STDERR)     at Function.Module._load (module.js:280:25)
W20150130-15:20:14.886(1)? (STDERR)     at Module.require (module.js:364:17)
W20150130-15:20:14.887(1)? (STDERR)     at require (module.js:380:17)
W20150130-15:20:14.887(1)? (STDERR)     at Object.Npm.require (/home/f.dasoghe/Scaricati/provamet/.meteor/local/build/programs/server/boot.js:136:18)
W20150130-15:20:14.887(1)? (STDERR)     at Package (packages/minifiers/minifiers.js:1:1)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by think01** [comment]
To anyone interested: I managed to solve reinstalling meteor.

I still cannot be totally sure what caused the problem. It arised when I downloaded a template meteor project from the web and used it to overwrite another project I already had (yes, I overwrited the .meteor directory...). 
The downloaded project was at an older version, so I updated the merged one. From that moment the project gave me the above error, AND meteor stopped working at all, giving that same error in every freshly created project. So it appears the overwrite operation (bad in itself) corrupted the main meteor installation too!

**Comment by tom2strobl** [comment]
Ok so I figured out when I bundle my meteor app and run the programs/server && npm install jazz fresh with every update, it works. When I try to overwrite an older version of my meteor app (only 1 line change is sufficient to trigger the problem) with git pull or sudo mv, then it throws this error.

**Comment by glasser** [comment]
Are you running `npm install` inside your `.meteor/local` directory or something?

It does sound like you've done something that has corrupted your meteor install.  eg, `.meteor/local/build/programs/server/npm/minifiers/node_modules` is typically a symlink, and maybe you did something that overwrote what it points to?

If you can show a complete reproduction from scratch, we can try to improve this.

**Comment by think01** [comment]
No, I didn't run any @npm install@ command.

I tried to reproduce the problem with the current version of meteor (1.0.3.1) but I was unable to, sorry.

**Comment by dperetti** [comment]
Happening to me as well.
The node_modules symlink is invalid :
![screenshot 2015-02-26 00 27 09](https://cloud.githubusercontent.com/assets/845612/6383053/46c7664e-bd4e-11e4-8bf3-177bdf82b105.png)

Looks like it points to a wrong symlink :

![screenshot 2015-02-26 00 29 31](https://cloud.githubusercontent.com/assets/845612/6383123/a5f82e3c-bd4e-11e4-890c-56f22d59f5a9.png)

The question is: how come it's still the case after a `meteor reset` ?

**Comment by glasser** [comment]
`meteor reset` only resets the Mongo database, not the build state, though that's not a bad idea. (Of course, in theory, the build state should never need to be reset ;) )

I don't exactly understand what your picture is showing.  What does `ls -l .meteor/local/build/programs/server/npm/minifiers/node_modules` say?

**Comment by lorensr** [comment]
```
