### ISSUE TITLE
run android error

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3453]
I've never developed for android, so this is a bit of a shot in the dark for me. I'm getting the following error:

```
~/C/m/5cmenu git:master ❯❯❯ meteor run android                                ✱
Error while running for mobile platforms: Error running
/Users/chet/.meteor/packages/meteor-tool/.1.0.38.r3iy6++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh

BUILD FAILED
/Users/chet/.meteor/android_bundle/android-sdk/tools/ant/build.xml:653: The
following error occurred while executing this line:
/Users/chet/.meteor/android_bundle/android-sdk/tools/ant/build.xml:698: null
returned: 1

Total time: 2 seconds
Error code 1 for command: ant with args:
debug,-f,/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/cordova/build:
Command failed with exit code 2
at ChildProcess.whenDone
(/Users/chet/.meteor/packages/meteor-tool/.1.0.38.r3iy6++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Process.ChildProcess._handle.onexit (child_process.js:823:5)


Running command:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/cordova/build 
Buildfile:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
[checkenv] Android SDK Tools Revision 23.0.2
[checkenv] Installed at /Users/chet/.meteor/android_bundle/android-sdk

-setup:
[echo] Project Name: 5CMenu
[gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 21.0.0
[echo] Resolving Build Target for 5CMenu...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
[echo] ----------
[echo] Creating output directories if needed...
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/res
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/rsObj
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/rsLibs
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-gen
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/classes
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/dexedLibs
[echo] ----------
[echo] Resolving Dependencies for 5CMenu...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
[echo] ----------
[echo] Building Libraries with 'debug'...

nodeps:

-set-mode-check:

-set-debug-files:

-check-env:
[checkenv] Android SDK Tools Revision 23.0.2
[checkenv] Installed at /Users/chet/.meteor/android_bundle/android-sdk

-setup:
[echo] Project Name: CordovaLib
[gettype] Project Type: Android Library

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 21.0.0
[echo] Resolving Build Target for CordovaLib...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
[echo] ----------
[echo] Creating output directories if needed...
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/res
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/libs
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/res
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/rsObj
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/rsLibs
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-gen
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/classes
[mkdir] Created dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/dexedLibs
[echo] ----------
[echo] Resolving Dependencies for CordovaLib...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
[echo] Handling aidl files...
[aidl] No AIDL files to compile.
[echo] ----------
[echo] Handling RenderScript files...
[echo] ----------
[echo] Handling Resources...
[aapt] Generating resource IDs...
[echo] ----------
[echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
[javac] Compiling 90 source files to
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/classes
[javac] warning: [options] source value 1.5 is obsolete and will be removed in
a future release
[javac] warning: [options] target value 1.5 is obsolete and will be removed in
a future release
[javac] warning: [options] To suppress warnings about obsolete options, use
-Xlint:-options.
[javac] Note: Some input files use or override a deprecated API.
[javac] Note: Recompile with -Xlint:deprecation for details.
[javac] 3 warnings
[echo] Creating library output jar file...
[jar] Building jar:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/classes.jar

-post-compile:

-obfuscate:

-dex:
[echo] Library project: do not convert bytecode...

-crunch:
[crunch] Crunching PNG Files in source dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/res
[crunch] To destination dir:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/res
[crunch] Crunched 0 PNG files to update cache

-package-resources:
[echo] Library project: do not package resources...

-package:
[echo] Library project: do not package apk...

-post-package:

-do-debug:
[echo] Library project: do not create apk...
[propertyfile] Creating new property file:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop

-post-build:

debug:

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
[echo] Handling aidl files...
[aidl] No AIDL files to compile.
[echo] ----------
[echo] Handling RenderScript files...
[echo] ----------
[echo] Handling Resources...
[aapt] Generating resource IDs...
[aapt]
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/AndroidManifest.xml:2:
error: Error: Float types not allowed (at 'versionCode' with value 'NaN').
[aapt] 
```

**Comment by Slava** [comment]
> error: Error: Float types not allowed (at 'versionCode' with value 'NaN').

I know it is not a good explanation but this means that the version of your app should be a semver-like number: "1.2.3" as an example.

**Comment by ccorcos** [comment]
Hmm. I changed it to `2.0.0` and I'm not getting that error anymore, but now I'm getting an error with the app id I think:

```
~/C/m/5cmenu git:master ❯❯❯ meteor run android                                                                                                                                                            
Error while running for mobile platforms: Error running
/Users/chet/.meteor/packages/meteor-tool/.1.0.38.r3iy6++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh

BUILD FAILED
/Users/chet/.meteor/android_bundle/android-sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/Users/chet/.meteor/android_bundle/android-sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 1 second
Error code 1 for command: ant with args: debug,-f,/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/cordova/build: Command failed with exit code 2
at ChildProcess.whenDone
(/Users/chet/.meteor/packages/meteor-tool/.1.0.38.r3iy6++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Process.ChildProcess._handle.onexit (child_process.js:823:5)


Running command: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/cordova/build 
Buildfile: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
[checkenv] Android SDK Tools Revision 23.0.2
[checkenv] Installed at /Users/chet/.meteor/android_bundle/android-sdk

-setup:
[echo] Project Name: 5CMenu
[gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 21.0.0
[echo] Resolving Build Target for 5CMenu...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
[echo] ----------
[echo] Creating output directories if needed...
[mkdir] Created dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build
[mkdir] Created dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/res
[mkdir] Created dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/rsObj
[mkdir] Created dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/rsLibs
[mkdir] Created dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/classes
[mkdir] Created dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/dexedLibs
[echo] ----------
[echo] Resolving Dependencies for 5CMenu...
[dependency] Library dependencies:
[dependency] 
[dependency] ------------------
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
[echo] ----------
[echo] Building Libraries with 'debug'...

nodeps:

-set-mode-check:

-set-debug-files:

-check-env:
[checkenv] Android SDK Tools Revision 23.0.2
[checkenv] Installed at /Users/chet/.meteor/android_bundle/android-sdk

-setup:
[echo] Project Name: CordovaLib
[gettype] Project Type: Android Library

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 21.0.0
[echo] Resolving Build Target for CordovaLib...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
[echo] ----------
[echo] Creating output directories if needed...
[mkdir] Created dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/rsObj
[mkdir] Created dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/rsLibs
[echo] ----------
[echo] Resolving Dependencies for CordovaLib...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency] 
[dependency] ------------------

-code-gen:
[mergemanifest] No changes in the AndroidManifest files.
[echo] Handling aidl files...
[aidl] No AIDL files to compile.
[echo] ----------
[echo] Handling RenderScript files...
[echo] ----------
[echo] Handling Resources...
[aapt] No changed resources. R.java and Manifest.java untouched.
[echo] ----------
[echo] Handling BuildConfig class...
[buildconfig] No need to generate new BuildConfig.

-pre-compile:

-compile:
[echo] Creating library output jar file...

-post-compile:

-obfuscate:

-dex:
[echo] Library project: do not convert bytecode...

-crunch:
[crunch] Crunching PNG Files in source dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/res
[crunch] To destination dir: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/res
[crunch] Crunched 0 PNG files to update cache

-package-resources:
[echo] Library project: do not package resources...

-package:
[echo] Library project: do not package apk...

-post-package:

-do-debug:
[echo] Library project: do not create apk...
[propertyfile] Updating property file: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file: /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop

-post-build:

debug:

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
[echo] Handling aidl files...
[aidl] No AIDL files to compile.
[echo] ----------
[echo] Handling RenderScript files...
[echo] ----------
[echo] Handling Resources...
[aapt] Generating resource IDs...
[echo] ----------
[echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:
[echo] Set jars path to:
/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/classes.jar:/Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/libs/libGoogleAnalyticsServices.jar

-compile:
[javac] Compiling 28 source files to /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-build/classes
[javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
[javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
[javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
[javac] /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/src/com/chetcorcos/5CollegeMenu/5CMenu.java:20: error: ';' expected
[javac] package com.chetcorcos.5CollegeMenu;
[javac]                       ^
[javac] /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/src/com/chetcorcos/5CollegeMenu/5CMenu.java:25: error: <identifier> expected
[javac] public class 5CMenu extends CordovaActivity 
[javac]             ^
[javac] /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/src/com/chetcorcos/5CollegeMenu/5CMenu.java:25: error: <identifier> expected
[javac] public class 5CMenu extends CordovaActivity 
[javac]                    ^
[javac] /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/src/com/chetcorcos/5CollegeMenu/5CMenu.java:25: error: <identifier> expected
[javac] public class 5CMenu extends CordovaActivity 
[javac]                                            ^
[javac] /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-gen/com/chetcorcos/5CollegeMenu/BuildConfig.java:2: error: ';' expected
[javac] package com.chetcorcos.5CollegeMenu;
[javac]                       ^
[javac] /Users/chet/Code/meteor/5cmenu/.meteor/local/cordova-build/platforms/android/ant-gen/com/chetcorcos/5CollegeMenu/R.java:8: error: ';' expected
[javac] package com.chetcorcos.5CollegeMenu;
[javac]                       ^
[javac] 6 errors
[javac] 3 warnings
```

This was my `App.info`:

```
App.info({
  id: 'com.chetcorcos.5CollegeMenu',
  name: '5C Menu',
  description: 'Dining hall menus of the Claremont Colleges.',
  author: 'Chet Corcos',
  email: 'ccorcos@gmail.com',
  website: 'http://www.chetcorcos.com',
  version: '2.0.0'
});
```

It appears Android had a problem with my app id. But this must be my app id to upload to the iOS App Store...

**Comment by Slava** [comment]
The error happens because Cordova uses your id as a class name in Java code. Class names cannot start with a number and that's what the error message states. There is already an open issue that discusses that Meteor could have warned from falling into these traps but it is not done yet.

**Comment by ccorcos** [comment]
Ahh. I see. Good catch. Would it be possible to separate the App.info for iOS from Android? for example, an iOS_id and an Android_id?
