### ISSUE TITLE
Installing Cordova Plugins stuck at 0% forever. (Cannot connect to Cordova Plugin server)

### ISSUE THREAD

**Issue by insaneinc01** [meteor/meteor#3459]
Hello,

Since the past 1 hour, for no apparent reason, meteor run or build doesn't move past 'Installing Cordova Plugins'. Its completely stuck at 0%.

```
Installing Cordova plugins                [                            ] 0% 0.0s
```
I have compiled, built and ran the same project hundreds of times before without any problems. So its definitely not because of any change in my project. 
To check further, I created a new project and quickly running 'meteor run ios' shows the following error:

```
Error while running for mobile platforms: Error running                            
/Users/insaneinc/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
SyntaxError: Unexpected token I
Internal routing error

Sorry, we cannot connect to the intended server.

We have just been notified of this problem. We will correct it as soon as possible.

Feel free to contact us if you have any questions: support@iriscouch.com

at Object.parse (native)
at RegClient.<anonymous>
(/Users/insaneinc/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:23)
at Request.self.callback
(/Users/insaneinc/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
at Request.emit (events.js:98:17)
at Request.<anonymous>
(/Users/insaneinc/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous>
(/Users/insaneinc/.meteor/packages/meteor-tool/.1.0.38.z83ibe++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:943:16
at process._tickCallback (node.js:419:13)


Fetching plugin "org.apache.cordova.console@0.2.10" via plugin registry
```

Is anyone else getting this error? 
Any help would be greatly appreciated. 

Thanks!

**Comment by insaneinc01** [comment]
OK. Just realized its a problem with http://plugins.cordova.io/
Their server's down.

Sorry about that. Closing issue.

**Comment by richpowell** [comment]
Im getting this now as well. But Cordova server seems to be up..

**Comment by afuhrtrumpet** [comment]
Same here. http://plugins.cordova.io/ is clearly up, but Meteor is stuck trying to install plugins.

**Comment by glasser** [comment]
@afuhrtrumpet Can you file this as a new issue explicitly showing what you're seeing?
