### ISSUE TITLE
Release 1.0.3

### ISSUE THREAD

**Issue by ekatek** [meteor/meteor#3473]
This issue tracks the release of Meteor 1.0.3. Have any concerns? Mention them here. Finding that the RCs are working great? Mention that here. We will keep this top-level description updated with known issues.

The main changes in this release are to `meteor show` and `meteor publish`. For `meteor show`, there is an entirely new output format. For `meteor publish`, we will upload the documentation file to the Isobuild server. Additionally, you can run `meteor publish --update` to change metadata on a previously uploaded version of a package. (There is a longer explanation here: https://groups.google.com/forum/#!topic/meteor-core/tnuDrNDELWU )

The current RC is 1.0.3-rc.1. Update to the release candidate with: `meteor update --release 1.0.3-rc.1`!
Run `meteor show <name> --release 1.0.3-rc.1` to see some of the new functionality.

**Comment by ManuelDeLeon** [comment]
Updated Meteor no problem
```
$ meteor update --release 1.0.3-rc.0
                                                                                   
Changes to your project's package version selections from updating the release:
                                              
autoupdate   upgraded from 1.1.4 to 1.1.5-rc.0
check        upgraded from 1.0.3 to 1.0.4-rc.0
http         upgraded from 1.0.9 to 1.0.10-rc.0
jquery       upgraded from 1.0.2 to 1.11.3-rc.0
routepolicy  upgraded from 1.0.3 to 1.0.4-rc.0
spacebars    upgraded from 1.0.4 to 1.0.5-rc.0
templating   upgraded from 1.0.10 to 1.0.11-rc.0
tracker      upgraded from 1.0.4 to 1.0.5-rc.0
webapp       upgraded from 1.1.5 to 1.1.6-rc.0

viewmodel: updated to Meteor 1.0.3-rc.0.      
```

Ran meteor okay but velocity blew up
```
$ meteor
[[[[[ ~/Dropbox/viewmodel ]]]]]               

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
W20150113-22:54:59.219(-7)? (STDERR) [velocity-mirror] /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/fibers.js:13
W20150113-22:54:59.221(-7)? (STDERR) 	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
W20150113-22:54:59.222(-7)? (STDERR) 	      ^
W20150113-22:54:59.222(-7)? (STDERR) Error: `/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/bin/linux-ia32-v8-3.26/fibers.node` is missing. Try reinstalling `node-fibers`?
W20150113-22:54:59.222(-7)? (STDERR)     at Object.<anonymous> (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/server-lib/node_modules/fibers/fibers.js:13:8)
W20150113-22:54:59.222(-7)? (STDERR)     at Module._compile (module.js:460:26)
W20150113-22:54:59.222(-7)? (STDERR)     at Object.Module._extensions..js (module.js:478:10)
W20150113-22:54:59.223(-7)? (STDERR)     at Module.load (module.js:355:32)
W20150113-22:54:59.223(-7)? (STDERR)     at Function.Module._load (module.js:310:12)
W20150113-22:54:59.223(-7)? (STDERR)     at Module.require (module.js:365:17)
W20150113-22:54:59.223(-7)? (STDERR)     at require (module.js:384:17)
W20150113-22:54:59.224(-7)? (STDERR)     at Object.<anonymous> (/home/manuel/Dropbox/viewmodel/.meteor/local/build/programs/server/boot.js:1:75)
W20150113-22:54:59.224(-7)? (STDERR)     at Module._compile (module.js:460:26)
W20150113-22:54:59.225(-7)? (STDERR)     at Object.Module._extensions..js (module.js:478:10)
W20150113-22:54:59.225(-7)? (STDERR) 
^C
```

Deleted local folder and tried again
```
$ meteor
[[[[[ ~/Dropbox/viewmodel ]]]]]               

=> Started proxy.                             
                                              
/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: rs.initiate error: couldn't initiate : new file allocation failure
  at Error (<anonymous>:null:null)
  at initiateReplSetAndWaitForReady (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-mongo.js:409:17)
  at launchMongo (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-mongo.js:492:9)
  at [object Object]._.extend._startOrRestart (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-mongo.js:590:19)
  at [object Object]._.extend.start (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-mongo.js:548:10)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-all.js:195:26
```

Removed Velocity
```
$ meteor remove mike:mocha
                                              
Changes to your project's package version selections:
                                              
amplify                    removed from your project
less                       removed from your project
mike:mocha                 removed from your project
practicalmeteor:chai       removed from your project
practicalmeteor:loglevel   removed from your project
velocity:core              removed from your project
velocity:html-reporter     removed from your project
velocity:node-soft-mirror  removed from your project
velocity:shim              removed from your project
velocity:test-proxy        removed from your project

mike:mocha: removed dependency                
```

And tried again
```
$ meteor
[[[[[ ~/Dropbox/viewmodel ]]]]]               

=> Started proxy.                             
                                              
/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: ENOSPC, write
  at Object.Future.wait (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:326:15)
  at Object.wrapper [as writeFile] (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/files.js:1115:24)
  at [object Object]._.extend.write (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/builder.js:186:13)
  at writeFile (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1745:11)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1188:7
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1142:11
  at Array.forEach (native)
  at Function._.each._.forEach (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1141:11
  at Array.forEach (native)
  at Function._.each._.forEach (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at eachResource (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1140:9)
  at [object Object]._.extend.write (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1155:5)
  at writeTargetToPath (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1756:12)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1864:26
  at Function._.each._.forEach (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
  at writeSiteArchive (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1863:7)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:2088:20
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/buildmessage.js:264:13
  at [object Object]._.extend.withValue (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/fiber-helpers.js:115:14)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/buildmessage.js:257:29
  at [object Object]._.extend.withValue (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/fiber-helpers.js:115:14)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/buildmessage.js:255:18
  at [object Object]._.extend.withValue (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/fiber-helpers.js:115:14)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/buildmessage.js:246:23
  at [object Object]._.extend.withValue (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/fiber-helpers.js:115:14)
  at Object.capture (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/buildmessage.js:245:19)
  at Object.exports.bundle (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/bundler.js:1975:31)
  at bundleApp (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-app.js:508:34)
  at [object Object]._.extend._runOnce (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-app.js:544:35)
  at [object Object]._.extend._fiber (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-app.js:771:28)
  at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-app.js:366:12

    - - - - -
```

Deleted local folder and tried again
```
$ meteor
[[[[[ ~/Dropbox/viewmodel ]]]]]               

=> Started proxy.                             
                                              
/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: rs.initiate error: couldn't initiate : failure writing file /home/manuel/Dropbox/viewmodel/.meteor/local/db/local.ns
    at Error (<anonymous>)
    at initiateReplSetAndWaitForReady (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-mongo.js:409:17)
    at launchMongo (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-mongo.js:492:9)
    at [object Object]._.extend._startOrRestart (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-mongo.js:590:19)
    at [object Object]._.extend.start (/home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-mongo.js:548:10)
    at /home/manuel/.meteor/packages/meteor-tool/.1.0.39-rc.0.1ffj8b++os.linux.x86_32+web.browser+web.cordova/meteor-tool-os.linux.x86_32/tools/run-all.js:195:26
$ 
```

**Comment by n1mmy** [comment]
@ManuelDeLeon Thanks for testing! That sounds like you're out of disk space. Can you check to see with `df -h`? If you disk is full, remove some files and try again with Velocity.

**Comment by ManuelDeLeon** [comment]
Now this is embarrassing... and I even had a red icon on the taskbar telling me I was out of disk space.
Sorry for the false alarm.

**Comment by ekatek** [comment]
1.0.39-rc.1 is out. It does not contain any fixes to known issues from 1.0.39-rc.0 (there haven't been any known issues specific 1.0.39-rc.0), but it does contain a bug fix to some session behavior.

**Comment by stachrom** [comment]
? 1.0.39-rc.1 --> 1.0.3-rc.0

2015-01-15 20:16 GMT+01:00 Ekaterina Kuznetsova <notifications@github.com>:

**Comment by ekatek** [comment]
Hah, sorry, mistype. Fixed.

**Comment by benjamin79** [comment]
I´have still the problem, that after 'meteor update' is says updated, but after doing 'meteor list' i get the old list with * for update. I´m on yosemite mac.

**Comment by ekatek** [comment]
That's sad. Thanks for reporting! This is hard to debug without more
information -- could you show us the output of 'meteor list' and 'meteor
update'? Thanks.

**Comment by benjamin79** [comment]
It seems that i´ve had a some problems with npm. I´ve deleted a module in packages.json from meteorhacks:npm. I don´t know why, but after that npm had permission problems and node_modules has been deleted.

After doing permissions repair with disk utility i can´t reproduce this  Sorry. So i can´t tell if it has had anything to do with it. Only 'http   1.0.10-rc.0* Make HTTP calls to remote servers'  doesn´t seem to update now.

**Comment by stubailo** [comment]
@ekatek should we close this?

**Comment by ekatek** [comment]
Yup, let's close it.
