### ISSUE TITLE
meteor windows TypeError: Object # has no method 'getDefaultReleaseVersion'

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#3549]
is there a separate repo/tag for windows issues?
we were trying to use meteor at a hackthon, but had problems even getting started for the windows guys. a google doesnt give any hints...

```
OUTPUT:

C:\Users\jfarmer\Documents\GitHub\WelcomeToWisconsin\metapp>meteor run --settings "config/config.json"

C:\Users\jfarmer\AppData\Local.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:173
throw(ex);
^
TypeError: Object # has no method 'getDefaultReleaseVersion'
at C:\Users\jfarmer\AppData\Local.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:416:39
at [object Object]._.extend.withProgressDisplayVisible (C:\Users\jfarmer\AppData\Local.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\console.js:612:14)
at springboard (C:\Users\jfarmer\AppData\Local.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:402:11)

at C:\Users\jfarmer\AppData\Local\.meteor\packages\meteor-tool\1.1.0-winr.0\mt-os.windows.x86_32\tools\main.js:992:5
```

**Comment by Slava** [comment]
Please refer to this wiki page regarding Windows preview release: https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

A repo for bug-reports: https://github.com/meteor/windows-preview

I am going to manually port the report there.
