### ISSUE TITLE
Issue with source handler in locally added package

### ISSUE THREAD

**Issue by patrickocoffeyo** [meteor/meteor#3558]
I'm writing a [jscs package](https://github.com/patrickocoffeyo/meteor-jscs) for Meteor, and I'm having issues using Plugin.registerSourceHandler within a package that's been added locally (in the packages dir).When I run meteor, I get a `TypeError: Cannot read property 'name' of undefined` error from `~/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:385:34` when running `meteor` in meteor's root.

 I've verified that other published and working packages with source handlers throw the same error when installed locally. 

Here's the error:

```
/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
TypeError: Cannot read property 'name' of undefined
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:385:34
    at Function._.each._.forEach (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:377:7
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at compileUnibuild (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:376:5)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:1078:27
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compiler.compile (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:1077:5)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/catalog-local.js:733:25
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:338:18
    at _.extend.withValue (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:331:34
    at _.extend.withValue (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:329:23
    at _.extend.withValue (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.enterJob (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:303:26)
    at _.extend._build (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/catalog-local.js:729:20)
    at _.extend.getLoadPathForPackage (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/catalog-local.js:503:12)
    at _.extend.getLoadPathForPackage (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/catalog.js:192:30)
    at _.extend.getLoadPathForPackage (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-loader.js:93:25)
    at _.extend.getPackage (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-loader.js:55:25)
    at Object.compiler.eachUsedUnibuild (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:85:37)
    at compileUnibuild (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:337:14)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:1078:27
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compiler.compile (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:1077:5)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:2004:26
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:250:13
    at _.extend.withValue (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:243:29
    at _.extend.withValue (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:241:18
    at _.extend.withValue (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:232:23
    at _.extend.withValue (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.capture (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:231:19)
    at Object.exports.bundle (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1926:31)
    at bundleApp (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:509:28)
    at _.extend._runOnce (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:527:24)
    at _.extend._fiber (/Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:744:28)
    at /Users/pcoffey/.meteor/packages/meteor-tool/.1.0.36.14t911q++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:380:12
```

Help! :)

**Comment by glasser** [comment]
Generally it's best to mention what version of Meteor you're running. It looks like you are running Meteor 1.0.1.  My vague memory is that a bug like this was fixed in 1.0.2.  Try with the current version of Meteor (1.0.3.1).

**Comment by patrickocoffeyo** [comment]
Excellent! I'll update the project. Thank you for your quick response. :+1:

**Comment by patrickocoffeyo** [comment]
I can confirm that updating to the latest version of Meteor resolves this issue. Thank you again!
