### ISSUE TITLE
HTTP.get error

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#3578]
I'm getting a HTTP.get on the server synchronously.

    result = HTTP.get url, httpOptions
    if result.statusCode is 422
      console.log "limit reached"
      return

I check the `result.statusCode` and react appropriately. However, I never get to my if statement above because an error is thrown.

```
Error: failed [422] {"message":"In order to keep the API fast for everyone, pagination is limited for this resource. Check the rel=last link relation in the Link response header to see how far back you can traverse.","documentation_url":"https://developer.github.com/v3/#pagination"}
    at Object.Future.wait (/Users/chet/.meteor/packages/meteor-tool/.1.0.40.flc0a++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:326:15)
    at Object.call (packages/meteor/helpers.js:119:1)
    at Object.HTTP.get (packages/http/httpcall_common.js:45:1)
    at getStargazers (server/server.coffee:80:17)
    at getAllStargazers (server/server.coffee:96:7)
    at getAllStargazers (server/server.coffee:101:12)
    at getAllStargazers (server/server.coffee:101:12)
    at getAllStargazers (server/server.coffee:101:12)
    at getAllStargazers (server/server.coffee:101:12)
    at getAllStargazers (server/server.coffee:101:12)
    - - - - -
    at makeErrorByStatus (packages/http/httpcall_common.js:12:1)
    at Request._callback (packages/http/httpcall_server.js:98:1)
    at Request.self.callback (/Users/chet/.meteor/packages/http/.1.0.10.ihdpxg++os+web.browser+web.cordova/npm/node_modules/request/request.js:372:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/chet/.meteor/packages/http/.1.0.10.ihdpxg++os+web.browser+web.cordova/npm/node_modules/request/request.js:1310:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/chet/.meteor/packages/http/.1.0.10.ihdpxg++os+web.browser+web.cordova/npm/node_modules/request/request.js:1258:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

This doesnt make sense to me. Why are we throwing an error here?

**Comment by stubailo** [comment]
It looks like the HTTP package throws an error on an error result code. You can get it using try/catch.

From the docs:

> The error argument will contain an Error if the request fails in any way, including a network error, time-out, or an HTTP status code in the 400 or 500 range. In case of a 4xx/5xx HTTP status code, the response property on error matches the contents of the result object. When run in synchronous mode, either result is returned from the function, or error is thrown.

**Comment by ccorcos** [comment]
Interesting. Why would this be a good idea? Do you understand my confusion?

**Comment by stubailo** [comment]
I understand your confusion, but the method in question is documented as throwing an error when the response status code indicates a failed request.
