### ISSUE TITLE
Crash running meteor publish (TypeError: Cannot use 'in' operator to search for 'track' in null)

### ISSUE THREAD

**Issue by DSpeichert** [meteor/meteor#3680]
```
 root ▶ marley ▶ SSH ▶ ~ ▶ # ▶ meteor publish
  downloading meteor-tool at version 1.0.40 ...  done

/root/.meteor/packages/meteor-tool/.1.0.40.vhmdxr++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
                                                throw(ex);
                                                      ^
TypeError: Cannot use 'in' operator to search for 'track' in null
    at /root/.meteor/packages/meteor-tool/.1.0.40.vhmdxr++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:834:18
    at Array.forEach (native)
    at _.each._.forEach (/root/.meteor/packages/meteor-tool/.1.0.40.vhmdxr++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Function._.pick (/root/.meteor/packages/meteor-tool/.1.0.40.vhmdxr++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:833:5)
    at [object Object]._.extend.getDefaultReleaseVersion (/root/.meteor/packages/meteor-tool/.1.0.40.vhmdxr++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/catalog-remote.js:848:14)
    at Object.release.latestKnown (/root/.meteor/packages/meteor-tool/.1.0.40.vhmdxr++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/release.js:185:41)
    at /root/.meteor/packages/meteor-tool/.1.0.40.vhmdxr++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/main.js:806:29
```

**Comment by stubailo** [comment]
What value is your `HOME` environment variable set to here? Is it `/root`?

**Comment by DSpeichert** [comment]
Yup, running as root here.

**Comment by Slava** [comment]
A workaround can be setting the parent folder of the meteor installation (`.meteor` folder) to HOME?

**Comment by hwillson** [comment]
Running Meteor as root is highly discouraged, but if you have to run Meteor as root, newer versions of Meteor (since  1.4.2.1) support the `--allow-superuser` flag (see https://github.com/meteor/meteor/issues/7959 for the full details). That being said, since there have been many new Meteor releases since this issue was created (and due to the low issue activity), I'll close this issue for now. Thanks!
