### ISSUE TITLE
package release will crash based on README markdown

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#3817]
I had a package with a README and some titles like

```
##heading
```

this caused the 
meteor publish --create

to crash with the error below.

after some sleuthing i found out that 
```
## heading ##
```

format is required.

```
/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: no pluginProviderPackageMap on isopack?
    at Error (<anonymous>)
    at bundleSource (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-client.js:286:11)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-client.js:675:26
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Object.exports.publishPackage (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-client.js:674:16)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:422:21
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.main.captureAndExit (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:257:29)
    at Command.main.registerCommand.name [as func] (/Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:418:8)
    at /Users/dc/.meteor/packages/meteor-tool/.1.0.41.gcbk74++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1300:23

```
FYI it's this package
https://github.com/dcsan/meteor-slick

and it seems to be recent change as the package was published by someone else before.

**Comment by glasser** [comment]
This is probably the same as #3676.

I think it's an error handling bug --- there's probably an error sitting in buildmessage but it doesn't do the appropriate recovery to make sure that it can continue to the stage where the messages are printed.

**Comment by glasser** [comment]
I can't reproduce this.  I tried checking out commit 1103074 from your repo, changing the package name to `glasser:test1234`, and running `meteor publish --create` both from devel and Meteor 1.0.3.2, and in neither case did it crash in this way.  I did get this error though.

```
While building package glasser:test1234:
error: File not found: vendor/slick/slick/ajax-loader.gif
error: File not found: vendor/slick/slick/fonts/slick.eot
error: File not found: vendor/slick/slick/fonts/slick.svg
error: File not found: vendor/slick/slick/fonts/slick.ttf
error: File not found: vendor/slick/slick/fonts/slick.woff
error: File not found: vendor/slick/slick/slick.css
error: File not found: vendor/slick/slick/slick.js
```

I do believe there really is a bug since multiple people have reported it, but please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

Without a way to replicate your problem, we can't debug and fix it.

**Comment by dcsan** [comment]
i just cloned and was not able to repro the bug, published fine. closing

**Comment by glasser** [comment]
OK, I figured out what's going on.

When you were running `publish`, was your package inside an app?

I think this is a crash that happens only when you're running inside an app, and the `publish` command doesn't have to rebuild the package because you've run some command that built it (eg just `meteor`) since the last time you've changed it.

So it seemed like it had something to do with the readme, but what actually was going on was that you saw the crash, then you changed *ANY FILE*, and then the publish did a rebuild which was enough to avoid the issue.

Does that match what you saw?

If so, great, and we'll continue tracking this in #3676.

**Comment by glasser** [comment]
Also, you have a mobile platform in your app, right?
