### ISSUE TITLE
Unexpected error when using audit argument checks

### ISSUE THREAD

**Issue by chrishill627** [meteor/meteor#3873]
I have been using audit argument checks and have always used it. I have a strange error which is saying it expected undefined but got an object

// console.log options

```
I20150306-08:23:12.481(0)? { title: 'Title',
I20150306-08:23:12.484(0)?   description: 'Description',
I20150306-08:23:12.484(0)?   keySkillsRequired:
I20150306-08:23:12.484(0)?    [ { keySkillTitle: 'Accountancy',
I20150306-08:23:12.484(0)?        keySkillId: '1',
I20150306-08:23:12.484(0)?        description: 'weufb',
I20150306-08:23:12.484(0)?        levelRequired: '5',
I20150306-08:23:12.484(0)?        hoursPerWeek: 21 } ],
I20150306-08:23:12.484(0)?   location:
I20150306-08:23:12.484(0)?    { context: 'default',
I20150306-08:23:12.484(0)?      location: { lng: -1.7138638, lat: 53.5831248 },
I20150306-08:23:12.484(0)?      locality: 'Shepley, West Yorkshire, UK' },
I20150306-08:23:12.485(0)?   continuationBasis: 'longTerm',
I20150306-08:23:12.485(0)?   relationshipType: 'employee',
I20150306-08:23:12.485(0)?   timeManagement: 'fixed',
I20150306-08:23:12.485(0)?   workLocation: 'onSite' }
```

// ERROR

```
I20150306-08:23:12.524(0)? Exception while invoking method 'savePosition' Error: Match error: Expected undefined, got object
I20150306-08:23:12.524(0)?     at checkSubtree (packages/check/match.js:159:1)
I20150306-08:23:12.524(0)?     at check (packages/check/match.js:32:1)
I20150306-08:23:12.524(0)?     at [object Object].Meteor.methods.savePosition (app/server/methods/employer_user.js:21:9)
I20150306-08:23:12.524(0)?     at packages/check/match.js:109:1
I20150306-08:23:12.524(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150306-08:23:12.524(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150306-08:23:12.524(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
I20150306-08:23:12.524(0)?     at packages/ddp/livedata_server.js:648:1
I20150306-08:23:12.524(0)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150306-08:23:12.524(0)?     at packages/ddp/livedata_server.js:647:1
I20150306-08:23:12.524(0)? Sanitized and reported to the client as: Match failed [400]
```

// METHOD SERVER SIDE
```
    savePosition: function(options) {
        console.log(options);
        check(options = {
            title: Match.Optional(String),
            description: Match.Optional(String),
            keySkillsRequired: Match.Optional(Array),
            location: Match.Optional(Object),
            continuationBasis: Match.Optional(String),
            relationshipType: Match.Optional(String),
            timeManagement: Match.Optional(String),
            workLocation: Match.Optional(String)
            //expiryDate: String
        });
        return EmploymentPositions.insert(options);
```
// METHOD CLIENT SIDE
```
'click #save-new-job-listing': function() {
        var options;
        options = {
            title: $("#job-title").val(),
            description: $("#job-description").val(),
            keySkillsRequired: Session.get("requiredSkillsArray"),
            location: Session.get("position"),
            continuationBasis: Session.get("continuationBasis"),
            relationshipType: Session.get("relationshipType"),
            timeManagement: Session.get("timeManagement"),
            workLocation: Session.get("workLocation"),
            //expiryDate: $("#application-date").val()
        };
        if (!_.isUndefined(_.values(options))) {
            //options.expiryDate = new Date(options.expiryDate);
            console.log(options);
            Meteor.call("savePosition", options, function(err, res){
                if (err) {
                    App.sendAlert("Sorry", err.reason || "Something went wrong", "error");
                } else {
                    App.sendAlert("Done!" + options.title + " has been added to your current vacancies!", "success");
                }
            });
        } else {
            App.sendAlert("", "Please fill in all fields to add this skill", "error");
        }
    }
```

Thanks!

**Comment by stubailo** [comment]
What if you write your code like this:

```
check(options, {
        title: Match.Optional(String),
        description: Match.Optional(String),
        keySkillsRequired: Match.Optional(Array),
        location: Match.Optional(Object),
        continuationBasis: Match.Optional(String),
        relationshipType: Match.Optional(String),
        timeManagement: Match.Optional(String),
        workLocation: Match.Optional(String)
        //expiryDate: String
    });
```

Note the comma after options rather than the equals symbol.

**Comment by chrishill627** [comment]
Ah. Yes, my bad! Thanks for the help!

**Comment by stubailo** [comment]
Np!
