### ISSUE TITLE
Regression in meteor publish: Cannot call method 'toString' of undefined at uploadFile

### ISSUE THREAD

**Issue by gadicc** [meteor/meteor#3977]
Hey,

I can't publish one of my [packages](https://github.com/gadicc/meteor-messageformat/commit/98db047e6acdfe2da332483b85883594ad42d6de) with the latest release (v1.0.4.1).

There were no major changes in the code, and `meteor --release 1.0.3 publish` worked fine (sorry, was a bit rushed to try all the versions in between but happy to do this over the weekend if it helps and the error below isn't obvious).  I'm guessing it's because of my Npm.depends(), but there's no binary component and of course, it used to publish and work fine.  Error is:

```
/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot call method 'toString' of undefined
    at uploadFile (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/package-client.js:331:34)
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/package-client.js:413:5
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at publishBuiltPackage (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/package-client.js:412:16)
    at Object.exports.publishPackage (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/package-client.js:782:7)
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-packages.js:424:21
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:245:19)
    at Object.main.captureAndExit (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:267:29)
    at Command.main.registerCommand.name [as func] (/home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-packages.js:420:8)
    at /home/dragon/.meteor/packages/meteor-tool/.1.0.43.jpklcu++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:1345:23
```

**Comment by ekatek** [comment]
Thanks for the bug report. It seems that you are running into a problem uploading some files. I can't replicate it -- does it come up every time you run with 1.0.4.1? If it broke once, and then fixed itself with 1.0.3, it might be a transient issue with a net connection or something.

Unrelated, there is also an error handling bug, since instead of displaying the error that you actually got, Meteor crashes. I have pushed a fix to devel. Going to close, but feel free to reopen if it recurs, especially with the better error message.
