### ISSUE TITLE
meteor install-sdk android failed

### ISSUE THREAD

**Issue by qdsang** [meteor/meteor#3996]
```
# meteor install-sdk android
Installing Android bundle
✓ A JDK is installed
Installing Android Platform tools

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
```
```
# ping 54.236.212.79
PING 54.236.212.79 (54.236.212.79): 56 data bytes
Request timeout for icmp_seq 0
```

I was in China.

Is there a solution?

**Comment by qdsang** [comment]
https://warehouse.meteor.com/cordova/android_bundle_Darwin_0.1.tar.gz
