### ISSUE TITLE
Error: Failed to install android target: build-tools-21.0.0

### ISSUE THREAD

**Issue by lenville** [meteor/meteor#4047]
I already installed JDK and HAXM by following [Mobile Dev Install: Android on Mac](https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Mac)

But I got this when running `meteor install-sdk android`

```
✓ Found Android bundle
✓ A JDK is installed
✓ Found Android Platform tools
Installing Android Build Tools

/Users/lenville/.meteor/packages/meteor-tool/.1.0.45.1y6cwq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: Failed to install android target: build-tools-21.0.0
    at [object Object]._.extend.installTarget (/Users/lenville/.meteor/packages/meteor-tool/.1.0.45.1y6cwq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:2256:15)
    at [object Object]._.extend.checkRequirements (/Users/lenville/.meteor/packages/meteor-tool/.1.0.45.1y6cwq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:2822:16)
    at checkPlatformRequirements (/Users/lenville/.meteor/packages/meteor-tool/.1.0.45.1y6cwq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:1342:20)
    at Command.func (/Users/lenville/.meteor/packages/meteor-tool/.1.0.45.1y6cwq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3199:19)
    at /Users/lenville/.meteor/packages/meteor-tool/.1.0.45.1y6cwq8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1345:23
```

Please help me : )

**Comment by lenville** [comment]
I've resolved this problem cause Chinese Great Firewall block all the *.google.com domains. And I manually get all needed resources prepared. 

It would be better if tools can be downloaded from a mirror site instead of Google.com. : )

**Comment by glasser** [comment]
Sorry to hear that your government is preventing you from installing our software. I'm not sure what exactly we can do in this case; I'm happy to hear that you were able to install it eventually.

**Comment by steve-zhang** [comment]
@lenville I got the problem too. My PC OS is Ubuntu14.04. I am also in China. How do u get the needed resources?
Can u help me with that? Thank u~

**Comment by lenville** [comment]
@steve-zhang 
可以参考 [Android SDK开发包国内下载地址](http://www.cnblogs.com/bjzhanghao/archive/2012/11/14/android-platform-sdk-download-mirror.html) 尝试手动部署

**Comment by zerosoul** [comment]
@lenville thanks,I solve it using vpn 😄
