### ISSUE TITLE
Android build hangs at "Installing Cordova plugins"

### ISSUE THREAD

**Issue by afuhrtrumpet** [meteor/meteor#4068]
I followed the instructions on the Wiki for running a Meteor app in Android; however, when I tried to do `meteor run android`, the command goes through all the steps fluidly until it gets to `Installing Cordova plugins`, in which it hangs infinitely with the rotating line.

I am running this on Ubuntu 14.04 64-bit with all the proper 32-bit libraries and Android SDK installed, if that helps.

**Comment by glasser** [comment]
Can you  try `meteor run -v android` and paste the full output here?

**Comment by glasser** [comment]
Also, it's quite likely that this depends on the Cordova plugins you're using in your app (or a package you use is using).

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by afuhrtrumpet** [comment]
Here's the output of `meteor run -v android`:

```
% Parsing the --port option                   
% Will compile mobile builds                  
Local package version is up-to-date: autopublish@1.0.3
Local package version is up-to-date: blaze@2.1.0
Local package version is up-to-date: random@1.0.3
Local package version is up-to-date: mobile-status-bar@1.0.3
Local package version is up-to-date: deps@1.0.7
Local package version is up-to-date: spacebars@1.0.6
Local package version is up-to-date: spacebars-compiler@1.0.5
Local package version is up-to-date: facebook@1.2.0
Local package version is up-to-date: launch-screen@1.0.2
Local package version is up-to-date: http@1.1.0
Local package version is up-to-date: json@1.0.3
Local package version is up-to-date: check@1.0.5
Local package version is up-to-date: meteorhacks:async@1.0.0
Local package version is up-to-date: retry@1.0.3
Local package version is up-to-date: id-map@1.0.3
Local package version is up-to-date: reactive-dict@1.1.0
Local package version is up-to-date: callback-hook@1.0.3
Local package version is up-to-date: meteor@1.1.5
Local package version is up-to-date: tarang:gcm@0.2.0
Local package version is up-to-date: fastclick@1.0.3
Local package version is up-to-date: minifiers@1.1.4
Local package version is up-to-date: accounts-facebook@1.0.4
Local package version is up-to-date: webapp@1.2.0
Local package version is up-to-date: ejson@1.0.6
Local package version is up-to-date: base64@1.0.3
Local package version is up-to-date: url@1.0.4
Local package version is up-to-date: localstorage@1.0.3
Local package version is up-to-date: accounts-oauth@1.1.4
Local package version is up-to-date: blaze-tools@1.0.3
Local package version is up-to-date: ddp@1.1.0
Local package version is up-to-date: observe-sequence@1.0.5
Local package version is up-to-date: reactive-var@1.0.5
Local package version is up-to-date: webapp-hashing@1.0.3
Local package version is up-to-date: mongo@1.1.0
Local package version is up-to-date: htmljs@1.0.4
Local package version is up-to-date: ui@1.0.6 
Local package version is up-to-date: meteor-platform@1.2.2
Local package version is up-to-date: ordered-dict@1.0.3
Local package version is up-to-date: session@1.1.0
Local package version is up-to-date: livedata@1.0.13
Local package version is up-to-date: meteorhacks:npm@1.3.0
Local package version is up-to-date: oauth@1.1.4
Local package version is up-to-date: templating@1.1.0
Local package version is up-to-date: binary-heap@1.0.3
Local package version is up-to-date: accounts-base@1.2.0
Local package version is up-to-date: tracker@1.0.6
Local package version is up-to-date: autoupdate@1.2.0
Local package version is up-to-date: html-tools@1.0.4
Local package version is up-to-date: reload@1.1.3
Local package version is up-to-date: less@1.0.13
Local package version is up-to-date: underscore@1.0.3
Local package version is up-to-date: oauth2@1.1.3
Local package version is up-to-date: routepolicy@1.0.5
Local package version is up-to-date: accounts-ui@1.1.5
Local package version is up-to-date: insecure@1.0.3
Local package version is up-to-date: geojson-utils@1.0.3
Local package version is up-to-date: minimongo@1.0.7
Local package version is up-to-date: accounts-ui-unstyled@1.1.7
Local package version is up-to-date: jquery@1.11.3_2
Local package version is up-to-date: service-configuration@1.0.4
Local package version is up-to-date: boilerplate-generator@1.0.3
Local package version is up-to-date: logging@1.0.7
% Running build for platforms: [ 'android' ]  
Running command  which jarsigner              
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/share/lilypond/2.16.2/scm/:~/lilypond/usr/bin/:~/lein:/usr/local/heroku/bin:/home/alex/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/alex/arm-2008q3/bin:/home/alex/esp-open-sdk/xtensa-lx106-elf/bin:/home/alex/.meteor/android_bundle/android-sdk/tools:/home/alex/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/alex/.meteor/android_bundle
/home/alex/.meteor/android_bundle/android-sdk/build-tools/21.0.0/aapt version
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/share/lilypond/2.16.2/scm/:~/lilypond/usr/bin/:~/lein:/usr/local/heroku/bin:/home/alex/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/alex/arm-2008q3/bin:/home/alex/esp-open-sdk/xtensa-lx106-elf/bin:/home/alex/.meteor/android_bundle/android-sdk/tools:/home/alex/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/alex/.meteor/android_bundle  /home/alex/.meteor/android_bundle/android-sdk/tools/android list
target
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/share/lilypond/2.16.2/scm/:~/lilypond/usr/bin/:~/lein:/usr/local/heroku/bin:/home/alex/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/alex/arm-2008q3/bin:/home/alex/esp-open-sdk/xtensa-lx106-elf/bin:/home/alex/.meteor/android_bundle/android-sdk/tools:/home/alex/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/alex/.meteor/android_bundle  /home/alex/.meteor/android_bundle/android-sdk/tools/android list
avd --compact
Found AVDS: [ 'meteor', '' ]                  
Found /dev/kvm                                
% Building the cordova build project          
% Bundling the web.cordova program of the app 
% Ensuring the cordova build project          
% Reading the mobile control file             
% Running the mobile control file             
% Copying resources for mobile apps           
% Writing new config.xml                      
% Ensuring that platforms in cordova build project are in sync
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
% Running synchronously:  /home/alex/.meteor/packages/meteor-tool/.1.0.45.1f817vb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
% The output of `cordova platforms list`: Installed platforms: android broken
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ubuntu

% Ensuring plugins in the cordova build project are in sync { 'org.apache.cordova.console': '0.2.13',
  'org.apache.cordova.file': '1.3.3',
  'org.apache.cordova.file-transfer': '0.5.0',
  'org.apache.cordova.inappbrowser': '0.6.0',
  'org.apache.cordova.device': '0.2.13',
  'com.meteor.cordova-update': 'https://github.com/meteor/com.meteor.cordova-update/tarball/92fe99b7248075318f6446b288995d4381d24cd2',
  'org.apache.cordova.statusbar': '0.1.10',
  'org.apache.cordova.splashscreen': '1.0.0' }
% Getting installed plugins for project       
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
% Running synchronously:  /home/alex/.meteor/packages/meteor-tool/.1.0.45.1f817vb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'list' ]
% The output of `cordova plugins list`: org.apache.cordova.console 0.2.13 "Console"

% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins file was not found.     
% Getting installed plugins for project       
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
% Running synchronously:  /home/alex/.meteor/packages/meteor-tool/.1.0.45.1f817vb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'list' ]
% The output of `cordova plugins list`: org.apache.cordova.console 0.2.13 "Console"

% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins file was not found.     
% Uninstalling a plugin org.apache.cordova.console
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
% Running synchronously:  /home/alex/.meteor/packages/meteor-tool/.1.0.45.1f817vb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'rm', 'org.apache.cordova.console' ]
% Plugin removal threw an error: Error running /home/alex/.meteor/packages/meteor-tool/.1.0.45.1f817vb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh
Error: /media/alex/Data/HackPSU/meteor/.meteor/local/cordova-build/platforms/android/cordova/version: Command failed with exit code EACCES
    at ChildProcess.whenDone (/home/alex/.meteor/packages/meteor-tool/.1.0.45.1f817vb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:818:12)


Uninstalling org.apache.cordova.console from android


% Getting installed plugins for project       
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
% Running synchronously:  /home/alex/.meteor/packages/meteor-tool/.1.0.45.1f817vb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'list' ]
% The output of `cordova plugins list`: org.apache.cordova.console 0.2.13 "Console"

% Will check for cordova-tarball-plugins.json for tarball-url-based plugins previously installed.
% The tarball plugins file was not found.     
% Uninstalling a plugin org.apache.cordova.console
Using (built-in) Android SDK at /home/alex/.meteor/android_bundle/android-sdk
% Running synchronously:  /home/alex/.meteor/packages/meteor-tool/.1.0.45.1f817vb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh [ 'plugin', 'rm', 'org.apache.cordova.console' ]
```
The portion starting at `Uninstalling org.apache.cordova.console from android` repeats in the console inifinitely.

Reproduction:
1. Have a Meteor app on Ubuntu 64-bit.
2. `sudo apt-get install lib32z1 lib32stdc++6`
3. `meteor install-sdk android`
4. `meteor add-platform android`
5. `meteor run android`

**Comment by glasser** [comment]
So, the fact that it retries indefinitely without printing errors is a bug.

To fix your particular issue, it sounds like there's a permissions problem, probably on `/media/alex/Data/HackPSU/meteor/.meteor/local/cordova-build/platforms/android/cordova/version`.  Did you run with sudo at some point and is this file unreadable, or something?

I will try to reproduce based on your instructions.

**Comment by glasser** [comment]
I was unable to reproduce.  Here's a log of what I did (it went on to fail to run the emulator because I was logged in over SSH, but it made it through cordova build).

https://gist.github.com/glasser/287c5bb1880a4c9ecfdf

**Comment by fabyeah** [comment]
I had the same problem. For me it was a permissions problem, as @glasser said.

Though I am a windows dev and was dual booting linux. So I tried to do the <code>meteor run android</code> on my NTFS windows drive.
To make permissions work for an NTFS drive, follow the instructions here: 

http://ubuntuforums.org/showthread.php?t=1604251
