### ISSUE TITLE
Ignore old cordova plugins when adding platform

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4071]
I do 

`meteor remove cordova:nl.x-services.plugins.launchmyapp`

I verify it is no longer in `.meteor/cordova-plugins`. Then I do:

`meteor remove-platform ios`

Note at this point that there is still a 

`.meteor/local/cordova-build/local-plugins/nl.x-services.plugins.launchmyapp` 

directory. I then do

```
$ meteor add-platform ios
                                              
/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Error running /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Failed to install 'nl.x-services.plugins.launchmyapp':Error: Variable(s) missing: URL_SCHEME
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:304:23
    at _fulfilled (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
Error: Variable(s) missing: URL_SCHEME
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:304:23
    at _fulfilled (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)


Creating ios project...
Installing "com.ionic.keyboard" for ios
Installing "com.meteor.cordova-update" for ios
Installing "com.verso.cordova.clipboard" for ios
Installing "nl.x-services.plugins.launchmyapp" for ios


    at execFileSyncOrThrow (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:272:11)
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:428:7
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at ensureCordovaPlatforms (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:422:5)
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3020:5
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Command.main.registerCommand.name [as func] (/Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3015:16)
    at /Users/me/.meteor/packages/meteor-tool/.1.0.45.1tdtw13++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1345:23
```

The plugin does require a URL arg, but it shouldn't matter because the plugin should be ignored b/c it's no longer in `cordova-plugins`.

A second time:

```
$ meteor add-platform ios
                                              
                                              
While adding platforms:
error: ios: platform is already added
```

After manually deleting 

`.meteor/local/cordova-build/`

it completes successfully:

```
$ meteor remove-platform ios
$ meteor add-platform ios  
ios: added platform         
```

**Comment by glasser** [comment]
That does seem like a bug, but it will definitely be easier for us to test and fix it if you provide a full reproduction as described in https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  You gave a bunch of useful and clear steps, but not a starting point :)

**Comment by martijnwalraven** [comment]
Is this still an issue with the updated Cordova integration in Meteor 1.2?

**Comment by lorensr** [comment]
Nope
