### ISSUE TITLE
android builds fail on 1.1

### ISSUE THREAD

**Issue by dcsan** [meteor/meteor#4081]
I think there are other reports #4076 of android build failing for 1.0.4
i'm also having problems with 1.1

```
app> meteor --version
Meteor 1.1

> java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)



/Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: ENOENT, readdir '/Users/dc/dev/shumi/chatu/app/.meteor/local/cordova-build/platforms/android/ant-build'
  at Object.Future.wait (/Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
  at Object.wrapper (/Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
  at findApkPath (/Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:965:30)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:950:21
  at Array.forEach (native)
  at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at buildCommand (/Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:933:29)
  at Command.main.registerCommand._.extend.name [as func] (/Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands.js:746:12)
  at /Users/dc/.meteor/packages/meteor-tool/.1.1.1.3ik08l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23

    - - - - -
```

**Comment by dcsan** [comment]
> cat app/.meteor/release 
METEOR@1.0.4

but same problem. I need to find some :goat: :goat: goats for the cordova gods. 
this was working before!

**Comment by dcsan** [comment]
for others stepping back to find a working version
1.0.3 introduced this change I guess, which was a cordova thing afair

    #<Object> has no method 'accessRule'
    at mobile-config.js:80:5

**Comment by dcsan** [comment]
oops i think this was caused by a java update breaking something. fixing now.

**Comment by glasser** [comment]
Great to hear you were able to fix it.
