### ISSUE TITLE
meteor install-sdk android failed

### ISSUE THREAD

**Issue by a1305315624** [meteor/meteor#4127]
# meteor install-sdk android
✓ Found Android bundle
✓ A JDK is installed                          
✓ Found Android Platform tools                
Installing Android Build Tools                
                                              
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at Pipe.onread (net.js:559:19)

Working:
             ubuntu 14.04
             meteor 1.1.0.1

I was in China.
Is there a solution?

**Comment by a1305315624** [comment]
To solve the problem
need vpn.......
