### ISSUE TITLE
bcrypt Error: based in node v0.12* 

### ISSUE THREAD

**Issue by struCoder** [meteor/meteor#4143]
+  meteor build --directory ../build --> okay
+  pm2 start main.js -n appName -->error  

the Error: 
```javascript
Error: Module did not self-register.
itodoPro-9 (err):     at Error (native)
itodoPro-9 (err):     at Module.load (module.js:355:32)
itodoPro-9 (err):     at Function.Module._load (module.js:310:12)
itodoPro-9 (err):     at Module.require (module.js:365:17)
itodoPro-9 (err):     at require (module.js:384:17)
itodoPro-9 (err):     at bindings (/home/strucoder/personal/itodoPro/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
itodoPro-9 (err):     at Object.<anonymous> (/home/strucoder/personal/itodoPro/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
itodoPro-9 (err):     at Module._compile (module.js:460:26)
itodoPro-9 (err):     at Object.Module._extensions..js (module.js:478:10)
itodoPro-9 (err):     at Module.load (module.js:355:32)
```  
in production env i must use node v0.10?

**Comment by Slava** [comment]
As of Meteor 1.1.0.2, Meteor only supports node 0.10. We do plan to upgrade to 0.12 in the near future: https://github.com/meteor/meteor/issues/3666.
