### ISSUE TITLE
Can't load isopacket before it has been verified: js-analyze

### ISSUE THREAD

**Issue by ImNotMyself** [meteor/meteor#4157]
Following the guide **Slow Start (for developers)**

``` shell
git clone git://github.com/meteor/meteor.git
cd meteor
./meteor --help
```

It throw me the exception

```
js-analyze: updating npm dependencies -- esprima, escope...

C:\Users\ImNotMyself\GitHub\meteor\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Can't load isopacket before it has been verified: js-analyze
    at Error (<anonymous>)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:94:13
    at Object.exports.noYieldsAllowed (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:66:14)

    at Object.load (C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:80:23)
    at compileUnibuild (C:\Users\ImNotMyself\GitHub\meteor\tools\compiler.js:792:28)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\compiler.js:136:26
.....
```

I have tried under Windows and RedHat Linux, the same error :( 

I have no admin right to install the meteor. The **Slow Start (for developers)** is only way I found to enjoy meteor without installation.

Waiting for your advise.

**Comment by glasser** [comment]
Please show the full stack trace instead of cutting off with `....`.

**Comment by ImNotMyself** [comment]
Sorry that I am late to reply you @glasser . 
But I have fixed this issue after tried  serval hours by myself , ( Goolge, Stackover were not help :-( )

It is due to the proxy setting. My default setting in env variable with the form `http_proxy=http://DOMAIN\USERNAME:PASSWORD@PROXYIP:PROXYPORT` was not work and threw the error above. It seems npm not accepted this setting and can not check out the packages dependencies. (no .npm folder under \meteor\packages\js-analyze)

After change to `http_proxy=http://USERNAME:PASSWORD@PROXYIP:PROXYPORT`, anything all right.

Although my issue fixed, the error log seems was quite cofusing in fact. 
The reproduced full stack for your convenience: 

```shell
C:\Users\ImNotMyself\GitHub\meteor\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Can't load isopacket before it has been verified: js-analyze
    at Error (<anonymous>)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:94:13
    at Object.exports.noYieldsAllowed (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:66:14)

    at Object.load (C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:80:23)
    at compileUnibuild (C:\Users\ImNotMyself\GitHub\meteor\tools\compiler.js:792:28)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\compiler.js:136:26
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\ImNotMyself\GitHub\meteor\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Object.compiler.compile (C:\Users\ImNotMyself\GitHub\meteor\tools\compiler.js:132:5)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:224:30
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:317:26)
    at [object Object]._.extend._loadLocalPackage (C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:198:18)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:149:14
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:317:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:141:20)
    at ensureLoaded (C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:116:12)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:143:11
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\ImNotMyself\GitHub\meteor\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:142:11
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:317:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:141:20)
    at ensureLoaded (C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:116:12)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:143:11
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\ImNotMyself\GitHub\meteor\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:142:11
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:317:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:141:20)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:59:14
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\ImNotMyself\GitHub\meteor\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at [object Object]._.extend.buildLocalPackages (C:\Users\ImNotMyself\GitHub\meteor\tools\isopack-cache.js:58:9)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:166:46
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:317:26)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:162:22
    at Function._.each._.forEach (C:\Users\ImNotMyself\GitHub\meteor\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:133:9
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\ImNotMyself\GitHub\meteor\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\ImNotMyself\GitHub\meteor\tools\buildmessage.js:245:19)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:132:25
    at [object Object]._.extend.withProgressDisplayVisible (C:\Users\ImNotMyself\GitHub\meteor\tools\console.js:612:14)
    at Object.ensureIsopacketsLoadable (C:\Users\ImNotMyself\GitHub\meteor\tools\isopackets.js:131:26)
    at C:\Users\ImNotMyself\GitHub\meteor\tools\main.js:738:30
```

**Comment by flyandi** [comment]
Getting the same issue

**Comment by abernix** [comment]
I think this old issue can serve as documentation for this very uncommon issue in the case that it needs to be revisited.  I'm not even sure this error could be encountered anymore in quite the same way.  Thanks for reporting it though!
