### ISSUE TITLE
Getting error when build after update to latest version (1.1.0.2)

### ISSUE THREAD

**Issue by brugnara** [meteor/meteor#4178]
I'm getting this error launching `meteor build ../build --server=mybuild.mysite.com`
(`meteor build --directory ../build ...` gives same error).

Debian 7. No probles building on osx with `-- architecture=os.linux.x86_64` and then running on the server.
```
/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259
			throw new Error('Must throw non-empty error');
			      ^
Error: Must throw non-empty error
    at Object.Future.throw (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259:10)
    at Extract.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:697:42)
    at Extract.emit (events.js:117:20)
    at DirWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/tar/lib/extract.js:61:8)
    at DirWriter.emit (events.js:117:20)
    at FileWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/dir-writer.js:158:12)
    at FileWriter.emit (events.js:117:20)
    at WriteStream.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/file-writer.js:50:47)
    at WriteStream.emit (events.js:95:17)
    at onwriteError (_stream_writable.js:239:10)
    at onwrite (_stream_writable.js:257:5)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at evalmachine.<anonymous>:1692:14
    at Object.wrapper [as oncomplete] (evalmachine.<anonymous>:522:5)
```

**Comment by glasser** [comment]
Looks like an error handling bug in the fstream module:

https://github.com/npm/fstream/blob/master/lib/file-writer.js#L50

That line sure ought to actually be passing an error from `_stream` into the next level of emitting...

If you go into `/root/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/file-writer.js` and change line 50 temporarily to 

```
  self._stream.on('error', function (e) { self.emit('error', e) })
```

and try again, you should get a better error message.

(Which maybe is "out of disk" or a permission error or something.)

**Comment by glasser** [comment]
See also https://github.com/npm/fstream/pull/43

**Comment by brugnara** [comment]
Very interesting. That gave me a `Error: ENOSPC, write`. Now I know how to solve this, many thanks for this :+1:

**Comment by glasser** [comment]
Since this is a combination of no disk space and an error-handling bug in another module (that's already been reported), I'm going to close this issue.

**Comment by j6k4m8** [comment]
On Ubuntu 14.04, from my experience, the background meteor update maxed out the `/tmp` directory. Check out a possible solution [here](http://stackoverflow.com/questions/27405566/after-1-0-1-update-meteor-is-filling-up-tmp-folder).

**Comment by nisdis** [comment]
Will try them all out, I have the same error with Meteor 1.3 update
