### ISSUE TITLE
Error starting built app on SunOS

### ISSUE THREAD

**Issue by geekrohit** [meteor/meteor#4188]
Hi,

Am trying to run a meteor app, built for deployment using meteor build. Issue is, when running it, 
getting this error : 
/root/build/bundle/programs/server/node_modules/fibers/future.js:173
throw(ex);
^
Error: ld.so.1: node: fatal: illegal mode: potential multiple path expansion requires RTLD_FIRST
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/root/build/bundle/programs/server/npm/lookback:emails/node_modules/node-sass/lib/index.js:188:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.Npm.require (/root/build/bundle/programs/server/boot.js:136:18)

**Comment by geekrohit** [comment]
Turns out, its because there is a " : " in the directory name, lookback:emails. Can anything be done ? Will package still function without the colon in path ?

**Comment by glasser** [comment]
Meteor does not support SunOS (see eg #736).

However, this is surprising since we should convert that colon to an underscore (Windows needs this too), and when I tested it with 1.1.0.2 on OSX it did convert to `lookback_emails`.  You did not mention what version of Meteor you are running so I assume it was an old version that didn't do this conversion.

**Comment by geekrohit** [comment]
If the new version supports converting to _, that would be great, and save me time for recompiling node.js with patches.
I know meteor cli tool doesn't support SunOS, but there is no reason for the built app using meteor build (on a linux build machine) to not run on SunOS.

**Comment by geekrohit** [comment]
Am using 1.0.3.1 currently.

**Comment by glasser** [comment]
Well, try upgrading, since a newer version (not sure if it's 1.0.4 or 1.1) should stop using colons.

**Comment by geekrohit** [comment]
Yeah, that worked. Thanks, even if you won't support SunOS, or atleast make it easier to deploy, by not bundling binaries.
