### ISSUE TITLE
Meteor continually restarting with exit code 1 after encountering uncaughtException

### ISSUE THREAD

**Issue by eeiswerth** [meteor/meteor#4245]
This morning I was using a reverse geocoder, which was setup to use OpenStreetMaps (OSM).  OSM was down this morning and as a result I saw the following in my console:

```
=> Meteor server restarted                    
=> Exited with code: 1
=> Meteor server restarted                    
=> Exited with code: 1
=> Meteor server restarted                    
=> Exited with code: 1
=> Meteor server restarted                    
=> Exited with code: 1
=> Meteor server restarted                    
=> Exited with code: 1
=> Meteor server restarted                    
=> Exited with code: 1
=> Meteor server restarted  
```

The UI appeared to be hanging. Digging deeper I saw this in the logs:

```
Apr 20 09:04:16 my-server default:  error: uncaughtException: getaddrinfo ENOTFOUND 
Apr 20 09:04:16 my-server default:  error:     { date: 'Mon Apr 20 2015 09:04:16 GMT-0400 (EDT)', 
Apr 20 09:04:16 my-server default:  error:       process:  
Apr 20 09:04:16 my-server default:  error:        { pid: 10054, 
Apr 20 09:04:16 my-server default:  error:          uid: 1000, 
Apr 20 09:04:16 my-server default:  error:          gid: 1000, 
Apr 20 09:04:16 my-server default:  error:          cwd: '/home/eeiswerth/app/.meteor/local/build/programs/server', 
Apr 20 09:04:16 my-server default:  error:          execPath: '/home/eeiswerth/.meteor/packages/meteor-tool/.1.1.3.f40tp3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node', 
Apr 20 09:04:16 my-server default:  error:          version: 'v0.10.36', 
Apr 20 09:04:16 my-server default:  error:          argv:  
Apr 20 09:04:16 my-server default:  error:           [ '/home/eeiswerth/.meteor/packages/meteor-tool/.1.1.3.f40tp3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node', 
Apr 20 09:04:16 my-server default:  error:             '/home/eeiswerth/app/.meteor/local/build/main.js', 
Apr 20 09:04:16 my-server default:  error:             'program.json' ], 
Apr 20 09:04:16 my-server default:  error:          memoryUsage:  
Apr 20 09:04:16 my-server default:  error:           { rss: 155267072, 
Apr 20 09:04:16 my-server default:  error:             heapTotal: 87106048, 
Apr 20 09:04:16 my-server default:  error:             heapUsed: 56642320 } }, 
Apr 20 09:04:16 my-server default:  error:       os:  
Apr 20 09:04:16 my-server default:  error:        { loadavg:  
Apr 20 09:04:16 my-server default:  error:           [ 0.26025390625, 
Apr 20 09:04:16 my-server default:  error:             0.35009765625, 
Apr 20 09:04:16 my-server default:  error:             0.34375 ], 
Apr 20 09:04:16 my-server default:  error:          uptime: 609062.734307007 }, 
Apr 20 09:04:16 my-server default:  error:       trace:  
Apr 20 09:04:16 my-server default:  error:        [ { column: 18, 
Apr 20 09:04:16 my-server default:  error:            file: '/home/eeiswerth/.meteor/packages/aldeed_geocoder/.0.3.6.vumtgx++os+web.browser+web.cordova/npm/node_modules/node-geocoder/lib/httpadapter/httpadapter.js', 
Apr 20 09:04:16 my-server default:  error:            function: '', 
Apr 20 09:04:16 my-server default:  error:            line: 51, 
Apr 20 09:04:16 my-server default:  error:            method: null, 
Apr 20 09:04:16 my-server default:  error:            native: false }, 
Apr 20 09:04:16 my-server default:  error:          { column: 17, 
Apr 20 09:04:16 my-server default:  error:            file: 'events.js', 
Apr 20 09:04:16 my-server default:  error:            function: 'ClientRequest.emit', 
Apr 20 09:04:16 my-server default:  error:            line: 95, 
Apr 20 09:04:16 my-server default:  error:            method: 'emit', 
Apr 20 09:04:16 my-server default:  error:            native: false }, 
Apr 20 09:04:16 my-server default:  error:          { column: 9, 
Apr 20 09:04:16 my-server default:  error:            file: 'http.js', 
Apr 20 09:04:16 my-server default:  error:            function: 'CleartextStream.socketErrorListener', 
Apr 20 09:04:16 my-server default:  error:            line: 1552, 
Apr 20 09:04:16 my-server default:  error:            method: 'socketErrorListener', 
Apr 20 09:04:16 my-server default:  error:            native: false }, 
Apr 20 09:04:16 my-server default:  error:          { column: 17, 
Apr 20 09:04:16 my-server default:  error:            file: 'events.js', 
Apr 20 09:04:16 my-server default:  error:            function: 'CleartextStream.emit', 
Apr 20 09:04:16 my-server default:  error:            line: 95, 
Apr 20 09:04:16 my-server default:  error:            method: 'emit', 
Apr 20 09:04:16 my-server default:  error:            native: false }, 
Apr 20 09:04:16 my-server default:  error:          { column: 17, 
Apr 20 09:04:16 my-server default:  error:            file: 'tls.js', 
Apr 20 09:04:16 my-server default:  error:            function: 'Socket.onerror', 
Apr 20 09:04:16 my-server default:  error:            line: 1456, 
Apr 20 09:04:16 my-server default:  error:            method: 'onerror', 
Apr 20 09:04:16 my-server default:  error:            native: false }, 
Apr 20 09:04:16 my-server default:  error:          { column: 20, 
Apr 20 09:04:16 my-server default:  error:            file: 'events.js', 
Apr 20 09:04:16 my-server default:  error:            function: 'Socket.emit', 
Apr 20 09:04:16 my-server default:  error:            line: 117, 
Apr 20 09:04:16 my-server default:  error:            method: 'emit', 
Apr 20 09:04:16 my-server default:  error:            native: false }, 
Apr 20 09:04:16 my-server default:  error:          { column: 16, 
Apr 20 09:04:16 my-server default:  error:            file: 'net.js', 
Apr 20 09:04:16 my-server default:  error:            function: null, 
Apr 20 09:04:16 my-server default:  error:            line: 834, 
Apr 20 09:04:16 my-server default:  error:            method: null, 
Apr 20 09:04:16 my-server default:  error:            native: false }, 
Apr 20 09:04:16 my-server default:  error:          { column: 13, 
Apr 20 09:04:16 my-server default:  error:            file: 'node.js', 
Apr 20 09:04:16 my-server default:  error:            function: 'process._tickDomainCallback', 
Apr 20 09:04:16 my-server default:  error:            line: 486, 
Apr 20 09:04:16 my-server default:  error:            method: '_tickDomainCallback', 
Apr 20 09:04:16 my-server default:  error:            native: false } ], 
Apr 20 09:04:16 my-server default:  error:       stack:  
Apr 20 09:04:16 my-server default:  error:        [ 'HttpError: getaddrinfo ENOTFOUND', 
Apr 20 09:04:16 my-server default:  error:          '    at ClientRequest.<anonymous> (/home/eeiswerth/.meteor/packages/aldeed_geocoder/.0.3.6.vumtgx++os+web.browser+web.cordova/npm/node_modules/node-geocoder/lib/httpadapter/httpadapter.js:51:18)',  
Apr 20 09:04:16 my-server default:  error:          '    at ClientRequest.emit (events.js:95:17)', 
Apr 20 09:04:16 my-server default:  error:          '    at CleartextStream.socketErrorListener (http.js:1552:9)', 
Apr 20 09:04:16 my-server default:  error:          '    at CleartextStream.emit (events.js:95:17)', 
Apr 20 09:04:16 my-server default:  error:          '    at Socket.onerror (tls.js:1456:17)', 
Apr 20 09:04:16 my-server default:  error:          '    at Socket.emit (events.js:117:20)', 
Apr 20 09:04:16 my-server default:  error:          '    at net.js:834:16', 
Apr 20 09:04:16 my-server default:  error:          '    at process._tickDomainCallback (node.js:486:13)' ] } 
```

There doesn't seem to be a way to gracefully handle an uncaughtException error. Any ideas for how best to handle the case where a geocode provider isn't available? An in general, handling these uncaughtException errors?

Thanks.

**Comment by glasser** [comment]
This sounds like something that your geocoder module should let you handle (probably by setting an error event handler somewhere).  However, if you really can't handle these errors via a real API, you can use Node's [`process.on('uncaughtException')`](https://nodejs.org/api/process.html#process_event_uncaughtexception).  (There's nothing Meteor-specific here.)
