### ISSUE TITLE
Meteor unstable on windows - Can't render headers after they are sent to the client

### ISSUE THREAD

**Issue by tomitrescak** [meteor/meteor#4253]
Recently I moved one of my Meteor projects to windows since I like Visual Studio. The problem is, that meteor is constantly crashing with a following error:

```
Error: Can't render headers after they are sent to the client.
    at ServerResponse.OutgoingMessage._renderHeaders (http.js:732:11)
    at ServerResponse.writeHead (http.js:1153:20)
    at ProxyServer.<anonymous> (C:\Users\Tomi\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-proxy.js:96:21)
    at ProxyServer.emit (C:\Users\Tomi\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\eventemitter3\index.js:100:27)
    at ClientRequest.proxyError (C:\Users\Tomi\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:140:16
)
    at ClientRequest.emit (events.js:117:20)
    at Socket.socketOnData (http.js:1593:9)
    at TCP.onread (net.js:528:27)
```

Any idea ?
Running the same code on MAC does not produce this error.

**Comment by tomitrescak** [comment]
Interesting observation. The application is failing only when debugging windows from Chrome / Firefox / Explorer are turned on. When I close the javascript console, the application becomes stable. I was able to debug the application running external "Web Console" in Firefox. This definitely needs to be looked at.

**Comment by Dominis13** [comment]
I got the same error on Linux (Ubuntu).
Disable chrome devtools doesn't work - code still crashing. Happens when i'm trying to view image that was uploaded to s3 with transformation. If i get original image - all work fine.
My transformation code

    transformFunc = (fileObj, readStream, writeStream) ->
        gm(readStream, fileObj.name()).resize('281').stream().pipe(writeStream)
    S3opt['transformWrite'] = transformFunc
    thumbStore = new FS.Store.S3("thumbs", S3opt)

    @Photos = new FS.Collection 'photos',
        useHttp: yes
        stores: [photosStore, thumbStore, localThumb],
        filter:
            allow:
                contentTypes: ['image/*']

**Comment by TomFreudenberg** [comment]
Hi, you may check issue #4277. Maybe also in your case the updated npm eventemitter3 raises this problem.

**Comment by glasser** [comment]
Tom, I don't think this looks related at all, since these stack traces indicate that they are running the normal released meteor tool and not a custom built dev bundle.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by Dominis13** [comment]
Ok. I'll try to find time for that today or tomorrow.
