### ISSUE TITLE
Can't rebuild dev bundle without upgrading http-proxy

### ISSUE THREAD

**Issue by TomFreudenberg** [meteor/meteor#4277]
Hi,

when using meteor from checkout and doing `scripts/generate-dev-bundle.sh` then http-proxy will fail. This is due last updated eventemitter3 npm. Any release eventemitter@1.0.0+ will fail running meteor.

<pre>
/private/tmp/meteor/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/private/tmp/meteor/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/private/tmp/meteor/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/private/tmp/meteor/dev_bundle/lib/node_modules/http-proxy/index.js:13:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [object Object]._.extend.start (/private/tmp/meteor/tools/run-proxy.js:38:21)
    at [object Object]._.extend.start (/private/tmp/meteor/tools/run-all.js:128:16)
    at Object.exports.run (/private/tmp/meteor/tools/run-all.js:332:10)
    at Command.doRunCommand [as func] (/private/tmp/meteor/tools/commands.js:392:17)
    at /private/tmp/meteor/tools/main.js:1363:23
</pre>

I have checked, that last working version ist eventemitter3@0.1.6

Problem was detected during discussion on: https://github.com/4commerce-technologies-AG/meteor/issues/13

I pushed a hot fix at: https://github.com/4commerce-technologies-AG/meteor/commit/2ccbb0b1c9993a024b7a9ce73cc05d2eaa7e27c8

Cheers,
Tom

**Comment by TomFreudenberg** [comment]
Short Note: Nobody can run from checkout at the moment.

**Comment by ekatek** [comment]
What OS are you running this on? Can you provide a reproduction, as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by TomFreudenberg** [comment]
Hi Ekatarina ( @ekatek )

the fail is on all OS and all branches cause eventemitter3 and http-proxy is broken.

To reproduce just follow your own guide:

````
# slow start
cd /tmp
git clone git://github.com/meteor/meteor.git
cd meteor
./scripts/generate-dev-bundle.sh
./meteor --version

# create helllo welcome
cd ..
meteor/meteor create helloworld
cd helloworld
../meteor/meteor

>>>> BAM 
````

Cheers
Tom

**Comment by glasser** [comment]
When you say "Nobody can run from checkout" you mean "Nobody can build their own dev bundle from scratch"; most people running from checkout are just using the prebuilt auto-downloaded dev bundles.

Looks like the underlying issue is that `http-proxy` 1.6.0 (which we use) didn't specify its dependency versions well enough.  https://github.com/nodejitsu/node-http-proxy/commit/81874f795b7df7929e03d9d4cb98a947b1ef114b fixed this, in `http-proxy` 1.7.2.  So we should upgrade to at least that version, if not newer.

**Comment by TomFreudenberg** [comment]
Hi David,

to be precise: You can build dev bundle from scratch without errors but the created dev-bundle will not run meteor in case of the above.

But in anyway it is just if you wish to meteor from scratch. Thankful you provide such an option so all the ARM boys and girls :-) are very happy to get meteor on their boards.

If I got you correctly, you will fix the dependency in the next release?

Cheers,
Tom

**Comment by TomFreudenberg** [comment]
This is not existing anymore. Generated dev_bundles of release 1.2+ work without an issue.
