### ISSUE TITLE
Upgrade version of Cordova Bundled w/ Meteor

### ISSUE THREAD

**Issue by alpjor** [meteor/meteor#4292]
on 21 Apr 2015 Apache updated cordova to version 5.0.0 which contains a large number of bug fixes (okay 4.0.0 contains all the bug fixes, 5.0.0 is just a vanity release). When can we expect to be able to upgrade the version of cordova used by Meteor? Is this something that we can do manually?

**Comment by Slava** [comment]
We plan to upgrade but don't have a specific date or an assigned person to do this.

**Comment by alpjor** [comment]
I guess it'll just be a feature request for now. If others see this and want this feature, please comment here, so we can gauge demand.

**Comment by alpjor** [comment]
There are a number of issues with Custom URL Schemes not working properly that are fixed in 4.0.0
https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/2

**Comment by n17r4m** [comment]
Starting up a new meteor - cordova project in a few days, must admit that I would really like to see this in. At the moment, running into difficulties with getting my environment set up, and I bet bumping to 5.0.0 might help.

$ meteor install-sdk android
✓ Found Android bundle
✓ A JDK is installed                          
✓ Found Android Platform tools                
Installing Android Build Tools                
                                              
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at Pipe.onread (net.js:559:19)

**Comment by Slava** [comment]
@n17r4m your error doesn't look related to the Cordova at all? Looks like it failed to install additional Android Build Tools.

**Comment by n17r4m** [comment]
Oh, I don't want to hijack the thread with this. I've already dug into this a bit but hit dead ends, and was hoping a version bump might help..

https://github.com/meteor/meteor/issues/2978
https://github.com/meteor/meteor/issues/2848#issuecomment-59653731

-- oops -- relaunching ./android sdk , and there are a lot of new options which weren't there yesterday. how odd. I'll update this post with results. In short though, getting things set up with meteor install-sdk android is painful at present. *shrugs*

**Comment by yauh** [comment]
Updated Cordova - I'm in.

**Comment by Exilz** [comment]
@yauh +1, we really need this.

**Comment by Slava** [comment]
Anyone knows the details of backwards incompatible changes between Cordova 4 and Cordova 5?

**Comment by dcsan** [comment]
it would be great to get crosswalk (chrome webview) in at the same time. that would probably impact web apps more than upgrading cordova itself.

discussion and work notes here:
https://forums.meteor.com/t/timeline-for-cordova-update/3361/3

**Comment by copleykj** [comment]
@dscan have a look at my post on https://github.com/meteor/meteor/issues/3076

**Comment by Slava** [comment]
The branch `cordova5-update` ships Cordova 5. All the testing was done on that branch. Any further updates would require another round of QA.

**Comment by dcsan** [comment]
> The branch cordova5-update ships Cordova

I was looking for this branch but don't see it as part of main repo?
https://github.com/meteor/meteor/branches/all?utf8=%E2%9C%93&query=cordo
or a cordova subrepo.
https://github.com/meteor/com.meteor.cordova-update

or is it not in the official meteor repo yet, just in @copleykj  ?
in which case 
https://forums.meteor.com/t/timeline-for-cordova-update/3361/3

is the latest info for building with Crosswalk/Cordova5 ?

**Comment by Slava** [comment]
@dcsan I merge the branch to devel and deleted the branch in the repo.https://github.com/meteor/meteor/commit/9b401ace639570892bf41824e60671b2da05f9c2

**Comment by dcsan** [comment]
thanks. So i'm trying to understand the status / how to get a crosswalk build

I did a normal meteor build process with from the devel branch, but it still appears to be using the old webview (is there anyway to be sure? just assuming since some things look different from mobile chrome).

So the devel branch doesn't build by default with chrome/crosswalk, correct?

and these steps still need to be taken?

```
symlink the following packages using ln -s meteor-checkout-dir/packages/packageName

webapp
autoupdate
launch-screen
logging
crosswalk (if you would like to use it instead of the standard webview) - will need to meteor add crosswalk as well
move back to your meteor project dir and use the meteor command in your meteor checkout

meteor-checkout-dir/meteor install-sdk

meteor-checkout-dir/meteor run android-device/android-emulator 
- should now build and install your app
```

is that correct?

**Comment by dcsan** [comment]
@copleykj 

> will need to meteor add crosswalk as well 

where can i get the `meteor crosswalk` package?
is this an mdg package?
https://atmospherejs.com/?q=crosswalk

```
$ meteordev --version
Unreleased (running from a checkout)          

➜  app git:(1247-android-build) ✗ meteordev add crosswalk
=> Running Meteor from a checkout -- overrides project version (Meteor 1.1.0.2)
=> Errors while parsing arguments:            
                                              
While adding package crosswalk:
error: no such package

➜  app git:(1247-android-build) ✗ meteordev update       
You are running Meteor from a checkout, so we cannot update the Meteor release.
Checking to see if we can update your packages.
=> Errors while upgrading packages:           

While selecting package versions:
error: conflict: constraints on meteor-platform cannot be satisfied.
Constraints come from:
  <top level>
```

I assume these notes (from 7 months ago) are not relevant now this is in `devel` branch?
https://meteor.hackpad.com/Building-Meteor-app-with-Crosswalk-kHKh4DzGxFQ

**Comment by copleykj** [comment]
If you are using the devel branch of meteor, the crosswalk package wasn't added due to the issues that can emerge when building the package. Reallly all the package does is relieve you of having to go and find the tarball link for the cordova plugin and add it manually, but you can do that manually with the meteor cli `meteor add cordova:cordova-plugin-crosswalk-webview@https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/tarball/ef4d7244f107c86b85a75edd5492f8e2f63b1bd7`

**Comment by dcsan** [comment]
hey - thanks for that. 
got the build working, signed and installed.

But after installing tho I just get the dreaded 

> "Unfortunately AppName v0.1.1 has stopped." [OK]

with both signed and unsigned, tried on a couple of android 4.4.2 devices.

I note from your forum instructions you mentioned to create symlinks to the various packages but also to the crosswalk package. Or did you just mean that has to be cli installed as a cordova plugin?

currently I just have these symlinks:
```
lrwxr-xr-x  autoupdate -> /Users/dc/dev/ref/meteor/packages/autoupdate
lrwxr-xr-x  launch-screen -> /Users/dc/dev/ref/meteor/packages/launch-screen
lrwxr-xr-x  logging -> /Users/dc/dev/ref/meteor/packages/logging
lrwxr-xr-x  webapp -> /Users/dc/dev/ref/meteor/packages/webapp
```

are there any other suggestions where to start looking, or build options to tweak?

**Comment by alpjor** [comment]
@dcsan You should be "reporting" those crashes, or running them on a sim / connected device so you can see the native stack trace of the error. It could honestly be anything and w/o the stack trace it'll be really hard to track down.

**Comment by copleykj** [comment]
@dcsan the crosswalk package was part of my cordova5-update branch on my fork and part of the PR that I sent.. the package though wasn't included in the merge to meteor/meteor/devel because of build issues with crosswalk itself.

Additional information on the crosswalk cordova plugin can be found at https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview

**Comment by dcsan** [comment]
@alpjor of course. `adb logcat` shows the following on a device

```
D/WfcActivityStateReceiver( 1308): onReceive(): packageName=comic.english.beta, activityState=create
V/SmartFaceService - 3rd party pause(  780): onReceive [android.intent.action.ACTIVITY_STATE/comic.english.beta/create]
D/Launcher( 1512): onTrimMemory. Level: 20
D/KeyguardViewMediator( 1061): setHidden false
D/KeyguardUpdateMonitor( 1061): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1061): handleKeyguardVisibilityChanged(1)
W/ApplicationPackageManager(27223): getCSCPackageItemText()
I/CordovaLog(27223): Changing log level to DEBUG(3)
D/STATUSBAR-NetworkController( 1061): refreshSignalCluster: data=0 bt=false
D/STATUSBAR-IconMerger( 1061): checkOverflow(216), More:true, Req:true Child:12
D/dalvikvm( 1433): GC_CONCURRENT freed 2055K, 32% free 18108K/26476K, paused 2ms+5ms, total 64ms
D/dalvikvm( 1433): WAIT_FOR_CONCURRENT_GC blocked 49ms
W/System.err(27223): java.lang.RuntimeException: Use SharedXWalkView if you want to support shared mode
W/System.err(27223): 	at org.xwalk.core.ReflectionHelper.handleException(ReflectionHelper.java:237)
W/System.err(27223): 	at org.xwalk.core.ReflectionHelper.init(ReflectionHelper.java:132)
W/System.err(27223): 	at org.xwalk.core.ReflectionHelper.loadClass(ReflectionHelper.java:199)
W/System.err(27223): 	at org.xwalk.core.XWalkPreferences.setValue(XWalkPreferences.java:112)
W/System.err(27223): 	at org.crosswalk.engine.XWalkCordovaView.setGlobalPrefs(XWalkCordovaView.java:43)
W/System.err(27223): 	at org.crosswalk.engine.XWalkCordovaView.<init>(XWalkCordovaView.java:50)
W/System.err(27223): 	at org.crosswalk.engine.XWalkWebViewEngine.<init>(XWalkWebViewEngine.java:56)
W/System.err(27223): 	at java.lang.reflect.Constructor.constructNative(Native Method)
W/System.err(27223): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
W/System.err(27223): 	at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:80)
W/System.err(27223): 	at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:191)
W/System.err(27223): 	at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:187)
W/System.err(27223): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:135)
W/System.err(27223): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:209)
W/System.err(27223): 	at comic.english.beta.MainActivity.onCreate(MainActivity.java:32)
W/System.err(27223): 	at android.app.Activity.performCreate(Activity.java:5389)
W/System.err(27223): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
W/System.err(27223): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2246)
W/System.err(27223): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340)
W/System.err(27223): 	at android.app.ActivityThread.access$800(ActivityThread.java:157)
W/System.err(27223): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
W/System.err(27223): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(27223): 	at android.os.Looper.loop(Looper.java:157)
W/System.err(27223): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
W/System.err(27223): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(27223): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(27223): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
W/System.err(27223): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
W/System.err(27223): 	at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime(27223): Shutting down VM
W/dalvikvm(27223): threadid=1: thread exiting with uncaught exception (group=0x417bfda0)
E/AndroidRuntime(27223): FATAL EXCEPTION: main
E/AndroidRuntime(27223): Process: comic.english.beta, PID: 27223
E/AndroidRuntime(27223): java.lang.RuntimeException: Unable to start activity ComponentInfo{comic.english.beta/comic.english.beta.MainActivity}: java.lang.RuntimeException: Failed to create webview. 
E/AndroidRuntime(27223): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
E/AndroidRuntime(27223): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340)
E/AndroidRuntime(27223): 	at android.app.ActivityThread.access$800(ActivityThread.java:157)
E/AndroidRuntime(27223): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
E/AndroidRuntime(27223): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27223): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(27223): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime(27223): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(27223): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(27223): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
E/AndroidRuntime(27223): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
E/AndroidRuntime(27223): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(27223): Caused by: java.lang.RuntimeException: Failed to create webview. 
E/AndroidRuntime(27223): 	at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:82)
E/AndroidRuntime(27223): 	at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:191)
E/AndroidRuntime(27223): 	at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:187)
E/AndroidRuntime(27223): 	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:135)
E/AndroidRuntime(27223): 	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:209)
E/AndroidRuntime(27223): 	at comic.english.beta.MainActivity.onCreate(MainActivity.java:32)
E/AndroidRuntime(27223): 	at android.app.Activity.performCreate(Activity.java:5389)
E/AndroidRuntime(27223): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime(27223): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2246)
E/AndroidRuntime(27223): 	... 11 more
E/AndroidRuntime(27223): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(27223): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(27223): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime(27223): 	at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:80)
E/AndroidRuntime(27223): 	... 19 more
E/AndroidRuntime(27223): Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Use SharedXWalkView if you want to support shared mode
E/AndroidRuntime(27223): 	at org.xwalk.core.ReflectionHelper.handleException(ReflectionHelper.java:233)
E/AndroidRuntime(27223): 	at org.xwalk.core.ReflectionHelper.handleException(ReflectionHelper.java:237)
E/AndroidRuntime(27223): 	at org.xwalk.core.ReflectionHelper.init(ReflectionHelper.java:132)
E/AndroidRuntime(27223): 	at org.xwalk.core.ReflectionHelper.loadClass(ReflectionHelper.java:199)
E/AndroidRuntime(27223): 	at org.xwalk.core.XWalkPreferences.setValue(XWalkPreferences.java:112)
E/AndroidRuntime(27223): 	at org.crosswalk.engine.XWalkCordovaView.setGlobalPrefs(XWalkCordovaView.java:43)
E/AndroidRuntime(27223): 	at org.crosswalk.engine.XWalkCordovaView.<init>(XWalkCordovaView.java:50)
E/AndroidRuntime(27223): 	at org.crosswalk.engine.XWalkWebViewEngine.<init>(XWalkWebViewEngine.java:56)
E/AndroidRuntime(27223): 	... 22 more
E/AndroidRuntime(27223): Caused by: java.lang.RuntimeException: Use SharedXWalkView if you want to support shared mode
E/AndroidRuntime(27223): 	... 29 more
W/ActivityManager(  780):   Force finishing activity comic.english.beta/.MainActivity
W/ContextImpl(  780): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1468 com.android.server.am.AppStateBroadcaster.BroadcastAppState:128 com.android.server.am.AppStateBroadcaster.SendApplicationFocusLoss:40 com.android.server.am.ActivityManagerService$2.handleMessage:2060 android.os.Handler.dispatchMessage:102 
W/ContextImpl(  780): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1468 com.android.server.am.ActivityStack.startPausingLocked:1002 com.android.server.am.ActivityStack.finishActivityLocked:3147 com.android.server.am.ActivityStack.finishTopRunningActivityLocked:2994 com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked:3093 
W/ContextImpl(  780): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1468 com.android.server.am.AppStateBroadcaster.BroadcastAppState:128 com.android.server.am.AppStateBroadcaster.SendApplicationStop:53 com.android.server.am.ActivityManagerService$2.handleMessage:2056 android.os.Handler.dispatchMessage:102 
D/WfcActivityStateReceiver( 1308): onReceive(): packageName=comic.english.beta, activityState=pause
D/CrashAnrDetector(  780): processName: comic.english.beta
D/CrashAnrDetector(  780): broadcastEvent : comic.english.beta data_app_crash
V/SmartFaceService - 3rd party pause(  780): onReceive [android.intent.action.ACTIVITY_STATE/comic.english.beta/pause]
W/ApplicationPackageManager(  780): getCSCPackageItemText()
W/ContextImpl(  780): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1468 com.android.server.analytics.data.collection.application.CrashAnrDetector.broadcastEvent:296 com.android.server.analytics.data.collection.application.CrashAnrDetector.processDropBoxEntry:254 com.android.server.analytics.data.collection.application.CrashAnrDetector.access$100:60 com.android.server.analytics.data.collection.application.CrashAnrDetector$1.onReceive:102 
I/dumpstate(27241): begin
I/SpenGestureManager(  780): setFocusWindow0
D/EnterpriseDeviceManager(  780): ContainerId: 0
D/STATUSBAR-StatusBarManagerService(  780): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
D/PointerIcon(  780): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
D/PointerIcon(  780): setHoveringSpenCustomIcon IconType is same.1
I/SurfaceFlinger(  275): id=343 createSurf (1x1),1 flag=4, ceta
D/KeyguardViewMediator( 1061): setHidden false
D/KeyguardUpdateMonitor( 1061): sendKeyguardVisibilityChanged(true)
D/KeyguardUpdateMonitor( 1061): handleKeyguardVisibilityChanged(1)
D/KeyguardViewMediator( 1061): setHidden false
D/KeyguardUpdateMonitor( 1061): sendKeyguardVisibilityChanged(true)
D/KeyguardViewMediator( 1061): setHidden false
```

**Comment by dcsan** [comment]
A little googling turns up
https://crosswalk-project.org/jira/browse/XWALK-3615

> 2. In embedded mode, the dynamic library was not packaged into apk.

could this be relevant?


https://crosswalk-project.org/jira/si/jira.issueviews:issue-html/XWALK-3380/XWALK-3380.html
```
# go to the platforms/android directory
$ cd ..

# remove the files from the previous Cordova build
$ rm -Rf ant-gen
$ rm -Rf ant-build
```

however even after rm -rf the whole android build/project and clean building, getting the same startup error.


also
http://stackoverflow.com/questions/30354396/crosswalk-crashes-use-sharedxwalkview-if-you-want-to-support-shared-mode

**Comment by leonidez** [comment]
+1

**Comment by henkstom** [comment]
+1

**Comment by veeramarni** [comment]
+1

**Comment by vohtaski** [comment]
+1
