### ISSUE TITLE
error in metoer add-platform android

### ISSUE THREAD

**Issue by shubham-agrawal** [meteor/meteor#4305]
Running command  which jarsigner              

```
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/shubham/.meteor/android_bundle/android-sdk/tools:/home/shubham/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/shubham/.meteor/android_bundle
/home/shubham/.meteor/android_bundle/android-sdk/build-tools/21.0.0/aapt version
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/shubham/.meteor/android_bundle/android-sdk/tools:/home/shubham/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/shubham/.meteor/android_bundle
/home/shubham/.meteor/android_bundle/android-sdk/tools/android list target
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/shubham/.meteor/android_bundle/android-sdk/tools:/home/shubham/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/shubham/.meteor/android_bundle
/home/shubham/.meteor/android_bundle/android-sdk/tools/android list avd
--compact
Found AVDS: [ 'meteor', '' ]                  
Found /dev/kvm                                
Doing HTTP request:  GET                      
https://warehouse.meteor.com/cordova/license_cordova_android.txt
The following terms apply to the Android platform:
                                              
                                              
To get started with the Android SDK, you must agree to the following terms and
conditions.

This is the Android SDK License Agreement (the "License Agreement").
 [terms and condition]  
You must agree to the terms to proceed.       
                                              
Do you agree (Y/n)? y
% Ensuring the cordova build project          
% Ensuring that platforms in cordova build project are in sync
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
% Running synchronously:  /home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'list' ]
% The output of `cordova platforms list`: Installed platforms: 
Available platforms: amazon-fireos, android, blackberry10, browser, firefoxos, ubuntu

% The platform is not in the Cordova project: android
Running command  which jarsigner              
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/shubham/.meteor/android_bundle/android-sdk/tools:/home/shubham/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/shubham/.meteor/android_bundle
/home/shubham/.meteor/android_bundle/android-sdk/build-tools/21.0.0/aapt version
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/shubham/.meteor/android_bundle/android-sdk/tools:/home/shubham/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/shubham/.meteor/android_bundle
/home/shubham/.meteor/android_bundle/android-sdk/tools/android list target
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
Running command                               
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/shubham/.meteor/android_bundle/android-sdk/tools:/home/shubham/.meteor/android_bundle/android-sdk/platform-tools
ANDROID_SDK_HOME=/home/shubham/.meteor/android_bundle
/home/shubham/.meteor/android_bundle/android-sdk/tools/android list avd
--compact
Found AVDS: [ 'meteor', '' ]                  
Found /dev/kvm                                
% Adding a platform android                   
Using (built-in) Android SDK at /home/shubham/.meteor/android_bundle/android-sdk
% Running synchronously:  /home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh [ 'platform', 'add', 'android' ]
                                              
/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Error running /home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova.sh

/home/shubham/.meteor/android_bundle/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:126
                    throw e;
                          ^
Error: ANDROID_HOME is not set and "android" command not in your PATH. You must fulfill at least one of these conditions.
    at /home/shubham/.meteor/android_bundle/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/lib/check_reqs.js:159:19
    at _fulfilled (/home/shubham/.meteor/android_bundle/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/shubham/.meteor/android_bundle/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/shubham/.meteor/android_bundle/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:760:13)
    at /home/shubham/.meteor/android_bundle/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:821:14
    at flush (/home/shubham/.meteor/android_bundle/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
Error: /home/shubham/.meteor/android_bundle/.cordova/lib/npm_cache/cordova-android/3.6.4/package/bin/create: Command failed with exit code 8
    at ChildProcess.whenDone (/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)


Creating android project...


    at execFileSyncOrThrow (/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:272:11)
    at /home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:428:7
    at Array.forEach (native)
    at Function._.each._.forEach (/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at ensureCordovaPlatforms (/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:422:5)
    at /home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:3020:5
    at /home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at Command.main.registerCommand.name [as func] (/home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:3015:16)
    at /home/shubham/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:1363:23
```

**Comment by Slava** [comment]
This log is not enough to understand the source of the problem.

Please follow https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor and provide a full cloneable example with explicit descriptions of what you hope to see and what you actually see.
