### ISSUE TITLE
`add/remove-platform` error: App id contains a reserved word, or is not a valid identifier.

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#4358]
Repro repo: https://github.com/youngfreezy/MeteorTutorial5.11

Behavior occurs when the cloned directory is named `MeteorTutorial5.11` or `MeteorTutorial5.11_copy` but not when it is named `foo`. Related:  #3950 
- `meteor remove-platform ios`: removes it, also gives error:

```
ios: removed platform                         
Error creating Cordova prject: Error running /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
App id contains a reserved word, or is not a valid identifier.


Error: Error running /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
App id contains a reserved word, or is not a valid identifier.


    at execFileSyncOrThrow (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:272:11)
    at ensureCordovaProject (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:376:22)
    at Command.main.registerCommand.name [as func] (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3078:5)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23

/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Error running /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
    at execFileSyncOrThrow (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:272:11)
    at ensureCordovaPlatforms (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:405:23)
    at Command.main.registerCommand.name [as func] (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3079:5)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
```
- `meteor add-platform ios`: Adds it but also gives the error:

```
Error creating Cordova prject: Error running /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
App id contains a reserved word, or is not a valid identifier.


Error: Error running /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
App id contains a reserved word, or is not a valid identifier.


    at execFileSyncOrThrow (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:272:11)
    at ensureCordovaProject (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:376:22)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3019:5
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Command.main.registerCommand.name [as func] (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3015:16)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23

/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Error running /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
    at execFileSyncOrThrow (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:272:11)
    at ensureCordovaPlatforms (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:405:23)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3020:5
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Command.main.registerCommand.name [as func] (/Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3015:16)
    at /Users/me/.meteor/packages/meteor-tool/.1.1.3.14ou92h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
MeteorTutorial5.11 me$ m add-platform ios


While adding platforms:
error: ios: platform is already added

```

**Comment by Slava** [comment]
Try to identify if the problem is in capitalized letters, dots or underscores. Then submit a PR that prints a better error message ;)

**Comment by JanAhrend** [comment]
I encountered the same problem when naming the meteor project "03" or similar. Giving the project another name (like "myapp") 'solved' the problem.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%60add%2Fremove-platform%60%20error%3A%20App%20id%20contains%20a%20reserved%20word%2C%20or%20is%20not%20a%20valid%20identifier.&body=Migrated%20from:%20meteor/meteor%234358) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
