### ISSUE TITLE
forbidClientAccountCreation causes error message in server console

### ISSUE THREAD

**Issue by proehlen** [meteor/meteor#4388]
Adding the following code to my project javascript file:
````
Accounts.config({
    forbidClientAccountCreation: true
});
````

Causes this output on the (locally running) server:

````
=> App running at: http://localhost:3000/
I20150515-02:26:59.753(7)? Exception from sub submissions id QfCnYHfXHK96LHhtB Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
I20150515-02:26:59.754(7)?     at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1)
I20150515-02:26:59.754(7)?     at [object Object].Meteor.startup.Meteor.users.find.sort.createdAt [as _handler] (app/witnessproject.js:133:32)
I20150515-02:26:59.754(7)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150515-02:26:59.754(7)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20150515-02:26:59.754(7)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20150515-02:26:59.755(7)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20150515-02:26:59.755(7)?     at packages/ddp/livedata_server.js:546:1
````

**Comment by proehlen** [comment]
Issue logged in error - cause was not as stated.
