### ISSUE TITLE
meteor stops running [unexpected]

### ISSUE THREAD

**Issue by mrzafod** [meteor/meteor#4405]
Have started meteor today and got next. Nothing was changed. It just stops working
```
/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Match error: Failed Match.OneOf or Match.Optional validation
    at checkSubtree (packages/check/match.js:244:1)
    at check (packages/check/match.js:32:1)
    at new CS.Input (packages/constraint-solver/constraint-solver-input.js:52:1)
    at packages/constraint-solver/constraint-solver.js:46:1
    at Function.time (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/profile.js:231:28)
    at [object Object].CS.PackagesResolver.resolve (packages/constraint-solver/constraint-solver.js:45:1)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/project-context.js:464:35
    at time (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/profile.js:231:28)
    at Function.run (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/profile.js:377:12)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/project-context.js:460:19
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:317:26)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/project-context.js:433:20
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/catalog.js:100:5
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at Object.capture (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/catalog.js:99:31)
    at ProjectContext._.extend._resolveConstraints (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/project-context.js:432:13)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/project-context.js:238:35
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/project-context.js:228:18)
    at ProjectContext._.extend.resolveConstraints (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/project-context.js:207:10)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/commands-packages.js:1586:22
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/fiber-helpers.js:115:14)
    at Object.capture (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/buildmessage.js:245:19)
    at Object.main.captureAndExit (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/main.js:269:29)
    at Command.main.registerCommand.name [as func] (/home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/commands-packages.js:1584:8)
    at /home/roman/.meteor/packages/meteor-tool/.1.1.3.ctcwkh++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/main.js:1363:23
```

**Comment by mrzafod** [comment]
release
```METEOR@1.1.0.2```
versions
```
accounts-base@1.2.0
accounts-password@1.1.1
app@1.0.0
autoupdate@1.2.1
base64@1.0.3
bases@1.0.0
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
cdn@1.0.0
check@1.0.5
classcraft:stylus-autoprefixer@0.0.2
coffeescript@1.0.6
constructor@1.0.0
core@1.0.0
cosmos:browserify@0.1.3
db@1.0.0
ddp@1.1.0
deps@1.0.7
editors@1.0.0
ejson@1.0.6
email@1.0.6
factories@1.0.0
fastclick@1.0.3
geojson-utils@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
mail@1.0.0
markdown@1.0.4
meteor@1.1.6
meteor-platform@1.2.2
meteorhacks:flow-router@1.6.0
meteorhacks:picker@1.0.2
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
models@1.0.0
mongo@1.1.0
mquandalle:jade@0.4.3
mquandalle:jade-compiler@0.4.3
npm-bcrypt@0.7.8_2
observe-sequence@1.0.6
ordered-dict@1.0.3
paper@1.0.0
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
router@1.0.0
seo@1.0.0
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
spacebars@1.0.6
spacebars-compiler@1.0.6
srp@1.0.3
templating@1.1.1
tracker@1.0.7
types@1.0.0
ui@1.0.6
underscore@1.0.3
url@1.0.4
usefulio:sync-methods@0.1.1
users@1.0.0
vschema@1.0.0
web.core@1.0.0
web.style@1.0.0
web.ui@1.0.0
webapp@1.2.0
webapp-hashing@1.0.3
````
platforms
```
server
browser
```
finished-upgrades
```
notices-for-0.9.0
notices-for-0.9.1
0.9.4-platform-file
notices-for-facebook-graph-api-2
```

**Comment by mrzafod** [comment]
found! Meteor do not clear packages list after all external packages have been removed. See versions

**Comment by tmbridge** [comment]
I'm experiencing this issue tonight.  Can you please elaborate a bit more on the solution you found?  I'm new to meteor and I'm not sure what you mean when you say Meteor doesn't clear packages list after all external packages have been removed?

**Comment by glasser** [comment]
I'm not sure what @mrzafod means either, but @tmbridge, if you'd like help, please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.
