### ISSUE TITLE
Accounts-password: bug in forgotPassword?

### ISSUE THREAD

**Issue by christieewen** [meteor/meteor#4427]
I am using the example todos and using {{> loginButtons}}.  I created an account then tried to reset my password via the forget password link and I got the following error:

    I20150521-04:56:41.873(-4)? Exception while invoking method 'forgotPassword' TypeError: Property 'subject' of object #<Object> is not a function
    I20150521-04:56:41.873(-4)?     at Object.Accounts.sendResetPasswordEmail (packages/accounts-password/password_server.js:409:1)
    I20150521-04:56:41.873(-4)?     at [object Object].Meteor.methods.forgotPassword (packages/accounts-password/password_server.js:365:1)
    I20150521-04:56:41.873(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    I20150521-04:56:41.873(-4)?     at packages/ddp/livedata_server.js:648:1
    I20150521-04:56:41.874(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    I20150521-04:56:41.874(-4)?     at packages/ddp/livedata_server.js:647:1
    I20150521-04:56:41.874(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    I20150521-04:56:41.874(-4)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    I20150521-04:56:41.874(-4)?     at packages/ddp/livedata_server.js:546:1

meteor list:

    accounts-password      1.1.1  Password support for accounts
    accounts-ui            1.1.5  Simple templates to add login widgets to an app
    email                  1.0.6  Send email messages
    insecure               1.0.3  Allow all database writes by default
    iron:router            0.9.4* Routing specifically designed for Meteor
    less                   1.0.14  The dynamic stylesheet language
    standard-app-packages  1.0.5  Moved to meteor-platform

**Comment by christieewen** [comment]
Never mind, it's working.  I was missing accounts-base.
