### ISSUE TITLE
error when migrate from windows to mac

### ISSUE THREAD

**Issue by yozawiratama** [meteor/meteor#4440]
I run 'meteor' of meteor project on my mac from windows.
i've tried meteor reset or erase local or meteor update, but it still same.

    Macintosh:iw2 yozawiratama$ meteor
[[[[[ ~/Bitbucket/new-infinite-wars/iw2 ]]]]] 

=> Started proxy.                             
=> Started MongoDB.                           
                                                                                
/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: EACCES, mkdir '/Users/yozawiratama/.meteor/packages/zimme_iron-router-active/.build617010..1.0.4.2wkin1++os+web.browser+web.cordova'
    at Object.Future.wait (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as mkdir] (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1332:24)
    at Object.files.mkdir_p (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:403:11)
    at new Builder (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/builder.js:38:9)
    at [object Object]._.extend.saveToPath (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isopack.js:797:19)
    at [object Object]._.extend._saveIsopack (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tropohouse.js:343:15)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tropohouse.js:475:14
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Object.download (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tropohouse.js:410:20)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tropohouse.js:544:22
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tropohouse.js:541:20)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:641:25
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:640:20
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog.js:96:5
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog.js:95:31)
    at ProjectContext._.extend._downloadMissingPackages (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:639:13)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:228:35
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:218:18)
    at ProjectContext._.extend.saveChangedMetadata (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:206:10)
    at ProjectContext._.extend.prepareProjectForBuild (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:211:10)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:520:29
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
    at bundleApp (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:519:31)
    at [object Object]._.extend._runOnce (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:591:35)
    at [object Object]._.extend._fiber (/Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:821:28)
    at /Users/yozawiratama/.meteor/packages/meteor-tool/.1.1.1-win.7.erufoa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:402:12
    - - - - -

what must i do?

**Comment by ekatek** [comment]
You are running into this at the stage where Meteor tries to download builds of packages (in this case, zimme:iron_router) into the `.meteor/packages` directory in your homedir and can't. (We do this, so that the next time any app that you make uses iron:router, you don't have to re-download it). EACCES typically indicates a permissions error -- does the `/Users/yozawiratama/.meteor/packages` exist? What are the permissions on that directory? Can you run any other `meteor` apps?

**Comment by yozawiratama** [comment]
okay finally i found the way, just use sudo, and everything solve.
