### ISSUE TITLE
Social login popup not closing and logging in with Meteor app

### ISSUE THREAD

**Issue by teddis** [meteor/meteor#4451]
New to Meteor. Using https://github.com/yogiben/meteor-starter as a base project. I've set up Facebook, Google+ and Twitter app keys. When I attempt to login with anyone of them, the popup goes blank and does not disappear and log me into the app. The app remains in the login screen form page. I can't find any helpful posts on why this might be happening. I've deployed on Heroku and the URLs and DNS all seems to work fine. The heroku logs don't appear to indicate any problem. When I manually refresh the page after seeing the blank popup, I get a server error after attempting to re-auth. Errors with each service:

Facebook

```
2015-05-25T13:42:25.262542+00:00 app[web.1]: {"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with Facebook. failed [400] {\"error\":{\"message\":\"This authorization code has been used.\",\"type\":\"OAuthException\",\"code\":100}}","time":{"$date":1432561345261},"level":"warn"}
2015-05-25T13:42:25.650902+00:00 app[web.1]: Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Facebook. failed [400] {"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100}}
```

Google
```
2015-05-25T13:53:39.076559+00:00 heroku[router]: at=info method=GET path="/_oauth/google?state=eyJsb2dpblN0eWxlIjoicG9wdXAiLCJjcmVkZW50aWFsVG9rZW4iOiJZek45bndfdnBKMGhmS090WkNXNXFpcEtBVXpMOVg0TkJnVk9CbVFVNVhrIiwiaXNDb3Jkb3ZhIjpmYWxzZX0%3D&code=4/vwlfB4ANgcshfHExUSftZw-6ZSMoeTf1zZ2TyH621p4.Qk0kfvTOMhIaaDn_6y0ZQNjwD7MWmwI" host=demo.rocketap.com request_id=0e843589-f08b-49ce-8400-2b7ed5f13673 fwd="104.156.240.138" dyno=web.1 connect=0ms service=103ms status=200 bytes=1650
2015-05-25T13:53:39.077884+00:00 app[web.1]: {"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with Google. failed [400] {   \"error\" : \"invalid_grant\",   \"error_description\" : \"Code was already redeemed.\" }","time":{"$date":1432562019077},"level":"warn"}
2015-05-25T13:53:39.365527+00:00 app[web.1]: Exception while invoking method 'login' Error: Failed to complete OAuth handshake with Google. failed [400] {   "error" : "invalid_grant",   "error_description" : "Code was already redeemed." }
2015-05-25T13:53:39.365531+00:00 app[web.1]:     at getTokens (packages/google/google_server.js:56:1)
2015-05-25T13:53:39.365533+00:00 app[web.1]:     at Object.ServiceConfiguration.configurations.findOne.service [as handleOauthRequest] (packages/google/google_server.js:10:1)
2015-05-25T13:53:39.365534+00:00 app[web.1]:     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
2015-05-25T13:53:39.365536+00:00 app[web.1]:     at middleware (packages/oauth/oauth_server.js:173:1)
2015-05-25T13:53:39.365537+00:00 app[web.1]:     at packages/oauth/oauth_server.js:146:1
```

Twitter
```
2015-05-25T13:54:40.792678+00:00 app[web.1]: {"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Unable to retrieve request token","time":{"$date":1432562080792},"level":"warn"}
2015-05-25T13:54:41.127857+00:00 app[web.1]: Exception while invoking method 'login' Error: Unable to retrieve request token
2015-05-25T13:54:41.127861+00:00 app[web.1]:     at OAuth._requestHandlers.(anonymous function) (packages/oauth1/oauth1_server.js:61:1)
2015-05-25T13:54:41.127863+00:00 app[web.1]:     at middleware (packages/oauth/oauth_server.js:173:1)
2015-05-25T13:54:41.127866+00:00 app[web.1]:     at packages/oauth/oauth_server.js:146:1
```

Thanks for any helpful pointers.

**Comment by glasser** [comment]
"Why doesn't this work?" questions are best posed on [StackOverflow](http://stackoverflow.com/questions/tagged/meteor) or the [Meteor forums](https://forums.meteor.com/), not our bug tracker. If the community thinks it sounds like a bug in Meteor, read https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor which gives advice about how to submit useful bug reports. Good luck!

My guess is that your Heroku setup isn't setting `$ROOT_URL` properly?
