### ISSUE TITLE
Failure to start development server due to eslint interaction

### ISSUE THREAD

**Issue by tel** [meteor/meteor#4513]
Running `meteor` fails with an `EEXIST` error:

```
[[[[[ ~/Desktop/meteor-fisher ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Babel active on file extensions: es6.js, es6, jsx

/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EEXIST, mkdir '/Users/tel/Desktop/meteor-fisher/.meteor/local/.build283337.build/programs/.build399536.server/app/node_modules/eslint/node_modules/escope/node_modules/es6-map/node_modules/es5-ext/test/array/'
    at Object.Future.wait (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as mkdir] (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/files.js:1350:24)
    at [object Object]._.extend.reserve (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/builder.js:241:17)
    at [object Object]._.extend.generateFilename (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/builder.js:274:10)
    at [object Object]._.extend.writeToGeneratedFilename (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/builder.js:287:26)
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1505:31
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at [object Object]._.extend.write (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1465:7)
    at [object Object]._.extend.write (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1750:13)
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1815:12
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1918:25
    at Function._.each._.forEach (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1917:7
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2147:20
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.exports.bundle (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:2040:31)
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:554:24
    at time (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/profile.js:231:28)
    at Function.run (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/profile.js:377:12)
    at bundleApp (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:544:34)
    at [object Object]._.extend._runOnce (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:591:35)
    at [object Object]._.extend._fiber (/Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:821:28)
    at /Users/tel/.meteor/packages/meteor-tool/.1.1.3.k6nqc3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/run-app.js:402:12
    - - - - -
```

**Comment by tel** [comment]
Whoops! This just had to do with me installing eslint into a node_modules directory. Very strange error, though.
