### ISSUE TITLE
upsert: MongoError: The dotted field is not valid for storage

### ISSUE THREAD

**Issue by gsuess** [meteor/meteor#4522]
### Steps to reproduce:

```JavaScript
test = new Mongo.Collection("test");
test.update({"subdocument.field": "value1"}, {$set: {"foo": "baz"}}, {upsert: true});
```
### Expected result:

Inserts a document:

```json
{"_id":  "EQawgZfPaYszG9FYA",  "subdocument": {"field": "value1"}, "foo": "baz"}
```

### Actual Result:

```
MongoError: The dotted field 'subdocument.field' in 'subdocument.field' is not valid for storage.
    at Object.Future.wait (/home/gsuess/WebstormProjects/meteor/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at [object Object].<anonymous> (/packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) [as update] (/packages/mongo/mongo_driver.js:698:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (/packages/mongo/collection.js:575:1)
    at repl:1:7
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/build/programs/server/shell-server.js:264:23
    - - - - -
    at Object.toError (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/db.js:1195:7
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at [object Object].MongoReply.parseBody (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/home/gsuess/WebstormProjects/meteor/examples/leaderboard/.meteor/local/isopacks/npm-mongo/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

### Notes:

When running the same query on mongo directly, it works just fine:

```JavaScript
db.test.update({"subdocument.field": "value1"}, {$set: {"foo": "baz"}}, {upsert: true})
```

```JavaScript
WriteResult({
        "nMatched" : 0,
        "nUpserted" : 1,
        "nModified" : 0,
        "_id" : ObjectId("5574737b843753e392cfa920")
})
```

**Comment by gsuess** [comment]
Meteor tries to do the following update query [here](https://github.com/meteor/meteor/blob/devel/packages/mongo/mongo_driver.js#L671):

```JavaScript
db.test.update({ 'subdocument.field': 'value1' } ,{ _id: 'F6sdtKdxSrp8xRcFu','subdocument.field': 'value1', foo: 'bar' },{ safe: true, upsert: true })
```

**Comment by ekatek** [comment]
Makes sense to me -- it would be cool if this command worked in Meteor.  Thanks for the catch and the pull request.
