### ISSUE TITLE
Spacebars/Blaze should give better error on unterminated string literals

### ISSUE THREAD

**Issue by sbalmer** [meteor/meteor#4529]
Unterminated string literals in templates cause an exception:

    {{test 'test}}

gives me this error:

   packages/blaze-tools/tokens.js:170:1: Cannot read property '0' of null (compiling test.html)
   at Object.BlazeTools.parseStringLiteral (packages/blaze-tools/tokens.js:170:1)
   at scanArgValue (packages/spacebars-compiler/templatetag.js:209:1)
   at scanArg (packages/spacebars-compiler/templatetag.js:198:1)

**Comment by Slava** [comment]
Thanks, fixed on devel
