### ISSUE TITLE
Using existing Android SDK installation fails

### ISSUE THREAD

**Issue by bbshopadmin** [meteor/meteor#4572]
I'm trying to use an existing/running Android SDK (API 22 / Build-tools v22.0.1) installation with Meteor (v1.1.0.2) on Linux Mint. Cordova v5 is running as well.

```
$ env USE_GLOBAL_ADK=t meteor --verbose add-platform android
```
outputs
```
The Android platform is not installed; please run: meteor install-sdk android
```

Then
```
$ env USE_GLOBAL_ADK=t meteor --verbose install-sdk android
```
outputs (last lines only)
```
Do you accept the license 'android-sdk-license-5be876d5' [y/n]: 
Installing Archives:
Preparing to install archives
Downloading Android SDK Build-tools, revision 21 (Obsolete)
URL not found: /opt/android-sdk-linux/temp/build-tools_r21-linux.zip (Permission denied)
Done. Nothing was installed.

                                              
/home/dev/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: Failed to install android target: build-tools-21.0.0
    at [object Object]._.extend.installTarget (/home/dev/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:2256:15)
    at [object Object]._.extend.checkRequirements (/home/dev/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:2822:16)
    at checkPlatformRequirements (/home/dev/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:1342:20)
    at Command.func (/home/dev/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:3199:19)
    at /home/dev/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:1363:23
```
I have no idea what to do about that.

**Comment by bbshopadmin** [comment]
Seems to be a permission problem. Is it possible to use existing build-tools v22.0.1 instead of v21?

**Comment by bbshopadmin** [comment]
Ok, it's running after changing owner/group for /android-sdk-linux diretory.

But i would like meteor to use my already installed build-tools and API, not installing old ones. How do you do that?
