### ISSUE TITLE
Parse error on http.call

### ISSUE THREAD

**Issue by onerussell** [meteor/meteor#4590]
When i put date string with colons into 'if-modified-since' header, i get parse error.

Code:
```javascipt
    moment.locale('en');
    var leadsData = {
            headers: {
                "if-modified-since": moment(new Date(userData.lastStart)).format('ddd, DD MMM YYYY HH:mm:ss')
            }
        }
    }
    result = HTTP.call("GET", url, leadsData);
```

Error:

Error: Parse Error
    at Object.Future.wait (/Users/ruslan/.meteor/packages/meteor-tool/.1.1.3.1rq7gnm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at Object.call (packages/meteor/helpers.js:119:1)
    at initialiseAmo (app/server/amo.js:58:19)
    at app/server/scheduler.js:28:17
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:965:1)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:812:1)
    at transactionsOperated (app/server/scheduler.js:25:11)
    at Object.SyncedCron.add.job (app/server/scheduler.js:15:31)
    at packages/percolate:synced-cron/synced-cron-server.js:215:1
    at scheduleTimeout (packages/percolate:synced-cron/synced-cron-server.js:263:1)
    - - - - -
    at CleartextStream.socketOnData (http.js:1588:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)

**Comment by fradee** [comment]
If you  use async calls you should use promise.

**Comment by glasser** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

As that link describes, a code snippet is not a reproduction.  Also, you can probably just write a static string here rather than depending on all the machinery of moment, right?
