### ISSUE TITLE
A build error while building a build plugin source file breaks file watching

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor#4591]
Reproduction:

1. Create a new app
2. Clone https://github.com/elidoran/cosmos-browserify as a local package and add it to the app
2. Edit `plugin/browserify.coffee` to cause a build error in the CoffeeScript compiler, and save
3. Witness build error
4. Fix file; it should recompile, but it doesn't

**Comment by glasser** [comment]
I can sort of reproduce this and sort of not. When I change the file, it does rebuild, but then running the app fails with a strange error.  Is that what you saw, or were you running something slightly different from me?

I'll fix the issue in question though.

```
glasser@glasser-lyrid 130 /tmp/a $ curmeteor
[[[[[ /private/tmp/a ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:
   
   While processing files with coffeescript (for target os.osx.x86_64):
   plugin/browserify.coffee:1:1: unmatched ]
   
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.
W20150716-21:14:32.543(-7)? (STDERR) 
W20150716-21:14:32.611(-7)? (STDERR) /private/tmp/a/.meteor/local/build/programs/server/boot.js:283
W20150716-21:14:32.612(-7)? (STDERR) }).run();
W20150716-21:14:32.612(-7)? (STDERR)    ^
W20150716-21:14:32.612(-7)? (STDERR) ReferenceError: Package is not defined
W20150716-21:14:32.612(-7)? (STDERR)     at /private/tmp/a/.meteor/local/build/programs/server/packages/reload.js:4:14
W20150716-21:14:32.612(-7)? (STDERR)     at /private/tmp/a/.meteor/local/build/programs/server/packages/reload.js:12:3
W20150716-21:14:32.612(-7)? (STDERR)     at /private/tmp/a/.meteor/local/build/programs/server/boot.js:242:10
W20150716-21:14:32.612(-7)? (STDERR)     at Array.forEach (native)
W20150716-21:14:32.612(-7)? (STDERR)     at Function._.each._.forEach (/Users/glasser/Projects/Meteor/meteor/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150716-21:14:32.612(-7)? (STDERR)     at /private/tmp/a/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```
