### ISSUE TITLE
Future resolved more than once on a brand new project

### ISSUE THREAD

**Issue by johanalkstal** [meteor/meteor#4711]
Meteor 1.1.0.2

Doing the following on my Windows 8.1 machine causes an error.

`meteor create my-project`

`cd my-project`

`meteor`

then opening another console in `/my-project` and running `meteor mongo`

returns

```
C:\Users\alkstal\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modu
les\fibers\future.js:226                                                                                       
                        throw new Error('Future resolved more than once');                                     
                              ^                                                                                
Error: Future resolved more than once                                                                          
    at Object.Future.return (C:\Users\alkstal\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x8
6_32\dev_bundle\lib\node_modules\fibers\future.js:226:10)                                                      
    at Socket.<anonymous> (C:\Users\alkstal\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_
32\tools\run-mongo.js:221:36)                                                                                  
    at Socket.emit (events.js:95:17)                                                                           
    at net.js:441:14                                                                                           
    at process._tickCallback (node.js:442:13)                                                                  
                                                                                                               
```

Why and what can I do to solve this?

**Comment by glasser** [comment]
Hmm. This looks like an issue in the Windows-specific findMongoPort code. I guess this happens if the client gets an error after successfully connecting.  Let's see if this fixes it.

**Comment by ninjasun** [comment]
how can i use the plugin?
