### ISSUE TITLE
No dependency info in bundle. Filesystem monitoring disabled.

### ISSUE THREAD

**Issue by tianshuo** [meteor/meteor#475]
Meteor does not run on windows XP, I've already changed mongo to mongo 2.0.7

```
Running on: http://localhost:3000/
No dependency info in bundle. Filesystem monitoring disabled.
Errors prevented startup:
Exception while bundling application:
Error: ENOTEMPTY, directory not empty 'G:\sources\meteor-todo\.meteor\local\.b
uild.build\server'
    at Object.fs.rmdirSync (fs.js:456:18)
    at Object.module.exports.rm_recursive (C:\Program Files\Meteor\app\lib\files
.js:256:10)
    at C:\Program Files\Meteor\app\lib\files.js:254:15
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Program Files\Meteor\app\lib\third\undersco
re.js:76:11)
    at Object.module.exports.rm_recursive (C:\Program Files\Meteor\app\lib\files
.js:252:9)
    at _.extend.write_to_directory (C:\Program Files\Meteor\app\lib\bundler.js:4
82:11)
    at Object.exports.bundle (C:\Program Files\Meteor\app\lib\bundler.js:675:12)

    at exports.run.restart_server (C:\Program Files\Meteor\app\meteor\run.js:510
:26)
    at C:\Program Files\Meteor\app\meteor\run.js:608:9
Please fix the problem and restart.
```

Does not work with `meteor create sample` or `meteor create todo --example todos`

**Comment by yashsharma04** [comment]
[[[[[ ~/Desktop/simple-todos ]]]]]
GOT THIS ERROR TOO 

No dependency info in bundle. Filesystem monitoring disabled.
=> Errors prevented startup:
Exception while bundling application:
Error: ENOENT, no such file or directory '/home/yash/.meteor/packages/meteor-base/package.js'
    at Object.fs.openSync (fs.js:338:18)
    at Object.fs.openSync (/home/yash/.meteor/tools/d699ad29da/lib/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:68:26)
    at Object.fs.readFileSync (fs.js:182:15)
    at _.extend.initFromPackageDir (/home/yash/.meteor/tools/d699ad29da/tools/packages.js:163:19)
    at _.extend.initFromWarehouse (/home/yash/.meteor/tools/d699ad29da/tools/packages.js:197:10)
    at Object._.extend.get (/home/yash/.meteor/tools/d699ad29da/tools/packages.js:353:15)
    at self.api.use (/home/yash/.meteor/tools/d699ad29da/tools/bundler.js:111:28)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/yash/.meteor/tools/d699ad29da/lib/node_modules/underscore/underscore.js:78:11)
    at Object.self.api.use (/home/yash/.meteor/tools/d699ad29da/tools/bundler.js:110:9)
    at _.extend.init_from_app_dir [as on_use_handler] (/home/yash/.meteor/tools/d699ad29da/tools/packages.js:238:11)
    at _.extend.use (/home/yash/.meteor/tools/d699ad29da/tools/bundler.js:464:11)
    at Object.exports.bundle (/home/yash/.meteor/tools/d699ad29da/tools/bundler.js:873:12)
    at /home/yash/.meteor/tools/d699ad29da/tools/run.js:697:26
    at exports.inFiber (/home/yash/.meteor/tools/d699ad29da/tools/fiber-helpers.js:24:12)

Please fix the problem and restart.
