### ISSUE TITLE
meteor run issue

### ISSUE THREAD

**Issue by sun2rise** [meteor/meteor#4779]
after ```meteor add cordova:org.apache.cordova.cordova-plugin-file@2.1.0```
when i try ```meteor run ios```

i get this error:
```
Error while running for mobile platforms: Error running
/Users/sunrising/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: 404 Not Found: org.apache.cordova.cordova-plugin-file
at RegClient.<anonymous>
(/Users/sunrising/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
at Request._callback
(/Users/sunrising/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
at Request.self.callback
(/Users/sunrising/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
at Request.emit (events.js:98:17)
at Request.<anonymous>
(/Users/sunrising/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous>
(/Users/sunrising/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)


Fetching plugin "org.apache.cordova.cordova-plugin-file@2.1.0" via plugin
registry
```

this is the plugin https://www.npmjs.com/package/cordova-plugin-file

**Comment by sun2rise** [comment]
i changed the url of the plugin, i'm sorry for the mistake!

**Comment by martijnwalraven** [comment]
Good to hear you found a fix, I'm closing the issue.

**Comment by sun2rise** [comment]
@martijnwalraven 
Actually the problem was still there after the editing :) 
BUT
the right way to add the plugin was this

```meteor add cordova:org.apache.cordova.file@1.3.3```
and that worked in the build phase too!

I think that, at least for me, it's not so clear where to get the exact thing to write in order to install plugins that you can find on the cordova plugin registry, if you want to install the on Meteor

Cheers&TNX!
