### ISSUE TITLE
[plugins-preview] Error: isopack-1 is undefined.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#4820]
I'm getting this error when using the published version of `rocket:module@0.3.0`:

```
   While loading plugin `rocket:module` from package `rocket:module`:
   packages/rocket:module/plugin/plugin.js:292:1: isopack-1 is undefined. Please report this issue. Thanks!
   at isoOrUni (packages/rocket:module/plugin/plugin.js:292:1)
   at getInfoFromIsopack (packages/rocket:module/plugin/plugin.js:355:1)
   at getPackageInfo (packages/rocket:module/plugin/plugin.js:490:1)
   at packages/rocket:module/plugin/plugin.js:186:1
   at arrayReduce
   (/Users/josephpea/.meteor/packages/rocket_module/.0.1.5_5.ewwmec++os+web.browser+web.cordova/plugin.rocket_module.os/npm/rocket_module/node_modules/lodash/index.js:1516:23)
   at Function.<anonymous>
   (/Users/josephpea/.meteor/packages/rocket_module/.0.1.5_5.ewwmec++os+web.browser+web.cordova/plugin.rocket_module.os/npm/rocket_module/node_modules/lodash/index.js:3505:13)
   at getDependentsOf (packages/rocket:module/plugin/plugin.js:185:1)
   at Package (packages/rocket:module/plugin/plugin.js:752:1)
   at Package (packages/rocket:module/plugin/plugin.js:845:1)
   at <runJavaScript-45>:865:4
   at <runJavaScript-45>:872:3
```

I added `rocket:module` to my project by running

```sh
meteor --release PLUGINS-PREVIEW@1 add rocket:module
```

then I'm running my test app with

```sh
meteor --release PLUGINS-PREVIEW@1 --settings settings.json
```

and it gives me that error. I get no error if I install `rocket:module` as a local package in `packages/module` instead of from Atmosphere.

cc: @glasser

**Comment by trusktr** [comment]
Wait, nevermind. False alarm. It's my own error. Forgot I did that. xD
