### ISSUE TITLE
oauth package dependencies

### ISSUE THREAD

**Issue by ccorcos** [meteor/meteor#4843]
Got this error:

```
Uncaught ReferenceError: _ is not definedOAuth._loginStyle @ oauth_client.js:23Facebook.requestCredential @ facebook_client.js:31Meteor.loginWithFacebook @ facebook.js:12facebook.login @ facebook-login.coffee:29Login.createView.login @ login.coffee:10executeDispatch @ react-0.13.3.js:3311SimpleEventPlugin.executeDispatch @ react-0.13.3.js:17428forEachEventDispatch @ react-0.13.3.js:3299executeDispatchesInOrder @ react-0.13.3.js:3320executeDispatchesAndRelease @ react-0.13.3.js:2693forEachAccumulated @ react-0.13.3.js:19430EventPluginHub.processEventQueue @ react-0.13.3.js:2900runEventQueueInBatch @ react-0.13.3.js:11217ReactEventEmitterMixin.handleTopLevel @ react-0.13.3.js:11243handleTopLevelImpl @ react-0.13.3.js:11329Mixin.perform @ react-0.13.3.js:18402ReactDefaultBatchingStrategy.batchedUpdates @ react-0.13.3.js:9669batchedUpdates @ react-0.13.3.js:16633ReactEventListener.dispatchEvent @ react-0.13.3.js:11423
```

It seems oauth need to add underscore to client as well:

https://github.com/meteor/meteor/blob/devel/packages/oauth/package.js#L13

Then I got this error:

```
W20150730-04:26:30.902(-7) (oauth_server.js:398) Error in OAuth Server: Random is not defined
I20150730-04:26:31.147(-7)? Exception while invoking method 'login' ReferenceError: Random is not defined
I20150730-04:26:31.147(-7)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:9:1)
I20150730-04:26:31.147(-7)?     at middleware (packages/oauth/oauth_server.js:173:1)
I20150730-04:26:31.148(-7)?     at packages/oauth/oauth_server.js:146:1
```

And it seems this guy needs to add random: https://github.com/meteor/meteor/blob/devel/packages/oauth2/package.js

**Comment by stubailo** [comment]
@ccorcos I appreciate this! I'm actually working on a thing to fix up these dependencies this week/next week.

I assume you got this by removing `underscore` from `.meteor/packages`, so that it was no longer global on the client?

**Comment by ccorcos** [comment]
yeah, well I removed `meteor-platform` and added only what I needed in `app:lib` -- finally putting in the overhead time for package-based development

**Comment by stubailo** [comment]
PR with a _ton_ of fixes for related issues: https://github.com/meteor/meteor/pull/4848

**Comment by ccorcos** [comment]
Great job :+1:

**Comment by stubailo** [comment]
Fixed in that PR and merged.
