### ISSUE TITLE
Cannot find module '../build/Debug/iconv.node' in bundle prepared by meteor build

### ISSUE THREAD

**Issue by master7xx** [meteor/meteor#4863]
At developer stage, project running well.
When i deploy "production", appears this error.

Other iconv versions change nothing.
I still able run meteor run --production.
stack:

```
/var/www/reader/bundle/programs/server/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/reader/bundle/programs/server/npm/mrt_iconv/node_modules/iconv/lib/iconv.js:27:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

packages list

```
accounts-google             1.0.4  Login service for Google accounts
accounts-password           1.1.1  Password support for accounts
alethes:pages               1.8.4  State of the art, out of the box Meteor pagination
audit-argument-checks       1.0.3  Try to detect inadequate input sanitization
blazer:react                0.2.2  Blaze with React: Create stateful components with methods and mixins like in Facebook's React
browser-policy              1.0.4  Configure security policies enforced by the browser
datariot:ganalytics         0.2.1  Publish pageviews and events to Google Analytics using the new analytics.js code.
dburles:collection-helpers  1.0.3  Transform your collections with helpers that you define
fastclick                   1.0.3  Faster touch events on mobile
froatsnook:request          2.58.0  A Simplified HTTP client which supports retrieving binary data
iron:router                 1.0.9  Routing specifically designed for Meteor
jquery                      1.11.3_2  Manipulate the DOM using CSS selectors
less                        1.0.14  The dynamic stylesheet language
manuelschoebel:ms-seo       0.4.1  Easily config SEO for your routes
matteodem:easy-security     0.1.4  Protection against harmful attacks by rate limiting all remote method calls
meteor-platform             1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:fast-render     2.7.1  Render your app before the DDP connection even comes alive - magic?
meteorhacks:npm             1.4.0  Use npm modules with your Meteor App
momentjs:moment             2.10.6  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mrt:iconv                   2.0.7  Text recoding in JavaScript in meteor
natestrauser:animate-css    3.2.6  Animate.css packaged for meteor
nemo64:bootstrap            3.3.5_2  Highly configurable bootstrap integration.
npm-container               1.1.0+ Contains all your npm dependencies
percolate:synced-cron       1.2.1  Allows you to define and run scheduled jobs across multiple servers.
underscore                  1.0.3  Collection of small helpers: _.map, _.each, ...
zimme:iron-router-active    2.0.1  Deprecated! Use zimme:active-route
```

**Comment by stubailo** [comment]
It looks like a problem with the `mrt:iconv` package, which is old and unmaintained. Try using `meteorhacks:npm` to load `iconv` or `iconv-lite` from NPM instead: https://github.com/meteorhacks/npm
