### ISSUE TITLE
Cannot meteor install-sdk android (Error: spawn ENOENT)

### ISSUE THREAD

**Issue by VioletaCalvo** [meteor/meteor#4885]
Hi everyone!

When I try to do ```meteor install-sdk android``` I get an error. These are my logs:
```
*Found Android bundle
*A JDK is installed                        
Installing Android Platform tools             
                                              
/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: spawn ENOENT
    at Object.Future.wait (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at [object Object]._.extend.waitForExit (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/processes.js:102:28)
    at [object Object]._.extend.run (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/processes.js:118:10)
    at [object Object]._.extend.runAndroidTool (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:2178:25)
    at /home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:2249:21
    at /home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:327:18
    at [object Object]._.extend.withValue (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:326:36
    at [object Object]._.extend.withValue (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at [object Object]._.extend.installTarget (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:2246:18)
    at [object Object]._.extend.checkRequirements (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:2803:16)
    at checkPlatformRequirements (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:1342:20)
    at Command.func (/home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-cordova.js:3199:19)
    at /home/violeta/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:1363:23
    - - - - -
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
Coud you please help me with this?
Thank you in advance!!!

**Comment by leomatthew** [comment]
Did you try to setup ANDROID_SDK_HOME variable?

Please set that up and try again.

**Comment by VioletaCalvo** [comment]
Thank you @leomatthew !

I've tried to setup ```ANDROID_SDK_HOME``` variable to ```/home/violeta/.meteor/android_bundle``` but now I get this error:

```
(11:59:35)[meteor-projects]$ meteor install-sdk android

* Found Android bundle
* A JDK is installed                        
Installing Android Platform tools             
                                              
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at Pipe.onread (net.js:559:19)
```
I followed this instructions to propertly add the andoid platform to my meteor project:
http://www.sitepoint.com/beginners-guide-mobile-development-meteor/
https://github.com/meteor/meteor/wiki/Mobile-Dev-Install:-Android-on-Linux#jdk

I have not KVM is enabled, but is not mandatory, doesn't it?
I don't know what I'm doing wrong.

**Comment by leomatthew** [comment]
Yes KVM is not mandatory. Does your user has "Sudo" access or other equal permission to install software? If not, please try with "Sudo".

**Comment by VioletaCalvo** [comment]
I've tried with sudo and get the first error "Error: spawn ENOENT", also now without sudo.

**Comment by leomatthew** [comment]
Try the below. 
https://github.com/meteor/meteor/issues/4083

I don't find any other clue. For me, it seems like a permission issue.

**Comment by martijnwalraven** [comment]
I'm not sure what could be going on here, but note that in the next release we're [switching to having developers install the Android SDK separate from Meteor](https://github.com/meteor/meteor/issues/4721), to avoid problems like this.

**Comment by VioletaCalvo** [comment]
Thank you @leomatthew and @martijnwalraven !

I'm using a chromebook. I was on Beta channel and a recently upgraded chroot (trusty lxde). Switched to chromebook stable channel and recovered an earlier backup of my chroot (precise lxde) and now I have no problems with ```meteor install-sdk android```. 

Thank you. I hope this will help somebody.
