### ISSUE TITLE
Unhelpful error message with Mongo.collection

### ISSUE THREAD

**Issue by wesyah234** [meteor/meteor#4898]
On this line:
```
InsuranceCompany = new Mongo.collection('insuranceCompany');
```
I received this error
```
W20150806-09:18:49.862(-5)? (STDERR) /Users/user1/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150806-09:18:49.862(-5)? (STDERR) 						throw(ex);
W20150806-09:18:49.862(-5)? (STDERR) 						      ^
W20150806-09:18:49.864(-5)? (STDERR) TypeError: undefined is not a function
W20150806-09:18:49.864(-5)? (STDERR)     at app/shared.js:49:20
W20150806-09:18:49.864(-5)? (STDERR)     at app/shared.js:320:3
W20150806-09:18:49.864(-5)? (STDERR)     at /Users/user1/NetBeansProjects/spine2/.meteor/local/build/programs/server/boot.js:222:10
W20150806-09:18:49.864(-5)? (STDERR)     at Array.forEach (native)
W20150806-09:18:49.864(-5)? (STDERR)     at Function._.each._.forEach (/Users/user1/.meteor/packages/meteor-tool/.1.1.3.1wysac9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150806-09:18:49.864(-5)? (STDERR)     at /Users/user1/NetBeansProjects/spine2/.meteor/local/build/programs/server/boot.js:117:5
```
I'm just wondering if this could be made more helpful... it took me a while to realize that I had failed to capitalize "Collection".

**Comment by stubailo** [comment]
Hi @wesyah234, unfortunately I think it would be unfeasible for us to throw helpful errors for typos of method names. Maybe the best thing to do is install a tool in your editor like Slava's tern JS integration that works in many different editors: https://github.com/slava/tern-meteor
