### ISSUE TITLE
Isopack backward compatibility broken on 1.2 devel

### ISSUE THREAD

**Issue by mizzao** [meteor/meteor#4923]
Found this while talking @Slava about a weird error. Basically, if PLUGINS-PREVIEW@2 uses a package at some version, then a 1.1.x app will no longer be able to use this package at the same version with the error shown below.

Any package will cause this, I think as long as it hasn't been cached before - so just pick something random. Steps to reproduce:

```
meteor create --release PLUGINS-PREVIEW@2 test1
cd test1
meteor add fortawesome:fontawesome@4.4.0
```

Then do the same thing with a 1.1 app:

```
meteor create test2
cd test2
meteor add fortawesome:fontawesome@4.4.0
```

The following error is shown:

```
/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Could not find isopack data with format isopack-1.
This isopack was likely built with a much newer version of Meteor.
    at Function.readMetadataFromDirectory (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isopack.js:323:13)
    at [object Object]._.extend._alreadyDownloaded (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:319:35)
    at [object Object]._.extend._makeDownloader (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:383:33)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:524:29
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:521:20
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/package-map.js:50:7
    at Function._.each._.forEach (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/package-map.js:42:7)
    at [object Object]._.extend.downloadPackagesMissingFromMap (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tropohouse.js:518:16)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:668:25
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:667:20
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/catalog.js:100:5
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:666:13)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:238:35
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/project-context.js:221:10)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-packages.js:1878:20
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:245:19)
    at Command.main.registerCommand.name [as func] (/home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands-packages.js:1877:27)
    at /home/mao/.meteor/packages/meteor-tool/.1.1.4.km8gs0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:1363:23
```

**Comment by Slava** [comment]
@glasser  this could be a problem with our back-compat code for ispacks.

**Comment by Slava** [comment]
(@dgreensp this can be a blocker for 1.2)

**Comment by glasser** [comment]
OK, I think this got introduced when @benjamn added the great new support for non-default `*.js` handling. There's one particular place where a resource of type "source" and extension "js" can be produced without properly setting the usesDefaultSourceProcessor field, oops.  (This is a good argument that "resource" should be a classed object, not a random dictionary.)  This also makes it clear that testing of this back-compat stuff is minimal.

I think I have a fix.  You'll need to delete any improperly downloaded packages from your cache manually though (or just delete `~/.meteor` and reinstall meteor, there's nothing there but cache anyway).
