### ISSUE TITLE
[1.2-rc.2] Add platform android fails

### ISSUE THREAD

**Issue by raix** [meteor/meteor#4937]
METEOR@1.2-rc.2

Replication:
```bash
$ meteor create safename --release METEOR@1.2-rc.2
$ cd safename/
$ meteor add-platform android
```

Results in:
```bash
Do you agree (Y/n)? Y
Error creating Cordova project: Error running 
/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.2.1cklypi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Could not find directory:
/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.2.1cklypi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-app-hello-world


Creating a new cordova project.


Error: Error running /Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.2.1cklypi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Could not find directory: /Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.2.1cklypi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-app-hello-world


Creating a new cordova project.


    at execFileSyncOrThrow (/tools/cli/commands-cordova.js:274:11)
    at ensureCordovaProject (/tools/cli/commands-cordova.js:378:22)
    at /tools/cli/commands-cordova.js:3103:5
    at /tools/utils/buildmessage.js:331:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:330:36
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-cordova.js:3099:16)
    at /tools/cli/main.js:1376:23
                                              
/Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.2.1cklypi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Error running /Users/raix/.meteor/packages/meteor-tool/.1.1.7-rc.2.1cklypi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
    at execFileSyncOrThrow (/tools/cli/commands-cordova.js:274:11)
    at getCordovaInstalledPlatforms (/tools/cli/commands-cordova.js:405:23)
    at ensureCordovaPlatforms (/tools/cli/commands-cordova.js:429:28)
    at /tools/cli/commands-cordova.js:3104:5
    at /tools/utils/buildmessage.js:331:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:330:36
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-cordova.js:3099:16)
    at /tools/cli/main.js:1376:23
~/dev/test/safename
```

I've also removed meteor completely and reinstalled - same error message

**Comment by martijnwalraven** [comment]
The Cordova integration updates haven't been merged to devel yet. Don't read too much into the 1.2-rc.2 label.

**Comment by raix** [comment]
Gotcha so its not a release candidate yet

**Comment by remcoder** [comment]
ah, ran into this with 1.2-rc.4 too.

**Comment by raix** [comment]
@martijnwalraven normally the community help tests the rc releases, this feels a bit early for calling it a rc?

**Comment by martijnwalraven** [comment]
I completely agree, and that's why they are not release candidates yet. See https://github.com/meteor/meteor/issues/4943.
