### ISSUE TITLE
Errors from package.js have giant stack-traces in Meteor 1.2 RCs

### ISSUE THREAD

**Issue by Slava** [meteor/meteor#4961]
```
~/w/p/e/pg-example *master> meteor add simple:bookshelf
TypeError: Object #<PackageAPI> has no method 'addFile'
    at package.js:15:7
    at __bottom_mark__ (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/parse-stack.js:92:14)
    at [object Object]._.extend.initFromPackageDir (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/package-source.js:966:52)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog-local.js:282:23
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at initSourceFromDir (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog-local.js:269:20)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog-local.js:340:9
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:573:27
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:570:9
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at enterJob (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at Object.forkJoin (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:531:3)
    at [object Object]._.extend._loadLocalPackages (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog-local.js:336:18)
    at [object Object]._.extend.initialize (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog-local.js:92:10)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:540:29
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:532:20
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog.js:100:5
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/catalog.js:99:31)
    at ProjectContext._.extend._initializeCatalog (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:531:13)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:238:35
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:352:18
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:345:34
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:343:23
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.enterJob (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:228:18)
    at ProjectContext._.extend.initializeCatalog (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/project-context.js:204:10)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-packages.js:1743:20
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.main.captureAndExit (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:271:29)
    at Command.main.registerCommand.name [as func] (/Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-packages.js:1740:8)
    at /Users/imslavko/.meteor/packages/meteor-tool/.1.1.4.ox6dn8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23
=> Errors while initializing project:

While reading package from `/Users/imslavko/work/pg-example/examples/pg-example/packages/bookshelf`:
package.js:15:7: Object #<PackageAPI> has no method 'addFile'

~/w/p/e/pg-example *master>
```

In my example, I just used the wrong method to add files: `api.addFile` instead of `api.addFiles`. I think something in tool is supposed to cut the stacktrace.

CC @stubailo @dgreensp (important for 1.2)

**Comment by dgreensp** [comment]
Added to Asana.

**Comment by stubailo** [comment]
Seems to have gotten fixed:

```
Oleksandrs-MacBook-Pro:lol sashko$ curmeteor
[[[[[ ~/playpen/lol ]]]]]

=> Started proxy.
=> Errors prevented startup:

   While reading package from `/Users/sashko/playpen/lol/packages/teststack`:
   package.js:12:1: cc is not defined

=> Your application has errors. Waiting for file change.
=> Started MongoDB.
```

I know I was messing around with `parse-stack.js`, so maybe I accidentally fixed it.

**Comment by Slava** [comment]
:+1:
