### ISSUE TITLE
Meteor 1.2 rc-4 Error: Unsupported npm version (1.4.28). Please downgrade to 1.3.4.

### ISSUE THREAD

**Issue by Tarang** [meteor/meteor#4998]
I recently updated a project to Meteor 1.2 rc-4.

Now when I run `meteor run ios` I get this error:

```
$ meteor run ios-device --mobile-server="http://192.168.1.101:3000"
Error while running for mobile platforms: Error running /Users/user/.meteor/packages/meteor-tool/.1.1.7-rc.4.1ib2n7q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: Unsupported npm version (1.4.28). Please downgrade to 1.3.4:
(cd /Users/user/.meteor/packages/meteor-tool/.1.1.7-rc.4.1ib2n7q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib && rm -rf node_modules/npm && npm install npm@1.3.4)
at Object.<anonymous> (/Users/user/.meteor/packages/meteor-tool/.1.1.7-rc.4.1ib2n7q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/registry/registry.js:42:11)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/Users/user/.meteor/packages/meteor-tool/.1.1.7-rc.4.1ib2n7q++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:32:16)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
```

**Comment by martijnwalraven** [comment]
Meteor 1.2 rc-4 is not a supported version. There is no public release candidate of Meteor 1.2 out yet, so please just have a little more patience! The updated Cordova integration hasn't been merged to devel, but will be before the public RC.

**Comment by Tarang** [comment]
@martijnwalraven In previous instances we would post issues of RCs here. They are 'RCs' for a reason and not a beta/alpha.

**Comment by martijnwalraven** [comment]
I'm sorry for the confusion, but what I was trying to say is that despite the name this is not yet a release candidate.  We should be able to release one soon, and we'd very much appreciate people testing it!

**Comment by raedle** [comment]
@martijnwalraven Is there by any chance a way to get Meteor working with CordovaLib/VERSION >= 3.8.0? I'd like to test a cordova plugin, which only supports Cordova >= 3.8.0 :(
