### ISSUE TITLE
Errors adding android platform.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5006]
I'm trying to run `meteor add-platform android` which results in error messages:

```js
You must agree to the terms to proceed.

Do you agree (Y/n)? y
Error creating Cordova project: Error running
/Users/josephpea/.meteor/packages/meteor-tool/.1.1.4-plugins.3.15h0pv6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Could not find directory:
/Users/josephpea/.meteor/packages/meteor-tool/.1.1.4-plugins.3.15h0pv6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_mod
ules/cordova-app-hello-world


Creating a new cordova project.


Error: Error running /Users/josephpea/.meteor/packages/meteor-tool/.1.1.4-plugins.3.15h0pv6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/c
va.sh
Could not find directory: /Users/josephpea/.meteor/packages/meteor-tool/.1.1.4-plugins.3.15h0pv6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/de
dules/cordova-lib/node_modules/cordova-app-hello-world


Creating a new cordova project.


    at execFileSyncOrThrow (/tools/commands-cordova.js:273:11)
    at ensureCordovaProject (/tools/commands-cordova.js:377:22)
    at /tools/commands-cordova.js:3102:5
    at /tools/buildmessage.js:331:18
    at [object Object]._.extend.withValue (/tools/fiber-helpers.js:114:14)
    at /tools/buildmessage.js:330:36
    at [object Object]._.extend.withValue (/tools/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/buildmessage.js:321:26)
    at Command.main.registerCommand.name [as func] (/tools/commands-cordova.js:3098:16)
    at /tools/main.js:1383:23

/Users/josephpea/.meteor/packages/meteor-tool/.1.1.4-plugins.3.15h0pv6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/
                                                throw(ex);
                                                      ^
Error: Error running /Users/josephpea/.meteor/packages/meteor-tool/.1.1.4-plugins.3.15h0pv6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/c
va.sh
    at execFileSyncOrThrow (/tools/commands-cordova.js:273:11)
    at getCordovaInstalledPlatforms (/tools/commands-cordova.js:404:23)
    at ensureCordovaPlatforms (/tools/commands-cordova.js:428:28)
    at /tools/commands-cordova.js:3103:5
    at /tools/buildmessage.js:331:18
    at [object Object]._.extend.withValue (/tools/fiber-helpers.js:114:14)
    at /tools/buildmessage.js:330:36
    at [object Object]._.extend.withValue (/tools/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/buildmessage.js:321:26)
    at Command.main.registerCommand.name [as func] (/tools/commands-cordova.js:3098:16)
    at /tools/main.js:1383:23
```

Any idea what's wrong?

**Comment by trusktr** [comment]
I just switched over to Arch Linux, and I get the same cordova-app-hello-world missing error:

```
Error: Error running /home/trusktr/.meteor/packages/meteor-tool/.1.1.4-plugins.3.1jqzzy9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova
.sh
Could not find directory: /home/trusktr/.meteor/packages/meteor-tool/.1.1.4-plugins.3.1jqzzy9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modu
les/cordova-lib/node_modules/cordova-app-hello-world


Creating a new cordova project.


    at execFileSyncOrThrow (/tools/commands-cordova.js:273:11)
    at ensureCordovaProject (/tools/commands-cordova.js:377:22)
    at /tools/commands-cordova.js:3102:5
    at /tools/buildmessage.js:331:18
    at [object Object]._.extend.withValue (/tools/fiber-helpers.js:114:14)
    at /tools/buildmessage.js:330:36
    at [object Object]._.extend.withValue (/tools/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/buildmessage.js:321:26)
    at Command.main.registerCommand.name [as func] (/tools/commands-cordova.js:3098:16)
    at /tools/main.js:1383:23

/home/trusktr/.meteor/packages/meteor-tool/.1.1.4-plugins.3.1jqzzy9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: Error running /home/trusktr/.meteor/packages/meteor-tool/.1.1.4-plugins.3.1jqzzy9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cordova-scripts/cordova
.sh
    at execFileSyncOrThrow (/tools/commands-cordova.js:273:11)
    at getCordovaInstalledPlatforms (/tools/commands-cordova.js:404:23)
    at ensureCordovaPlatforms (/tools/commands-cordova.js:428:28)
    at /tools/commands-cordova.js:3103:5
    at /tools/buildmessage.js:331:18
    at [object Object]._.extend.withValue (/tools/fiber-helpers.js:114:14)
    at /tools/buildmessage.js:330:36
    at [object Object]._.extend.withValue (/tools/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/buildmessage.js:321:26)
    at Command.main.registerCommand.name [as func] (/tools/commands-cordova.js:3098:16)
    at /tools/main.js:1383:23
```

**Comment by martijnwalraven** [comment]
Could you try this again with the Meteor 1.2 RC (`--release METEOR@1.2-rc.7`)? There have been some major changes to the architecture of the Cordova integration, so I hope that will solve your issue. If not, let me know, and I'll look into it.

**Comment by zeorin** [comment]
I don't think this is related to Meteor. I'm not using Meteor, but came across this same issue when trying to run `cordova create hello` on Debian 8.

**Comment by zeorin** [comment]
I filed an issue with Cordova: https://issues.apache.org/jira/browse/CB-9687.

**Comment by zeorin** [comment]
Workaround:

I ran `sudo npm install` in `/usr/lib/node_modules/cordova/node_modules/cordova-lib` and after that I could run `cordova create hello`.

@trusktr you can probably run `npm install` in
```
/Users/josephpea/.meteor/packages/meteor-tool/.1.1.4-plugins.3.15h0pv6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib
```
to make it work.

**Comment by martijnwalraven** [comment]
An alternative would be to upgrade to Meteor 1.2, which doesn't use `cordova-app-hello-world` and hence is not affected by this.

**Comment by zeorin** [comment]
@martijnwalraven that's assuming that Meteor 1.2 never calls `cordova create`.

**Comment by martijnwalraven** [comment]
It doesn't :) We now use `cordova-lib` instead of calling out to the CLI, and avoid `cordova-app-hello-world` by passing our own template based on `mobile-config.js`.

**Comment by zeorin** [comment]
The underlying issue in Cordova is now resolved: https://issues.apache.org/jira/browse/CB-9687

**Comment by trusktr** [comment]
I've been on 1.2 for a while, and haven't had the problem. :}

**Comment by martijnwalraven** [comment]
Good to hear, that's why I closed it!
