### ISSUE TITLE
spiderable + iron-router

### ISSUE THREAD

**Issue by dnish** [meteor/meteor#5010]
Hey guys,
I don't know if it is spiderables fault, but if I add both packages to a clean project, I get the following error when I call a URL with "?_escaped_fragment_=1":

<code>
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (C:\Users\Dennis\AppData\Local.meteor\packages\webapp\1.2.0\npm\node_modules\connect\lib\proto.js:190:15)
    at packages/spiderable/spiderable_server.js:123:1
</code>

(tested with *.meteor.com servers and my local machine)

Without "?_escaped_fragment_=1", everything works fine. 

After that, I've just add a copy of the spiderable package and modified "spiderable_server.js" to the following

<code>
 Meteor.bindEnvironment(function (err, res) {

 {...whole code of spiderable_server.js...}
});
</code>

After that, Meteor works fine again, but spiderable is still not working (empty body - but no error).

**Comment by stubailo** [comment]
I think this would be a good bug to file on `iron:router` - I'm not exactly sure what it does with server-side routes and similar. Have you filed a bug there?

**Comment by hwillson** [comment]
Closing due to low activity and as mentioned in https://github.com/meteor/meteor/issues/5010#issuecomment-136860563, this issue would be better placed in the [Iron.Router](https://github.com/iron-meteor/iron-router) repo. Thanks for reporting this originally!
