### ISSUE TITLE
parseError from _pollMongo during startup, breaks all DB I/O

### ISSUE THREAD

**Issue by joeytwiddle** [meteor/meteor#5106]
After a few days of inserting data, I see this error, first at runtime, and then every time I start the server thereafter:

```
Exception while polling query {"collectionName":"records","selector":{},"options":{"transform":null}}: Error: parseError occured
    at Object.Future.wait (/home/joey/.meteor/packages/meteor-tool/.1.1.4.xvre8c++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
    at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:1012:1)
    at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:147:1)
    at Object.task (packages/mongo/polling_observe_driver.js:85:1)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
    - - - - -
    at [object Object].<anonymous> (/home/joey/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:198:34)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/home/joey/.meteor/packages/mongo/.1.1.0.11t75li++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:411:20)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
```

The Meteor server is still running (it serves the initial page) but it does not present any data.  This is on my dev machine.

The documents were saved through Meteor (nothing else is talking to Mongo).

Meteor 1.1.0.3
mongodb 2.0.4-1ubuuntu2.1

Dropping the collection gets my server running as normal again.  Restoring a dump of the DB brings the problem back again.

(I did export the broken collection, to try to parse it with JSON, but the exported file does not contain `,`s between documents, so isn't valid JSON!)

Any idea what is causing this?  Is it a Meteor or a Mongo issue?  What can I do to debug it / prevent it?  Cheers.

**Comment by joeytwiddle** [comment]
I exported the collection from mongo, and modified it so it should load.  This got me a `SyntaxError: Unexpected token ILLEGAL` with a line number:

                        " 155, 135); border-bottom-width: 2px; border-bottom-style: solid; border-radius:" +
                        " 5px; transition: background-color 0.2s linear; background: rgb(9, 179, 156); }\" +
                        "n.bt:hover { color: rgb(255, 255, 255); background-color: rgb(10, 203, 177); }\n" +

As you can see, at the end of the middle line, a `\n` has been broken, leading to the SyntaxError.

This is obviously an issue with mongoexport. But it *might* be the cause of my parseError, if mongo passes the data to Meteor in a similar fashion. I now need to test using the latest version of MongoDB, to see if this has been fixed.

**Comment by joeytwiddle** [comment]
I uninstalled Ubuntu's mongodb-2.0.4 and installed the latest version 3.0.6 from mongo's own repo.  The database remained intact but now the error is not appearing!  :+1:
