### ISSUE TITLE
Error compiling {{#each a in (b)}}

### ISSUE THREAD

**Issue by wh0** [meteor/meteor#5137]
In Meteor release 1.2-rc.12, when compiling `{{#each a in (b)}}`, I get the following error:

```
=> Errors prevented startup:                  
   
   While processing files with templating (for target web.browser):

   /home/wh0/.meteor/packages/meteor-tool/.1.1.7-rc.12.dvasa3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:395:16:
   Cannot call method 'replace' of undefined
   at Object.Future.wait
   (/home/wh0/.meteor/packages/meteor-tool/.1.1.7-rc.12.dvasa3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:395:16)
   at CachingHtmlCompiler.processFilesForTarget (caching-compiler.js:312:12)
   at CachingHtmlCompiler.processFilesForTarget (caching-html-compiler.js:40:32)
```

[caching-compiler.js:312](https://github.com/meteor/meteor/blob/8754e3626f866173bf9a89693f3ecc1e3c72cd07/packages/caching-compiler/caching-compiler.js#L312)
[caching-html-compiler.js:40](https://github.com/meteor/meteor/blob/8754e3626f866173bf9a89693f3ecc1e3c72cd07/packages/caching-html-compiler/caching-html-compiler.js#L40)
(can't find `replace` on either of these lines)

`{{#each a in b}}` don't `{{#each (b)}}` cause the crash.

---

steps to reproduce:

```sh
meteor create --release 1.2-rc.12 asdf
cd asdf
rm asdf.css
rm asdf.js
cat <<EOF >asdf.html
<body>
  {{#each a in (b)}}
    Hello
  {{/each}}
</body>
EOF
meteor
```

**Comment by wh0** [comment]
maybe it's this replace:
https://github.com/meteor/meteor/blob/8754e3626f866173bf9a89693f3ecc1e3c72cd07/packages/spacebars-compiler/codegen.js#L122

**Comment by wh0** [comment]
it's not that replace. Here's the real stack trace

```
#0 toJSLiteral <runJavaScript-53>:269:12
#1 _.extend.codeGenPath <runJavaScript-55>:1066:36
#2 _.extend.codeGenTemplateTag <runJavaScript-55>:942:20
#3 SpacebarsCompiler._TemplateTagReplacer.def.visitObject <runJavaScript-55>:1247:27
#4 HTML.Visitor.def.visit <runJavaScript-51>:101:31
#5 SpacebarsCompiler.codeGen <runJavaScript-55>:1299:26
#6 SpacebarsCompiler.compile <runJavaScript-55>:1230:28
#7 <runJavaScript-56>:307:48
#8 TemplatingTools.compileTagsWithSpacebars <runJavaScript-56>:247:13
#9 native array.js:1120:24
```

**Comment by wh0** [comment]
https://github.com/meteor/meteor/blob/8754e3626f866173bf9a89693f3ecc1e3c72cd07/packages/spacebars-compiler/codegen.js#L127
calls `codeGenPath` with an EXPR, not a PATH.

**Comment by wh0** [comment]
trying to commit this patch

```diff
diff --git a/packages/spacebars-compiler/codegen.js b/packages/spacebars-compiler/codegen.js
index f816218..e1ff226 100644
--- a/packages/spacebars-compiler/codegen.js
+++ b/packages/spacebars-compiler/codegen.js
@@ -124,7 +124,7 @@ _.extend(CodeGen.prototype, {
             }
             var variable = variableArg[1][0];
             dataCode = 'function () { return { _sequence: Spacebars.call(' +
-              self.codeGenPath(args[2][1]) +
+              self.codeGenArgValue(args[2]) +
               '), _variable: ' + BlazeTools.toJSLiteral(variable) + ' }; }';
           } else if (path[0] === 'let') {
             var dataProps = {};
```

but I get

```
Linting Meteor tool code...
npm WARN unmet dependency /home/wh0/work/meteor/scripts/admin/eslint/node_modules/eslint/node_modules/escope requires estraverse@'^3.1.0' but will load
npm WARN unmet dependency /home/wh0/work/meteor/scripts/admin/eslint/node_modules/eslint/node_modules/estraverse,
npm WARN unmet dependency which is version 2.0.0

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/wh0/work/meteor/scripts/admin/eslint/node_modules/.bin/eslint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
Linter errors detected in pre-commit hook.

Run the linter with ./scripts/admin/eslint/eslint.sh

If you know what you are doing you can disable this
check using:

  git config hooks.ignore-eslint true
```

**Comment by stubailo** [comment]
weird, try running the `./scripts/admin/eslint/eslint.sh` script?

**Comment by stubailo** [comment]
Thanks for handing me the fix on a silver platter! Also added a test for it.

Should be out in the next RC (>= 16)

**Comment by wh0** [comment]
I've opened a pull request with a more permissive fix, which additionally allows `{{#each a in b c}}`, without need for parentheses.

**Comment by yyx990803** [comment]
Ref: the new PR is #5138

**Comment by stubailo** [comment]
This fix is out now, and we're looking at the other one.
