### ISSUE TITLE
Error In deployment

### ISSUE THREAD

**Issue by leomatthew** [meteor/meteor#5152]
When I deploy a app in a new server. I got the below error. Can anyone help?

root@grannytherapy:/opt/granny/Acito# sudo meteor
[[[[[ /opt/granny/Acito ]]]]]                 

=> Started proxy.                             
=> Started MongoDB.                           
                                              
/root/.meteor/packages/meteor-tool/.1.1.4.st5tu4++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:259
			throw new Error('Must throw non-empty error');
			      ^
Error: Must throw non-empty error
    at Object.Future.throw (/root/.meteor/packages/meteor-tool/.1.1.4.st5tu4++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/fibers/future.js:259:10)
    at Extract.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.4.st5tu4++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/tools/files.js:697:42)
    at Extract.emit (events.js:117:20)
    at DirWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.4.st5tu4++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/tar/lib/extract.js:61:8)
    at DirWriter.emit (events.js:117:20)
    at FileWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.4.st5tu4++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/fstream/lib/dir-writer.js:158:12)
    at FileWriter.emit (events.js:117:20)
    at WriteStream.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.4.st5tu4++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/fstream/lib/file-writer.js:50:47)
    at WriteStream.emit (events.js:95:17)
    at onwriteError (_stream_writable.js:239:10)
    at onwrite (_stream_writable.js:257:5)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at evalmachine.<anonymous>:1692:14
    at Object.wrapper [as oncomplete] (evalmachine.<anonymous>:522:5)

**Comment by stubailo** [comment]
Please don't run `meteor` with `sudo`, ever. If you would like to deploy your Meteor app on your server, use `meteor build`: http://docs.meteor.com/#/full/deploying

There is also a lot of good discussion about deployment on the forums: https://forums.meteor.com/c/deployment

**Comment by leomatthew** [comment]
Thanks Stubailo. It helped
