### ISSUE TITLE
[1.2-rc.15] error in buildPlugin does not produce proper error stack trace

### ISSUE THREAD

**Issue by wojtkowiak** [meteor/meteor#5193]
Hey,

I do not know is this really a bug, but I am trying to write a build plugin but it is really hard since every error stops the app build stage without any hint on what is wrong. I would expect to have a normal error stack trace printed so I can check what is wrong in the package I am developing.
Maybe this is impossible or I am trying to write the packe wrong way - let me know:

Here is the error I get if I made for example a syntax error:
```
TypeError: Cannot read property '0' of undefined
    at Object.exception (/tools/utils/buildmessage.js:490:22)
    at /tools/isobuild/compiler.js:745:22
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/isobuild/compiler.js:733:18
    at Function._.each._.forEach (/Users/bwojtkowiak/.meteor/packages/meteor-tool/.1.1.7-rc.14.1w7su19++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at runLinters (/tools/isobuild/compiler.js:716:5)
    at /tools/isobuild/compiler.js:307:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at lintUnibuild (/tools/isobuild/compiler.js:306:39)
    at /tools/isobuild/compiler.js:215:30
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/bwojtkowiak/.meteor/packages/meteor-tool/.1.1.7-rc.14.1w7su19++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compiler.lint (/tools/isobuild/compiler.js:208:5)
    at lintBundle (/tools/isobuild/bundler.js:2239:54)
    at /tools/isobuild/bundler.js:2114:25
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2047:31)
    at /tools/runners/run-app.js:551:36
    at time (/tools/tool-env/profile.js:232:28)
    at Function.run (/tools/tool-env/profile.js:377:12)
    at bundleApp (/tools/runners/run-app.js:541:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
```
Here is repro: https://github.com/wojtkowiak/repro
Just run it and you will get the error. Here I intentionally left an error https://github.com/wojtkowiak/repro/blob/master/packages/xcodeProjectModifier/plugin.js#L5

Thanks for your time in advance.

**Comment by stubailo** [comment]
Great news! this is already fixed in the current RC, 1.2-rc.16!

See the output below:

```
Oleksandrs-MacBook-Pro:repro sashko$ meteor --release 1.2-rc.16
=> Using Meteor 1.2-rc.16 as requested (overriding Meteor 1.2-rc.15)

[[[[[ ~/playpen/repro ]]]]]

=> Started proxy.
=> Started MongoDB.

Changes to your project's package version selections:

babel-runtime       upgraded from 0.1.4-rc.0 to 0.1.4-rc.1
blaze               upgraded from 2.1.3-rc.0 to 2.1.3-rc.1
mobile-status-bar   upgraded from 1.0.5-rc.1 to 1.0.6-rc.0
spacebars-compiler  upgraded from 1.0.7-rc.0 to 1.0.7-rc.1
templating          upgraded from 1.1.2-rc.5 to 1.1.2-rc.6

=> Linted your app.

   While linting files with xcode-project-modifier for the app (Server):
   packages/xcode-project-modifier/plugin.js:5:1: noObject is not defined (at XcodeProjectModifier.processFilesForPackage)

   While linting files with xcode-project-modifier for the app (Client):
   packages/xcode-project-modifier/plugin.js:5:1: noObject is not defined (at XcodeProjectModifier.processFilesForPackage)

=> Started your app.

=> App running at: http://localhost:3000/
```

**Comment by wojtkowiak** [comment]
Thanks! That's really great :) You guys are faster than light!

**Comment by wojtkowiak** [comment]
Sorry to bother, one question - should I be able to write the build plugin in ES2015? Adding api.use('ecmascrtipt') does not do anything.
