### ISSUE TITLE
OSX Yosemite install

### ISSUE THREAD

**Issue by Brianchat** [meteor/meteor#5234]
Trying to install on Yosemite, behind a proxy.

Keeping getting the following error, even when now by-passing the proxy:

admins-iMac:~ sli$ meteor install-sdk android
✓ Found Android bundle
✓ A JDK is installed                          
✓ Found Android Platform tools                
Installing Android Build Tools                
                                              
/Users/sli/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: Failed to install android target: build-tools-21.0.0
    at [object Object]._.extend.installTarget (/Users/sli/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:2256:15)
    at [object Object]._.extend.checkRequirements (/Users/sli/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:2822:16)
    at checkPlatformRequirements (/Users/sli/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:1342:20)
    at Command.func (/Users/sli/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/commands-cordova.js:3199:19)
    at /Users/sli/.meteor/packages/meteor-tool/.1.1.4.2l3p0l++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/main.js:1363:23

**Comment by avital** [comment]
We changed the way we launch the Android SDK in Meteor 1.2. @martijnwalraven, could you take a look at this?

In the meanwhile, downgrading to Meteor 1.1.0.3 may work for you. Could you give that a shot? (Run `meteor update --release 1.1.0.3` in your app directory)

**Comment by martijnwalraven** [comment]
Actually, I think the poster is running Meteor 1.1.0.3 and I would advise using Meteor 1.2!

**Comment by martijnwalraven** [comment]
@Brianchat Have you been able to get this to work?

**Comment by Brianchat** [comment]
Applologies for the delayed response, I have been offline.

Meteor 1.2 'just works' :+1:
