### ISSUE TITLE
meteor run android-device fails on adding a plugin after upgrading to 1.2.0.1

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#5251]
The plugin: com.phonegap.plugins.facebookconnect@0.11.0
Fixed by `rm -rf .meteor/local/cordova-build/platforms/android/`

```
Getting installed version for platform android in Cordova project
Getting installed version for platform ios in Cordova project
Checking Cordova requirements for platform Android
[[[[[ ~/parlay ]]]]]                          

=> Started proxy.                             
=> Started MongoDB.                           
Local package version is up-to-date: accounts-base@1.2.1
...
Preparing Cordova project from app bundle     
Processing mobile-config.js                   
Copying resources for mobile apps             
Writing new config.xml                        
                                              
WARNING: Cordova plugin nl.x-services.plugins.launchmyapp has been renamed to cordova-plugin-customurlscheme   as part of moving to npm. Please change the App.configurePlugin call in   mobile-config.js
         accordingly.
Removing plugins                              
...
from Cordova project
% Plugin "cordova-plugin-contacts" is not present in the project. Converting value to "org.apache.cordova.contacts" and trying again.
...      
Adding plugin com.phonegap.plugins.facebookconnect@0.11.0 to Cordova project       
% Fetching plugin "com.phonegap.plugins.facebookconnect@0.11.0" via npm            
% Fetching plugin "com.phonegap.plugins.facebookconnect@0.11.0" via cordova plugins registry
% Installing "com.phonegap.plugins.facebookconnect" for android                    
% Error during processing of action! Attempting to revert...                       
% Failed to install 'com.phonegap.plugins.facebookconnect':Error: Uh oh!           
"/Users/me/parlay/.meteor/local/cordova-build/platforms/android/res/values/facebookconnect.xml" already exists!
  at Object.module.exports.common.copyNewFile (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
  at Object.module.exports.source-file.install (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
  at installWrapper (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
  at Object.ActionStack.process (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
  at handleInstall (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:576:20)
  at /Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:363:28
  at _fulfilled (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
  at /Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
  at flush (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:448:13)

=> Errors executing Cordova commands:                                              
                                                                                   
   While adding plugin com.phonegap.plugins.facebookconnect@0.11.0 to Cordova project:
   Error: Uh oh!                                                                   
   "/Users/me/parlay/.meteor/local/cordova-build/platforms/android/res/values/facebookconnect.xml" already exists!
   at Object.module.exports.common.copyNewFile
   (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
   at Object.module.exports.source-file.install
   (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
   at installWrapper
   (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
   at Object.ActionStack.process
   (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
   at handleInstall
   (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:576:20)
   at /Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:363:28
   at _fulfilled (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at /Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
   at flush (/Users/me/.meteor/packages/meteor-tool/.1.1.8.1ty3odi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
   

ExitWithCode:1
```

**Comment by martijnwalraven** [comment]
I'm not sure what is going on here, but I don't think this is something we can fix in Meteor. It seems this error is specific to the `com.phonegap.plugins.facebookconnect` plugin and may have to do with a failure to remove `facebookconnect.xml` when the plugin is uninstalled.

Does it happen repeatedly or was this a one time error?

**Comment by lorensr** [comment]
It kept happening until I did the rm -rf. Is The plug-in responsible for
removing itself, or is meteor supposed to be deleting all the files?

**Comment by martijnwalraven** [comment]
Cordova (actually a subproject called plugman) is responsible for uninstalling plugins, and that should include deleting all the files.

**Comment by flake** [comment]
I have been getting the same error ever since i updated to 1.2

Cordova error: CordovaError: Failed to fetch plugin cordova-plugin-splashscreen@2.1.0 via registry.

**Comment by martijnwalraven** [comment]
@flake That doesn't seem like the same error. Could you open a new issue for this?
