### ISSUE TITLE
Issue when trying to update to version 1.2.0.1

### ISSUE THREAD

**Issue by em0ney** [meteor/meteor#5252]
***1 Upvote*** Hi there,

Having this issue when trying to update to version 1.2.0.1.  Can't see any of my code in the stacktrace so thought I'd escalate to here.

Error is:
Error: Path contains forbidden segment '..'

```bash
▶ meteor update
                                              
/home/e/.meteor/packages/meteor-tool/.1.1.8.9fcrk6++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: Path contains forbidden segment '..'
    at Builder._sanitize (/tools/isobuild/builder.js:143:15)
    at Builder.generateFilename (/tools/isobuild/builder.js:340:20)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:352:28)
    at /tools/isobuild/isopack.js:1335:27
    at Array.forEach (native)
    at Function._.each._.forEach (/home/e/.meteor/packages/meteor-tool/.1.1.8.9fcrk6++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at _.each._.each.builder.generateFilename.directory (/tools/isobuild/isopack.js:1309:11)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/e/.meteor/packages/meteor-tool/.1.1.8.9fcrk6++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1222:9
    at [object Object]._.extend.saveToPath (/tools/isobuild/isopack.js:1574:26)
    at /tools/isobuild/isopack-cache.js:289:23
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (/tools/isobuild/isopack-cache.js:227:18)
    at /tools/isobuild/isopack-cache.js:166:14
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:158:20)
    at /tools/isobuild/isopack-cache.js:73:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/e/.meteor/packages/meteor-tool/.1.1.8.9fcrk6++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at [object Object]._.extend.buildLocalPackages (/tools/isobuild/isopack-cache.js:72:24)
    at /tools/project-context.js:735:25
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:734:18)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/cli/commands-packages.js:1506:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:270:29)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1505:8)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:1577:29)
    at /tools/cli/main.js:1378:23
```

Cheers,
Elliott

**Comment by hkstsony** [comment]
I'm having the same issue

**Comment by stubailo** [comment]
What packages are you using?

**Comment by hkstsony** [comment]
accounts-password         1.1.1* Password support for accounts
alanning:roles            1.2.13  Role-based authorization
aldeed:autoform           5.5.1  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2        2.5.0  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema      1.3.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
aslagle:reactive-table    0.8.12  A reactive table designed for Meteor
cfs:autoform              2.2.1  Upload files as part of autoform submission
cfs:filesystem            0.1.2  Filesystem storage adapter for CollectionFS
cfs:http-methods          0.0.30  Adds HTTP.methods RESTful
cfs:standard-packages     0.5.9  Filesystem for Meteor, collectionFS
d3js:d3                   3.5.5  D3 (official): A JavaScript visualization library for HTML and SVG.
emgee:mssql               1.3.0_8  mssql wrapper: non-reactive SQL Server package
flemay:less-autoprefixer  1.1.0  The dynamic stylesheet language + Autoprefixer
flowkey:hotkeys           1.1.1  Easy and effective hotkeys for your app, powered by Mousetrap
froatsnook:bardcode       1.2.0  Draw 1-D barcodes (client and server); supports code 128, 3 of 9, 2 of 5, EAN, and more
iron:router               1.0.9  Routing specifically designed for Meteor
jquery                    1.11.3_2* Manipulate the DOM using CSS selectors
meteor-platform           1.2.2* Include a standard set of Meteor packages in your app
meteorhacks:cluster       1.6.9  Clustering solution for Meteor with load balancing and service discovery.
meteorhacks:kadira        2.23.4  Performance Monitoring for Meteor
meteorhacks:kadira-debug  1.3.3  Full Stack Debugging Solution for Meteor
meteorhacks:subs-manager  1.6.2  Subscriptions Manager for Meteor
meteortoys:toykit         0.8.7  Shared processes for Mongol and JetSetter
mizzao:user-status        0.6.5  User connection and idle state tracking for Meteor
momentjs:moment           2.10.6  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor...
msavin:jetsetter          1.0.20  Visual Get/Set Tool for Sessions
random                    1.0.3* Random number generator and utilities
richsilv:owl-carousel     0.1.0  Touch enabled jQuery plugin that lets you create a beautiful responsive carousel slider.
semantic:ui               2.1.4  Official Semantic UI Integration for Meteor
sergeyt:typeahead         0.11.1_4  Autocomplete package for meteor powered by twitter typeahead.js
simple:reactive-method    1.0.2  Call methods synchronously inside Tracker.autorun
tap:i18n                  1.6.1  A comprehensive internationalization solution for Meteor
twbs:bootstrap            3.3.5  The most popular front-end framework for developing responsive, mobile first projects o...
underscore                1.0.3* Collection of small helpers: _.map, _.each, ...
zimme:active-route        2.3.2  Active route helpers

**Comment by cubitworx** [comment]
Are there any plans to fix this? I feel like this is a step backwards if it is not a bug & it is intended to have this limitation. It worked in 1.1 but not in 1.2.

I have detailed the problem [here](http://stackoverflow.com/questions/33626282/meteor-1-2-share-files-between-packages). Specifically I need to be able to do the following in my package, which now produces the `Error: Path contains forbidden segment '..'` error:

    api.addFiles([
        '../../private/bower_components/bootstrap/less/buttons.less',
    ],'client',{isImport: true});

**Comment by cubitworx** [comment]
I have created a repository reproducing this problem in its simplest form...
https://github.com/cubitworx/meteor-1.2-forbidden-path-segment

**Comment by marianafranco** [comment]
+1 I'm having the same problem

**Comment by mathiasrw** [comment]
Any news on this?

**Comment by timmygee** [comment]
In 1.2 api.addFiles has a breaking change. From the upgrade guide:

> In packages, files added with api.addFiles that have no recognizable extension are no longer added as static assets.  You must now use api.addAssets to add a static asset.  Package authors must make this change to their package.js files before they can publish from Meteor 1.2, but existing published packages will continue to work. The hidden isAsset: true flag to api.addFiles is now deprecated and throws an error suggesting that you should use addAssets instead.

More info: https://quip.com/RXFlAk9Rc2xI

**Comment by abernix** [comment]
@em0ney Do these other problems sound like yours?  Is it possible that you have a package with `addFiles` on a non-JS resource, like CSS or LESS?  As @timmygee said, this requires changes to use `addAssets` in 1.2.
