### ISSUE TITLE
buildNumber in mobile-config.js has to be a number for Android

### ISSUE THREAD

**Issue by pfafman** [meteor/meteor#5255]
This might be obvious to some people but was not to me.  The new buildNumber in mobile-config settings has to be a number for android builds.  If all you are doing is building iOS then it is fine being a dot string.

You might add a note somewhere in the documentation since you are using this to map to two different cordoava config directives.

Feel free to close this but I am putting it here so that if someone else runs into this mistake they may find it when searching the issues.

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/tep/Projects/WineSail/winesail/app/.meteor/local/cordova-build/platforms/android/CordovaLib/cordova.gradle' line: 128

* What went wrong:
A problem occurred evaluating root project 'android'.
> No match found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.664 secs
   Starting app on Android Device            /
/Users/tep/Projects/WineSail/winesail/app/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/tep/Projects/WineSail/winesail/app/.meteor/local/cordova-build/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/tep/Projects/WineSail/winesail/app/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
=> Errors executing Cordova commands:

   While running Cordova app for platform Android with options --device:
   Error: Command failed: /Users/tep/Projects/WineSail/winesail/app/.meteor/local/cordova-build/platforms/android/cordova/run --device

   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1
```

**Comment by miri-am** [comment]
#5092

**Comment by pfafman** [comment]
Sorry.  Missed that one in my search.

**Comment by stubailo** [comment]
That indeed is a duplicate. Are the docs for this inadequate? Should we improve the content in docs.meteor.com about the mobile config file?
