### ISSUE TITLE
Greeting never received with email 1.0.7

### ISSUE THREAD

**Issue by d4nyll** [meteor/meteor#5284]
I have a bog-standard user accounts / password implementation and was working well until this afternoon, when I updated the `email` package from `1.0.6` to `1.0.7`, I now get this error when trying to send a verification email when creating a user.

`Exception while invoking method 'createUser' E rror: Greeting never received`

Sorry I don't have the time to post a full bug report right now, I will update with more details later.

**Comment by stubailo** [comment]
This could be any variety of different things. The Email package is basically the same as before, so I don't know how it could cause your error.

Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by yogiben** [comment]
@stubailo believe I'm experiencing the same. I can add some more info

Working on staging & production servers (Modulus). Not working when running locally such as

`MAIL_URL=... meteor`

Full error:
```
I20160202-16:21:10.020(1)? Exception while invoking method 'ATCreateUserServer' Error: Greeting never received
I20160202-16:21:10.021(1)?     at Object.Future.wait (/Users/gringo/.meteor/packages/meteor-tool/.1.1.10.lf79tx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20160202-16:21:10.021(1)?     at smtpSend (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/email.js:103:37)
I20160202-16:21:10.021(1)?     at Object.Email.send (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/email.js:202:5)
I20160202-16:21:10.021(1)?     at Object.Email.send (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:3143:28)
I20160202-16:21:10.021(1)?     at AccountsServer.Accounts.sendVerificationEmail (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/accounts-password.js:789:9)
I20160202-16:21:10.021(1)?     at [object Object].Meteor.methods.ATCreateUserServer (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/useraccounts_core.js:1304:16)
I20160202-16:21:10.021(1)?     at [object Object].methodMap.(anonymous function) (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2515:30)
I20160202-16:21:10.021(1)?     at maybeAuditArgumentChecks (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/ddp-server.js:1785:12)
I20160202-16:21:10.021(1)?     at /Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/ddp-server.js:872:20
I20160202-16:21:10.021(1)?     at [object Object]._.extend.withValue (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/meteor.js:1021:17)
I20160202-16:21:10.021(1)?     at /Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/ddp-server.js:871:41
I20160202-16:21:10.022(1)?     at [object Object]._.extend.withValue (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/meteor.js:1021:17)
I20160202-16:21:10.022(1)?     at /Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/ddp-server.js:870:46
I20160202-16:21:10.022(1)?     at tryCallTwo (/Users/gringo/.meteor/packages/promise/.0.5.1.1ae4h7c++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160202-16:21:10.022(1)?     at doResolve (/Users/gringo/.meteor/packages/promise/.0.5.1.1ae4h7c++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20160202-16:21:10.022(1)?     at new Promise (/Users/gringo/.meteor/packages/promise/.0.5.1.1ae4h7c++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
I20160202-16:21:10.022(1)?     at [object Object]._.extend.protocol_handlers.method (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/ddp-server.js:848:21)
I20160202-16:21:10.022(1)?     at /Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2403:38
I20160202-16:21:10.022(1)?     at [object Object]._.extend.withValue (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/meteor.js:1021:17)
I20160202-16:21:10.022(1)?     at [object Object].sessionProto.protocol_handlers.method (/Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2402:44)
I20160202-16:21:10.022(1)?     at /Users/gringo/dev/bitcoin/bitwala/app/.meteor/local/build/programs/server/packages/ddp-server.js:729:85
I20160202-16:21:10.023(1)?     - - - - -
I20160202-16:21:10.023(1)?     at SMTPClient.<anonymous> (/Users/gringo/.meteor/packages/email/.1.0.8.1tv9xsa++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:268:25)
I20160202-16:21:10.023(1)?     at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

**Comment by raduchiriac** [comment]
I am running a Modulus hosted Telescope app and I get the same error from time to time. I don't know exactly what is causing this, but it doesn't seem to be related to anything from my code. That `checkInfo` method is properly executing 99% of the times. 

```shell
//////// sending email…
from: no-reply@12345.org
to: 123@123456.us
subject: [siteName.org] Verify your account
Exception while invoking method 'checkInfo' Error: Greeting never received
    at Object.Future.wait (/mnt/app/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/email/email.js:86:1)
    at Object.Email.send (packages/email/email.js:185:1)
    at Object.Email.send (packages/meteorhacks_kadira/lib/hijack/email.js:10:1)
    at Object.Telescope.email.send (lib/server/email.js:82:9)
    at Object.Telescope.email.buildAndSend (server/email.js:27:26)
    at adminUserCreationNotification (server/signup.js:138:21)
    at [object Object].Meteor.methods.checkInfo (server/methods.js:54:14)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (livedata_server.js:1698:12)
```

**Comment by MichaelJCole** [comment]
This is a transport error with NodeMailer.  
https://github.com/nodemailer/nodemailer/issues/441

I'm getting this after a switch from mandrill (never saw it) to sparkpost (happening 1%-5% of time)

The workround is in the linked bug, which is to set the ssl to true. 

Setting protocol to smpts://  in process.env.MAIL_URL doesn't work.

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  If you're still having this issue, I would suggest checking #7042 and the related PR to see if it may pertain to your issue and open a new issue with a reproduction per [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines.

Thanks!
