### ISSUE TITLE
Getting EEXIST running `meteor run --test` or `meteor` on jenkins server

### ISSUE THREAD

**Issue by swemail** [meteor/meteor#5305]
Works on my local machine but not on jenkins (docker hub official image), meteor version 1.1.0.2

```
[[[[[ ~/jobs/Twine/workspace ]]]]]            

=> Started proxy.                             
=> Meteor 1.2.0.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
                                              
/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: EEXIST, mkdir '/var/jenkins_home/jobs/Twine/workspace/.meteor/local/.build570532.build/programs/.build231809.server/app/dev_bundle/lib/node_modules/es5-ext/test/array/'
    at Object.Future.wait (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.wrapper [as mkdir] (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:1350:24)
    at [object Object]._.extend.reserve (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/builder.js:241:17)
    at [object Object]._.extend.generateFilename (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/builder.js:274:10)
    at [object Object]._.extend.writeToGeneratedFilename (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/builder.js:287:26)
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:1505:31
    at Array.forEach (native)
    at Function._.each._.forEach (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at [object Object]._.extend.write (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:1465:7)
    at [object Object]._.extend.write (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:1750:13)
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:1815:12
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:1918:25
    at Function._.each._.forEach (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:1917:7
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:2147:20
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/buildmessage.js:245:19)
    at Object.exports.bundle (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/bundler.js:2040:31)
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:554:24
    at time (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/profile.js:231:28)
    at Function.run (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/profile.js:377:12)
    at bundleApp (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:544:34)
    at [object Object]._.extend._runOnce (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:591:35)
    at [object Object]._.extend._fiber (/var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:821:28)
    at /var/jenkins_home/.meteor/packages/meteor-tool/.1.1.3.vbxqhq++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/run-app.js:402:12
```

**Comment by stubailo** [comment]
Can you help me build a recipe for a reproduction? Right now I don't know where I would start. Will reopen if there is a clear path to a repro that I can follow on my machine.
