### ISSUE TITLE
Meteor doesn't recover from MongoDB connection failure after idling some time 

### ISSUE THREAD

**Issue by Shogutora** [meteor/meteor#5306]
I have an application that uses mongolab for distributed mongodb . If idling in the browser on a particular page for some time, I receive the following in the server console:

```javascript
I20150928-02:45:04.232(3)? Exception while polling query {"collectionName":"cfs.images.filerecord","selector":{"uploadedAt":{"$exists":true},"copies.images":null,"failures.copies.images.doneTrying":{"$ne":true}},"options":{"fields":{"copies":0}}}: Error: failed to connect to [ds055732.mongolab.com:55732]
I20150928-02:45:04.233(3)?     at Object.Future.wait (/Users/yrkkoa/.meteor/packages/meteor-tool/.1.1.4.1hqa553++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20150928-02:45:04.234(3)?     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
I20150928-02:45:04.234(3)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
I20150928-02:45:04.234(3)?     at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:1012:1)
I20150928-02:45:04.234(3)?     at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:147:1)
I20150928-02:45:04.234(3)?     at Object.task (packages/mongo/polling_observe_driver.js:85:1)
I20150928-02:45:04.234(3)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20150928-02:45:04.234(3)?     at packages/meteor/fiber_helpers.js:125:1
I20150928-02:45:04.234(3)?     - - - - -
I20150928-02:45:04.234(3)?     at [object Object].<anonymous> (/Users/yrkkoa/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
I20150928-02:45:04.234(3)?     at [object Object].emit (events.js:106:17)
I20150928-02:45:04.234(3)?     at [object Object].<anonymous> (/Users/yrkkoa/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
I20150928-02:45:04.234(3)?     at [object Object].emit (events.js:98:17)
I20150928-02:45:04.234(3)?     at Socket.<anonymous> (/Users/yrkkoa/.meteor/packages/mongo/.1.1.0.1ruc6ua++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
I20150928-02:45:04.234(3)?     at Socket.emit (events.js:95:17)
I20150928-02:45:04.235(3)?     at net.js:441:14
I20150928-02:45:04.235(3)?     at process._tickCallback (node.js:442:13)
```

I have set up the mongolab via MONGO_URL env var.

This results in images not being shown in the templates unless refreshing the whole application.
It also disables reactivity from the template, meaning the data in the page is as it was before the exception.

**Comment by zol** [comment]
There are definitely attempts in the code to make reconnection work. So we're really going to need a reproduction to be able to work on this. https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor

**Comment by raphaelarias** [comment]
I'm having this problem now almost every day. I'm using Galaxy.

I can't manage to reproduce this in dev, would it be possible for us to use Galaxy logs or something?
