### ISSUE TITLE
1.2.0.2 - importing SCSS files results in an error

### ISSUE THREAD

**Issue by ffxsam** [meteor/meteor#5330]
I'm using `fourseven;scss` and importing via the new syntax:

    @import "{}/client/styles/variables.import.scss";

And I'm getting this error on the server end:

```
W20150929-12:38:13.533(-7)? (STDERR) ReferenceError: Plugin is not defined
W20150929-12:38:13.533(-7)? (STDERR)     at path (caching-compiler.js:1:12)
W20150929-12:38:13.533(-7)? (STDERR)     at /Volumes/SuperData/Sites/myapp/.meteor/local/build/programs/server/packages/caching-compiler.js:482:4
W20150929-12:38:13.533(-7)? (STDERR)     at multi-file-caching-compiler.js:216:2
W20150929-12:38:13.534(-7)? (STDERR)     at /Volumes/SuperData/Sites/myapp/.meteor/local/build/programs/server/boot.js:242:10
W20150929-12:38:13.534(-7)? (STDERR)     at Array.forEach (native)
W20150929-12:38:13.534(-7)? (STDERR)     at Function._.each._.forEach (/Users/samh/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150929-12:38:13.534(-7)? (STDERR)     at /Volumes/SuperData/Sites/myapp/.meteor/local/build/programs/server/boot.js:137:5
```

**Comment by Krabaul** [comment]
+1

**Comment by cryptoquick** [comment]
I'm also having this issue. In a large project, removing fourseven:scss fixed my build, and adding it breaks it. I don't believe this is a problem with that particular package.

I'm getting a very similar error:

```
ReferenceError: Plugin is not defined
W20150929-14:06:48.522(-6)? (STDERR)     at path (caching-compiler.js:1:12)
W20150929-14:06:48.523(-6)? (STDERR)     at /Users/xxx/GitHub/xxx/.meteor/local/build/programs/server/packages/caching-compiler.js:482:4
W20150929-14:06:48.523(-6)? (STDERR)     at multi-file-caching-compiler.js:216:2
W20150929-14:06:48.523(-6)? (STDERR)     at /Users/xxx/GitHub/xxx/.meteor/local/build/programs/server/boot.js:242:10
W20150929-14:06:48.523(-6)? (STDERR)     at Array.forEach (native)
W20150929-14:06:48.523(-6)? (STDERR)     at Function._.each._.forEach (/Users/xxx/.meteor/packages/meteor-tool/.1.1.9.nv791y++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150929-14:06:48.523(-6)? (STDERR)     at /Users/xxx/GitHub/xxx/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

**Comment by sebakerckhof** [comment]
This is a package specific issue: https://github.com/fourseven/meteor-scss/issues/114

**Comment by sebakerckhof** [comment]
Should be fixed

**Comment by ffxsam** [comment]
Awesome, thanks for the heads up!

**Comment by avital** [comment]
Happy to see this was fixed!
