### ISSUE TITLE
[1.2.0.2] Updated meteor but throws TypeError: Property 'undefined' of object [object Object] is not a function

### ISSUE THREAD

**Issue by digz6666** [meteor/meteor#5332]
Updated meteor from 1.1.0.3 to 1.2.0.2 with meteor update command:
```
C:\meteor_app>meteor update

Changes to your project's package version selections from updating the
release:

accounts-base           upgraded from 1.2.0 to 1.2.1
accounts-password       upgraded from 1.1.1 to 1.1.3
autoupdate              upgraded from 1.2.1 to 1.2.3
babel-compiler          added, version 5.8.24_1
babel-runtime           added, version 0.1.4
base64                  upgraded from 1.0.3 to 1.0.4
binary-heap             upgraded from 1.0.3 to 1.0.4
blaze                   upgraded from 2.1.2 to 2.1.3
blaze-tools             upgraded from 1.0.3 to 1.0.4
boilerplate-generator   upgraded from 1.0.3 to 1.0.4
caching-compiler        added, version 1.0.0
caching-html-compiler   added, version 1.0.2
callback-hook           upgraded from 1.0.3 to 1.0.4
check                   upgraded from 1.0.5 to 1.0.6
ddp                     upgraded from 1.1.0 to 1.2.2
ddp-client              added, version 1.2.1
ddp-common              added, version 1.2.1
ddp-rate-limiter        added, version 1.0.0
ddp-server              added, version 1.2.1
deps                    upgraded from 1.0.7 to 1.0.9
diff-sequence           added, version 1.0.1
ecmascript              added, version 0.1.5
ecmascript-collections  added, version 0.1.6
ejson                   upgraded from 1.0.6 to 1.0.7
email                   upgraded from 1.0.6 to 1.0.7
fastclick               upgraded from 1.0.3 to 1.0.7
geojson-utils           upgraded from 1.0.3 to 1.0.4
html-tools              upgraded from 1.0.4 to 1.0.5
htmljs                  upgraded from 1.0.4 to 1.0.5
http                    upgraded from 1.1.0 to 1.1.1
id-map                  upgraded from 1.0.3 to 1.0.4
insecure                upgraded from 1.0.3 to 1.0.4
jquery                  upgraded from 1.11.3_2 to 1.11.4
json                    removed from your project
launch-screen           upgraded from 1.0.2 to 1.0.4
livedata                upgraded from 1.0.13 to 1.0.15
localstorage            upgraded from 1.0.3 to 1.0.5
logging                 upgraded from 1.0.7 to 1.0.8
meteor                  upgraded from 1.1.6 to 1.1.9
meteor-platform         upgraded from 1.2.2 to 1.2.3
minifiers               upgraded from 1.1.5 to 1.1.7
minimongo               upgraded from 1.0.8 to 1.0.10
mobile-status-bar       upgraded from 1.0.3 to 1.0.6
mongo                   upgraded from 1.1.0 to 1.1.2
mongo-id                added, version 1.0.1
mongo-livedata          upgraded from 1.0.8 to 1.0.9
npm-mongo               added, version 1.4.39_1
observe-sequence        upgraded from 1.0.6 to 1.0.7
ordered-dict            upgraded from 1.0.3 to 1.0.4
promise                 added, version 0.5.0
random                  upgraded from 1.0.3 to 1.0.4
rate-limit              added, version 1.0.0
reactive-dict           upgraded from 1.1.0 to 1.1.2
reactive-var            upgraded from 1.0.5 to 1.0.6
reload                  upgraded from 1.1.3 to 1.1.4
retry                   upgraded from 1.0.3 to 1.0.4
routepolicy             upgraded from 1.0.5 to 1.0.6
service-configuration   upgraded from 1.0.4 to 1.0.5
session                 upgraded from 1.1.0 to 1.1.1
sha                     upgraded from 1.0.3 to 1.0.4
spacebars               upgraded from 1.0.6 to 1.0.7
spacebars-compiler      upgraded from 1.0.6 to 1.0.7
srp                     upgraded from 1.0.3 to 1.0.4
templating              upgraded from 1.1.1 to 1.1.4
templating-tools        added, version 1.0.0
tracker                 upgraded from 1.0.7 to 1.0.9
ui                      upgraded from 1.0.6 to 1.0.8
underscore              upgraded from 1.0.3 to 1.0.4
url                     upgraded from 1.0.4 to 1.0.5
webapp                  upgraded from 1.2.0 to 1.2.2
webapp-hashing          upgraded from 1.0.3 to 1.0.5

meteor_app: updated to Meteor 1.2.0.2.

-- Notice --

1.2: Meteor 1.2 includes many changes and improvements to the build
     system, some of which might require small changes to apps and
     packages. Please read the guide about breaking changes here:
     https://github.com/meteor/meteor/wiki/Breaking-changes-in-Meteor-1.2

Changes to your project's package version selections from updating package
versions:

aldeed:template-extension        removed from your project
babrahams:editable-json          removed from your project
blaze-html-templates             added, version 1.0.1
cfs:http-methods                 upgraded from 0.0.29 to 0.0.30
dburles:google-maps              upgraded from 1.1.1 to 1.1.4
fortawesome:fontawesome          upgraded from 4.3.0 to 4.4.0
gwendall:session-json            removed from your project
hot-code-push                    added, version 1.0.0
matb33:collection-hooks          upgraded from 0.7.13 to 0.8.0
meteor-base                      added, version 1.0.1
meteor-platform                  removed from your project
meteorhacks:aggregate            upgraded from 1.2.1 to 1.3.0
meteortoys:toykit*               upgraded from 0.8.2 to 1.0.0
mobile-experience                added, version 1.0.1
msavin:mongol                    upgraded from 1.1.0 to 1.2.0
standard-minifiers               added, version 1.0.1
themeteorchef:jquery-validation  upgraded from 1.13.1 to 1.14.0


* These packages have been updated to new versions that are not
backwards
compatible.

C:\meteor_app>
```

But it throws TypeError: Property 'undefined' of object [object Object] is not a function on start
```
"C:\Program Files (x86)\JetBrains\WebStorm 10.0.4\bin\runnerw.exe" C:\Users\MethoD\AppData\Local\.meteor\meteor.bat
[[[[[ C:\meteor_app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20150930-12:41:47.046(8)? (STDERR) 
W20150930-12:41:47.047(8)? (STDERR) C:\Users\MethoD\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20150930-12:41:47.047(8)? (STDERR) 						throw(ex);
W20150930-12:41:47.048(8)? (STDERR) 						      ^
W20150930-12:41:47.048(8)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-12:41:47.048(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-12:41:47.048(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150930-12:41:47.048(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\packages\meteortoys_toykit.js:325:4
W20150930-12:41:47.048(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\packages\meteortoys_toykit.js:334:3
W20150930-12:41:47.049(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\boot.js:242:10
W20150930-12:41:47.049(8)? (STDERR)     at Array.forEach (native)
W20150930-12:41:47.049(8)? (STDERR)     at Function._.each._.forEach (C:\Users\MethoD\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20150930-12:41:47.049(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\boot.js:137:5
=> Exited with code: 8
W20150930-12:41:59.510(8)? (STDERR) 
W20150930-12:41:59.510(8)? (STDERR) C:\Users\MethoD\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20150930-12:41:59.510(8)? (STDERR) 						throw(ex);
W20150930-12:41:59.511(8)? (STDERR) 						      ^
W20150930-12:41:59.511(8)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-12:41:59.511(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-12:41:59.511(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150930-12:41:59.511(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\packages\meteortoys_toykit.js:325:4
W20150930-12:41:59.512(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\packages\meteortoys_toykit.js:334:3
W20150930-12:41:59.512(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\boot.js:242:10
W20150930-12:41:59.512(8)? (STDERR)     at Array.forEach (native)
W20150930-12:41:59.513(8)? (STDERR)     at Function._.each._.forEach (C:\Users\MethoD\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20150930-12:41:59.513(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\boot.js:137:5
W20150930-12:42:13.809(8)? (STDERR) 
W20150930-12:42:13.810(8)? (STDERR) C:\Users\MethoD\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20150930-12:42:13.811(8)? (STDERR) 						throw(ex);
W20150930-12:42:13.811(8)? (STDERR) 						      ^
W20150930-12:42:13.811(8)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-12:42:13.811(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-12:42:13.811(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150930-12:42:13.811(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\packages\meteortoys_toykit.js:325:4
W20150930-12:42:13.811(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\packages\meteortoys_toykit.js:334:3
W20150930-12:42:13.812(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\boot.js:242:10
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20150930-12:42:13.812(8)? (STDERR)     at Array.forEach (native)
W20150930-12:42:13.812(8)? (STDERR)     at Function._.each._.forEach (C:\Users\MethoD\AppData\Local\.meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20150930-12:42:13.812(8)? (STDERR)     at C:\meteor_app\.meteor\local\build\programs\server\boot.js:137:5

Process finished with exit code -1
```

**Comment by digz6666** [comment]
Seems like https://atmospherejs.com/meteortoys/toykit this package from https://atmospherejs.com/msavin/mongol caused the issue, removed it and works

**Comment by otroboe** [comment]
An open issue here: https://github.com/msavin/Mongol/issues/115

**Comment by mikeislearning** [comment]
Thank you for this!

**Comment by armandomendivil** [comment]
Update meteortoys:allthings to 2.0.0 version, works for me

**Comment by stubailo** [comment]
Yep, looks like a bug in Meteor Toys.

**Comment by fearless23** [comment]
change to Mongo.Collection .......... i changed c to C and it worked

**Comment by yuefengh** [comment]
I have the same problem. Because the speed of operation system, I put the  TMP, TEMP directory to ram disk. After changed the TMP, TEMP directory to the larger disk partition, then it work.
