### ISSUE TITLE
[MOBILE] meteor run android-device fails after upgrade to 1.2.0.1 (errors executing Cordova commands)

### ISSUE THREAD

**Issue by VioletaCalvo** [meteor/meteor#5336]
Hi!

After upgrading to Meteor 1.2.0.1 I cannot run with `meteor run android-device --settings config/local_settings.json`. I modified the code in order to use right cordova package names and versions I can't find the problem. 

I've also tried to delete android SDK Platform 22 ([as in this link] (http://stackoverflow.com/questions/32780560/meteor-run-android-device-stopped-working)) and install it again but nothing works.

This is what I get after running the command:

```
=> Started proxy.                             
=> Started MongoDB.                           
% Unsupported global orientation: portait                                          
% Defaulting to value: default                                                     
                                                                                   
WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that
         the network configuration allows clients to talk to each other (no client isolation).
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed: /home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/cordova/run --device
   Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: zip file is empty
   at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
   at org.gradle.wrapper.Install.createDist(Install.java:47)
   at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
   at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
   Caused by: java.util.zip.ZipException: zip file is empty
   at java.util.zip.ZipFile.open(Native Method)
   at java.util.zip.ZipFile.<init>(ZipFile.java:215)
   at java.util.zip.ZipFile.<init>(ZipFile.java:145)
   at java.util.zip.ZipFile.<init>(ZipFile.java:159)
   at org.gradle.wrapper.Install.unzip(Install.java:160)
   at org.gradle.wrapper.Install.access$400(Install.java:29)
   at org.gradle.wrapper.Install$1.call(Install.java:70)
   at org.gradle.wrapper.Install$1.call(Install.java:47)
   at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
   ... 3 more
   
   /home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   Error code 1 for command: /home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/gradlew with args:
   cdvBuildDebug,-b,/home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1
```
Thank you in advance.

**Comment by martijnwalraven** [comment]
(This doesn't have anything to do with this issue, but you seem to have misspelled `portrait` as `portait` in your config.)

It seems your Gradle installation may somehow have become corrupted. If you delete it with `rm -rf ~/.gradle` it should be reinstalled on the next build. I hope this works!

**Comment by VioletaCalvo** [comment]
Thank you @martijnwalraven, I've modified the portrait in my config :blush: 

I've made also `rm -rf ~/.gradle` but now I get another error (I've tried with an Android 4.4 device and with another Android 4.0.4 and get the same error: 

```
(18:09:30)[alpha]$ meteor run android-device --settings config/local_settings.json
[[[[[ ~/Downloads/meteor-projects/alpha ]]]]] 

=> Started proxy.                             
=> Started MongoDB.                           
                                                                                   
WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that
         the network configuration allows clients to talk to each other (no client isolation).
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
I20150930-18:13:34.050(2)? ** You are using the appcache package but the total size of the
I20150930-18:13:34.065(2)? ** cached resources is 9.7MB.
I20150930-18:13:34.066(2)? **                 
I20150930-18:13:34.066(2)? ** This is over the recommended maximum of 5 MB and may break your
I20150930-18:13:34.066(2)? ** app in some browsers! See http://docs.meteor.com/#appcache
I20150930-18:13:34.066(2)? ** for more information and fixes.
I20150930-18:13:34.066(2)?                    
I20150930-18:13:34.067(2)? ROOT_URL: http://localhost:3000/
I20150930-18:13:34.067(2)? MOBILE_ROOT_URL: http://192.168.1.58:3000
I20150930-18:13:34.067(2)? MOBILE_DDP_URL: http://192.168.1.58:3000
I20150930-18:13:34.068(2)? DDP_DEFAULT_CONNECTION_URL: undefined
I20150930-18:13:34.068(2)? Kadira: completed instrumenting the app
I20150930-18:13:34.070(2)? Kadira: successfully authenticated
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed: /home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/cordova/run --device
   /home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/inappbrowser/InAppBrowser.java:120: error: cannot
   find symbol
   || Config.isUrlWhiteListed(url)) {
   ^
   symbol:   method isUrlWhiteListed(String)
   location: class Config
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use unchecked or unsafe operations.
   Note: Recompile with -Xlint:unchecked for details.
   1 error
   
   FAILURE: Build failed with an exception.
   
   * What went wrong:
   Execution failed for task ':compileDebugJava'.
   > Compilation failed; see the compiler error output for details.
   
   * Try:
   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
   
   /home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   Error code 1 for command: /home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/gradlew with args:
   cdvBuildDebug,-b,/home/violeta/Downloads/meteor-projects/alpha/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1

```

**Comment by martijnwalraven** [comment]
That's due to an incompatibility between an older version of `cordova-plugin-inappbrowser` and the Cordova Android version bundled with Meteor 1.2. Updating the plugin to the latest version should solve this (`meteor add cordova:cordova-plugin-inappbrowser@1.0.1`).

**Comment by VioletaCalvo** [comment]
Finally it works, thank you @martijnwalraven! :blush:

**Comment by FGM** [comment]
FWIW, I had a somehow related issue : the application would not launch, because AndroidStudio / Android SDK Manager only provide Gradle 2.4. Removing ~/.gradle allowed Gradle 2.2.1 to be downloaded during build.
