### ISSUE TITLE
Cannot run on Microsoft Docker Containers ( Server 2016 TP3 )

### ISSUE THREAD

**Issue by hvram1** [meteor/meteor#5383]
Hi
   I followed the alternative install and built a Docker Container for meteor . But i am getting the following error when  I am running

      This is what I did : 
1. Downloaded the alternatve install (tar.gz ) and repackaged it as a zip file 
2. Used the Dockerfile to copy the .zip file and then unzip inside the container using Powershell
3. run the meteor.bat 

I got errors while unpacking in Step 1 which mostly seemed to be of the type that file exists and do u want to override . ( i said No to All )

C:\m32\meteor\packages\meteor-tool\1.1.9\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Can't get default release version for track undefined
    at [object Object]._.extend.getDefaultReleaseVersion (C:\tools\packaging\catalog\catalog-remote.js:852:13)
    at Object.release.latestKnown (C:\tools\packaging\release.js:189:41)
    at C:\tools\cli\main.js:853:29

**Comment by hvram1** [comment]
Duplicate of #4702 . Fixed by adding the METEOR_WAREHOUSE_DIR env variable
