### ISSUE TITLE
HTTP.get throws Fiber error

### ISSUE THREAD

**Issue by mhhf** [meteor/meteor#5395]
When i use the Meteors HTTP.get method to call an API, I get this Error:

```
Possibly unhandled Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at Object.Meteor.bindEnvironment (packages/meteor/dynamics_nodejs.js:85:1)
    at Object.call (packages/meteor/helpers.js:117:1)
    at Object.HTTP.get (packages/http/httpcall_common.js:50:1)
    at __ipfs (server/lib/ipfsWrapper.jsx:27:10)
    at __catJson (server/lib/ipfsWrapper.jsx:37:4)
    at Object.catJson (server/lib/ipfsWrapper.jsx:105:5)
    at server/DB.jsx:19:41
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at ipfsWrapper.catJsonP.then.then.header (server/DB.jsx:18:7)
```

I don't use any 3rd party tools, so this might be a bug within Meteor itself.

**Comment by mizzao** [comment]
The error message literally tells you what you need to do: wrap the callback in `Meteor.bindEnvironment`.

**Comment by mitar** [comment]
Please provide a full reproduction: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor

**Comment by timbotnik** [comment]
That is unexpected, yes a reproduction would be helpful.  Perhaps you are calling `HTTP.get` from within an NPM package callback?  This may help: https://www.discovermeteor.com/blog/wrapping-npm-packages/

**Comment by abernix** [comment]
@mhhf Without a reproduction there isn't much help that can be provided.  Please let us know if you can get one put together, otherwise, consult the docs at http://docs.meteor.com which documents how to use `HTTP.call`.
