### ISSUE TITLE
meteor add-platform ios error

### ISSUE THREAD

**Issue by StijnAvdL** [meteor/meteor#5467]
I try to do <b>meteor add-platform ios</b> on my iOS system. But i get the error:

<code>enoent no such file or directory</code>

i succesfully run meteor install-sdk ios. And my meteor project is succesfully build (version 1.2.0.2)

also tried <b>meteor add-platform android</b> isnt working too with same error. Can someone help me with this problem? 

Thanks in advance.

**Comment by bramsdenteuling** [comment]
I get the same error when adding platform:

Adding platform iOS to Cordova project        
                                              
/Users/bramdenteuling/.meteor/packages/meteor-tool/.1.1.9.ecy1kx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: ENOENT, no such file or directory
    at process.chdir (/Users/bramdenteuling/.meteor/packages/meteor-tool/.1.1.9.ecy1kx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:18:9)
    at CordovaProject.runCommands (/tools/cordova/project.js:617:15)
    at CordovaProject.addPlatform (/tools/cordova/project.js:323:10)
    at CordovaProject.ensurePlatformsAreSynchronized (/tools/cordova/project.js:350:12)
    at /tools/cli/commands-cordova.js:57:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:268:29)
    at Command._mainJs2.default.registerCommand.name [as func] (/tools/cli/commands-cordova.js:42:8)

**Comment by StijnAvdL** [comment]
We both had a typo in the mobile-config.js file ...

**Comment by martijnwalraven** [comment]
So what was the type that caused this issue? It might make sense to improve the error message here...

**Comment by bramsdenteuling** [comment]
True. It was a missing comma in mobile-config.js in App.launchScreens({}) between two different screens.
