### ISSUE TITLE
`meteor build` not successful with node v4.2.1

### ISSUE THREAD

**Issue by buhrmi** [meteor/meteor#5485]
We have upgraded Jenkins to node v4.2.1 and now the Meteor build fails. Is somebody already on this?

```
> fibers@1.0.5 install /var/lib/jenkins/jobs/athena-qa/workspace/.build_target/bundle/programs/server/node_modules/fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory `/var/lib/jenkins/jobs/athena-qa/workspace/.build_target/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from /var/lib/jenkins/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
../src/fibers.cc:39:58: error: ‘Handle’ has not been declared
../src/fibers.cc:39:64: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/fibers.cc: In function ‘void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)’:
../src/fibers.cc:40:29: error: ‘handle’ was not declared in this scope
../src/fibers.cc: At global scope:
../src/fibers.cc:62:26: error: variable or field ‘SetInternalPointer’ declared void
../src/fibers.cc:62:26: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:62:34: error: expected primary-expression before ‘>’ token
../src/fibers.cc:62:36: error: ‘handle’ was not declared in this scope
../src/fibers.cc:62:44: error: expected primary-expression before ‘int’
../src/fibers.cc:62:55: error: expected primary-expression before ‘void’
../src/fibers.cc:66:27: error: template declaration of ‘void* uni::GetInternalPointer’
../src/fibers.cc:66:27: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:66:35: error: expected primary-expression before ‘>’ token
../src/fibers.cc:66:37: error: ‘handle’ was not declared in this scope
../src/fibers.cc:66:45: error: expected primary-expression before ‘int’
../src/fibers.cc:71:2: error: ‘Handle’ does not name a type
../src/fibers.cc:76:14: error: variable or field ‘Return’ declared void
../src/fibers.cc:76:14: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:76:22: error: expected primary-expression before ‘>’ token
../src/fibers.cc:76:24: error: ‘handle’ was not declared in this scope
../src/fibers.cc:76:32: error: expected primary-expression before ‘const’
../src/fibers.cc:80:14: error: variable or field ‘Return’ declared void
../src/fibers.cc:80:14: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:80:22: error: expected primary-expression before ‘>’ token
../src/fibers.cc:80:24: error: ‘handle’ was not declared in this scope
../src/fibers.cc:80:51: error: expected primary-expression before ‘info’
../src/fibers.cc:88:2: error: ‘Handle’ does not name a type
../src/fibers.cc:92:2: error: ‘Handle’ does not name a type
../src/fibers.cc:96:2: error: ‘Handle’ does not name a type
../src/fibers.cc:100:2: error: ‘Handle’ does not name a type
../src/fibers.cc:104:2: error: ‘Handle’ does not name a type
../src/fibers.cc:108:2: error: ‘Handle’ does not name a type
../src/fibers.cc:112:2: error: ‘Handle’ does not name a type
../src/fibers.cc:116:2: error: ‘Handle’ does not name a type
../src/fibers.cc:126:2: error: ‘Handle’ does not name a type
../src/fibers.cc: In function ‘void uni::SetResourceConstraints(v8::Isolate*, v8::ResourceConstraints*)’:
../src/fibers.cc:140:3: error: ‘SetResourceConstraints’ is not a member of ‘v8’
../src/fibers.cc:140:3: note: suggested alternative:
../src/fibers.cc:139:7: note:   ‘uni::SetResourceConstraints’
../src/fibers.cc: At global scope:
../src/fibers.cc:283:17: error: expected ‘;’ at end of member declaration
../src/fibers.cc:283:30: error: expected ‘)’ before ‘<’ token
../src/fibers.cc:289:15: error: expected ‘)’ before ‘<’ token
../src/fibers.cc:554:3: error: ‘Handle’ does not name a type
../src/fibers.cc:721:20: error: ‘Handle’ has not been declared
../src/fibers.cc:721:26: error: expected ‘,’ or ‘...’ before ‘<’ token
../src/fibers.cc: In static member function ‘static void Fiber::DestroyOrphans()’:
../src/fibers.cc:370:30: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::New(const Arguments&)’:
../src/fibers.cc:392:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:392:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:392:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:394:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:394:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:394:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:396:5: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:396:17: error: expected primary-expression before ‘>’ token
../src/fibers.cc:396:19: error: ‘argv’ was not declared in this scope
../src/fibers.cc:397:24: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc:397:106: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:400:4: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:400:19: error: expected primary-expression before ‘>’ token
../src/fibers.cc:400:21: error: ‘fn’ was not declared in this scope
../src/fibers.cc:400:41: error: expected primary-expression before ‘>’ token
../src/fibers.cc:400:42: error: ‘::Cast’ has not been declared
../src/fibers.cc:401:31: error: ‘GetCurrentContext’ is not a member of ‘uni’
../src/fibers.cc:402:40: error: no matching function for call to ‘Return(v8::Local<v8::Object>, const Arguments&)’
../src/fibers.cc:402:40: note: candidate is:
../src/fibers.cc:84:7: note: template<class T> void uni::Return(v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, uni::GetterCallbackInfo)
../src/fibers.cc:402:40: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::Run(const Arguments&)’:
../src/fibers.cc:410:38: error: no match for call to ‘(Fiber) (v8::Local<v8::Object>)’
../src/fibers.cc:416:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:416:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:416:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:418:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:418:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:418:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:429:6: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:429:6: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:429:6: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:439:52: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)’
../src/fibers.cc:439:52: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:441:52: error: ‘Undefined’ is not a member of ‘uni’
../src/fibers.cc:441:52: note: suggested alternatives:
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:8121:18: note:   ‘v8::Undefined’
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:8121:18: note:   ‘v8::Undefined’
../src/fibers.cc:445:28: error: ‘class Fiber’ has no member named ‘ReturnYielded’
../src/fibers.cc:445:49: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::ThrowInto(const Arguments&)’:
../src/fibers.cc:452:38: error: no match for call to ‘(Fiber) (v8::Local<v8::Object>)’
../src/fibers.cc:455:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:455:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:455:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:457:51: error: ‘Undefined’ is not a member of ‘uni’
../src/fibers.cc:457:51: note: suggested alternatives:
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:8121:18: note:   ‘v8::Undefined’
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:8121:18: note:   ‘v8::Undefined’
../src/fibers.cc:459:51: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)’
../src/fibers.cc:459:51: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:461:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:461:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:461:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:465:28: error: ‘class Fiber’ has no member named ‘ReturnYielded’
../src/fibers.cc:465:49: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::Reset(const Arguments&)’:
../src/fibers.cc:473:38: error: no match for call to ‘(Fiber) (v8::Local<v8::Object>)’
../src/fibers.cc:476:24: error: ‘Undefined’ is not a member of ‘uni’
../src/fibers.cc:476:24: note: suggested alternatives:
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:8121:18: note:   ‘v8::Undefined’
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:8121:18: note:   ‘v8::Undefined’
../src/fibers.cc:476:58: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:478:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:478:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:478:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:480:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:480:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:480:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:488:4: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:488:16: error: expected primary-expression before ‘>’ token
../src/fibers.cc:488:18: error: ‘val’ was not declared in this scope
../src/fibers.cc:488:24: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc:491:24: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:491:68: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:493:33: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In member function ‘void Fiber::UnwindStack()’:
../src/fibers.cc:510:4: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:510:16: error: expected primary-expression before ‘>’ token
../src/fibers.cc:510:54: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:511:64: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Persistent<v8::Value>&)’
../src/fibers.cc:511:64: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:512:49: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Persistent<v8::Value>&)’
../src/fibers.cc:512:49: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:525:41: error: ‘Undefined’ is not a member of ‘uni’
../src/fibers.cc:525:41: note: suggested alternatives:
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:8121:18: note:   ‘v8::Undefined’
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:8121:18: note:   ‘v8::Undefined’
../src/fibers.cc: In static member function ‘static void Fiber::RunFiber(void**)’:
../src/fibers.cc:590:5: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:590:19: error: expected primary-expression before ‘>’ token
../src/fibers.cc:272:23: error: invalid use of member ‘Fiber::v8_context’ in static member function
../src/fibers.cc:590:21: error: from this location
../src/fibers.cc:590:34: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc:272:23: error: invalid use of member ‘Fiber::v8_context’ in static member function
../src/fibers.cc:591:5: error: from this location
../src/fibers.cc:595:21: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:597:17: error: expected primary-expression before ‘>’ token
../src/fibers.cc:274:21: error: invalid use of member ‘Fiber::yielded’ in static member function
../src/fibers.cc:597:19: error: from this location
../src/fibers.cc:599:18: error: expected primary-expression before ‘>’ token
../src/fibers.cc:599:20: error: ‘argv’ was not declared in this scope
../src/fibers.cc:274:21: error: invalid use of member ‘Fiber::yielded’ in static member function
../src/fibers.cc:600:6: error: from this location
../src/fibers.cc:600:16: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc:272:23: error: invalid use of member ‘Fiber::v8_context’ in static member function
../src/fibers.cc:600:56: error: from this location
../src/fibers.cc:274:21: error: invalid use of member ‘Fiber::yielded’ in static member function
../src/fibers.cc:602:6: error: from this location
../src/fibers.cc:602:16: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc:272:23: error: invalid use of member ‘Fiber::v8_context’ in static member function
../src/fibers.cc:602:56: error: from this location
../src/fibers.cc:606:66: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)’
../src/fibers.cc:606:66: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:608:45: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc:608:98: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc:610:67: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)’
../src/fibers.cc:610:67: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:274:21: error: invalid use of member ‘Fiber::yielded’ in static member function
../src/fibers.cc:613:45: error: from this location
../src/fibers.cc:272:23: error: invalid use of member ‘Fiber::v8_context’ in static member function
../src/fibers.cc:628:5: error: from this location
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::Yield_(const Arguments&)’:
../src/fibers.cc:643:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:643:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:643:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:649:24: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:649:58: error: ‘Deref’ is not a member of ‘uni’
../src/fibers.cc:649:112: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:651:74: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Primitive>)’
../src/fibers.cc:651:74: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:653:51: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::Value>&, v8::Local<v8::Value>)’
../src/fibers.cc:653:51: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:655:5: error: ‘ThrowException’ is not a member of ‘uni’
../src/fibers.cc:655:5: error: ‘NewLatin1String’ is not a member of ‘uni’
../src/fibers.cc:655:5: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:677:28: error: ‘class Fiber’ has no member named ‘ReturnYielded’
../src/fibers.cc:677:49: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::GetStarted(v8::Local<v8::String>, const GetterCallbackInfo&)’:
../src/fibers.cc:685:24: error: ‘Undefined’ is not a member of ‘uni’
../src/fibers.cc:685:24: note: suggested alternatives:
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:315:27: note:   ‘v8::Undefined’
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:315:27: note:   ‘v8::Undefined’
../src/fibers.cc:685:67: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc:687:36: error: no match for call to ‘(Fiber) (v8::Local<v8::Object>)’
../src/fibers.cc:688:23: error: ‘NewBoolean’ is not a member of ‘uni’
../src/fibers.cc:688:72: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::GetCurrent(v8::Local<v8::String>, const GetterCallbackInfo&)’:
../src/fibers.cc:695:24: error: ‘Undefined’ is not a member of ‘uni’
../src/fibers.cc:695:24: note: suggested alternatives:
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:315:27: note:   ‘v8::Undefined’
/var/lib/jenkins/.node-gyp/4.2.1/include/node/v8.h:315:27: note:   ‘v8::Undefined’
../src/fibers.cc:695:67: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::GetPoolSize(v8::Local<v8::String>, const GetterCallbackInfo&)’:
../src/fibers.cc:703:23: error: ‘NewNumber’ is not a member of ‘uni’
../src/fibers.cc:703:88: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function ‘static uni::FunctionType Fiber::GetFibersCreated(v8::Local<v8::String>, const GetterCallbackInfo&)’:
../src/fibers.cc:714:23: error: ‘NewNumber’ is not a member of ‘uni’
../src/fibers.cc:714:99: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/fibers.cc: In static member function ‘static void Fiber::Init(int)’:
../src/fibers.cc:734:4: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:734:27: error: expected primary-expression before ‘>’ token
../src/fibers.cc:734:36: error: ‘NewFunctionTemplate’ is not a member of ‘uni’
../src/fibers.cc:735:41: error: no matching function for call to ‘Reset(v8::Isolate*&, v8::Persistent<v8::FunctionTemplate>&, v8::Persistent<v8::FunctionTemplate>&)’
../src/fibers.cc:735:41: note: candidate is:
../src/fibers.cc:39:7: note: template<class T> void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)
../src/fibers.cc:736:8: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
../src/fibers.cc:736:23: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:740:20: error: expected primary-expression before ‘>’ token
../src/fibers.cc:740:22: error: ‘sig’ was not declared in this scope
../src/fibers.cc:740:28: error: ‘NewSignature’ is not a member of ‘uni’
../src/fibers.cc:741:8: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
../src/fibers.cc:744:25: error: expected primary-expression before ‘>’ token
../src/fibers.cc:744:27: error: ‘proto’ was not declared in this scope
../src/fibers.cc:744:39: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
../src/fibers.cc:745:15: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:746:5: error: ‘NewFunctionTemplate’ is not a member of ‘uni’
../src/fibers.cc:746:58: error: expected primary-expression before ‘>’ token
../src/fibers.cc:746:60: error: expected primary-expression before ‘)’ token
../src/fibers.cc:747:15: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:748:5: error: ‘NewFunctionTemplate’ is not a member of ‘uni’
../src/fibers.cc:748:56: error: expected primary-expression before ‘>’ token
../src/fibers.cc:748:58: error: expected primary-expression before ‘)’ token
../src/fibers.cc:749:15: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:750:5: error: ‘NewFunctionTemplate’ is not a member of ‘uni’
../src/fibers.cc:750:62: error: expected primary-expression before ‘>’ token
../src/fibers.cc:750:64: error: expected primary-expression before ‘)’ token
../src/fibers.cc:751:23: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:754:19: error: expected primary-expression before ‘>’ token
../src/fibers.cc:754:21: error: ‘yield’ was not declared in this scope
../src/fibers.cc:754:29: error: ‘NewFunctionTemplate’ is not a member of ‘uni’
../src/fibers.cc:755:17: error: expected primary-expression before ‘>’ token
../src/fibers.cc:755:19: error: ‘sym_yield’ was not declared in this scope
../src/fibers.cc:755:31: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:756:4: error: ‘target’ was not declared in this scope
../src/fibers.cc:759:19: error: expected primary-expression before ‘>’ token
../src/fibers.cc:759:21: error: ‘fn’ was not declared in this scope
../src/fibers.cc:759:30: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::FunctionTemplate>’
../src/fibers.cc:761:20: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:762:20: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:763:20: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc:766:16: error: ‘NewLatin1Symbol’ is not a member of ‘uni’
../src/fibers.cc: At global scope:
../src/fibers.cc:781:22: error: variable or field ‘init’ declared void
../src/fibers.cc:781:22: error: ‘Handle’ was not declared in this scope
../src/fibers.cc:781:35: error: expected primary-expression before ‘>’ token
../src/fibers.cc:781:37: error: ‘target’ was not declared in this scope
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/var/lib/jenkins/jobs/athena-qa/workspace/.build_target/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-53-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /var/lib/jenkins/jobs/athena-qa/workspace/.build_target/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
```

**Comment by martijnwalraven** [comment]
Meteor currently requires Node 0.10 (we use 0.10.40) and does not work on other versions.

**Comment by stubailo** [comment]
issue here: https://github.com/meteor/meteor/issues/5124

**Comment by reidlai** [comment]
but works in nodejs 5.1.1
