### ISSUE TITLE
Meteor with android having issue starting app on the device and emulator

### ISSUE THREAD

**Issue by hafizali05** [meteor/meteor#5531]
I am currently struggling with meteor over android.

I am getting some strange error when  I start the local host.

the error is as follows.

please help me get out of this issue, struggled with it since last two days.

=> App running at: http://localhost:4000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options
   --device:
   Error: Command failed:                     
   /home/hafiz/localmarket/.meteor/local/cordova-build/platforms/android/cordova/run
   --device

   /home/hafiz/localmarket/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   ERROR: Failed to deploy to device, no devices found.
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

**Comment by adrianolsk** [comment]
Run "adb list" to see if your device is detected.
Maybe a bad USB cable or some missing driver.
Try to open the emulator manually as well to check if it's working without
meteor.
Run adb list to see if the emulator is listed.
Try to run the app with the emulator opened.
Em 24/10/2015 19:44, "Hafiz" <notifications@github.com> escreveu:

**Comment by martijnwalraven** [comment]
Great advise, @adrianolsk!

@hafizali05: Did you manage to get this working?

**Comment by larfadin** [comment]
Same here. Juste install android sdk on ubuntu 15.10 everything work fine. My smartphone is connected to my computer on developer mod is active.
But it doesn't work when deploying my app on my phone 
`starting app on android device`
And it block here.  NOthing happened, just like that

**Comment by martijnwalraven** [comment]
@larfadin: What is the output of `adb list`?

**Comment by larfadin** [comment]
```
me@me-desktop:~/Documents/dev/my_project$ adb list

Android Debug Bridge version 1.0.31

 -a                            - directs adb to listen on all interfaces for a connection
 -d                            - directs command to the only connected USB device
                                 returns an error if more than one USB device is present.
 -e                            - directs command to the only running emulator.
                                 returns an error if more than one emulator is running.
 -s <specific device>          - directs command to the device or emulator with the given
                                 serial number or qualifier. Overrides ANDROID_SERIAL
                                 environment variable.
 -p <product name or path>     - simple product name like 'sooner', or
                                 a relative/absolute path to a product
                                 out directory like 'out/target/product/sooner'.
                                 If -p is not specified, the ANDROID_PRODUCT_OUT
                                 environment variable is used, which must
                                 be an absolute path.
 -H                            - Name of adb server host (default: localhost)
 -P                            - Port of adb server (default: 5037)
 devices [-l]                  - list all connected devices
                                 ('-l' will also list device qualifiers)
 connect <host>[:<port>]       - connect to a device via TCP/IP
                                 Port 5555 is used by default if no port number is specified.
 disconnect [<host>[:<port>]]  - disconnect from a TCP/IP device.
                                 Port 5555 is used by default if no port number is specified.
                                 Using this command with no additional arguments
                                 will disconnect from all connected TCP/IP devices.

device commands:
  adb push <local> <remote>    - copy file/dir to device
  adb pull <remote> [<local>]  - copy file/dir from device
  adb sync [ <directory> ]     - copy host->device only if changed
                                 (-l means list but don't copy)
                                 (see 'adb help all')
  adb shell                    - run remote shell interactively
  adb shell <command>          - run remote shell command
  adb emu <command>            - run emulator console command
  adb logcat [ <filter-spec> ] - View device log
  adb forward --list           - list all forward socket connections.
                                 the format is a list of lines with the following format:
                                    <serial> " " <local> " " <remote> "\n"
  adb forward <local> <remote> - forward socket connections
                                 forward specs are one of: 
                                   tcp:<port>
                                   localabstract:<unix domain socket name>
                                   localreserved:<unix domain socket name>
                                   localfilesystem:<unix domain socket name>
                                   dev:<character device name>
                                   jdwp:<process pid> (remote only)
  adb forward --no-rebind <local> <remote>
                               - same as 'adb forward <local> <remote>' but fails
                                 if <local> is already forwarded
  adb forward --remove <local> - remove a specific forward socket connection
  adb forward --remove-all     - remove all forward socket connections
  adb jdwp                     - list PIDs of processes hosting a JDWP transport
  adb install [-l] [-r] [-s] [--algo <algorithm name> --key <hex-encoded key> --iv <hex-encoded iv>] <file>
                               - push this package file to the device and install it
                                 ('-l' means forward-lock the app)
                                 ('-r' means reinstall the app, keeping its data)
                                 ('-s' means install on SD card instead of internal storage)
                                 ('--algo', '--key', and '--iv' mean the file is encrypted already)
  adb uninstall [-k] <package> - remove this app package from the device
                                 ('-k' means keep the data and cache directories)
  adb bugreport                - return all information from the device
                                 that should be included in a bug report.

  adb backup [-f <file>] [-apk|-noapk] [-shared|-noshared] [-all] [-system|-nosystem] [<packages...>]
                               - write an archive of the device's data to <file>.
                                 If no -f option is supplied then the data is written
                                 to "backup.ab" in the current directory.
                                 (-apk|-noapk enable/disable backup of the .apks themselves
                                    in the archive; the default is noapk.)
                                 (-shared|-noshared enable/disable backup of the device's
                                    shared storage / SD card contents; the default is noshared.)
                                 (-all means to back up all installed applications)
                                 (-system|-nosystem toggles whether -all automatically includes
                                    system applications; the default is to include system apps)
                                 (<packages...> is the list of applications to be backed up.  If
                                    the -all or -shared flags are passed, then the package
                                    list is optional.  Applications explicitly given on the
                                    command line will be included even if -nosystem would
                                    ordinarily cause them to be omitted.)

  adb restore <file>           - restore device contents from the <file> backup archive

  adb help                     - show this help message
  adb version                  - show version num

scripting:
  adb wait-for-device          - block until device is online
  adb start-server             - ensure that there is a server running
  adb kill-server              - kill the server if it is running
  adb get-state                - prints: offline | bootloader | device
  adb get-serialno             - prints: <serial-number>
  adb get-devpath              - prints: <device-path>
  adb status-window            - continuously print device status for a specified device
  adb remount                  - remounts the /system partition on the device read-write
  adb reboot [bootloader|recovery] - reboots the device, optionally into the bootloader or recovery program
  adb reboot-bootloader        - reboots the device into the bootloader
  adb root                     - restarts the adbd daemon with root permissions
  adb usb                      - restarts the adbd daemon listening on USB
  adb tcpip <port>             - restarts the adbd daemon listening on TCP on the specified port
networking:
  adb ppp <tty> [parameters]   - Run PPP over USB.
 Note: you should not automatically start a PPP connection.
 <tty> refers to the tty for PPP stream. Eg. dev:/dev/omap_csmi_tty1
 [parameters] - Eg. defaultroute debug dump local notty usepeerdns

adb sync notes: adb sync [ <directory> ]
  <localdir> can be interpreted in several ways:

  - If <directory> is not specified, both /system and /data partitions will be updated.

  - If it is "system" or "data", only the corresponding partition
    is updated.

environmental variables:
  ADB_TRACE                    - Print debug information. A comma separated list of the following values
                                 1 or all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp
  ANDROID_SERIAL               - The serial number to connect to. -s takes priority over this if given.
  ANDROID_LOG_TAGS             - When used with the logcat option, only these debug tags are printed.
```

**Comment by martijnwalraven** [comment]
I'm sorry, the right command is `adb devices`.

**Comment by larfadin** [comment]
List of devices attached 
006678911f12b50b	device

**Comment by martijnwalraven** [comment]
That looks fine. Have you tried running meteor run with `--verbose`?

**Comment by larfadin** [comment]
Yes, but there is nothing more with verbose.
 I've make an issue #5557 for my case

**Comment by hafizali05** [comment]
@martijnwalraven  I am sorry for the late reply as I was on leave, btw the same issue is still up... will checkout @larfadin  issue  luckily if I find a solution in there.

**Comment by sureshpersonal3020** [comment]
am getting this error

Error detecting IP address for mobile app to connect to:
Found multiple network interfaces with non-internal IPv4 addresses:
10.0.2.182, 192.168.34.1, 192.168.224.1
Please specify the address that the mobile app should connect
to with --mobile-server.

please some one help me

**Comment by hafizali05** [comment]
Same here.. I am getting the same while I have started using on windows... ubuntu as shown above worked.

**Comment by martijnwalraven** [comment]
@hafizali05: So you mean you are getting the `Found multiple network interfaces` error above? Have you tried following the instructions and used `--mobile-server` to pick the address the mobile app should connect to?

**Comment by hafizali05** [comment]
Okay can you please give an example to run? 

Like... Meteor run android-device --settings settings.json --mobile-server ...dunno what parameter to include next..

**Comment by martijnwalraven** [comment]
@hafizali05: You'll have to list the IP address you want the mobile app to connect to. So if the machine you're running `meteor` on has multiple IP addresses, pick the one that allows the device to connect. Usually that means they are on the same subnet. For example, `meteor run android-device http://192.168.34.1:3000`.

**Comment by abernix** [comment]
@hafizali05 You would put the IP address that your device would be able to communicate with your development machine on.  If you have no idea which would be best, I guess try each one or look at the IP address in your device's settings and use the one which is closest.

`meteor run android-device --settings settings.json --mobile-server 1.1.1.1`
`meteor run android-device --settings settings.json --mobile-server 2.2.2.2`
etc.

**Comment by sylarmeng** [comment]
Hi, I came across this problem yesterday. I ran meteor in  a Ubuntu guest with the VisualBox.  **## I fixed this by remove the adb1.0.31, then installed adb 1.0.32.** 

May this help you.

**Comment by michael3912** [comment]
try comment all in mobile-config.js and run the program
