### ISSUE TITLE
Error on meteor list

### ISSUE THREAD

**Issue by micaelpdias** [meteor/meteor#5625]
/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1011:11)
    at ChildProcess.spawn (child_process.js:958:11)
    at exports.spawn (child_process.js:746:9)
    at Object.exports.execFile (child_process.js:628:15)
    at Object.exports.execFileSync (/tools/utils/utils.js:526:17)
    at run (/tools/utils/archinfo.js:133:26)
    at Object.host (/tools/utils/archinfo.js:151:21)
    at ProjectContext._.extend.reset (/tools/project-context.js:77:45)
    at new ProjectContext (/tools/project-context.js:44:8)
    at Command.func (/tools/cli/commands-packages.js:1101:24)
    at /tools/cli/main.js:1378:23

**Comment by micaelpdias** [comment]
How I got here: 
1. meteor create simple-todos-react
2. meteor add react
And got this first error:
/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: Unable to allocate ArrayBuffer.
    at C_MINISAT (packages/logic-solver/minisat.js:3:1)
    at new MiniSat (packages/logic-solver/minisat_wrapper.js:19:1)
    at new Logic.Solver (packages/logic-solver/logic.js:275:1)
    at packages/constraint-solver/solver.js:613:1
    at Function.time (/tools/tool-env/profile.js:232:28)
    at [object Object].CS.Solver._getAnswer (packages/constraint-solver/solver.js:612:1)
    at packages/constraint-solver/solver.js:599:1
    at Function.time (/tools/tool-env/profile.js:232:28)
    at [object Object].CS.Solver.getAnswer (packages/constraint-solver/solver.js:598:1)
    at packages/constraint-solver/constraint-solver.js:121:1
    at Object.Logic.disablingAssertions (packages/logic-solver/logic.js:45:1)
    at Function.CS.PackagesResolver._resolveWithInput (packages/constraint-solver/constraint-solver.js:120:1)
    at [object Object].CS.PackagesResolver.resolve (packages/constraint-solver/constraint-solver.js:82:1)
    at /tools/project-context.js:497:35
    at time (/tools/tool-env/profile.js:232:28)
    at Function.run (/tools/tool-env/profile.js:377:12)
    at /tools/project-context.js:493:19
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/project-context.js:466:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._.extend._resolveConstraints (/tools/project-context.js:465:13)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/cli/commands-packages.js:1996:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:1995:27)
    at /tools/cli/main.js:1378:23

**Comment by micaelpdias** [comment]
Found it was because I ran out of memory in a $5 DO Droplet. Created a swapfile and fixed it
