### ISSUE TITLE
[bug] Production minifier unable to compile generator functions.

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5643]
I have some code using generator `function* (){}`s, which is valid syntax fine in development mode (with Chrome and Firefox, but soon Edge too), but when I run in production I get this error:

```
Your app is crashing. Here's the latest log:
Started MongoDB.
Errors prevented startup:

While minifying app code:
/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:196:18: Unexpected token operator «*», expected punc «(»
  at new JS_Parse_Error (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:196:18)
  at js_error (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:204:11)
  at croak (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:675:9)
  at token_error (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:683:9)
  at expect_token (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:696:9)
  at expect (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:699:36)
  at function_ (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:959:9)
  at expr_atom (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:1188:24)
  at maybe_unary (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:1358:19)
  at expr_ops (/app/.meteor/packages/standard-minifiers/.1.0.2.s431cs++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:1393:24)


Your application has errors. Waiting for file change.
```

**Comment by stubailo** [comment]
This is a combined effect of two issues:

1. The `ecmascript` package doesn't support generators, so doesn't transpile them to ES5
2. `uglify`, the minifier we use, [doesn't support new ES features](https://github.com/mishoo/UglifyJS2/issues/448)

It would probably be a big deal to switch the default minifier to not use uglify for this reason, but you should feel free to implement your own minifier, since the packages are now split up - you can remove just the standard JS minifier and add a custom one.

**Comment by trusktr** [comment]
@stubailo The first effect doesn't apply because I'm not using the `ecmascript` package. It's just the second thing. Is there an alternative to `uglify`, because generators should just work since they're native in 2/3 of the browsers.

**Comment by AlbinoGeek** [comment]
Here's a question for all those involved, can you use generators if you have the `es6-shim` package installed in Meteor?  Does this package properly transpile them?  @stubailo noted that es5 doesn't.

**Comment by trusktr** [comment]
@AlbinoGeek I don't think so, es6-shim doesn't compile anything, it just provides shims. It's not possible to implement generator functions as shims.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, Meteor feature requests are now being managed under the https://github.com/meteor/meteor-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/meteor/meteor-feature-requests/issues/new?title=%5Bbug%5D%20Production%20minifier%20unable%20to%20compile%20generator%20functions.&body=Migrated%20from:%20meteor/meteor%235643) to start the feature request migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
