### ISSUE TITLE
Meteor node process crashes on being attached by VS NTVS

### ISSUE THREAD

**Issue by rodrigorodriguez** [meteor/meteor#5730]
Using meteor debug, whenever the Visual Studio 2015 NTVS (https://github.com/Microsoft/nodejstools) tries to attach to the Node debugger on port 5858 the meteor node process crashes. Here is the stack:

<pre>
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write ECONNRESET
  at errnoException (net.js:905:11)
  at Socket._write (net.js:646:26)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at Socket.Writable.write (_stream_writable.js:183:11)
  at Socket.write (net.js:616:40)
  at BackloggedStreamWriter.write (C:\Users\rodriguez\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\inspector.js:246:17)
  at Array.forEach (native)
  at Function._.each._.forEach (C:\Users\rodriguez\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
  at BackloggedStreamWriter.setTarget (C:\Users\rodriguez\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\inspector.js:265:9)
  at Server.self.interceptServer.net.createServer.on.self.interceptServer (C:\Users\rodriguez\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\inspector.js:92:23)
  at Server.emit (events.js:95:17)
  at TCP.onconnection (net.js:1192:8)

<pre>

**Comment by zol** [comment]
Hey @rodrigorodriguez, This seems like a possible version compatibility issue. Please post a question in our forums at [Meteor forums](https://forums.meteor.com/) to determine if anyone has had success in connecting the Visual Studio debugger with Meteor and if so, what versions of each they used.

**Comment by rodrigorodriguez** [comment]
I have to mention that it is possible to debug pure Node v5.0.0 with no problems. 
Node used by this meteor instalation (1.2.1) is of **v0.10.40**.
Issue opened: https://forums.meteor.com/t/debugging-meteor-1-2-1-on-windows-with-visual-studio-2015-enterprise-latest-version/14208
