### ISSUE TITLE
release-1.3 branch and tapi18n

### ISSUE THREAD

**Issue by lampe** [meteor/meteor#5812]
Hey,

I'am running Meteor from checkout from the release-1.3 branch
and when i want to start my project with tapi18n i get this:

```bash
Push configuration "config.push.json", JSON Error: self is not defined
Push configuration "config.push.json", JSON Error: self is not defined
=> Errors prevented startup:                  
   
   While building the application:
   /home/micha/dev/meteor/tools/isobuild/compiler-deprecated-compile-step.js:355:25: self is not defined (compiling tap-i18n/de.i18n.json)
   at Object.compileStep.addJavaScript (/home/micha/dev/meteor/tools/isobuild/compiler-deprecated-compile-step.js:355:25)
   at compilers.i18n_json (<runJavaScript-115>:726:22)
   
   /home/micha/dev/meteor/tools/isobuild/compiler-deprecated-compile-step.js:355:25: self is not defined (compiling tap-i18n/en.i18n.json)
   at Object.compileStep.addJavaScript (/home/micha/dev/meteor/tools/isobuild/compiler-deprecated-compile-step.js:355:25)
   at compilers.i18n_json (<runJavaScript-115>:726:22)
   
   /home/micha/dev/meteor/tools/isobuild/compiler-deprecated-compile-step.js:355:25: self is not defined (compiling project-tap.i18n)
   at Object.compileStep.addJavaScript (/home/micha/dev/meteor/tools/isobuild/compiler-deprecated-compile-step.js:355:25)
   at Object.compilers.project_tap_i18n (<runJavaScript-115>:522:22)
   at __coffeescriptShare (<runJavaScript-115>:401:22)
   
   
=> Your application has errors. Waiting for file change.
```

I also posted it here:
https://github.com/TAPevents/tap-i18n/issues/130

**Comment by benjamn** [comment]
Fixed in 1.3b1: https://github.com/meteor/meteor/issues/5788#issuecomment-165935104
