### ISSUE TITLE
[1.3] npm import of some packages do not work

### ISSUE THREAD

**Issue by mcbain** [meteor/meteor#5824]
```javascript
Npm.depends({
  'yahoo-finance': '0.2.12',
  'big-js': "3.1.3"
});
```

OK: 
```javascript
import Big from 'big-js'
```

Error:
```javascript
import Y from 'yahoo-finance'
```
```javascript
ReferenceError: dirPath is not defined
  at ImportScanner._tryToResolveImportedPath (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/import-scanner.js:279:79)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/import-scanner.js:101:36
  at Array.forEach (native)
  at Function._.each._.forEach (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at ImportScanner._scanDeps (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/import-scanner.js:100:17)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/import-scanner.js:73:26
  at Array.forEach (native)
  at ImportScanner.getOutputFiles (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/import-scanner.js:71:22)
  at Object.fullLink (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/linker.js:959:34)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/compiler-plugin.js:673:28
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:361:18
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:354:34
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:352:23
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at Object.enterJob (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:326:26)
  at PackageSourceBatch._linkJS (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/compiler-plugin.js:672:18)
  at PackageSourceBatch.getResources (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/compiler-plugin.js:579:48)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:772:35
  at Array.forEach (native)
  at ClientTarget._emitResources (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:758:19)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:531:13
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:361:18
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:354:34
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:352:23
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at Object.enterJob (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:326:26)
  at ClientTarget.make (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:522:18)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2178:14
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2265:20
  at Array.forEach (native)
  at Function._.each._.forEach (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2264:7
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:273:13
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:266:29
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:264:18
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:255:23
  at [object Object]._.extend.withValue (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/fiber-helpers.js:94:14)
  at Object.capture (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/utils/buildmessage.js:254:19)
  at Object.exports.bundle (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/bundler.js:2161:31)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:594:36
  at time (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tool-env/profile.js:238:28)
  at Function.run (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/tool-env/profile.js:385:12)
  at bundleApp (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:584:34)
  at [object Object]._.extend._runOnce (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:637:35)
  at [object Object]._.extend._fiber (/data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:899:28)
  at /data/home/jzastrow/.meteor/packages/meteor-tool/.1.1.11-modules.0.oy2qvh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/runners/run-app.js:412:12
```

**Comment by stubailo** [comment]
Already fixed in this commit, will be out in the next beta: https://github.com/meteor/meteor/commit/fb73d9e3704556018310b7c873b4e7a95fac807c
