### ISSUE TITLE
[1.3-beta1] issue when add 'kadira:flow-router'

### ISSUE THREAD

**Issue by bySabi** [meteor/meteor#5832]
A clean project with added `kadira:flow-router@2.10.0`package, output this error on build.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module 'qs' from '/Users/flx/.meteor/packages/kadira_flow-router/.2.10.0.nzapae++os+web.browser+web.cordova/npm'
    at /Users/flx/.meteor/packages/cosmos_browserify/.0.9.2.1q73moc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/flx/.meteor/packages/cosmos_browserify/.0.9.2.1q73moc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/flx/.meteor/packages/cosmos_browserify/.0.9.2.1q73moc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/flx/.meteor/packages/cosmos_browserify/.0.9.2.1q73moc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/flx/.meteor/packages/cosmos_browserify/.0.9.2.1q73moc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/flx/.meteor/packages/cosmos_browserify/.0.9.2.1q73moc++os+web.browser+web.cordova/plugin.CosmosBrowserify.os/npm/CosmosBrowserify/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)
```

~~it seens a problem with `browserify` package.~~

**Comment by bySabi** [comment]
A workaround is:

```
> mkdir node_modules
> npm install qs
```

**Comment by bySabi** [comment]
Solved! removing `~/.meteor` and `~/.npm*` folders
