### ISSUE TITLE
[Windows] Setting PACKAGE_DIRS results in build error

### ISSUE THREAD

**Issue by fabyeah** [meteor/meteor#5851]
I set **PACKAGE_DIRS** to ```..\packages```. When i run ```meteor``` I now get this error:

```
C:\Users\Fabian\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Builder can not write without either data or a file path or a symlink path: os/packages.json
    at Builder.write (C:\tools\isobuild\builder.js:225:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:353:10)
    at C:\tools\isobuild\isopack.js:1346:27
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Fabian\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at _.each._.each.builder.generateFilename.directory (C:\tools\isobuild\isopack.js:1320:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Fabian\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1233:9
    at [object Object]._.extend.saveToPath (C:\tools\isobuild\isopack.js:1585:26)
    at C:\tools\isobuild\isopack-cache.js:289:23
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:227:18)
    at C:\tools\isobuild\isopack-cache.js:166:14
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:158:20)
    at ensureLoaded (C:\tools\isobuild\isopack-cache.js:133:12)
    at C:\tools\isobuild\isopack-cache.js:160:11
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Fabian\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack-cache.js:159:11
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:158:20)
    at ensureLoaded (C:\tools\isobuild\isopack-cache.js:133:12)
    at C:\tools\isobuild\isopack-cache.js:160:11
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Fabian\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack-cache.js:159:11
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:158:20)
    at C:\tools\isobuild\isopack-cache.js:73:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\Fabian\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at [object Object]._.extend.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:72:24)
    at C:\tools\project-context.js:735:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:734:18)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.js:240:10)
    at C:\tools\runners\run-app.js:517:29
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at bundleApp (C:\tools\runners\run-app.js:516:31)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:594:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:858:28)
    at C:\tools\runners\run-app.js:396:12
```

I'm on Windows. The path to the package folder seems to be correct, because when I use any other (wrong) path, it will say ```Unknown package [...]```

**Comment by fabyeah** [comment]
Solved it by setting a permanent environment variable it through the windows environment variable GUI, instead of setting a temporary env variable via CLI. There seem to be some problem with the latter.

**Comment by isdzulqor** [comment]
@fabyeah can you elaborate it? I have the same problem when I want to build my app

**Comment by fabyeah** [comment]
@isdzulqor go to Control Panel > System and Security > System, click "Advanced System settings", click "Advanced" Tab, click "Environment Variables...", create new user variable "PACKAGE_DIRS" with the appropriate value for your case.

**Comment by SimonVuong** [comment]
getting the same problem on mac. could you explain why this is happening? does meteor not see where my smart packages are? is it a webstorm issue? how do we know where the proper location is? what even is the location describing? is it the location of my packages folder?

**Comment by Chandranadmin** [comment]
@fabyeah Can you please let me know, what appropriate value needs to set in new user variable "PACKAGE_DIRS". I am also facing the same error, when I run app with meteor. 
![meteor-error](https://cloud.githubusercontent.com/assets/9997132/12507729/96851b30-c11d-11e5-8cc5-d4844f3a152e.png)

**Comment by fabyeah** [comment]
@Chandranadmin you only need to set it, if you use packages that are located somewhere else than in your projects package folder. If so, you can set the variable to the relative path to that package folder, as seen from your project folder. Don't know if global paths work as well, haven't tried.
