### ISSUE TITLE
Match.

### ISSUE THREAD

**Issue by AbhinavMadahar** [meteor/meteor#5853]
I defined a Collection in another file using `Clubs = new Mongo.Collection("Clubs");` and, in another file, wrote:

```javascript
Meteor.startup(function() {
  Clubs.find({}, (error, clubs) => console.log(clubs));
});
```

However, this ended up throwing the error:

```bash
W20151221-00:28:23.633(-5)? (STDERR)          
W20151221-00:28:23.634(-5)? (STDERR) /home/abhinav/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151221-00:28:23.634(-5)? (STDERR) 						throw(ex);
W20151221-00:28:23.634(-5)? (STDERR) 						      ^
W20151221-00:28:23.687(-5)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation
W20151221-00:28:23.687(-5)? (STDERR)     at check (packages/check/match.js:33:1)
W20151221-00:28:23.687(-5)? (STDERR)     at [object Object]._.extend._getFindOptions (packages/mongo/collection.js:248:1)
W20151221-00:28:23.687(-5)? (STDERR)     at [object Object]._.extend.find (packages/mongo/collection.js:284:1)
W20151221-00:28:23.687(-5)? (STDERR)     at server/bootstrap.js:3:8
W20151221-00:28:23.687(-5)? (STDERR)     at /home/abhinav/Documents/personal/Millburn-Clubs/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8

```

Using the `meteor mongo` shell, everything works perfectly fine and it can read the data. However, from Meteor itself it throws this error on both the server and client, even if the database is completely empty.

**Comment by sebakerckhof** [comment]
http://docs.meteor.com/#/full/find

**Comment by AbhinavMadahar** [comment]
Well I feel like an idiot. Thanks for that. This works:

```javascript
const clubs = Clubs.find({});
```

**Comment by tmeasday** [comment]
Glad you worked it out.
