### ISSUE TITLE
meteor create <app> : Error: ENOENT, stat 'CHANGELOG.md'

### ISSUE THREAD

**Issue by josh--newman** [meteor/meteor#5861]
With a fresh install of meteor, trying to create a new app throws the following error. Running with `sudo` doesn't help. Running OSX 10.11

```
/Users/josh/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: ENOENT, stat 'CHANGELOG.md'
    at Object.Future.wait (/Users/josh/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as stat] (/tools/fs/files.js:1334:20)
    at thisPathCountsAsAFile (/tools/cli/commands.js:630:25)
    at Array.some (native)
    at Function._.some._.any (/Users/josh/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:207:59)
    at Command.buildCommands.minArgs [as func] (/tools/cli/commands.js:616:33)
    at /tools/cli/main.js:1378:23
    - - - - -
```

**Comment by zol** [comment]
This is most likely something odd about your system. Please try (and post the full shell output) the following commands:

```
cd /tmp
mkdir empty_dir
cd empty_dir
meteor create hello_world
```

**Comment by sicum** [comment]
this is my error:

/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: ENOENT, stat '/Users/erickgaillard/Developer/skip/.meteor/local/cordova-build/platforms/ios/DerivedData/skip/Build/Intermediates/ArchiveIntermediates/skip/BuildProductsPath/Release-iphoneos/skip.app'
  at Object.Future.wait (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1293:28
  at Object.wrapper [as stat] (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1297:11)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:441:74
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:443:13
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:443:13
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:443:13
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:443:13
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:443:13
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:443:13
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:443:13
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:443:13
  at Array.forEach (native)
  at Function._.each._.forEach (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
  at Object.files.cp_r (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:433:5)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:903:19
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:352:18
  at [object Object]._.extend.withValue (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:345:34
  at [object Object]._.extend.withValue (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:343:23
  at [object Object]._.extend.withValue (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at Object.enterJob (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:317:26)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:895:24
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:264:13
  at [object Object]._.extend.withValue (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:257:29
  at [object Object]._.extend.withValue (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:255:18
  at [object Object]._.extend.withValue (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:246:23
  at [object Object]._.extend.withValue (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:116:14)
  at Object.capture (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:245:19)
  at Object.main.captureAndExit (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/main.js:257:29)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:874:12
  at buildCommand (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:919:7)
  at Command.main.registerCommand._.extend.name [as func] (/private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/commands.js:728:10)
  at /private/var/root/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cli/main.js:1227:23

    - - - - -
