### ISSUE TITLE
[bug] fibers worker error: the buildmessages.js can not catch this file error.

### ISSUE THREAD

**Issue by snowyu** [meteor/meteor#5917]
reproduce it:

* meteor add civilframe:angular-jade

test.ng.jade:
```jade
div(,,)
```

and `meteor run` , It's just report this instead of "the 'test.ng.jade' file compile error": 

```bash
\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
TypeError: Cannot call method 'split' of undefined
  at Object.parse (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\parse-stack.js:24:26)
  at Object.exception (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\buildmessage.js:481:29)
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler.js:561:20
  at Array.forEach (native)
  at compileUnibuild (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler.js:447:21)
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler.js:170:26
  at Array.forEach (native)
  at Function._.each._.forEach (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
  at Object.compile (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler.js:167:5)
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\bundler.js:2119:24
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\buildmessage.js:264:13
  at [object Object]._.extend.withValue (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:116:14)
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\buildmessage.js:257:29
  at [object Object]._.extend.withValue (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:116:14)
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\buildmessage.js:255:18
  at [object Object]._.extend.withValue (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:116:14)
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\buildmessage.js:246:23
  at [object Object]._.extend.withValue (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:116:14)
  at Object.capture (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\utils\buildmessage.js:245:19)
  at Object.exports.bundle (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\bundler.js:2070:31)
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\runners\run-app.js:537:36
  at time (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\tool-env\profile.js:226:28)
  at Function.run (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\tool-env\profile.js:361:12)
  at bundleApp (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\runners\run-app.js:527:34)
  at [object Object]._.extend._runOnce (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\runners\run-app.js:580:35)
  at [object Object]._.extend._fiber (~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\runners\run-app.js:845:28)
  at ~\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\runners\run-app.js:385:12

```

**Comment by zol** [comment]
Please work through your issue with the author of the civilframe:angular-jade package.

**Comment by snowyu** [comment]
I do not think so. It's just a workaround. The meteor should catch all errors from any plugins..
Can you ensure each plugin DO NOT raise exception? And such error will make everyone confused.
It seems that the meteor can not work.  So, please let the meteor try to catch error from the plugins.
