### ISSUE TITLE
[1.3-modules-beta.2] Error in NPM packages with Shebangs

### ISSUE THREAD

**Issue by TimFletcher** [meteor/meteor#5931]
It's not possible to install the [JSONStream](https://www.npmjs.com/package/JSONStream) NPM module due to a shebang which is invalid syntax when combined into `app.js`.

[More detail](https://forums.meteor.com/t/1-3-beta-not-handling-npm-packages-with-shebangs/15735) on the forum.

**Error thrown (on the server)**

```
/Users/tim/Desktop/meteor-1.3-possible-npm-bug/.meteor/local/build/programs/server/app/app.js:52
#! /usr/bin/env node                                                          
^
SyntaxError: Unexpected token ILLEGAL
    at /Users/tim/Desktop/meteor-1.3-possible-npm-bug/.meteor/local/build/programs/server/boot.js:241:30
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/tim/.meteor/packages/meteor-tool/.1.1.11-modules.3.1rpyovf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/tim/Desktop/meteor-1.3-possible-npm-bug/.meteor/local/build/programs/server/boot.js:137:5
```

**Steps to Reproduce**

```
git clone git@github.com:TimFletcher/meteor-1.3-possible-npm-bug.git
cd meteor-1.3-possible-npm-bug/
npm install
meteor
```

I'm using OS X 10.10.5

**Comment by benjamn** [comment]
Definitely a bug! Thanks for reporting.

**Comment by abernix** [comment]
This should be fixed.  Thanks for reporting it!

Be sure to upgrade to a newer version – at least 1.3.5.1 or even better, 1.4.2.3. :)
