### ISSUE TITLE
Errors executing Cordova commands: 

### ISSUE THREAD

**Issue by vithanidarpan** [meteor/meteor#5942]
$ meteor run android
[[[[[ ~/Desktop/MeteorProjects/demo ]]]]]     

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                                                            
                                              
=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --emulator:
   Error: Command failed:                     
   /home/ibl/Desktop/MeteorProjects/demo/.meteor/local/cordova-build/platforms/android/cordova/run
   --emulator

   /home/ibl/Desktop/MeteorProjects/demo/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
   throw e;
   ^
   Error code 1 for command:
   /home/ibl/Desktop/MeteorProjects/demo/.meteor/local/cordova-build/platforms/android/gradlew
   with args:
   cdvBuildDebug,-b,/home/ibl/Desktop/MeteorProjects/demo/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
   at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1

I have also tried to solve using https://github.com/meteor/meteor/issues/5336 link but not worked for me.

**Comment by vithanidarpan** [comment]
I got actual error using --verbose command. It was java_home variable error and also New Meteor runs on API 22 so I have create emulator in API 22.
