### ISSUE TITLE
Unable to publish package on Atmosphere for Meteor 1.3-beta.3

### ISSUE THREAD

**Issue by trusktr** [meteor/meteor#5961]
I'm getting messages like this:

```
 ❯ meteor publish                                                           [01:14:38]
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint ecmascript@0.3.1-modules.3 is not satisfied by ecmascript
0.1.6.
Constraints on package "ecmascript":
* ecmascript@=0.1.6 <- top level
* ecmascript@0.3.1-modules.3 <- rocket:module 0.16.0
* ecmascript@0.1.6 <- random 1.0.5 <- ddp-client 1.2.1 <- ddp 1.2.2 <- mongo 1.1.3 <- tinytest 1.0.6 <- local-test:rocket:module 0.16.0
* ecmascript@0.1.6 <- random 1.0.5 <- ddp-client 1.2.1 <- ddp 1.2.2 <- tinytest 1.0.6 <- local-test:rocket:module 0.16.0
* ecmascript@0.1.6 <- random 1.0.5 <- mongo 1.1.3 <- tinytest 1.0.6 <- local-test:rocket:module 0.16.0
* ecmascript@0.1.6 <- random 1.0.5 <- tinytest 1.0.6 <- local-test:rocket:module 0.16.0
* ecmascript@0.1.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- mongo 1.1.3 <- tinytest 1.0.6 <- local-test:rocket:module 0.16.0
* ecmascript@0.1.6 <- ddp-server 1.2.2 <- ddp 1.2.2 <- tinytest 1.0.6 <- local-test:rocket:module 0.16.0
```

My `package.js` looks like this:

```js
Package.describe({
    name: 'rocket:module',
    version: '0.16.0',
    summary: 'ES6/CJS/AMD modules and cross-package NPM dependencies.',
    git: 'https://github.com/meteor-rocket/module.git',
    documentation: 'README.md'
})

Package.registerBuildPlugin({
    name: 'rocket:module',
    use: [
        'meteor',
        'rocket:webpack@1.12.3',
        'rocket:build-tools@2.1.4',
        'ecmascript@0.3.1-modules.3'
    ],

    //sources: ['hello'],
    sources: ['plugin/plugin.js'],
    npmDependencies: {
        'lodash': '3.8.0',
        //'glob': '5.0.5',
        //'fs-extra': '0.18.4',
        //'async': '1.2.0',
        'regexr': '1.1.1',
        'mkdirp': '0.5.1',
        'npm': '3.2.0',
        'shelljs': '0.5.1',
    }
})

Package.onUse(function(api) {
    api.versionsFrom('1.3-modules-beta.3');

    // needed if using Plugin.registerCompiler.
    api.use('isobuild:compiler-plugin@1.0.0');

    api.addFiles('npm.json')
    api.addFiles('shared-modules.js')

    api.export('RocketModule')
})

Package.onTest(function(api) {
    api.use('tinytest')
    api.use('rocket:module')
    api.addFiles('module-tests.js')
})
```

What might I be missing?

**Comment by nathan-muir** [comment]
@trusktr It might be because `meteor publish` just uses the latest non/beta version of meteor, have you tried specifying the release like:

```sh
meteor publish --release METEOR@1.3-modules-beta.4
```

**Comment by trusktr** [comment]
@nathan-muir That seems to have been it, but I get an error:

```
 ❯ meteor publish --release METEOR@1.3-modules-beta.3                                                                                                               [22:03:39]

TypeError: Cannot call method 'toString' of undefined
    at uploadFile (/tools/packaging/package-client.js:330:66)
    at /tools/packaging/package-client.js:418:5
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at publishBuiltPackage (/tools/packaging/package-client.js:417:16)
    at Object.exports.publishPackage (/tools/packaging/package-client.js:829:7)
    at /tools/cli/commands-packages.js:438:21
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:276:29)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:434:8)
    at /tools/cli/main.js:1407:23

 ❯ meteor publish --release METEOR@1.3-modules-beta.3                                                                                                               [22:14:00]
=> Errors while publishing:

While pre-publishing package rocket:module:
error: Version already exists

```

You can see I tried it again after the error, and it says the package exists. When I try to use the version, it doesn't work:

```
 ❯ meteor add rocket:module                                                                                                                                         [22:23:34]
 => Errors while adding packages:

While checking for rocket:module@0.16.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

Do you know if there's some way to publish the missing parts?

**Comment by trusktr** [comment]
Oh well, I'm abandoning the project anyways, in light of Meteor 1.3 (`rocket:module` was a temporary module solution), so it's really not that important. I'll close and just leave it as is. Thanks for the tip!
