### ISSUE TITLE
Spiderable fails without error message

### ISSUE THREAD

**Issue by Firfi** [meteor/meteor#5976]
Hey,

I asked this question half a year ago in SO but it seems had no luck. It is still actual: http://stackoverflow.com/questions/31459362/meteor-spiderable-failing-with-no-reason-in-error

```

I have phantomjs installed from binaries and working, accessible through $PATH and MeteorJS latest version with Spiderable latest version.

I use package flow-router for routing and flow-layout for rendering.

I have all my publishers either returning cursors (through find method) or returning this.ready(), through I don't have any subscribe() on page which I test nether in page template code, routes code nor layout template code.

I have Meteor set up locally (with meteor command for run) and websockets working.

When I visit the page, I see phantomjs process running on background, with ps aux

After awhile I get this error in meteor server console:

spiderable: phantomjs failed: Error: Command failed:
at ChildProcess.exithandler (child_process.js:658:15)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:766:16)
at Process.ChildProcess._handle.onexit (child_process.js:833:5)
stderr:
That's all; no stderr. It looks like there's non-ready subscriptions but I checked this thing thrice.

Any suggestions?
```

**Comment by timbotnik** [comment]
Yes usually we would hope these types of questions to be answered on SO but sorry to hear you haven't had any luck over there.  

In any event, we are moving towards a new mechanism for doing SEO / server rendered functionality as described in the [Meteor Guide here](http://guide.meteor.com/deployment.html#seo), which may help you get around this issue.
