### ISSUE TITLE
Mongo DB NPM.depends error

### ISSUE THREAD

**Issue by DClark5218** [meteor/meteor#5979]
Started a brand new meteor project today duplicating the simple-todos-react example.

I am getting the stack trace error on startup:
```
/Users/MyComputerName/Apps/simple-todos-react/.meteor/local/build/programs/server/boot.js:283
W20160112-13:13:28.833(-5)? (STDERR) }).run();
W20160112-13:13:28.834(-5)? (STDERR)    ^
W20160112-13:13:28.837(-5)? (STDERR) Error: Can't find npm module 'mongodb'. Did you forget to call 'Npm.depends' in package.js within the 'npm-mongo' package?
W20160112-13:13:28.837(-5)? (STDERR)     at Object.Npm.require (/Users/MyComputerName/Apps/simple-todos-react/.meteor/local/build/programs/server/boot.js:175:17)
W20160112-13:13:28.838(-5)? (STDERR)     at Package (packages/npm-mongo/packages/npm-mongo.js:9:1)
W20160112-13:13:28.838(-5)? (STDERR)     at Package (packages/npm-mongo/packages/npm-mongo.js:14:1)
W20160112-13:13:28.838(-5)? (STDERR)     at /Users/MyComputerName/Apps/simple-todos-react/.meteor/local/build/programs/server/packages/npm-mongo.js:34:4
W20160112-13:13:28.838(-5)? (STDERR)     at /Users/MyComputerName/Apps/simple-todos-react/.meteor/local/build/programs/server/packages/npm-mongo.js:44:3
W20160112-13:13:28.838(-5)? (STDERR)     at /Users/MyComputerName/Apps/simple-todos-react/.meteor/local/build/programs/server/boot.js:242:10
W20160112-13:13:28.838(-5)? (STDERR)     at Array.forEach (native)
W20160112-13:13:28.839(-5)? (STDERR)     at Function._.each._.forEach (/Users/DanielClark/.meteor/packages/meteor-tool/.1.1.10.9rlu9k++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160112-13:13:28.839(-5)? (STDERR)     at /Users/MyComputerName/Apps/simple-todos-react/.meteor/local/build/programs/server/boot.js:137:5
```

Can anyone replicate this error?

**Comment by DClark5218** [comment]
Update - Seems to be effecting all my existing apps on my computer above, but when downloaded and tested on another computer everything works OK.

Is there a reason things are no longer working on my laptop?

Thanks!

**Comment by DClark5218** [comment]
Found and fixed with help from:
https://github.com/meteor/meteor/issues/3432
Looks like system links changed for some reason.

Thanks everyone ;)
