### ISSUE TITLE
[1.2.2-faster-rebuilds.0] Node process locking directory / hanging / blocking

### ISSUE THREAD

**Issue by reel** [meteor/meteor#5993]
Using 1.2.2-faster-rebuilds.0, on Windows, when triggering the second rebuild after a change, the meteor process exit with the following trace.

I see the node.exe process still running and using the C:\Users\Felix\code\site-dot-com\.meteor\local\build\programs\server ressource and I am not able to kill it nor remove the folder manually.

The only solution is to reboot.

```
C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245                                  
                                                throw(ex);                                                                                                                               
                                                      ^                                                                                                                                  
Error: EBUSY, rmdir 'C:\Users\Felix\code\site-dot-com\.meteor\local\build\programs\server'                                                                                     
  at Object.Future.wait (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)     
  at Object.rm_recursive (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\fs\files.js:260:9)                                
  at Object.files.rename (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\fs\files.js:1373:13)                              
  at Object.files.renameDirAlmostAtomically (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\fs\files.js:785:11)            
  at Builder.complete (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\isobuild\builder.js:606:30)                          
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\isobuild\bundler.js:1935:15                                            
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\isobuild\bundler.js:1955:7                                             
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\isobuild\bundler.js:2218:22                                            
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\buildmessage.js:264:13                                           
  at [object Object]._.extend.withValue (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:116:14)     
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\buildmessage.js:257:29                                           
  at [object Object]._.extend.withValue (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:116:14)     
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\buildmessage.js:255:18                                           
  at [object Object]._.extend.withValue (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:116:14)     
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\buildmessage.js:246:23                                           
  at [object Object]._.extend.withValue (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:116:14)     
  at Object.capture (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\utils\buildmessage.js:245:19)                          
  at Object.exports.bundle (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\isobuild\bundler.js:2070:31)                    
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\runners\run-app.js:537:36                                              
  at time (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\tool-env\profile.js:226:28)                                      
  at Function.run (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\tool-env\profile.js:361:12)                              
  at bundleApp (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\runners\run-app.js:527:34)                                  
  at [object Object]._.extend._runOnce (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\runners\run-app.js:580:35)          
  at [object Object]._.extend._fiber (C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\runners\run-app.js:845:28)            
  at C:\Users\Felix\AppData\Local\.meteor\packages\meteor-tool\1.1.11-faster-rebuild.0\mt-os.windows.x86_32\tools\runners\run-app.js:385:12

**Comment by avital** [comment]
To clarify, this happens to you every time when you app rebuilds a second time?

Does this also happen on a small app?

**Comment by reel** [comment]
I have been using 1.3-modules-beta.4 since then and I don't have any problems. 

Reverted back to this release and still no problem. I updated Windows in the meantime (maybe?)... 

Will comment if it occurs again.

Thank you

**Comment by jonathascarrijo** [comment]
Same problem here, but it happens very occasionally.

**Comment by neil-s** [comment]
Same problem. 
I'm using the stable Meteor 1.2.1, on Windows 10. The project was working fine, until I added aldeed:collection2, yogiben:admin, created a schema for my 1 collection, and attempted to `mongo reset`
