### ISSUE TITLE
The `findImportedModuleIdentifiers` function should print more useful errors when parsing fails

### ISSUE THREAD

**Issue by timothyarmes** [meteor/meteor#6009]
Hi,

I successfully updated my project to use beta 4 of Meteor 1.3. I then converted one of my packages (I'm using a package based approach) to use modules.

When compiling I get this error:

```
SyntaxError: Unexpected token (5:20)
    at Parser.pp.raise (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseExportFrom (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/parser/statement.js:737:12)
    at Parser.pp.parseExport (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/parser/statement.js:678:10)
    at Parser.parseExport (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/plugins/flow.js:679:20)
    at Parser.pp.parseStatement (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/parser/statement.js:115:90)
    at Parser.parseStatement (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/plugins/flow.js:621:22)
    at Parser.pp.parseTopLevel (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babylon/lib/index.js:45:50)
    at Object.parse (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/node_modules/babel-core/lib/api/node.js:160:21)
    at Object.parse (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-babel/index.js:12:32)
    at tryToParse (/tools/isobuild/js-analyze.js:7:12)
    at Object.findImportedModuleIdentifiers (/tools/isobuild/js-analyze.js:52:15)
    at ImportScanner._scanDeps (/tools/isobuild/import-scanner.js:114:23)
    at /tools/isobuild/import-scanner.js:177:27
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Tim/.meteor/packages/meteor-tool/.1.1.11-modules.5.xkk0yv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at ImportScanner._scanDeps (/tools/isobuild/import-scanner.js:116:5)
    at /tools/isobuild/import-scanner.js:82:26
    at Array.forEach (native)
    at ImportScanner.getOutputFiles (/tools/isobuild/import-scanner.js:79:22)
    at PackageSourceBatch._linkJS (/tools/isobuild/compiler-plugin.js:615:10)
    at PackageSourceBatch.getResources (/tools/isobuild/compiler-plugin.js:590:48)
    at /tools/isobuild/bundler.js:753:37
    at Array.forEach (native)
    at ServerTarget._emitResources (/tools/isobuild/bundler.js:736:19)
    at /tools/isobuild/bundler.js:515:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ServerTarget.make (/tools/isobuild/bundler.js:506:18)
    at /tools/isobuild/bundler.js:2227:14
    at /tools/isobuild/bundler.js:2295:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2180:31)
    at /tools/runners/run-app.js:585:36
    at time (/tools/tool-env/profile.js:238:28)
    at Function.run (/tools/tool-env/profile.js:391:12)
    at bundleApp (/tools/runners/run-app.js:575:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:628:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:402:12
```

In case it's useful I've attached the [versions](https://github.com/meteor/meteor/files/91669/versions.txt) file.

I wouldn't know how to event start trying to create a reproduction of this bug since there are no clues at all in the trace.

**Comment by timothyarmes** [comment]
Ah, I've found the issue thanks to my linter I done this:

```
export generateQuery(userId, options) { ... }
```

instead of this:

```
export function generateQuery(userId, options) { ... }
```

I proper error message would have been nice, so I'll leave this issue open :)

**Comment by benjamn** [comment]
Yep, `findImportedModuleIdentifiers` should definitely display more helpful errors when parsing fails.

**Comment by avital** [comment]
Copying @stubailo's repro from #5934:
> The syntax error is in this file: https://github.com/stubailo/repro-export-default-const/blob/master/imports/repro.js
>
> Try running the app and you will see a scary stack trace."

**Comment by trusktr** [comment]
It took me *foreeeeeveeeer* to find a syntax error just now. I hope this can be fixed soon!
