### ISSUE TITLE
[1.3 beta 5] ReferenceError: AccountsUIWrapper is not defined

### ISSUE THREAD

**Issue by laurentpayot** [meteor/meteor#6072]
Installing the simple todos app:
```
meteor create --example simple-todos-react
cd simple-todos-react/
meteor update --release 1.3-modules-beta.5
meteor update
```
When I launch meteor I get:
```
$ meteor
[[[[[ ~/meteor/debug/simple-todos-react ]]]]] 

=> Started proxy.                             
=> Started MongoDB.                           
W20160124-21:07:33.053(1)? (STDERR)           
W20160124-21:07:33.055(1)? (STDERR) /home/laurent/.meteor/packages/meteor-tool/.1.1.12-modules.5.1ekxrws++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160124-21:07:33.055(1)? (STDERR) 						throw(ex);
W20160124-21:07:33.055(1)? (STDERR) 						      ^
W20160124-21:07:33.055(1)? (STDERR) ReferenceError: AccountsUIWrapper is not defined
W20160124-21:07:33.055(1)? (STDERR)     at meteorInstall.AccountsUIWrapper.jsx (AccountsUIWrapper.jsx:1:1)
W20160124-21:07:33.055(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:183:1)
W20160124-21:07:33.055(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160124-21:07:33.055(1)? (STDERR)     at /home/laurent/meteor/debug/simple-todos-react/.meteor/local/build/programs/server/app/app.js:359:1
W20160124-21:07:33.055(1)? (STDERR)     at /home/laurent/meteor/debug/simple-todos-react/.meteor/local/build/programs/server/boot.js:242:10
W20160124-21:07:33.055(1)? (STDERR)     at Array.forEach (native)
W20160124-21:07:33.055(1)? (STDERR)     at Function._.each._.forEach (/home/laurent/.meteor/packages/meteor-tool/.1.1.12-modules.5.1ekxrws++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160124-21:07:33.056(1)? (STDERR)     at /home/laurent/meteor/debug/simple-todos-react/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

**Comment by huttonr** [comment]
Running into the same issue here.  https://github.com/meteor/meteor/issues/6074

#### Reproduction
https://github.com/huttonr/meteor-global-variable-error

**Comment by gbersani** [comment]
+1
Global variables seem to be causing issues on this version of the beta. Reverting to 1.3 beta 4 seems to have take care of the problem in the meantime.

**Comment by huttonr** [comment]
Can be temporarily solved by adding a `global.` prefix however it is very definitely still a bug.

**Comment by vjau** [comment]
Even node globals are not available, you have to use global.Date instead of Date

**Comment by benjamn** [comment]
The specific commit that should fix this is https://github.com/meteor/babel-preset-meteor/commit/57316d6bab33f4888d1e4aca0feb508a0e5d2b8b.
