### ISSUE TITLE
1.3-modules-beta.5: TypeError: Cannot set property 'getPropertyValue' of undefined

### ISSUE THREAD

**Issue by ljack** [meteor/meteor#6075]
trying to start meteor after running "meteor update --release 1.3-modules-beta.5  "
```
=> Started proxy.                             
=> Started MongoDB.                           
W20160125-10:54:55.908(0)? (STDERR)           
W20160125-10:54:55.916(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.1.12-modules.5.a45895++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160125-10:54:55.917(0)? (STDERR)                                             throw(ex);
W20160125-10:54:55.917(0)? (STDERR)                                                   ^
W20160125-10:54:55.918(0)? (STDERR) TypeError: Cannot set property 'getPropertyValue' of undefined
W20160125-10:54:55.918(0)? (STDERR)     at meteorInstall.lib.object_utils.js (lib/object_utils.js:9:1)
W20160125-10:54:55.918(0)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:183:1)
W20160125-10:54:55.918(0)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160125-10:54:55.918(0)? (STDERR)     at /home/ubuntu/workspace/PITPA/.meteor/local/build/programs/server/app/app.js:1661:1
W20160125-10:54:55.919(0)? (STDERR)     at /home/ubuntu/workspace/PITPA/.meteor/local/build/programs/server/boot.js:242:10
W20160125-10:54:55.920(0)? (STDERR)     at Array.forEach (native)
W20160125-10:54:55.920(0)? (STDERR)     at Function._.each._.forEach (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.12-modules.5.a45895++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160125-10:54:55.920(0)? (STDERR)     at /home/ubuntu/workspace/PITPA/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8  
```
Ah, didn't understand the error message right away. It's a problem with some js in my project:
object_utils.js:
```javascript
/*
   Returns property value, where property name is given as path.

   Example:

       getPropertyValue("x.y.z", {x: { y: { z: 123}}});
*/

this.getPropertyValue = function(propertyName, obj) {
	return propertyName.split('.').reduce(function(o, i) { return o[i]; }, obj);	
};
```

**Comment by ljack** [comment]
So the correct fix is to replace this. with ```const``` or with ```export const```? Still trying to figure out how modules fit in this scenario ;)

**Comment by avital** [comment]
`this` at the top-level of a file is probably not what you want to set `getPropertyValue` on. What did you expect `this` to evaluate to?

**Comment by avital** [comment]
(I don't think this has much to do with modules, maybe other than the fact that in non-module code in Meteor `this` references `global`)

**Comment by ljack** [comment]
Hi,   thanks for the comments. 
 Yes, ```this``` at top level was used for some other reason (had something to do with js->coffeescript transformation).  Closing this as this seems to be issue on some other code.
