### ISSUE TITLE
Project auto rebuild on files changes conflicts with external MONGO_URL 

### ISSUE THREAD

**Issue by Firfi** [meteor/meteor#6082]
Hey,

looks like it's making auto rebuild not useful as _the_ only way to recover from this error is ctrl+c meteor dev server and run it again. I have mongo instance outside on our staging server and MONGO_URL pointed to it. I have oplog enabled. ~80% times when I'm getting project auto refresh, I get

```
=> Client modified -- refreshing
I20160126-03:51:11.344(3)? Exception while invoking method 'login' Error: failed to connect to [MY STAGING URL HERE!:27017]
I20160126-03:51:11.344(3)?     at Object.Future.wait (/Users/firfi/.meteor/packages/meteor-tool/.1.1.10.selhsd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20160126-03:51:11.344(3)?     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:986:1)
I20160126-03:51:11.344(3)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1020:1)
I20160126-03:51:11.345(3)?     at [object Object]._.extend.map (packages/mongo/mongo_driver.js:1030:1)
I20160126-03:51:11.345(3)?     at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:1054:1)
I20160126-03:51:11.345(3)?     at [object Object].Cursor.(anonymous function) (packages/mongo/mongo_driver.js:869:1)
I20160126-03:51:11.345(3)?     at [object Object].cursorProto.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/db.js:126:1)
I20160126-03:51:11.345(3)?     at [object Object].kadira_Cursor_fetch [as fetch] (packages/meteorhacks_kadira/lib/hijack/set_labels.js:75:1)
I20160126-03:51:11.346(3)?     at [object Object].MongoConnection.findOne (packages/mongo/mongo_driver.js:776:1)
I20160126-03:51:11.346(3)?     at Object.Collection (packages/matb33_collection-hooks/findone.js:27:1)
I20160126-03:51:11.346(3)?     at Object.collection.(anonymous function) [as findOne] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
I20160126-03:51:11.346(3)?     at [object Object]._.extend.findOne (packages/mongo/collection.js:305:1)
I20160126-03:51:11.346(3)?     at [object Object].defaultResumeLoginHandler (accounts_server.js:971:29)
I20160126-03:51:11.346(3)?     at [object Object].<anonymous> (accounts_server.js:955:38)
I20160126-03:51:11.347(3)?     at accounts_server.js:462:32
I20160126-03:51:11.347(3)?     at tryLoginMethod (accounts_server.js:239:14)
I20160126-03:51:11.347(3)?     - - - - -
I20160126-03:51:11.347(3)?     at [object Object].<anonymous> (/Users/firfi/.meteor/packages/npm-mongo/.1.4.39_1.176uc2o++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
I20160126-03:51:11.347(3)?     at [object Object].emit (events.js:106:17)
I20160126-03:51:11.348(3)?     at [object Object].<anonymous> (/Users/firfi/.meteor/packages/npm-mongo/.1.4.39_1.176uc2o++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
I20160126-03:51:11.348(3)?     at [object Object].emit (events.js:98:17)
I20160126-03:51:11.348(3)?     at Socket.<anonymous> (/Users/firfi/.meteor/packages/npm-mongo/.1.4.39_1.176uc2o++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
I20160126-03:51:11.348(3)?     at Socket.emit (events.js:95:17)
I20160126-03:51:11.348(3)?     at net.js:441:14
I20160126-03:51:11.349(3)?     at process._tickDomainCallback (node.js:492:13)
I20160126-03:51:11.476(3)? Exception while polling query {"collectionName":"meteor_accounts_loginServiceConfiguration","selector":{},"options":{"transform":null,"fields":{"secret":0}}}: Error: No replica set primary available for query with ReadPreference PRIMARY
I20160126-03:51:11.476(3)?     at Object.Future.wait (/Users/firfi/.meteor/packages/meteor-tool/.1.1.10.selhsd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
I20160126-03:51:11.477(3)?     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:986:1)
I20160126-03:51:11.477(3)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1020:1)
I20160126-03:51:11.477(3)?     at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:1069:1)
I20160126-03:51:11.477(3)?     at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:147:1)
I20160126-03:51:11.477(3)?     at [object Object].proto._pollMongo (packages/meteorhacks_kadira/lib/hijack/wrap_observers.js:63:1)
I20160126-03:51:11.477(3)?     at Object.task (packages/mongo/polling_observe_driver.js:85:1)
I20160126-03:51:11.477(3)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20160126-03:51:11.477(3)?     at packages/meteor/fiber_helpers.js:125:1
I20160126-03:51:11.477(3)?     - - - - -
I20160126-03:51:11.478(3)?     at [object Object].ReplSet.checkoutReader (/Users/firfi/.meteor/packages/npm-mongo/.1.4.39_1.176uc2o++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:619:14)
I20160126-03:51:11.478(3)?     at Cursor.nextObject (/Users/firfi/.meteor/packages/npm-mongo/.1.4.39_1.176uc2o++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:748:48)
I20160126-03:51:11.478(3)?     at [object Object].fn [as _synchronousNextObject] (/Users/firfi/.meteor/packages/meteor-tool/.1.1.10.selhsd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:89:26)
I20160126-03:51:11.478(3)?     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:986:1)
I20160126-03:51:11.478(3)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1020:1)
I20160126-03:51:11.478(3)?     at [object Object]._.extend.getRawObjects (packages/mongo/mongo_driver.js:1069:1)
I20160126-03:51:11.479(3)?     at [object Object]._.extend._pollMongo (packages/mongo/polling_observe_driver.js:147:1)
I20160126-03:51:11.479(3)?     at [object Object].proto._pollMongo (packages/meteorhacks_kadira/lib/hijack/wrap_observers.js:63:1)
I20160126-03:51:11.479(3)?     at Object.task (packages/mongo/polling_observe_driver.js:85:1)
I20160126-03:51:11.479(3)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20160126-03:51:11.479(3)?     at packages/meteor/fiber_helpers.js:125:1
```

Note: it happens on ` Client modified -- refreshing` only. ` Client modified -- refreshing` stage is quite slow, it's about 1-2 minutes as Meteor rebuild lot of things right now (I have npm-container applied also). It doesn't happens on server-only modifications.

**Comment by zol** [comment]
Please provide a full reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  Without a way to replicate your problem, we can't debug and fix it.

**Comment by Firfi** [comment]
So only thing is needed to be done is set up new db with oplog enabled, emulate network delays there, set up a project that is big enough to build 3 minutes and report here. Will do it when will have some time.
