### ISSUE TITLE
[meteor1.3-beta5] meteor build fails

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#6115]
Running from docker image `node:0.10.41`:

```
root@92c9a7f5ff7b:/opt/src# meteor build --directory /opt/app                               
                                                                                   
/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259
			throw new Error('Must throw non-empty error');
			      ^
Error: Must throw non-empty error
    at Object.Future.throw (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:259:10)
    at Extract.<anonymous> (/tools/fs/files.js:699:42)
    at Extract.emit (events.js:117:20)
    at DirWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/tar/lib/extract.js:61:8)
    at DirWriter.emit (events.js:117:20)
    at FileWriter.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/dir-writer.js:158:12)
    at FileWriter.emit (events.js:92:17)
    at WriteStream.<anonymous> (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fstream/lib/file-writer.js:50:47)
    at WriteStream.emit (events.js:95:17)
    at WriteStream.<anonymous> (evalmachine.<anonymous>:1669:12)
    at OpenReq.Req.done (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/graceful-fs.js:141:5)
    at OpenReq.done (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/graceful-fs.js:61:22)
    at Object.oncomplete (evalmachine.<anonymous>:108:15)
```

**Comment by markoshust** [comment]
Ok, so the build is processing just fine on my Mac. Seems to be a problem with the node:0.10.41 docker image.
