### ISSUE TITLE
Error while building for android platform

### ISSUE THREAD

**Issue by agaezcode** [meteor/meteor#6119]
While executing the command `meteor build` on the console it shows this error: 
Is this an issue? Any suggestion? Thank you

```console

hs@hs:~/Documentos/sandbox/app$ meteor build ../mobile-app --server=my-app-deployed-url.meteor.com
                                              
/home/hs/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: ENOENT, stat '/home/hs/Documentos/sandbox/app/resources/icons/icon-ldpi.png'
    at Object.Future.wait (/home/hs/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as stat] (/tools/fs/files.js:1334:20)
    at Object.files.copyFile (/tools/fs/files.js:549:21)
    at /tools/cordova/builder.js:316:13
    at Function._.each._.forEach (/home/hs/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CordovaBuilder.configureAndCopyImages (/tools/cordova/builder.js:297:7)
    at CordovaBuilder.writeConfigXmlAndCopyResources (/tools/cordova/builder.js:266:12)
    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:158:13)
    at /tools/cli/commands.js:966:24
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/cli/commands.js:958:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:270:29)
    at /tools/cli/commands.js:957:10
    at buildCommand (/tools/cli/commands.js:1012:8)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:791:12)
    at /tools/cli/main.js:1378:23
    - - - - -
hs@hs:~/Documentos/sandbox/app$ 

```

**Comment by martijnwalraven** [comment]
It seems it complains because it can't find `icon-ldpi.png`. Can you check whether that file exists?
