### ISSUE TITLE
`SyntaxError: Unexpected reserved word` when including a client file from server context

### ISSUE THREAD

**Issue by tmeasday** [meteor/meteor#6146]
Repro: https://github.com/tmeasday/1.3-client-server-import

In short `server/load.js` requires `imports/client/file1.js`.

Running against `1.3-modules-beta.5` leads to a crashloop of:

```
W20160203-17:30:33.546(11)? (STDERR) /private/tmp/import-test/.meteor/local/build/programs/server/app/app.js:22
W20160203-17:30:33.547(11)? (STDERR) export const foo = 1;                                                // 1
W20160203-17:30:33.547(11)? (STDERR) ^^^^^^
W20160203-17:30:33.550(11)? (STDERR) SyntaxError: Unexpected reserved word
W20160203-17:30:33.550(11)? (STDERR)     at /private/tmp/import-test/.meteor/local/build/programs/server/boot.js:241:30
W20160203-17:30:33.550(11)? (STDERR)     at Array.forEach (native)
W20160203-17:30:33.550(11)? (STDERR)     at Function._.each._.forEach (/Users/tom/.meteor/packages/meteor-tool/.1.1.12-modules.5.1jh3udk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160203-17:30:33.550(11)? (STDERR)     at /private/tmp/import-test/.meteor/local/build/programs/server/boot.js:137:5
```

Move `server/load.js` to `client/load.js` and the app runs as normal.

**Comment by rclai** [comment]
I have something similar, except I `npm install`'ed the `mysql` package and was trying to `import mysql from 'mysql'`, which yielded the same error. Is this related?

**Comment by tmeasday** [comment]
@rclai in my case it didn't really matter about the specifics of what was in the imported file (in my case you can see it's sort of trivial). The problem occurred if I imported a client import from a server context. Are you doing that?

**Comment by rclai** [comment]
No, like I said, I was importing the Mysql Npm package in the server and got the same error.

**Comment by avital** [comment]
This no longer happens with `1.3-modules-beta.8`

**Comment by tmeasday** [comment]
:+1:

**Comment by nilsi** [comment]
Having something similar:

```

W20160423-14:43:10.267(9)? (STDERR) app/server/methods.js:1
W20160423-14:43:10.267(9)? (STDERR) (function(Npm,Assets){(function(){import Fibers from 'fibers';
W20160423-14:43:10.269(9)? (STDERR)                                   ^^^^^^
W20160423-14:43:10.271(9)? (STDERR) SyntaxError: Unexpected reserved word
W20160423-14:43:10.271(9)? (STDERR)     at /repos/affilate-site/.meteor/local/build/programs/server/boot.js:278:30
W20160423-14:43:10.272(9)? (STDERR)     at Array.forEach (native)
W20160423-14:43:10.272(9)? (STDERR)     at Function._.each._.forEach (/Volumes/320gb/macbookpro/.meteor/packages/meteor-tool/.1.3.2_4.1rz3z4t++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160423-14:43:10.272(9)? (STDERR)     at /repos/myproject/.meteor/local/build/programs/server/boot.js:133:5

```

**Comment by gemhuang21519992** [comment]
@nilsi 
Add the packages
`meteor add ecmascript` `meteor add es5-shim`
solves the problem for me when I was updating my old apps from 1.2 to 1.3 .
This problem does not occur when I was creating new app.

**Comment by nilsi** [comment]
This error goes away if I add ecmascript. Is this a bug?

`meteor add ecmascript`

**Comment by rclai** [comment]
No, you do need `ecmascript` for any ES2015 stuff.

**Comment by nilsi** [comment]
Thought it should be included by default. Also bit strange that isn't mentioned in Meteors migration guides .

**Comment by sarBolt** [comment]
Just added the `ecmascript`, start meteor and got a bunch of jquery errors. I have upgraded from 1.2 to 1.3

**Comment by nilsi** [comment]
I use jQuery as well but didn't get any errors. Might be on your part.

**Comment by leemind** [comment]
@nilsi - Thank you.  Adding ecmascript solved it for me as well

**Comment by john-osullivan** [comment]
I got this error as well but am also using `webpack:webpack` to manage my build.  Adding `ecmascript

**Comment by semeano** [comment]
Hi! I'm getting the following error when running an app.
The weirdest thing is that it works on my friend's laptop and we both have v.1.3.4.4 installed.

```
I20160715-12:39:27.637(1)? [gadicc:hot] modules-runtime - current: v0.6.5, supported v0.6.3; This might be ok but look out for newer versions and issues on meteor-hmr GitHub.
W20160715-12:39:28.822(1)? (STDERR)           
W20160715-12:39:28.824(1)? (STDERR) /Users/semeano/Development/mvp/app/.meteor/local/build/programs/server/app/app.js:15
W20160715-12:39:28.825(1)? (STDERR) import React from 'react';                                                    
W20160715-12:39:28.825(1)? (STDERR) ^^^^^^    
W20160715-12:39:28.830(1)? (STDERR) SyntaxError: Unexpected reserved word
W20160715-12:39:28.830(1)? (STDERR)     at /Users/semeano/Development/mvp/app/.meteor/local/build/programs/server/boot.js:292:30
W20160715-12:39:28.831(1)? (STDERR)     at Array.forEach (native)
W20160715-12:39:28.831(1)? (STDERR)     at Function._.each._.forEach (/Users/semeano/.meteor/packages/meteor-tool/.1.3.4_4.rwnnka++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160715-12:39:28.831(1)? (STDERR)     at /Users/semeano/Development/mvp/app/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```

Do you have any idea of what might be wrong?

Thanks.

**Comment by john-osullivan** [comment]
I fixed that error in the past by using `require` rather than `import` on the client.  That said, Meteor has updated since that happened and I believe that shouldn't be a bug anymore...  Maybe double-check your underlying versions of node and npm?

**Comment by semeano** [comment]
I tried that, but still nothing... Now I get this:

```
I20160716-17:45:32.924(1)? [gadicc:hot] modules-runtime - current: v0.6.5, supported v0.6.3; This might be ok but look out for newer versions and issues on meteor-hmr GitHub.
W20160716-17:45:34.059(1)? (STDERR)           
W20160716-17:45:34.061(1)? (STDERR) /Users/semeano/Development/mvp/app/.meteor/local/build/programs/server/app/app.js:97
W20160716-17:45:34.061(1)? (STDERR) export default Layout;                                                        
W20160716-17:45:34.062(1)? (STDERR) ^^^^^^    
W20160716-17:45:34.064(1)? (STDERR) SyntaxError: Unexpected reserved word
W20160716-17:45:34.064(1)? (STDERR)     at /Users/semeano/Development/mvp/app/.meteor/local/build/programs/server/boot.js:292:30
W20160716-17:45:34.065(1)? (STDERR)     at Array.forEach (native)
W20160716-17:45:34.065(1)? (STDERR)     at Function._.each._.forEach (/Users/semeano/.meteor/packages/meteor-tool/.1.3.4_4.rwnnka++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160716-17:45:34.065(1)? (STDERR)     at /Users/semeano/Development/mvp/app/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8 
```

It seems that any ES6 reserved word pop's up on top but, the bottom lines refer to the same files at exactly the same line:col.

Adding ecmascript package doesn't help either...

```
=> Errors prevented startup:                  
   
   While determining active plugins:
   error: conflict: two packages included in the app (ecmascript and
   gadicc:ecmascript-hot) are both trying to handle *.js
   error: conflict: two packages included in the app (ecmascript and
   gadicc:ecmascript-hot) are both trying to handle *.jsx
   
   While determining active plugins:
   error: conflict: two packages included in the app (ecmascript and
   gadicc:ecmascript-hot) are both trying to handle *.js
   error: conflict: two packages included in the app (ecmascript and
   gadicc:ecmascript-hot) are both trying to handle *.jsx
```

I'm running out of options... :(

**Comment by abernix** [comment]
@semeano If the exact same project is failing for one of you, perhaps try deleting the folders in your `.meteor/local` directory and letting them rebuild themselves.  You can save the `db` folder if you don't want to wipe your database.

**Comment by semeano** [comment]
@abernix Thanks, but it didn't help. I'm having the same issue.

But, I copied my friend's folder into my computer and it worked.
Could it be that some package might be missing here?

**Comment by abernix** [comment]
Hmm, It could have been something in your `node_modules` which removing and running `meteor npm install` might have fixed.  Or some version got upgraded in one place but not the other.  Hard to be sure.

**Comment by nwabdou85** [comment]
Hi, 
any one could help with this error please http://pastecode.org/index.php/view/17802020 ??;
