### ISSUE TITLE
[1.3-cordova-beta.3] After upgrading to 1.3, a name attribute is required for js-modules

### ISSUE THREAD

**Issue by smowden** [meteor/meteor#6156]
After upgrading to 1.3 I ran into an issue where one of the Cordova modules caused an error that prevented the project from building a Cordova App for Android

> Object [object Object] has no method 'parse'
    at handlers.js-module.install (/Users/sexy/_WorkCode/1.3-cdv-test/.meteor/local/cordova-build/platforms/android/cordova/lib/pluginHandlers.js:142:66)
    at Object.ActionStack.process (/Users/sexy/_WorkCode/1.3-cdv-test/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Api.addPlugin (/Users/sexy/_WorkCode/1.3-cdv-test/.meteor/local/cordova-build/platforms/android/cordova/Api.js:205:20)
    at handleInstall (/Users/sexy/.meteor/packages/meteor-tool/.1.1.11-cordova.3.1h9et9p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:603:6)
    at /Users/sexy/.meteor/packages/meteor-tool/.1.1.11-cordova.3.1h9et9p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/Users/sexy/.meteor/packages/meteor-tool/.1.1.11-cordova.3.1h9et9p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/sexy/.meteor/packages/meteor-tool/.1.1.11-cordova.3.1h9et9p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/sexy/.meteor/packages/meteor-tool/.1.1.11-cordova.3.1h9et9p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
    at /Users/sexy/.meteor/packages/meteor-tool/.1.1.11-cordova.3.1h9et9p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
    at flush (/Users/sexy/.meteor/packages/meteor-tool/.1.1.11-cordova.3.1h9et9p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:448:13)

This error is new and the module used to work fine with 1.2. I am not sure if this is a breaking change in cordova and therefore should be resolved by modifying the plugin or whether this is caused by Meteor but I figured I'll post it here, maybe someone else will run into this.

In any case this can be fixed by adding a name attribute to the js-module tag in the plugin.xml, so

`<js-module src="www/powermanagement.js">
        <clobbers target="window.powermanagement" />
    </js-module>`

becomes

`<js-module src="www/powermanagement.js" name="PowerManagement">
        <clobbers target="window.powermanagement" />
    </js-module>`

If someone from the Meteor community could let me know whether this is an issue with cordova or with Meteor I'd be much appreciated.

You can easily reproduce this error by doing this:
> meteor create --release 1.3-cordova-beta.3 1.3-cdv-test
> meteor add cordova:cordova-plugin-powermanagement@https://github.com/cranberrygame/cordova-plugin-powermanagement
> meteor build ../1.3-cdv-test-build/ --server locahost:3000

if you do the same with 1.2, the error goes away

**Comment by martijnwalraven** [comment]
This is definitely a result of the Cordova upgrade and not a Meteor-specific issue. 

As far as I know, `<js-module>` has always required a `name` attribute (see [here](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#link-js-module-element)). I suspect Cordova used to be more lenient but now somehow runs into trouble when it is missing.

**Comment by nerdmed** [comment]
@martijnwalraven thanks for pointing out - let fix this then in the package :+1:
