### ISSUE TITLE
"packages" directory in client directory causes unexpected behavior

### ISSUE THREAD

**Issue by kctang** [meteor/meteor#6161]
A project with js files in client/packages will throw confusing error message. I understand packages is special when used in root directory but i am not sure what is the behavior when used in client directory.

Currently, this is the error message I am getting. Things will work nicely if i just rename the directory to "client/abcde". Reporting this as a bug to improve error message for these special cases instead of the following. I am using 1.3 beta 6.

    TypeError: Cannot call method 'split' of undefined
    at /tools/isobuild/compiler-plugin.js:699:42
    at Array.forEach (native)
    at /tools/isobuild/compiler-plugin.js:698:34
    at scan (/tools/isobuild/compiler-plugin.js:719:51)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:729:7)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:736:8)
    at /tools/isobuild/bundler.js:515:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:506:18)
    at /tools/isobuild/bundler.js:2210:14
    at /tools/isobuild/bundler.js:2299:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/xxx/.meteor/packages/meteor-tool/.1.1.13-modules.6.wxnsas++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2298:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2191:31)
    at /tools/runners/run-app.js:585:36
    at time (/tools/tool-env/profile.js:284:28)
    at Function.run (/tools/tool-env/profile.js:458:12)
    at bundleApp (/tools/runners/run-app.js:575:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:824:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:402:12

**Comment by kctang** [comment]
Tried with Meteor 1.3-modules-beta.7, lines numbers changed a little but same behavior.

    TypeError: Cannot call method 'split' of undefined
    at /tools/isobuild/compiler-plugin.js:701:42
    at Array.forEach (native)
    at /tools/isobuild/compiler-plugin.js:700:34
    at scan (/tools/isobuild/compiler-plugin.js:721:9)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:731:7)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:736:8)
    at /tools/isobuild/bundler.js:515:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:506:18)
    at /tools/isobuild/bundler.js:2214:14
    at /tools/isobuild/bundler.js:2303:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/xxx/.meteor/packages/meteor-tool/.1.1.13-modules.7.1psdqhw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2302:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2195:31)
    at /tools/runners/run-app.js:586:36
    at Function.run (/tools/tool-env/profile.js:462:12)
    at bundleApp (/tools/runners/run-app.js:576:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
    at AppRunner._fiber (/tools/runners/run-app.js:881:28)
    at /tools/runners/run-app.js:406:12

**Comment by benjamn** [comment]
@kctang think I might have fixed this problem (or at least a similar problem) in beta.8, coming soon!

**Comment by kctang** [comment]
hahaha... cool. i'll check again when its out, not a high priority anyway. you guys are awesome! :-)

**Comment by zol** [comment]
@kctang - Closing this out. Please re-open if this is still an issue on the latest beta. Thanks for your help and support.
