### ISSUE TITLE
[1.3-beta.8] Unable to run for cordova (meteor run ios)

### ISSUE THREAD

**Issue by dotansimha** [meteor/meteor#6178]
Trying to run my project, which have ios platform, and it does not run.

The exact error is:
````
TypeError: Can't call method on  undefined
    at TypeError (<anonymous>)
    at module.exports (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.defined.js:3:28)
    at module.exports (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/$.to-object.js:4:17)
    at from (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.array.from.js:12:19)
    at exports.default (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/helpers/toConsumableArray.js:19:31)
    at CordovaProject.run$ (/tools/cordova/project.js:207:17)
    at tryCatch (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:191:11
    at new Promise (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/core-js/library/modules/es6.promise.js:197:7)
    at callInvokeWithMethodAndArg (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:190:16)
    at AsyncIterator.enqueue (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:211:37)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at Object.runtime.async (/Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-runtime/regenerator/runtime.js:228:12)
    at /Users/dotansimha/.meteor/packages/meteor-tool/.1.1.13-modules.8.tv9wfs++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/promise/node_modules/meteor-promise/fiber_pool.js:33:40
````

And it caused because of this line:
https://github.com/meteor/meteor/blob/release-1.3/tools/cordova/project.js#L204

The third argument, `extraPaths` does not have a default value, it should be `extraPaths = []`, otherwise, if this line runs:
```
const env = this.defaultEnvWithPathsAdded(...extraPaths);
``` 

runs and `extraPaths` is undefined, it throws the exception and it does not on the mobile.

**Comment by martijnwalraven** [comment]
Hmmm, this may be caused by the upgrade to Babel 6. Before, the way the spread operator was transpiled apparently accepted an undefined argument.

**Comment by Unforgiven-wanda** [comment]
Hello,
was having the same issue just instants ago, an update to Meteor Beta 11 seems to have fixed this issue for me.

**Comment by tomasz-szymanek** [comment]
I have this bug in Meteor 1.3 beta8

**Comment by martijnwalraven** [comment]
@tomasz-szymanek: Could you try upgrading to `1.3-rc.3`?
