### ISSUE TITLE
My meteor suddenly cannot start

### ISSUE THREAD

**Issue by Hongbo-Miao** [meteor/meteor#6197]
This error below suddenly happens when I were writing codes. Then all my meteor projects cannot run now. Any help? Thanks

```
/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: UNKNOWN, open '/Users/hongbo-miao/Clouds/Git/webrtc/client/video.service.ts'
    at Object.Future.wait (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as readFile] (/tools/fs/files.js:1334:20)
    at readFile (/tools/fs/watch.js:243:18)
    at Watcher._fireIfFileChanged (/tools/fs/watch.js:372:20)
    at /tools/fs/watch.js:440:12
    at Function._.each._.forEach (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at Watcher._startFileWatches (/tools/fs/watch.js:429:7)
    at new Watcher (/tools/fs/watch.js:355:10)
    at setupClientWatcher (/tools/runners/run-app.js:758:23)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:769:7)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
    - - - - -
```

And this is when I open another project:
```
/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:168
    }).run();
       ^
Error: UNKNOWN, unknown error '/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/logging/program.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.wrapper [as readFile] (/tools/fs/files.js:1338:35)
    at Function.readFromDisk (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:1554:33)
    at Object.readJsImage (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:2365:18)
    at loadIsopacketFromDisk (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/isopackets.js:247:23)
    at /Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/isopackets.js:85:23
    at Object.exports.noYieldsAllowed (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:73:14)
    at Object.load (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/isopackets.js:77:23)
    at getLoggingPackage (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-log.js:20:24)
    at [object Object]._.extend.logAppOutput (/Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/runners/run-log.js:86:15)
    at Transformer.<anonymous> (/tools/runners/run-app.js:108:14)
    at /Users/hongbo-miao/.meteor/packages/meteor-tool/.1.1.10.96gafk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:167:12
```

**Comment by Hongbo-Miao** [comment]
Hmm, I just fixed it by reinstalling meteor on my system
