### ISSUE TITLE
MongoError: driver is incompatible with this server version for Mongo 3.2 + SSL

### ISSUE THREAD

**Issue by artgo** [meteor/meteor#6260]
With latest mongo + SSL the meteor stopped working :(
```
$ export MONGO_URL='mongodb://admin:pass@localhost:11102/local?authSource=admin&ssl=true' && meteor
[[[[[ ~/proj/myapp ]]]]]

=> Started proxy.
W20160217-19:33:57.039(-8)? (STDERR)
W20160217-19:33:57.041(-8)? (STDERR) /Users/me/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20160217-19:33:57.041(-8)? (STDERR)            throw(ex);
W20160217-19:33:57.041(-8)? (STDERR)                  ^
W20160217-19:33:57.041(-8)? (STDERR) MongoError: driver is incompatible with this server version
W20160217-19:33:57.041(-8)? (STDERR)     at Object.Future.wait (/Users/me/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20160217-19:33:57.041(-8)? (STDERR)     at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)
W20160217-19:33:57.041(-8)? (STDERR)     at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:635:1)
W20160217-19:33:57.041(-8)? (STDERR)     at setupUsersCollection (accounts_server.js:1413:9)
W20160217-19:33:57.042(-8)? (STDERR)     at new AccountsServer (accounts_server.js:49:5)
W20160217-19:33:57.042(-8)? (STDERR)     at Package (globals_server.js:5:12)
W20160217-19:33:57.042(-8)? (STDERR)     at /Users/me/proj/myapp/.meteor/local/build/programs/server/packages/accounts-base.js:1814:4
W20160217-19:33:57.042(-8)? (STDERR)     at /Users/me/proj/myapp/.meteor/local/build/programs/server/packages/accounts-base.js:1825:3
W20160217-19:33:57.042(-8)? (STDERR)     at /Users/me/proj/myapp/.meteor/local/build/programs/server/boot.js:242:10
W20160217-19:33:57.042(-8)? (STDERR)     at Array.forEach (native)
W20160217-19:33:57.042(-8)? (STDERR)     - - - - -
W20160217-19:33:57.043(-8)? (STDERR)     at Object.toError (/Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
W20160217-19:33:57.043(-8)? (STDERR)     at __executeInsertCommand (/Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1926:27)
W20160217-19:33:57.043(-8)? (STDERR)     at Db._executeInsertCommand (/Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:2028:5)
W20160217-19:33:57.043(-8)? (STDERR)     at /Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1348:12
W20160217-19:33:57.043(-8)? (STDERR)     at /Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1442:20
W20160217-19:33:57.043(-8)? (STDERR)     at /Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1196:16
W20160217-19:33:57.043(-8)? (STDERR)     at /Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1905:9
W20160217-19:33:57.044(-8)? (STDERR)     at Server.Base._callHandler (/Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
W20160217-19:33:57.044(-8)? (STDERR)     at /Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
W20160217-19:33:57.044(-8)? (STDERR)     at [object Object].MongoReply.parseBody (/Users/me/.meteor/packages/npm-mongo/.1.4.39_1.17b8oex++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
=> Exited with code: 8
```

**Comment by tmeasday** [comment]
Thanks for the report, see #5809

**Comment by interfaith** [comment]
MongoError: driver is incompatible with this server version

the latest meteor gives me this error with the latest mongo on ubuntu 16.04
? any work around ?

**Comment by tmeasday** [comment]
Meteor 1.3 does not work in Mongo 3.2. I believe it works pretty well with Mongo 3.0 however.

(The upcoming) Meteor 1.4 *will* ship with Mongo 3.2 by default however.

**Comment by interfaith** [comment]
the basic works, maybe some unusual operations fail. the problem here was
oplog initialization, my mistake.

On Sun, Jun 26, 2016 at 3:47 PM, Tom Coleman <notifications@github.com>
wrote:

> Meteor 1.3 does not work in Mongo 3.2. I believe it works pretty well with
> Mongo 3.0 however.
>
> (The upcoming) Meteor 1.4 *will* ship with Mongo 3.2 by default however.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/meteor/meteor/issues/6260#issuecomment-228627655>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAs5z4_JHUB8uD1FMKKUagAh3MdpqW2Wks5qPwGdgaJpZM4Hcvla>
> .
>



-- 
-----
Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
