### ISSUE TITLE
[meteor 1.3-beta.12] Runtime error with when npm package

### ISSUE THREAD

**Issue by urossmolnik** [meteor/meteor#6376]
I get a runtime error when using when npm package:
```
Error: Cannot find module './lib/decorators/timed'
     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:85:1)
     at node_modules/when/when.js:12:1
     at node_modules/when/when.js:228:1
     at node_modules/when/when.js:10:1
     at meteorInstall.node_modules.when.when.js (node_modules/when/when.js:228:1)
```

How to replay:
```
meteor create --release 1.3-beta.12 myapp
cd myapp
npm install when --save
# insert in myapp.js: import when from 'when';
npm run start
```

**Comment by zol** [comment]
Thanks for reporting this. We're going to tackle module specific issues post 1.3

**Comment by benjamn** [comment]
This is fixed in `beta.16`, thanks to #6398.
