### ISSUE TITLE
[1.3-beta.12] Error: sourcePath not a file, ImportScanner

### ISSUE THREAD

**Issue by Siyfion** [meteor/meteor#6383]
***1 Upvote*** After upgrading from beta.11 to beta.12 my application no-longer runs. It throws the following error:
```
=> Started proxy.

Error: sourcePath not a file: bootstrap/js/transition.js
    at ImportScanner._ensureSourcePath (/tools/isobuild/import-scanner.js:208:13)
    at /tools/isobuild/import-scanner.js:101:28
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:100:11)
    at /tools/isobuild/compiler-plugin.js:709:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:689:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
    at /tools/isobuild/bundler.js:516:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
    at /tools/isobuild/bundler.js:2232:14
    at /tools/isobuild/bundler.js:2322:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/siyfion/.meteor/packages/meteor-tool/.1.1.13-beta.12.14gk7rd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2321:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
    at /tools/runners/run-app.js:586:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:576:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
    at AppRunner._fiber (/tools/runners/run-app.js:881:28)
    at /tools/runners/run-app.js:406:12
```

I have the following packages installed:
```
255kb:meteor-status                 1.4.3  Meteor Status automatically alerts users when the connection to the server has been lost.
accounts-base                       1.2.3-beta.12* A user account system
accounts-password                   1.1.5-beta.12* Password support for accounts
alanning:roles                      1.2.15  Authorization package for Meteor
aldeed:collection2                  2.9.0  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema                1.5.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
blaze-html-templates                1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                               1.1.1-beta.12* Check whether a value matches a pattern
chrismbeckett:toastr                2.1.2_1  Gnome / Growl type non-blocking notifications
ecmascript                          0.4.0-beta.12* Compiler plugin that supports ES2015+ in all .js files
edgee:slingshot                     0.7.1  Directly post files to cloud storage services, such as AWS-S3.
ejson                               1.0.8-beta.12* Extended and Extensible JSON library
email                               1.0.9-beta.12* Send email messages
fortawesome:fontawesome             4.5.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
gwendall:impersonate                0.2.2  Impersonate users in Meteor
http                                1.1.2-beta.12* Make HTTP calls to remote servers
ian:accounts-ui-bootstrap-3         1.2.89  Bootstrap-styled accounts-ui with multi-language support.
jquery                              1.11.5-beta.12* Manipulate the DOM using CSS selectors
kadira:blaze-layout                 2.3.0  Layout Manager for Blaze (works well with FlowRouter)
kadira:flow-router                  2.10.1  Carefully Designed Client Side Router for Meteor
less                                2.5.2-beta.12* Leaner CSS language
logging                             1.0.9-beta.12* Logging facility.
matb33:collection-hooks             0.8.1  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
mdg:validated-method                1.0.1  A simple wrapper for Meteor.methods
meteor-base                         1.0.1  Packages that every Meteor app needs
meteorhacks:kadira                  2.28.2  Performance Monitoring for Meteor
meteorhacks:kadira-debug            1.3.3  Full Stack Debugging Solution for Meteor
meteorhacks:kadira-profiler         1.2.1  CPU Profiler for Meteor (used with Kadira)
meteorhacks:picker                  1.0.3  Server Side Router for Meteor
meteorhacks:unblock                 1.1.0  a way to use this.unblock inside publications
meteortoys:allthings                2.3.1  Insanely Handy Development Tools
mizzao:bootboxjs                    4.4.0  Programmatic dialog boxes using Twitter's bootstrap modals
mobile-experience                   1.0.1  Packages for a great mobile user experience
momentjs:moment                     2.11.2  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                               1.1.4-beta.12* Adaptor for using MongoDB and Minimongo over DDP
mrgalaxy:stripe                     2.2.2  Stripe.js and Node-Stripe brought to Meteor.
natestrauser:select2                4.0.1  Select2 is a jQuery based replacement for select boxes.
nemo64:bootstrap                    3.3.5_2  Highly configurable bootstrap integration.
okgrow:analytics                    1.0.4  Complete Google Analytics, Mixpanel, KISSmetrics (and more) integration for Meteor
peerlibrary:async                   0.9.2_1* Async provides straight-forward, powerful functions for working with asynchronous JavaScript
peerlibrary:aws-sdk                 2.2.37_1  SDK for AWS services including Amazon S3, Amazon EC2, DynamoDB, and Amazon SWF
percolate:migrations                0.9.8  Define and run db migrations.
percolate:synced-cron               1.3.0  Allows you to define and run scheduled jobs across multiple servers.
random                              1.0.6-beta.12* Random number generator and utilities
react-meteor-data                   0.2.5  React mixin for reactively tracking Meteor data
react-template-helper               0.2.5  Use React components in native Meteor templates
reactive-dict                       1.1.4-beta.12* Reactive dictionary
reactive-var                        1.0.6  Reactive variable
reload                              1.1.5-beta.12* Reload the page while preserving application state.
reywood:publish-composite           1.4.2  Publish a set of related documents from multiple collections with a reactive join
rubaxa:sortable                     1.3.0  Sortable: reactive minimalist reorderable drag-and-drop lists on modern browsers and touch devices
ryanswapp:spectrum-colorpicker      0.0.1  A meteor wrapper for the spectrum colorpicker
sergeyt:typeahead                   0.11.1_8  Autocomplete package for meteor powered by twitter typeahead.js
session                             1.1.2-beta.12* Session variable
siyfion:webfontloader               1.6.21  Web Font Loader gives you added control when using linked fonts via @font-face.
snapsvg:core                        0.4.0  Snap.svg (official): The JavaScript library for modern SVG graphics.
spacebars                           1.0.8-beta.12* Handlebars-like template language for Meteor
standard-minifier-css               1.0.3-beta.12  Standard css minifier used with Meteor apps by default.
standard-minifier-js                1.0.3-beta.12  Standard javascript minifiers used with Meteor apps by default.
themeteorchef:jquery-validation     1.14.0  jQuery Validation by jzaefferer, repackaged for Meteor.
tmeasday:publish-counts             0.7.3  Publish the count of a cursor, in real time
tracker                             1.0.10-beta.12* Dependency tracker to allow reactive callbacks
underscore                          1.0.5-beta.12* Collection of small helpers: _.map, _.each, ...
underscorestring:underscore.string  3.3.4  underscore.string (official): String manipulation extensions for Underscore.js javascript library.
zenorocha:clipboard                 1.5.9  Modern copy to clipboard. No Flash. Just 2kb.
```

**Comment by maabed** [comment]
+1 
This error shows  same to me as well when using `nemo64:bootstrap` package

**Comment by Siyfion** [comment]
I would surmise that the only packaged required to recreate this issue then would be the `nemo64:bootstrap` package.

**Comment by DanielDornhardt** [comment]
Hi, I have the same problem with the raix:push - package. Unfortunately it seems like it's not *only* the raix:push - package, because in an empty project with just that package I don't receive the same error and the app starts running.

I'll try to whittle it down a bit.

My error looks like this:

    Error: sourcePath not a file: push.config.web.browser.js
        at ImportScanner._ensureSourcePath (/tools/isobuild/import-scanner.js:208:13)
        at /tools/isobuild/import-scanner.js:101:28
        at Array.forEach (native)
        at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:100:11)
        at /tools/isobuild/compiler-plugin.js:709:15
        at Array.forEach (native)
        at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:689:19)
        at ClientTarget._emitResources (/tools/isobuild/bundler.js:749:8)
        at /tools/isobuild/bundler.js:516:12
        at /tools/utils/buildmessage.js:359:18
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:352:34
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:350:23
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at Object.enterJob (/tools/utils/buildmessage.js:324:26)
        at ClientTarget.make (/tools/isobuild/bundler.js:507:18)
        at /tools/isobuild/bundler.js:2232:14
        at /tools/isobuild/bundler.js:2322:20
        at Array.forEach (native)
        at Function._.each._.forEach (/Users/spaceman/.meteor/packages/meteor-tool/.1.1.13-beta.12.1p7kgab++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
        at /tools/isobuild/bundler.js:2321:7
        at /tools/utils/buildmessage.js:271:13
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:264:29
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:262:18
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at /tools/utils/buildmessage.js:253:23
        at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
        at Object.capture (/tools/utils/buildmessage.js:252:19)
        at Object.exports.bundle (/tools/isobuild/bundler.js:2213:31)
        at /tools/runners/run-app.js:586:36
        at Function.run (/tools/tool-env/profile.js:489:12)
        at bundleApp (/tools/runners/run-app.js:576:34)
        at AppRunner._runOnce (/tools/runners/run-app.js:629:35)
        at AppRunner._fiber (/tools/runners/run-app.js:881:28)
        at /tools/runners/run-app.js:406:12

We also use a lot of packages, many of those are the same @Siyfion  is using and i'd call it a medium-sized project at least.

I'll try to binary search for the error a bit and see if I can narrow it down a bit.

**Comment by benjamn** [comment]
This is fixed in `beta.16`. Sorry for the overly aggressive assertion :)
