### ISSUE TITLE
Internal Server Error on Accounts.resetPassword

### ISSUE THREAD

**Issue by danielflippance** [meteor/meteor#6397]
I'm using Meteor's built-in account reset behaviour which sends you an email containing a reset link and then internally calls the Accounts.resetPassword method when you click on that link. It works great on the dev machine, but on our staging server (Heroku) it returns an 'Internal Server Error' in the New Password window when I click Set Password. The stack trace is:

    Exception while invoking method 'resetPassword' Error: setUserId must be called on string or null, not object 
        at [object Object]._.extend._setUserId (livedata_server.js:774:13) 
        at [object Object].setUserId [as _setUserId] (livedata_server.js:666:14) 
        at [object Object]._.extend.setUserId (packages/ddp-common/method_invocation.js:94:1) 
        at AccountsServer.Ap._loginUser (accounts_server.js:286:20) 
        at AccountsServer.Ap._attemptLogin (accounts_server.js:340:12) 
        at AccountsServer.Ap._loginMethod (accounts_server.js:368:15) 
        at [object Object].Meteor.methods.resetPassword (password_server.js:643:19) 
        at maybeAuditArgumentChecks (livedata_server.js:1698:12) 
        at livedata_server.js:708:19 
        at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) 

We're not customizing the the email sent, just using the default email from Meteor. Email is sent via SendGrid. Meteor version is 1.2.1. We've also using angular-meteor. In both cases, there is no logged in user.

I checked the websocket on each and the only difference I can see is that the localhost request header has the following cookies in it but the Heroku version doesn't: __atuvc=5%7C14%2C51%blahblah; _ga=GA1.1.629blahblah; express.sid=s%3AP3GjI6q49hblahblah, plus Heroku shows a proxy header on the response Via:1.1 vegur

Versions: 
accounts-base@1.2.2
accounts-password@1.1.4
accounts-ui@1.1.6
accounts-ui-unstyled@1.1.8
alanning:roles@1.2.14
angular@1.3.1
angular-blaze-templates-compiler@0.0.1
angular-meteor-data@0.0.8
angular-templates@0.0.3
angular-with-blaze@1.2.1
angular:angular@1.4.8
angular:angular-animate@1.4.8
angular:angular-sanitize@1.4.8
angularui:angular-ui-router@0.2.15
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
benjamine:jsondiffpatch@0.1.38_1
binary-heap@1.0.4
blaze@2.1.3
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
check@1.1.0
dburles:mongo-collection-instances@0.3.4
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.2
ddp-rate-limiter@1.0.0
ddp-server@1.2.2
deps@1.0.9
diff-sequence@1.0.1
ecmascript@0.1.6
ecmascript-runtime@0.2.6
ejson@1.0.7
email@1.0.8
es5-shim@4.1.14
fastclick@1.0.7
force-ssl@1.0.6
fortawesome:fontawesome@4.4.0
fourseven:scss@3.4.1
francocatena:compass@0.6.0
geojson-utils@1.0.4
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.0.11
iron:router@1.0.12
iron:url@1.0.11
jquery@1.11.4
lai:collection-extensions@0.1.4
launch-screen@1.0.4
less@2.5.1
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
maxharris9:meteor-bootstrap-slider@0.9.0
meteor@1.1.10
meteor-base@1.0.1
meteorhacks:async@1.0.0
meteorhacks:npm@1.5.0
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
momentjs:moment@2.11.1
mongo@1.1.3
mongo-id@1.0.1
npm-bcrypt@0.7.8_2
npm-container@1.2.0
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
pbastowski:angular-babel@1.0.9
peerlibrary:aws-sdk@2.2.6_1
peerlibrary:blocking@0.5.2
peernohell:c3@1.1.3
promise@0.5.1
random@1.0.5
rate-limit@1.0.0
reactive-dict@1.1.3
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
sergeyt:d3@3.4.1
service-configuration@1.0.5
session@1.1.1
sha@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.2
teamon:tinymce@4.3.3_3
templating@1.1.5
templating-tools@1.0.0
tracker@1.0.9
twbs:bootstrap-noglyph@3.3.5
ui@1.0.8
underscore@1.0.4
url@1.0.5
webapp@1.2.3
webapp-hashing@1.0.5

**Comment by danielflippance** [comment]
Decided to not use the built in account reset feature.

**Comment by danielflippance** [comment]
Turns out this error occurs when calling Accounts.resetPassword directly as well. It only occurs on our staging server which is running on Heroku. Basically this means the users cannot reset their password when running on Heroku.
