### ISSUE TITLE
meteor shell in 1.2.1 first query throws error

### ISSUE THREAD

**Issue by reduxdj** [meteor/meteor#6423]
Often starting my shell and entering a query returns this, the following query commands in the shell seem to work fine.

> RatingItems.remove({})
TypeError: Object exports has no method 'split'
    at relativeTo (packages/amd_manager/packages/amd_manager.js:53:1)
    at [object Object].manager.load (packages/amd_manager/packages/amd_manager.js:92:1)
    at [object Object].manager.define (packages/amd_manager/packages/amd_manager.js:128:1)
    at define (packages/mrt_define/packages/mrt_define.js:65:1)
    at Token.BooleanLiteral (/Users/Patrick_/.meteor/packages/babel-compiler/.5.8.24_1.ijudcs++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/esprima-fb/esprima.js:41:9)
    at Object.<anonymous> (/Users/Patrick_/.meteor/packages/babel-compiler/.5.8.24_1.ijudcs++os+web.browser+web.cordova/npm/node_modules/meteor-babel/node_modules/esprima-fb/esprima.js:47:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
> RatingItem

**Comment by zol** [comment]
Please provide a minimal reproduction as described in: https://github.com/meteor/meteor/wiki/Contributing-to-Meteor#reporting-a-bug-in-meteor  . Often the act of pairing down your code reveals a different bug or cause for the behavior behind your original report. Being able to clone, run and understand a simple git repository makes it more likely that contributors will take a look at your report.
