### ISSUE TITLE
Unable to run Meteor apps 1.3 beta.16+ on Windows 10

### ISSUE THREAD

**Issue by Goatic** [meteor/meteor#6507]
As the title states, I'm unable to run Meteor `1.3.beta.16+` apps including the two `rc`'s. I'm executing on a Windows 10 machine, and I've made sure to test my issue thoroughly, to isolate the margin of error. Creating and running `1.2x` projects works great, and without issues. The same goes for `1.3.beta.8`.

However, if I create a new project or update an existing project (tested with `beta.16` and `rc.2`) , I get follow output when I try to run the application:
```
[[[[[ ~\D\Documents\Meteor Projects\SomeProject]]]]]

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
W20160316-20:37:22.471(1)? (STDERR)
W20160316-20:37:22.472(1)? (STDERR) }).run();
W20160316-20:37:22.472(1)? (STDERR) D:\Documents\Meteor Projects\SomeProject\.meteor\local\build\programs\server\boot.js:322
W20160316-20:37:22.472(1)? (STDERR)    ^
W20160316-20:37:22.473(1)? (STDERR)     at Object.Npm.require (D:\Documents\Meteor Projects\SomeProject\.meteor\local\build\programs\server\boot.js:193:17)
W20160316-20:37:22.472(1)? (STDERR) Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
W20160316-20:37:22.473(1)? (STDERR)     at Meteor.startup (D:\Documents\Meteor Projects\SomeProject\.meteor\local\build\programs\server\packages\meteor.js:666:32)
W20160316-20:37:22.473(1)? (STDERR)     at D:\Documents\Meteor Projects\SomeProject\.meteor\local\build\programs\server\packages\meteor.js:835:4
W20160316-20:37:22.473(1)? (STDERR)     at D:\Documents\Meteor Projects\SomeProject\.meteor\local\build\programs\server\packages\meteor.js:1353:3
W20160316-20:37:22.473(1)? (STDERR)     at D:\Documents\Meteor Projects\SomeProject\.meteor\local\build\programs\server\boot.js:281:10
W20160316-20:37:22.473(1)? (STDERR)     at Array.forEach (native)
W20160316-20:37:22.473(1)? (STDERR)     at Function._.each._.forEach (C:\Users\Goati\AppData\Local\.meteor\packages\meteor-tool\1.2.4-rc.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160316-20:37:22.474(1)? (STDERR)     at D:\Documents\Meteor Projects\SomeProject\.meteor\local\build\programs\server\boot.js:133:5
W20160316-20:37:25.408(1)? (STDERR)
```
Please let me know if you need any more information - like the password to my email, my favorite color or whatever will help you resolve this issue :sunny:

**Comment by treylon** [comment]
This issue has already been reported and a fix is in progress #6500
