### ISSUE TITLE
Update from release 1.3-rc.4 to 1.3-rc.5 fails with error

### ISSUE THREAD

**Issue by miri-am** [meteor/meteor#6557]
I get the following error on a Mac when updating with `meteor update --release 1.3-rc.5`. It works on a clean project but fails on all (3) of my more complex ones.

```
miri$ meteor update --release 1.3-rc.5
                                              
/Users/miri/.meteor/packages/meteor-tool/.1.2.4-rc.5.coawjo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: false == true
    at new NodeModulesDirectory (/tools/isobuild/bundler.js:230:12)
    at add (/tools/isobuild/bundler.js:352:9)
    at Function.readDirsFromJSON (/tools/isobuild/bundler.js:358:7)
    at /tools/isobuild/bundler.js:1926:34
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/miri/.meteor/packages/meteor-tool/.1.2.4-rc.5.coawjo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Function.readFromDisk (/tools/isobuild/bundler.js:1918:7)
    at Object.readJsImage (/tools/isobuild/bundler.js:2790:18)
    at /tools/isobuild/isopack.js:957:28
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/miri/.meteor/packages/meteor-tool/.1.2.4-rc.5.coawjo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:954:7)
    at Isopack._.extend.initFromPath (/tools/isobuild/isopack.js:888:17)
    at /tools/isobuild/isopack-cache.js:240:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/isopack-cache.js:226:24
    at Function.time (/tools/tool-env/profile.js:305:10)
    at [object Object]._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:216:15)
    at /tools/isobuild/isopack-cache.js:77:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/miri/.meteor/packages/meteor-tool/.1.2.4-rc.5.coawjo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at [object Object].buildLocalPackages (/tools/isobuild/isopack-cache.js:76:24)
    at /tools/project-context.js:758:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:757:18)
    at /tools/project-context.js:278:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:268:18)
    at /tools/project-context.js:260:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:259:13)
    at /tools/cli/commands-packages.js:1523:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:279:29)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1522:8)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:1594:29)
    at /tools/cli/main.js:1408:23
```

**Comment by sanderdatema** [comment]
Duplicate of #6555

**Comment by miri-am** [comment]
ok. Closing because of #6555
