### ISSUE TITLE
[1.3-rc.8] winston module files are being searched in wrong directory

### ISSUE THREAD

**Issue by aniketdd** [meteor/meteor#6571]
W20160323-15:38:29.492(5.5)? (STDERR)                                           throw(ex);
W20160323-15:38:29.492(5.5)? (STDERR)                                                 ^
W20160323-15:38:29.492(5.5)? (STDERR) Error: ENOENT, no such file or directory 'C:\node_modules\winston\node_modules\pkginfo\lib'
W20160323-15:38:29.493(5.5)? (STDERR)     at Object.fs.readdirSync (fs.js:666:18)
W20160323-15:38:29.493(5.5)? (STDERR)     at Function.pkginfo.find (packages\modules.js:28207:18)
W20160323-15:38:29.493(5.5)? (STDERR)     at Function.pkginfo.read (packages\modules.js:28231:17)
W20160323-15:38:29.494(5.5)? (STDERR)     at module.exports (packages\modules.js:28181:21)
W20160323-15:38:29.494(5.5)? (STDERR)     at meteorInstall.node_modules.winston.node_modules.pkginfo.lib.pkginfo.js (packages\modules.js:28244:1)
W20160323-15:38:29.494(5.5)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:158:9)
W20160323-15:38:29.494(5.5)? (STDERR)     at require (packages\modules-runtime.js:92:16)
W20160323-15:38:29.495(5.5)? (STDERR)     at meteorInstall.node_modules.winston.lib.winston.js (packages\modules.js:26101:1)
W20160323-15:38:29.495(5.5)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:158:9)
W20160323-15:38:29.495(5.5)? (STDERR)     at require (packages\modules-runtime.js:92:16)

Getting above error on updating meteor to rc8 on my windows 10 64 bit machine.
Had to create symlink to point to c drive as mentioned in another issue.
works fine after copying node_modules folder containing winston into C: drive.

**Comment by aniketdd** [comment]
got resolved in rc.10
