### ISSUE TITLE
[1.3-rc.12] Throw error after upgrading

### ISSUE THREAD

**Issue by jayasth** [meteor/meteor#6591]
After I upgraded from 1.3-beta.16 to 1.3-rc.12 I am getting the following error:
```
Jayas-Mac-Pro:PollV2 jayashrestha$ meteor
[[[[[ ~/projects/pollv2 ]]]]]

=> Started proxy.
=> Started MongoDB.

/Users/jayashrestha/.meteor/packages/templating/.1.1.7-rc.12.v38ygi++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: EACCES, open '/Users/jayashrestha/projects/pollv2/node_modules/.bin/.meteor-portable'
```

**Comment by Nomeasmo** [comment]
Same here.

If I build with Xcode I get an error:
```
.../Classes/MainViewController.m:109:19: No visible @interface for 'CDVViewController' declares the selector 'webViewDidFinishLoad:'
```
The stack trace if run with `meter run ios` is:
```
    at tryCatchNextTick .../.meteor/packages/meteor-tool/.1.2.6-rc.12.gatj9k++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:115:12)
    at .../.meteor/packages/meteor-tool/.1.2.6-rc.12.gatj9k++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:102:5
    at .../.meteor/packages/templating/.1.1.7-rc.12.p80i6a++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:33:40
```

**Comment by jayasth** [comment]
My issue is resolved after I updated it to rc.13
