### ISSUE TITLE
[1.3-rc.12] Throw error on update due to npm-container package

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#6593]
I saw a throw error when I update to `1.3-rc.12` from `1.3-beta.12`.  I tried upgrading on the Meteor example and it works fine.

I added packages from my non-working version to the example until I saw the error.  The problematic package was `npm-container`.  I do not know how it got into my packages, I think it was added to packages automatically at some point?  Maybe you know more...

### Workaround
I removed `npm-container` from packages and all is well now.

**Request:** Maybe a better error statement flagging the problem package?

### Environment:
Windows 10 x64, meteor installed on `C:` drive, project on `E:` drive
starting from `1.3-beta.12`.

### Error Output
`meteor update --release 1.3-rc.12`

C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool\1.2.6-rc.12\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
`Error: Builder can not write without either data or a file path or a symlink path: os/packages/packages.json
    at Builder.write (C:\tools\isobuild\builder.js:251:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:382:10)
    at C:\tools\isobuild\isopack.js:1400:27
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool\1.2.6-rc.12\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at _.each.builder.copyDirectory.from (C:\tools\isobuild\isopack.js:1372:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool\1.2.6-rc.12\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1263:9
    at Isopack._.extend.saveToPath (C:\tools\isobuild\isopack.js:1641:7)
    at C:\tools\isobuild\isopack-cache.js:323:23
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:260:18)
    at C:\tools\isobuild\isopack-cache.js:194:16
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at C:\tools\isobuild\isopack-cache.js:193:17
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:184:20)
    at C:\tools\isobuild\isopack-cache.js:75:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool\1.2.6-rc.12\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object].eachPackage (C:\tools\packaging\package-map.js:49:7)
    at [object Object].buildLocalPackages (C:\tools\isobuild\isopack-cache.js:74:24)
    at C:\tools\project-context.js:758:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:757:18)
    at C:\tools\project-context.js:278:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:268:18)
    at C:\tools\project-context.js:260:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:259:13)
    at C:\tools\cli\commands-packages.js:1523:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:279:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1522:8)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands-packages.js:1594:29)
    at C:\tools\cli\main.js:1408:23

**Comment by lieuwex** [comment]
Thanks, had the same problem when deploying to my docker instance.

**Comment by jking13** [comment]
I had this problem with a docker container. The problem was docker caching the curl install. Here's a good doc on docker caching: http://thenewstack.io/understanding-the-docker-cache-for-faster-builds/ The fix was to change the dockerfile to be 

RUN curl https://install.meteor.com/ | sh; echo "version 1.3"

and then change the version to match the meteor version to force meteor to update the cache.
