### ISSUE TITLE
[1.3] Error: Builder can not write, using highcharts:highcharts:meteor

### ISSUE THREAD

**Issue by oliverlloyd** [meteor/meteor#6616]
Just wanted to check, is this an issue with 1.3 or with the way this package is initialised? If it is the package author's problem, are you able to comment on what they need to do to resolve it and I'll raise it with them directly.

```
$ meteor create hc-test
$ cd hc-test/
$ meteor update
This project is already at Meteor 1.3, the latest release.
$ meteor add highcharts:highcharts-meteor
highcharts:highcharts-meteor  added, version 0.2.1
highcharts:highcharts-meteor: Official wrapper for Highcharts, Highstock and Highmaps charting libraries.
$ meteor
[[[[[ ~/Code/hc-test ]]]]]

=> Started proxy.
=> Started MongoDB.
Highcharts initialized, please restart Meteor.
$ meteor
[[[[[ ~/Code/hc-test ]]]]]

=> Started proxy.
=> Started MongoDB.
highcharts-container: updating npm dependencies -- highcharts...

/Users/oliver/.meteor/packages/meteor-tool/.1.3.0_3.10nvw69++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: Builder can not write without either data or a file path or a symlink path: web.browser/packages/highcharts-container/client/config.highcharts.json
    at Builder.write (/tools/isobuild/builder.js:251:13)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:382:10)
    at /tools/isobuild/isopack.js:1400:27
    at Array.forEach (native)...
```

**Comment by jallen2281** [comment]
I'm also experiencing this same error.

/home/admin/.meteor/packages/meteor-tool/.1.3.0_3.1dx5qss++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: Builder can not write without either data or a file path or a symlink path: web.browser/packages/highcharts-container/client/config.highcharts.json
    at Builder.write (/tools/isobuild/builder.js:251:13)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:382:10)
    at /tools/isobuild/isopack.js:1400:27
    at Array.forEach (native)
    at Function._.each._.forEach (/home/admin/.meteor/packages/meteor-tool/.1.3.0_3.1dx5qss++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at _.each.builder.copyDirectory.from (/tools/isobuild/isopack.js:1372:11)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/admin/.meteor/packages/meteor-tool/.1.3.0_3.1dx5qss++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1263:9
    at Isopack._.extend.saveToPath (/tools/isobuild/isopack.js:1641:7)
    at /tools/isobuild/isopack-cache.js:323:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._loadLocalPackage (/tools/isobuild/isopack-cache.js:260:18)
    at /tools/isobuild/isopack-cache.js:194:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:193:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:184:20)
    at /tools/isobuild/isopack-cache.js:75:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/admin/.meteor/packages/meteor-tool/.1.3.0_3.1dx5qss++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at [object Object].buildLocalPackages (/tools/isobuild/isopack-cache.js:74:24)
    at /tools/project-context.js:758:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:757:18)
    at /tools/project-context.js:278:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:268:18)
    at /tools/project-context.js:260:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:259:13)
    at /tools/cli/commands-packages.js:2021:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:2020:27)
    at /tools/cli/main.js:1408:23

**Comment by keepthefaya** [comment]
same error

Error: Builder can not write without either data or a file path or a symlink path: web.browser/packages/highcharts-container/client/config.highcharts.json
    at Builder.write (/tools/isobuild/builder.js:251:13)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:382:10)
    at /tools/isobuild/isopack.js:1400:27
    at Array.forEach (native)
    at Function._.each._.forEach (/home/minerlocal/.meteor/packages/meteor-tool/.1.3.0_3.1juah9i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at _.each.builder.copyDirectory.from (/tools/isobuild/isopack.js:1372:11)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/minerlocal/.meteor/packages/meteor-tool/.1.3.0_3.1juah9i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1263:9
    at Isopack._.extend.saveToPath (/tools/isobuild/isopack.js:1641:7)
    at /tools/isobuild/isopack-cache.js:323:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._loadLocalPackage (/tools/isobuild/isopack-cache.js:260:18)
    at /tools/isobuild/isopack-cache.js:194:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:193:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:184:20)
    at /tools/isobuild/isopack-cache.js:75:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/minerlocal/.meteor/packages/meteor-tool/.1.3.0_3.1juah9i++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at [object Object].buildLocalPackages (/tools/isobuild/isopack-cache.js:74:24)
    at /tools/project-context.js:758:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:757:18)
    at /tools/project-context.js:278:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:268:18)
    at /tools/project-context.js:260:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:259:13)
    at /tools/runners/run-app.js:557:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:556:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12

**Comment by eblismanuel** [comment]
Same error, and not let me remove the highcharts:highcharts-meteor package.

Error: Builder can not write without either data or a file path or a symlink path: web.browser/packages/highcharts-container/client/config.highcharts.json
    at Builder.write (/tools/isobuild/builder.js:251:13)
    at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:382:10)
    at /tools/isobuild/isopack.js:1400:27
    at Array.forEach (native)
    at Function._.each._.forEach (/home/eblis/.meteor/packages/meteor-tool/.1.3.0_3.fc5itk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at _.each.builder.copyDirectory.from (/tools/isobuild/isopack.js:1372:11)
    at Array.forEach (native)
    at Function._.each._.forEach (/home/eblis/.meteor/packages/meteor-tool/.1.3.0_3.fc5itk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack.js:1263:9
    at Isopack._.extend.saveToPath (/tools/isobuild/isopack.js:1641:7)
    at /tools/isobuild/isopack-cache.js:323:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._loadLocalPackage (/tools/isobuild/isopack-cache.js:260:18)
    at /tools/isobuild/isopack-cache.js:194:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:193:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at [object Object]._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:184:20)
    at /tools/isobuild/isopack-cache.js:75:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/eblis/.meteor/packages/meteor-tool/.1.3.0_3.fc5itk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at [object Object].buildLocalPackages (/tools/isobuild/isopack-cache.js:74:24)
    at /tools/project-context.js:758:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:757:18)
    at /tools/project-context.js:278:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:268:18)
    at /tools/project-context.js:260:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:259:13)
    at /tools/cli/commands-packages.js:2139:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:279:29)
    at Command.main.registerCommand.name [as func] (/tools/cli/commands-packages.js:2138:8)
    at /tools/cli/main.js:1408:23

**Comment by grtsvetkov** [comment]
same error,
meteor --version
Meteor 1.3.1

=> Started proxy.
=> Started MongoDB.

C:\Users\rim\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
Error: Builder can not write without either data or a file path or a symlink path: web.browser/packages/highcharts-container/client/config.highcharts.json
    at Builder.write (C:\tools\isobuild\builder.js:251:13)
    at Builder.writeToGeneratedFilename (C:\tools\isobuild\builder.js:382:10)
    at C:\tools\isobuild\isopack.js:1394:21
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\rim\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at _.each.builder.copyDirectory.from (C:\tools\isobuild\isopack.js:1387:11)
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\rim\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:1268:9
    at Isopack._.extend.saveToPath (C:\tools\isobuild\isopack.js:1667:7)
    at C:\tools\isobuild\isopack-cache.js:374:23
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:311:18)
    at C:\tools\isobuild\isopack-cache.js:245:16
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at C:\tools\isobuild\isopack-cache.js:244:17
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:235:20)
    at C:\tools\isobuild\isopack-cache.js:76:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\rim\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object].eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:75:24)
    at C:\tools\project-context.js:758:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (C:\tools\project-context.js:757:18)
    at C:\tools\project-context.js:278:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:268:18)
    at C:\tools\project-context.js:260:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:259:13)
    at C:\tools\runners\run-app.js:557:29
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundleApp (C:\tools\runners\run-app.js:556:31)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:634:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)
    at C:\tools\runners\run-app.js:411:12

**Comment by oliverlloyd** [comment]
The solution here is to add the highcharts package via Npm. See [this issue](https://github.com/highcharts/highcharts-meteor/issues/1#issuecomment-204320465).
