### ISSUE TITLE
Meteor error with windows 8.1: your application has errors. waiting for file change 

### ISSUE THREAD

**Issue by dinesh-1992** [meteor/meteor#6634]
Hi
I am trying to create & rum meteor app on win 8.1 pc
what I done,I install meteor using official Meteor installer
 I run following commands at desired path

```
meteor create myapp
```

this was ok
then `cd myapp`
this was also ok

but when I run command meteor to run the app, I got following result with error 

```
[[[[[ ~\F\meteor\resolutions ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading plugin `compileTemplatesBatch` from packag
   module.js:338:15: Cannot find module
   '../modules/es6.object.get-own-property-descriptor'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (C:\Users\Dinesh
   Singh\AppData\Local\.meteor\packages\templating\1.1.7\pl
Batch.os\npm\node_modules\meteor\ecmascript-runtime\node_mo
pt-runtime\node_modules\meteor-ecmascript-runtime\node_modu
t.js:12:1)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (C:\Users\Dinesh
   Singh\AppData\Local\.meteor\packages\templating\1.1.7\pl
Batch.os\npm\node_modules\meteor\ecmascript-runtime\node_mo
pt-runtime\node_modules\meteor-ecmascript-runtime\server.js
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at npmRequire (C:\tools\isobuild\bundler.js:1665:14)
   at Module.useNode (packages/modules-runtime.js:453:20)
   at fileEvaluate (packages/modules-runtime.js:157:20)
   at require (packages/modules-runtime.js:92:16)
   at meteorInstall.node_modules.meteor.ecmascript-runtime.
   (packages/ecmascript-runtime.js:24:18)
   at fileEvaluate (packages/modules-runtime.js:158:9)
   at require (packages/modules-runtime.js:92:16)
   at packages/ecmascript-runtime.js:2832:15
   at packages/ecmascript-runtime.js:2845:3


=> Your application has errors. Waiting for file change.
```

I search over the but didn't find specific result for windows 

Thanks in advance for help

**Comment by abernix** [comment]
@dinesh-1992 Try running `meteor npm install` before you run the `meteor` command.  Or maybe, try asking for help on either the [Meteor Forums](https://forums.meteor.com) or StackOverflow?

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)
