### ISSUE TITLE
[1.3] Fresh meteor 1.3 on win7 not runnning

### ISSUE THREAD

**Issue by pwnball** [meteor/meteor#6646]
I upgraded my project to Meteor 1.3, and after updating all the proper packages I could not get meteor 1.3 to run. Then I created a fresh project and after solving the initial issue with the templating, standard-minifier-css and ecmascript, I get this error I posted below. I created a fresh project in webstorm (v 2016.1), but also tried to create the simple-todos example shown here https://www.meteor.com/tutorials/blaze/creating-an-app in CMD. Same result.

Windows 7 btw :) Also I have not installed meteorhacks:npm or any other extra packages whatsoever.

```
http.js:733
      throw new TypeError('The header content contains invalid characters');
            ^
TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (http.js:733:13)
    at new ClientRequest (http.js:1429:14)
    at Object.exports.request (http.js:1899:10)
    at Array.stream [as 3] (C:\Users\Lightspeed\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\http-proxy\lib\http-proxy\passes\web-inc
oming.js:108:74)
    at ProxyServer.<anonymous> (C:\Users\Lightspeed\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\http-proxy\lib\http-proxy\index.js:8
0:21)
    at Proxy._tryHandleConnections (C:\tools\runners\run-proxy.js:182:20)
    at Server.<anonymous> (C:\tools\runners\run-proxy.js:50:12)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2164:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:152:23)
    at Socket.socket.ondata (http.js:2022:22)
    at TCP.onread (net.js:528:27)

```

Meteor does startup properly and does not crash until I actually navigate to localhost:3000. The page immediately errors (host not reachable) and meteor crashes with the error shown in my OP.

**Comment by pwnball** [comment]
Something I forgot to mention:
Meteor does startup properly and does not crash until I actually navigate to localhost:3000. The page immediately errors (host not reachable) and meteor crashes with the error shown in my OP.

**Comment by scheung38** [comment]
So 1.3 seems to be crashing for the whole community but nothing has been done to fix it since ?

**Comment by avalanche1** [comment]
I guess they ARE doing smth... but they could at least keep us posted.

**Comment by jackkav** [comment]
How did you fix this?

**Comment by pwnball** [comment]
@jackkav In all honesty.. I gave up on it. I reverted my codebase to meteor 1.2. If you find a solution to the problem, I would love to hear it. Also would love to hear how you found one, as Ive spend quite a bit of time on it. 
I am rather inexperienced in debugging external factors that fall outside the codebase I'm working on, so dont let my failed attempt demotivate you to do your own investigation.

**Comment by jackkav** [comment]
Seems like updating Windows is worth a try.

**Comment by pwnball** [comment]
@jackkav funny you say that, I just upgraded today yesterday :p 
I'll check monday if it works :)

**Comment by WooGenius** [comment]
@pwnball I think It's okay when we run meteor on server. It seems only broken when we run meteor on local
