### ISSUE TITLE
[1.3] TypeError

### ISSUE THREAD

**Issue by howna13** [meteor/meteor#6648]
After updating to meteor 1.3 I got the following error:
```
TypeError: Cannot call method 'displayName' of undefined
  at SourceProcessorSet.addLegacyHandler (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\build-plugin.js:151:84)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\build-plugin.js:187:14
  at Function._.each._.forEach (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
  at SourceProcessorSet.merge (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\build-plugin.js:181:7)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\compiler.js:377:26
  at Array.forEach (native)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\compiler.js:373:26
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:367:18
  at [object Object].withValue (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:107:14)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:360:34
  at [object Object].withValue (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:107:14)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:358:23
  at [object Object].withValue (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:107:14)
  at Object.enterJob (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:332:26)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\compiler.js:370:16
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\compiler.js:175:26
  at Array.forEach (native)
  at Function._.each._.forEach (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
  at Object.compile (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\compiler.js:170:5)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\bundler.js:2601:24
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:279:13
  at [object Object].withValue (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:107:14)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:272:29
  at [object Object].withValue (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:107:14)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:270:18
  at [object Object].withValue (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:107:14)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:261:23
  at [object Object].withValue (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\fiber-helpers.js:107:14)
  at Object.capture (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\utils\buildmessage.js:260:19)
  at Object.exports.bundle (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\isobuild\bundler.js:2546:31)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\runners\run-app.js:651:36
  at Function.run (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\tool-env\profile.js:485:12)
  at bundleApp (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\runners\run-app.js:641:34)
  at AppRunner._runOnce (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\runners\run-app.js:694:35)
  at AppRunner._fiber (C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\runners\run-app.js:957:28)
  at C:\Users\howna13\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\tools\runners\run-app.js:472:12
```

**Comment by stubailo** [comment]
Hi, we need more information to reproduce this issue. What packages are you using in your app? Is it possible for you to create a repository with an app we can run that demonstrates this?

**Comment by remipichon** [comment]
Do you have the babel package ?
```
grigio:babel
```

Try to remove it, it is no longer needed as 1.3 brings ES2015 support

**Comment by howna13** [comment]
It was a rushy work to be done. So, unfortunately I had to change to another framework to get it done on time. You can delete the issue. Thank for the interest and I hope meteor gets more stable with the time. Best wishes.
