### ISSUE TITLE
build error after upgrading to 1.3.1

### ISSUE THREAD

**Issue by Jerret321** [meteor/meteor#6650]
```
NodeJS 4.2.5
```

When I upgrade Meteor 1.3.1 and build the meteor app, some error occur. 
The log below:
```bash
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at bindings (/var/www/hexpm-build/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/var/www/hexpm-build/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by cyclops24** [comment]
@Jerret321 meteor 1.3.1 ?? NodeJS 4.2.5 ??

**Comment by Jerret321** [comment]
@cyclops24  yes, I upgrade meteor 1.3.1 in our application with NodeJS 4.2.5. The error logs is below. 
When I use NodeJS 0.10.41, everything is ok. But I think the stable Node is good for development
