### ISSUE TITLE
Meteor 1.3 - Installation issue (with Templating) in Windows

### ISSUE THREAD

**Issue by sri-p** [meteor/meteor#6669]
Currently

$ meteor --version
Meteor 1.3

Running:
Today I started Installing Meteor 1.3 from the meteor.com website. Once after the installation is complete tried to run meteor and then getting the below error.

   While loading plugin `compileTemplatesBatch` from package `templating`:
   module.js:338:15: Cannot find module
   '../modules/es6.object.get-own-property-descriptor'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\spendyala5\AppData\Local\.meteor\packages\templating\1.1.7\plugin.c
ompileTemplatesBatch.os\npm\node_modules\meteor\ecmascript-runtime\node_modules\
meteor\ecmascript-runtime\node_modules\meteor-ecmascript-runtime\node_modules\co
re-js\es6\object.js:12:1)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\spendyala5\AppData\Local\.meteor\packages\templating\1.1.7\plugin.c
ompileTemplatesBatch.os\npm\node_modules\meteor\ecmascript-runtime\node_modules\
meteor\ecmascript-runtime\node_modules\meteor-ecmascript-runtime\server.js:1:1)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at npmRequire (C:\tools\isobuild\bundler.js:1665:14)
   at Module.useNode (packages/modules-runtime.js:453:20)
   at fileEvaluate (packages/modules-runtime.js:157:20)
   at require (packages/modules-runtime.js:92:16)
   at meteorInstall.node_modules.meteor.ecmascript-runtime.runtime.js
   (packages/ecmascript-runtime.js:24:18)
   at fileEvaluate (packages/modules-runtime.js:158:9)
   at require (packages/modules-runtime.js:92:16)
   at packages/ecmascript-runtime.js:2832:15
   at packages/ecmascript-runtime.js:2845:3

=> Your application has errors. Waiting for file change.

Is there a way I can make it work. This is the first time me installing Meteor app.

**Comment by gtdudu** [comment]
#6609

**Comment by zayaisshawn** [comment]
Hey any fix for this?

**Comment by benjamn** [comment]
Fixed (like #6609) if you do `meteor update --release 1.3.1`.
