### ISSUE TITLE
Can't deploy on Meteor 1.3

### ISSUE THREAD

**Issue by hyperh** [meteor/meteor#6714]
Getting the following errors when trying to deploy from OSX to Ubuntu. This was all working fine for me on Meteor 1.3-beta-4. I'm using mup to deploy to a Digital Ocean droplet.

```
[139.59.224.193]     at require (module.js:380:17)
    at bindings (/opt/test-draftjs/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/test-draftjs/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
error: Script restart attempt #4

/opt/test-draftjs/app/programs/server/node_modules/fibers/future.js:267
						throw(ex);
						      ^
Error: /opt/test-draftjs/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/opt/test-draftjs/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/test-draftjs/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
error: Script restart attempt #5

/opt/test-draftjs/app/programs/server/node_modules/fibers/future.js:267
						throw(ex);
						      ^
Error: Can't find npm module 'bcrypt'. Did you forget to call 'Npm.depends' in package.js within the 'npm-bcrypt' package?
    at Object.Npm.require (/opt/test-draftjs/app/programs/server/boot.js:195:17)
    at Package (packages/npm-bcrypt.js:27:23)
    at Package (packages/npm-bcrypt.js:31:4)
    at packages/npm-bcrypt.js:35:4
    at packages/npm-bcrypt.js:47:3
    at /opt/test-draftjs/app/programs/server/boot.js:283:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/test-draftjs/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/test-draftjs/app/programs/server/boot.js:133:5
error: Forever detected script exited with code: 8
error: Script restart attempt #6

module.js:340
    throw err;
```

I also tried out Modulus, but I got this error.

```
Errors prevented bundling:
While linking the program:
error: this app is not compatible with architecture 'os.linux.x86_64'
```

**Comment by felixb101** [comment]
Same here going from Mac OS to Debian 8 Jessie...

**Comment by aldeed** [comment]
You should post your package list. One of the packages has a binary dep and did not get published for all 4 architectures.

**Comment by hyperh** [comment]
My package list is as follows: 

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

kadira:flow-router
reactive-dict
check
random
accounts-base
accounts-ui
accounts-password

meteortoys:allthings

meteorhacks:subs-manager
kadira:debug
```

**Comment by mlecoq** [comment]
Any news ?

**Comment by mlecoq** [comment]
\ o /    Newer versions of the following indirect dependencies are available:
 * npm-bcrypt 0.7.8_2 (0.8.5 is available)

**Comment by akinnee** [comment]
On OSX, after updating to 1.3 today:
```
W20160410-17:39:51.914(-4)? (STDERR) /Users/<me>/.meteor/packages/meteor-tool/.1.3.1.1n5jjvk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160410-17:39:51.914(-4)? (STDERR) 						throw(ex);
W20160410-17:39:51.914(-4)? (STDERR) 						      ^
W20160410-17:39:51.915(-4)? (STDERR) TypeError: Cannot set property 'Anchor' of undefined
W20160410-17:39:51.915(-4)? (STDERR)     at meteorInstall.lib.anchor.js (/Users/<me>/repos/<company>/<app>/.meteor/local/build/programs/server/app/app.js:181:13)
W20160410-17:39:51.915(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160410-17:39:51.916(-4)? (STDERR)     at require (packages/modules-runtime.js:92:16)
W20160410-17:39:51.916(-4)? (STDERR)     at /Users/<me>/repos/<company>/<app>/.meteor/local/build/programs/server/app/app.js:453:1
W20160410-17:39:51.916(-4)? (STDERR)     at /Users/<me>/repos/<company>/<app>/.meteor/local/build/programs/server/boot.js:283:10
W20160410-17:39:51.916(-4)? (STDERR)     at Array.forEach (native)
W20160410-17:39:51.916(-4)? (STDERR)     at Function._.each._.forEach (/Users/<me>/.meteor/packages/meteor-tool/.1.3.1.1n5jjvk++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160410-17:39:51.916(-4)? (STDERR)     at /Users/<me>/repos/<company>/<app>/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```
Package list:
```
meteor-base             
mobile-experience       
mongo                   
blaze-html-templates    
session                 
jquery                  
tracker                 

es5-shim                
ecmascript              

maxkfranz:cytoscape
infinitedg:winston
accounts-base
accounts-facebook
accounts-ui
mdg:geolocation
matb33:collection-hooks
dburles:google-maps
sanjo:jasmine
velocity:console-reporter
less
huttonr:bootstrap3
kadira:flow-router
momentjs:moment
rajit:bootstrap3-datepicker
standard-minifier-css
standard-minifier-js
```

**Comment by hyperh** [comment]
I finally got this working. Try Meteor 1.3.2-rc.5. These are the steps that worked for me.

1. Delete `node_modules`
2. Delete `.meteor/local`
3. `meteor update --release METEOR@1.3.2-rc.5`
4. Create a new Digital Ocean droplet
5. `mupx setup`
6. `mupx deploy`

**Comment by mlecoq** [comment]
works for me also (with a manual build)

**Comment by erperejildo** [comment]
I'm using 1.3.5.1 and still having this issue.
I'm deploying against Modulus.

**Comment by tomtom87** [comment]
This is broken since deployment, none of MDG have taken interest in deployment outside of their own financial horizon. Very sad indeed. The problem is the node version is out of date in the docker image. There is an unofficial newer one kicking about, I couldn't get it working. You need to look in the issues on mup for more info...

**Comment by erperejildo** [comment]
@tomtom87 but I'm not using mup to deploy:
https://help.modulus.io/customer/portal/articles/1647770-using-meteor-with-modulus
I'm finishing my first Meteor app and is a pain in... my back to find a proper hosting to work with and deploy against it.
This should be definitely easier (or at least it should work).

**Comment by tomtom87** [comment]
Ok... meteor 1.3 is working fine in mupx. like a dream its so nice i have it runnin on DO droplet $5 a month and a AWS one also.. but they broke it in 1.4 cos they really shit and dont care and now dont give any fix probably cos they think it will make people pay for galaxy. Good luck with ur app. dont expect help from meteor group this has been goin on for ages now. peace

**Comment by erperejildo** [comment]
Yes, I was thinking to contract with DO as well. Galaxy looks better maybe but it's more expensive and I'd prefer to try something cheaper first.
I'm still developing my app and I found Modulus to work with for a while, because they give you $15 (no credit card verification like Heroku) and you can try your app on a real environment. Or at least is what I thought. I'm going to speak with them about this and if they can solve this issue I'll comment it here.

**Comment by erperejildo** [comment]
Check Modulus out. Really easy to work with and they give you $15 to waste hosting yours apps

**Comment by tanermelikoglu** [comment]
Works for me with only the steps 2, 5 and 6 @hyperh. I have the version 1.3.2.4
