### ISSUE TITLE
[1.3.1] TypeError: Cannot call method 'substr' of undefined

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#6722]
i try import something into js file like this:

`import '/imports/styles/misc.scss';`

and this error, program break.

```
C:\Users\lyquo\AppData\Local\.meteor\packages\templating\1.1.8\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promis
      throw error;                                                                                                                                       
            ^                                                                                                                                            
TypeError: Cannot call method 'substr' of undefined                                                                                                      
    at Function.<anonymous> (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\source-map\
    at Array.forEach (native)                                                                                                                            
    at SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\li
map-consumer.js:155:16)                                                                                                                                  
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.wi
les\source-map\lib\source-node.js:80:26)                                                                                                                 
    at File._.extend.getPrelinkedOutput (C:\tools\isobuild\linker.js:700:42)                                                                             
    at walk (C:\tools\isobuild\linker.js:272:23)                                                                                                         
    at C:\tools\isobuild\linker.js:281:11                                                                                                                
    at Array.forEach (native)                                                                                                                            
    at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\unders
    at C:\tools\isobuild\linker.js:279:11                                                                                                                
    at walk (C:\tools\isobuild\linker.js:286:9)                                                                                                          
    at C:\tools\isobuild\linker.js:281:11                                                                                                                
    at Array.forEach (native)                                                                                                                            
    at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\unders
    at C:\tools\isobuild\linker.js:279:11                                                                                                                
    at walk (C:\tools\isobuild\linker.js:286:9)                                                                                                          
    at C:\tools\isobuild\linker.js:281:11                                                                                                                
    at Array.forEach (native)                                                                                                                            
    at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\unders
    at C:\tools\isobuild\linker.js:279:11                                                                                                                
    at walk (C:\tools\isobuild\linker.js:286:9)                                                                                                          
    at Module._chunkifyModuleTree (C:\tools\isobuild\linker.js:295:5)                                                                                    
    at Module._.extend.getPrelinkedFiles (C:\tools\isobuild\linker.js:171:24)                                                                            
    at Object.fullLink (C:\tools\isobuild\linker.js:978:31)                                                                                              
    at C:\tools\isobuild\compiler-plugin.js:1108:28                                                                                                      
    at C:\tools\utils\buildmessage.js:359:18                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at C:\tools\utils\buildmessage.js:352:34                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at C:\tools\utils\buildmessage.js:350:23                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)                                                                                           
    at PackageSourceBatch._linkJS (C:\tools\isobuild\compiler-plugin.js:1107:18)                                                                         
    at PackageSourceBatch.getResources (C:\tools\isobuild\compiler-plugin.js:999:28)                                                                     
    at C:\tools\isobuild\bundler.js:934:37                                                                                                               
    at Array.forEach (native)                                                                                                                            
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:916:19)                                                                                 
    at C:\tools\isobuild\bundler.js:680:12                                                                                                               
    at C:\tools\utils\buildmessage.js:359:18                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at C:\tools\utils\buildmessage.js:352:34                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at C:\tools\utils\buildmessage.js:350:23                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)                                                                                           
    at ClientTarget.make (C:\tools\isobuild\bundler.js:671:18)                                                                                           
    at C:\tools\isobuild\bundler.js:2512:14                                                                                                              
    at C:\tools\isobuild\bundler.js:2602:20                                                                                                              
    at Array.forEach (native)                                                                                                                            
    at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\unders
    at C:\tools\isobuild\bundler.js:2601:7                                                                                                               
    at C:\tools\utils\buildmessage.js:271:13                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at C:\tools\utils\buildmessage.js:264:29                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at C:\tools\utils\buildmessage.js:262:18                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at C:\tools\utils\buildmessage.js:253:23                                                                                                             
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)                                                                                 
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)                                                                                            
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2493:31)                                                                                      
    at C:\tools\runners\run-app.js:591:36                                                                                                                
    at Function.run (C:\tools\tool-env\profile.js:489:12)                                                                                                
    at bundleApp (C:\tools\runners\run-app.js:581:34)                                                                                                    
    at AppRunner._runOnce (C:\tools\runners\run-app.js:831:35)                                                                                           
    at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)                                                                                             
    at C:\tools\runners\run-app.js:411:12                                                                                                                
```

**Comment by skirunman** [comment]
I think you have to use import format of `@import "{}/imports/styles/misc.scss"` for styles files as per Meteor Guide [here](http://guide.meteor.com/v1.3/build-tool.html#css-importing-from-package.)

**Comment by lyquocnam** [comment]
thanks @skirunman that a good way or we can move file to client folder ( outside imports folder ) it will load auto.
but i think this can not be throw error with missing 'substr' method.
may this need to be fixed.

**Comment by stubailo** [comment]
Yeah, this should definitely throw a better error.

**Comment by webbower** [comment]
I just ran into this issue as well. It would spring up when I was editing a non-LESS file. Then, because of what @skirunman said, I'd comment out a new-ish block of LESS in a LESS file that is only 6 lines and it would behave. Then I'd try uncommenting the LESS and it would continue working. Then I'd edit a non-LESS file and it would suddenly crash with this stacktrace again (I got the same one as pasted in the OP). The most frustrating part is that the stacktrace makes no mention of any file in the app code so that I would know which file tripped the bug.

@gaurav-

**Comment by ubald** [comment]
I just updated a working app to 1.3.2.4 and I have the same error on startup.

**Comment by abernix** [comment]
Can anyone confirm if this problem goes away if you upgrade to Meteor 1.3.4.4?  You can try with this command and I'd recommend moving toward if you are using 1.3.2.4:

   meteor update --release 1.3.4.4

If you still have problems, please let us know which plugins you are using for SCSS compilation!

**Comment by ubald** [comment]
I don't have this problem anymore.

**Comment by abernix** [comment]
Closing this issue because I believe it has been resolved, but please feel free to @mention me if you think it should be reopened or needs further discussion!
