### ISSUE TITLE
less error during ImportScanner._resolveNodeModule

### ISSUE THREAD

**Issue by lorensr** [meteor/meteor#6724]
***6 Upvotes*** Full output below. Meteor 1.3.1.

1. Looks like the `less` package: `/Users/me/.meteor/packages/less`
1. When I remove `modules` package, I get a different error, and it looks like it's unrelated and further in the build process – `ReferenceError: require is not defined`, `=> Exited with code: 8`, and restart loop, versus the below, which is a hard exit.
1. Error does not occur with a blank app, `less`, `modules`, and a `foo.less` file.
1. `at ImportScanner._resolveNodeModule (/tools/isobuild/import-scanner.js:727:9)`, which at the 1.3.1 release is: https://github.com/meteor/meteor/blob/release-1.3.1/tools/isobuild/import-scanner.js#L727

`has(file.deps, id)`
You get this error when `deps` isn't a field of `file`:
```
> _.has({foo:1}.deps,'bar')
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at Function._.has (packages/underscore.js:1106:27)
```

```
> meteor
[[[[[ ~/parlay ]]]]]                          

=> Started proxy.                             
=> Started MongoDB.                           
                                              
/Users/me/.meteor/packages/less/.2.5.7.1c9bnxi++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at _.has (/Users/me/.meteor/packages/meteor-tool/.1.3.1.1dp3ty6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:1046:27)
    at ImportScanner._resolveNodeModule (/tools/isobuild/import-scanner.js:727:9)
    at ImportScanner._tryToResolveImportedPath (/tools/isobuild/import-scanner.js:565:12)
    at ImportScanner._resolvePkgJsonMain (/tools/isobuild/import-scanner.js:812:14)
    at ImportScanner._tryToResolveImportedPath (/tools/isobuild/import-scanner.js:576:25)
    at /tools/isobuild/import-scanner.js:333:29
    at _.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.3.1.1dp3ty6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:332:5)
    at /tools/isobuild/import-scanner.js:194:14
    at Array.forEach (native)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:192:22)
    at /tools/isobuild/compiler-plugin.js:791:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:759:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:680:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:671:18)
    at /tools/isobuild/bundler.js:2512:14
    at /tools/isobuild/bundler.js:2602:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.3.1.1dp3ty6++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2601:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2493:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

cc @benjamn

**Comment by jamesabbottsmith** [comment]
+1

**Comment by TeemoWan** [comment]
+1

**Comment by paul-bo** [comment]
+1

**Comment by vbelolapotkov** [comment]
+1

**Comment by mmaguire400** [comment]
+1

**Comment by the-phunk** [comment]
+1

**Comment by benjamn** [comment]
To all of you leaving "+1" comments, try `meteor update --release 1.3.1-rc.4` if you want to help confirm that this is fixed.

**Comment by area** [comment]
@benjamn I assume you have a typo and mean `meteor update --release 1.3.2-rc.4`

**Comment by benjamn** [comment]
fixed, thanks :)

**Comment by jlichti** [comment]
Issue was fixed for me in this release. Thanks.

**Comment by lorensr** [comment]
Confirmed, thank you 😃 Should I close, or does it auto-close when merged?
