### ISSUE TITLE
[1.3.1] react-data-grid causes error in templating

### ISSUE THREAD

**Issue by zksailor534** [meteor/meteor#6741]
Tried to use react-data-grid in Meteor 1.3.1 with simple configuration (began with Meteor-React tutorial and replaced App.jsx with Datagrid.jsx populated with code from http://adazzle.github.io/react-data-grid/examples.html#/basic and translated to ES2015).  Three files for application are attached.
[main_html.txt](https://github.com/meteor/meteor/files/208445/main_html.txt)
[main_jsx.txt](https://github.com/meteor/meteor/files/208444/main_jsx.txt)
[datagrid_jsx.txt](https://github.com/meteor/meteor/files/208446/datagrid_jsx.txt)

Also tried importing react-data-grid with simple nodejs application (react-example-es2015) and was successful.

C:\...\AppData\Local\.meteor\packages\templating\1.1.8\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at _.has (C:\...\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:1046:27)
    at ImportScanner._resolveNodeModule (C:\tools\isobuild\import-scanner.js:727:9)
    at ImportScanner._tryToResolveImportedPath (C:\tools\isobuild\import-scanner.js:565:12)
    at ImportScanner._resolvePkgJsonMain (C:\tools\isobuild\import-scanner.js:812:14)
    at ImportScanner._tryToResolveImportedPath (C:\tools\isobuild\import-scanner.js:576:25)
    at C:\tools\isobuild\import-scanner.js:333:29
    at _.each._.forEach (C:\...\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:332:5)
    at C:\tools\isobuild\import-scanner.js:364:18
    at _.each._.forEach (C:\...\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:332:5)
    at C:\tools\isobuild\import-scanner.js:194:14
    at Array.forEach (native)
    at ImportScanner.scanImports (C:\tools\isobuild\import-scanner.js:192:22)
    at C:\tools\isobuild\compiler-plugin.js:791:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:759:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:913:8)
    at C:\tools\isobuild\bundler.js:680:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:671:18)
    at C:\tools\isobuild\bundler.js:2512:14
    at C:\tools\isobuild\bundler.js:2602:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\...\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2601:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2493:31)
    at C:\tools\runners\run-app.js:591:36
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at bundleApp (C:\tools\runners\run-app.js:581:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:634:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)
    at C:\tools\runners\run-app.js:411:12

**Comment by zeroasterisk** [comment]
I'm getting the same bug `TypeError: Cannot convert null to object` when importing a `npm` package [react-sidenav](https://github.com/wmira/react-sidenav)

```
Local package version is up-to-date: zeroasterisk:s-enum@1.0.3
Doing HTTP request:  POST
https://www.meteor.com/oauth2/authorize?state=12cf8ded64fd81ec810d13b675da1fc3&response_type=code&client_id=LdpZEt7ubqXAfkDJ2&redirect_uri=https%3A%2F%2Factivity.meteor.com%2F_oauth%2Fmeteor-developer%3Fclose

/Users/alan/.meteor/packages/coffeescript/.1.0.16.14uglvs++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at _.has (/Users/alan/.meteor/packages/meteor-tool/.1.3.1.6u43i0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:1046:27)
    at ImportScanner._resolveNodeModule (/tools/isobuild/import-scanner.js:727:9)
    at ImportScanner._tryToResolveImportedPath (/tools/isobuild/import-scanner.js:565:12)
    at ImportScanner._resolvePkgJsonMain (/tools/isobuild/import-scanner.js:812:14)
    at ImportScanner._tryToResolveImportedPath (/tools/isobuild/import-scanner.js:576:25)
    at /tools/isobuild/import-scanner.js:333:29
    at _.each._.forEach (/Users/alan/.meteor/packages/meteor-tool/.1.3.1.6u43i0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
```

When I remove the `node_module` meteor prompts me to npm install it, all good.

I re-install it, Meteor tries to start, and gives that error.

I have meteor 1.3.1, npm 2.14.7, node v4.2.1 on OSX

**Comment by threefoldo** [comment]
Got the same error with react-data-grid. The test code is OK with react-storybook.

**Comment by abernix** [comment]
Unfortunately, this problem is too vague to tell if there is a bug in Meteor or a misconfiguration.  Please try a newer version of Meteor and see if this problem still exists.  If it does, please re-open this issue by providing a reproduction repo that demonstrates this problem using the minimum possible configuration (minimum files, code, etc.).

See [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) for more requirements on opening an Issue.

Closing, but happy to reopen with the appropriate reproduction repo and steps.
