### ISSUE TITLE
[1.3.2.rc.0] AssertionError: "node_modules1" === "node_modules" when generating bundle

### ISSUE THREAD

**Issue by gbhrdt** [meteor/meteor#6765]
If I try to bundle my application for deployment, this is what happens.

	Building App Bundle Locally

	AssertionError: "node_modules1" === "node_modules"
	    at Object.meteorNpm.dependenciesArePortable (/tools/isobuild/meteor-npm.js:130:10)
	    at NodeModulesDirectory.isPortable (/tools/isobuild/bundler.js:259:22)
	    at /tools/isobuild/bundler.js:1830:17
	    at Function._.each._.forEach (/Users/marius/.meteor/packages/meteor-tool/.1.3.2-rc.0.3sag6n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
	    at JsImage.write (/tools/isobuild/bundler.js:1827:7)
	    at ServerTarget.write (/tools/isobuild/bundler.js:2063:13)
	    at /tools/isobuild/bundler.js:2147:30
	    at Object.keys.forEach.subBuilder (/tools/isobuild/bundler.js:2275:9)
	    at Array.forEach (native)
	    at /tools/isobuild/bundler.js:2265:26
	    at /tools/isobuild/bundler.js:2308:5
	    at /tools/isobuild/bundler.js:2606:22
	    at /tools/utils/buildmessage.js:271:13
	    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
	    at /tools/utils/buildmessage.js:264:29
	    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
	    at /tools/utils/buildmessage.js:262:18
	    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
	    at /tools/utils/buildmessage.js:253:23
	    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
	    at Object.capture (/tools/utils/buildmessage.js:252:19)
	    at Object.exports.bundle (/tools/isobuild/bundler.js:2441:31)
	    at buildCommand (/tools/cli/commands.js:909:30)
	    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:789:12)
	    at /tools/cli/main.js:1402:23

	=> Build Error. Check the logs printed above.
	Error: build-error
	    at ChildProcess.<anonymous> (build.js:20:18)
	    at emitTwo (events.js:100:13)
	    at ChildProcess.emit (events.js:185:7)
	    at maybeClose (internal/child_process.js:821:16)
	    at Socket.<anonymous> (internal/child_process.js:319:11)
	    at emitOne (events.js:90:13)
	    at Socket.emit (events.js:182:7)
	    at Pipe._onclose (net.js:469:12)

These are my npm dependencies (They do not include any binaries):

    "body-parser": "1.15.0",
    "indexof": "0.0.1",
    "meteor-node-stubs": "^0.2.1",
    "moment": "^2.12.0",
    "paymill-wrapper": "2.2.0",
    "rc-slider": "^3.5.1",
    "react": "^0.14.8",
    "react-addons-create-fragment": "^0.14.8",
    "react-addons-css-transition-group": "^0.14.8",
    "react-addons-linked-state-mixin": "^0.14.8",
    "react-addons-perf": "^0.14.8",
    "react-addons-pure-render-mixin": "^0.14.8",
    "react-addons-test-utils": "^0.14.8",
    "react-addons-transition-group": "^0.14.8",
    "react-addons-update": "^0.14.8",
    "react-datetime": "^2.1.0",
    "react-dom": "^0.14.8",
    "react-mounter": "^1.1.0",
    "web-push-meteor": "^2.0.0"

This is probably for @benjamn

**Comment by bensventures** [comment]
I am getting a similar error with `1.3.2-rc.0` when trying to deploy (with mupx). 1.3.1 was not showing this. I am using `node_modules` with binaries, notably `node_sass` and probably others.

```
AssertionError: false === true
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:189:12)
    at /tools/isobuild/import-scanner.js:176:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:147:11)
    at /tools/isobuild/compiler-plugin.js:825:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:796:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:899:8)
    at /tools/isobuild/bundler.js:670:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:661:18)
    at /tools/isobuild/bundler.js:2460:14
    at /tools/isobuild/bundler.js:2549:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Ben/.meteor/packages/meteor-tool/.1.3.2-rc.0.36waaf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2548:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2441:31)
    at buildCommand (/tools/cli/commands.js:909:30)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:789:12)
    at /tools/cli/main.js:1402:23
```
running the app works though.

**Comment by benjamn** [comment]
These look like different stack traces to me…

**Comment by benjamn** [comment]
@gbhrdt if you run this command in your app directory, do you get any results?
```sh
find . | grep node_modules1
```

**Comment by gbhrdt** [comment]
@benjamn nope, no results.

**Comment by gbhrdt** [comment]
I just searched for node_modules1 in `~` and that's what I got:

	$ find . | grep node_modules1
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/.node_version
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/.npmignore
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/.travis.yml
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/bcrypt.js
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/binding.gyp
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/bcrypt_lib.target.mk
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/binding.Makefile
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/config.gypi
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Makefile
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release/bcrypt_lib.node.d
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release/obj.target
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release/obj.target/bcrypt_lib
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release/obj.target/bcrypt_lib/src
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt.o.d
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt_node.o.d
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/.deps/Release/obj.target/bcrypt_lib.node.d
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/bcrypt_lib.node
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/linker.lock
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/obj.target
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/obj.target/bcrypt_lib
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/obj.target/bcrypt_lib/src
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/obj.target/bcrypt_lib/src/bcrypt.o
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/obj.target/bcrypt_lib/src/bcrypt_node.o
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/obj.target/bcrypt_lib/src/blowfish.o
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/build/Release/obj.target/bcrypt_lib.node
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/CHANGELOG
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/examples
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/examples/async_compare.js
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/examples/forever_gen_salt.js
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/LICENSE
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/Makefile
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/node_modules
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/node_modules/bindings
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/node_modules/bindings/bindings.js
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/node_modules/bindings/package.json
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/node_modules/bindings/README.md
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/package.json
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/README.md
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/src
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/src/bcrypt.cc
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/src/bcrypt_node.cc
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/src/blowfish.cc
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/src/node_blf.h
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/test
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/test/async.js
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/test/repetitions.js
	./.meteor/packages/npm-bcrypt/.0.7.8_2.it64yc++os.linux.x86_64+os.osx.x86_64+web.browser+web.cordova/npm/node_modules1/bcrypt/test/sync.js

**Comment by benjamn** [comment]
What if you remove the whole `~/.meteor/packages/npm-bcrypt` directory?

If that doesn't work, then we probably need to publish a fresh version of that package.

You can also `meteor npm install bcrypt` now and use that instead of using the Meteor wrapper package, for what it's worth.

**Comment by benjamn** [comment]
Another quick way to fix this:
```sh
meteor remove npm-bcrypt
meteor add npm-bcrypt
```
This will install the latest version, 0.8.5, which I just published.

**Comment by gbhrdt** [comment]
Thanks, but it won't let me install the new version:

	$ meteor add npm-bcrypt@0.8.5
	 => Errors while adding packages:             
	                                              
	While selecting package versions:
	error: Conflict: Constraint npm-bcrypt@=0.7.8_2 is not satisfied by npm-bcrypt 0.8.5.
	Constraints on package "npm-bcrypt":
	* npm-bcrypt@0.8.5 <- top level
	* npm-bcrypt@=0.7.8_2 <- accounts-password 1.1.8-rc.0

**Comment by lyquocnam** [comment]
problem with `meteor 1.3.2-rc.1` and `npm-bcrypt@0.8.5`

```
AssertionError: "node_modules1" === "node_modules"
    at Object.meteorNpm.dependenciesArePortable (C:\tools\isobuild\meteor-npm.js:130:10)
    at NodeModulesDirectory.isPortable (C:\tools\isobuild\bundler.js:259:22)
    at C:\tools\isobuild\bundler.js:1830:17
    at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.2-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at JsImage.write (C:\tools\isobuild\bundler.js:1827:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2063:13)
    at C:\tools\isobuild\bundler.js:2147:30
    at Object.keys.forEach.subBuilder (C:\tools\isobuild\bundler.js:2275:9)
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2265:26
    at C:\tools\isobuild\bundler.js:2308:5
    at C:\tools\isobuild\bundler.js:2606:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2441:31)
    at buildCommand (C:\tools\cli\commands.js:909:30)
    at Command.main.registerCommand._.extend.name [as func] (C:\tools\cli\commands.js:789:12)
    at C:\tools\cli\main.js:1402:23

=> Build Error. Check the logs printed above.
```

**Comment by gbhrdt** [comment]
Now getting the same error with `1.3.2-rc.2` as @lyquocnam

**Comment by adrianmc** [comment]
@benjamn I also think maybe this should be re-opened.

I am now getting a similar error when trying to deploy **1.3.2-rc.4** to Modulus:

```
/Users/liadrian/.meteor/packages/coffeescript/.1.0.17-rc.4.z6xzao++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: "node_modules1" === "node_modules"
    at Object.meteorNpm.dependenciesArePortable (/tools/isobuild/meteor-npm.js:130:10)
    at NodeModulesDirectory.isPortable (/tools/isobuild/bundler.js:259:22)
    at /tools/isobuild/bundler.js:1830:17
    at Function._.each._.forEach (/Users/liadrian/.meteor/packages/meteor-tool/.1.3.2-rc.4.ftigtb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:1827:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2063:13)
    at /tools/isobuild/bundler.js:2147:30
    at Object.keys.forEach.subBuilder (/tools/isobuild/bundler.js:2275:9)
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2265:26
    at /tools/isobuild/bundler.js:2308:5
    at /tools/isobuild/bundler.js:2606:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2441:31)
    at buildCommand (/tools/cli/commands.js:909:30)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:789:12)
    at /tools/cli/main.js:1402:23
undefined
```

**Comment by lyquocnam** [comment]
meteor 1.3.2-rc.4 mupx error when deploy

**Comment by adrianmc** [comment]
I've tried removing the `~/.meteor/packages/npm-bcrypt` directory as well and it did nothing. I am on `npm-bcrypt@0.8.5`.

**Comment by lyquocnam** [comment]
this happen when run `meteor build bin --architecture=os.linux.x86_64`

**Comment by benjamn** [comment]
I have a reproduction! Yay!

**Comment by benjamn** [comment]
This issue will be officially fixed when Meteor 1.3.2 is released today or tomorrow, but you can test it out by doing `meteor update --release 1.3.2-rc.5` now.

**Comment by gbhrdt** [comment]
Finally works for me now, thank you very much @benjamn ! I'm closing this now.

**Comment by adrianmc** [comment]
Fixed for me too! Thanks a lot @benjamn, I know how hard you've been working these past few days fielding all these issues. Really appreciate it.
