### ISSUE TITLE
[Meteor 1.3.2 rc 2 ] build issue

### ISSUE THREAD

**Issue by mlecoq** [meteor/meteor#6778]
***1 Upvote*** Since building from mac os is not possible in Meteor 1.3 & Meteor 1.3.1 (due to npm bcrypt issue), I have tried Meteor 1.3.2 rc 2. 

Here my issue while building with it:

.meteor/packages/less/.2.5.8-rc.1.1vermpj++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Cannot call method 'load' of undefined
    at /tools/isobuild/bundler.js:1352:20
    at ClientTarget.write (/tools/isobuild/bundler.js:1360:7)
    at /tools/isobuild/bundler.js:2147:30
    at Object.keys.forEach.subBuilder (/tools/isobuild/bundler.js:2275:9)
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2265:26
    at /tools/isobuild/bundler.js:2308:5
    at /tools/isobuild/bundler.js:2606:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)

**Comment by hyperh** [comment]
Same here, 1.3.2 rc 2 doesn't work for me either. I had the same problem as you with the npm-bcrypt thing.

**Comment by mlecoq** [comment]
@hyperh thanks for the tip, I will use 1.3-beta-11 (and hope that everything will be fine)

**Comment by clayne11** [comment]
I'm using `1.3.1` and I've had no issues deploying with `mupx` from a mac.

**Comment by mlecoq** [comment]
@clayne11 I tried mupx. I use Collection FS and GraphicsMagick.  Unfortunately with mupx (based on docker) you cannot add GraphicsMagick (You can find an issue about this topic). 

But I agree with your solution for people whig do not use GraphicsMagick

**Comment by adrianmc** [comment]
@benjamn I see that you seem to have made a commit to fix this issue, but I'm still getting a VERY similar error when trying to deploy **1.3.2-rc.4** to Modulus:

```
/Users/liadrian/.meteor/packages/coffeescript/.1.0.17-rc.4.z6xzao++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: "node_modules1" === "node_modules"
    at Object.meteorNpm.dependenciesArePortable (/tools/isobuild/meteor-npm.js:130:10)
    at NodeModulesDirectory.isPortable (/tools/isobuild/bundler.js:259:22)
    at /tools/isobuild/bundler.js:1830:17
    at Function._.each._.forEach (/Users/liadrian/.meteor/packages/meteor-tool/.1.3.2-rc.4.ftigtb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:1827:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2063:13)
    at /tools/isobuild/bundler.js:2147:30
    at Object.keys.forEach.subBuilder (/tools/isobuild/bundler.js:2275:9)
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2265:26
    at /tools/isobuild/bundler.js:2308:5
    at /tools/isobuild/bundler.js:2606:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2441:31)
    at buildCommand (/tools/cli/commands.js:909:30)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:789:12)
    at /tools/cli/main.js:1402:23
undefined
```

Is this a related problem or a separate one?

**Comment by lyquocnam** [comment]
this still happen with meteor 1.3.2-rc.4, i use passenger and this error on /var/nginx/error.log.
i tried reinstall bcrypt too, but not work !

**Comment by benjamn** [comment]
This issue will be officially fixed when Meteor 1.3.2 is released this Friday, but you can test it out by doing `meteor update --release 1.3.2-rc.5` now.

**Comment by hyperh** [comment]
@benjamn Fantastic! it worked for me, thanks for all your hard work!

Just a note to anyone else trying it out, delete your `node_modules` and `.meteor/local` after updating your meteor and let it rebuild everything.

**Comment by mbateman** [comment]
@mlecoq this is the stack trace I get when using mup deploy with 1.3.2.4:

[178.62.8.181] Error: /opt/ariadne/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[178.62.8.181]
[178.62.8.181]     at Module.load (module.js:356:32)[178.62.8.181]
[178.62.8.181]     at Function.Module._load (module.js:312:12)[178.62.8.181]
[178.62.8.181]     at Module.require (module.js:364:17)[178.62.8.181]
[178.62.8.181]     at require (module.js:380:17)[178.62.8.181]
[178.62.8.181]     at bindings (/opt/ariadne/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)[178.62.8.181]

I think this is quite familiar to anyone deploying from mac os to linux.

Using METEOR@1.3-beta.11 it works fine.

**Comment by lijoantony** [comment]
same error here

**Comment by clayne11** [comment]
Are you using `mup` or `mupx`? The old `mup` hasn't been developed on in a long time and you should switch to `mupx` or possibly even the new `[meteor-up](https://github.com/kadirahq/meteor-up)`

**Comment by lijoantony** [comment]
Just tried mupx. it works!

**Comment by mlecoq** [comment]
@lijoantony @clayne11 @mbateman  I think that It may be a good idea to use docker directly or https://github.com/kadirahq/meteor-up

Docker : 
https://medium.com/@justinkrup/deploying-meteor-with-docker-on-aws-ecs-2a69794a322d#.1z7yma3r6
Meteor Up : 
https://medium.com/@timbrandin/host-your-own-secure-galaxy-with-let-s-encrypt-mongodb-and-meteor-up-mup-b657211d1268#.cjo8xb5nd

**Comment by shahidkarimi** [comment]
Meteor is just a piece of bullshit

**Comment by hwillson** [comment]
@shahidkarimi Sorry you feel that way. Posting comments like this on closed (or open) issues really doesn't help anyone however. If you have a specific issue with Meteor, please consider opening a new issue with your problem.

**Comment by kimseak-dev** [comment]
/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:280
RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:166:12)
    at new Buffer (buffer.js:56:12)
    at Object.fs.readFileSync (fs.js:419:16)
    at wrapper (/tools/fs/files.js:1593:35)
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:23:15)
    at Entry._reallyRecompute (/home/kadmin/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/home/kadmin/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/home/kadmin/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/home/kadmin/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/builder.js:579:13
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at /tools/isobuild/builder.js:556:11
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at /tools/isobuild/builder.js:556:11
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at Builder.copyDirectory (/tools/isobuild/builder.js:594:5)
    at /tools/isobuild/bundler.js:2216:17
    at Function._.each._.forEach (/home/kadmin/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:2175:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2444:13)
    at /tools/isobuild/bundler.js:2563:30
    at /tools/isobuild/bundler.js:2698:9
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2688:26
    at /tools/isobuild/bundler.js:3029:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2862:31)
    at /tools/isobuild/bundler.js:2809:32
    at Object.withCache (/tools/fs/files.js:1693:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2809:16)
    at buildCommand (/tools/cli/commands.js:956:30)
    at Command.func (/tools/cli/commands.js:831:12)
    at /tools/cli/main.js:1483:23
#Meteor 3.1.2
It still not work for me
