### ISSUE TITLE
[1.3.1|1.3] Package build failing for strange reason.

### ISSUE THREAD

**Issue by Zodiase** [meteor/meteor#6788]
To reproduce, try `meteor test-packages ./ --release 1.3.1` (or `meteor test-packages ./ --release 1.3`) in the package which can be cloned from here: https://github.com/Zodiase/meteor-mdl

Everything was fine until Meteor 1.3.

Running on OSX El Capitan.

Error in terminal:

```Bash
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
* zodiase:mdl > Enabled with default settings. See documentation for customization options.
* zodiase:mdl > Enabled with default settings. See documentation for customization options.

/Users/xh/.meteor/packages/templating/.1.1.8.1eh0n9++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
AssertionError: true === "undefined"
    at ImportScanner._combineFiles (/tools/isobuild/import-scanner.js:160:12)
    at /tools/isobuild/import-scanner.js:146:14
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:119:11)
    at /tools/isobuild/compiler-plugin.js:788:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:759:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:680:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:671:18)
    at /tools/isobuild/bundler.js:2512:14
    at /tools/isobuild/bundler.js:2602:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/xh/.meteor/packages/meteor-tool/.1.3.1.1b2brxe++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2601:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2493:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

Beside the assertion error, another abnormal thing is the double appearance of the log `* zodiase:mdl > Enabled with default settings. See documentation for customization options.`. It looks to me that the build script somehow got execute twice.

**Comment by abernix** [comment]
I ran your repro with 1.3.1 and I wasn't able to get the same assertion error you got.  However, I did receive:
```
Symlink cycle detected at integration-tests/dashboard/packages/zodiase:mdl
```
Anyhow, I upgraded to 1.3.2.4 and it works fine **(with the exception of the double-logging)**.  There were various import scanner fixes in 1.3.2 which probably resolved the first part.

As to why `* zodiase:mdl > Enabled with default settings. See documentation for customization options.` is appearing twice, I'd have to speculate one of three things:

0. Some weird lazy loading situation (maybe)
0. Not specifying a specific extension and it's picking it up for both the file and extension? (possible)
0. Or more than likely, in `test-packages` mode a regular server is spun up too and it also is running your compiler plugin.

Anyhow, your original issue seems resolved.  Closing this.  Can you open a separate issue to track that since it's not related to your original issue?
