### ISSUE TITLE
[1.3.1 Windows] Can't run meteor with --production option

### ISSUE THREAD

**Issue by tcastelli** [meteor/meteor#6795]
I can succesfully run meteor locally without --production flag, but turning it on brings the following error
````javascript
C:\Users\xxx\AppData\Local\.meteor\packages\coffeescript\1.0.16\plugin.compileCoffeescript.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
TypeError: Cannot call method 'split' of undefined
    at Object.parse (C:\tools\utils\parse-stack.js:18:28)
    at Object.exception (C:\tools\utils\buildmessage.js:497:29)
    at C:\tools\isobuild\bundler.js:1093:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.minifyJs (C:\tools\isobuild\bundler.js:1088:18)
    at C:\tools\isobuild\bundler.js:709:16
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:671:18)
    at C:\tools\isobuild\bundler.js:2512:14
    at C:\tools\isobuild\bundler.js:2602:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2601:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2493:31)
    at C:\tools\runners\run-app.js:591:36
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at bundleApp (C:\tools\runners\run-app.js:581:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:634:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:887:28)
    at C:\tools\runners\run-app.js:411:12
````

**Comment by sahanDissanayake** [comment]
Same error here, I have the ReactLayout and Flowrouter setup,
I still do not have the app for ES2015 strcture

```
TypeError: Cannot call method 'split' of undefined
    at Object.parse (/tools/utils/parse-stack.js:18:28)
    at Object.exception (/tools/utils/buildmessage.js:497:29)
    at /tools/isobuild/bundler.js:1093:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.minifyJs (/tools/isobuild/bundler.js:1088:18)
    at /tools/isobuild/bundler.js:709:16
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:671:18)
    at /tools/isobuild/bundler.js:2512:14
    at /tools/isobuild/bundler.js:2602:20
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/sahan/.meteor/packages/meteor-tool/.1.3.1.1d75k6w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2601:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2493:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by vhf** [comment]
Had the same error, took me a few minutes to notice I had an invalid json file laying around in my project directory. Check if you haven't added a file `<something>.json` with invalid json in it.

**Comment by tcastelli** [comment]
In my case, I had to go removing every package in my project (npm and atmosphere), since all my json files where correct. Finally I discovered that I was using a version of the npm package turf-buffer@1.0.1 that was crashing when minifying the code (looks like a problem on the minifier). 
I updated the version and the problem dissapeared, but the newest version brings breaking changes, so I will have to change quite a lot of code :-1: 

Anyway, I guess this is the common recipe, start removing things until it works...

Closing for now

**Comment by mariohmol** [comment]
i'm having same error (split...) https://github.com/Urigo/meteor-angular-socially/issues/120
