### ISSUE TITLE
Can't deploy on METEOR@1.3.2-rc.4

### ISSUE THREAD

**Issue by hyperh** [meteor/meteor#6796]
I'm using 1.3.2-rc.4 and I'm having issues deploying from OSX to Ubuntu using mup. My error logs are below.

```
	-----------------------------------STDERR-----------------------------------
	 you're running the version of npm bundled with
	npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
	npm WARN deprecated will be bundled with a version of npm@2, which has some small
	npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
	npm WARN deprecated semver behavior.
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/opt/olis/tmp/bundle/programs/server)
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
	Latest deployment failed! Reverted back to the previous version.
	-----------------------------------STDOUT-----------------------------------
	fibers.node`
	ansi-regex@0.2.1 node_modules/ansi-regex
	
	ansi-styles@1.1.0 node_modules/ansi-styles
	
	chalk@0.5.1 node_modules/chalk
	
	escape-string-regexp@1.0.5 node_modules/escape-string-regexp
	
	has-ansi@0.1.0 node_modules/has-ansi
	
	supports-color@0.2.0 node_modules/supports-color
	
	strip-ansi@0.3.0 node_modules/strip-ansi
	
	eachline@2.3.3 node_modules/eachline
	
	type-of@2.0.1 node_modules/type-of
	
	amdefine@1.0.0 node_modules/amdefine
	
	asap@2.0.3 node_modules/asap
	
	underscore@1.5.2 node_modules/underscore
	
	meteor-promise@0.5.1 node_modules/meteor-promise
	
	promise@7.0.4 node_modules/promise
	
	source-map-support@0.3.2 node_modules/source-map-support
	
	semver@4.1.0 node_modules/semver
	
	source-map@0.1.32 node_modules/source-map
	
	fibers@1.0.8 node_modules/fibers
	Waiting for MongoDB to initialize. (5 minutes)
	connected
	olis stop/waiting
	olis start/running, process 20863
	Waiting for 60 seconds while app is booting up
	Checking is app booted or not?
	olis stop/waiting
	olis start/running, process 21225
	----------------------------------------------------------------------------

```

```
Error: /opt/olis/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/opt/olis/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/olis/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
error: Script restart attempt #26

module.js:340
    throw err;
          ^
Error: Cannot find module '/opt/olis/app/main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/lib/node_modules/userdown/lib/userdown.js:42:3)
    at Object.<anonymous> (/usr/lib/node_modules/userdown/bin/userdown:22:27)
    at Module._compile (module.js:456:26)
    at Object.Module._e[188.166.250.138] xtensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
```

**Comment by abernix** [comment]
This keeps coming up with Meteor 1.3 and (old) Mup.  But your issue belongs with the mup project.  There is already an issue open over there @ arunoda/meteor-up#938

It is also well-known that the original `mup` is no longer in active development.  You should check `mupx` branch and also the www.github.com/kadirahq/meteor-up

If you're trying to fix the old install, from what I gather, the solutions are:
1. Upgrade your node version in mup.conf, then `mup setup`, then `mup deploy`.
2. Change `deployCheckWaitTime` to a higher value (30? 60?)

Regardless, please see the issues on the mup project.

**Comment by abernix** [comment]
@hyperh Also, you already commented on the same issue here – #6778.  Please close this duplicate issue.

**Comment by hyperh** [comment]
I'll try out your suggestions thanks.
