### ISSUE TITLE
[1.3.2-rc.5] Build error: issue with static-html package

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6812]
```
/Users/clayne/workspace/meteor/.meteor/packages/juliancwirko_postcss/.1.1.0.1o1yix1++os+web.browser+web.cordova/plugin.minifier-postcss.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Cannot call method 'split' of undefined
    at Object.parse (/tools/utils/parse-stack.js:18:28)
    at Object.exception (/tools/utils/buildmessage.js:497:29)
    at /tools/isobuild/compiler-plugin.js:189:26
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/compiler-plugin.js:176:22
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:175:15
    at Function._.each._.forEach (/Users/clayne/workspace/meteor/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:165:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:901:22)
    at /tools/isobuild/bundler.js:681:34
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
```

I ran it from a checkout and added a `console.log` where the exception is happening and I got this:

`
[RangeError: Maximum call stack size exceeded]
`

**Comment by clayne11** [comment]
I put in a log statement in `/tools/isobuild/compiler-plugin.js:189:26` and found that `static-html` was the culprit. I removed this package and my app is now building normally again. Any ideas why this would be happening?

**Comment by clayne11** [comment]
The same issue occurs if I add `templating` into my project as well.

**Comment by clayne11** [comment]
I have worked around the issue for now by using `react-helmet` to add elements to the head of my html but this is a bit of an issue.

**Comment by stubailo** [comment]
Hmm, I can't reproduce this issue by making an app with the latest Meteor release and adding `static-html`. Could you post a more detailed reproduction?

**Comment by mariohmol** [comment]
Here how to reproduce: https://github.com/Urigo/meteor-angular-socially/issues/120

**Comment by clayne11** [comment]
Issue seems to be fixed for me now. I'm closing this.
