### ISSUE TITLE
[1.3.3.2] Problem with MongoDB & SSL

### ISSUE THREAD

**Issue by csillag** [meteor/meteor#6872]
I am using a hosted MongoDB deployment by Compose.io.

Normally, the connection works, but when I add "?ssl=true" to the end of the MONGO_URL, I get this connection error:

```
           
 /whatever/meteor/packages/meteor-tool/.1.3.2_2.1gyeu33++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:300
             				throw(ex);
             				      ^
 Error: failed to connect to [aws-us-east-1-portal.16.dblayer.com:10204]
     at Object.Future.wait (/whatever/meteor/packages/meteor-tool/.1.3.2_2.1gyeu33++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:420:15)
     at new MongoConnection (packages/mongo/mongo_driver.js:213:27)
     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
     at new Mongo.Collection (packages/mongo/collection.js:102:40)
     at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
     at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
     - - - - -
     at [object Object].<anonymous> (/whatever/meteor/packages/npm-mongo/.1.4.43.lp07h8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
     at [object Object].emit (events.js:106:17)
     at [object Object].<anonymous> (/whatever/meteor/packages/npm-mongo/.1.4.43.lp07h8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
     at [object Object].emit (events.js:98:17)
     at CleartextStream.<anonymous> (/whatever/meteor/packages/npm-mongo/.1.4.43.lp07h8++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
     at CleartextStream.emit (events.js:95:17)
     at SecurePair.<anonymous> (tls.js:1411:15)
     at SecurePair.emit (events.js:95:17)
     at SecurePair.error (tls.js:1018:27)
     at EncryptedStream.CryptoStream._done (tls.js:703:22)
```

Are SSL Mongo connections supposed to be working in the recent releases?
(According to https://github.com/meteor/meteor/issues/4812, they are supported...)

**Comment by abernix** [comment]
If you are trying to use Mongo 3.2, that is likely the problem.  3.0 is widely known to be compatible but 3.2 has some issues.  It is in the pipeline to be resolved soon and also [on the Roadmap](https://github.com/meteor/meteor/blob/c5e7de42f670227dec7cbd0869a67bfa6fa84acd/Roadmap.md).  See #5809.

If you are on Compose.io switch your database to MongoDB Classic version 3.0.6 and everything should work great.

Please close this issue if this helps as it is a duplicate of existing issues.

**Comment by csillag** [comment]
Oh yes, I am on Compose, and I got the default Mongo 3.2 installation. I am switching back to 3.0.x.

Thanks for the info. Closing this as duplicate.
