### ISSUE TITLE
Error 1 using android-device

### ISSUE THREAD

**Issue by rolivav** [meteor/meteor#6908]
Hi, yesterday I was able to compile to an android mobile succesfully without a problem. I had to reinstall Node because it got corrupted and now i'm getting this error when I use `meteor run android-device --mobile-server <host>`.
```
λ meteor run android-device --mobile-server <host>
[[[[[ C:\<path>\meteor-project ]]]]]

=> Started proxy.
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the
         local server, make sure your device is on the same network, and that the network configuration
         allows clients to talk to each other (no client isolation).
=> Errors executing Cordova commands:

   While running Cordova app for platform Android with options --device:
   Error: Command failed:
   C:\<path>\meteor-project\.meteor\local\cordova-build\platforms\android\cordova\run
   --device --device
   Error code 1 for command: cmd with args:
   /s,/c,"C:\<path>\meteor-project\.meteor\local\cordova-build\platforms\android\gradlew
   cdvBuildDebug -b
   C:\<path>\meteor-project\.meteor\local\cordova-build\platforms\android\build.gradle
   -PcdvBuildArch=arm -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true" undefined
   at ChildProcess.exitCallback (C:\tools\utils\processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

C:\Users\<user>\AppData\Local\.meteor\packages\less\2.6.0\plugin.compileLessBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
ExitWithCode:1
```
I don't understand this error at all.
Things I've tried: I removed cordova-build, I removed .gradle in AppData, I cloned the project from the repository and compiled from scratch, I removed node_modules folder and installed again everything, I updated to last version of meteor. Nothing worked, same error. Any ideas?

**Comment by rolivav** [comment]
I'm currently updating the SDK tools, but I don't know if that will fix anything.

**Comment by rolivav** [comment]
I feel dumb... I executed `gradlew.bat` and it turns out I didn't have JAVA_HOME pointing to the root of the JDK. After fixing this the mobile version built correctly.
