### ISSUE TITLE
[1.3.2.4] - Error: Can't find npm module 'babel-runtime/helpers/typeof' after upgrade from 1.3

### ISSUE THREAD

**Issue by timmygee** [meteor/meteor#6918]
Actually this happens when updating from 1.3 to 1.3.1 as well

I have trawled the existing issues here for problems to do with babel-runtime but I haven't come across any solutions to this issue.

When running meteor after the upgrade it crashes with this stack trace:

```
W20160427-18:00:48.446(10)? (STDERR) /Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/boot.js:324
W20160427-18:00:48.446(10)? (STDERR) }).run();
W20160427-18:00:48.446(10)? (STDERR)    ^
W20160427-18:00:48.471(10)? (STDERR) Error: Can't find npm module 'babel-runtime/helpers/typeof'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160427-18:00:48.471(10)? (STDERR)     at Object.Npm.require (/Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/boot.js:195:17)
W20160427-18:00:48.471(10)? (STDERR)     at options.fallback (packages/modules-runtime/packages/modules-runtime.js:396:1)
W20160427-18:00:48.471(10)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:88:1)
W20160427-18:00:48.471(10)? (STDERR)     at meteorInstall.node_modules.meteor.webapp.webapp_server.js (/Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/packages/webapp.js:33:16)
W20160427-18:00:48.471(10)? (STDERR)     at fileEvaluate (packages/modules-runtime/packages/modules-runtime.js:148:1)
W20160427-18:00:48.471(10)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:82:1)
W20160427-18:00:48.472(10)? (STDERR)     at /Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/packages/webapp.js:843:1
W20160427-18:00:48.472(10)? (STDERR)     at /Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/packages/webapp.js:856:3
W20160427-18:00:48.472(10)? (STDERR)     at /Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/boot.js:283:10
W20160427-18:00:48.472(10)? (STDERR)     at Array.forEach (native)
```

I can't provide an isolated reproduction of the issue because the code is proprietary sorry. Plus I'm not entirely sure what to isolate

Output from `meteor list`

```
accounts-google                  1.0.9  Login service for Google accounts
accounts-password                1.1.8  Password support for accounts
accounts-ui                      1.1.9  Simple templates to add login widgets to an app
aldeed:autoform                  5.8.1  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2               2.9.1  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema             1.5.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
blaze-html-templates             1.0.4  Compile HTML templates into reactive UI with Meteor Blaze
check                            1.2.1  Check whether a value matches a pattern
chhib:selectize-bootstrap-3      0.0.1  Selectize is a hybrid of a textbox and <select> element used for tagging, contact lists, and more.
comerc:autoform-selectize        2.3.0  Custom "selectize" input type for AutoForm
comerc:autoform-typeahead        1.0.5  Custom "typeahead" input type for AutoForm
comerc:bs-typeahead              1.0.2  Typeahead-plugin with Bootstrap-style
dali                             0.0.0+ dali.styl
datejs                           0.0.0+ Date parsing library
dburles:collection-helpers       1.0.4  Transform your collections with helpers that you define
dburles:lazy                     1.0.1  A handy little development tool
ecmascript                       0.4.3  Compiler plugin that supports ES2015+ in all .js files
ejson                            1.0.11  Extended and Extensible JSON library
email                            1.0.12  Send email messages
erasaur:meteor-lodash            3.10.1_1* Wrapper for Lo-Dash v3.10.1
factories                        0.0.0+ Object creation package
filepicker                       0.0.1+ Ink filepicker
fortawesome:fontawesome          4.5.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
fourseven:scss                   3.4.3  Style with attitude. Sass and SCSS support for Meteor.js (with autoprefixer and sourcemaps).
iron:router                      1.0.12  Routing specifically designed for Meteor
jeremy:selectize                 0.12.1_5  Selectize is a hybrid of a textbox and <select> element used for tagging, contact lists, and more.
johnantoni:meteor-stickynav      0.0.2  stickyNavbar.js: Fancy sticky navigation jQuery plugin with smart anchor link highlighting.
jquery                           1.11.8  Manipulate the DOM using CSS selectors
juliancwirko:s-alert             3.1.4  Simple and fancy notifications / alerts / errors for Meteor
juliancwirko:s-alert-stackslide  3.1.3  StackSlide effect for s-alert - simple and fancy notifications / alerts for Meteor.
linkify                          0.0.0+ Linkify library
logging                          1.0.12  Logging facility.
loops                            0.0.0+ Loop Model
messages                         0.0.0+ Message Model
meteor-base                      1.0.4  Packages that every Meteor app needs
meteorhacks:kadira               2.28.5  Performance Monitoring for Meteor
mobile-experience                1.0.4  Packages for a great mobile user experience
models                           0.0.1+ Tom's models
momentjs:moment                  2.13.1  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor packaging
mongo                            1.1.7  Adaptor for using MongoDB and Minimongo over DDP
mrt:q                            1.0.1  A wrapper for the Q promise library from kris kowal
notifications                    0.0.0+ Notification Model
organisations                    0.0.0+ Mentorloop Organisations
pauli:accounts-linkedin          1.3.1  Accounts service for LinkedIn accounts
percolate:migrations             0.9.8  Define and run db migrations.
percolate:momentum               0.7.2  Reactive animations
profiles                         0.0.0+ Profile Model
programs                         0.0.0+ Program Model
publications                     0.0.0+ The Publications we use
raix:handlebar-helpers           0.2.5  Handlebar helpers
random                           1.0.9  Random number generator and utilities
reactive-dict                    1.1.7  Reactive dictionary
reactive-var                     1.0.9  Reactive variable
recruits                         0.0.0+ Recruits Forms
reload                           1.1.8  Reload the page while preserving application state.
reywood:publish-composite        1.4.2  Publish a set of related documents from multiple collections with a reactive join
roles                            0.0.0+ Roles Model
session                          1.1.5  Session variable
spacebars                        1.0.11  Handlebars-like template language for Meteor
standard-minifier-css            1.0.6  Standard css minifier used with Meteor apps by default.
standard-minifier-js             1.0.6  Standard javascript minifiers used with Meteor apps by default.
tmeasday:presence                1.0.6  A package to help track users' presence
tmeasday:publish-counts          0.7.3  Publish the count of a cursor, in real time
topics                           0.0.0+ Topic Model
tracker                          1.0.13  Dependency tracker to allow reactive callbacks
underscore                       1.0.8  Collection of small helpers: _.map, _.each, ...
uservoice                        0.0.0+ UserVoice: Feedback & Online Help Desk Software
xolvio:email-stub                0.2.0  Allows you to inspect sent emails and assert on their content.
```

I came across a similar issue here: https://github.com/meteor/meteor/issues/6355 where the missing `toArray` reference was implemented to fix the issue. I wonder if the same thing needs to be done here for `typeof`?

Googling the error seems to return a few results so I don't think I'm alone in this problem.

I came across one suggestion where the solution was to run

```
meteor npm install --save babel-runtime@5
```

But that just yielded another error when running meteor which said

```
/Users/tim/.meteor/packages/meteor-tool/.1.3.2_4.t9x6n0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160427-18:14:14.704(10)? (STDERR)            				throw(ex);
W20160427-18:14:14.704(10)? (STDERR)            				      ^
W20160427-18:14:14.751(10)? (STDERR) TypeError: Cannot read property 'env' of undefined
W20160427-18:14:14.751(10)? (STDERR)     at meteorInstall.node_modules.meteor.ddp-server.server_convenience.js (packages/ddp-server/server_convenience.js:1:5)
W20160427-18:14:14.751(10)? (STDERR)     at fileEvaluate (packages/modules-runtime/packages/modules-runtime.js:148:1)
W20160427-18:14:14.752(10)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:82:1)
W20160427-18:14:14.752(10)? (STDERR)     at /Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/packages/ddp-server.js:2501:1
W20160427-18:14:14.752(10)? (STDERR)     at /Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/packages/ddp-server.js:2512:3
W20160427-18:14:14.752(10)? (STDERR)     at /Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/boot.js:283:10
W20160427-18:14:14.752(10)? (STDERR)     at Array.forEach (native)
W20160427-18:14:14.752(10)? (STDERR)     at Function._.each._.forEach (/Users/tim/.meteor/packages/meteor-tool/.1.3.2_4.t9x6n0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160427-18:14:14.752(10)? (STDERR)     at /Users/tim/ccc/mentorloop/app/.meteor/local/build/programs/server/boot.js:133:5
```

So no success there either. Any suggestions?

**Comment by ni-ko-o-kin** [comment]
Happens to me too. I upgraded from 1.1 to 1.2, then to 1.3.2.4, and then back to 1.3 because of _Error: Can't find npm module 'babel-runtime/helpers/typeof'_

**Comment by timmygee** [comment]
I can confirm that this error is resolved by removing the `.meteor` directory in your home directory and re-installing meteor with `curl https://install.meteor.com/ | sh`

**Comment by abernix** [comment]
Just as a pointer to anyone coming to this issue, you may be able to avoid reinstalling Meteor completely by simply removing the `<PROJECT_DIR>/.meteor/local/bundler-cache/` directory and relaunching your app.  Should be a lot quicker than a full-reinstall.

**Comment by Cleanshooter** [comment]
These solutions do not work for Windows install.  Please re-open.

**Comment by abernix** [comment]
@Cleanshooter Your `.meteor` directory on Windows is in a different place than the above examples – it would be in `%localappdata%\.meteor`.  Not sure if the Windows installer would replace that automatically or not, but you could try to delete that folder and reinstall with the GUI installer.

**Comment by Cleanshooter** [comment]
Yeah if you delete the .meteor directory from your project the app won't be able to build and it's not replaced unless you start over and do a meteor create <app-name> which... means that the issue persists.  Deleting the bundler-cache get's replaced on build but the issue persists in this situation as well.  And installing older (working) versions of meteor is very difficult in my experience, and has doing so has changed from version to version as well, to be honest I'm not sure how to do it anymore.

**Comment by abernix** [comment]
@Cleanshooter I wasn't suggesting you delete your app's `.meteor` directory – that will definitely cause problems.  I'm also not suggesting installing older versions.  `%localappdata%\.meteor` is a directory on your computer in `C:\Users\<YourUsername>\AppData\Local`.  Once you remove that, reinstalling the current version might fix this for you (as it did for the users above).

Which of these exact error messages are you receiving (there are two mentioned in this issue)?
1. `TypeError: Cannot read property 'env' of undefined`
2. `Error: Can't find npm module 'babel-runtime/helpers/typeof'. `

**Comment by Cleanshooter** [comment]
I'm getting: Error: Can't find npm module 'babel-runtime/helpers/typeof'.
I'm attempting a fresh install right now.  Complete meteor uninstall and reinstall with latest windows installer.  I'll let you know if i see any success from it.

**Comment by Cleanshooter** [comment]
THAT DID IT.  On windows complete uninstall and reinstall and app launches just fine.

**Comment by abernix** [comment]
@Cleanshooter Glad to hear that got it working for you again.

@benjamn This seems to be a recurring, not-too-common-but-still-happens issue that is resolved by reinstall on both *nix and Windows.  Any ideas?

**Comment by benjamn** [comment]
I think the `meteor npm install --save babel-runtime@5` command probably did solve the original problem, and the `TypeError: Cannot read property 'env' of undefined` error is something else. That said, installing `babel-runtime` shouldn't be necessary, since we definitely do provide the `babel-runtime/helpers/typeof` [helper](https://github.com/meteor/meteor/blob/249e4498b739366bc41410ab187502fb91d77839/packages/babel-runtime/babel-runtime.js#L136-L138) from the Meteor `babel-runtime` package.

What happens if you `meteor add babel-runtime@0.1.8` so that it's a direct, version-pinned dependency of your app?

**Comment by abernix** [comment]
I don't believe that anyone who has reinstalled it has needed to install the `babel-runtime` after the reinstall though.  Reinstall just fixed it so it would lead me to believe that there was some sort of previous-version residue that was breaking it.

Will have to see if direct pinning fixes it for the next person who experiences this.

**Comment by ni-ko-o-kin** [comment]
removing ~/.meteor worked for me on debian/linux.

**Comment by array-addu** [comment]
removing .meteor and then re-installing meteor doesn't help me. It doesn't taking the meteor command as .meteor folder is deleted, any solution for this?

**Comment by timmygee** [comment]
@array-addu please confirm that you are removing the .meteor directory in your HOME directory, not your PROJECT directory

**Comment by ffxsam** [comment]
This is interesting, my Meteor apps run fine on Mac, but on Ubuntu I get an error about `babel-runtime/helpers/defineProperty` not being found. Removing `~/.meteor` doesn't fix it. I figure the best workaround is to just do `npm i --save-dev babel-runtime` (as the app doesn't need it in production).

**Comment by gsabran** [comment]
This just happened for me after upgrading to `1.4.2` Contrary to the opened issue, this is happening on the client. I've removed both `~/.meteor` and `<pathToApp>/.meteor/local`, reinstalled and restarted and the issue still happens. Is there something new to do with `1.4.2` related to how npm packages are now handled?

**Comment by MartinBucko** [comment]
+1 

Meteor 1.4.2 - Ubuntu 16.04
After meteor update. When i run meteor it start without problems, but when i run meteor test it produce error:

```
$ meteor npm test

> api@1.0.3 test /home/.../api
> meteor test --driver-package practicalmeteor:mocha

[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
W20161109-09:48:20.906(1)? (STDERR) /tmp/meteor-test-rundwglcs/.meteor/local/build/programs/server/boot.js:348
W20161109-09:48:20.951(1)? (STDERR) }).run(); 
W20161109-09:48:20.951(1)? (STDERR)    ^      
W20161109-09:48:20.952(1)? (STDERR)           
W20161109-09:48:20.952(1)? (STDERR) Error: Can't find npm module 'babel-runtime/helpers/typeof'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20161109-09:48:20.952(1)? (STDERR)     at Object.require (/tmp/meteor-test-rundwglcs/.meteor/local/build/programs/server/boot.js:200:17)
W20161109-09:48:20.953(1)? (STDERR)     at options.fallback (packages/modules-runtime.js:445:18)
W20161109-09:48:20.954(1)? (STDERR)     at Module.require (packages/modules-runtime.js:112:16)
W20161109-09:48:20.954(1)? (STDERR)     at Module.Mp.import (/home/martinez/.meteor/packages/modules/.0.7.7.mccaq7++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161109-09:48:20.954(1)? (STDERR)     at meteorInstall.node_modules.meteor.webapp.webapp_server.js (/tmp/meteor-test-rundwglcs/.meteor/local/build/programs/server/packages/webapp.js:33:26)
W20161109-09:48:20.955(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161109-09:48:20.955(1)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161109-09:48:20.956(1)? (STDERR)     at /tmp/meteor-test-rundwglcs/.meteor/local/build/programs/server/packages/webapp.js:842:1
W20161109-09:48:20.956(1)? (STDERR)     at /tmp/meteor-test-rundwglcs/.meteor/local/build/programs/server/packages/webapp.js:855:3
W20161109-09:48:20.956(1)? (STDERR)     at /tmp/meteor-test-rundwglcs/.meteor/local/build/programs/server/boot.js:295:34
=> Exited with code: 1 
```
- i try to remove meteor form home and reinstall meteor
- i try to remove .meteor/local
- i try to remove node_modules and do meteor npm install
- i try meteor add babel-runtime 
- i try meteor npm i babel-runtime --save-dev
- in package.json is `"babel-runtime": "^6.18.0"`

Nothing helps..

**Comment by abernix** [comment]
@MartinBucko Please see #8032 for the solution to your problem (and an explanation!)

**Comment by MartinBucko** [comment]
Meteor 1.4.2.1 fix this issue
Thanks to all participants!
