### ISSUE TITLE
SCSS file being compiled from node_modules even though it isn't imported

### ISSUE THREAD

**Issue by clayne11** [meteor/meteor#6950]
I'm trying to setup `nathantreid:css-modules` but I'm having an issue with some SCSS files trying to be compiled from my `node_modules` folder even though I never import those files.

I'm getting the following error: 

```
TypeError: Cannot set property './components.scss.js' of undefined
    at ImportScanner._checkSourceAndTargetPaths (/tools/isobuild/import-scanner.js:256:7)
    at /tools/isobuild/import-scanner.js:159:12
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:158:11)
    at /tools/isobuild/compiler-plugin.js:834:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:805:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:925:8)
```

The package in question is `react-select`. Is Meteor supposed to eagerly evaluate all files in my `node_modules` folder?

**Comment by clayne11** [comment]
Looks like Meteor evaluates all the file and sets them to "lazy" if they in the `node_modules` folder. It seems like `nathantreid:css-modules` is trying to process the file even though it's lazy and never used though which seems odd. I would think that the build plugin should never even receive a lazy file that isn't imported.

**Comment by clayne11** [comment]
Here's a minimal repro: https://github.com/clayne11/css-modules-test

**Comment by clayne11** [comment]
In `import-scanner` when trying to set `sourceFile.deps` `deps` is undefined:

```
serverPath: /node_modules/react-select/scss/components.scss.js
sourceFile.deps: undefined
```

**Comment by clayne11** [comment]
Fixed in nathantreid:css-modules.
