### ISSUE TITLE
android build failed - Execution failed for task ':processDebugResources'.

### ISSUE THREAD

**Issue by rlech** [meteor/meteor#6979]
Meteor Version: **METEOR@1.3.2.4**
Android API Level: 23
OS: OSX

**Packages**
```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library
standard-minifier-css   # CSS minifier run for production mode
standard-minifier-js    # JS minifier run for production mode
es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code
kadira:flow-router     
kadira:blaze-layout     
arillo:flow-router-helpers  
matb33:collection-hooks
moments:moment
session
accounts-password
check
gwendall:body-events
cfs:standard-packages
cvs:Griffs
cfs:graphicsmagick
percolate:synced-cron
buildateam:count
rain:push
```

**Cordova-plugins**
```
cordova-plugin-actionsheet@2.2.2
cordova-plugin-camera@2.1.1
cordova-plugin-customurlscheme@4.1.5
cordova-plugin-device@1.1.2
cordova-plugin-geolocation@2.2.0
cordova-plugin-ios-longpress-fix@1.1.0
cordova-plugin-network-information@1.2.1
cordova-plugin-statusbar@2.1.3
cordova-plugin-vibration@2.1.1
cordova-plugin-x-socialsharing@5.0.10
phonegap-plugin-barcodescanner@4.1.0
cordova-plugin-inappbrowser@1.4.0
cordova.plugins.diagnostic@2.3.16
```

**error log**
```
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
   Starting app on Android Device            |                       
:preBuild
:preDebugBuild
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
 UP-TO-DATE app on Android Device            |                                
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:compileReleaseAidl UP-TO-DATE
 UP-TO-DATE app on Android Device            |                                      
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2330Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72330Library UP-TO-DATE
:prepareComAndroidSupportSupportV132330Library UP-TO-DATE
:prepareComAndroidSupportSupportV42330Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2330Library UP-TO-DATE
:prepareDebugDependencies
 UP-TO-DATE app on Android Device            |                 
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
   Starting app on Android Device            /                 
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
 UP-TO-DATE app on Android Device            /                    
:processDebugManifest UP-TO-DATE
 FAILEDting app on Android Device            /                      

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/kippiz/Library/Android/sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.895 secs
Error code 1 for command: /Users/kippiz/WebstormProjects/kippiz-ios/.meteor/local/cordova-build/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/kippiz/WebstormProjects/kippiz-ios/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true undefined
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed: /Users/kippiz/WebstormProjects/kippiz-ios/.meteor/local/cordova-build/platforms/android/cordova/run --device
   
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

/Users/kippiz/.meteor/packages/meteor-tool/.1.3.2_4.1hgoaof++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1
Roberts-iMac:kippiz-ios kippiz$ 
```

when I try to build or run my code on android its failing and give me the error with the **processDebugResources**

working fine on iOS.

**Comment by laosb** [comment]
Could you provide a minimal repro?

**Comment by rlech** [comment]
nope this is a working production ready ios app that I would like to compile into a android apk

**Comment by laosb** [comment]
Would you like try to reproduce it in a `meteor create`ed bare new app?

**Comment by rlech** [comment]
when I create a bare new project everything works fine with iOS and Android. when I try to copy&paste my code into the bare project I got this error again but just for android builds.

**Comment by rlech** [comment]
ok it seems like there are some issues with files in the public folder. I have stored some images for the interface there. letting you know which file it was when I found this bastard.

btw: are there any restrictions for android how big a file in the public folder can be? Or how many files I can store there?

**Comment by rlech** [comment]
bug was fixed by renaming a file that contains a "ß" in the name.

**Comment by abernix** [comment]
Good to know.  Thanks for reporting back @rlech.

**Comment by boustanihani** [comment]
I'm having the same error without any special letters...

**Comment by boustanihani** [comment]
Issue solved, my problem was that I forgot to install the 32-bit libraries under Ubuntu 14.04 64bit:
`sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6`
