### ISSUE TITLE
Meteor Build Fails with copyFileSync: could not write to dest

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#7037]
I am using the android and ios platforms for Cordova in my meteor 1.3.2.4 app. The apps run fine locally via:

```
meteor run android
meteor run android-device
meteor run ios
meteor run ios-device
```

However, when attempting to build for deployment:

```
meteor build <Dir> --server <hostname>:<ip>
```

I get the following error:
```
cp: copyFileSync: could not write to dest file (code=ENOENT):platforms/android/assets/www/cordova.js
```

All I can find online is that this is likely a local permissions issue, however all of the existing remedies I've seen haven't worked for me:

- `mkdir .meteor/local/cordova-build/platforms/android/assets/www` <- Meteor destroys this directory on the next build command, and then spits out the same error
- `rm -rf .meteor/local` <- same as above
- deleting the repository and re-cloning from source
- I also tried a `chmod -R 777 .meteor/` just to see what would happen, still no luck.

Any ideas on what barrier(s) I'm running up against here? Thanks!

**Comment by joncursi** [comment]
I tried removing the `android` platform from my project, and I get a slightly different (and more verbose) error this time (now it's trying to build for just web and `ios`):

```
Error: ENOENT, no such file or directory '/Users/jcursi/Sites/joncursi/redbird/.meteor/local/cordova-build/www/*'
    at Object.fs.statSync (fs.js:696:18)
    at /Users/jcursi/Sites/joncursi/redbird/node_modules/shelljs/src/cp.js:148:21
    at Array.forEach (native)
    at Object._cp (/Users/jcursi/Sites/joncursi/redbird/node_modules/shelljs/src/cp.js:144:13)
    at Object.cp (/Users/jcursi/Sites/joncursi/redbird/node_modules/shelljs/src/common.js:240:23)
    at updateWww (/Users/jcursi/Sites/joncursi/redbird/.meteor/local/cordova-build/platforms/ios/cordova/lib/prepare.js:105:11)
    at Api.module.exports.prepare (/Users/jcursi/Sites/joncursi/redbird/.meteor/local/cordova-build/platforms/ios/cordova/lib/prepare.js:44:19)
    at Api.prepare (/Users/jcursi/Sites/joncursi/redbird/.meteor/local/cordova-build/platforms/ios/cordova/Api.js:165:45)
    at /Users/jcursi/.meteor/packages/meteor-tool/.1.3.2_4.1ypt9bt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/cordova/prepare.js:101:32
    at _fulfilled (/Users/jcursi/.meteor/packages/meteor-tool/.1.3.2_4.1ypt9bt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/jcursi/.meteor/packages/meteor-tool/.1.3.2_4.1ypt9bt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/jcursi/.meteor/packages/meteor-tool/.1.3.2_4.1ypt9bt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
    at /Users/jcursi/.meteor/packages/meteor-tool/.1.3.2_4.1ypt9bt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
    at flush (/Users/jcursi/.meteor/packages/meteor-tool/.1.3.2_4.1ypt9bt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
```

After removing the `ios` platform, and just building for web, it succeeds. So it's something funky with Cordova?

**Comment by abernix** [comment]
That `*` looks *really* suspicious to me on the first line.

Can you reproduce this in a new project?  Do you have a file somewhere named `*` in your Meteor project somewhere?  Or some other weird filenames?

**Comment by joncursi** [comment]
After a lot of testing, I've been able to isolate these Cordova build errors to the `juliancwirko:postcss` package. When I remove this package from my project, the build completes without errors. I will port this issue over to the package's GitHub repo, but I think this should also be cause for concern for the Meteor team as this package is recommended in the Meteor Guide.

**Comment by joncursi** [comment]
Moving this conversation to [here](https://github.com/meteor/meteor/issues/7037#issuecomment-219198574).

**Comment by joncursi** [comment]
cc @martijnwalraven @tmeasday
