### ISSUE TITLE
Cannot find module 'eslint-config-plugin:meteor/recommended'

### ISSUE THREAD

**Issue by markoshust** [meteor/meteor#7044]
I'm setting up eslinting from the new meteor code styling guide at http://guide.meteor.com/code-style.html

After following the instructions, WebStorm is complaining with the following error:

```
Cannot read config package: eslint-config-plugin:meteor/recommended
Error: Cannot find module 'eslint-config-plugin:meteor/recommended'
Referenced from: /Users/markshust/Sites/chanj/flow-frontend/.eslintrc.json
Error: Cannot read config package: eslint-config-plugin:meteor/recommended
Error: Cannot find module 'eslint-config-plugin:meteor/recommended'
Referenced from: /Users/markshust/Sites/chanj/flow-frontend/.eslintrc.json
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at loadPackage (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:385:18)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:309:28)

Process finished with exit code 1
```

**Comment by markoshust** [comment]
Ah -- found my answer at https://github.com/airbnb/javascript/issues/465#issuecomment-129213642

This screenshot:
<img width="1031" alt="webstorm-configuration" src="https://cloud.githubusercontent.com/assets/437029/15236560/f0d1703e-1893-11e6-9b3a-381f12c0824a.png">

references the global ESLint package -- it should reference the local project eslint package.

**Comment by abernix** [comment]
Thanks for pointing this out!

I've moved this Issue over to the issue tracker for the Meteor Guide Repo at https://github.com/meteor/guide/

**Comment by markoshust** [comment]
Thanks -- figured it had it's own repo someplace :)
