### ISSUE TITLE
Meteor code must always run within a Fiber

### ISSUE THREAD

**Issue by hadijaveed** [meteor/meteor#7057]
```
var wrappedEvents = function(queryObj, cb) {
      getEvents(queryObj, 'NY', function(err, eventIds) {
        if (err) console.log(err);
        _.each(eventIds, (id) => {
          getEventFromId(id, function(res) {
            // console.log(res);
            Collection.insert({
              event_id: res.id,
              cover_url: res.cover.source,
            });
          });
        });
      });
      cb(null, true);
    };
    
    let c = Meteor.wrapAsync(wrappedEvents);
    c(queryObj);
```
I have tried fibers but it keeps giving same error. I have to insert collection in this callback function.

Error Stack:
```
W20160515-08:37:15.035(5)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20160515-08:37:15.035(5)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20160515-08:37:15.035(5)? (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
W20160515-08:37:15.036(5)? (STDERR)     at Object.DDP.randomStream (packages/ddp-client/random_stream.js:5:1)
W20160515-08:37:15.036(5)? (STDERR)     at [object Object].self._makeNewID (packages/mongo/collection.js:75:19)
W20160515-08:37:15.036(5)? (STDERR)     at [object Object].insert (packages/mongo/collection.js:474:22)
W20160515-08:37:15.036(5)? (STDERR)     at Class.prototypeMethods.save (packages/jagi_astronomy/lib/modules/storage/init_definition.js:71:1)
W20160515-08:37:15.036(5)? (STDERR)     at Function.classMethods.insert (packages/jagi_astronomy/lib/modules/storage/init_class.js:40:1)
W20160515-08:37:15.036(5)? (STDERR)     at server/methods.js:26:21
W20160515-08:37:15.037(5)? (STDERR)     at Graph.callback (server/lib/location-utils.js:39:11)
W20160515-08:37:15.037(5)? (STDERR)     at Graph.end (/home/hadijaveed/.meteor/packages/stevezhu_fbgraph/.2.0.0.9ommc6++os+web.browser+web.cordova/npm/node_modules/fbgraph/lib/graph.js:170:8)
```

**Comment by laosb** [comment]
That's exactly expected behavior. You can ask for help on forums.meteor.com. Closing and feel free to reopen if this is a bug.
