### ISSUE TITLE
Crashes on android device with latest android SDK

### ISSUE THREAD

**Issue by cunneen** [meteor/meteor#7088]
Running with command:

```
meteor run android-device --settings settings.json --production --mobile-server=https://my-mobile-server.example.com
```

With the very latest android SDKs:

* SDK Tools 25.1.6
* Platform tools 23.1
* Build tools 23.0.3
* SDK Platform v23
* Google Play Services 30
* Android Support Repository 32

, I get the following stacktrace:

```
05-20 22:52:38.275 16059 16204 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/com.example.app-1/base.apk)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-20 22:52:38.275 16059 16204 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

There look to be a couple of related issues on stackoverflow:
* [http://stackoverflow.com/q/37312340](IncompatibleClassChangeError after updating to Android Build Tools 25.1.6 GCM / FCM)
* [Android Google Cloud Messaging (GCM) token generation crash after Firebase-related Google Play Services update](http://stackoverflow.com/q/37337393)

**Comment by cunneen** [comment]
Looking at that stacktrace, it could be a cordova push plugin issue...

**Comment by cunneen** [comment]
[Raised #218 on the raix:push repository](https://github.com/raix/push/issues/218). Closing.
