### ISSUE TITLE
Not compiling 1.3.3beta0 

### ISSUE THREAD

**Issue by rickmed** [meteor/meteor#7105]
1.3.3beta0 on linux x63

.babelrc
```
{
  "plugins": [
    "plugin-react-html-attrs"
  ]
}
```

EDIT:
Changing .babelrc from original to
```
{
  "plugins": [
    "./node_modules/babel-plugin-react-html-attrs"
  ]
}
```
 it compiles (meteor run)

```
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   native: Cannot convert null to object
   at hasOwnProperty (native)
   at Function._.has
   (/root/.meteor/packages/meteor-tool/.1.3.3-beta.0.1l4z13f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:1046:27)
   at /tools/isobuild/compiler-plugin.js:331:15
   at Array.forEach (native)
   at /tools/isobuild/compiler-plugin.js:330:41
   at InputFile.resolve (/tools/isobuild/compiler-plugin.js:324:23)
   at InputFile.<anonymous> (/tools/isobuild/compiler-plugin.js:351:25)
   at InputFile.require
   (/root/.meteor/packages/meteor-tool/.1.3.3-beta.0.1l4z13f++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/isobuild/compiler-plugin.js:353:23)
   at req (packages/babel-compiler/babel-compiler.js:209:1)
   at packages/babel-compiler/babel-compiler.js:214:1
   at Array.forEach (native)
   at infer (packages/babel-compiler/babel-compiler.js:212:1)
   at BabelCompiler.BCp._inferHelper (packages/babel-compiler/babel-compiler.js:231:1)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler/babel-compiler.js:163:1)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler/babel-compiler.js:150:1)
   at packages/babel-compiler/babel-compiler.js:92:1
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:40:1)
```

**Comment by abernix** [comment]
What if in your project root you do:
```
meteor npm install babel-plugin-react-html-attrs --save-dev
```
and do not include the `babel-plugin-` prefix on the plugin name in your `.babelrc`:
```json
{
  "plugins": [
    "react-html-attrs"
  ]
}
```
❓

**Comment by benjamn** [comment]
How is this issue different from https://github.com/meteor/meteor/issues/7098?

**Comment by rickmed** [comment]
You're right (although this is on linux while the other one was on windows, but I'll close it).
