### ISSUE TITLE
practicalmeteor:mocha cannot find html modules

### ISSUE THREAD

**Issue by Brona123** [meteor/meteor#7169]
When trying to run some UI tests with practicalmeteor:mocha as the driver package, I get the following error:

```
Error: Cannot find module './home.html'
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:78:1)
    at meteorInstall.imports.ui.pages.home.home.js (imports/ui/pages/home/home.js:4:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.imports.ui.pages.home.home.tests.js (imports/ui/pages/home/home.tests.js:5:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at C:\Users\Sami\AppData\Local\Temp\meteor-test-run1p5dkpj\.meteor\local\build\programs\server\app\app.js:112:1
    at C:\Users\Sami\AppData\Local\Temp\meteor-test-run1p5dkpj\.meteor\local\build\programs\server\boot.js:283:10
    at Array.forEach (native)
```

The testing code is more or less copied from 
http://guide.meteor.com/testing.html#simple-blaze-unit-test

imports/ui/test-helpers.js:
```javascript
import { _ } from 'meteor/underscore';
import { Template } from 'meteor/templating';
import { Blaze } from 'meteor/blaze';
import { Tracker } from 'meteor/tracker';

const withDiv = function(callback) {
    const el = document.createElement('div');
    document.body.appendChild(el);
    try {
        callback(el);
    } finally {
        document.body.removeChild(el);
    }
};

export const withRenderedTemplate = function(template, data, callback) {
    withDiv((el) => {
        const ourTemplate = _.isString(template) ? Template[template] : template;
        Blaze.renderWithData(ourTemplate, data, el);
        Tracker.flush();
        callback(el);
    });
};
```

imports/ui/pages/home/home.tests.js:
```javascript
import { assert } from 'meteor/practicalmeteor:chai';
import { Template } from 'meteor/templating';

import { withRenderedTemplate } from '../../test-helpers.js';
import './home.js';

if (Meteor.isClient) {
    describe('home page', function () {
        it('Renders correctly', function () {
            withRenderedTemplate('home', {}, el => {
                assert.notEqual($(el).find().length, 0);
            });
        });
    });
}
```

I isolated the issue with a fresh project at
https://github.com/Brona123/meteor-mocha-bug

imports/ui/pages/home/home.js:
```javascript
import { Template } from 'meteor/templating';
import { ReactiveVar } from 'meteor/reactive-var';

import './home.html';

Template.home.onCreated(function helloOnCreated() {
    this.counter = new ReactiveVar(0);
});

Template.home.helpers({
    counter() {
        return Template.instance().counter.get();
    },
});

Template.home.events({
    'click button'(event, instance) {
        // increment the counter when button is clicked
        instance.counter.set(instance.counter.get() + 1);
    },
});
```

imports/ui/pages/home/home.html:
```html
<head>
  <title>simple</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> home}}
  {{> info}}
</body>

<template name="home">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>

<template name="info">
  <h2>Learn Meteor!</h2>
  <ul>
    <li><a href="https://www.meteor.com/try">Do the Tutorial</a></li>
    <li><a href="http://guide.meteor.com">Follow the Guide</a></li>
    <li><a href="https://docs.meteor.com">Read the Docs</a></li>
    <li><a href="https://forums.meteor.com">Discussions</a></li>
  </ul>
</template>
```

When I'm testing parts of code where html is not imported (publications or methods),
the tests are executed just fine. But as soon as the import chain includes any html, this error is thrown. Using 'require' instead of 'import' did not help. Also when running the app in normal mode everything works just fine. Running Meteor version 1.3.2.4 on Windows 8.1 if that makes any difference.

**Comment by benjamn** [comment]
This is expected, for better or worse: `.html` files are not compiled on the server, and can't be imported by server code.

I believe this change will fix this problem in your reproduction repo:

```diff
diff --git a/imports/ui/pages/home/home.tests.js b/imports/ui/pages/home/home.tests.js
index 8522d7d..b7a6ea1 100644
--- a/imports/ui/pages/home/home.tests.js
+++ b/imports/ui/pages/home/home.tests.js
@@ -2,14 +2,15 @@ import { assert } from 'meteor/practicalmeteor:chai';
 import { Template } from 'meteor/templating';
 
 import { withRenderedTemplate } from '../../test-helpers.js';
-import './home.js';
 
 if (Meteor.isClient) {
-    describe('home page', function () {
-        it('Renders correctly', function () {
-            withRenderedTemplate('home', {}, el => {
-                assert.notEqual($(el).find().length, 0);
-            });
-        });
+  import './home.js';
+
+  describe('home page', function () {
+    it('Renders correctly', function () {
+      withRenderedTemplate('home', {}, el => {
+        assert.notEqual($(el).find().length, 0);
+      });
     });
+  });
 }
```

**Comment by Brona123** [comment]
Thank you, using 'require' inside the 'Meteor.isClient' -block was the proper solution!

**Comment by benjamn** [comment]
Ah, that's right, nested `import` statements won't work until Meteor 1.3.3 :)

**Comment by molinto** [comment]
Thank you :)

**Comment by bayodesegun** [comment]
@benjamn Thanks a lot. This just saved me from another sleepless night!
