### ISSUE TITLE
Babel error after update to 1.3.3 (from 1.3.2.4)

### ISSUE THREAD

**Issue by RWizard** [meteor/meteor#7208]
On Mac after update release in 1.3.3 error:
=> Errors prevented startup:                  
   
   While processing files with ecmascript (for target web.browser):
   native: Unexpected string
   at Object.parse (native)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler/babel-compiler.js:182:1)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler/babel-compiler.js:172:1)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler/babel-compiler.js:115:1)
   at BabelCompiler.<anonymous> (packages/babel-compiler/babel-compiler.js:40:1)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:39:1)
   
   
   While processing files with ecmascript (for target os.osx.x86_64):
   native: Unexpected string
   at Object.parse (native)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler/babel-compiler.js:182:1)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler/babel-compiler.js:172:1)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler/babel-compiler.js:115:1)
   at BabelCompiler.<anonymous> (packages/babel-compiler/babel-compiler.js:40:1)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:39:1)

.babelrc:
{
  "presets": [
    "es2015", 
    "stage-2", 
    "react"
  ],
  "plugins": [
    "babel-root-slash-import"
    "react-require"
  ]
}

package.json: (dev section)
"devDependencies": {
    "babel": "^6.0.0",
    "babel-plugin-react-require": "^2.0.0",
    "babel-polyfill": "^6.0.0",
    "babel-preset-es2015": "^6.5.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-2": "^6.5.0",
    "babel-root-slash-import": "^1.0.0",
    "babel-runtime": "^6.9.0",
    "chai": "^3.0.0",
    "enzyme": "^2.2.0",
    "eslint": "^2.7.0",
    "eslint-plugin-react": "^4.3.0",
    "jsdom": "^8.0.4",
    "mocha": "^2.0.0",
    "react-addons-test-utils": "^15.1.0",
    "sinon": "^1.17.0"
  }

**Comment by benjamn** [comment]
You need a comma between these plugins:
```js
"plugins": [
"babel-root-slash-import"
"react-require"
]
```

**Comment by RWizard** [comment]
Thanks! I thoughtless.
