### ISSUE TITLE
[1.3.3] unable to update to 1.3.3 on Windows 10 - invalid tar file

### ISSUE THREAD

**Issue by s-devaney** [meteor/meteor#7222]
```
C:\Users\Sam Devaney\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
Error: invalid tar file
    at Extract.Parse._startEntry (C:\Users\Sam Devaney\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:145:13)
    at Extract.Parse._process (C:\Users\Sam Devaney\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:127:12)
    at BlockStream.<anonymous> (C:\Users\Sam Devaney\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:47:8)
    at BlockStream.emit (events.js:95:17)
    at BlockStream._emitChunk (C:\Users\Sam Devaney\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:145:10)
    at BlockStream.flush (C:\Users\Sam Devaney\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:70:8)
    at BlockStream.end (C:\Users\Sam Devaney\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:66:8)
    at Extract.Parse.end (C:\Users\Sam Devaney\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:86:23)
    at Gunzip.onend (_stream_readable.js:502:10)
    at Gunzip.g (events.js:180:16)
    at Gunzip.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)
```

**Comment by s-devaney** [comment]
Restarting my machine fixed this issue
