### ISSUE TITLE
TypeError: Cannot call method 'displayName' of undefined

### ISSUE THREAD

**Issue by tatufrancis** [meteor/meteor#7257]
This issue also reported in previous versions. is it still on meteor? 

`=> Started proxy.                             
=> Started MongoDB.                           
                                              
/home/tatu/.meteor/packages/meteor-tool/.1.3.3_1.9tltar++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
TypeError: Cannot call method 'displayName' of undefined
    at SourceProcessorSet.addLegacyHandler (/tools/isobuild/build-plugin.js:142:64)
    at /tools/isobuild/build-plugin.js:172:12
    at Function._.each._.forEach (/home/tatu/.meteor/packages/meteor-tool/.1.3.3_1.9tltar++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at SourceProcessorSet.merge (/tools/isobuild/build-plugin.js:170:7)
    at /tools/isobuild/compiler.js:376:26
    at Array.forEach (native)
    at /tools/isobuild/compiler.js:372:26
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/compiler.js:368:16
    at /tools/isobuild/compiler.js:176:26
    at Array.forEach (native)
    at Function._.each._.forEach (/home/tatu/.meteor/packages/meteor-tool/.1.3.3_1.9tltar++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:171:5)
    at /tools/isobuild/bundler.js:2571:24
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2514:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
`

**Comment by laosb** [comment]
Do you mean #6648 ? This was not treated as a bug in fact. In #6648 it was considered the wrong behavior of user usage of `urigo:babel`, not Meteor itself.

**Comment by laosb** [comment]
If you think it's a bug, please provide a reproduce.

**Comment by kachkaev** [comment]
If you are using meteor-hmr, can it be because of [gadicc/meteor-hmr#121](https://github.com/gadicc/meteor-hmr/issues/121)?

**Comment by vancovver** [comment]
`/Users/user/.meteor/packages/meteor-tool/.1.3.3_1.1vvx39c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
TypeError: Cannot call method 'displayName' of undefined
    at SourceProcessorSet.addLegacyHandler (/tools/isobuild/build-plugin.js:142:64)
    at /tools/isobuild/build-plugin.js:172:12
    at Function._.each._.forEach (/Users/andyke/.meteor/packages/meteor-tool/.1.3.3_1.1vvx39c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at SourceProcessorSet.merge (/tools/isobuild/build-plugin.js:170:7)
    at /tools/isobuild/compiler.js:376:26
    at Array.forEach (native)
    at /tools/isobuild/compiler.js:372:26
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/compiler.js:368:16
    at /tools/isobuild/compiler.js:176:26
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/andyke/.meteor/packages/meteor-tool/.1.3.3_1.1vvx39c++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:171:5)
    at /tools/isobuild/bundler.js:2571:24
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2514:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
`

**Comment by vancovver** [comment]
Just following this tutorial and after adding meteortoys:allthings, got the above error:
https://www.youtube.com/watch?v=kCn_AnU91Dg&index=9&list=PLLnpHn493BHFYZUSK62aVycgcAouqBt7V

**Comment by vancovver** [comment]
I had manually added stylus package.  By removing that package, problem solved.

**Comment by abernix** [comment]
@tatufrancis Update on this issue?  Does the solution that @vancovver suggested work for you?

**Comment by abernix** [comment]
Closing due to no response.
