### ISSUE TITLE
Meteor run time error at 1.3

### ISSUE THREAD

**Issue by saurabh21shukla** [meteor/meteor#7269]
Hi,

I have install new meteor version on my system and facing issue when running new meteor app.

error detail on my console are as follow.

please provide some solution.  

E:\RND\meteardemo\Myapps\app1>meteor
[[[[[ ~\E\RND\meteardemo\Myapps\app1 ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   module.js:338:15: Cannot find module 'babel-helper-function-name'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\ecmascript\0.4.5\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\node_modules\babel-plugin-transform-es2015-classes\lib\loose.js:17:56)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\ecmascript\0.4.5\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\node_modules\babel-plugin-transform-es2015-classes\lib\index.js:56:38)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\ecmascript\0.4.5\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\index.js:12:6)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.getDefaults
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\ecmascript\0.4.5\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\options.js:30:15)
   at Object.getDefaultOptions (packages/babel-compiler/babel.js:9:1)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler/babel-compiler.js:95:1)
   at BabelCompiler.<anonymous> (packages/babel-compiler/babel-compiler.js:21:1)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:20:1)

   While processing files with ecmascript (for target os.windows.x86_32):
   module.js:338:15: Cannot find module 'babel-helper-function-name'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\ecmascript\0.4.5\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\node_modules\babel-plugin-transform-es2015-classes\lib\loose.js:17:56)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\ecmascript\0.4.5\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\node_modules\babel-plugin-transform-es2015-classes\lib\index.js:56:38)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\ecmascript\0.4.5\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteor\index.js:12:6)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Module.Mp.load
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.getDefaults
   (C:\Users\Saurabh.Shukla\AppData\Local\.meteor\packages\ecmascript\0.4.5\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\options.js:30:15)
   at Object.getDefaultOptions (packages/babel-compiler/babel.js:9:1)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler/babel-compiler.js:95:1)
   at BabelCompiler.<anonymous> (packages/babel-compiler/babel-compiler.js:21:1)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler/babel-compiler.js:20:1)

Thanks & Regards
Saurabh Shukla

**Comment by laosb** [comment]
Hi, this is exactly the case of #7247, which should be fixed in 1.3.4. Please refer to that issue and I'm closing this.

**Comment by saurabh21shukla** [comment]
Now its working!!  Thank You very much for superb support.
