### ISSUE TITLE
Filename containing dots? 'Cannot find module './issues/methods.issues.comment.js' 

### ISSUE THREAD

**Issue by Batistleman** [meteor/meteor#7280]
I'm getting this error when I try to deploy to production. (Not when running in dev.)

    Error: Cannot find module './issues/methods.issues.comment.js'
        at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:78:1)
        at meteorInstall.imports.api.server.api.js (imports/api/server.api.js:3:1)
        at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
        at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
        at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:18:1)
        at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
        at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
        at meteorInstall.server.main.js (server/main.js:1:1)
        at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
        at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)

I'm using 1.3.2.4

Can filenames contain dots?

**Comment by kachkaev** [comment]
Could you quickly check if all characters are lowercase in the file name? I remember having this magic error in production myself, it happened because the FS on my server was case-sensitive and in the dev env it was not.

**Comment by Batistleman** [comment]
Yes, everything is lower case...

I was wondering about the dots because _meteorInstall.imports.api.server.api.js_ seems to be the result of a _/imports/api/server.api.js_ ?

**Comment by Batistleman** [comment]
My bad, my deploy script contains a 
   
    git reset --hard origin/master

I did a rename from _Issues_ to _issues_ and it seems like it was not changed on the filesystem. Thanks for the hint!
