### ISSUE TITLE
1.3.4.1 Breaking all existing apps on 'meteor upgrade'   |  OSX

### ISSUE THREAD

**Issue by rjpalermo1** [meteor/meteor#7298]
OSX El Capitan
Version 10.11.5 (15F34)
Xcode Version 7.3.1 (7D1014)
NVM install Node v6.2.2 / npm 3.9.5

```
W20160625-09:02:26.940(-4)? (STDERR)
W20160625-09:02:27.057(-4)? (STDERR) /Users/me/.meteor/packages/meteor-tool/.1.3.4_1.1ignoa7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160625-09:02:27.057(-4)? (STDERR)            				throw(ex);
W20160625-09:02:27.057(-4)? (STDERR)            				      ^
W20160625-09:02:27.079(-4)? (STDERR) TypeError: undefined is not a function
W20160625-09:02:27.080(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.imports.helpers.js (packages/std:accounts-ui/imports/helpers.js:3:12)
W20160625-09:02:27.080(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/packages/modules-runtime.js:160:1)
W20160625-09:02:27.080(-4)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:89:1)
W20160625-09:02:27.080(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.imports.accounts_ui.js (packages/std:accounts-ui/imports/accounts_ui.js:2:1)
W20160625-09:02:27.081(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/packages/modules-runtime.js:160:1)
W20160625-09:02:27.081(-4)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:89:1)
W20160625-09:02:27.081(-4)? (STDERR)     at meteorInstall.node_modules.meteor.std:accounts-ui.main_server.js (packages/std:accounts-ui/main_server.js:2:1)
W20160625-09:02:27.081(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/packages/modules-runtime.js:160:1)
W20160625-09:02:27.081(-4)? (STDERR)     at require (packages/modules-runtime/packages/modules-runtime.js:89:1)
W20160625-09:02:27.082(-4)? (STDERR)     at node_modules/meteor/std:accounts-ui/node_modules/react-dom/index.js:3:1
=> Exited with code: 8
```

**Comment by rjpalermo1** [comment]
Been adding and removing packages one at a time.  Getting this error with package

std:accounts-basic

**Comment by rjpalermo1** [comment]
Had to downgrade to METEOR@1.3.3.1 to get past these...1.4  builds did not fix anything

**Comment by laosb** [comment]
It looks like a bug of std:accounts-basic,

**Comment by rjpalermo1** [comment]
Filed issue with package owner also...

https://github.com/studiointeract/accounts-basic/issues/3

**Comment by laosb** [comment]
Closing as it looks like a package problem. Please reopen if I'm wrong.

**Comment by c9s** [comment]
This seems also related to mongo
