### ISSUE TITLE
[1.3.4.*] TypeError: Cannot call method 'split' of undefined error

### ISSUE THREAD

**Issue by ThomasEley** [meteor/meteor#7311]
Since upgrading to 1.3.4 on Friday I have been receiving the following error. 

/home/thomas/.meteor/packages/meteor-tool/.1.3.4_1.1accegj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
TypeError: Cannot call method 'split' of undefined
    at Object.parse (/tools/utils/parse-stack.js:19:28)
    at Object.exception (/tools/utils/buildmessage.js:497:29)
    at /tools/isobuild/compiler-plugin.js:190:26
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/compiler-plugin.js:177:22
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:176:15
    at Function._.each._.forEach (/home/thomas/.meteor/packages/meteor-tool/.1.3.4_1.1accegj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:166:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:913:22)
    at /tools/isobuild/bundler.js:693:34
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:687:18)
    at /tools/isobuild/bundler.js:2538:14
    at /tools/isobuild/bundler.js:2627:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/thomas/.meteor/packages/meteor-tool/.1.3.4_1.1accegj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2626:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2519:31)
    at /tools/isobuild/bundler.js:2466:32
    at Object.withCache (/tools/fs/files.js:1440:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2466:16)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12

Upgrading to 1.3.4_1 has not helped the issue either.

**Comment by gugurete** [comment]
Same here

**Comment by abernix** [comment]
To anyone experiencing this problem, **please submit a complete reproduction for this issue**.  That snippet by itself is not enough to isolate the problem. [Read more information on reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

If you are unable to post a reproduction, please **at the very least provide Gist links** to your `package.json`, `.meteor/packages` and `.meteor/versions` files.  Also, please provide the version you were using attempting to upgrade in order to narrow down what might have changed.

**Comment by ThomasEley** [comment]
MY error was my project size becoming too big, branched my project and took out some section and all is working again.

**Comment by abernix** [comment]
Good to know!  Sounds _somewhat_ similar to #6926 (specifically https://github.com/meteor/meteor/issues/6926#issuecomment-219976204, https://github.com/meteor/meteor/issues/6926#issuecomment-220497585 and https://github.com/meteor/meteor/issues/6926#issuecomment-227403206).  There are some solutions in that issue for those that might need it!
