### ISSUE TITLE
Bcrypt fails with release-1.4

### ISSUE THREAD

**Issue by zvictor** [meteor/meteor#7331]
Meteor fails to build Bcrypt. Tried with both 1.4.0-beta.5 and 1.4.0-beta.6, running OS X El Capitan.

I could see that a similar issue has been [reported before](https://github.com/meteor/meteor/pull/7218#issuecomment-228522346), and [changes](https://github.com/meteor/meteor/commit/27b1d38a5e7c1c515aac5bb0cf8136fb522d60c1) have been made since then.

I am posting it still because I assume it is a new error, probably because of my use of `anaconda` instead of regular `python`.

**Console**
```haskell
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading package npm-bcrypt@0.8.7:
   error: Command failed: /Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm rebuild
   gyp ERR! configure error
   gyp ERR! stack Error: Python executable "/Users/zvictor/anaconda/bin/python" is v3.5.1, which is not supported by gyp.
   gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
   gyp ERR! stack     at failPythonVersion (/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:14)
   gyp ERR! stack     at /Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:395:9
   gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
   gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
   gyp ERR! stack     at emitOne (events.js:77:13)
   gyp ERR! stack     at Socket.emit (events.js:169:7)
   gyp ERR! stack     at Pipe._onclose (net.js:486:12)
   gyp ERR! System Darwin 15.2.0
   gyp ERR! command "/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
   "rebuild"
   gyp ERR! cwd /Users/zvictor/.meteor/packages/npm-bcrypt/.0.8.7.1tl7gcv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1eespw9/node_modules/bcrypt
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.3.1
   gyp ERR! not ok

   npm ERR! Darwin 15.2.0
   npm ERR! argv "/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.2
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /Users/zvictor/.meteor/packages/npm-bcrypt/.0.8.7.1tl7gcv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1eespw9/npm-debug.log
   gyp ERR! configure error
   gyp ERR! stack Error: Python executable "/Users/zvictor/anaconda/bin/python" is v3.5.1, which is not supported by gyp.
   gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
   gyp ERR! stack     at failPythonVersion (/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:14)
   gyp ERR! stack     at /Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:395:9
   gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
   gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
   gyp ERR! stack     at emitOne (events.js:77:13)
   gyp ERR! stack     at Socket.emit (events.js:169:7)
   gyp ERR! stack     at Pipe._onclose (net.js:486:12)
   gyp ERR! System Darwin 15.2.0
   gyp ERR! command "/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
   "rebuild"
   gyp ERR! cwd /Users/zvictor/.meteor/packages/npm-bcrypt/.0.8.7.1tl7gcv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1eespw9/node_modules/bcrypt
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.3.1
   gyp ERR! not ok

   npm ERR! Darwin 15.2.0
   npm ERR! argv "/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/zvictor/.meteor/packages/meteor-tool/.1.4.0-beta.6.1kwputp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.2
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /Users/zvictor/.meteor/packages/npm-bcrypt/.0.8.7.1tl7gcv++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-1eespw9/npm-debug.log
```

**Comment by zvictor** [comment]
Reproducible steps:

```shell
$ meteor create bcryptBug
$ cd bcryptBug
$ echo METEOR@1.4-beta.6 > .meteor/release
$ meteor add accounts-password # throws the error
```

**Comment by seeekr** [comment]
I think this is the line of output relevant here:

```
gyp ERR! stack Error: Python executable "/Users/zvictor/anaconda/bin/python" is v3.5.1, which is not supported by gyp.
```

You need Python 2.x for node-gyp, not 3.x. I don't think there will be a solution for that coming from Meteor. You'll have to make sure your toolchain has everything required if you want to build native packages. Meteor package authors will also be able to precompile native packages (or something of that sort) and for those a local compiler toolchain (incl. node-gyp) won't be necessary, but for now I believe there is no way around that.

**Comment by benjamn** [comment]
Official instructions: https://github.com/nodejs/node-gyp#installation

Similar question and answer (from me) on the forums: https://forums.meteor.com/t/announcing-meteor-1-3-4-1-and-1-4-beta-1/25460/13?u=benjamn

**Comment by benjamn** [comment]
If you install Python 2.7 somewhere else, you should be able to `export PYTHON=/path/to/python27` to override the path that `meteor npm` uses by default.

**Comment by zvictor** [comment]
Thank you for the assistance. It solves the issue for me.

**Comment by omasopust** [comment]
Still getting this trying to update to 1.4-beta.7 on Windows

Windows 10 Pro; Python27 installed and added to npm config; installed MS Build tools
also tried `set PYTHON=/path/to/python27`

What am I missing?


```
meteor update --release 1.4-beta.7
C:\Users\Ondra\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle
=> Errors while initializing project:

While loading package npm-bcrypt@0.8.7:
error: Command failed: C:\Users\Ondra\AppData\Local\.meteor\packages\meteor-tool\1.4.0-beta.7\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd rebuild
gyp
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\Ondra\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.7\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Ondra\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.7\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ondra\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1kfib5h\npm-debug.log
gyp
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\Ondra\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.7\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Ondra\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-beta.7\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     
C:\Users\Ondra\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\npm\node_modules\.temp-1kfib5h\npm-debug.log
```

`npm-debug.log` from the last line is not there. In fact, whole `.temp-1kfib5h` folder is missing.

**Comment by seeekr** [comment]
@omasopust To me it looks like this is not the same issue. Yes, it's triggered by bcrypt native compilation, too, but in the OP's case it was about Python 2.7 missing, but it's not clear what the actual problem is in your case. I can't find anything in the output that would give me an immediate idea of what might be wrong, but I'm not very familiar with Meteor (and Nodejs) on Windows.
