### ISSUE TITLE
Error: You've been logged out by the server. Please log in again. [403]

### ISSUE THREAD

**Issue by Grep-Juub** [meteor/meteor#7383]
Hello Guys, 

I'm using Meteor for quite a time now and recently I've an issue with some of my app wich are in the lastest versions of Meteor (1.3.4_4), here you can see the paste of the error I've collected with Kadira Debug Tools,
It is a bit annoying for my user who keep being disconnected for no reasons, and honestly I don't know if it's something I did wrong or not.

`Error: You've been logged out by the server. Please log in again. [403]
    at [object Object].defaultResumeLoginHandler (packages/accounts-base/accounts_server.js:999:14)
    at [object Object].<anonymous> (packages/accounts-base/accounts_server.js:964:38)
    at packages/accounts-base/accounts_server.js:470:32
    at tryLoginMethod (packages/accounts-base/accounts_server.js:247:14)
    at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:467:18)
    at [object Object].methods.login (packages/accounts-base/accounts_server.js:530:27)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)`

[Packages List](http://pastebin.com/PEnRTR1B)

**Comment by abernix** [comment]
Without a reproduction this is not likely to get tracked down or resolved.  It seems to be an isolated problem in your setup.  What version were you on before 1.3.4.4 that it didn't happen on?  Can you come up with a reproduction?

**Comment by laosb** [comment]
Close due to inactivity. If someone found this again, please open a new issue.
