### ISSUE TITLE
Arguments to path.resolve must be strings - minifying app stylesheet

### ISSUE THREAD

**Issue by davidworkman9** [meteor/meteor#7394]
I don't have a reproduction but as seen [here](https://forums.meteor.com/t/arguments-to-path-resolve-must-be-strings-minifying-app-stylesheet/26213) I'm not the only one running into this after upgrading to 1.3.4.4.

**Comment by abernix** [comment]
It's my understanding based on that forum thread that the issue is related to functionality needing to be changed within [`bevanhunt:leafletjs`](https://atmospherejs.com/bevanhunt/leaflet) which @sewdn addressed with bevanhunt/meteor-leaflet#68.

**If you're experiencing this issue**, please run `meteor update bevanhunt:leafletjs` to obtain version 2.0.1 and this problem should be resolved.

If this is not correct and this is in fact a bug with Meteor, please ping me back and we can reopen this!

**Comment by dburles** [comment]
fwiw I have an app that also now dumps this error and I am not using `bevanhunt:leafletjs`

**Comment by dburles** [comment]
I'm on Meteor 1.4. It's difficult to track the location of the cause of the error.

```
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   path.js:8:11: Path must be a string. Received null
   at assertPath (path.js:8:11)
   at Object.posix.relative (path.js:496:3)
   at pathRelative (packages/minifier-css/minifier.js:206:1)
   at packages/minifier-css/minifier.js:165:1
   at Array.forEach (native)
   at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
   at packages/minifier-css/minifier.js:122:1
   at Array.forEach (native)
   at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
   at rewriteRules (packages/minifier-css/minifier.js:99:1)
   at Object.CssTools.rewriteCssUrls (packages/minifier-css/minifier.js:85:1)
   at packages/minifier-css/minifier.js:55:1
   at Array.forEach (native)
   at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
   at Object.CssTools.mergeCssAsts (packages/minifier-css/minifier.js:32:1)
   at packages/minifyStdCSS/plugin/minify-css.js:79:1
   at CssToolsMinifier.processFilesForBundle (packages/minifyStdCSS/plugin/minify-css.js:17:1)
   
   
=> Your application has errors. Waiting for file change.
```
