### ISSUE TITLE
{{ > loginButtons }} failing.  Meteor 1.3.4.4

### ISSUE THREAD

**Issue by switheyw** [meteor/meteor#7428]
I  don't have the time at the moment to try to reproduce the issue.  What I will do over the next few hours is try to reproduce issue on my own in a simple program.   Otherwise I will install my app in a repository.  I wonder what I created that foils accounts-ui?

I was trying to create my own login system, but failed. When I went to fall back on the accounts-ui package, {{ > loginButtons }} also failed in the same way.

The callback function reported error number 500. I'll try to find the callback error object if you think it would do any good.

The traceback:

=> App running at: http://localhost:3000/
Exception while invoking method 'createUser' Error: insert requires an argument
at [object Object].insert (packages/mongo/collection.js:470:11)
at [object Object].Mongo.Collection.(anonymous function) as insert
at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1257:25)
at _createUser (packages/accounts-password/password_server.js:998:25)
at packages/accounts-password/password_server.js:1029:20
at tryLoginMethod (packages/accounts-base/accounts_server.js:247:14)
at AccountsServer.Ap._loginMethod (packages/accounts-base/accounts_server.js:380:5)
at [object Object].createUser (packages/accounts-password/password_server.js:1015:19)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
at packages/ddp-server/livedata_server.js:711:19

The versions of some of the account packaages

accounts-base@1.2.8
accounts-password@1.1.12
accounts-ui@1.1.9
accounts-ui-unstyled@1.1.12
aldeed:collection2@2.9.1
aldeed:collection2-core@1.1.1
aldeed:schema-deny@1.0.1
aldeed:schema-index@1.0.1
aldeed:simple-schema@1.5.3

**Comment by laosb** [comment]
How does it fail? Please provide more detailed information like the platform, error Stack trace, etc.

**Comment by switheyw** [comment]
I was trying to create my own login system, but failed.  When I went to fall back on the accounts-ui package, {{ > loginButtons }} also failed in the same way. 

The callback function reported error number 500.  I'll try to find the callback error object if you think it would do any good.

The traceback:

=> App running at: http://localhost:3000/
Exception while invoking method 'createUser' Error: insert requires an argument
at [object Object].insert (packages/mongo/collection.js:470:11)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1257:25)
at _createUser (packages/accounts-password/password_server.js:998:25)
at packages/accounts-password/password_server.js:1029:20
at tryLoginMethod (packages/accounts-base/accounts_server.js:247:14)
at AccountsServer.Ap._loginMethod (packages/accounts-base/accounts_server.js:380:5)
at [object Object].createUser (packages/accounts-password/password_server.js:1015:19)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
at packages/ddp-server/livedata_server.js:711:19

The versions of some of the account packaages

accounts-base@1.2.8
accounts-password@1.1.12
accounts-ui@1.1.9
accounts-ui-unstyled@1.1.12
aldeed:collection2@2.9.1
aldeed:collection2-core@1.1.1
aldeed:schema-deny@1.0.1
aldeed:schema-index@1.0.1
aldeed:simple-schema@1.5.3

**Comment by laosb** [comment]
That's weird.

**Comment by abernix** [comment]
@switheyw Please edit the text on your original issue, remove the boilerplate information and update it with the information that the text is asking for.   Specifically:

> An isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)

Otherwise this will be closed as lacking information to reproduce the problem.

**Comment by switheyw** [comment]
Hi all - 
My app has some sensitive survey related questions and I don't want to release it to a public repository.  Obviously the accounts system is working everyplace else, even on an earlier version of my current app.   So, either close it down or i'll just remove it tomorrow.  I'll track it down and let you know if it's anything to be concerned with.
