### ISSUE TITLE
Failed to start Meteor 1.2.1 on Ubuntu 14.04 64 bit (Fibers related)  

### ISSUE THREAD

**Issue by xvendo** [meteor/meteor#7432]
I restarted Meteor again, and It's working now. But It seems unstable. It worries me a bit, because that should not happen.

## Operating System
Lubuntu 14.04 LTS 64bit

## Meteor Tool
Bundle Version: 0.6.18
SymLink to /home/paul/.meteor/packages/meteor-tool/.1.3.4_4.845h3e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle

## Installed Packages
accounts-base@1.2.2
accounts-facebook@1.0.6
accounts-google@1.0.6
accounts-oauth@1.1.8
accounts-password@1.1.4
accounts-twitter@1.0.6
agustino:purecss@1.6.0
alanning:roles@1.2.15
aldeed:simple-schema@1.3.3
amplify@1.0.0
arillo:flow-router-helpers@0.5.2
autoupdate@1.2.4
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
cfs:access-point@0.1.49
cfs:base-package@0.0.30
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.17
cfs:graphicsmagick@0.0.18
cfs:gridfs@0.0.33
cfs:http-methods@0.0.32
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:standard-packages@0.5.9
cfs:storage-adapter@0.2.3
cfs:tempstore@0.1.5
cfs:ui@0.1.3
cfs:upload-http@0.0.20
cfs:worker@0.1.4
chart:chart@1.0.1-beta.4
check@1.1.0
chrismbeckett:toastr@2.1.2_1
chuangbo:cookie@1.1.0
coffeescript@1.0.11
cosmos:browserify@0.9.4
dburles:google-maps@1.1.5
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.2
ddp-rate-limiter@1.0.0
ddp-server@1.2.2
deps@1.0.9
diff-sequence@1.0.1
ecmascript@0.1.6
ecmascript-runtime@0.2.6
ejson@1.0.7
email@1.0.8
es5-shim@4.1.14
facebook@1.2.2
fastclick@1.0.7
fortawesome:fontawesome@4.5.0
geojson-utils@1.0.4
gfk:mailgun-api@1.1.0
google@1.1.7
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
jeremy:geocomplete@1.7.0
jquery@1.11.4
kadira:blaze-layout@2.3.0
kadira:dochead@1.4.0
kadira:flow-router@2.10.1
launch-screen@1.0.4
less@2.5.1
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
matb33:bootstrap-base@10.0.0
matb33:bootstrap-button-js@10.0.0
matb33:bootstrap-buttons@10.0.0
meteor@1.1.10
meteor-base@1.0.1
meteorhacks:fast-render@2.14.0
meteorhacks:inject-data@2.0.0
meteorhacks:kadira@2.29.1
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
meteorspark:util@0.2.0
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
momentjs:moment@2.11.2
mongo@1.1.3
mongo-id@1.0.1
mongo-livedata@1.0.9
mrgalaxy:stripe@2.2.2
mrt:moment@2.8.1
mrt:moment-timezone@0.2.1
npm-bcrypt@0.7.8_2
npm-mongo@1.4.39_1
oauth@1.1.6
oauth1@1.1.5
oauth2@1.1.5
observe-sequence@1.0.7
ongoworks:pdf@1.1.1
ordered-dict@1.0.4
promise@0.5.1
raix:eventemitter@0.1.3
random@1.0.5
rate-limit@1.0.0
reactive-dict@1.1.3
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
risul:moment-timezone@0.5.0_5
routepolicy@1.0.6
sacha:spin@2.3.1
service-configuration@1.0.5
session@1.1.1
sewdn:masked-input@1.0.6
sha@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.2
tap:i18n@1.8.2
tap:i18n-ui@0.8.0
templating@1.1.5
templating-tools@1.0.0
tmeasday:publish-counts@0.7.3
tomwasd:flow-router-autoscroll@0.0.2
tracker@1.0.9
twitter@1.1.5
ui@1.0.8
underscore@1.0.4
url@1.0.5
webapp@1.2.3
webapp-hashing@1.0.5
xvendo:barcoder@0.0.3
xvendo:clipboardjs@0.0.1
zimme:active-route@2.3.2

## Error Report Details

/home/paul/.meteor/packages/meteor-tool/.1.1.10.ese5d4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
abort() at Error
    at jsStackTrace (packages/logic-solver/minisat.js:3:1)
    at stackTrace (packages/logic-solver/minisat.js:3:1)
    at Object.abort (packages/logic-solver/minisat.js:33:1)
    at _abort (packages/logic-solver/minisat.js:3:1)
    at fe (packages/logic-solver/minisat.js:11:1)
    at Ud (packages/logic-solver/minisat.js:7:1)
    at qc (packages/logic-solver/minisat.js:7:1)
    at Nb (packages/logic-solver/minisat.js:7:1)
    at Kb (packages/logic-solver/minisat.js:7:1)
    at Dc (packages/logic-solver/minisat.js:7:1)
    at Object.dd [as _addClause] (packages/logic-solver/minisat.js:7:1)
    at packages/logic-solver/minisat_wrapper.js:74:1
    at Object._native.savingStack (packages/logic-solver/minisat_wrapper.js:37:1)
    at [object Object].MiniSat.addClause (packages/logic-solver/minisat_wrapper.js:68:1)
    at [object Object].Logic.Solver.solve (packages/logic-solver/logic.js:1326:1)
    at [object Object].Logic.Solver.solveAssuming (packages/logic-solver/logic.js:1369:1)
    at minMaxWS (packages/logic-solver/optimize.js:38:1)
    at [object Object].Logic.Solver.minimizeWeightedSum (packages/logic-solver/optimize.js:139:1)
    at packages/constraint-solver/solver.js:368:1
    at Function.time (/tools/tool-env/profile.js:232:28)
    at [object Object].CS.Solver.minimize (packages/constraint-solver/solver.js:352:1)
    at [object Object].CS.Solver.minimize (packages/constraint-solver/solver.js:346:1)
    at [object Object].CS.Solver._getAnswer (packages/constraint-solver/solver.js:731:1)
    at packages/constraint-solver/solver.js:599:1
    at Function.time (/tools/tool-env/profile.js:232:28)
    at [object Object].CS.Solver.getAnswer (packages/constraint-solver/solver.js:598:1)
    at packages/constraint-solver/constraint-solver.js:121:1
    at Object.Logic.disablingAssertions (packages/logic-solver/logic.js:45:1)
    at Function.CS.PackagesResolver._resolveWithInput (packages/constraint-solver/constraint-solver.js:120:1)
    at [object Object].CS.PackagesResolver.resolve (packages/constraint-solver/constraint-solver.js:82:1)
    at /tools/project-context.js:497:35
    at time (/tools/tool-env/profile.js:232:28)
    at Function.run (/tools/tool-env/profile.js:377:12)
    at /tools/project-context.js:493:19
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/project-context.js:466:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._.extend._resolveConstraints (/tools/project-context.js:465:13)
    at /tools/project-context.js:257:35
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (/tools/project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:240:10)
    at /tools/runners/run-app.js:517:29
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at bundleApp (/tools/runners/run-app.js:516:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by abernix** [comment]
What is this in relation to?  Your other issue #7405?

**Comment by xvendo** [comment]
No there is no relation. New Issue. But it's strongly fibers related.

**Comment by abernix** [comment]
Many things in Meteor happen within Fibers; even though it shows `fibers/future.js` in the error does not indicate an error in Fibers.

There isn't anything included in this issue to help debug your problem though.  When did you get this error?  What were you doing?  Does it happen on an empty project or only on your full application?  Can you provide a reproduction?  How often does it happen?

**Comment by laosb** [comment]
Close due to inactivity. If someone found this again, please open a new issue or comment below.
