### ISSUE TITLE
1.3.5.1 breaks CI build: cross-device link not permitted

### ISSUE THREAD

**Issue by Ben305** [meteor/meteor#7435]
With the update to 1.3.5.1 the CI build is broken (updated from 1.3.4.4). When the command `meteor test --settings settings-development.json --driver-package dispatch:mocha-phantomjs --port 3010 --once` is run, the builds fails.

<pre>
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.

/root/.meteor/packages/ecmascript/.0.4.8.rpx2jv++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
            ^
Error: EXDEV, cross-device link not permitted '/root/.meteor/packages/fourseven_scss/.3.8.0_1.1jpm3v9++os.linux.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.linux.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass'
    at Object.fs.renameSync (fs.js:555:18)
    at Object.wrapper [as rename] (/tools/fs/files.js:1379:35)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:819:11)
    at /tools/isobuild/meteor-npm.js:251:11
    at Array.forEach (native)
    at Object.rebuildIfNonPortable (/tools/isobuild/meteor-npm.js:250:17)
    at /tools/isobuild/bundler.js:409:19
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.5uec5e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at Function.readDirsFromJSON (/tools/isobuild/bundler.js:408:9)
    at /tools/isobuild/bundler.js:1967:34
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.5uec5e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Function.readFromDisk (/tools/isobuild/bundler.js:1959:7)
    at Object.readJsImage (/tools/isobuild/bundler.js:2848:18)
    at /tools/isobuild/isopack.js:954:28
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.5uec5e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Isopack._loadUnibuildsFromPath (/tools/isobuild/isopack.js:951:7)
    at Isopack._.extend.initFromPath (/tools/isobuild/isopack.js:885:17)
    at /tools/isobuild/isopack-cache.js:286:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/isopack-cache.js:272:24
    at Function.time (/tools/tool-env/profile.js:305:10)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:262:15)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:213:12)
    at /tools/isobuild/isopack-cache.js:241:11
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.5uec5e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:240:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:213:12)
    at /tools/isobuild/isopack-cache.js:241:11
    at Array.forEach (native)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.5uec5e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:240:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.3.5_1.5uec5e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:822:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:821:18)
    at /tools/project-context.js:284:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:274:18)
    at /tools/project-context.js:266:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:265:13)
    at /tools/runners/run-app.js:557:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:556:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12

</pre>

The build/tests are executed in a docker container, which contains a Meteor installation (in this case, Meteor 1.3.4.4 is installed)

cc @benjamn

**Comment by abernix** [comment]
Are your Meteor installation and the Git checkout of your project on different actual devices on the filesystem?

**Comment by Ben305** [comment]
I'm not sure how GitLab CI handles this, but actually I have build a custom docker image that contains a Meteor installation (installed via install script). GitLab CI runner uses this container, sends a build script to the container, checks out the code and runs the script.

This has been working since 1.2.1.

**Comment by abernix** [comment]
It sounds like GitLab is checking out your code onto one partition while your Meteor installation is on another.  Then Meteor 1.3.5.1 comes along and tries to rename across the partitions and fails.  Perhaps this requires something like [mv NPM](https://www.npmjs.com/package/mv) instead.

Marking as confirmed even though I don't have a reproduction since this sounds probable.

**Comment by Ben305** [comment]
@abernix _Impact:few_ doesn't feel right here. Meteor 1.3.5.1 breaks tests and builds for everyone who is using GitLab CI. For me, it's a blocker because all my tests aren't executed any longer and my deployment doesn't work any more, too.

**Comment by abernix** [comment]
You are the first to report this issue.  It's impact is `few` until proven otherwise.  Realistically, I don't know how many of Meteor's users are running CI within GitLab (out of the dozens of CI providers) and with the particular configuration you're using.  I fully expect folks to report in here soon if there's a huge footprint here – at which point the label will change.  Also, you shouldn't perceive that label as "won't fix", "not going to get fixed" or even that it's not going to get attention.

**Comment by abernix** [comment]
Also, [looking at the code throwing the error](https://github.com/meteor/meteor/blob/78af10a047ad60b8f26cbbe2308ab210675ba7ea/tools/isobuild/meteor-npm.js#L174-L257), the step is only running in order to rebuild binary dependencies that have to be re-built.  Perhaps it's possible to work around this if your `node_modules` don't need to be rebuilt.  As a temporary work around, you might be able to try adding some commands to your CI setup before `test-packages`.  Namely:

* `rm -rf node_modules`
* `meteor npm install`

Might be worth a shot if you're stuck!

**Comment by Ben305** [comment]
The node_modules folder is cached and restored before each build, so the binaries should already have been built, since the node version hasn't changed from 1.3.4.4 to 1.3.5.1

**Comment by abernix** [comment]
I understand that's probably what is happening, however,  if you're receiving that error then Meteor has detected some version of some NPM with binary dependencies that it wants to rebuild – and you can see there is a fair bit of code in place to make sure that it doesn't rebuild unnecessarily.  This doesn't only mean `node` versions but the versions of anything returned from `process.versions` (i.e. `openssl`, `zlib`, `v8`, etc.).

Anyhow, I was merely offering a suggestion for how to potentially move along before a fix for your problem is available.  I'm still curious if my above suggestion works for you.

**Comment by Ben305** [comment]
I have added `rm -rf node_modules` to the build script, but the error still occurs.

**Comment by abernix** [comment]
Ok, but did you add `meteor npm install`?

> * `rm -rf node_modules`
> * `meteor npm install`

**Comment by benjamn** [comment]
The code in question (`files.renameDirAlmostAtomically` called by `rebuildIfNonPortable`) was introduced in Meteor 1.3.3, so I strongly suspect this is not a regression between 1.3.4.4 and 1.3.5.1. Perhaps the GitLab CI environment has changed recently?

**Comment by Ben305** [comment]
@benjamn Nothing has changed in the CI environment recently. The used docker image has been built when 1.3.4.4 was relased, and today all builds except the branch that contained the update to 1.3.5.1 were executed successfully.

I have update the docker image so that it comes with Meteor 1.3.5.1, and now the branch with 1.3.5.1 can be built successfully, and other branches that are still using 1.3.4.4 are also working. So I will close this ticket.

@abernix I would like to thank you for your work here, it's great to get feedback so fast!

**Comment by KevinMarzec** [comment]
I am getting this error with Jenkins after upgrading to 1.3.5.5:

```
/var/lib/jenkins/.meteor/packages/meteor-tool/.1.3.4_4.1c6gk60++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/dev-bundle.js:87
        var tool = JSON.parse(data.content).tool;
                                  ^
TypeError: Cannot read property 'content' of undefined
    at Statement.<anonymous> (/var/lib/jenkins/.meteor/packages/meteor-tool/.1.3.4_4.1c6gk60++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/dev-bundle.js:87:35)
Build step 'Execute shell' marked build as failure
```

**Comment by Ben305** [comment]
@KevinMarzec Install Meteor 1.3.5.1 on Jenkins, and the error will be gone

**Comment by KevinMarzec** [comment]
@Ben305 thanks, should have tried that earlier, worked perfectly :)
