### ISSUE TITLE
[1.3.5.1] Error: EEXIST, file already exists 'Z:\Temp\mt-eq6yvt'

### ISSUE THREAD

**Issue by JSReligion** [meteor/meteor#7442]
OS win 7x64;
meteor (METEOR@1.3.5.1) just reinstalled;
plugins:
allow-deny@1.0.5
autoupdate@1.2.11
babel-compiler@6.8.5
babel-runtime@0.1.9_1
base64@1.0.9
binary-heap@1.0.9
blaze@2.1.8
blaze-html-templates@1.0.4
blaze-tools@1.0.9
boilerplate-generator@1.0.9
caching-compiler@1.0.6
caching-html-compiler@1.0.6
callback-hook@1.0.9
check@1.2.3
ddp@1.2.5
ddp-client@1.2.9
ddp-common@1.2.6
ddp-server@1.2.10
deps@1.0.12
diff-sequence@1.0.6
ecmascript@0.4.8
ecmascript-runtime@0.2.12
ejson@1.0.12
es5-shim@4.5.13
fastclick@1.0.12
geojson-utils@1.0.9
hot-code-push@1.0.4
html-tools@1.0.10
htmljs@1.0.10
http@1.1.8
id-map@1.0.8
jquery@1.11.9
launch-screen@1.0.12
livedata@1.0.18
logging@1.0.14
meteor@1.1.16
meteor-base@1.0.4
minifier-css@1.1.13
minifier-js@1.1.13
minimongo@1.0.17
mobile-experience@1.0.4
mobile-status-bar@1.0.12
modules@0.6.5
modules-runtime@0.6.5
mongo@1.1.9_1
mongo-id@1.0.5
npm-mongo@1.4.45
observe-sequence@1.0.12
ordered-dict@1.0.8
promise@0.7.3
random@1.0.10
reactive-dict@1.1.8
reactive-var@1.0.10
reload@1.1.10
retry@1.0.8
routepolicy@1.0.11
session@1.1.6
spacebars@1.0.12
spacebars-compiler@1.0.12
standard-minifier-css@1.0.8
standard-minifier-js@1.0.8
templating@1.1.14
templating-tools@1.0.4
tracker@1.0.15
ui@1.0.11
underscore@1.0.9
url@1.0.10
webapp@1.2.11
webapp-hashing@1.0.9

```
C:\Users\work\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x
86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise
\promise_server.js:165
      throw error;
            ^
Error: EEXIST, file already exists 'Z:\Temp\mt-eq6yvt'
    at Object.fs.renameSync (fs.js:555:18)
    at wrapper (C:\tools\fs\files.js:1379:35)
    at Object.files.rename (C:\tools\fs\files.js:1518:9)
    at Object.files.extractTarGz (C:\tools\fs\files.js:732:9)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)

    at [object Object]._downloadBuildToTempDir (C:\tools\packaging\tropohouse.js
:314:20)
    at C:\tools\packaging\tropohouse.js:495:39
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:491:24
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\work\AppData\Local\.meteor\packages\m
eteor-tool\1.3.5_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\u
nderscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:490:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:448:20)
    at C:\tools\packaging\tropohouse.js:605:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\work\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.wi
ndows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-
promise\fiber_pool.js:32:39
```

**Comment by laosb** [comment]
How about deleting the `Z:\Temp\mt-eq6yvt`?

**Comment by JSReligion** [comment]
deleting does not helping, just same like reinstall meteor or create new project, when you trying to add some new addons, its crushes with similar errors

**Comment by abernix** [comment]
Do you have a `TMPDIR`, `TMP`, or `TEMP` environment variable set that would be forcing you to use your Z: drive?  You can check by just running `SET` (or `SET T`).

I can potentially see why this might be happening but this doesn't seem like it would have started in 1.3.5.1 – has it worked for you in the past?

**Comment by JSReligion** [comment]
TEMP dir was moved to RAM disk
I tried to run project on home pc (different is just its on win8.1), and its looks working fine..
But, then i returns to previous work pc and run meteor update, still same issues;
I double checked that is no files in this TEMP dir is exist, and its have enough space;
```
E:\meteor\app>meteor update
This project is already at Meteor 1.3.5.1, the latest release.

C:\Users\work\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: EEXIST, file already exists 'Z:\Temp\mt-1a4cm9g'
    at Object.fs.renameSync (fs.js:555:18)
    at wrapper (C:\tools\fs\files.js:1379:35)
    at Object.files.rename (C:\tools\fs\files.js:1518:9)
    at Object.files.extractTarGz (C:\tools\fs\files.js:732:9)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)
    at [object Object]._downloadBuildToTempDir (C:\tools\packaging\tropohouse.js:314:20)
    at C:\tools\packaging\tropohouse.js:495:39
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:491:24
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\work\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:490:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:448:20)
    at C:\tools\packaging\tropohouse.js:605:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\work\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:32:39
```

**Comment by abernix** [comment]
Please try updating to Meteor 1.4.0.1 and see if this problem improves for you.  Also, please try a completely fresh reinstall using these steps:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.
* Install fresh 1.3.4.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

**Comment by abernix** [comment]
I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  Would be happy to reopen it if you come up with some additional details that are helpful in resolving it! :)
