### ISSUE TITLE
[1.4] Error: minifier.js: Cannot call method 'replace' of null

### ISSUE THREAD

**Issue by nnn** [meteor/meteor#7446]
After update to Meteor 1.3.5.1 and even to 1.4 getting this:

```
Errors prevented startup:

While minifying app stylesheet:
packages/minifier-css/minifier.js:184:1: Cannot call method 'replace' of null
  at toOSPath (packages/minifier-css/minifier.js:184:1)
  at pathRelative (packages/minifier-css/minifier.js:205:1)
  at packages/minifier-css/minifier.js:164:1
  at Array.forEach (native)
  at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
  at packages/minifier-css/minifier.js:122:1
  at Array.forEach (native)
  at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
  at rewriteRules (packages/minifier-css/minifier.js:99:1)
  at Object.CssTools.rewriteCssUrls (packages/minifier-css/minifier.js:85:1)
  at packages/minifier-css/minifier.js:55:1
  at Array.forEach (native)
  at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
  at Object.CssTools.mergeCssAsts (packages/minifier-css/minifier.js:32:1)
  at packages/minifyStdCSS/plugin/minify-css.js:79:1
  at CssToolsMinifier.processFilesForBundle (packages/minifyStdCSS/plugin/minify-css.js:17:1)

```

NPM:
```
  "dependencies": {
    "clipboard": "^1.5.12",
    "crossfilter": "^1.3.12",
    "d3": "^3.5.17",
    "datatables": "^1.10.12",
    "dc": "^2.0.0-beta.30",
    "elasticsearch": "^11.0.1",
    "github": "^1.4.0",
    "jquery": "<3.0.0",
    "jquery.rateit": "^1.0.23",
    "js-yaml": "^3.6.1",
    "lodash": "^4.13.1",
    "meteor-node-stubs": "^0.2.3",
    "moment": "^2.14.1",
    "simple-statistics": "^2.1.0",
    "swagger-parser": "^3.4.1"
  }
```

Packages: 
```
less
accounts-base
accounts-password
aldeed:autoform
alanning:roles
aldeed:collection2
aldeed:simple-schema
fortawesome:fontawesome
raix:handlebar-helpers
cfs:standard-packages
cfs:gridfs
aldeed:template-extension
yogiben:helpers
iron:router
yogiben:autoform-modals
yogiben:pretty-email
multiply:iron-router-progress
spiderable
accounts-ui
jparker:gravatar
tap:i18n
useraccounts:bootstrap
service-configuration
juliancwirko:s-alert
juliancwirko:s-alert-stackslide
zimme:iron-router-active
matb33:collection-hooks
dburles:collection-helpers
reywood:publish-composite
natestrauser:animate-css
meteorhacks:subs-manager
fastclick
accounts-github
percolate:synced-cron
twbs:bootstrap
reactive-var
aldeed:tabular
benmgreene:moment-range
email
zimme:active-route
cfs:filesystem
mrt:flash-messages
brylie:leaflet-heat
pfafman:filesaver
raix:ui-dropped-event
brylie:accounts-admin-ui
brylie:first-user-admin
meteor-base
mobile-experience
mongo
blaze-html-templates
session
jquery
tracker
logging
reload
random
ejson
spacebars
check
useraccounts:iron-routing
pahans:inline-help
dandv:jquery-rateit
yogiben:autoform-file
harrison:papa-parse
olragon:uri-js
forwarder:autoform-wizard
universe:reactive-queries
ecmascript
simple:reactive-method
sacha:spin
tap:i18n-ui
kadira:dochead
gwendall:autoform-i18n
forwarder:autoform-wizard-iron-router
peppelg:bootstrap-3-modal
apinf:api-umbrella
standard-minifier-css
standard-minifier-js
vsivsi:file-collection
deepwell:bootstrap-datepicker2
```

**Comment by abernix** [comment]
* Does this happen when you create a new application too or only on your existing application?
* What version of Meteor were you on before you upgraded?
* What have you tried to do in order to fix the problem so far?
* Can you share a link to a reproduction repo on GitHub that demonstrates this problem?

**Comment by nnn** [comment]
This happens with existing application, referenced it to this issue.
I am trying to upgrade from 1.3.4.1. We are using lodash but also underscore is one of the dependencies. 
I have tried to remove underscore as npm - no affect. Tried to add underscore as meteor package - no affect.

**Comment by abernix** [comment]
How can I reproduce this easily and see this error on my own terminal?

**Comment by nnn** [comment]
No, it's enough if you just clone it and run meteor.

**Comment by nnn** [comment]
@abernix, same error with Meteor 1.4

**Comment by abernix** [comment]
Thanks for the updates.  I will try to take a look at this tomorrow!

**Comment by sdhrjm** [comment]
The issue is with the 'standard-minifier-css' and leaflet package. It exists in the previous versions also. If you remove standard-minifier-css package, it will work. Leaflet package authors should fix it. [Source](https://forums.meteor.com/t/arguments-to-path-resolve-must-be-strings-minifying-app-stylesheet/26213/11)

**Comment by nnn** [comment]
@sdhrjm, removing 'standard-minifier-css' is no an option. Removing Leaflet didn't help.

**Comment by abernix** [comment]
The problem is definitely with `bevanhunt:leaflet` as stated (by myself) in the forum post @sdhrjm linked to.  On this particular project, `brylie:leaflet-heat` depends on an old version of `bevanhunt:leaflet` so it's not updating to the 2.0.1 update.

It appears that the solution is just:

    meteor remove brylie:leaflet-heat
    meteor add bevanhunt:leaflet@2.0.1

...Though I don't know what `brylie:leaflet-heat` does or how important it is.

You should contact the package authors for further assistance.
