### ISSUE TITLE
Windows 10 : Error While loading package npm-bcrypt@0.8.7:

### ISSUE THREAD

**Issue by ThomsCass** [meteor/meteor#7497]
Hi,

I'm trying to launch my meteor 1.4 app on windows 10 but I got this error : 

```javascript
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading package npm-bcrypt@0.8.7:
   error: Command failed: C:\Users\Thomas\AppData\Local\.meteor\packages\meteor-
   gyp ERR! build error
   gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.
   gyp ERR! stack     at ChildProcess.onExit (C:\Users\Thomas\AppData\Local\.met
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_pro
   gyp ERR! System Windows_NT 10.0.10586
   gyp ERR! command "C:\\Users\\Thomas\\AppData\\Local\\.meteor\\packages\\meteo
   "C:\\Users\\Thomas\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt
   gyp ERR! cwd C:\Users\Thomas\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok

   npm ERR! Windows_NT 10.0.10586
   npm ERR! argv "C:\\Users\\Thomas\\AppData\\Local\\.meteor\\packages\\meteor-t
   "C:\\Users\\Thomas\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project wit
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     C:\Users\Thomas\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\
   gyp ERR! build error
   gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.
   gyp ERR! stack     at ChildProcess.onExit (C:\Users\Thomas\AppData\Local\.met
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_pro
   gyp ERR! System Windows_NT 10.0.10586
   gyp ERR! command "C:\\Users\\Thomas\\AppData\\Local\\.meteor\\packages\\meteo
   "C:\\Users\\Thomas\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt
   gyp ERR! cwd C:\Users\Thomas\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok

   npm ERR! Windows_NT 10.0.10586
   npm ERR! argv "C:\\Users\\Thomas\\AppData\\Local\\.meteor\\packages\\meteor-t
   "C:\\Users\\Thomas\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0\\mt
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR!
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project wit
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     C:\Users\Thomas\AppData\Local\.meteor\packages\npm-bcrypt\0.8.7\


=> Your application has errors. Waiting for file change.

```
I already re-install meteor, did a meteor npm rebuild but nothing work

`node : 6.3.1`

`npm : 3.10.3`

What should I do ?

**Comment by Deadly0** [comment]
The same problem with `bcrypt@0.8.7` on Windows 8.1

**Comment by Fen747** [comment]
Same here !

**Comment by abernix** [comment]
Please read #7469 carefully and please *Search Issues* before opening new issues.  The other issue was literally the second result for a search on `bcrypt` before you opened this.

Closing as duplicate.
