### ISSUE TITLE
NPM breaks - Error: Cannot find module 'npmlog'

### ISSUE THREAD

**Issue by birkskyum** [meteor/meteor#7507]
I have experienced this error on 1.3.4.4, 1.3.5.1 and 1.4

When I work, `meteor npm` suddenly stops working, and I get this error whenever I try to use it:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/birkskyum/.meteor/packages/meteor-tool/.1.4.0.p6v4r8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:19:13
    at Object.<anonymous> (/Users/birkskyum/.meteor/packages/meteor-tool/.1.4.0.p6v4r8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:75:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

I can't fix it by changing the meteor version.

**Comment by birkskyum** [comment]
I'm having trouble reproducing this. I might reopen it if I succeed.

**Comment by birkskyum** [comment]
The issue was probably caused by a symlink that was converted to a file at some point (it can happen if it is copied/moved).

I solved the issue by reinstalling meteor with:
`curl https://install.meteor.com/ | sh`

**Comment by yeeking** [comment]
I had the same issue, which suddenly cropped up in the middle of working an app. I can confirm that re-installing the meteor framework fixed the problem.

**Comment by jakobwilkenson** [comment]
Happening to me as well. Re-installing meteor doesn't fix the issue.
