### ISSUE TITLE
application failed to run after update to meteor 1.4 - AssertionError  'undefined' === 'function'

### ISSUE THREAD

**Issue by vandretti** [meteor/meteor#7521]
After updating to meteor 1.4, my application failed to run when deploying to Heroku. The application runs ok on my local machine (Ubuntu 16.04). My current workaround is to revert back to meteor version 1.3. Any suggestion to fix this issue?

Here is the log output.

  throw new assert.AssertionError({assert.js:93
        ^

AssertionError: "undefined" === "function"
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
    at Module.load (module.js:356:32)
    at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
    at Module._compile (module.js:456:26)
    at Function.Module._load (module.js:312:12)
    at Object.Module._extensions..js (module.js:474:10)
    at Module._compile (module.js:456:26)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

assert.js:93
    at Module._compile (module.js:456:26)
    at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
    at require (module.js:380:17)
AssertionError: "undefined" === "function"
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
        ^
  throw new assert.AssertionError({
    at Module._compile (module.js:456:26)
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

assert.js:93
  throw new assert.AssertionError({
AssertionError: "undefined" === "function"
    at wrapPathFunction (/app/.meteor/heroku_build/app/programs/server/mini-files.js:77:10)
        ^
    at Module._compile (module.js:456:26)
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/mini-files.js:108:24)
    at Module.load (module.js:356:32)
    at Object.Module._extensions..js (module.js:474:10)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/app/.meteor/heroku_build/app/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

**Comment by Ben305** [comment]
That happens when you deploy to a server which is not running Node 4.4.7.

**Comment by vandretti** [comment]
Thanks. Issue closed.

**Comment by meonkeys** [comment]
@Ben305 or anyone know _why_ this happens?

**Comment by Ben305** [comment]
@meonkeys Well, Meteor 1.4 uses Node 4.4.7, while Meteor 1.3 uses Node 0.10. When an application is deployed, the matching Node version must be installed on the server.

**Comment by meonkeys** [comment]
Gotcha, thank you. I was surprised about this, and it took several days to get my old apps running again. I build my own Docker containers and deploy on my own Kubernetes cluster. I think the problem was the Meteor build tool upgrading itself, but I'm not really sure.

**Comment by OllinLabs** [comment]
I replaced the buildpack to this one: https://github.com/AdmitHub/meteor-buildpack-horse and it worked

**Comment by NenadPavlov** [comment]
In my case Node version is 4.5.0 and setting buildpack to "horse" wasn't solving the issue. I simply added ["engines"](https://devcenter.heroku.com/articles/getting-started-with-nodejs#declare-app-dependencies) section in my package.json and deployed my app.
