### ISSUE TITLE
[meteor 1.4.0.1] Module did not self-register

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#7531]
version 1.3.5.1 is work fine.
i bundled project 1.4.0.1 and try to run, this exception:
```
/home/ngoicode/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/home/ngoicode/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/home/ngoicode/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/ngoicode/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:409:26)
```

**Comment by abernix** [comment]
Please search existing issues before opening new issues.

**Comment by meonkeys** [comment]
Maybe #7512 is the one you were supposed to find.
