### ISSUE TITLE
[meteor 1.4.0.1] AssertionError: "undefined" === "function" - error when deploy

### ISSUE THREAD

**Issue by lyquocnam** [meteor/meteor#7532]
i builded app ok, upload to server and setup.
when run app, this error on nginx log:

```
App 1206 stdout: 
App 1206 stderr: 
App 1206 stderr: assert.js:93
App 1206 stderr:   throw new assert.AssertionError({
App 1206 stderr:  
App 1206 stderr:  
App 1206 stderr:  
App 1206 stderr:  
App 1206 stderr:  
App 1206 stderr:  
App 1206 stderr:  
App 1206 stderr:  
App 1206 stderr: ^
App 1206 stderr: 
App 1206 stderr: AssertionError: "undefined" === "function"
App 1206 stderr:     at wrapPathFunction (/home/lynam/ngoicode/programs/server/mini-files.js:77:10)
App 1206 stderr:     at Object.<anonymous> (/home/lynam/ngoicode/programs/server/mini-files.js:108:24)
App 1206 stderr:     at Module._compile (module.js:456:26)
App 1206 stderr:     at Object.Module._extensions..js (module.js:474:10)
App 1206 stderr:     at Module.load (module.js:356:32)
App 1206 stderr:     at Function.Module._load (module.js:312:12)
App 1206 stderr:     at Module.require (module.js:364:17)
App 1206 stderr:     at require (module.js:380:17)
App 1206 stderr:     at Object.<anonymous> (/home/lynam/ngoicode/programs/server/boot.js:9:13)
App 1206 stderr:     at Module._compile (module.js:456:26)
[ 2016-07-31 03:26:51.5197 942/7f5df5812700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/lynam/ngoicode: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: cacd3f55
  Error details saved to: /tmp/passenger-error-jWo9Uy.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
<pre>

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: &quot;undefined&quot; === &quot;function&quot;
    at wrapPathFunction (/home/lynam/ngoicode/programs/server/mini-files.js:77:10)
    at Object.&lt;anonymous&gt; (/home/lynam/ngoicode/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.&lt;anonymous&gt; (/home/lynam/ngoicode/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
</pre>

[ 2016-07-31 03:26:51.5234 942/7f5df6814700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is cacd3f55. Please see earlier logs for details about the error.

```

**Comment by abernix** [comment]
You're using the wrong version of Node to run your application.  Again, please search before opening new issues - your error message is actually the subject of this recent issue.  #7475

You may want to consider any other changes you might need to make to your production environment by reading the Meteor Guide section on Migrating to 1.4 and the version History. 

https://guide.meteor.com/1.4-migration.html
