### ISSUE TITLE
Cannot run simple-todos to Meteor 1.4

### ISSUE THREAD

**Issue by zol** [meteor/meteor#7545]
### Environment
* Meteor 1.4.0.1
* Ubuntu 14.04 LTS 64bit clean install

1. Ensure you're on the latest Meteor 1.4.0.1
2. Clone `https://github.com/meteor/simple-todos`
3. Run `meteor`

### Error

```
$ meteor
[[[[[ ~/simple-todos ]]]]]                    

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                                                       
   
   While loading package npm-bcrypt@0.8.7:
   error: Command failed: /home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild
   --no-bin-links --update-binary
   gyp ERR! build error 
   gyp ERR! stack Error: not found: make
   gyp ERR! stack     at getNotFoundError
   (/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:14:12)
   gyp ERR! stack     at F
   (/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:69:19)
   gyp ERR! stack     at E
   (/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:81:29)
   gyp ERR! stack     at
   /home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:90:16
   gyp ERR! stack     at
   /home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
   gyp ERR! stack     at
   /home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
   gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
   gyp ERR! System Linux 3.13.0-92-generic
   gyp ERR! command "/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
   "rebuild"
   gyp ERR! cwd /home/ubuntu/.meteor/packages/npm-bcrypt/.0.8.7.ysar5l++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-4j4y5u/node_modules/bcrypt
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok 
   
   npm ERR! Linux 3.13.0-92-generic
   npm ERR! argv "/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links"
   "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!     /home/ubuntu/.meteor/packages/npm-bcrypt/.0.8.7.ysar5l++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-4j4y5u/npm-debug.log
   gyp ERR! build error 
   gyp ERR! stack Error: not found: make
   gyp ERR! stack     at getNotFoundError
   (/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:14:12)
   gyp ERR! stack     at F
   (/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:69:19)
   gyp ERR! stack     at E
   (/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:81:29)
   gyp ERR! stack     at
   /home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/which.js:90:16
   gyp ERR! stack     at
   /home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
   gyp ERR! stack     at
   /home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
   gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
   gyp ERR! System Linux 3.13.0-92-generic
   gyp ERR! command "/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
   "rebuild"
   gyp ERR! cwd /home/ubuntu/.meteor/packages/npm-bcrypt/.0.8.7.ysar5l++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-4j4y5u/node_modules/bcrypt
   gyp ERR! node -v v4.4.7
   gyp ERR! node-gyp -v v3.4.0
   gyp ERR! not ok 
   
   npm ERR! Linux 3.13.0-92-generic
   npm ERR! argv "/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
   "/home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links"
   "--update-binary"
   npm ERR! node v4.4.7
   npm ERR! npm  v3.10.5
   npm ERR! code ELIFECYCLE
   npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the bcrypt package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     node-gyp rebuild
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs bcrypt
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls bcrypt
   npm ERR! There is likely additional logging output above.
   
   npm ERR! Please include the following file with any support request:
   npm ERR!     /home/ubuntu/.meteor/packages/npm-bcrypt/.0.8.7.ysar5l++os.linux.x86_64+web.browser+web.cordova/npm/node_modules/.temp-4j4y5u/npm-debug.log
   
   
=> Your application has errors. Waiting for file change.
```

**Comment by zol** [comment]
@benjamn - I'm concerned that users who don't directly use binary packages and are just trying out our examples are unable to do so without requiring a toolchain.

**Comment by benjamn** [comment]
We should just update the example apps to 1.4.0.1 ourselves. The promise of pre-built binary dependencies holds for new apps, and example apps that do not need to be updated, but not for apps updated from older versions that used a different version of `npm-bcrypt`.

**Comment by zol** [comment]
This is still an issue with the example app updated to `1.4.0.1`. The relevant error appears to be:

```
error: Command failed: /home/ubuntu/.meteor/packages/meteor-tool/.1.4.0-1.13j49n2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm rebuild
   --no-bin-links --update-binary
   gyp ERR! build error 
   gyp ERR! stack Error: not found: make
   gyp ERR! stack     at getNotFoundError
```

**Comment by benjamn** [comment]
@zol I believe this should work now (without a compiler toolchain) with `accounts-password@1.2.13`, which uses `npm-bcrypt@0.8.7_1`.

**Comment by zol** [comment]
This is now working with `accounts-password@1.2.13`
