### ISSUE TITLE
resetPassword: The positional operator did not find the match needed from the query

### ISSUE THREAD

**Issue by aramk** [meteor/meteor#7596]
I'm attempting to call `Accounts.resetPassword()` with Meteor 1.4.0.1 but I'm getting this error:

```
I20160806-13:22:18.873(10)? Exception while invoking method 'resetPassword' MinimongoError: The positional operator did not find the match needed from the query
I20160806-13:22:18.874(10)?     at MinimongoError (packages/minimongo/minimongo.js:44:1)
I20160806-13:22:18.874(10)?     at findModTarget (packages/minimongo/modify.js:129:1)
I20160806-13:22:18.874(10)?     at packages/minimongo/modify.js:66:1
I20160806-13:22:18.875(10)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20160806-13:22:18.875(10)?     at packages/minimongo/modify.js:47:1
I20160806-13:22:18.876(10)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20160806-13:22:18.876(10)?     at Function.LocalCollection._modify (packages/minimongo/modify.js:40:1)
I20160806-13:22:18.877(10)?     at [object Object].LocalCollection._modifyAndNotify (packages/minimongo/minimongo.js:843:1)
I20160806-13:22:18.877(10)?     at packages/minimongo/minimongo.js:759:1
I20160806-13:22:18.878(10)?     at [object Object].LocalCollection._eachPossiblyMatchingDoc (packages/minimongo/minimongo.js:604:1)
```

I've tracked down the issue to this line:

https://github.com/meteor/meteor/blob/be986fd70926c9dd8eff6d8866205f236c8562c4/packages/accounts-password/password_server.js#L698

In order to update a property in an object contained in an array (email.$.verified) it seems MongoDB needs to identify which item in the array should be updated, since the $ operator can only update a single item at once.

I can verify this fails with a direct query:

```
db.getCollection('users').update({_id: 'noaP8MhPu8W6ufNGL'}, {$set: {'emails.$.verified': true}})
```

While including the email query in the selector works:

```
db.getCollection('users').update({_id: 'noaP8MhPu8W6ufNGL', 'emails.address': 'test@email.com'}, {$set: {'emails.$.verified': true}})
```

**Comment by aramk** [comment]
I realised during further debugging that the selector does indeed contain the email, but it's still failing. I believe it's a side effect of using collection hooks and not a bug within the core framework.
