### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by polkhovsky** [meteor/meteor#7620]
I get this error periodically on the server side which started after I updated Meteor to the latest 1.4.0.1
```
TypeError: Error.captureStackTrace is not a function
    at Error.MongoError (/Users/alex/.meteor/packages/npm-mongo/.1.5.45.1t1n125++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:13:9)
    at Function.MongoError.create (/Users/alex/.meteor/packages/npm-mongo/.1.5.45.1t1n125++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/Users/alex/.meteor/packages/npm-mongo/.1.5.45.1t1n125++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:161:20)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:332:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
=> Exited with code: 7
```
`Error.captureStackTrace` is a `node` method. So does this mean my meteor install is using an outdated node version?

**Comment by polkhovsky** [comment]
I have an [SO question](http://stackoverflow.com/questions/38697074/meteor-app-crashes-periodically-with-a-mongo-error) open. Here is additional information I uncovered:

The most important detail as I see it is this:
`Error.captureStackTrace is not a function`
This is a core node function! If I run node and enter `Error` I see the function: `captureStackTrace: [Function: captureStackTrace]`. So the issue looks like Meteor is maybe running an older version of node that doesn't have `captureStackTrace` in `Error` yet? Well, I followed the instructions [here][1] to check the version:

    MonsterMac:/ alex$ cd ~/.meteor/packages/meteor-tool/1.4.0-1/mt-os.osx.x86_64/dev_bundle/bin/
    MonsterMac:bin alex$ ./node -v
    v4.4.7

According to the [Change log][2] `captureStackTrace` is there in version 4.4.7. Now what?


  [1]: http://stackoverflow.com/questions/12014750/how-can-i-know-the-version-of-node-being-used-by-my-meteor-app
  [2]: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#4.4.7

**Comment by abernix** [comment]
I see that you opened this with christkv/mongodb-core#126 and they suggested it was an issue on the Meteor side.  You're the only person who has reported this so far in over 2 months of using this driver, so I have a few questions:

* First of all, are you still seeing this issue on Meteor 1.4.1?
* Do you have any other packages installed that might be creating their own `Error.captureStackTrace` function or blowing yours away?  I'm leaning toward this since Meteor doesn't do anything to modify `Error.captureStackTrace` and merely tries to use it itself.
* What is the output if you open up another terminal to your same project, run `meteor shell` and type `Error.captureStackTrace` at the REPL prompt?  You should get something like this:
 ```sh
 user@host:~/project-dir $ meteor shell

 Welcome to the server-side interactive shell!

 ...snip...

 > Error.captureStackTrace
 [Function: captureStackTrace]
 ```
* Can you reproduce this problem on a very basic new Meteor project GitHub repo that you can share in this issue?

**Comment by polkhovsky** [comment]
I am no longer seeing this error. I chose a radical path and moved all code out of the project and then started adding stuff back while also refactoring some of my code. So far so good. There must've been something in my React components that was causing this (I am doing server side rendering). I'll close the issue. Thank you.
