### ISSUE TITLE
[1.4] Path must be a string. Received null

### ISSUE THREAD

**Issue by santhanam87** [meteor/meteor#7628]
Please check the below log:
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   path.js:8:11: Path must be a string. Received null
   at assertPath (path.js:8:11)
   at Object.posix.relative (path.js:496:3)
   at pathRelative (packages/minifier-css/minifier.js:206:1)
   at packages/minifier-css/minifier.js:165:1
   at Array.forEach (native)
   at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
   at packages/minifier-css/minifier.js:122:1
   at Array.forEach (native)
   at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
   at rewriteRules (packages/minifier-css/minifier.js:99:1)
   at Object.CssTools.rewriteCssUrls
   (packages/minifier-css/minifier.js:85:1)
   at packages/minifier-css/minifier.js:55:1
   at Array.forEach (native)
   at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
   at Object.CssTools.mergeCssAsts (packages/minifier-css/minifier.js:32:1)
   at packages/minifyStdCSS/plugin/minify-css.js:79:1
   at CssToolsMinifier.processFilesForBundle
   (packages/minifyStdCSS/plugin/minify-css.js:17:1)
   
   
=> Your application has errors. Waiting for file change.

**Comment by dan335** [comment]
I'm getting this too.  Found the culprit but not sure how to fix.

```
fill: url(#teamGradient)
```

**Comment by mair0z** [comment]
I have the same error :(

**Comment by dan335** [comment]
This got rid of the error for me.  

    url("/#teamGradient")

But it doesn't work.  I think it needs to be a path but not sure how.

**Comment by mair0z** [comment]
Guys, i found the solution: all works with post-css minifyer.

just run this commands:
```
meteor remove standard-minifier-css
meteor add juliancwirko:postcss
npm install autoprefixer --save-dev
```

and add this to your package.json

```
"postcss": {
    "plugins": {
      "autoprefixer": {"browsers": ["last 2 versions"]}
    }
  }
```

original: https://github.com/juliancwirko/meteor-postcss

**Comment by santhanam87** [comment]
@mair0z  Thanks a ton , It worked :)
