### ISSUE TITLE
Import from local package with api.mainModule fails on 1.3.51 

### ISSUE THREAD

**Issue by javascriptlove** [meteor/meteor#7654]
I have 2 projects that use the same package, the package is just a package.js with one file server.js which has just 1 export inside, and is declared like this:

```
Package.describe({
    name:    'linguahouse:linglib',
    version: '1.0.0',
    summary: 'Add the missing functionality',
    documentation: 'README.md'
});

Package.onUse(function(api) {
    api.versionsFrom('1.3.1');

    api.mainModule('lib/server.js', 'server');
    api.export('somefunction', 'server');
});
```

One project is Meteor 1.3.2.4 and this package works fine there when i do 
```
import { somefunction } from 'meteor/linguahouse-linglib';
```

The other project is Meteor 1.3.5.1 and this package spits this:

```
W20160816-11:19:13.913(2)? (STDERR) Error: Can't find npm module 'meteor/linguahouse-linglib'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160816-11:19:13.913(2)? (STDERR)     at Object.Npm.require (/Users/akuzmenok/Zend/MeteorLingua/linguapdf/.meteor/local/build/programs/server/boot.js:203:17)
W20160816-11:19:13.913(2)? (STDERR)     at options.fallback (/Users/akuzmenok/Zend/MeteorLingua/linguapdf/.meteor/local/build/programs/server/packages/modules-runtime.js:425:18)
W20160816-11:19:13.913(2)? (STDERR)     at Module.require (/Users/akuzmenok/Zend/MeteorLingua/linguapdf/.meteor/local/build/programs/server/packages/modules-runtime.js:105:16)
W20160816-11:19:13.913(2)? (STDERR)     at Module.Mp.import (/Users/akuzmenok/.meteor/packages/modules/.0.6.5.hurh7d++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20160816-11:19:13.914(2)? (STDERR)     at meteorInstall.imports.api.settings.js (/Users/akuzmenok/Zend/MeteorLingua/linguapdf/.meteor/local/build/programs/server/app/app.js:847:45)
W20160816-11:19:13.914(2)? (STDERR)     at fileEvaluate (/Users/akuzmenok/Zend/MeteorLingua/linguapdf/.meteor/local/build/programs/server/packages/modules-runtime.js:170:9)
W20160816-11:19:13.914(2)? (STDERR)     at Module.require (/Users/akuzmenok/Zend/MeteorLingua/linguapdf/.meteor/local/build/programs/server/packages/modules-runtime.js:99:16)
W20160816-11:19:13.914(2)? (STDERR)     at Module.Mp.import (/Users/akuzmenok/.meteor/packages/modules/.0.6.5.hurh7d++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20160816-11:19:13.915(2)? (STDERR)     at meteorInstall.server.main.js (/Users/akuzmenok/Zend/MeteorLingua/linguapdf/.meteor/local/build/programs/server/app/app.js:956:14)
W20160816-11:19:13.915(2)? (STDERR)     at fileEvaluate (/Users/akuzmenok/Zend/MeteorLingua/linguapdf/.meteor/local/build/programs/server/packages/modules-runtime.js:170:9)
```

What's going on?

**Comment by javascriptlove** [comment]
Also happens with Meteor 1.3.4.4

**Comment by benjamn** [comment]
Try `import { somefunction } from 'meteor/linguahouse:linglib'`? Colon characters aren't usually valid in npm package names, but we make an exception for Meteor packages.

**Comment by javascriptlove** [comment]
Oh my, it worked! Thank you!
I'll close the ticket
