### ISSUE TITLE
Meteor 1.4.1 Error with Global Namespaces

### ISSUE THREAD

**Issue by abhiaiyer91** [meteor/meteor#7678]
Hey there.

In Meteor 1.3.2.4, we have several global variables within Application code (not packages). Since upgrading to 1.4.1 we are hit with several uncaught exceptions:

```
2016-08-20 00:02:30.093 [INTERNAL][ERROR] Uncaught Exception: 'ReferenceError: WPBatchJobs is not defined\n    at meteorInstall.server.batchJobs.js (server/batchJobs.js:24:1)\n 
```

For the example above, we have a namespace registered like

```
WPBatchJobs = {};
```

This and several other in-app variables are behaving the same way. Whats the deal?

**Comment by Dielz98** [comment]
Please don't remove global namespace feature. It is very convenient for many case.

**Comment by JWo1F** [comment]
Hm, I don't have this problem.

**Comment by abhiaiyer91** [comment]
Every single global defined within my application is blowing up. Resolves by moving into packages and exporting but this is a shitty workaround.

Heres my trace:

```
[INTERNAL][ERROR] Uncaught Exception: 'ReferenceError: Feeds is not defined\n    at meteorInstall.server.feeds.js (server/feeds.js:3:1)\n    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)\n    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)\n    at /Users/abhiaiyer/Projects/Workpop-Org/Workpop-Web/.meteor/local/build/programs/server/app/app.js:39301:1\n    at /Users/abhiaiyer/Projects/Workpop-Org/Workpop-Web/.meteor/local/build/programs/server/boot.js:292:10\n    at Array.forEach (native)\n    at Function._.each._.forEach (/Users/abhiaiyer/.meteor/packages/meteor-tool/.1.4.1.1qzkxnb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)\n    at /Users/abhiaiyer/Projects/Workpop-Org/Workpop-Web/.meteor/local/build/programs/server/boot.js:128:5'  >>> Error
```

**Comment by abhiaiyer91** [comment]
.babelrc issues.
