### ISSUE TITLE
modules not supported in Package.registerBuildPlugin.use

### ISSUE THREAD

**Issue by lucendio** [meteor/meteor#7682]
When I am trying to use the `modules` package in the `use` array with `Package.registerBuildPlugin` during the registration of a build plugin in `package.js`, like:

``` javascript
Package.registerBuildPlugin({
    name: 'my-compiler',
    use: [
        'ecmascript',
        'modules',
        'es5-shim',

        'caching-compiler'
    ],
    npmDependencies: ...,
    sources: [...]
});
```

I get an error as follows:

```
While loading plugin `my-compiler` from package `tap:i18n`:
vm.js:24:10: Unexpected reserved word
...(long trace)
```

I am assuming, it is caused by `import`, which is in the first line of the reffered source file. (Maybe thats why I cant find such an example among the core packages). Are there any plans to support this? (tested in meteor@1.4.0.1)

EDIT:
the error mentioned above, only throws when the entry file (like `api.mainModule`) is the only file referenced in the sources array. if all files (the ones with the exports) are referenced in that arrray as well, everything is fine and `modules` seems to work as expected

**Comment by abernix** [comment]
Does it work if you just use `ecmascript` and not `modules`?  `ecmascript` implies `modules`.

**Comment by lucendio** [comment]
I am affraid not. I t doesnt matter if `modules` is explicitly used or not. 

In case it might help, here is the full trace. And you can reproduce this error by checking out [this branch](https://github.com/lucendio/tap-i18n/tree/feature/meteor-v1.3-support) an commenting out every entry but the last one in the `sources` array of the `Package.registerBuildPlugin

```
   While loading plugin `tap-i18n-compiler` from package `tap:i18n`:
   vm.js:24:10: Unexpected reserved word
   at Object.exports.createScript (vm.js:24:10)
   at /tools/fs/files.js:1095:34
   at Function.time (/tools/tool-env/profile.js:305:10)
   at Object.files.runJavaScript (/tools/fs/files.js:1033:18)
   at /tools/isobuild/bundler.js:1622:15
   at Array.forEach (native)
   at Function._.each._.forEach (/Users/USERNAME/.meteor/packages/meteor-tool/.1.4.1_1.1p7vkws++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at JsImage.load (/tools/isobuild/bundler.js:1538:7)
   at /tools/isobuild/isopack.js:535:16
   at /tools/utils/buildmessage.js:359:18
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/isopack.js:525:20
   at Function._.each._.forEach (/Users/USERNAME/.meteor/packages/meteor-tool/.1.4.1_1.1p7vkws++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at Isopack.ensurePluginsInitialized (/tools/isobuild/isopack.js:513:7)
   at /tools/isobuild/compiler.js:377:16
   at Array.forEach (native)
   at /tools/isobuild/compiler.js:376:26
   at /tools/utils/buildmessage.js:359:18
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/compiler.js:372:16
   at /tools/isobuild/compiler.js:179:28
   at Object.withCache (/tools/fs/files.js:1585:12)
   at /tools/isobuild/compiler.js:178:11
   at Array.forEach (native)
   at Function._.each._.forEach (/Users/USERNAME/.meteor/packages/meteor-tool/.1.4.1_1.1p7vkws++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at Object.compile (/tools/isobuild/compiler.js:173:5)
   at /tools/isobuild/isopack-cache.js:360:30
   at /tools/utils/buildmessage.js:359:18
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
   at /tools/isobuild/isopack-cache.js:249:16
   at Function.time (/tools/tool-env/profile.js:305:10)
   at /tools/isobuild/isopack-cache.js:248:17
   at /tools/utils/buildmessage.js:359:18
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
   at ensureLoaded (/tools/isobuild/isopack-cache.js:213:12)
   at /tools/isobuild/isopack-cache.js:241:11
   at Array.forEach (native)
   at Function._.each._.forEach (/Users/USERNAME/.meteor/packages/meteor-tool/.1.4.1_1.1p7vkws++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at /tools/isobuild/isopack-cache.js:240:11
   at /tools/utils/buildmessage.js:359:18
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
   at /tools/isobuild/isopack-cache.js:76:14
   at /tools/packaging/package-map.js:57:7
   at Function._.each._.forEach (/Users/USERNAME/.meteor/packages/meteor-tool/.1.4.1_1.1p7vkws++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
   at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
   at /tools/project-context.js:781:25
   at /tools/utils/buildmessage.js:359:18
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at ProjectContext._buildLocalPackages (/tools/project-context.js:780:18)
   at /tools/project-context.js:268:9
   at /tools/utils/buildmessage.js:359:18
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
   at /tools/project-context.js:250:12
   at Function.run (/tools/tool-env/profile.js:489:12)
   at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
   at /tools/runners/run-app.js:548:29
   at /tools/utils/buildmessage.js:271:13
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at bundleApp (/tools/runners/run-app.js:547:31)
   at AppRunner._runOnce (/tools/runners/run-app.js:625:35)
   at AppRunner._fiber (/tools/runners/run-app.js:884:28)
   at /tools/runners/run-app.js:402:12
```

**Comment by hwillson** [comment]
`modules` can be used with `Package.registerBuildPlugin`. This is confirmed working with Meteor 1.5.2.2. If you're still running into this problem, please consider posting a small runnable reproduction that demonstrates the issue (using Meteor 1.5.2.2). Thanks!
