### ISSUE TITLE
package installation not working after installing Meteor 1.4.1 on windows

### ISSUE THREAD

**Issue by pacogeanu** [meteor/meteor#7686]
Tried to install 2 packages:
- meteor add ian:accounts-ui-bootstrap-3
- meteor add ryw:blog

The both were failed throwing the same error:

C:\Users\some_user\Tutorial\temp\app1>meteor add ian:accounts-ui-bootstrap-3
C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: Extracted archive '/C/Users/some_user/AppData/Local/Temp/.tmp7l2zg2' should only contain one entry
    at Object.files.extractTarGz (C:\tools\fs\files.js:741:11)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)
    at C:\tools\packaging\tropohouse.js:505:42
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at C:\tools\packaging\tropohouse.js:502:24
   at Array.forEach (native)
   at Function._.each._.forEach (C:\Users\some_user\AppData\Local\.meteor\packages\meteor-tool\1.4.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
   at C:\tools\packaging\tropohouse.js:469:11
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at Object.download (C:\tools\packaging\tropohouse.js:427:20)
   at C:\tools\packaging\tropohouse.js:600:22
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:597:20)
   at C:\tools\project-context.js:748:25
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at C:\tools\project-context.js:747:20
   at C:\tools\packaging\catalog\catalog.js:100:5
   at C:\tools\utils\buildmessage.js:271:13
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:264:29
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:262:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:253:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.capture (C:\tools\utils\buildmessage.js:252:19)
   at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
   at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:746:13)
   at C:\tools\project-context.js:268:9
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
   at C:\tools\project-context.js:250:12
   at Function.run (C:\tools\tool-env\profile.js:489:12)
   at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
   at C:\tools\cli\commands-packages.js:2034:20
   at C:\tools\utils\buildmessage.js:271:13
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:264:29
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:262:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:253:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.capture (C:\tools\utils\buildmessage.js:252:19)
   at Command.func (C:\tools\cli\commands-packages.js:2033:27)
   at C:\tools\cli\main.js:1410:23

**Comment by pacogeanu** [comment]
Problem solved after a meteor cleanup and switching to a different tar for unpacking. More details below.

Succeeded to install both packages after:
- deleting .meteor folder from User/Appdata/Local
- deleting .tmp * and mt-* files from User/AppData/Local/Temp
- removing path "C:\MinGW\bin" in order to force meteor not using tar.exe utility installed by MinGW
- reinstalling meteor

**Comment by chuikoffru** [comment]
How it does in os x 10.11?

`Milano:calendar milano$ meteor add aldeed:autoform
/Users/milano/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/private/var/folders/md/hmrmdn9s5cxfjhgz5msjz89c0000gn/T/mt-1bzatvb/web.cordova.json'
    at Error (native)
Milano:calendar milano$ `

How fix it?

**Comment by kylemclaren** [comment]
I have encountered this issue too with a fresh clone of Rocket.Chat and unfortunately `meteor npm rebuild` does not solve the problem...

**Comment by danilichev** [comment]
@kylemclaren probably you should remove .meteor/local folder
