### ISSUE TITLE
Cannot update to Meteor 1.4.1.1

### ISSUE THREAD

**Issue by ceonnel** [meteor/meteor#7703]
`meteor update --patch`
The latest version of Meteor, 1.4.1, is already installed on this computer. Run 'meteor update' inside of a
particular project directory to update that project to Meteor 1.4.1

Windows 10 64-bit, Meteor 1.4.1

## Updated
Trying just
`meteor update`
`Downloading meteor-tool@1.4.1_1....` and it's take a very long time

## Updated
Error... (tried several times).
```
%LOCALAPP%\.meteor\packages\meteor-tool\1.4.1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (%LOCALAPP%\.meteor\packages\meteor-tool\1.4.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
```

**Comment by ceonnel** [comment]
Trying just
`meteor update`
`Downloading meteor-tool@1.4.1_1....` and it's take a very long time

**Comment by benjamn** [comment]
This should be fixed now. The 1.4.1.1 was accidentally not published before the release was recommended, so I temporarily un-recommended it. Sorry for the inconvenience!

**Comment by ceonnel** [comment]
`meteor update --patch` works, but after it:

`%LOCALAPP%\.meteor\packages\meteor-tool\1.4.1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (%LOCALAPP%\.meteor\packages\meteor-tool\1.4.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)`

**Comment by stefanholzapfel** [comment]
For me the update doesn't work at all. Meteor Update in cmd hangs at

`Extracting meteor-tool@1.4.1_1...`

Keeps running forever...

Windows 7 64Bit

**Comment by hiei189** [comment]
mine says 
```
 %HOMEDIR%/.meteor/packages/meteor-tool/.1.4.1.1lr2zdx++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165` 
throw error;
^

Error: ENOENT: no such file or directory, open '/tmp/mt-1x95egp/os.json'
at Error (native)
```
ubuntu 16.04 64bits

**Comment by Isarstyle** [comment]
+1

**Comment by ekhmoi** [comment]
+1

```
C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at resume (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:62:16)
    at unblockEntry (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:43:28)
    at Entry.<anonymous> (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:47:9)
    at FileWriter.<anonymous> (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:205:14
    at C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:232:16
    at C:\Users\ekhmo\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by darguet** [comment]
Download it by adding 54.192.225.217 warehouse.meteor.com to /etc/hosts 

http://stackoverflow.com/questions/37185894/meteor-is-stuck-at-downloading-meteor-tool1-3-2-4

**Comment by LucasRodriguez0402** [comment]
dfs

**Comment by aaroncalderon** [comment]
I'm having the same issue as hiei189. I have reinstalled meteor several times. Still having same issue.

**Comment by aaroncalderon** [comment]
## Update 2

I tryed again from scratch.

- Uninstall Meteor (manually)
- clone again and spinoff meteor

>
cd C:\dev\p\m
git clone https://github.com/meteor/todos
cd todos
meteor npm install
__meteor # new step__
meteor update

This time, I had a lot of issues with `meteor npm install`. It was hanging a lot on `cloneCurrentTree` message.

I troublesoot the npm issue by:

```
meteor npm config set cache <path>
meteor npm config set htps-proxy <proxy>
meteor npm config set prefix <prefix_path>
meteor npm config set proxy <proxy again>
meteor npm config set registry http://registry.npmjs.org/
meteor npm config set strict-ssl false
meteor npm config set tmp <path>
```

This adds all my global configuration of npm to the npm installation of meteor.

Then I ran `meteor` it took for ever.

Then I ran `meteor update` and it seems to have worked this time.

**Comment by LucasRodriguez0402** [comment]
For my experienced, if you update the meteor to latest version... it seems to be do not work properly, but please wait and try to do that it can be work.

**Comment by LucasRodriguez0402** [comment]
Don't be shy with one issue, lots of ways for living also the developing.

**Comment by aaroncalderon** [comment]
## Update 3

I tested a third time.

I kept having issues with `meteor npm install` and `meteor update`. 

### `ntlmaps` to the rescue

After some more digging around ai swithced my proxy choice from `cntlm` to [`ntlmaps` ](https://github.com/heupel/ntlmaps) and for some reason, it went smothly after that. I think that the proxy setup on my corp had something to do with it, but `cntlm` was not handlilng the connections well. `ntlmaps` saved the day.

**Comment by aaroncalderon** [comment]
This is where it gets interesting. I tryed to update another [project](https://github.com/meteor/localmarket) with `meteor update` and now I get:

```
%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at FileWriter.<anonymous> (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:147:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (%LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at %LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:205:14
    at %LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:232:16
    at %LOCALAPPDATA%\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```

If I try `meteor update --release 1.4.1.1`

```
C:\Users\aaron calderon\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '%LOCALAPPDATA%\Temp\mt-1g587s7\os\packages\iron_dynamic-template.js'
    at Error (native)
```

so, I'm back to square one :(

**Comment by MalcolmGC** [comment]
Thanks 
The < meteor update --patch
worked fabulously! Fast and then  '> meteor' works with others projects.

**Comment by gabak** [comment]
meteor update --patch did not work for me i still have error
`C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:16
5
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstra
ct.js:67:36)
    at Extract.Abstract.error (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstr
eam\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\
extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar
\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\bloc
k-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-st
ream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstre
am\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\p
arse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.
js:93:8)
    at resume (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.
js:62:16)
    at unblockEntry (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\co
llect.js:43:28)
    at Entry.<anonymous> (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\l
ib\collect.js:47:9)
    at FileWriter.<anonymous> (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstr
eam\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fst
ream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:2
05:14
    at C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:2
32:16
    at C:\Users\gabak\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm
\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)`

**Comment by abernix** [comment]
As this issue is closed now, if you're still experiencing the `unexpected eof` error from the `decorate` in Meteor 1.4.1.1, a new issue is open and being tracked in #7766 so I'd recommend picking up the conversation over there.

**Comment by FabianoVilela** [comment]
On linux I got with:
`meteor update --release 1.4.1.1`
or
Editing `.meteor/release` to METEOR@1.4.1.1
