### ISSUE TITLE
deploying Meteor 1.4.1 cannot find module

### ISSUE THREAD

**Issue by jacobjuul** [meteor/meteor#7748]
I just updated my app to meteor 1.4.1 from 1.3 and get the following error.

```bash
e7xd
2016-09-02 10:46:47+02:00/app/bundle/programs/server/boot.js:333
e7xd
2016-09-02 10:46:47+02:00}).run();
e7xd
2016-09-02 10:46:47+02:00 ^
e7xd
2016-09-02 10:46:47+02:00
e7xd
2016-09-02 10:46:47+02:00Error: Cannot find module 'core-js/library/fn/symbol'
e7xd
2016-09-02 10:46:47+02:00 at Function.Module._resolveFilename (module.js:325:15)
e7xd
2016-09-02 10:46:47+02:00 at Function.Module._load (module.js:276:25)
e7xd
2016-09-02 10:46:47+02:00 at Module.require (module.js:353:17)
e7xd
2016-09-02 10:46:47+02:00 at require (internal/module.js:12:17)
e7xd
2016-09-02 10:46:47+02:00 at Object.<anonymous> (/app/bundle/programs/server/npm/node_modules/babel-runtime/core-js/symbol.js:1:31)
e7xd
2016-09-02 10:46:47+02:00 at Module._compile (module.js:409:26)
e7xd
2016-09-02 10:46:47+02:00 at Object.Module._extensions..js (module.js:416:10)
e7xd
2016-09-02 10:46:47+02:00 at Module.load (module.js:343:32)
e7xd
2016-09-02 10:46:47+02:00 at Module.Mp.load (/app/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
e7xd
2016-09-02 10:46:47+02:00 at Function.Module._load (module.js:300:12)
e7xd
2016-09-02 10:46:47+02:00Application exited with code: 1 signal: null
e7xd
2016-09-02 10:46:47+02:00Application process closed with code: 1 signal: null
e7xd
2016-09-02 10:46:52+02:00The container has crashed. A new container will be started to replace it.
```

packages file

```json
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
reactive-var@1.0.10            # Reactive variable for tracker
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-js@1.2.0    # JS minifier run for production mode
es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.

accounts-ui@1.1.9
accounts-password@1.3.0
service-configuration@1.0.10
email@1.1.17
aldeed:simple-schema
aldeed:collection2
themeteorchef:bert
accounts-facebook@1.0.10
accounts-base@1.2.11
mrgalaxy:stripe
http@1.2.9
react-meteor-data
edgee:slingshot
fortawesome:fontawesome
deanius:promise
meteorhacks:ssr
vsivsi:job-collection
nooitaf:colors
webpack:sass
webpack:webpack
webpack:react
blaze-html-templates@1.0.4
juliancwirko:postcss
reactive-dict@1.1.8
reactrouter:react-router-ssr
shell-server
```

**Comment by jacobjuul** [comment]
fixed after installing `core-js`
