### ISSUE TITLE
meteor npm install fails (Windows)

### ISSUE THREAD

**Issue by pcarrier** [meteor/meteor#7838]
`meteor npm install` fails on Windows 10 aniversary update with:

```
$ meteor npm install
C:\opt\meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\tools\cli\dev-bundle.js:44
  return getDevBundleForRelease(release).then(function (devBundleDir) {
                                        ^

TypeError: Cannot read property 'then' of null
    at getDevBundleDir (C:\opt\meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\tools\cli\dev-bundle.js:44:41)
    at Object.<anonymous> (C:\opt\meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\tools\cli\dev-bundle.js:172:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.getDevBundle (C:\opt\meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\tools\cli\dev-bundle-bin-helpers.js:6:10)
    at getChildProcess (C:\opt\meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\tools\cli\dev-bundle-bin-commands.js:27:31)
```

`.meteor/release` contains `METEOR@1.4.1.1`.

**Comment by pcarrier** [comment]
Is there a workaround before 1.4.2?

**Comment by pcarrier** [comment]
The meteor install directory needs to be called `.meteor`.

**Comment by illya13** [comment]
any updates here ?

**Comment by pcarrier** [comment]
@illya13 yes, AFAICT this issue happens when your Meteor install directory is not called `.meteor` and renaming it should work around the issue (if not your issue is different from mine).

**Comment by illya13** [comment]
@pcarrier 
- meteor is installed to c:\Users\illya\AppData\Local\.meteor\meteor.bat 
- METEOR@1.4.1.2
- meteor-tool
    - 1.1.10
    - 1.1.9 
    - 1.3.2_2 
    - 1.3.2_4 
    - 1.3.3 
    - 1.3.3_1 
    - 1.3.4_1 
    - 1.4.0-1 
    - 1.4.1_2

**Comment by abernix** [comment]
@illya13 Can you provide your actual console output from when you run `meteor npm install` including stack trace?

**Comment by illya13** [comment]
@pcarrier @abernix sorry, my fault
I had a Directory Junction from ```c:\Users\illya\AppData\Local\.meteor\``` to ```d:\meteor\``` to save some space on ```C drive```.
And renaming ```d:\meteor\``` to ```d:\.meteor\``` helped
