### ISSUE TITLE
[docker] EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by zhaoyao91** [meteor/meteor#7852]
I have a project like this [https://github.com/zhaoyao91/meteor-multi-apps-project-demo](https://github.com/zhaoyao91/meteor-multi-apps-project-demo) except that I have npm dependencies in the shared local package (I use PACKAGE_DIRS to share local pacakges in two app).

Everything works well before I tried to deploy them with docker. I get the following error:

```
local:lib: updating npm dependencies -- lodash...
/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
throw error;
^
Error: EXDEV: cross-device link not permitted, rename '/project/packages/lib/.npm/package' -> '/project/packages/lib/.npm/package-garbage-1jw8rr8'
at Error (native)
at Object.fs.renameSync (fs.js:681:18)
at Object.wrapper [as rename] (/tools/fs/files.js:1519:35)
at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:959:11)
at completeNpmDirectory (/tools/isobuild/meteor-npm.js:641:9)
at updateExistingNpmDirectory (/tools/isobuild/meteor-npm.js:586:3)
at Object.meteorNpm.updateDependencies (/tools/isobuild/meteor-npm.js:98:7)
at Object.compile (/tools/isobuild/compiler.js:121:19)
at /tools/isobuild/isopack-cache.js:360:30
at /tools/utils/buildmessage.js:359:18
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:352:34
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:350:23
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.enterJob (/tools/utils/buildmessage.js:324:26)
at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
at /tools/isobuild/isopack-cache.js:249:16
at Function.time (/tools/tool-env/profile.js:305:10)
at /tools/isobuild/isopack-cache.js:248:17
at /tools/utils/buildmessage.js:359:18
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:352:34
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:350:23
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.enterJob (/tools/utils/buildmessage.js:324:26)
at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
at /tools/isobuild/isopack-cache.js:76:14
at /tools/packaging/package-map.js:57:7
at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.4.1_1.139xb76++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
at /tools/project-context.js:781:25
at /tools/utils/buildmessage.js:359:18
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:352:34
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:350:23
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.enterJob (/tools/utils/buildmessage.js:324:26)
at ProjectContext._buildLocalPackages (/tools/project-context.js:780:18)
at /tools/project-context.js:268:9
at /tools/utils/buildmessage.js:359:18
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:352:34
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:350:23
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.enterJob (/tools/utils/buildmessage.js:324:26)
at ProjectContext._completeStagesThrough (/tools/project-context.js:258:18)
at /tools/project-context.js:250:12
at Function.run (/tools/tool-env/profile.js:489:12)
at ProjectContext.prepareProjectForBuild (/tools/project-context.js:249:13)
at /tools/cli/commands.js:845:20
at /tools/utils/buildmessage.js:271:13
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:264:29
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:262:18
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:253:23
at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.capture (/tools/utils/buildmessage.js:252:19)
at Object.main.captureAndExit (/tools/cli/main.js:273:29)
at buildCommand (/tools/cli/commands.js:844:8)
at Command.func (/tools/cli/commands.js:798:12)
at /tools/cli/main.js:1410:23
```

**Comment by gossel-j** [comment]
This is a problem with aufs. The rename(2) syscall don't work when need to move directories and meteor use fs.renameSync that use internally rename(2).

More at https://github.com/npm/npm/issues/9863 and https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/#/renaming-directories-with-the-aufs-storage-driver.

This is a real problem. The fix would be to use [fs-extra](https://github.com/jprichardson/node-fs-extra) package with [fs-extra.move](https://github.com/jprichardson/node-fs-extra#movesrc-dest-options-callback) method instead of fs.rename.

**Comment by gossel-j** [comment]
For a quick temporary fix, you can mv to a tmp dir and move back again the /project/packages directory `mv /project/packages /project/packages.tmp && mv /project/packages.old /project/packages && the rest of your build...`

**Comment by zhaoyao91** [comment]
thanks. will this bug get fixed?

**Comment by abernix** [comment]
I didn't try to reproduce this, but [based on the Docker documentation](https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/#/renaming-directories-with-the-aufs-storage-driver) linked above and as demonstrated, it's safe to assume this is a problem and I'll mark this as `confirmed`:

Relevant quote from `docker` docs:
> your application has to be designed so that it can handle EXDEV and fall back to a “copy and unlink” strategy.

Relevant Meteor Code: https://github.com/meteor/meteor/blob/b40df12129fa6b3545f89394723fcf044b47f78d/tools/fs/files.js#L950-L978

**Comment by abernix** [comment]
@zhaoyao91 I know I've confirmed this previously but I'm going to un-confirming this because having finally had time to look at your reproduction, it's far too hard to figure out how to reproduce it and therefore too hard to determine if this problem is actually fixed.  Some changes have been made to resolve things like this, but there's no way of knowing if the problem is gone for you.

Please provide exact instructions on how to reproduce this problem with the reproduction that you've provided.

**Comment by zhaoyao91** [comment]
@abernix 

1. create a root dir and put app and local packages dir into it. note here we are not puting packages dir under app dir, we install local packages by first setting PACKAGES_DIR (now METEOR_PACKAGES_DIR).
```
root/
  app/
  packages/
```

2. use dockerfile to build this project. the context root is root dir, and we may install several npm packages in both app and local packages.

according to the error, it seems that in some building step, meteor will rename the `.npm/pacakge` file in local package, and this cause the error. so as a workaround for now, I set the .gitignore to not check in this dir, with the trade-off of losing features like npm shrinkwrap.

**Comment by abernix** [comment]
I will still take a look at this as soon as possible, but it would be greatly simplified by a link to a Git project with a structure and script that could be simply cloned.  A (Git) image is worth a hundred words. :smile:

**Comment by zhaoyao91** [comment]
https://github.com/zhaoyao91/meteor-re-7852

I previously thought it may be relative to PACKAGE_DIRS, but in the process of testing this reproduce repo, I found as if you have a local package installed, this error will occur.

**Comment by jshimko** [comment]
Ok, I can reliably reproduce this issue every time now.  It has actually been around for quite a while now when doing docker builds on a CoreOS host, but Docker 1.13 now causes it to happen on macOS every time too.

The reproduction steps are fairly simple...

```sh
# create an empty app
meteor create testapp
cd testapp

# add a Dockerfile with my base image
# https://github.com/jshimko/meteor-launchpad/blob/master/scripts/build-meteor.sh
echo "FROM jshimko/meteor-launchpad:latest" > Dockerfile

# build the image
docker build -t meteor-todos .
```

`meteor build` will then throw this every time...

```sh
[-] Building Meteor application...

/root/.meteor/packages/templating-compiler/.1.3.0.qxyget++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:177
      throw error;
      ^

Error: EXDEV: cross-device link not permitted, rename '/opt/meteor/dist/bundle' -> '/opt/meteor/dist/bundle-garbage-1vn2pov'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
    at Object.wrapper [as rename] (/tools/fs/files.js:1535:35)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:965:11)
    at Builder.complete (/tools/isobuild/builder.js:690:13)
    at /tools/isobuild/bundler.js:2529:13
    at /tools/isobuild/bundler.js:2436:7
    at /tools/isobuild/bundler.js:2837:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2670:31)
    at /tools/isobuild/bundler.js:2617:32
    at Object.withCache (/tools/fs/files.js:1601:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2617:16)
    at buildCommand (/tools/cli/commands.js:954:30)
    at Command.func (/tools/cli/commands.js:829:12)
    at /tools/cli/main.js:1483:23
```

For reference, the Docker base is my image here...
https://github.com/jshimko/meteor-launchpad

Ok, so I'll share my current understanding of the problem (several parts of which came from this issue thread).  As mentioned earlier, this error happens during a `meteor build` process.  Specifically, it happens right here...

https://github.com/meteor/meteor/blob/b40df12129fa6b3545f89394723fcf044b47f78d/tools/fs/files.js#L957-L978

This is presumably related to this aufs limitation that @gossel-j and @abernix linked from the Docker docs above.

Source
https://docs.docker.com/engine/userguide/storagedriver/aufs-driver/#deleting-files-with-the-aufs-storage-driver

> Calling rename(2) for a directory is not fully supported on AUFS. It returns EXDEV (“cross-device link not permitted”), even when both of the source and the destination path are on a same AUFS layer, unless the directory has no children. So your application has to be designed so that it can handle EXDEV and fall back to a “copy and unlink” strategy.

That said, the [`fs-extra`](https://github.com/jprichardson/node-fs-extra) npm package has the [`fs.move`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/move.md) method which implements error handling for that EXDEV error.  It has `moveDirAcrossDevice` and `moveFileAcrossDevice` methods that presumably fix it.

https://github.com/jprichardson/node-fs-extra/blob/master/lib/move/index.js

Also, right from the readme for that `move` method...

> Moves a file or directory, even across devices.

So my thinking was perhaps we could either import that method or snag the code and replace the `files.rename` in the Meteor build.  However, there's a bunch of magic wrapped around the `fs` package in there, so it wasn't real obvious to me how to make that change without dumping hours into figuring out what's going on there.  So that's why I'm here now.  I'm assuming someone else here knows that code well enough to drop in `fs-extra` and test that method.

Any help/discussion on this would be extremely appreciated.  This is a MAJOR blocker for us right now as we use have various CI workflows that are completely broken by this and we're having to manually build outside of CI to get around it in the meantime.
