### ISSUE TITLE
Error: double colon in host identifier (future.js:280)

### ISSUE THREAD

**Issue by jkd65** [meteor/meteor#7903]
I am getting this error when trying to run my project

```
>meteor --settings settings.json
[[[[[ ~\F\Documents\Github\FEMA-SAH-WebApp\FEMA-SAH-WebApp ]]]]]

=> Started proxy.
=> Meteor 1.4.1.2 is available. Update this project with 'meteor update'.
W20161010-15:02:34.731(-7)? (STDERR) C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20161010-15:02:34.794(-7)? (STDERR)                                            throw(ex);
W20161010-15:02:34.795(-7)? (STDERR)                                            ^
W20161010-15:02:34.795(-7)? (STDERR)
W20161010-15:02:34.795(-7)? (STDERR) Error: double colon in host identifier
W20161010-15:02:34.796(-7)? (STDERR)     at module.exports (C:\Users\keeva\AppData\Local\.meteor\packages\npm-mongo\1.5.45\npm\node_modules\mongodb\lib\url_parser.js:91:13)
W20161010-15:02:34.796(-7)? (STDERR)     at connect (C:\Users\keeva\AppData\Local\.meteor\packages\npm-mongo\1.5.45\npm\node_modules\mongodb\lib\mongo_client.js:266:16)
W20161010-15:02:34.797(-7)? (STDERR)     at Function.MongoClient.connect (C:\Users\keeva\AppData\Local\.meteor\packages\npm-mongo\1.5.45\npm\node_modules\mongodb\lib\mongo_client.js:113:3)
W20161010-15:02:34.798(-7)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:174:11)
W20161010-15:02:34.798(-7)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
W20161010-15:02:34.798(-7)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20161010-15:02:34.799(-7)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
W20161010-15:02:34.799(-7)? (STDERR)     at [object Object].Mongo.Collection (packages/mongo/collection.js:103:40)
^C0161010-15:02:34.800(-7)? (STDERR)     at new _0x19bfx8.(anonymous function) (packages/meteortoys_toy
```

Any help is appreciated

**Comment by abernix** [comment]
This is not a Meteor error, but rather an error coming from the Mongo driver.  What is the value of your `MONGO_URL`?  Please hide/change sensitive information before posting it here and make sure you have set it properly.

You can output this on Windows Command Prompt by running `echo %PATH%` (or `echo $Env:PATH` if you're using PowerShell).

**Comment by abernix** [comment]
I'm going to close this as we haven't heard back from you.  Happy to reopen with additional information on how to reproduce it, but as I previously stated, this is likely due to an invalid `MONGO_URL` and is not an error being produced by Meteor – but rather the Mongo driver.  Make sure that the `MONGO_URL` matches the URL provided by your Mongo host (and that it is properly escaped/quoted/etc.).
