### ISSUE TITLE
bug when trying to run meteor from checkout on release-1.4.2

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/meteor#7909]
### Summary

I am trying to run meteor from a local checkout on the `release-1.4.2` branch, to try to help out a bit with some minor micro-optimizations (maybe).  Sadly, I'm not able to run meteor, even against the todos example repo (react branch).

### Error

```
W20161011-13:52:00.919(-4)? (STDERR) Error: Cannot find module '../core-js/object/assign'
W20161011-13:52:00.919(-4)? (STDERR)     at require (packages/modules-runtime.js:102:19)
W20161011-13:52:00.919(-4)? (STDERR)     at meteorInstall.node_modules.babel-runtime.helpers.extends.js (packages/modules.js:465:15)
W20161011-13:52:00.919(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:170:9)
W20161011-13:52:00.919(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:99:16)
W20161011-13:52:00.919(-4)? (STDERR)     at Module.Mp.import (/Users/alan/Code/Meteor/todos/.meteor/local/isopacks/modules/npm/node_modules/reify/lib/runtime.js:70:16)
W20161011-13:52:00.919(-4)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (/Users/alan/Code/Meteor/todos/.meteor/local/build/programs/server/packages/react-meteor-data.js:210:87)
W20161011-13:52:00.919(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:170:9)
W20161011-13:52:00.920(-4)? (STDERR)     at require (packages/modules-runtime.js:99:16)
W20161011-13:52:00.920(-4)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
W20161011-13:52:00.920(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:170:9)
```

### Environment

```
alan at alan in ~/Code/Meteor/todos
$ node --version; npm --version; ../meteor/meteor --version; uname -a
v4.4.7
3.10.7
Unreleased, running from a checkout at 1d375ff (HEAD -> lodash-in-builder, upstream/release-1.4.2)
Darwin alan.middleearth 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin

alan at alan in ~/Code/Meteor/todos (react)
$ git show
commit e2b367ec145be9cf03b215cea3430626f222f0b6
Merge: 4e39a16 088128a
Author: Hugh Willson <hugh@octonary.com>
Date:   Tue Oct 4 12:14:17 2016 -0400

    Merge pull request #191 from hwillson/react

    Added shelljs devDependency to fix problematic eslint shelljs version (react)


alan at alan in ~/Code/Meteor/todos (react)
$ git remote -v
origin	https://github.com/meteor/todos (fetch)
origin	https://github.com/meteor/todos (push)
```

(yes, I've done `npm i` in the `todos` folder - no, it has not worked yet)`

### Recreation

```
$ ../meteor/meteor run
=> Running Meteor from a checkout -- overrides project version (Meteor 1.4.1.1)

$ ../meteor/meteor debug
=> Running Meteor from a checkout -- overrides project version (Meteor 1.4.1.1)
```

both exhibit the same bug for me.

**Comment by abernix** [comment]
This is a known bug and has existing issues.  See #7833 and others.

Dup.

**Comment by zeroasterisk** [comment]
thanks, sorry
