### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by jkd65** [meteor/meteor#7924]
This occurs when running meteor, meteor reset, or demeteorizer. No idea what it means, and cannot find an issue related to the similar file.

```
C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\big-integer\BigInteger.js:2



SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\bplist-parser\bplistParser.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\cordova-common\src\ConfigChanges\ConfigFile.js:20:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\cordova-common\src\ConfigChanges\ConfigKeeper.js:19:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:39:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\cordova-common\cordova-common.js:36:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\src\plugman\plugman.js:22:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\cordova-lib.js:28:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Module.Mp.import (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\lib\runtime.js:70:16)
    at Object.<anonymous> (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\tools\cordova\project.js:1:1723)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Module.Mp.import (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\lib\runtime.js:70:16)
    at Object.<anonymous> (C:\tools\cli\commands.js:1:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\tools\cli\main.js:288:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (C:\Users\keeva\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at continueSetup (C:\tools\index.js:22:3)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
```

Any help is appreciated. Thanks!

**Comment by abernix** [comment]
The problem you're referring to is too vague to accurately provide help.  Essentially, `Unexpected token ILLEGAL` is a JavaScript parsing error, but what you have provided is not enough to isolate the problem, or even to determine if the problem is in Meteor itself.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

Please consult those instructions and provide a reproduction or information about whether this happens only on an existing project or if it also happens on a new project.

If it's only happening on one project, then it might be something in that project.  A reproduction would be necessary to help further.

If it's happening on all projects (and new projects), you might want to try a reinstallation of Meteor.  For Windows, you should:

* Uninstall Meteor from:
 * **Win10:** Settings > System > Apps & features > Meteor > Uninstall
 * **Win7:** Control Panel > Programs > Programs and Features > Meteor > Uninstall
* Using Windows Explorer, delete the `.meteor` folder from `%LOCALAPPDATA%` completely.  If you are unable to delete it due to long file-paths, please try using the [7-zip File Explorer](http://www.7-zip.org/) application to do it instead.
* Install fresh 1.4.1.1 from https://install.meteor.com/windows (skip logging in at end due to #6218 bug)
* **Restart**
* Open Command Prompt and type `meteor --version` to confirm it's working.

**Comment by jkd65** [comment]
Thank you, that seems to fix the issue (doing a complete reinstall). Will reopen if problem arises again.
