### ISSUE TITLE
[1.4.2-rc.3] importing chai npm package from *.test.js fails

### ISSUE THREAD

**Issue by hexsprite** [meteor/meteor#7953]
I created a repro here: https://github.com/hexsprite/todos

All I changed from the upstream was update the release to 1.4.2-rc.3 and change the `practicalmeteor:chai` usage to a regular `chai` npm import.

The same import works just fine under 1.4.1.x

I wonder if this is some kind of casualty of the import optimizations.

The actual traceback I get:

```
> meteor test --once --driver-package dispatch:mocha-phantomjs

[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
W20161023-20:29:23.635(-7)? (STDERR) /Users/jbb/.meteor/packages/meteor-tool/.1.4.2-rc.3.j7a233++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161023-20:29:23.635(-7)? (STDERR) 						throw(ex);
W20161023-20:29:23.636(-7)? (STDERR) 						^
W20161023-20:29:23.636(-7)? (STDERR) 
W20161023-20:29:23.636(-7)? (STDERR) Error: Cannot find module './lib/chai'
W20161023-20:29:23.637(-7)? (STDERR)     at require (packages/modules-runtime.js:102:19)
W20161023-20:29:23.637(-7)? (STDERR)     at meteorInstall.node_modules.chai.index.js (packages/modules.js:401:18)
W20161023-20:29:23.637(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:170:9)
W20161023-20:29:23.637(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:99:16)
W20161023-20:29:23.638(-7)? (STDERR)     at Module.Mp.import (/Users/jbb/.meteor/packages/modules/.0.7.6.1rr9fy6++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161023-20:29:23.638(-7)? (STDERR)     at meteorInstall.imports.api.lists.lists.tests.js (/private/var/folders/q5/2qtj1b5n67b_q7czgc5mj8fh0000gn/T/meteor-test-runicp94w/.meteor/local/build/programs/server/app/app.js:156:252)
W20161023-20:29:23.638(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:170:9)
W20161023-20:29:23.638(-7)? (STDERR)     at require (packages/modules-runtime.js:99:16)
W20161023-20:29:23.638(-7)? (STDERR)     at /private/var/folders/q5/2qtj1b5n67b_q7czgc5mj8fh0000gn/T/meteor-test-runicp94w/.meteor/local/build/programs/server/app/app.js:930:1
W20161023-20:29:23.639(-7)? (STDERR)     at /private/var/folders/q5/2qtj1b5n67b_q7czgc5mj8fh0000gn/T/meteor-test-runicp94w/.meteor/local/build/programs/server/boot.js:293:34
```

**Comment by benjamn** [comment]
Has the npm `chai` package worked for you before?

**Comment by benjamn** [comment]
And what happens if you move `chai` from `devDependencies` to `dependencies`?

**Comment by hexsprite** [comment]
@benjamn yup, apparently moving it to `devDependencies` did the trick.  So it looks like perhaps the devDependencies are no longer being processed in test mode?
