### ISSUE TITLE
Ignoring .babelrc

### ISSUE THREAD

**Issue by gitTerebi** [meteor/meteor#7965]
If I have a .babelrc file in project root folder I get...

> => Started proxy.
> => Errors prevented startup:
> 
>    While processing files with ecmascript (for target web.browser):
>    native: Unexpected token p
>    at Object.parse (native)
>    at BabelCompiler.BCp._inferFromBabelRc

Is there anyway of disabling .babelrc file support?

**Comment by abernix** [comment]
What is in your `.babelrc` file?  Can you please create a reproduction of this problem per the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines?

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem and it seems to be an isolated situation or strangeness in your setup.  If you're still having problems, please update to the latest Meteor 1.4.2.1.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)

**Comment by crapthings** [comment]
Ignoring empty .babelrc

**Comment by crapthings** [comment]
reproduce https://github.com/crapthings/meteor-empty-babelrc

```
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   native: Unexpected end of input
   at Object.parse (native)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler.js:246:14)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:236:10)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:166:10)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:109:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:108:14)


   While processing files with ecmascript (for target os.osx.x86_64):
   native: Unexpected end of input
   at Object.parse (native)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler.js:246:14)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:236:10)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:166:10)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:109:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:108:14)
```
