### ISSUE TITLE
Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package? on CentOS

### ISSUE THREAD

**Issue by elmarti** [meteor/meteor#8003]
I am running meteor build on my own Linux machine for use on a CentOS production server. I have followed the instructions in the built project's README.md, but whenever I run node main.js, I get the following error.
`
/root/meteor/build/bundle/programs/server/boot.js:348
}).run();
   ^

Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
    at Object.require (/root/meteor/build/bundle/programs/server/boot.js:200:17)
    at packages/meteor.js:677:32
    at packages/meteor.js:846:4
    at packages/meteor.js:1380:3
    at /root/meteor/build/bundle/programs/server/boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (/root/meteor/build/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /root/meteor/build/bundle/programs/server/boot.js:128:5
    at /root/meteor/build/bundle/programs/server/boot.js:344:5
    at Function.run (/root/meteor/build/bundle/programs/server/profile.js:480:12)
`

**Comment by elmarti** [comment]
(My own Linux machine is Ubuntu)

**Comment by elmarti** [comment]
Just worked when  I built on the target machine, I was avoiding it as I wasn't sure what the --unsafe-perm flag meant. It's strange because I've built on Ubuntu before, but retrospectively I can see that I should have persisted in building it on CentOS
