### ISSUE TITLE
[1.4.2][Cordova][Android]

### ISSUE THREAD

**Issue by jagi** [meteor/meteor#8025]
Hi, I'm trying to run Meteor application on Android `meteor run android-device`. My computer and Android device are in the same network. Application open on a device but I get several errors and one warning.

```
=> Started proxy.                             
=> Started MongoDB.                           
                                              
WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and that the network configuration allows
         clients to talk to each other (no client isolation).
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
=> Started app on Android Device.             
I20161106-23:26:05.024(1)? int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied
I20161106-23:26:05.102(1)? 
I20161106-23:26:05.103(1)? Note: log switch off, only log_main and log_events will have logs!
I20161106-23:26:05.105(1)? 11-06 23:26:03.432 30789 30789 I chromium: [INFO:library_loader_hooks.cc(151)] Chromium logging enabled: level = 0, default verbosity = 0
I20161106-23:26:05.105(1)? 11-06 23:26:03.895 30789 30789 I MeteorWebApp: Serving asset bundle with version: d26433e27e5b909f28154e6153a2b92c6904cf6c
I20161106-23:26:05.566(1)? 11-06 23:26:05.860 30789 30789 I chromium: [INFO:CONSOLE(4478)] "Download the React DevTools for a better development experience: https://fb.me/react-devtools", source: http://localhost:12320/packages/modules.js?hash=3cb0008d66366671f9c98f39cb530f35baa6ad69 (4478)
I20161106-23:26:05.658(1)? 11-06 23:26:05.965 30789 30789 E chromium: [ERROR:interface_registry.cc(99)] Failed to locate a binder for interface: autofill::mojom::AutofillDriver
I20161106-23:26:06.553(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: Download failure
I20161106-23:26:06.553(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: com.meteor.webapp.WebAppException: Skipping downloading new version because the Cordova platform version or plugin versions have changed and are potentially incompatible
I20161106-23:26:06.553(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: 	at com.meteor.webapp.WebAppLocalServer.shouldDownloadBundleForManifest(WebAppLocalServer.java:367)
I20161106-23:26:06.554(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: 	at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:131)
I20161106-23:26:06.555(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
I20161106-23:26:06.555(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20161106-23:26:06.555(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
I20161106-23:26:06.555(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
I20161106-23:26:06.555(1)? 11-06 23:26:06.880 30789 30893 E MeteorWebApp: 	at java.lang.Thread.run(Thread.java:833)
I20161106-23:26:06.562(1)? 11-06 23:26:06.890 30789 30789 I chromium: [INFO:CONSOLE(68)] "Error: Skipping downloading new version because the Cordova platform version or plugin versions have changed and are potentially incompatible", source: http://localhost:12320/packages/webapp.js?hash=f3aa8270837e777711cd576e71551ca362ebc55b (68)
```

Application shows up but it's not working. Do you know what can I do to solve this problem?

**Comment by mcoenca** [comment]
Have you tried removing .meteor/local/cordova-build before running that command ? It seems the build you're pushing contains cordova plugins that are not in the build you installed on your client.

**Comment by jagi** [comment]
I've removed android platform and added it one more time and it worked. So closing this issue. However, Meteor mobile builds seems to cause many problems which makes development really hard.

**Comment by carpmike** [comment]
I've seen that error before too on Android. I believe it is because the websocket can't connect to the back end. For me it was due to not having wifi turned on on my phone. Likely also the same problem if you aren't on the wifi network.
