### ISSUE TITLE
Error building for deploy (ENFILE: file table overflow)

### ISSUE THREAD

**Issue by rijk** [meteor/meteor#8052]
I'm running Meteor 1.4.2.1. I've deployed the exact same codebase successfully last week.

The terminal output:

```
Talking to Galaxy servers at https://eu-west-1.galaxy.meteor.com
Deploying your app...                         
{ [Error: ENFILE: file table overflow, uv_cwd] errno: -23, code: 'ENFILE', syscall: 'uv_cwd' }
/Users/Rijk/.meteor/packages/templating-compiler/.1.2.15.gbaukz++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:177
      throw error;
      ^

Error: ENFILE: file table overflow, open '/Users/Rijk/Code/Projects/transmate/client/lib/semantic-ui/site/elements/list.overrides.import.less'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at wrapper (/tools/fs/files.js:1533:35)
    at wrap.makeCacheKey._len2 (/Users/Rijk/.meteor/packages/meteor-tool/.1.4.2_1.112et1r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/optimistic.js:20:15)
    at Entry._reallyRecompute (/Users/Rijk/.meteor/packages/meteor-tool/.1.4.2_1.112et1r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/Users/Rijk/.meteor/packages/meteor-tool/.1.4.2_1.112et1r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/Users/Rijk/.meteor/packages/meteor-tool/.1.4.2_1.112et1r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/Users/Rijk/.meteor/packages/meteor-tool/.1.4.2_1.112et1r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/compiler.js:558:22
    at Array.forEach (native)
    at /tools/isobuild/compiler.js:494:21
    at /tools/isobuild/compiler.js:184:28
    at Object.withCache (/tools/fs/files.js:1599:12)
    at /tools/isobuild/compiler.js:183:11
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/Rijk/.meteor/packages/meteor-tool/.1.4.2_1.112et1r++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:178:5)
    at /tools/isobuild/bundler.js:2690:24
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2633:31)
    at /tools/isobuild/bundler.js:2580:32
    at Object.withCache (/tools/fs/files.js:1599:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2580:16)
    at Object.bundleAndDeploy (/tools/meteor-services/deploy.js:425:32)
    at Command.func (/tools/cli/commands.js:1319:29)
    at /tools/cli/main.js:1483:23
```

**Comment by rijk** [comment]
A reboot seems to have resolved the issue.

**Comment by PolGuixe** [comment]
It is happening to me quite often every I run meteor.

```
=> Started proxy.
=> Started MongoDB.
/Users/PolGuixe/.meteor/packages/coffeescript/.1.11.1_3.7g1l85++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/PolGuixe/Documents/Developer/Meteor/Apps/LaJunglaBike/node_modules/npm/node_modules/lodash.union'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1533:35)
    at readDirectory (/tools/fs/watch.js:271:26)
    at Watcher._fireIfDirectoryChanged (/tools/fs/watch.js:410:23)
    at /tools/fs/watch.js:662:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.2_1.s0g4ay++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/tools/fs/watch.js:651:7)
    at new Watcher (/tools/fs/watch.js:359:10)
    at setupClientWatcher (/tools/runners/run-app.js:786:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:797:7)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

**Comment by rijk** [comment]
I do get it quite often as well.. Having to reboot every time is a bother :/

**Comment by PolGuixe** [comment]
@rijk apparently it is an issue with macOSx. At least it was in my case: 

See https://github.com/meteor/meteor/issues/8057

**Comment by rijk** [comment]
Ah, thanks for the heads up! 👍
