### ISSUE TITLE
es2015 preset within .babelrc breaks globals

### ISSUE THREAD

**Issue by dburles** [meteor/meteor#8058]
Storybook adds a `.babelrc` that looks like:

```
{
  "presets": [
    "es2015",
    "es2016",
    "react",
    "stage-1"
  ],
  "plugins": [
    "babel-root-slash-import"
  ]
}
```

Defining a variable like `X = true;` anywhere in the app causes Meteor to dump the following error:

```
W20161116-12:19:23.811(11)? (STDERR) /Users/dave/.meteor/packages/meteor-tool/.1.4.2_1.jehjpf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161116-12:19:23.812(11)? (STDERR) 						throw(ex);
W20161116-12:19:23.813(11)? (STDERR) 						^
W20161116-12:19:23.814(11)? (STDERR) 
W20161116-12:19:23.814(11)? (STDERR) ReferenceError: X is not defined
W20161116-12:19:23.815(11)? (STDERR)     at meteorInstall.test.js (test.js:1:1)
W20161116-12:19:23.816(11)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161116-12:19:23.817(11)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161116-12:19:23.817(11)? (STDERR)     at /Users/dave/Projects/hiapp/.meteor/local/build/programs/server/app/app.js:51:1
W20161116-12:19:23.818(11)? (STDERR)     at /Users/dave/Projects/hiapp/.meteor/local/build/programs/server/boot.js:295:34
W20161116-12:19:23.818(11)? (STDERR)     at Array.forEach (native)
W20161116-12:19:23.818(11)? (STDERR)     at Function._.each._.forEach (/Users/dave/.meteor/packages/meteor-tool/.1.4.2_1.jehjpf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20161116-12:19:23.819(11)? (STDERR)     at /Users/dave/Projects/hiapp/.meteor/local/build/programs/server/boot.js:128:5
W20161116-12:19:23.819(11)? (STDERR)     at /Users/dave/Projects/hiapp/.meteor/local/build/programs/server/boot.js:344:5
W20161116-12:19:23.819(11)? (STDERR)     at Function.run (/Users/dave/Projects/hiapp/.meteor/local/build/programs/server/profile.js:480:12)
=> Exited with code: 1
```

Is there a potential workaround here? or is it expected that this would break the Meteor build?

**Comment by stubailo** [comment]
I mean Meteor code that uses globals is not valid ES2015. So I would expect this to break - you probably just need to change the babelrc.

**Comment by dburles** [comment]
Yeah, I figured. It's annoying as storybook relies on it and it breaks when it's removed, so I thought I might as well see if there is a workaround on this end!

**Comment by stubailo** [comment]
Interesting - how does storybook rely on a particular babelrc?

**Comment by dburles** [comment]
Ok (from what I understand) it looks like now it's not actually required, it's just that the getstorybook generator for Meteor still adds one to the project root by default :)

**Comment by crapthings** [comment]
@dburles 

how to solved this ? i've removed .babelrc and i still can't use global

X = something

**Comment by dburles** [comment]
@crapthings shouldn't be a problem with no `.babelrc`
