### ISSUE TITLE
Adding highlight.js (through npm) throws an error when using in code (but not in meteor shell)

### ISSUE THREAD

**Issue by laddi** [meteor/meteor#8119]
I'm trying to add [highlight.js](https://highlightjs.org) so I run the following:

`meteor npm install highlight.js`

This runs smoothly and the package is installed correctly.  Then I go to `meteor shell` and run the following:

`import { highlight } from 'highlight.js';`

Also, runs fine and I can use the package to syntax highlight code correctly.  The problem starts when I try to use the same import in code.  Then my application fails spectacularly with the following error:

```
/Users/laddi/.meteor/packages/meteor-tool/.1.4.2_3.1e4huql++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
                        throw(ex);
                        ^

Error: Cannot find module './highlight'
    at require (packages/modules-runtime.js:109:19)
    at meteorInstall.node_modules.k8s.index.js.__webpack_require__.callbackFunction.primise.then.get.done.logs.done.post.done.put.done.highlight.js.lib.index.js (packages/modules.js:4858:12)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/Users/laddi/.meteor/packages/modules/.0.7.7.3t9ga6++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.server.xxx.yyy.zzz.js (/Users/laddi/Development/xxx/zzz/.meteor/local/build/programs/server/app/app.js:25024:354)
```

This is, as far as I can tell, a Meteor error and not an error in the package itself, otherwise it would also fail in `meteor shell`.

Platform: Mac
Version: 1.4.2.3

**Comment by runarberg** [comment]
This works fine when importing client side:

```bash
cd /tmp
meteor create foo
cd foo
meteor npm install highlight.js
meteor npm install
echo "import hljs from 'highligh.js';" >> client/main.js
echo "console.log(hljs);" >> client/main.js
meteor
```

```
[[[[[ /private/tmp/foo ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
```

Navigating to the page, the correct module appears in the console output:

```
Object { highlight: highlight(), highlightAuto: highlightAuto(), fixMarkup: fixMarkup(), highlightBlock: highlightBlock(), configure: configure(), initHighlighting: initHighlighting(), initHighlightingOnLoad: initHighlightingOnLoad(), registerLanguage: registerLanguage(), listLanguages: listLanguages(), getLanguage: getLanguage(), 23 more… }  app.js:62:5
```

But as soon as we try to import this server side, we get this annoying error:

```bash
echo "import hljs from 'highlight.js'" >> server/main.js
meteor
```

```
[[[[[ /private/tmp/foo ]]]]]

=> Started proxy.
=> Started MongoDB.
W20161130-15:10:11.421(-8)? (STDERR) /Users/runarberg/.meteor/packages/meteor-tool/.1.4.2_3.1mqloml++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161130-15:10:11.522(-8)? (STDERR) 						throw(ex);
W20161130-15:10:11.523(-8)? (STDERR) 						^
W20161130-15:10:11.523(-8)? (STDERR)
W20161130-15:10:11.524(-8)? (STDERR) Error: Cannot find module './highlight'
W20161130-15:10:11.524(-8)? (STDERR)     at require (packages/modules-runtime.js:109:19)
W20161130-15:10:11.524(-8)? (STDERR)     at meteorInstall.node_modules.highlight.js.lib.index.js (packages/modules.js:345:12)
W20161130-15:10:11.525(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161130-15:10:11.526(-8)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20161130-15:10:11.526(-8)? (STDERR)     at Module.Mp.import (/Users/runarberg/.meteor/packages/modules/.0.7.7.18rrid9++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20161130-15:10:11.526(-8)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:1)
W20161130-15:10:11.526(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161130-15:10:11.527(-8)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161130-15:10:11.527(-8)? (STDERR)     at /private/tmp/foo/.meteor/local/build/programs/server/app/app.js:18:1
W20161130-15:10:11.528(-8)? (STDERR)     at /private/tmp/foo/.meteor/local/build/programs/server/boot.js:295:34
=> Exited with code: 1
```

**Comment by benjamn** [comment]
I believe you need to run `meteor npm install --save highlight.js` so that the `highlight.js` dependency will be listed in `package.json` (and not just temporarily installed in `node_modules`).

**Comment by abernix** [comment]
I had actually just confirmed, yes, it does work if you use `--save`.

This is possibly similar or the same reason as whatever is causing #7990.  I commented here about it: https://github.com/meteor/meteor/issues/7990#issuecomment-262562209
