### ISSUE TITLE
Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by Jayuda** [meteor/meteor#8124]
i have error on meteor in server. But at development on local work well. 
This log show on server. 
Any sugestions ?
Thanks anyway

```
    O2016-12-02T03:53:08.851800591Z TypeError: Cannot read property 'slice' of null
    A2016-12-02T03:53:08.851808036Z     at packages/meteor.js:1221:19
    @2016-12-02T03:53:08.851815363Z     at packages/meteor.js:1233:4
    @2016-12-02T03:53:08.851827034Z     at packages/meteor.js:1380:3
    T2016-12-02T03:53:08.851839639Z     at /bundle/bundle/programs/server/boot.js:295:34
    =2016-12-02T03:53:08.851848646Z     at Array.forEach (native)
    2016-12-02T03:53:08.851856346Z     at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    S2016-12-02T03:53:08.851864074Z     at /bundle/bundle/programs/server/boot.js:128:5
    S2016-12-02T03:53:08.851871656Z     at /bundle/bundle/programs/server/boot.js:344:5
    f2016-12-02T03:53:08.851878996Z     at Function.run (/bundle/bundle/programs/server/profile.js:480:12)
    T2016-12-02T03:53:08.851886459Z     at /bundle/bundle/programs/server/boot.js:343:11
```

**Comment by abernix** [comment]
Have you tried looking at line 1221 of `packages/meteor.js`?  What does it say?

The problem you're referring to is too vague to accurately provide help.  Here is [more information on reporting a bug with Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug).

**Comment by Jayuda** [comment]
Thanks Mr. @abernix ,
on `packages/meteor.js` line 1221 show : 
```
var pathPrefix = parsedUrl.pathname;
    if (pathPrefix.slice(-1) === '/') {
```

its my wrong at declare `ROOT_URL=192.168.0.2` not use `http://`. 
So i change to `ROOT_URL=http://192.168.0.2` all work like charm. 

Thanks for your help
