### ISSUE TITLE
Weird crash trying to run recently updated project

### ISSUE THREAD

**Issue by jay-depot** [meteor/meteor#8148]
I've just updated a project from Meteor 1.2.x to the latest release version. Everything went smoothly on the update to 1.3.5.1, but when I ran the final `meteor update` to bring the project up to 1.4.2.3, the app started crashing with a really weird error. From what I'm seeing here: https://github.com/meteor/meteor/blob/devel/tools/isobuild/resolver.js#L317 this should be impossible. Somehow I'm seeing this output when I try to run this project:

```
--- Projects/untapped ‹master*➔ M› » meteor run --settings ./settings.json                                                                                                                                      1 ↵
[[[[[ ~/Projects/untapped ]]]]]               

=> Started proxy.                             
=> Started MongoDB.                           
/home/unleet/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Cannot set property '/home/unleet/Projects/untapped/package.json' of undefined
    at Resolver._resolvePkgJsonMain (/tools/isobuild/resolver.js:320:9)
    at Resolver._resolve (/tools/isobuild/resolver.js:123:25)
    at /tools/isobuild/resolver.js:75:19
    at Entry._reallyRecompute (/home/unleet/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/home/unleet/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/home/unleet/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at Resolver.optimistic [as resolve] (/home/unleet/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at ImportScanner._resolve (/tools/isobuild/import-scanner.js:466:36)
    at /tools/isobuild/import-scanner.js:499:29
    at _.each._.forEach (/home/unleet/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:498:5)
    at /tools/isobuild/import-scanner.js:344:14
    at Array.forEach (native)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:342:22)
    at /tools/isobuild/compiler-plugin.js:1040:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1008:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1020:8)
    at /tools/isobuild/bundler.js:791:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:782:18)
    at /tools/isobuild/bundler.js:2652:14
    at /tools/isobuild/bundler.js:2741:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/unleet/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2740:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2633:31)
    at /tools/isobuild/bundler.js:2580:32
    at Object.withCache (/tools/fs/files.js:1601:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2580:16)
    at /tools/runners/run-app.js:574:36
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:573:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

Unfortunately, I can't share the full app code, but if this isn't an easy fix, I can try to create a simple repro case for it.

**Comment by jay-depot** [comment]
Figured it out. The `cosmos:browserify` package seems to be the cause.

**Comment by HungryDinosaur** [comment]
Hey @jay-depot, I'm running into this issue too, what did you do to resolve it?

**Comment by HungryDinosaur** [comment]
Never mind, I resolved my issue: http://stackoverflow.com/questions/41445266/whenever-i-import-the-node-instagram-module-meteor-crashes/
