### ISSUE TITLE
EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by Proxy08** [meteor/meteor#8224]
Meteor version `1.4.2.3`
Window 10 
Whenever I try to execute meteor command it show following error

```
capta@MINGW64

 /d/meteor/kuntsammler
$ meteor
[[[[[  #~\D\meteor\kuntsammler ]]]]]

=> Started proxy.
=> Started MongoDB.
C:\Users\capta\AppData\Local\.meteor\packages\templating-compiler\1.2.15\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:177
      throw error;
      ^

Error: EISDIR: illegal operation on a directory, symlink 'C:\Users\capta\AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules' -> 'D:\meteor\kuntsammler\.meteor\local\.build31850.build\programs\.build216248.server\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1535:35)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:737:5)
    at Builder.write (C:\tools\isobuild\builder.js:266:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2228:15)
    at C:\tools\isobuild\bundler.js:2336:30
    at C:\tools\isobuild\bundler.js:2469:9
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2459:26
    at C:\tools\isobuild\bundler.js:2399:7
    at C:\tools\isobuild\bundler.js:2800:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2633:31)
    at C:\tools\isobuild\bundler.js:2580:32
    at Object.withCache (C:\tools\fs\files.js:1601:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2580:16)
    at C:\tools\runners\run-app.js:574:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:573:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:617:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:876:28)
    at `C:\tools\runners\run-app.js:403:12
```

I tried to completely reinstall meteor multiple time, but still no effect. Please someone can help me with this issue.

**Comment by abernix** [comment]
Minimalist GNU for Windows is not supported by Meteor (or many applications).  Please use Windows PowerShell (or Command Prompt).

Ultimately, the problem here is that Windows doesn't support creating symlinks for unprivileged users and when running under Mingw32, this is not prevented as Meteor thinks it's running on a true Unix system.  On Windows, Meteor uses junction instead as a work-around for this, but they are prone to their own problems (#7414).  While Windows does (now) support symlinks to be created unprivileged on some more recent "Insider" builds, it's still experimental.

In the future, the hope is that "Bash on Windows" will make Meteor a lot less painless on Windows, but there are still a number of deficiencies in Windows that are preventing that from happening right now.  See #7583 for more information and to track that progress.

**Comment by ghybs** [comment]
Hi,

FWIW, I had this exact error message when trying to use Meteor on an `exFAT` drive with Windows.
Just to realize that symlinks are not supported in this configuration, so I had to move my project to a Windows `NTFS` drive, and then everything works fine.

Hope this helps.

**Comment by SCOZYTOUNY** [comment]
I had this exact error message when trying to use OMNIVERSE on an exFAT drive with Windows10.
Just to realize that symlinks are not supported in this configuration, so I had to FORMATE THE DRIVE TO NTFS drive .
