### ISSUE TITLE
Meteor 1.4.2.3 "Unexpected token ..." @ packages/modules : 454

### ISSUE THREAD

**Issue by TheGame2500** [meteor/meteor#8258]
Hey there, Meteor 1.4.2.3 here on Ubuntu 16.04.

I get 
```
W20170115-12:09:16.853(2)? (STDERR) packages/modules.js:454
W20170115-12:09:16.853(2)? (STDERR)     const generator = makeGenerator(...arguments);
W20170115-12:09:16.854(2)? (STDERR)                                     ^^^
W20170115-12:09:16.854(2)? (STDERR) 
W20170115-12:09:16.854(2)? (STDERR) SyntaxError: Unexpected token ...
W20170115-12:09:16.854(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170115-12:09:16.854(2)? (STDERR)     at /home/bira/workspace/upwork/brianBarnett/image-matcher/.meteor/local/build/programs/server/boot.js:289:30
W20170115-12:09:16.854(2)? (STDERR)     at Array.forEach (native)
W20170115-12:09:16.854(2)? (STDERR)     at Function._.each._.forEach (/home/bira/.meteor/packages/meteor-tool/.1.4.2_3.qrjzn2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170115-12:09:16.854(2)? (STDERR)     at /home/bira/workspace/upwork/brianBarnett/image-matcher/.meteor/local/build/programs/server/boot.js:128:5
W20170115-12:09:16.855(2)? (STDERR)     at /home/bira/workspace/upwork/brianBarnett/image-matcher/.meteor/local/build/programs/server/boot.js:344:5
W20170115-12:09:16.855(2)? (STDERR)     at Function.run (/home/bira/workspace/upwork/brianBarnett/image-matcher/.meteor/local/build/programs/server/profile.js:480:12)
W20170115-12:09:16.855(2)? (STDERR)     at /home/bira/workspace/upwork/brianBarnett/image-matcher/.meteor/local/build/programs/server/boot.js:343:11
```

when trying to run my app. I should probably mention mention that I did install babel-runtime as a npm dependency, so I'm not sure what's going on.

**Comment by TheGame2500** [comment]
Sorry, had to do with a NPM package I was using.
