### ISSUE TITLE
[1.5-beta.4] Windows 10 x64 - Can't run basic example

### ISSUE THREAD

**Issue by tcastelli** [meteor/meteor#8336]
Reproduction steps:

````
meteor create basic-example --release 1.5-beta.3
cd basic-example
meteor npm install
meteor
````

Produced Error is

````
C:\Users\Dell\AppData\Local\.meteor\packages\templating-compiler\1.3.0\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:177
      throw error;
      ^

TypeError: Cannot read property '0' of undefined
    at toDosPath (C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.0-beta.3\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:33:8)
    at C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.0-beta.3\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:90:16
    at Array.map (native)
    at Function._.map._.collect (C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.0-beta.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:97:56)
    at C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.0-beta.3\mt-os.windows.x86_32\tools\static-assets\server\mini-files.js:87:16
    at ImportScanner._getRelativeImportId (C:\tools\isobuild\import-scanner.js:519:7)
    at C:\tools\isobuild\import-scanner.js:502:33
    at _.each._.forEach (C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.0-beta.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at C:\tools\isobuild\import-scanner.js:498:7
    at ImportScanner._resolve (C:\tools\isobuild\import-scanner.js:494:46)
    at C:\tools\isobuild\import-scanner.js:556:29
    at _.each._.forEach (C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.0-beta.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:550:5)
    at C:\tools\isobuild\import-scanner.js:377:14
    at ImportScanner.addNodeModules (C:\tools\isobuild\import-scanner.js:372:33)
    at C:\tools\isobuild\compiler-plugin.js:1099:32
    at Map.forEach (native)
    at handleMissing (C:\tools\isobuild\compiler-plugin.js:1097:18)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:1109:5)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:1047:8)
    at C:\tools\isobuild\bundler.js:818:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:809:18)
    at C:\tools\isobuild\bundler.js:2771:14
    at C:\tools\isobuild\bundler.js:2860:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Dell\AppData\Local\.meteor\packages\meteor-tool\1.5.0-beta.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2859:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2752:31)
    at C:\tools\isobuild\bundler.js:2699:32
    at Object.withCache (C:\tools\fs\files.js:1601:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2699:16)
    at C:\tools\runners\run-app.js:574:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:573:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:617:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:876:28)
    at C:\tools\runners\run-app.js:403:12
````

**Comment by abernix** [comment]
Thanks for reporting this, @tcastelli.

**Comment by benjamn** [comment]
[`ImportScanner#_getRelativeImportId`](https://github.com/meteor/meteor/pull/8327/commits/0e210ef53cccae8810829e218d06c854dc21cef5#diff-d6c77eb9e6788966e380d6626a030ff4R512) is new in 1.5, so I'm guessing it's not quite right. Sorry about that.
