### ISSUE TITLE
[1.4.3.1] SyntaxError: Unexpected end of input checking `package.json` for portability.

### ISSUE THREAD

**Issue by PolGuixe** [meteor/meteor#8427]
I am trying to update an app from 1.4.2.7 to 1.4.3.1. When I run meteor update I am getting the following error: 
```
/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.10aai9w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /tools/fs/optimistic.js:204:17
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
    at Entry._reallyRecompute (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.10aai9w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.10aai9w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.10aai9w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.10aai9w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/meteor-npm.js:478:31
    at /tools/isobuild/meteor-npm.js:491:9
    at Array.every (native)
    at /tools/isobuild/meteor-npm.js:488:30
    at /tools/isobuild/meteor-npm.js:491:9
    at Array.every (native)
    at /tools/isobuild/meteor-npm.js:488:30
    at /tools/isobuild/meteor-npm.js:284:9
    at Array.forEach (native)
    at Object.rebuildIfNonPortable (/tools/isobuild/meteor-npm.js:281:33)
    at /tools/isobuild/bundler.js:423:19
    at Function._.each._.forEach (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.10aai9w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at Function.readDirsFromJSON (/tools/isobuild/bundler.js:422:9)
    at /tools/isobuild/isopack.js:1095:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.10aai9w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at [object Object]._.extend._loadUnibuildsFromPath (/tools/isobuild/isopack.js:965:7)
    at [object Object].initFromPath (/tools/isobuild/isopack.js:885:17)
    at /tools/isobuild/isopack-cache.js:286:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/isopack-cache.js:272:24
    at Function.time (/tools/tool-env/profile.js:305:10)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:262:15)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.10aai9w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:841:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:840:18)
    at /tools/project-context.js:283:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:273:18)
    at /tools/project-context.js:265:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:264:13)
    at /tools/cli/commands-packages.js:1528:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at maybeUpdateRelease (/tools/cli/commands-packages.js:1527:8)
    at Command.func (/tools/cli/commands-packages.js:1601:29)
    at /tools/cli/main.js:1483:23
```

I am using macOS 10.12.3 .

**Comment by PolGuixe** [comment]
I've already tried to remove meteor and install it again. The error persists.

**Comment by generalleger** [comment]
+1 I too am experiencing this issue.  macOS 10.12.3

**Comment by abernix** [comment]
One of the `package.json` files in your project's `node_modules` would seem to have an invalid structure to it – this could have other implications (such as `npm` not being able to read it itself), so you may want to look into this anyway.  The error message here should be more clear though and identify which file is problematic.

The relevant part of this stack trace is:

    at /tools/isobuild/meteor-npm.js:478:31

Which points to https://github.com/meteor/meteor/blob/331e6e2c98fbad520a40e3f23039ed57c6d486be/tools/isobuild/meteor-npm.js#L478

Essentially, the error is happening because Meteor 1.4.3.1 attempts to parse the `package.json` file for each NPM module in the project to see if it has a `install`, `postinstall` or `preinstall` script present (thanks to bcffe53).  The presence of these may indicate the presence of binary dependencies, so Meteor marks it as non-portable so they are rebuilt when switched to different architecture.

To find the offending file, you may want to try something like the following which will attempt to parse each `package.json` and print `FAIL` if it doesn't work and `OK` if successful:

    find . -name 'package.json' -exec node -e 'var result; try { result = JSON.parse(require("fs").readFileSync(require("path").resolve("{}"))) && "OK"; } catch (err) { result = "FAIL"; } console.log("{}", result);' \;

**Comment by generalleger** [comment]
thanks for the detailed response!  I ran the script and all of my packages came back with a status of OK

**Comment by PolGuixe** [comment]
I run the same script and all of my packages came back with OK status, as well.

**Comment by abernix** [comment]
Interesting!  It may be a NPM which an Atmosphere package is depending on as well, I suppose.

What if you add a `console.log(pkgJsonPath);` above the offending like (478) in this file:

    ~/.meteor/packages/meteor-tool/1.4.3_1/mt-os.osx.x86_64/tools/isobuild/meteor-npm.js

...And restart your `meteor`? 

(Note, if you're not on macOS, you should change `mt-os.osx.x86_64` accordingly).

**Comment by PolGuixe** [comment]
I've added the log in line 476. 

Here is the new log: 
```
/Users/PolGuixe/.meteor/packages/kadira_flow-router-ssr/.3.13.0.1vp6oj2++os+web.browser+web.cordova/npm/node_modules/nopt/examples/package.json
/Users/PolGuixe/.meteor/packages/kadira_flow-router-ssr/.3.13.0.1vp6oj2++os+web.browser+web.cordova/npm/node_modules/nopt/lib/package.json
/Users/PolGuixe/.meteor/packages/kadira_flow-router-ssr/.3.13.0.1vp6oj2++os+web.browser+web.cordova/npm/node_modules/nopt/test/package.json
/Users/PolGuixe/.meteor/packages/kadira_flow-router-ssr/.3.13.0.1vp6oj2++os+web.browser+web.cordova/npm/node_modules/npmconf/package.json
/Users/PolGuixe/.meteor/packages/kadira_flow-router-ssr/.3.13.0.1vp6oj2++os+web.browser+web.cordova/npm/node_modules/npmconf/lib/package.json
/Users/PolGuixe/.meteor/packages/kadira_flow-router-ssr/.3.13.0.1vp6oj2++os+web.browser+web.cordova/npm/node_modules/npmconf/test/package.json
/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /tools/fs/optimistic.js:204:17
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
    at Entry._reallyRecompute (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/Users/PolGuixe/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/meteor-npm.js:478:31
```

**Comment by generalleger** [comment]
Exact same result on my end

**Comment by abernix** [comment]
Thanks, I see the problem, indeed in an NPM dependency of a Atmosphere package, in this case `kadirahq:flow-router-ssr` within the `npmconf` NPM – [in this file](https://github.com/npm/npmconf/blob/master/test/fixtures/package.json).

**Comment by PolGuixe** [comment]
any way of solving it?

**Comment by generalleger** [comment]
Not sure, but fyi - the non-ssr flow-router updated to the latest version just fine.

**Comment by PolGuixe** [comment]
I was thinking on migrating to React-router.... maybe it is a signal 😅

**Comment by jlichti** [comment]
Hit this issue as well. Probably time to move off flow router.

**Comment by heschong** [comment]
Same here, mine crashes on the twbs_bootstrap package, not flowrouter.  Uses npmconf as a dependency as well.

**Comment by gary-menzel** [comment]
After making sure I update absolutely every package to the latest version - I temporarily "fixed" it by adding an empty pair of braces {} to the empty package.json file deep in the bowels of the .meteor node_modules. This got me over the error and updated to 1.4.3.1 without further issue.  As far as I can see, it is only in the test/fixtures folder and is not consequential to the operation of the package. The "downside" would be when the package is downloaded again still with the empty package.json still there.  It should be removed from flow-router-ssr (as it is a deprecated package with the functionality now available in the npm package directly).

**Comment by PolGuixe** [comment]
@gary-menzel is `flowrouter` available as an npm package?

**Comment by gary-menzel** [comment]
@PolGuixe not that I know of.  I just went in to where it is stored in the .meteor node_modules folder and found the `npmconf` package.  Given NPM is now in Meteor core, it should be possible to rewrite the sections of `flowrouter` that use `npmconf` to use NPM inside Meteor (although I have not looked at how easy that would be to do and I know that Arunoda is not focussing on Meteor anymore).

I've looked at React Router but it seems too-html/declarative from my perspective.  I prefer my routes to be in javascript and `flowrouter` just seems to work as I would expect it to.

**Comment by vauruk** [comment]
I have the same error, in execute meteor update --release 1.4.3.1

**Comment by robertpitt** [comment]
Having tyhe same issue here, works well with `1.4.2.*`

**Comment by gary-menzel** [comment]
In my case the offending package.json was an EMPTY file.  It had nothing in it.  I just added {} and it was then happy.  This does not seem to bother `npm` (I suspect they just ignore it and report the normal missing stuff) so maybe Meteor could consider ignoring a file if it had a length of zero?

**Comment by jamiter** [comment]
@abernix, this also prevents us from using 1.4.3+. Should we wait for a fix or is this something outside of Meteor that we should work around ourselves?

**Comment by abernix** [comment]
This should be fixed in Meteor 1.4.3.2.  You can try the latest 1.4.3.2 beta and help confirm by running:

    meteor update --release 1.4.3.2-beta.0

Please report back if you encounter any problems, and thanks for reporting initially!

**Comment by ProphetDaniel** [comment]
After updating my app through `meteor update --release 1.4.3.2-beta.0`

Then trying to run with plain `meteor`

```
/home/daniel/.meteor/packages/templating-compiler/.1.3.1.1nq0emr++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /tools/fs/optimistic.js:204:17
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
    at Entry._reallyRecompute (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at Resolver._resolvePkgJsonMain (/tools/isobuild/resolver.js:283:17)
    at Resolver._resolve (/tools/isobuild/resolver.js:123:25)
    at /tools/isobuild/resolver.js:75:19
    at Entry._reallyRecompute (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at Resolver.optimistic [as resolve] (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at ImportScanner._resolve (/tools/isobuild/import-scanner.js:471:36)
    at /tools/isobuild/import-scanner.js:504:29
    at _.each._.forEach (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:503:5)
    at /tools/isobuild/import-scanner.js:594:12
    at _.each._.forEach (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:503:5)
    at ImportScanner.addNodeModules (/tools/isobuild/import-scanner.js:369:14)
    at /tools/isobuild/compiler-plugin.js:1099:32
    at Map.forEach (native)
    at handleMissing (/tools/isobuild/compiler-plugin.js:1097:18)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1109:5)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1057:8)
    at /tools/isobuild/bundler.js:828:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:819:18)
    at /tools/isobuild/bundler.js:2689:14
    at /tools/isobuild/bundler.js:2778:20
    at Array.forEach (native)
    at Function._.each._.forEach (/home/daniel/.meteor/packages/meteor-tool/.1.4.3-2-beta.0.txvozy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2777:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2670:31)
    at /tools/isobuild/bundler.js:2617:32
    at Object.withCache (/tools/fs/files.js:1601:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2617:16)
    at /tools/runners/run-app.js:588:36
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:587:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12

```

**Comment by abernix** [comment]
@ProphetDaniel Please try using a more recent, non-beta version of Meteor and if you still experience a problem please open a new issue with a minimal reproduction per the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) instructions.

**Comment by PushanPatel** [comment]
I am getting following error. I have tried uninstalling and then reinstalling both meteor.js as well as chocolatey(installer for windows for meteor.js). Even then the problem is not getting resolved. What should I do?
`
D:\Coursera_Web_development\Course 3 - Meteor.js\My tried\getting_started>meteor create image_share
C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: C:\WINDOWS\system32\cmd.exe /c C:\Users\Admin\AppData\Local\.meteor\packages\meteor-tool\1.10.2\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd install --production=false
npm ERR! Unexpected end of JSON input while parsing near '...AyLGrzLyLyZprcfC5KsYc'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-05-12T04_56_54_151Z-debug.log
npm ERR! Unexpected end of JSON input while parsing near '...AyLGrzLyLyZprcfC5KsYc'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-05-12T04_56_54_151Z-debug.log

    at Object.error (C:\tools\utils\buildmessage.js:467:11)
    at C:\tools\cli\default-npm-deps.js:36:20
    at Object.enterJob (C:\tools\utils\buildmessage.js:356:14)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:837:36)
    at C:\tools\cli\main.js:1528:15 
`
Due to this my app crashes everytime
