### ISSUE TITLE
Building error due to some utf filenames

### ISSUE THREAD

**Issue by far4599** [meteor/meteor#8434]
Hi friends,

The solution is to use plane english file names.

I use 1.4.3.1 (Win7 x64) and came across the problem with file naming. If file name contains utf [diaeresis](https://en.wikipedia.org/wiki/Diaeresis_(diacritic))-like letters like "ô" or "é" (even if the file is within 'public' folder) it will cause the following error during building process (it is shown here like the problem occured in Coffeescript plugin, but it may be i.e. "templating-compiler" or any other):

C:\dev\.meteor\packages\coffeescript\1.12.0_1\plugin.compileCoffeescript.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: Must provide either sourcePath or data
    at new File (C:\tools\isobuild\bundler.js:551:13)
    at C:\tools\isobuild\bundler.js:1088:19
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:1083:17
    at Array.forEach (native)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:1060:19)
    at C:\tools\isobuild\bundler.js:828:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:819:18)
    at C:\tools\isobuild\bundler.js:2689:14
    at C:\tools\isobuild\bundler.js:2778:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\dev\.meteor\packages\meteor-tool\1.4.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2777:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2670:31)
    at C:\tools\isobuild\bundler.js:2617:32
    at Object.withCache (C:\tools\fs\files.js:1601:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2617:16)
    at C:\tools\runners\run-app.js:574:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:573:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:814:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:876:28)
    at C:\tools\runners\run-app.js:403:12

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Specifically, please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed for a reproduction.  :)

**Comment by stefanve** [comment]
I got this error today when I put a document "händischer-lst.pdf" in the folder 'public/download'. Changing the name to 'haendischer-lst.pdf' fixed the problem, so obviously there is something in the build process that does not like extended ASCII. My error trace was very similar to the one posted by @far4599 
I had not referenced the document, just thrown it in there for future use, so the error was very confusing and I might have gone through a much longer and more painful debug cycle had I not discovered this issue...
