### ISSUE TITLE
Update 1.4.2.7 to 1.4.3.1 : fiber future crash on boot

### ISSUE THREAD

**Issue by Ontokrat** [meteor/meteor#8472]
Hi,
I just perform an update from Meteor 1.4.2.7 to 1.4.3.1. Everything's worked fine in 1.4.2.7.
On server boot, I got : 
```
W20170310-15:26:43.597(1)? (STDERR) /Users/d/.meteor/packages/meteor-tool/.1.4.3_1.qj9trq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170310-15:26:43.598(1)? (STDERR) 						throw(ex);
W20170310-15:26:43.598(1)? (STDERR) 						^
W20170310-15:26:43.598(1)? (STDERR) 
W20170310-15:26:43.598(1)? (STDERR) TypeError: Cannot read property 'export' of undefined
W20170310-15:26:43.598(1)? (STDERR)     at meteorInstall.imports.api.public.handle-webhook.js (imports/api/public/handle-webhook.js:1:1)
W20170310-15:26:43.599(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170310-15:26:43.599(1)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170310-15:26:43.600(1)? (STDERR)     at Module.Mp.import (/Users/d/.meteor/packages/modules/.0.7.9.1n4od2s++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170310-15:26:43.600(1)? (STDERR)     at meteorInstall.imports.api.public.api.js (imports/api/public/api.js:1:192)
W20170310-15:26:43.601(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170310-15:26:43.602(1)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170310-15:26:43.602(1)? (STDERR)     at Module.Mp.import (/Users/d/.meteor/packages/modules/.0.7.9.1n4od2s++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170310-15:26:43.603(1)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:127)
W20170310-15:26:43.603(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170310-15:26:43.603(1)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170310-15:26:43.603(1)? (STDERR)     at /Users/d/ontokratmeteor/.meteor/local/build/programs/server/app/app.js:2888:1
W20170310-15:26:43.604(1)? (STDERR)     at /Users/d/ontokratmeteor/.meteor/local/build/programs/server/boot.js:303:34
W20170310-15:26:43.605(1)? (STDERR)     at Array.forEach (native)
W20170310-15:26:43.606(1)? (STDERR)     at Function._.each._.forEach (/Users/d/.meteor/packages/meteor-tool/.1.4.3_1.qj9trq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170310-15:26:43.608(1)? (STDERR)     at /Users/d/ontokratmeteor/.meteor/local/build/programs/server/boot.js:128:5
W20170310-15:26:43.608(1)? (STDERR)     at /Users/d/ontokratmeteor/.meteor/local/build/programs/server/boot.js:352:5
W20170310-15:26:43.608(1)? (STDERR)     at Function.run (/Users/d/ontokratmeteor/.meteor/local/build/programs/server/profile.js:510:12)
W20170310-15:26:43.609(1)? (STDERR)     at /Users/d/ontokratmeteor/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
```

I've tried to perform `meteor update --all-packages` `meteor npm update --save` `meteor npm rebuild` `removing node_modules directory and doing a fresh NPM install with meteor npm install`: nothing works.

Even try to follow [this issue discussion](https://github.com/meteor/meteor/issues/8427): 
I've got only OK with `find . -name 'package.json' -exec node -e 'var result; try { result = JSON.parse(require("fs").readFileSync(require("path").resolve("{}"))) && "OK"; } catch (err) { result = "FAIL"; } console.log("{}", result);' \;`
`meteor update --release 1.4.3.2-beta.0` as @abernix  proposed change nothing. 

Can you help me?
Below my `package.json` dependencies

```
"dependencies": {
    "babel-polyfill": "^6.23.0",
    "babel-runtime": "^6.23.0",
    "bcrypt": "^0.8.7",
    "blob": "0.0.4",
    "body-parser": "^1.17.1",
    "fibers": "^1.0.15",
    "future": "^2.3.1",
    "iconv-lite": "^0.4.15",
    "jit-grunt": "^0.10.0",
    "meteor-node-stubs": "^0.2.5",
    "payment": "^2.2.1",
    "pdfkit": "^0.8.0",
    "postmark": "^1.3.1",
    "simpl-schema": "^0.1.1",
    "sweetalert2": "^6.4.3",
    "twilio": "^2.11.1",
    "wenk": "^1.0.5"
  }
```

**Comment by hwillson** [comment]
Hi @Ontokrat - it's difficult to help troubleshoot without seeing your code. For example, what are you doing in `imports/api/public/handle-webhook.js`? Any chance you could put together a small, runnable reproduction showing this problem (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) for more info)? Thanks!

**Comment by Ontokrat** [comment]
Hi @hwillson - thanks for answering. My code was working just fine few hours ago, just before updating Meteor. Anyway, below the code of this file `imports/api/public/handle-webhook.js`

```
/* eslint-disable consistent-return */
import { stripeHandler } from './providers/stripe';
import { twilioHandler } from './providers/twilio';
import { postmarkHandler } from './providers/postmark';

let module;

const providers = {
  stripe: stripeHandler,
  twilio: twilioHandler,
  postmark: postmarkHandler,
};

const handler = ({ provider, request }, promise) => {
  try {
    module = promise;
    const targetProvider = providers[provider];
    if (targetProvider) targetProvider({ body: request.body });
    module.resolve();
    //empty response for every provider or twilio will send it back by sms on incommming message
    //module.resolve('Webhook received!');
  } catch (exception) {
    module.reject(`[handleWebhook.handler] ${exception}`);
  }
};

export const handleWebhook = (options) =>
new Promise((resolve, reject) =>
handler(options, { resolve, reject }));
```

**Comment by hwillson** [comment]
I wouldn't recommend using `module` as a variable name. Try changing that to something like `myModule`, and I think you'll find that your app will start properly.

**Comment by Ontokrat** [comment]
@hwillson You are so right! That was exactly the issue.
Sorry to report it as an issue of Meteor 1.4.3.1: maybe it was that this bad habit to use `module` as a variable name break the code when fiber future has been updated with the `meteor update`? Seems coherent to you?
Thanks again for taking time for me.
