### ISSUE TITLE
Fatal error when publishing package that uses Npm.depends

### ISSUE THREAD

**Issue by copleykj** [meteor/meteor#8475]
Trying to publish my base-model package which depends on a package from npm. When I run `meteor publish` it dies with the following error:

```sh
updating npm dependencies -- mongodb-diff...
/home/copleykj/.meteor/packages/ecmascript/.0.6.3.1ax5r61++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENOENT: no such file or directory, lstat '/home/copleykj/projects/JavaScript/socialize/socialize-base-model/.npm/package'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at Object.realpathSync (fs.js:1439:21)
    at Object.wrapper [as realpath] (/tools/fs/files.js:1535:35)
    at Builder.copyDirectory (/tools/isobuild/builder.js:594:16)
    at /tools/isobuild/isopack.js:1446:17
    at Function._.each._.forEach (/home/copleykj/.meteor/packages/meteor-tool/.1.4.3_1.91supr++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/isopack.js:1445:9
    at [object Object].saveToPath (/tools/isobuild/isopack.js:1191:9)
    at bundleBuild (/tools/packaging/package-client.js:361:11)
    at /tools/packaging/package-client.js:401:20
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at createBuiltPackage (/tools/packaging/package-client.js:400:16)
    at Object.exports.publishPackage (/tools/packaging/package-client.js:823:26)
    at /tools/cli/commands-packages.js:441:21
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:271:29)
    at Command.func (/tools/cli/commands-packages.js:437:8)
    at /tools/cli/main.js:1483:23

```

he files in the .npm directory are being wiped out by the publish command. If I restore them via git checkout and run it again, it erases them again without updating them.. If I symlink a the package from the packages folder of a meteor project that uses the package and then meteor run the project, the files in .npm are updated correctly and the project runs. Trying to publish after this still yields the same error though.

I'd really like to issue an update for this package so hopefully someone can shed some light on this.

**Comment by abernix** [comment]
* When was the last publish which worked and what version of Meteor did you use to do that?
* What version of Meteor are you using to `meteor publish` with?  (i.e. what is the output of `meteor --version` in that package before you run `meteor publish`?).
* Have you tried publishing with another version of Meteor to see if that works? (i.e. `meteor --release 1.4.2.3 publish`)
* Is it [this repository's `devel` branch](https://github.com/copleykj/socialize-base-model/tree/devel) which you're publishing from?

Having more details included when filing an issue is super helpful when determining the source and resolution to issues like this!

**Comment by copleykj** [comment]
Last publish was Sept 12 with 1.4.1.1

The initial try to publish the current changes was with 1.4.2.7. I then tried with multiple previous versions using `--release` back to the 1.3 release track.

Yes the devel branch of that repo is the code in question.

**Comment by abernix** [comment]
Ah, I see the problem.  You should move [your `Npm.depends`](https://github.com/copleykj/socialize-base-model/blob/devel/package.js#L9-L11) up to the top-level (as opposed to nested with `Package.onUse`) and it will work.

See [this comment](https://github.com/meteor/meteor/issues/8200#issuecomment-270723863) in #8200 for an explanation!

**Comment by copleykj** [comment]
<img src="https://media.giphy.com/media/rTgtVnbqiwt5S/giphy.gif" />
