### ISSUE TITLE
While running Cordova app for platform Android with options --device:

### ISSUE THREAD

**Issue by chenmoran** [meteor/meteor#8476]
meteor 1.4.3.1

Tools:
Android SDK Tools:25.2.5
Android SDK Platform-tools:25.0.3
Android SDK Build-tools:25.0.2

Android 7.1.1(API25)
SDK Platform:25.3
Sources for Android SDK:25.1

```
macbook:newapp` apple$ meteor run android-device
[[[[[ ~/Desktop/new/newapp ]]]]]    
=> Started proxy.                             
                                              
WARNING: You are testing your app on a remote device. For the mobile app to be
         able to connect to the local server, make sure your device is on the
         same network, and that the network configuration allows clients to
         talk to each other (no client isolation).
=> Started MongoDB.                           
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed:                     
   /Users/apple/Desktop/new/newapp/.meteor/local/cordova-build/platforms/android/cordova/run
   --device
   Exception in thread "main" java.lang.RuntimeException:
   java.net.SocketException: Connection reset
   at
   org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
   at org.gradle.wrapper.Install.createDist(Install.java:47)
   at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
   at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
   Caused by: java.net.SocketException: Connection reset
   at java.net.SocketInputStream.read(SocketInputStream.java:210)
   at java.net.SocketInputStream.read(SocketInputStream.java:141)
   at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
   at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
   at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
   at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
   at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
   at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:675)
   at
   sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
   at
   sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
   at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
   at org.gradle.wrapper.Download.download(Download.java:45)
   at org.gradle.wrapper.Install$1.call(Install.java:60)
   at org.gradle.wrapper.Install$1.call(Install.java:47)
   at
   org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
   ... 3 more
   { [Error:
   /Users/apple/Desktop/new/newapp/.meteor/local/cordova-build/platforms/android/gradlew:
   Command failed with exit code 1 Error output:
   Exception in thread "main" java.lang.RuntimeException:
   java.net.SocketException: Connection reset
   at
   org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
   at org.gradle.wrapper.Install.createDist(Install.java:47)
   at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
   at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
   Caused by: java.net.SocketException: Connection reset
   at java.net.SocketInputStream.read(SocketInputStream.java:210)
   at java.net.SocketInputStream.read(SocketInputStream.java:141)
   at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
   at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
   at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
   at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
   at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
   at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:675)
   at
   sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
   at
   sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
   at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
   at org.gradle.wrapper.Download.download(Download.java:45)
   at org.gradle.wrapper.Install$1.call(Install.java:60)
   at org.gradle.wrapper.Install$1.call(Install.java:47)
   at
   org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
   ... 3 more] code: 1 } 'Error:
   /Users/apple/Desktop/new/newapp/.meteor/local/cordova-build/platforms/android/gradlew:
   Command failed with exit code 1 Error output:\nException in thread "main"
   java.lang.RuntimeException: java.net.SocketException: Connection reset\n\tat
   org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)\n\tat
   org.gradle.wrapper.Install.createDist(Install.java:47)\n\tat
   org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)\n\tat
   org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)\nCaused
   by: java.net.SocketException: Connection reset\n\tat
   java.net.SocketInputStream.read(SocketInputStream.java:210)\n\tat
   java.net.SocketInputStream.read(SocketInputStream.java:141)\n\tat
   java.io.BufferedInputStream.fill(BufferedInputStream.java:246)\n\tat
   java.io.BufferedInputStream.read1(BufferedInputStream.java:286)\n\tat
   java.io.BufferedInputStream.read(BufferedInputStream.java:345)\n\tat
   sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)\n\tat
   sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)\n\tat
   sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:675)\n\tat
   sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)\n\tat
   sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)\n\tat
   org.gradle.wrapper.Download.downloadInternal(Download.java:59)\n\tat
   org.gradle.wrapper.Download.download(Download.java:45)\n\tat
   org.gradle.wrapper.Install$1.call(Install.java:60)\n\tat
   org.gradle.wrapper.Install$1.call(Install.java:47)\n\tat
   org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)\n\t...
   3 more\n    at ChildProcess.whenDone
   (/Users/apple/Desktop/new/newapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)\n
   at emitTwo (events.js:87:13)\n    at ChildProcess.emit
   (events.js:172:7)\n    at maybeClose (internal/child_process.js:854:16)\n
   at Socket.<anonymous> (internal/child_process.js:330:11)\n    at emitOne
   (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at
   Pipe._onclose (net.js:487:12)'
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   => awaited here:
   at Function.Promise.await
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.run$ (/tools/cordova/project.js:261:10)
   at tryCatch
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at tryCatch
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at invoke
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:139:20)
   at
   /Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:184:11
   at callInvokeWithMethodAndArg
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:183:16)
   at AsyncIterator.enqueue
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:206:13)
   at AsyncIterator.prototype.(anonymous function) [as next]
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at Object.runtime.async
   (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:226:14)
   at
   /Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
                                              
/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
    at Function.Promise.await (/Users/apple/.meteor/packages/meteor-tool/.1.4.3_1.1vq35o4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at /tools/cordova/runner.js:98:17
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at CordovaRunner.startRunTargets (/tools/cordova/runner.js:97:37)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:763:21)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
macbook:newapp apple$ 
```

**Comment by abernix** [comment]
First, do not use Android SDK 25.3.x – see https://github.com/meteor/meteor/issues/8464 for more information.

### Questions

What version of Java do you have installed?

    java -version

Have you tried removing and re-adding the `android` platform?  Just run:

    meteor remove-platform android

Then

    meteor add-platform android

Do you see your device when you run:

    adb devices

?

**Comment by hwillson** [comment]
Hi @chenmoran - we haven't heard back from you in a couple of weeks, so I'll close this issue for now. Happy to re-open if you're able to answer the questions outlined in https://github.com/meteor/meteor/issues/8476#issuecomment-288075989. Thanks!

**Comment by akatrodiya** [comment]
no thanx

**Comment by markoshust** [comment]
To anyone who finds this, if you are testing on an actual android device, make sure you install the related sdk tools for your device (if it's marshmallow, that means installing 23.x).
