### ISSUE TITLE
reify/lib/compiler.js:549:24: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by VenelinPetkov** [meteor/meteor#8497]
After upgrade to Meteor 1.4.3.2, I am facing the follow issue:

`
   While processing files with ecmascript (for target os.linux.x86_64):
  /home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/reify/lib/compiler.js:549:24: Cannot read property 'name'
   of undefined
   at /home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/reify/lib/compiler.js:549:24
   at Array.forEach (native)
   at computeSpecifierMap (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/reify/lib/compiler.js:548:14)
   at Context.types.PathVisitor.fromMethodsObject.visitExportNamedDeclaration
   (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/reify/lib/compiler.js:462:26)
   at Context.invokeVisitorMethod
   (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:344:49)
   at Visitor.PVp.visitWithoutReset
   (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:196:32)
   at NodePath.each (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path.js:101:26)
   at visitChildren (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:219:18)
   at Visitor.PVp.visitWithoutReset
   (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:204:20)
   at visitChildren (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:246:25)
   at Visitor.PVp.visitWithoutReset
   (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:204:20)
   at visitChildren (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:246:25)
   at Visitor.PVp.visitWithoutReset
   (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:204:20)
   at Visitor.PVp.visit
   (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/ast-types/lib/path-visitor.js:133:29)
   at Object.compile (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/reify/lib/compiler.js:31:23)
   at compile (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:52:35)
   at Cache.Cp.get (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:94:19)
   at Object.compile (/home/sample/.meteor/packages/ecmascript/.0.6.3.xc1eas++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:48:23)
   at Object.Babel.compile (packages/babel-compiler.js:48:24)
   at packages/babel-compiler.js:162:22
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/babel-compiler.js:192:20)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:161:20)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:93:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:92:14)
`

**Comment by dmolin** [comment]
+1

**Comment by abernix** [comment]
Could you try and see if the latest Meteor 1.4.3.3 beta resolves this problem for you?  You can upgrade by running:

    meteor update --release 1.4.3.3-beta.4

**Comment by dmolin** [comment]
That seems to work!
I was having the reify compiler issue even on the 1.4.2.7 patch version (hence I was still working on 1.4.2.3). The 1.4.3.3-beta.4 seems to do the trick :+1: 

Thanks!

**Comment by rcsandell** [comment]
Howsit, same problem seems to have resurfaced:
[build_error.txt](https://github.com/meteor/meteor/files/2519894/build_error.txt)

Similar error reported here 17 days ago:
#https://github.com/zodern/meteor-up/issues/1020
