### ISSUE TITLE
Error: must use ordered observe (ie, 'addedBefore' instead of 'added') with skip or limit

### ISSUE THREAD

**Issue by MMrj9** [meteor/meteor#8501]
I added a limit to my publication query and I started getting the following error: 

> Exception from sub Products id Xbd4EW32oob8fBPkk Error: must use ordered observe (ie, 'addedBefore' instead of 'added') with skip or limit

The publication: 
```

Meteor.publish('Products', function(user, options) {
            if (organization && organization.categories) {
                //find products in array of categories
                let products = Products.find({
                                categories: {
                                    '$elemMatch': {
                                        '$in': organization.categories
                                    }
                                }                    
                            },
                            {limit: 10}
                            );
                return products;
            } else {
                return [];
            }
        });
```

I'm not using observe() or observeChanges() anywhere on my code.
Meteor 1.4.3.2

Error Trace
```
I20170320-16:29:58.231(0)? Exception from sub Products id vDz4GLRXJ6s3cENeE Error: must use ordered observe (ie, 'addedBefore' instead of 'added') with skip or limit
I20170320-16:29:58.233(0)?     at [object Object]._.extend.observeChanges (packages/minimongo/minimongo.js:325:13)
I20170320-16:29:58.234(0)?     at [object Object].<anonymous> (packages/omknee:sales-process/sales-process.js:38:31)
I20170320-16:29:58.235(0)?     at [object Object]._handler (packages/omknee:access-control/access-control.js:38:31)
I20170320-16:29:58.236(0)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170320-16:29:58.236(0)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
I20170320-16:29:58.237(0)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
I20170320-16:29:58.238(0)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
I20170320-16:29:58.239(0)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by abernix** [comment]
The error message is pretty clear as to what the problem is, and the stack trace shows fairly clearly that there is an `observeChanges` in the `omknee:sales-process` package:

```
at [object Object]._.extend.observeChanges (packages/minimongo/minimongo.js:325:13)
at [object Object].<anonymous> (packages/omknee:sales-process/sales-process.js:38:31)
```

I'd suggest you investigate a bit more or ask for help on the Meteor Forums/StackOverflow.  Regardless, this is not the place for filing issues without reproductions.
