### ISSUE TITLE
Bug: Already registered the Google OAuth service

### ISSUE THREAD

**Issue by merlinpatt** [meteor/meteor#8509]
Version: 1.4.3.2, 1.4.3.1
Version Before Upgrade: 1.4.2.3
Platform: Ubuntu 14.04.3 LTS

I just tried to upgrade from 1.4.2.3 to 1.4.3.2 and am getting this error.

Attempted fixes
* `meteor reset`, but I get the same error.
* Downgrading to 1.4.3.1, but I get the same error.
* Commenting out the `ServiceConfiguration.insert` call, but if I'm reading the documentation correctly, this is irrelevant.

I can keep downgrading if need be to see if that fixes it, but I don't think it will. I looked at the history of the file throwing the error, and the line has been there since well before this year, so I'm not sure why I'm getting it now.

1. Any thoughts?
2. Why does this throw an error instead of a warning?

Below is the stack trace I'm getting, which points me to [this line](https://github.com/meteor/meteor/blob/devel/packages/oauth/oauth_server.js#L33)

```
Error: Already registered the google OAuth service
     at Object.OAuth.registerService (packages/oauth.js:65:11)
     at packages/google.js:32:7
     at packages/google.js:127:4
     at packages/google.js:139:3
     at /home/vagrant/classtracks/app/.meteor/local/build/programs/server/boot.js:303:34
     at Array.forEach (native)
     at Function._.each._.forEach (/home/vagrant/.meteor/packages/meteor-tool/.1.4.3_2.vz7x6n++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
     at /home/vagrant/classtracks/app/.meteor/local/build/programs/server/boot.js:128:5
     at /home/vagrant/classtracks/app/.meteor/local/build/programs/server/boot.js:352:5
     at Function.run (/home/vagrant/classtracks/app/.meteor/local/build/programs/server/profile.js:510:12)
```

**Comment by merlinpatt** [comment]
I found a fix on the percolate repo [here](https://github.com/percolatestudio/meteor-google-api/issues/40#issuecomment-280662638).

I'll close this since it has a workaround
