### ISSUE TITLE
Using rate-limit inside another package fails while minifying app code on 1.4.3.2

### ISSUE THREAD

**Issue by engelgabriel** [meteor/meteor#8515]
We use `rate-limit` inside another package, and since Meteor 1.4.3.2 and `rate-limit` version 1.0.7, some platforms fail to build while minifying app code with the following error:

```
While minifying app code:
packages/minifyStdJS_plugin.js:113:28: UglifyJS minification error: 
SyntaxError: Unexpected token punc «(», expected punc «:» at
packages/rate-limit/rate-limit.js line 105
within packages/rate-limit.js (line: 135, col: 18, pos: 10314):
_executeCallback(reply, ruleInput) {
at maybeThrowMinifyErrorBySourceFile (packages/minifyStdJS_plugin.js:113:28)
at packages/minifyStdJS_plugin.js:145:9
at Array.forEach (native)
at UglifyJSMinifier.processFilesForBundle
(packages/minifyStdJS_plugin.js:130:9)
```

I believe the cause is the missing dependency on `ecmascript` since the syntax on line 105 may need babel parsing it?

https://github.com/meteor/meteor/blob/devel/packages/rate-limit/rate-limit.js#L105

**Comment by engelgabriel** [comment]
This is blocking https://github.com/RocketChat/Rocket.Chat/pull/6455
