### ISSUE TITLE
compile-ecmascript: Cannot find module './entry.js' in 1.4.3.2

### ISSUE THREAD

**Issue by theWeird** [meteor/meteor#8550]
I just cloned one of my projects to a dev server and ran into this error when trying to run it.  
That project uses Meteor 1.4.3.1

To ensure it is not a self-made problem on project level, I used `meteor create test` to create a clean and fresh project using Meteor 1.4.3.2. In this project, the same error occours (see console output below).

OS on dev server: Debian 8.4

```
myuser:~/projekte/test$ meteor --version
Meteor 1.4.3.2
myuser:~/projekte/test$ meteor
[[[[[ ~/projekte/test ]]]]]

=> Started proxy.
For compatibility, the PACKAGE_DIRS environment variable is deprecated and will be removed in a future Meteor release.
Developers should now use METEOR_PACKAGE_DIRS and Windows projects should now use a semi-colon (;) to separate paths.
=> Started MongoDB.
=> Errors prevented startup:

   While loading plugin `compile-ecmascript` from package `ecmascript`:
   packages/modules-runtime.js:123:19: Cannot find module './entry.js'
   at require (packages/modules-runtime.js:123:19)
   at meteorInstall.node_modules.meteor.modules.node_modules.reify.lib.runtime.js (packages/modules.js:138:13)
   at fileEvaluate (packages/modules-runtime.js:197:9)
   at require (packages/modules-runtime.js:120:16)
   at meteorInstall.node_modules.meteor.modules.server.js (packages/modules.js:24:1)
   at fileEvaluate (packages/modules-runtime.js:197:9)
   at require (packages/modules-runtime.js:120:16)
   at packages/modules.js:274:15
   at packages/modules.js:287:3


=> Your application has errors. Waiting for file change.
^C
myuser:~/projekte/test$ cat package.json
{
  "name": "test",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "babel-runtime": "^6.20.0",
    "meteor-node-stubs": "~0.2.4"
  }
}
myuser:~/projekte/test$ cat .meteor/packages
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.16                   # The database Meteor supports right now
blaze-html-templates@1.0.4 # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.2                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.4   # CSS minifier run for production mode
standard-minifier-js@1.2.3    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.6.3              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.3            # Server-side component of the `meteor shell` command

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)
myuser:~/projekte/test$ meteor npm -v
4.3.0
```

**Comment by abernix** [comment]
Does the error go away if you run:

    unset PACKAGE_DIRS

And then try starting either project again?

If that works, then what do you have in your `$PACKAGE_DIRS` directory? (`ls -lad $(echo $PACKAGE_DIRS)`).

**Comment by theWeird** [comment]
No, made no difference.  
There are only some self-made packages not used by meteors default project setup.

**Comment by abernix** [comment]
Ok.  A [reproduction]((https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor)) would be helpful because I cannot reproduce your problem with the information you've provided above – I tried and it works just fine for me.

Do you have a `.babelrc` or anything else floating around in your `test` directory?  Did you run `meteor npm install`?

**Comment by theWeird** [comment]
No. The test directory is as-provided by `meteor create test`
I removed the test project and repeated `meteor create test` and `meteor npm i` (inside project folder) with the same result.  
The project created by the command is attached.
[testproject.tar.gz](https://github.com/meteor/meteor/files/885423/testproject.tar.gz)

```
user:~/projekte$ rm -r test
user:~/projekte$ meteor create test
Created a new Meteor app in 'test'.

To run your new app:
  cd test
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

meteor create --bare to create an empty app.
meteor create --full to create a scaffolded app.

user:~/projekte$ cd test
user:~/projekte/test$ meteor npm i
user:~/projekte/test$ meteor
[[[[[ ~/projekte/test ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading plugin `compile-ecmascript` from package `ecmascript`:
   packages/modules-runtime.js:123:19: Cannot find module './entry.js'
   at require (packages/modules-runtime.js:123:19)
   at meteorInstall.node_modules.meteor.modules.node_modules.reify.lib.runtime.js (packages/modules.js:138:13)
   at fileEvaluate (packages/modules-runtime.js:197:9)
   at require (packages/modules-runtime.js:120:16)
   at meteorInstall.node_modules.meteor.modules.server.js (packages/modules.js:24:1)
   at fileEvaluate (packages/modules-runtime.js:197:9)
   at require (packages/modules-runtime.js:120:16)
   at packages/modules.js:274:15
   at packages/modules.js:287:3


=> Your application has errors. Waiting for file change.
^C
```

**Comment by abernix** [comment]
I extracted that tarball and ran it on my Mac with zero problems (literally, `tar xzf testproject.tar.gz && cd test && meteor`).

I don't have Debian specifically installed at the moment, but it ran fine on my Ubuntu 14.04 Server too, and 14.04 is based on Debian Jessie (v8.x):

    $ cat /etc/debian_version
    jessie/sid

Can you reinstall Meteor and see if that fixes it?

    curl https://install.meteor.com/ | sh

**Comment by theWeird** [comment]
Yeah!  
Didn't know that the installer can also be used to reinstall meteor tool.  
Seems this problem comes from old stuff in the meteor distribution, error during a previous tool upgrade or something else like that.

After reinstalling the meteor distribution it works great.  
Thank you

**Comment by abernix** [comment]
Still a bit bizarre, but glad it's working for you again!
