### ISSUE TITLE
1.4.4-rc.4 fails on Windows: no directory ...\dev_bundle\server-lib

### ISSUE THREAD

**Issue by edemaine** [meteor/meteor#8558]
I've tried this both upgrading an existing Meteor project and starting a fresh new project:

```
C:\...>meteor create test --release 1.4.4-rc.4
Created a new Meteor app in 'test'.

To run your new app:
  cd test
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

meteor create --bare to create an empty app.
meteor create --full to create a scaffolded app.

C:\...>cd test

C:\...\test>meteor
[[[[[ C:\...\test ]]]]]

=> Started proxy.
=> Started MongoDB.
C:\Users\edemaine\AppData\Local\.meteor\packages\templating-compiler\1.3.2\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: ENOENT: no such file or directory, stat 'C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.wrapper (C:\tools\fs\files.js:1556:35)
    at Object.files.(anonymous function) [as stat] (C:\tools\fs\files.js:1658:27)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:732:17)
    at Builder.write (C:\tools\isobuild\builder.js:266:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2265:15)
    at C:\tools\isobuild\bundler.js:2373:30
    at C:\tools\isobuild\bundler.js:2506:9
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2496:26
    at C:\tools\isobuild\bundler.js:2837:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2670:31)
    at C:\tools\isobuild\bundler.js:2617:32
    at Object.withCache (C:\tools\fs\files.js:1623:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2617:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12
```

I confirm that the directory `C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.4\mt-os.windows.x86_32\dev_bundle\server-lib` does not exist (but its parent does).  Not sure what's wrong though.  `meteor npm install` doesn't help.

**Comment by abernix** [comment]
I believe this is fixed with https://github.com/meteor/meteor/commit/3257bafc84de9624d69cff50c93aec23b7cbc5c9 which is in `1.4.4-rc.5` if you don't mind giving it a try.

Although, I suspect you may then run into another problem (another FS issue) as I'm fairly sure I reproduced a separate issue related to https://github.com/meteor/meteor/pull/8491 on Friday.

**Comment by edemaine** [comment]
Confirmed on both counts.

**Comment by abernix** [comment]
What was the follow-up error you received, out of curiosity?  `EDIRNOTEMPTY`, by chance?

**Comment by edemaine** [comment]
Ah, no `EPERM`.  Symlinks are only allowed as superuser on Windows.  I'm hoping a superuser shell won't be necessary in future Meteor versions; it's been that way so far.

```
Error: EPERM: operation not permitted, symlink 'C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\' -> 'C:\Users\edemaine\Projects\test\.meteor\local\.build34106.build\programs\server\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at copySync (C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fs-extra\lib\copy-sync\copy-sync.js:58:8)
    at C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fs-extra\lib\copy-sync\copy-sync.js:54:7
    at Array.forEach (native)
    at copySync (C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fs-extra\lib\copy-sync\copy-sync.js:51:14)
    at tryCopySync (C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fs-extra\lib\move-sync\index.js:97:5)
    at moveDirSyncAcrossDevice (C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fs-extra\lib\move-sync\index.js:93:5)
    at moveSyncAcrossDevice (C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fs-extra\lib\move-sync\index.js:55:12)
    at tryRenameSync (C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fs-extra\lib\move-sync\index.js:43:18)
    at Object.moveSync (C:\Users\edemaine\AppData\Local\.meteor\packages\meteor-tool\1.4.4-rc.5\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fs-extra\lib\move-sync\index.js:21:3)
    at Object.wrapper [as move] (C:\tools\fs\files.js:1556:35)
    at Object.files.renameDirAlmostAtomically (C:\tools\fs\files.js:995:9)
    at Builder.complete (C:\tools\isobuild\builder.js:690:13)
    at C:\tools\isobuild\bundler.js:2380:13
    at C:\tools\isobuild\bundler.js:2506:9
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2496:26
    at C:\tools\isobuild\bundler.js:2837:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2670:31)
    at C:\tools\isobuild\bundler.js:2617:32
    at Object.withCache (C:\tools\fs\files.js:1623:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2617:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12
```
