### ISSUE TITLE
SyntaxError: Unexpected token } after meteor update

### ISSUE THREAD

**Issue by AdrianKrebs** [meteor/meteor#8575]
After I did a meteor update I get the following weird error:

```
=> Started proxy.
=> Started MongoDB.
C:\Users\Adrian\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:280
                                                throw(ex);
                                                ^

SyntaxError: Unexpected token }
    at Object.parse (native)
    at Object.defaultExtensionHandlers..json (C:\tools\isobuild\import-scanner.js:56:27)
    at ImportScanner._readModule (C:\tools\isobuild\import-scanner.js:656:23)
    at C:\tools\isobuild\import-scanner.js:563:22
    at _.each._.forEach (C:\Users\Adrian\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:503:5)
    at C:\tools\isobuild\import-scanner.js:547:18
    at _.each._.forEach (C:\Users\Adrian\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:503:5)
    at C:\tools\isobuild\import-scanner.js:547:18
    at _.each._.forEach (C:\Users\Adrian\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:503:5)
    at C:\tools\isobuild\import-scanner.js:547:18
    at _.each._.forEach (C:\Users\Adrian\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:503:5)
    at C:\tools\isobuild\import-scanner.js:349:14
    at Array.forEach (native)
    at ImportScanner.scanImports (C:\tools\isobuild\import-scanner.js:347:22)
    at C:\tools\isobuild\compiler-plugin.js:1041:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:1009:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:1057:8)
    at C:\tools\isobuild\bundler.js:828:12
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:819:18)
    at C:\tools\isobuild\bundler.js:2689:14
    at C:\tools\isobuild\bundler.js:2778:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Adrian\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2777:7
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2670:31)
    at C:\tools\isobuild\bundler.js:2617:32
    at Object.withCache (C:\tools\fs\files.js:1601:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2617:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12
```
It seems like it has to do with `underscore each`. When I open underscore.js:79:11 I see:

```
  // Collection Functions
  // --------------------

  // The cornerstone, an `each` implementation, aka `forEach`.
  // Handles objects with the built-in `forEach`, arrays, and raw objects.
  // Delegates to **ECMAScript 5**'s native `forEach` if available.
  var each = _.each = _.forEach = function(obj, iterator, context) {
    if (obj == null) return;
    if (nativeForEach && obj.forEach === nativeForEach) {
      obj.forEach(iterator, context);
    } else if (obj.length === +obj.length) {
      for (var i = 0, length = obj.length; i < length; i++) {
        if (iterator.call(context, obj[i], i, obj) === breaker) return;
      }
    } else {
      var keys = _.keys(obj);
      for (var i = 0, length = keys.length; i < length; i++) {
        if (iterator.call(context, obj[keys[i]], keys[i], obj) === breaker) return; // line 79
      }
    }
  };
```

Any idea? I reinstalled meteor and did a `meteor reset` to resolve possible caching issues. But I have no clue what else I could try.

**Comment by hwillson** [comment]
Hi @AdrianKrebs - could you try updating to 1.4.4.1 and let us know if you're still having issues?

```
meteor update --release 1.4.4.1
```

Thanks!

**Comment by AdrianKrebs** [comment]
Hi @hwillson - Thanks for your tip. I've already tried that. The error keeps occurring with 1.4.4.1. Then I downgraded but it still appears. Any other idea?

**Comment by abernix** [comment]
@AdrianKrebs It would seem that you have a `.json` file somewhere in your project which is malformed and doesn't parse correctly.  I'd suggest a command to quickly check your project directory, but I'm not familiar with the best recommendation for such a command on Windows.

**Comment by AdrianKrebs** [comment]
@abernix you were right, thank you! There was a malformed json file in my project...

**Comment by rkstar** [comment]
for anyone else finding this... i had a similar problem and it was a malformed `.json` file in my `/imports` directory
