### ISSUE TITLE
Error: No metadata files found for isopack

### ISSUE THREAD

**Issue by knuVe** [meteor/meteor#8587]
I have reinstalled Meteor and then this happens...

It puts out following Errors:

C:\Users\Timm\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/Timm/AppData/Local/.meteor/packages/meteor-tool/1.3.1
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:521:21
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Timm\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:520:13
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:600:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:597:20)
    at C:\tools\cli\main.js:462:30
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at C:\tools\cli\main.js:461:17
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at C:\tools\cli\main.js:459:33
    at [object Object]._.extend.withProgressDisplayVisible (C:\tools\console\console.js:639:14)
    at springboard (C:\tools\cli\main.js:458:11)
    at C:\tools\cli\main.js:1126:5

**Comment by hwillson** [comment]
Hi @knuVe - is there anything in your `C:\Users\Timm\AppData\Local\.meteor\packages\meteor-tool\1.3.1` directory? Maybe try removing that `1.3.1` directory, and running meteor again.

**Comment by rwdietrich** [comment]
@knuVe I had a similar issue (1.4.3_2). I deleted the offending meteor-tool directory and reran meteor. This problem was fixed.

**Comment by hwillson** [comment]
Since we haven't heard back on this in a few weeks, I'll close it for now. Happy to re-open if you're still having this problem, and you can answer https://github.com/meteor/meteor/issues/8587#issuecomment-293607466. Thanks!

**Comment by hounaine** [comment]
+1 same issue here >> l tried : removing and re-installing meteor
the app is to be build for the 1st time
l have another meteor app that runs perfectly

**Comment by hounaine** [comment]
@rwdietrich: l may have understood wrongly "l deleted the offending meteor-tool directory"...
of course meteor could'nt run then uninstalled meteor, re-install it, but !!! no meteor-tool folder. Now meteor does work at wall (lost all paths)
what to do to recover ? Thanks.

**Comment by hounaine** [comment]
>> @rwdietrich: solved, just created an empty folder before uninstall reinstall...

**Comment by hounaine** [comment]
last try >>
C:\Users\Pc_user\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os.window
s.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-prom
ise\promise_server.js:190
      throw error;
      ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Pc_user\AppData\Local\Tem
p\.tmp1fdub8w\ostrio_cookies-2.2.0'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\Pc_user\node_modules\rimraf\rimraf.js:342:11)
    at rmdirSync (C:\Users\Pc_user\node_modules\rimraf\rimraf.js:332:7)
    at Function.rimrafSync [as sync] (C:\Users\Pc_user\node_modules\rimraf\rimra
f.js:303:9)
    at Object.rm_recursive (C:\tools\fs\files.js:303:12)
    at Object.files.rename (C:\tools\fs\files.js:1735:13)
    at Object.files.extractTarGz (C:\tools\fs\files.js:767:9)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)

    at C:\tools\packaging\tropohouse.js:505:42
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:502:24
    at Function._.each._.forEach (C:\Users\Pc_user\node_modules\underscore\under
score.js:103:9)
    at C:\tools\packaging\tropohouse.js:469:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\Pc_user\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\mete
or-promise\fiber_pool.js:32:39
 => awaited here:
    at Promise.await (C:\Users\Pc_user\AppData\Local\.meteor\packages\meteor-too
l\1.4.4_2\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\no
de_modules\meteor-promise\promise_server.js:39:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:604:6)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packagi
ng\tropohouse.js:609:18)
    at C:\tools\project-context.js:808:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:807:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalo
g\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:806:
13)
    at C:\tools\project-context.js:283:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.
js:273:18)
    at C:\tools\project-context.js:265:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.
js:264:13)
    at C:\tools\cli\commands-packages.js:1528:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1527:8)
    at Command.func (C:\tools\cli\commands-packages.js:1601:29)
    at C:\tools\cli\main.js:1483:23
