### ISSUE TITLE
Unexpected token when upgrading to meteor 1.4.4_1

### ISSUE THREAD

**Issue by Mklueh** [meteor/meteor#8589]
I´m getting this error when trying to update Meteor

```
.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

SyntaxError: Unexpected token
```

Running "meteor list" now prints the same, but under current version "1.4.3_2"
```

.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

SyntaxError: Unexpected token
```

How can I solve this issue?

PS: I´ve added the .meteor package to Git, but there was a sneaky .gitignore inside of it which excluded the /local dir. Reverting is no option :P

**Comment by hwillson** [comment]
Hi @Mklueh - any chance you could put together a small, runnable reproduction that demonstrates this issue? (see [Reporting a bug in Meteor](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug))

**Comment by benjamn** [comment]
By the way, the `.meteor/local` directory should never be committed to version control, as it gets (mostly) regenerated with every build. That `.gitignore` file is doing the right thing!

**Comment by Mklueh** [comment]
@benjamn 

It was recommended in the latest blog entry by @abernix 

https://blog.meteor.com/announcing-meteor-1-4-4-11027f33e3bf

> As a reminder, make sure your application’s .meteor directory is committed to your version-control system (e.g. Git, Subversion, etc.) so it’s easy to roll-back if you ever encounter problems during any upgrade.

**Comment by benjamn** [comment]
Note that he recommended versioning `.meteor`, not necessarily `.meteor/local`. The `.meteor/.gitignore` file is there for a reason!

**Comment by Mklueh** [comment]
@hwillson I´ve send you a message on Gitter

@benjamn ok then everything is like it should be

**Comment by Mklueh** [comment]
I did a "meteor reset", which made project at least working again.

Then I tried to do the update again and got a bigger error log then before

```
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\MyPC\AppData\Local\Temp\.tmphh0kj2\blaze-html-templates-1.1.2'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\MyPC\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:332:11)
    at rmdirSync (C:\Users\MyPC\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync [as sync] (C:\Users\MyPC\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at Object.rm_recursive (C:\tools\fs\files.js:303:12)
    at Object.files.rename (C:\tools\fs\files.js:1735:13)
    at Object.files.extractTarGz (C:\tools\fs\files.js:767:9)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)
    at C:\tools\packaging\tropohouse.js:505:42
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:502:24
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\MyPC\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:469:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\MyPC\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\fiber_pool.js:32:39
 => awaited here:
    at Promise.await (C:\Users\MyPC\AppData\Local\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.
js:39:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:604:6)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:609:18)
    at C:\tools\project-context.js:808:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:807:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:806:13)
    at C:\tools\project-context.js:283:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:273:18)
    at C:\tools\project-context.js:265:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.js:264:13)
    at C:\tools\cli\commands-packages.js:1528:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1527:8)
    at Command.func (C:\tools\cli\commands-packages.js:1601:29)
    at C:\tools\cli\main.js:1483:23
```

**Comment by Mklueh** [comment]
Ok working now.

To sum up what I did

1. meteor reset
2. Delete content of C:\Users\MyPC\AppData\Local\Temp
3. meteor update
