### ISSUE TITLE
Google OAuth not working on Android with latest code

### ISSUE THREAD

**Issue by OleksandrChekhovskyi** [meteor/meteor#8613]
Related to https://github.com/meteor/meteor/commit/7a9dd2b7a457cf54c5e11d1aed1102182c0688fe, summoning @benjamn

`request.accessToken` is available on iOS, but not on Android, compare:
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/de47036d848d1285994fc5a948636ded2cff7117/src/ios/GooglePlus.m#L198
vs.
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/de47036d848d1285994fc5a948636ded2cff7117/src/android/GooglePlus.java#L324

Crashes with this callstack:
```
Exception while invoking method 'login' Error: Failed to fetch tokeninfo from Google. failed [400] {  "error": "invalid_token",  "error_description": "Invalid Value" } 
    at getScopes (packages/google-oauth/google_server.js:142:7)
    at getServiceDataFromTokens (packages/google-oauth/google_server.js:12:16)
    at [object Object].<anonymous> (packages/google-oauth/google_server.js:58:36)
    at packages/accounts-base/accounts_server.js:471:32
    at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)
    at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:468:18)
    at [object Object].methods.login (packages/accounts-base/accounts_server.js:531:27)
    at [object Object].wrappedMethod (lib/common/wrapmethods.ts:41:19)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
```

Also call to `Accounts.updateOrCreateUserFromExternalService` should pass `options` containing `{ profile: {name: "..."} }`. Right now it will attempt to create user document with non-existent profile for new users.

**Comment by chrisknu** [comment]
Same error here: snippet of error from galaxy logs...
`Exception while invoking method 'login' Error: Failed to fetch tokeninfo from Google. failed [400] { "error": "invalid_token", "error_description": "Invalid Value" }
6hhc
2017-04-19 22:07:00-04:00 at getScopes (packages/google-oauth/google_server.js:136:7)
6hhc
2017-04-19 22:07:00-04:00 at getServiceDataFromTokens (packages/google-oauth/google_server.js:12:16)...`

**Comment by abernix** [comment]
Hopefully this is fixed with `google-oauth@1.2.4` (just published!).  Please report back on your findings!

**Comment by OleksandrChekhovskyi** [comment]
Seems to work now. Thanks!

**Comment by chrisknu** [comment]
That worked, thanks
