### ISSUE TITLE
Meteor EPERM garbage crash while rebuilding local package

### ISSUE THREAD

**Issue by nathantreid** [meteor/meteor#8628]
Meteor: 1.4.4.1
OS: Windows 10
Package I'm working on: akryum:vue-sass

I'm working on a patch for aykrum's vue-sass package (https://github.com/Akryum/vue-meteor/tree/master/packages/vue-sass) and whenever I make a change to the package, the following error occurs:
```
H:\.meteor\packages\promise\0.8.8\npm\node_modules\meteor-promise\promise_server.js:190
      throw error;
      ^

Error: EPERM: operation not permitted, unlink 'C:\projects\go2\swmid-228671-mp\site\.meteor\local\isopacks\akryum_vue-sass-garbage-tity77\plugin.vue-component-sass.os\npm\node_modules\meteor\vue-component-sass\node_modules\node-sass\vendor\win32-ia32-46\binding.node'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:204:13)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at rimrafSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at fixWinEPERMSync (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:202:5)
    at Function.rimrafSync [as sync] (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:300:28)
    at Object.rm_recursive (H:\tools\fs\files.js:303:12)
    at Object.renameDirAlmostAtomically (H:\tools\fs\files.js:1041:13)
    at Builder.complete (H:\tools\isobuild\builder.js:690:13)
    at [object Object].saveToPath (H:\tools\isobuild\isopack.js:1679:15)
    at H:\tools\isobuild\isopack-cache.js:380:23
    at H:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (H:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (H:\tools\isobuild\isopack-cache.js:317:18)
    at H:\tools\isobuild\isopack-cache.js:251:16
    at Function.time (H:\tools\tool-env\profile.js:305:10)
    at H:\tools\isobuild\isopack-cache.js:250:17
    at H:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (H:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (H:\tools\isobuild\isopack-cache.js:241:20)
    at H:\tools\isobuild\isopack-cache.js:77:14
    at H:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (H:\.meteor\packages\meteor-tool\1.4.4_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (H:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (H:\tools\isobuild\isopack-cache.js:76:24)
    at H:\tools\project-context.js:841:25
    at H:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (H:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (H:\tools\project-context.js:840:18)
    at H:\tools\project-context.js:283:9
    at H:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (H:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (H:\tools\project-context.js:273:18)
    at H:\tools\project-context.js:265:12
    at Function.run (H:\tools\tool-env\profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (H:\tools\project-context.js:264:13)
    at H:\tools\runners\run-app.js:563:29
    at H:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at H:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (H:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (H:\tools\utils\buildmessage.js:252:19)
    at bundleApp (H:\tools\runners\run-app.js:562:31)
    at [object Object]._.extend._runOnce (H:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (H:\tools\runners\run-app.js:890:28)
    at H:\tools\runners\run-app.js:417:12

Process finished with exit code 1
```
The exact change doesn't matter, it can be as simple as adding an empty line and saving. As long as Meteor is running when I make the change, it will begin rebuilding the plugin then crash with the above error. Once I restart Meteor, it works fine until I make another change.

**Comment by nathantreid** [comment]
Strangely, while I had experienced this issue a number of times and run multiple `meteor reset`s, I ran another `meteor reset` about an hour ago and haven't experienced the issue since.
