### ISSUE TITLE
process uncaughtException never fires

### ISSUE THREAD

**Issue by hungbya** [meteor/meteor#8649]
I am using `Meteor 1.4.2.6` for my application on `Centos 7` deployed by `pm2-meteor`. I am trying to send some HTTP request through a tunnel.

```javascript
process.on('uncaughtException', (e) => {
    console.error('uncaughtException');
    console.error(e);
});
```
Here is the logs
```
AssertionError: 120 == 0
    at ClientRequest.onConnect (/home/meteor/ACWebService/bundle/programs/server/npm/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:293:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:197:7)
    at Socket.socketOnData (_http_client.js:443:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```
without `uncaughtException` is printed, then the application crashed and stopped.

Do `Meteor` override `process.on('uncaughtException')` and provide other alternative methods?

**Comment by hwillson** [comment]
Hi @hungbya - can you provide a few more details about how you're making your HTTP request (ideally with a small reproduction showing your issue)? Your global error handler might not be working for a few different reasons - it could be affected by:

- Calling `process.on('uncaughtException')` after you've made your HTTP request
- How you're making your HTTP request
- Is your exception being thrown in a callback
- How Fibers are being brought into play

The more details you can provide, the better. Thanks!

**Comment by hungbya** [comment]
My apologies, this is because the library/script I used prints the error logs instead of throwing an error.
