### ISSUE TITLE
1.5 rc1 Bundle visualizer error.

### ISSUE THREAD

**Issue by dan335** [meteor/meteor#8689]
Getting this error after installing 1.5 rc1 and bundle-visualizer.  Using windows.  Meteor reset did not help.

````
=> Started proxy.
=> Started MongoDB.
C:\Users\danph\AppData\Local\.meteor\packages\coffeescript\1.12.3_1\plugin.compileCoffeescript.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promis
e_server.js:190
      throw error;
      ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\danph\web\astro\.meteor\local\.build274080.build\programs\.build715086.web.browser\dynamic\node_modules\meteo
r\bundle-visualizer'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:332:11)
    at rmdirSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)
    at rmdirSync (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync [as sync] (C:\Users\danph\AppData\Local\.meteor\packages\meteor-tool\1.5.0-rc.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\r
imraf.js:293:9)
    at Object.rm_recursive (C:\tools\fs\files.js:303:12)
    at Builder.abort (C:\tools\isobuild\builder.js:696:11)
    at C:\tools\isobuild\bundler.js:2718:13
    at C:\tools\isobuild\bundler.js:3007:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2840:31)
    at C:\tools\isobuild\bundler.js:2787:32
    at Object.withCache (C:\tools\fs\files.js:1652:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2787:16)
    at C:\tools\runners\run-app.js:588:36
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:587:34)
    at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:631:35)
    at [object Object]._.extend._fiber (C:\tools\runners\run-app.js:890:28)
    at C:\tools\runners\run-app.js:417:12
````

**Comment by hwillson** [comment]
Hi @dan335 - this doesn't appear to be specific to the `bundle-visualizer`. This looks more like the issues outlined in #8663 and #8485. Can you look through those issues and try some of the outlined workarounds? If you're still having problems, can you add to the discussion in one of those existing issues? I'll close this one for now. Thanks!

**Comment by abernix** [comment]
@dan335 I agree with @hwillson on this. Your issue is unfortunately a different, sporadic, Windows problem which hasn't been resolved yet.

**Comment by trusktr** [comment]
@abernix First time I've heard of bundle-visualizer (sounds interesting), but I don't see any docs or anything. What's it for and how do we use it?
