### ISSUE TITLE
[Windows] Error when installing package

### ISSUE THREAD

**Issue by steph643** [meteor/meteor#8691]
Meteor v1.4.4.2 under Windows.

How to reproduce:
1. Uninstall Meteor:
1.1. Control Panel > Programs > right click on Meteor > Uninstall
1.2. Use `rimraf` to remove all Meteor temp folders in `C:\Users\Steph\AppData\Local\Temp`, as described in https://github.com/meteor/meteor/issues/7194#issuecomment-226055121 (be patient, several GB)
1.3. Use `rimraf` to remove Meteor install folder `C:\Users\Steph\AppData\Local\.meteor`
2. Install a clean version of Meteor by running `InstallMeteor.exe`
3. `meteor create test`
4. `cd test`
5. `meteor add deanius:promise`

Result:
```
C:\Meteor\test>meteor add deanius:promise
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Steph\AppData\Local\
Temp\mt-1xpt0mh\npm\node_modules\browserify\node_modules\syntax-error']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Steph\\AppData\\Local\\Temp\\mt-1xpt0mh\\npm\\node_modules
\\browserify\\node_modules\\syntax-error' }
C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os.window
s.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-prom
ise\promise_server.js:190
      throw error;
      ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Steph\AppData\Local\Tem
p\.tmp1ru4ld3\coffeescript-1.0.17\plugin.compileCoffeescript.os\npm\node_modules
\meteor\babel-compiler\node_modules\meteor-babel\node_modules\babel-preset-meteo
r\node_modules\core-js'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:332:11)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at rimrafSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:293:9)
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:330:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1
.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:329:26)

    at rmdirSync (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.
4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimraf\rimraf.js:322:7)
    at Function.rimrafSync [as sync] (C:\Users\Steph\AppData\Local\.meteor\pac
kages\meteor-tool\1.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\rimra
f\rimraf.js:293:9)
    at Object.rm_recursive (C:\tools\fs\files.js:303:12)
    at Object.files.rename (C:\tools\fs\files.js:1735:13)
    at Object.files.extractTarGz (C:\tools\fs\files.js:767:9)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)

    at C:\tools\packaging\tropohouse.js:505:42
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:502:24
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Steph\AppData\Local\.meteor\package
s\meteor-tool\1.4.4_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscor
e\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:469:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\Steph\AppData\Local\.meteor\packages\meteor-tool\1.4.4_2\mt-os
.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\mete
or-promise\fiber_pool.js:32:39
 => awaited here:
    at Promise.await (C:\Users\Steph\AppData\Local\.meteor\packages\meteor-too
l\1.4.4_2\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\no
de_modules\meteor-promise\promise_server.js:39:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:604:6)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packagi
ng\tropohouse.js:609:18)
    at C:\tools\project-context.js:808:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:807:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalo
g\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:806:
13)
    at C:\tools\project-context.js:283:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.
js:273:18)
    at C:\tools\project-context.js:265:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.
js:264:13)
    at C:\tools\cli\commands-packages.js:2071:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14
)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Command.func (C:\tools\cli\commands-packages.js:2070:27)
    at C:\tools\cli\main.js:1483:23

C:\Meteor\test>
```

**Comment by steph643** [comment]
The error looks similar to this one: https://github.com/meteor/meteor/issues/8485#issuecomment-295476353.

**Comment by steph643** [comment]
It seems the problem was due to a corrupted hard drive. Solved by running the Windows error checking utility (right click on drive > Properties > Tools > Check now...).

**Comment by steph643** [comment]
> It seems the problem was due to a corrupted hard drive

As mentioned in https://github.com/meteor/meteor/issues/8663#issuecomment-305725604, the ENOTEMPTY error occurs randomly. So I suspect it finally worked by pure chance.
