### ISSUE TITLE
1.5-rc6 - Error with "optionalDependencies"

### ISSUE THREAD

**Issue by billyvg** [meteor/meteor#8716]
There is a problem where an "optionalDependency" package that is defined in `package.json` is not installed.

Unfortunately I'm unable to reproduce this in a clean repository. This happens for us in one of our meteor packages that depends on the `bunyan` package. You can view their (package.json)[https://github.com/trentm/node-bunyan/blob/master/package.json#L28]. For us, the `safe-json-stringify` does not get installed (however when I add our package in a bare meteor project, it does get installed).

Here is the relevant stack trace:
```
TypeError: Cannot read property '0' of undefined
    at toPosixPath (/Users/billy/.meteor/packages/meteor-tool/.1.5.0-rc.6.z4yke1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/static-assets/server/mini-files.js:27:8)
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:533:22)
    at /tools/isobuild/import-scanner.js:516:9
    at _.each._.forEach (/Users/billy/.meteor/packages/meteor-tool/.1.5.0-rc.6.z4yke1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._resolve (/tools/isobuild/import-scanner.js:498:7)
    at /tools/isobuild/import-scanner.js:567:8
    at _.each._.forEach (/Users/billy/.meteor/packages/meteor-tool/.1.5.0-rc.6.z4yke1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:561:7)
    at /Users/billy/.meteor/packages/meteor-tool/.1.5.0-rc.6.z4yke1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/import-scanner.js:759:14
    at _.each._.forEach (/Users/billy/.meteor/packages/meteor-tool/.1.5.0-rc.6.z4yke1++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:561:7)
    at /tools/isobuild/import-scanner.js:357:14
    at Array.forEach (native)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:355:22)
    at /tools/isobuild/compiler-plugin.js:1040:17
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1008:19)
    at ServerTarget._emitResources (/tools/isobuild/bundler.js:1059:8)
    at /tools/isobuild/bundler.js:830:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ServerTarget.make (/tools/isobuild/bundler.js:821:18)
    at /tools/isobuild/bundler.js:2907:14
    at /tools/isobuild/bundler.js:2975:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2860:31)
    at /tools/isobuild/bundler.js:2807:32
    at Object.withCache (/tools/fs/files.js:1652:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2807:16)
    at /tools/runners/run-app.js:588:36
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:587:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
```

Here is a dump of `packageJsonFile` in `ImportScanner.prototype._resolve`:
```

{ type: 'js',or os.osx.x86_64                |
  data: <Buffer 65 78 70 6f 72 74 73 2e 6e 61 6d 65 20 3d 20 22 73 61 66 65 2d 6a 73 6f 6e 2d 73 74 72 69 6e 67 69 66 79 22 3b 0a 65 78 70 6f 72 74 73 2e 76 65 72 73 ... >,
  jsonData:
   { name: 'safe-json-stringify',
     version: '1.0.3',
     main: 'index.js' },
  deps: {},
  sourcePath: '../../.2.0.3.1ef0dor++os+web.browser+web.cordova/npm/node_modules/safe-json-stringify/package.json',
  installPath: undefined,
  servePath: '../../.2.0.3.1ef0dor++os+web.browser+web.cordova/npm/node_modules/safe-json-stringify/package.json',
  hash: '2f00b993461ea58dd791db44bb33da868e9a301f',
  lazy: true,
  imported: true,
  implicit: true }
```

And then error from build tool:
```
TypeError: Path must be a string. Received undefined
```

**Comment by hwillson** [comment]
Hi @billyvg - Meteor installs `optionalDependencies` by default which is why it gets installed in your bare Meteor project. In the project that's showing this issue, have you tried:

1. Removing `node_modules`
2. `meteor npm install`
3. `meteor reset` (warning: will remove your local DB; if you want to keep your database just remove `APP_ROOT/.meteor/local`)

After that, can you verify that `safe-json-stringify` is installed?

**Comment by billyvg** [comment]
Oops you're right, thank you!

I did not run `meteor npm install`, instead I was using my system `npm`.
