### ISSUE TITLE
Meteor updating NPM dependencies on every file change

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#8747]
I have a meteor package inside a packages folder of my Meteor 1.4.4.2 project.
Inside the package I have some NPM dependencies specified.

The problem is that somehow on every filechange all NPM packages are updated.
E.g. a small change to a client-only file results in:
`barco-accounts-saml: updating npm dependencies -- connect, whatwg-url, @sebak/express-saml2...`

I don't know if that is supposed to be like this, but because of this bug: https://github.com/meteor/meteor/issues/8732 after each file change it can occur that packages are suddenly 'lost' and I need to remove the `.npm` directory and try again. 

And other times meteor just crashes with errors like:
```
Error: ENOENT: no such file or directory, readlink '/home/seke/dev/blue-new/packages/barco_accounts-saml/.npm/package/node_modules/.bin/mime'
    at Error (native)
    at Object.fs.readlinkSync (fs.js:857:18)
    at Object.wrapper [as readlink] (/tools/fs/files.js:1586:35)
    at /tools/isobuild/builder.js:563:40
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at /tools/isobuild/builder.js:556:11
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at Builder.copyDirectory (/tools/isobuild/builder.js:594:5)
    at /tools/isobuild/isopack.js:1446:17
    at Function._.each._.forEach (/home/seke/.meteor/packages-from-server/kndedu01.barco.comX3005/meteor-tool/.1.4.4_2.1k50n65++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].saveToPath (/tools/isobuild/isopack.js:1445:9)
    at /tools/isobuild/isopack-cache.js:380:23
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:317:18)
    at /tools/isobuild/isopack-cache.js:251:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:250:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:241:20)
    at /tools/isobuild/isopack-cache.js:77:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/seke/.meteor/packages-from-server/kndedu01.barco.comX3005/meteor-tool/.1.4.4_2.1k50n65++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:76:24)
    at /tools/project-context.js:841:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:840:18)
    at /tools/project-context.js:283:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:273:18)
    at /tools/project-context.js:265:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:264:13)
    at /tools/runners/run-app.js:563:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:562:31)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
    at /tools/runners/run-app.js:417:12
```

**Comment by benjamn** [comment]
This is definitely a problem (sorry!), but I believe removing the `.npm` directory (so that it will be recreated) is the best workaround until we can fix this in Meteor 1.5.1. I agree that #8732 is very likely the same problem (or at least related).
