### ISSUE TITLE
Ecmascript Update 0.8.0: TypeError: module.exportDefault is not a function

### ISSUE THREAD

**Issue by lmachens** [meteor/meteor#8755]
Hi, 

I updated the ecmascript package from 0.8.0-rc.4 to 0.8.0 and get the following error message:

```
TypeError: module.exportDefault is not a function
W20170603-10:42:15.279(2)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.ReactMeteorData.jsx (packages/react-meteor-data/ReactMeteorData.jsx:1:8)
W20170603-10:42:15.279(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170603-10:42:15.280(2)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170603-10:42:15.280(2)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:1:136)
W20170603-10:42:15.280(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170603-10:42:15.280(2)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170603-10:42:15.281(2)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:1:14)
W20170603-10:42:15.281(2)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:333:9)
W20170603-10:42:15.281(2)? (STDERR)     at require (packages\modules-runtime.js:228:16)
W20170603-10:42:15.282(2)? (STDERR)     at ...\.meteor\local\build\programs\server\packages\react-meteor-data.js:343:15
```

All updated packages:

```
ecmascript                 upgraded from 0.8.0-rc.4 to 0.8.0
ecmascript-runtime         upgraded from 0.4.0 to 0.4.1
ecmascript-runtime-client  upgraded from 0.4.0 to 0.4.1
ecmascript-runtime-server  upgraded from 0.4.0 to 0.4.1
promise                    upgraded from 0.8.8 to 0.8.9
```

The `react-meteor-data` version is 0.2.11.

Anyone has an idea or similar problems?

**Comment by benjamn** [comment]
What version of the `modules` package are you using?

**Comment by lmachens** [comment]
`versions`:
```
modules@0.10.0-pre.1
modules-runtime@0.9.0-pre.1
```
modules was not part of my `packages` file. So I installed it with `meteor install modules` and changed the version in `versions` file by hand to 0.9.1.
Now it is working fine thx! Meteor 1.5 is fine too! :)

The question is, why modules@0.10.0-pre.1 was in my versions file?

**Comment by benjamn** [comment]
Hmm, have you ever tried any of the the Meteor 1.6 prereleases? Might be left over from that?

**Comment by lmachens** [comment]
Never
