### ISSUE TITLE
meteor build using 1.5 fails :  UglifyJSMinify is not defined

### ISSUE THREAD

**Issue by scottstensland** [meteor/meteor#8762]
Our build process is fine on previous releases however when I upgrade meteor from

old    METEOR@1.4.2.7
new  METEOR@1.5

seeing  :    UglifyJSMinify is not defined
at packages/widgets-build/plugin.js:68:12

```

meteor update --all-packages


meteor --release 1.5 build --server https://example.com  --verbose  --directory /some/deploy --mobile-settings build/../config/staging.json

Opening db file /home/stens/.meteor/package-metadata/v2.0.1/packages.data.db
Local package version is up-to-date: accounts-base@1.3.0
Local package version is up-to-date: accounts-password@1.3.6
Local package version is up-to-date: aldeed:collection2@2.10.0
Local package version is up-to-date: aldeed:collection2-core@1.2.0
Local package version is up-to-date: aldeed:schema-deny@1.1.0
Local package version is up-to-date: aldeed:schema-index@1.1.1
Local package version is up-to-date: aldeed:simple-schema@1.5.3
Local package version is up-to-date: allow-deny@1.0.5
Local package version is up-to-date: autoupdate@1.3.12
Local package version is up-to-date: babel-compiler@6.19.2
Local package version is up-to-date: babel-runtime@1.0.1
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.2
Local package version is up-to-date: blaze-html-templates@1.1.2
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.1.0
Local package version is up-to-date: caching-compiler@1.1.9
Local package version is up-to-date: caching-html-compiler@1.1.2
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: check@1.2.5
Local package version is up-to-date: ddp@1.2.5
Local package version is up-to-date: ddp-client@1.3.4
Local package version is up-to-date: ddp-common@1.2.8
Local package version is up-to-date: ddp-rate-limiter@1.0.7
Local package version is up-to-date: ddp-server@1.3.14
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: dynamic-import@0.1.1
Local package version is up-to-date: ecmascript@0.8.0
Local package version is up-to-date: ecmascript-runtime@0.4.1
Local package version is up-to-date: ecmascript-runtime-client@0.4.1
Local package version is up-to-date: ecmascript-runtime-server@0.4.1
Local package version is up-to-date: ejson@1.0.13
Local package version is up-to-date: email@1.2.3
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: fastclick@1.0.13
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.2.12
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: localstorage@1.1.0
Local package version is up-to-date: logging@1.1.17
Local package version is up-to-date: mdg:validation-error@0.5.1
Local package version is up-to-date: meteor@1.6.1
Local package version is up-to-date: meteor-base@1.1.0
Local package version is up-to-date: minifier-css@1.2.16
Local package version is up-to-date: minifier-js@2.1.0
Local package version is up-to-date: minimongo@1.2.0
Local package version is up-to-date: mobile-experience@1.0.4
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modules@0.9.1
Local package version is up-to-date: modules-runtime@0.8.0
Local package version is up-to-date: mongo@1.1.18
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: npm-bcrypt@0.9.2
Local package version is up-to-date: npm-mongo@2.2.24
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: peerlibrary:blocking@0.5.2
Local package version is up-to-date: peerlibrary:xml2js@0.4.8_1
Local package version is up-to-date: promise@0.8.9
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: rate-limit@1.0.8
Local package version is up-to-date: reactive-dict@1.1.9
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
Local package version is up-to-date: service-configuration@1.0.11
Local package version is up-to-date: session@1.1.7
Local package version is up-to-date: sha@1.0.9
Local package version is up-to-date: shell-server@0.2.3
Local package version is up-to-date: spacebars@1.0.15
Local package version is up-to-date: spacebars-compiler@1.1.2
Local package version is up-to-date: srp@1.0.10
Local package version is up-to-date: standard-minifier-css@1.3.4
Local package version is up-to-date: standard-minifier-js@2.1.0
Local package version is up-to-date: templating@1.3.2
Local package version is up-to-date: templating-compiler@1.3.2
Local package version is up-to-date: templating-runtime@1.3.2
Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: tracker@1.1.3
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.1.0
Local package version is up-to-date: webapp@1.3.16
Local package version is up-to-date: webapp-hashing@1.0.9
Errors prevented bundling:
While processing files with loudspeed:widgets-build (for target os.linux.x86_64):
packages/widgets-build/plugin.js:68:12: UglifyJSMinify is not defined
at packages/widgets-build/plugin.js:68:12
at Array.forEach (native)
at WidgetBuilder.processFilesForTarget (packages/widgets-build/plugin.js:45:8)

```

ubuntu 16.04  
nodejs  v4.8.3

**Comment by benjamn** [comment]
I believe you should update your `loudspeed:widgets-build` package to call [`meteorJsMinify`](https://github.com/meteor/meteor/blob/40f1d99e2ca6d56b8909620dffe03ddb11165f78/packages/minifier-js/minifier.js#L3) instead of `UglifyJSMinify` (in `packages/widgets-build/plugin.js`). That package should probably also `api.use("minifier-js@2.1.0")` to avoid version inconsistencies like this in the future. Does that help?

**Comment by GeorgeCalvert** [comment]
@benjamn -- Thanks, that worked :-)  For some reason, we couldn't figure out what the new name was.
