### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by Rongky** [meteor/meteor#8785]
Good day. Since updating to meteor 1.5, I can no longer build and deploy my meteor app due to this error. I'm using ubuntu 16.04 / node v4.8.3 / npm v2.15.11. Below is the complete error:

Building the application                  \
/home/user/.meteor/packages/coffeescript/.1.12.3_1.1uifmy6++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/home/user/.meteor/packages/less/.2.7.9.18yn5i7++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/compileLessBatch/node_modules/less/node_modules/graceful-fs/polyfills.js:14:9)
    at process.chdir (/home/user/dev/meteor/app/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/home/user/.meteor/packages/meteor-tool/.1.5.0.ogir81++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/graceful-fs/polyfills.js:21:9)
    at CordovaProject.runCommands (/tools/cordova/project.js:701:15)
    at CordovaProject.buildForPlatform (/tools/cordova/project.js:245:10)
    at /tools/cli/commands.js:1021:30
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/cli/commands.js:1004:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at buildCommand (/tools/cli/commands.js:990:10)
    at Command.func (/tools/cli/commands.js:824:12)
    at /tools/cli/main.js:1483:23

**Comment by Rongky** [comment]
Solved. This is somewhat similar to issue #5467 - on simply having a typo in the mobile-config.js file. The issue is not due to upgrading to meteor 1.5 nor with using certain npm/meteor packages having graceful-fs/polyfills.js as dependencies. It is simply caused by modifying the mobile-config.js file. I simply imported a js file to automate the app's versioning in the App.info() config. With that, it took me days troubleshooting, deleting/reinstalling packages to no avail. Hope MDG will provide better error messages for mobile-configuration issues.

**Comment by abernix** [comment]
@Rongky Glad you found the problem and got it fixed.  The best way to get it fixed more permanently would be to create and share a basic reproduction repository per the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) instructions.  If you've already found the specific typo, it should only take a few minutes of your time and would be a great help to future developers (like yourself!) who run into it.
