### ISSUE TITLE
native: Unexpected end of input when .babelrc is empty

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#8792]
https://github.com/meteor/meteor/issues/7965

reproduce 

https://github.com/crapthings/meteor-empty-babelrc

```
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   native: Unexpected end of input
   at Object.parse (native)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler.js:246:14)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:236:10)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:166:10)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:109:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:108:14)


   While processing files with ecmascript (for target os.osx.x86_64):
   native: Unexpected end of input
   at Object.parse (native)
   at BabelCompiler.BCp._inferFromBabelRc (packages/babel-compiler.js:246:14)
   at BabelCompiler.BCp.inferExtraBabelOptions (packages/babel-compiler.js:236:10)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:166:10)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:109:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:108:14)
```

**Comment by crapthings** [comment]
this work .babelrc

```js
{}
```

newline failed .babelrc

```js

```

**Comment by abernix** [comment]
While the error _could_ be caught and you could be given a nice error message, [`.babelrc` files are intended to be in the JSON file-format](https://babeljs.io/docs/usage/babelrc/) and JSON cannot be empty.

For example, you would receive the same `Unexpected end of input` error if you ran the following in any JavaScript console since it's invalid JSON:

```js
JSON.parse("");
```

Whereas, the following would succeed since it is valid JSON:

```js
JSON.parse("{}");
```
