### ISSUE TITLE
Fresh install, meteor create test fails: Error: EACCES: permission denied, open...

### ISSUE THREAD

**Issue by holmrenser** [meteor/meteor#8818]
I am trying to get meteor to work on a Ubuntu machine (16.10).

The following two commands result in errors:

```
curl https://install.meteor.com/ | sh
meteor create test
```

After which I get a permission denied error for (what I think are) some temporary build files.
Example:

```
/home/holme003/.meteor/packages/meteor-tool/.1.5.0.utbu0o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: EACCES: permission denied, open '/home/holme003/.meteor/packages/dynamic-import/.build138814..0.1.1.zmtqae++os+web.browser+web.cordova/.builder-tmp-file.867978'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.wrapper [as writeFile] (/tools/fs/files.js:1586:35)
    at atomicallyRewriteFile (/tools/isobuild/builder.js:710:9)
    at Builder.write (/tools/isobuild/builder.js:274:9)
    at [object Object].saveToPath (/tools/isobuild/isopack.js:1262:15)
    at [object Object]._.extend._saveIsopack (/tools/packaging/tropohouse.js:353:15)
    at /tools/packaging/tropohouse.js:526:16
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/packaging/tropohouse.js:515:22
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.download (/tools/packaging/tropohouse.js:427:20)
    at /tools/packaging/tropohouse.js:613:18
    at /tools/utils/buildmessage.js:572:21
    at /home/holme003/.meteor/packages/meteor-tool/.1.5.0.utbu0o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:32:39
 => awaited here:
    at Promise.await (/home/holme003/.meteor/packages/meteor-tool/.1.5.0.utbu0o++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Object.forkJoin (/tools/utils/buildmessage.js:604:6)
    at [object Object]._.extend.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:609:18)
    at /tools/project-context.js:808:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/project-context.js:807:20
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (/tools/project-context.js:806:13)
    at /tools/project-context.js:283:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:273:18)
    at /tools/project-context.js:265:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:264:13)
```

When I check the folder mentioned in the error the file that should be opened (```/home/holme003/.meteor/packages/dynamic-import/.build138814..0.1.1.zmtqae++os+web.browser+web.cordova/.builder-tmp-file.867978```) does not exist. What is more is that the folder in which the file should be also does not exist. The first existing parent folder is ```/home/holme003/.meteor/packages/dynamic-import/.build138814..0.1.1.zmtqae++os+web.browser+web.cordova/.builder-tmp-file.867978```.

Additionally it seems that when I try this multiple times it crashes on a variety of dependencies.

**Comment by hwillson** [comment]
Did you run any of your reproduction commands as `root` (or via `sudo`)?

**Comment by hwillson** [comment]
We haven't heard back regarding https://github.com/meteor/meteor/issues/8818#issuecomment-329148895, so closing for now.

**Comment by holmrenser** [comment]
Definitely did not run as root or sudo, as I do not have these permissions on this particular machine.
