### ISSUE TITLE
(ReferenceError: dynamicImportInfo is not defined) after updating to Meteor 1.4.4.3.

### ISSUE THREAD

**Issue by walterchau** [meteor/meteor#8855]
Hi, I got an error after updating to Meteor 1.4.4.3. Please help.

ReferenceError: dynamicImportInfo is not defined
    at meteorInstall.node_modules.meteor.dynamic-import.server.js (packages/dynamic-import/server.js:15:13)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at /Users/chaupuikit/meteor-projects/dashboard/.meteor/local/build/programs/server/packages/dynamic-import.js:495:15
    at /Users/chaupuikit/meteor-projects/dashboard/.meteor/local/build/programs/server/packages/dynamic-import.js:501:3
    at /Users/chaupuikit/meteor-projects/dashboard/.meteor/local/build/programs/server/boot.js:303:34
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/chaupuikit/.meteor/packages/meteor-tool/.1.4.4_3.16p256d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/chaupuikit/meteor-projects/dashboard/.meteor/local/build/programs/server/boot.js:128:5
    at /Users/chaupuikit/meteor-projects/dashboard/.meteor/local/build/programs/server/boot.js:352:5
Exited with code: 1
Your application is crashing. Waiting for file change.

**Comment by benjamn** [comment]
The `dynamic-import` package only works with Meteor 1.5. Can you remove it from your `.meteor/packages` file, or is it used by some other package?

**Comment by hwillson** [comment]
As mentioned in https://github.com/meteor/meteor/issues/8855#issuecomment-311699980, the earliest Meteor version that supports dynamic imports is Meteor 1.5. Closing - thanks!
