### ISSUE TITLE
promise_server error on deployment

### ISSUE THREAD

**Issue by formspoint** [meteor/meteor#8886]
I'm on MacOS 10.12.4, Meteor 1.5.

After having use 1.5 since it dropped weeks ago, and without adding any additional libs, today two strange things happended.

The first is a file in the import dir was renamed to have a zero behind the file name, and my app started complaining on rebuild it could not find the file.  I removed the 0 from the back of the file and Meteor still did not rebuild, complaining that it could not find that file -- even thought it was there.  I had to stop Meteor and restart before it started building correctly.  By the way I wasn't even working in this file.

Shortly after this, I made my changes to another file, and decided to use MUP to deploy it to my EC2 server as always.  Again, I did this just yesterday without a hich.  The following error is consistently throwing while trying to do that.  I'll try to restart my machine to see if it helps.

Building Started: /Users/aadams/Meteors/development/client
Bundle path: /var/folders/lb/t3zr71hx4_v5rtj847yyghb80000gn/T/14c75ea4-4e61-4e7e-87ee-5b823e51ae38/bundle.tar.gz
/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/aadams/Meteors/development/client'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1582:34)
    at readDirectory (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:338:26)
    at Object.readAndWatchDirectory (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:797:18)
    at [object Object]._.extend._readAndWatchDirectory (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/package-source.js:866:18)
    at find (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/package-source.js:1095:39)
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/package-source.js:1139:14
    at Object.withCache (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1650:12)
    at [object Object]._.extend._findSources (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/package-source.js:1138:18)
    at SourceArch.getFiles (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/package-source.js:919:27)
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/compiler.js:431:67
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/compiler.js:207:28
    at Object.withCache (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1650:12)
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/compiler.js:206:11
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/compiler.js:201:5)
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:2793:24
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:291:13
    at [object Object]._.extend.withValue (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:110:14)
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:282:29
    at [object Object]._.extend.withValue (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:110:14)
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:280:18
    at [object Object]._.extend.withValue (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:110:14)
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:270:23
    at [object Object]._.extend.withValue (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/fiber-helpers.js:110:14)
    at Object.capture (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/utils/buildmessage.js:269:19)
    at bundle (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:2745:31)
    at /Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:2700:12
    at Object.withCache (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/files.js:1650:12)
    at Object.exports.bundle (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.ofgn8b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/isobuild/bundler.js:2699:16)
    at buildCommand (/tools/cli/commands.js:949:30)
    at Command.func (/tools/cli/commands.js:824:12)
    at /tools/cli/main.js:1483:23

=> Build Error. Check the logs printed above.

**Comment by formspoint** [comment]
I got rid of this error by:

1) Restarting

2) sudo rm /usr/local/bin/meteor

3) rm -rf ~/.meteor

4) curl https://install.meteor.com/ | sh

**Comment by formspoint** [comment]
Another promise_server error today when trying to deploy, looks similar.

Building Started: /Users/aadams/Meteors/development/test-client
Bundle path: /var/folders/lb/t3zr71hx4_v5rtj847yyghb80000gn/T/81711f85-38ac-4b5b-b071-b77453840b2d/bundle.tar.gz
/Users/aadams/.meteor/packages/templating-compiler/.1.3.2.7o28ib++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, open '/Users/aadams/Meteors/development/test-client/client/views/report-screens/report1.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at wrapper (/tools/fs/files.js:1586:35)
    at wrap.makeCacheKey._len2 (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/optimistic.js:103:15)
    at Entry._reallyRecompute (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/compiler.js:558:22
    at Array.forEach (native)
    at /tools/isobuild/compiler.js:494:21
    at /tools/isobuild/compiler.js:184:28
    at Object.withCache (/tools/fs/files.js:1652:12)
    at /tools/isobuild/compiler.js:183:11
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/aadams/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:178:5)
    at /tools/isobuild/bundler.js:2917:24
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2860:31)
    at /tools/isobuild/bundler.js:2807:32
    at Object.withCache (/tools/fs/files.js:1652:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2807:16)
    at buildCommand (/tools/cli/commands.js:949:30)
    at Command.func (/tools/cli/commands.js:824:12)
    at /tools/cli/main.js:1483:23

=> Build Error. Check the logs printed above.

**Comment by hwillson** [comment]
Sounds like you're hitting an open file limit on macOS - see https://github.com/meteor/meteor/issues/8057. Does anything in that thread help?

**Comment by abernix** [comment]
Thanks for reporting an issue with Meteor.  I'm going to close this because we haven't heard anything back from you about this problem.

We'd be happy to reopen it if you come up with some additional details that are helpful in resolving it.  Please read the [reporting a bug](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-bug) guidelines to see what is needed in a reproduction.  :)
