### ISSUE TITLE
fresh install error

### ISSUE THREAD

**Issue by cesarve77** [meteor/meteor#8910]
I created a new project like following:

```
MacBook-Air-de-Cesar:www cesar$ meteor create twilio
Created a new Meteor app in 'twilio'.         

To run your new app:                          
  cd twilio                                   
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                
                                              
meteor create --bare to create an empty app.  
meteor create --full to create a scaffolded app.
                                              
MacBook-Air-de-Cesar:www cesar$   cd twilio                                   
MacBook-Air-de-Cesar:twilio cesar$   meteor                
[[[[[ ~/Documents/www/twilio ]]]]]            

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20170714-10:04:31.820(10)? Internal exception while processing message { msg: 'connect',
I20170714-10:04:31.916(10)?   version: '1',
I20170714-10:04:31.917(10)?   support: [ '1', 'pre2', 'pre1' ] } Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
I20170714-10:04:31.918(10)?     at withoutInvocation (packages/meteor.js:443:33)
I20170714-10:04:31.918(10)?     at bindAndCatch (packages/meteor.js:452:33)
I20170714-10:04:31.919(10)?     at Object._.extend.setInterval (packages/meteor.js:479:24)
I20170714-10:04:31.920(10)?     at [object Object]._.extend._startHeartbeatIntervalTimer (packages/ddp-common.js:89:44)
I20170714-10:04:31.921(10)?     at [object Object]._.extend.start (packages/ddp-common.js:84:10)
I20170714-10:04:31.925(10)?     at new Session (packages/ddp-server/livedata_server.js:318:20)
I20170714-10:04:31.926(10)?     at [object Object]._.extend._handleConnect (packages/ddp-server/livedata_server.js:1463:29)
I20170714-10:04:31.927(10)?     at packages/ddp-server/livedata_server.js:1379:18
```

the error appears any time I refresh the browser.

Using OSX 10.12.5
Meteor 1.5

**Comment by ejdelmonico** [comment]
Same error here with a fresh install through Webstorm 2017's Meteor App generator. It worked fine up until this fresh project. Also, I had the same issue using the cli to generate a new project.

**Comment by copleykj** [comment]
duplicate #8908 #8902

**Comment by hwillson** [comment]
Closing as a duplicate (thanks @copleykj!).
