### ISSUE TITLE
empty file: `rando.html.handlebars` crashes server

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/meteor#8916]
Meteor 1.5.  Creating a file `server/lib/etc/etc/rando.html.handlebars` crashes the server with the exception below.  If the file has a newline, the crash doesn't happen.

```
W20170714-14:06:05.237(-5)? (STDERR)          
W20170714-14:06:05.237(-5)? (STDERR) /home/michael/.meteor/packages/meteor-tool/.1.5.0.13y3u7e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170714-14:06:05.238(-5)? (STDERR) 						throw(ex);
W20170714-14:06:05.238(-5)? (STDERR) 						^
W20170714-14:06:05.239(-5)? (STDERR) Error
W20170714-14:06:05.239(-5)? (STDERR)     at Object.exports.attach (/home/michael/.meteor/packages/cmather_handlebars-server/.2.0.0.2dnoml++os+web.browser+web.cordova/npm/node_modules/handlebars/lib/handlebars/utils.js:15:34)
W20170714-14:06:05.239(-5)? (STDERR)     at create (/home/michael/.meteor/packages/cmather_handlebars-server/.2.0.0.2dnoml++os+web.browser+web.cordova/npm/node_modules/handlebars/lib/handlebars.js:12:9)
W20170714-14:06:05.240(-5)? (STDERR)     at Object.<anonymous> (/home/michael/.meteor/packages/cmather_handlebars-server/.2.0.0.2dnoml++os+web.browser+web.cordova/npm/node_modules/handlebars/lib/handlebars.js:19:18)
W20170714-14:06:05.240(-5)? (STDERR)     at Module._compile (module.js:409:26)
W20170714-14:06:05.241(-5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170714-14:06:05.241(-5)? (STDERR)     at Module.load (module.js:343:32)
W20170714-14:06:05.241(-5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170714-14:06:05.242(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170714-14:06:05.242(-5)? (STDERR)     at require (internal/module.js:12:17)
W20170714-14:06:05.242(-5)? (STDERR)     at Object.require (/home/michael/scm/blink/blink-meteor/admin/.meteor/local/build/programs/server/boot.js:217:18)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by MichaelJCole** [comment]
nmind.  It's cmather handlebars server.  Will post there.

**Comment by MichaelJCole** [comment]
https://github.com/cmather/meteor-handlebars-server/issues/37
