### ISSUE TITLE
Failed upgrade from v1.2.0 to latest version

### ISSUE THREAD

**Issue by mu-hasan** [meteor/meteor#8964]
I'm newbie on Meteor and NodeJS. I continue the chat project of another team. They use Meteor version 1.2.0, and My Leader want upgrade it to latest version. And I got this error when I upgrade it

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/project/jajal/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Super expression must either be null or a function, not undefined
    at exports.default (/project/jajal/bundle/programs/server/npm/node_modules/babel-runtime/helpers/inherits.js:21:11)
    at /project/jajal/bundle/programs/server/packages/react-meteor-data.js:285:26
    at meteorInstall.node_modules.meteor.react-meteor-data.ReactMeteorData.jsx (/project/jajal/bundle/programs/server/packages/react-meteor-data.js:293:2)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:1:136)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:1:14)
    at fileEvaluate (packages/modules-runtime.js:333:9)

**Comment by derwaldgeist** [comment]
Have you followed the upgrade guide's recommendation to upgrade step by step, i.e. from 1.2 to 1.3 to 1.4 and then finally to 1.5(.1)? There are upgrade guides for each of these:

https://guide.meteor.com/1.3-migration.html
https://guide.meteor.com/1.4-migration.html
https://guide.meteor.com/1.5-migration.html

The biggest challenge is the step from 1.2 to 1.3, which included a lot of changes in the build system and requires you to install some local npm packages.

It took me 2 weeks so far, to upgrade my own app from 1.2 to 1.5, and I'm still facing issues. So: good luck :-)
