### ISSUE TITLE
[SOLVED][Windows 1.5.1] After Update nothing works - error

### ISSUE THREAD

**Issue by gcacars** [meteor/meteor#8968]
I just executed meteor update in my project (1.5).
After meter-tool download, all meteor commands doesn't works anymore.

```
C:\Users\gabri\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\tools\index.js:13
    throw error;
    ^

Error: spawn EPERM
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:315:11)
    at Object.exports.spawn (child_process.js:365:9)
    at C:\Users\gabri\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\tools\cli\dev-bundle-bin-helpers.js:138:42
    at addWindowsVariables (C:\Users\gabri\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\tools\cli\dev-bundle-bin-helpers.js:135:10)
    at C:\Users\gabri\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\tools\cli\dev-bundle-bin-helpers.js:105:14
    at C:\Users\gabri\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:32:39
```

I reinstalled Meteor using official installer, but doesn't worked too.
I restarted my PC. I deleted again the .meteor folder, and extract alternative installation zip.
I restarted my PC again.
The message is always the same.

Read-only flag was removed and I applied grant to user Everyone to control the files (either AppData and project).

My PC is a Windows 10 x64.
Any ideas to solve this?

**Comment by gcacars** [comment]
Solved.

My Comodo Internet Security for any reason was blocking Meteor.
I solved by disabling the Hips module and remove all rules with node and meteor.
