### ISSUE TITLE
bcrypt error on upgrading to 1.5.1

### ISSUE THREAD

**Issue by cdcv** [meteor/meteor#9046]
- [x] The version of Meteor showing the problem.

1.5.1

- [x] The last version of Meteor where the problem did _not_ occur (if applicable)

1.5

- [x] The operating system you're running Meteor on.

macOS Sierra 10.12

- [x] The expected behavior.

Meteor server starts without error

- [x] The actual behavior.

I get an error:

```
$ meteor 
[runs fine]
$ meteor update
[updated from 1.5 to 1.5.1]
$ meteor

=> Started proxy.
=> Started MongoDB.

W20170825-22:54:22.402(-7)? (STDERR) /Users/me/.meteor/packages/meteor-tool/.1.5.1.18nj1hx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170825-22:54:22.479(-7)? (STDERR)                                            throw(ex);
W20170825-22:54:22.480(-7)? (STDERR)                                            ^
W20170825-22:54:22.480(-7)? (STDERR)
W20170825-22:54:22.481(-7)? (STDERR) TypeError: Cannot read property 'hash' of undefined
W20170825-22:54:22.482(-7)? (STDERR)     at meteorInstall.node_modules.meteor.accounts-password.password_server.js (packages/accounts-password/password_server.js:4:35)
W20170825-22:54:22.482(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170825-22:54:22.483(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170825-22:54:22.484(-7)? (STDERR)     at /Users/me/app/.meteor/local/build/programs/server/packages/accounts-password.js:1226:1
W20170825-22:54:22.484(-7)? (STDERR)     at /Users/me/app/.meteor/local/build/programs/server/packages/accounts-password.js:1232:3
W20170825-22:54:22.485(-7)? (STDERR)     at /Users/me/app/.meteor/local/build/programs/server/boot.js:338:34
W20170825-22:54:22.485(-7)? (STDERR)     at Array.forEach (native)
W20170825-22:54:22.486(-7)? (STDERR)     at Function._.each._.forEach (/Users/me/.meteor/packages/meteor-tool/.1.5.1.18nj1hx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170825-22:54:22.486(-7)? (STDERR)     at /Users/me/app/.meteor/local/build/programs/server/boot.js:158:5
W20170825-22:54:22.487(-7)? (STDERR)     at /Users/me/app/.meteor/local/build/programs/server/boot.js:387:5
=> Exited with code: 1
```

Looks like `NpmModuleBcrypt` is undefined? I don't know why. 

https://github.com/meteor/meteor/blob/devel/packages/accounts-password/password_server.js#L4

- `node_modules/` has `bcrypt@0.8.7`
- `.meteor/versions` has `npm-bcrypt@0.9.3`

And now when I try to downgrade with `meteor update --release 1.5`, I get this fatal error:

```
Error: ENOENT: no such file or directory, lstat '/Users/me/.meteor/packages/es5-shim/.4.6.15.lise9m++os+web.browser+web.cordova/npm/node_modules'
```

**Comment by cdcv** [comment]
I was able to resolve this issue by removing bcrypt using:
rm -rf ~/.meteor/packages/npm-bcrypt  

and re-installing it.  Normal uninstall/reinstall didn't work.
