### ISSUE TITLE
meteor npm error

### ISSUE THREAD

**Issue by tomasdms** [meteor/meteor#9053]
meteor 1.5.1 running on macOS sierra 10.12.6 

The problem starts when i try to create a new app with

meteor create testapp

it gives me this error:
______________________________________________________________________
/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: /Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm install
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:19:21
    at Object.<anonymous> (/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:92:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:19:21
    at Object.<anonymous> (/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:92:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

    at Object.error (/tools/utils/buildmessage.js:430:11)
    at /tools/cli/default-npm-deps.js:32:20
    at /tools/utils/buildmessage.js:334:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:333:36
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.install (/tools/cli/default-npm-deps.js:27:27)
    at Command.func (/tools/cli/commands.js:754:36)
    at /tools/cli/main.js:1483:23
_______________________________________________________________________

Then when i run the app for the first time it gives me this one
_______________________________________________________________________
=> Started proxy.
=> Started MongoDB.
W20170831-18:46:39.481(-7)? (STDERR) /Users/tomasdms/Dropbox (Freedeo)/code/meteor/test-app/.meteor/local/build/programs/server/boot.js:391
W20170831-18:46:39.558(-7)? (STDERR) }).run();
W20170831-18:46:39.559(-7)? (STDERR)    ^
W20170831-18:46:39.560(-7)? (STDERR)
W20170831-18:46:39.561(-7)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules
W20170831-18:46:39.561(-7)? (STDERR) directory. Please run the following command to install it:
W20170831-18:46:39.562(-7)? (STDERR)
W20170831-18:46:39.562(-7)? (STDERR)   meteor npm install --save babel-runtime
W20170831-18:46:39.563(-7)? (STDERR)
W20170831-18:46:39.564(-7)? (STDERR)     at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:35:9)
W20170831-18:46:39.564(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170831-18:46:39.565(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170831-18:46:39.565(-7)? (STDERR)     at packages/babel-runtime.js:142:15
W20170831-18:46:39.566(-7)? (STDERR)     at packages/babel-runtime.js:153:3
W20170831-18:46:39.567(-7)? (STDERR)     at /Users/tomasdms/Dropbox (Freedeo)/code/meteor/test-app/.meteor/local/build/programs/server/boot.js:338:34
W20170831-18:46:39.567(-7)? (STDERR)     at Array.forEach (native)
W20170831-18:46:39.568(-7)? (STDERR)     at Function._.each._.forEach (/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170831-18:46:39.569(-7)? (STDERR)     at /Users/tomasdms/Dropbox (Freedeo)/code/meteor/test-app/.meteor/local/build/programs/server/boot.js:158:5
W20170831-18:46:39.570(-7)? (STDERR)     at /Users/tomasdms/Dropbox (Freedeo)/code/meteor/test-app/.meteor/local/build/programs/server/boot.js:387:5
=> Exited with code: 1

______________________________________________________________________

When i run the suggested meteor npm install --save babel-runtime
(or any meteor npm command)
________________________________________________________________________

meteor npm install --save babel-runtime
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:19:21
    at Object.<anonymous> (/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.1.gda7tv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:92:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

____________________________________________________________________________

If i run> 
npm install --save babel-runtime 
it does work, and then the app does start next time i run meteor.

any ideas?

**Comment by abernix** [comment]
Does `/Users/tomasdms/.meteor/packages/meteor-tool/1.5.1/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/unsupported.js` exist on your machine?

Does this happen when you create a project in a different directory, which isn't your `Dropbox (Freedo)` directory?

And was this the first version of Meteor that you experienced this error or has it happened in the past?

**Comment by tomasdms** [comment]
Yes the file unsupported.js file exist.
it happens in any directory.
i never had any previous version of meteor i'm new at this.

**Comment by tomasdms** [comment]
I also notice that if i create do metero create test --release 1.5.1 there is no error.

**Comment by hwillson** [comment]
@tomasdms Is this still happening when you try creating a new project with the latest version of Meteor (1.5.2.2 as of today)?

**Comment by christianheyn** [comment]
I got an error like this.
My problem was that a npm package was installed as devDependencie instead of dependencie.

Just switching the package from devDependencies to dependencies in package.json solves the problem for me.

**Comment by hwillson** [comment]
Since we haven't heard back regarding the additional details asked in https://github.com/meteor/meteor/issues/9053#issuecomment-337279158, I'll close this off. Thanks!

**Comment by tomasdms** [comment]
Sorry, it took me so long to reply
I still get the error

Here's what i get when i run "meteor create foo"

`$ meteor create foo
/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.2_2.1p1zdhc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: /Users/tomasdms/.meteor/packages/meteor-tool/.1.5.2_2.1p1zdhc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm install
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/tomasdms/.meteor/packages/meteor-tool/.1.5.2_2.1p1zdhc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:19:21
    at Object.<anonymous> (/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.2_2.1p1zdhc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:92:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/tomasdms/.meteor/packages/meteor-tool/.1.5.2_2.1p1zdhc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:19:21
    at Object.<anonymous> (/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.2_2.1p1zdhc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:92:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

    at Object.error (/tools/utils/buildmessage.js:430:11)
    at /tools/cli/default-npm-deps.js:32:20
    at /tools/utils/buildmessage.js:334:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:333:36
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.install (/tools/cli/default-npm-deps.js:27:27)
    at Command.func (/tools/cli/commands.js:754:36)
    at /tools/cli/main.js:1483:23`

**Comment by tomasdms** [comment]
and this is when i try to run meteor npm 
`$ meteor npm install moment
module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/tomasdms/.meteor/packages/meteor-tool/.1.5.2_2.1p1zdhc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:19:21
    at Object.<anonymous> (/Users/tomasdms/.meteor/packages/meteor-tool/.1.5.2_2.1p1zdhc++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm:92:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)`

**Comment by juvyc** [comment]
Hi, we encountered the same issue on the latest meteor version. Any solution?

Here's the error displays on the screen.

 at require (internal/module.js:11:18)
e_modules/meteor/bower/bower/node_modules/bower/node_modules/graceful-fs/graceful-fs.js:3:27)
   at Module.load (module.js:531:32)
s/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
   at tryModuleLoad (module.js:494:12)
   at Function.Module._load (module.js:486:3)
   at Module.require (module.js:556:17)
   at require (internal/module.js:11:18)
   at Object.require (/tools/isobuild/bundler.js:1906:22)
   at packages/bower/plugin/bower.js:1:1   at <runJavaScript-26>:38:4
   at <runJavaScript-26>:326:3

**Comment by abernix** [comment]
Please follow https://github.com/meteor/meteor/issues/9310#issuecomment-342494463 for more information.
