### ISSUE TITLE
Meteor fails to install packages dependencies when auth is required

### ISSUE THREAD

**Issue by plitex** [meteor/meteor#9057]
I'm using Nexus repository manager as a proxy and some private packages. You must be logged to install packages. It looks everything is working ok until I start the app and meteor tries to install npm dependencies for some packages.

Meteor: 1.4.4.3
OS: macOS Sierra 10.12.6

Here is the error:

```
[[[[[ ~/app ]]]]]

=> Started proxy.                             
=> Meteor 1.5.1 is available. Update this project with 'meteor update'.
private-packages:services: updating npm dependencies -- microtime...
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While building package private-packages:services:
   error: couldn't install npm package microtime@2.1.1: Command failed: /Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm install
   microtime@2.1.1
   npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /Users/plitex/.npm/_logs/2017-09-04T16_17_18_377Z-debug.log
   npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.
   
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /Users/plitex/.npm/_logs/2017-09-04T16_17_18_377Z-debug.log
   
   
=> Your application has errors. Waiting for file change.

```
If I install the same package that gave the error using the meteor tool it works:

```
> $ meteor npm install microtime@2.1.1                                                                                                                                                                       
> microtime@2.1.1 install /Users/plitex/app/node_modules/microtime
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/microtime/src/microtime.o
  SOLINK_MODULE(target) Release/microtime.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
meteor-main-app@ /Users/plitex/app
└── microtime@2.1.1 
```

```
# ~/.npmrc

always-auth=true
registry=https://packages-its.nexus.local/repository/npm/
//packages-its.nexus.local/repository/npm/:_authToken=9999999999
```
Thanks for your help!

**Comment by abernix** [comment]
Does it work if you login via `meteor npm login` first?

**Comment by plitex** [comment]
Same issue:

```
plitex@machine ~/app                                        [10:44:59]
> $ meteor npm login
Username: plitex
Password:
Email: (this IS public) plitex@mydomain.com
Logged in as plitex on https://packages-its.nexus.local/repository/npm/.

plitex@machine ~/app                                        [10:45:17]
> $ meteor

[[[[[ ~/app ]]]]]

=> Started proxy.
=> Meteor 1.5.1 is available. Update this project with 'meteor update'.
private-packages:services: updating npm dependencies -- microtime...
=> Started MongoDB.
=> Errors prevented startup:

   While building package private-packages:services:
   error: couldn't install npm package microtime@2.1.1: Command failed:
   /Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
   install microtime@2.1.1
   npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

   npm ERR! A complete log of this run can be found in:
   npm ERR!     /Users/plitex/.npm/_logs/2017-09-05T08_46_36_849Z-debug.log
   npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

   npm ERR! A complete log of this run can be found in:
   npm ERR!     /Users/plitex/.npm/_logs/2017-09-05T08_46_36_849Z-debug.log


=> Your application has errors. Waiting for file change.
```

Debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
1 verbose cli   '/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm',
1 verbose cli   'install',
1 verbose cli   'microtime@2.1.1' ]
2 info using npm@4.5.0
3 info using node@v4.8.3
4 warn invalid config loglevel="notice"
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData microtime@2.1.1
9 silly fetchNamedPackageData microtime
10 silly mapToRegistry name microtime
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://packages-its.nexus.local/repository/npm/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'microtime',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'microtime',
13 silly mapToRegistry   name: 'microtime',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://packages-its.nexus.local/repository/npm/microtime
15 verbose request uri https://packages-its.nexus.local/repository/npm/microtime
16 verbose request always-auth set; sending authorization
17 info attempt registry request try #1 at 10:45:26 AM
18 info retry will retry, error on last attempt: Error: This request requires auth credentials. Run `npm login` and repeat the request.
19 info attempt registry request try #2 at 10:45:36 AM
20 info retry will retry, error on last attempt: Error: This request requires auth credentials. Run `npm login` and repeat the request.
21 info attempt registry request try #3 at 10:46:36 AM
22 silly fetchPackageMetaData Error: This request requires auth credentials. Run `npm login` and repeat the request.
22 silly fetchPackageMetaData     at CachingRegistryClient.authify (/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/authify.js:17:14)
22 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:116:17)
22 silly fetchPackageMetaData     at /Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:68:17
22 silly fetchPackageMetaData     at RetryOperation._fn (/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:18:5)
22 silly fetchPackageMetaData     at null._onTimeout (/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/retry/lib/retry_operation.js:68:10)
22 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:92:15)
22 silly fetchPackageMetaData  error for microtime@2.1.1 [Error: This request requires auth credentials. Run `npm login` and repeat the request.]
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: This request requires auth credentials. Run `npm login` and repeat the request.
27 verbose stack     at CachingRegistryClient.authify (/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/authify.js:17:14)
27 verbose stack     at CachingRegistryClient.makeRequest (/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:116:17)
27 verbose stack     at /Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:68:17
27 verbose stack     at RetryOperation._fn (/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:18:5)
27 verbose stack     at null._onTimeout (/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/retry/lib/retry_operation.js:68:10)
27 verbose stack     at Timer.listOnTimeout (timers.js:92:15)
28 verbose cwd /Users/plitex/app/node_modules/@private-packages/services/.npm/package-new-glur09
29 verbose Darwin 16.7.0
30 verbose argv "/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install" "microtime@2.1.1"
31 verbose node v4.8.3
32 verbose npm  v4.5.0
33 error This request requires auth credentials. Run `npm login` and repeat the request.
34 verbose exit [ 1, true ]
```

NPM Config:

```
> $ meteor npm config ls                                                                                                                                                                               ⬡ 8.4.0 [±227-update-project-structure ✓]
; cli configs
metrics-registry = "https://packages-its.nexus.local/repository/npm/"
scope = ""
user-agent = "npm/4.5.0 node/v4.8.3 darwin x64"

; environment configs
cache = "/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/.npm"
no-update-notifier = true
prefix = "/Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle"

; userconfig /Users/plitex/.npmrc
@dorna-its:registry = "https://packages-its.nexus.local/repository/npm/"
always-auth = true
cafile = "/Users/plitex/.npm-cafile"
package-lock = false
registry = "https://packages-its.nexus.local/repository/npm/"

; node bin location = /Users/plitex/.meteor/packages/meteor-tool/.1.4.4_3.1v0cc9b++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node
; cwd = /Users/plitex/app
; HOME = /Users/plitex
; "npm config ls -l" to show all defaults.
```

**Comment by hwillson** [comment]
@plitex I don't have access to Nexus to verify this, but have you tried the approach they've outlined here: http://blog.sonatype.com/using-nexus-3-as-your-repository-part-2-npm-packages

It looks like they're by-passing the need to login by adding a `_auth=YWRtaW46YWRtaW4xMjM=` credential hash to the registry URL.

**Comment by hwillson** [comment]
Please try the suggestions mentioned in https://github.com/meteor/meteor/issues/9057#issuecomment-348477119, and post back if you're still encountering problems. Thanks!

**Comment by plitex** [comment]
I have updated to Nexus v3.6 and Meteor v1.6 and it's fixed! I really don't know if it was a bug, I didn't have time to look for it. 

Thank you guys for your help!
