### ISSUE TITLE
[SOLVED] 1.5.2: Cordova [Error: spawn EACCES] [HELP]

### ISSUE THREAD

**Issue by fullhdpixel** [meteor/meteor#9073]
When building my Meteor Cordova this error occurs. It only happens for the Cordova app.

If you need a reproduction let me know, but I think this is something you can help with without a reproduction. Below the log is the cordova-plugin list

```
=> Errors executing Cordova commands:         
                                              
   While running Cordova app for platform Android with options --device:
   Error: Command failed:                     
   /Users/fullhdpixel/Projects/MyRoutes/.meteor/local/cordova-build/platforms/android/cordova/run
   --device
   { [Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
   'Error: spawn EACCES\n    at exports._errnoException (util.js:907:11)\n
   at ChildProcess.spawn (internal/child_process.js:315:11)\n    at
   Object.exports.spawn (child_process.js:365:9)\n    at exports.spawn
   (/Users/fullhdpixel/Projects/MyRoutes/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:134:31)\n
   at GradleBuilder.runGradleWrapper
   (/Users/fullhdpixel/Projects/MyRoutes/.meteor/local/cordova-build/platforms/android/cordova/lib/builders/GradleBuilder.js:78:14)\n
   at
   /Users/fullhdpixel/Projects/MyRoutes/.meteor/local/cordova-build/platforms/android/cordova/lib/builders/GradleBuilder.js:178:21\n
   at _fulfilled
   (/Users/fullhdpixel/Projects/MyRoutes/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:854:54)\n
   at self.promiseDispatch.done
   (/Users/fullhdpixel/Projects/MyRoutes/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:883:30)\n
   at Promise.promise.promiseDispatch
   (/Users/fullhdpixel/Projects/MyRoutes/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:816:13)\n
   at
   /Users/fullhdpixel/Projects/MyRoutes/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:570:49'
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
   => awaited here:
   at Function.Promise.await
   (/Users/fullhdpixel/.meteor/packages/templating-compiler/.1.3.2.1ljtiv3++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.run$ (/tools/cordova/project.js:261:10)
   at tryCatch
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at GeneratorFunctionPrototype.invoke [as _invoke]
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:337:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at tryCatch
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:63:40)
   at invoke
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:139:20)
   at
   /Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:184:11
   at callInvokeWithMethodAndArg
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:183:16)
   at AsyncIterator.enqueue
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:206:13)
   at AsyncIterator.prototype.(anonymous function) [as next]
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:96:21)
   at Object.runtime.async
   (/Users/fullhdpixel/.meteor/packages/meteor-tool/.1.5.2.167b85w++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/regenerator-runtime/runtime.js:226:14)
   at
   /Users/fullhdpixel/.meteor/packages/templating-compiler/.1.3.2.1ljtiv3++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:32:39
                                              
/Users/fullhdpixel/.meteor/packages/templating-compiler/.1.3.2.1ljtiv3++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
    at Function.Promise.await (/Users/fullhdpixel/.meteor/packages/templating-compiler/.1.3.2.1ljtiv3++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
    at /tools/cordova/runner.js:98:17
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at CordovaRunner.startRunTargets (/tools/cordova/runner.js:97:37)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:772:21)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:885:28)
    at /tools/runners/run-app.js:412:12
```

> cordova-custom-config@4.0.2
> cordova-plugin-crosswalk-webview@2.3.0
> cordova-plugin-device@1.1.6
> cordova-plugin-file@4.3.3
> cordova-plugin-geolocation@2.4.3
> cordova-plugin-inappbrowser@1.7.1
> cordova-plugin-meteor-webapp@1.4.2
> cordova-plugin-splashscreen@4.0.3
> cordova-plugin-statusbar@2.2.3
> cordova-plugin-tts@0.2.3
> cordova-plugin-wkwebview-engine@1.1.3
> cordova-plugin-x-socialsharing@5.2.0
> cordova-universal-links-plugin@1.2.1
> cordova-plugin-console@1.0.7
> cordova-plugin-flurryanalytics@1.4.3
>

**Comment by teknologist** [comment]
@fullhdpixel Running into this too. Did you get it solved ? Thanks.

**Comment by teknologist** [comment]
@fullhdpixel FYI I solved the issue by uninstalling the whole android sdk and reinstalling (through Android Studio)

**Comment by fullhdpixel** [comment]
Downgraded to 1.5.1 instead. Thanks for your solution

**Comment by fullhdpixel** [comment]
Just reinstalled every SDK I had installed but it didnt help

**Comment by fullhdpixel** [comment]
Still same issue also with Meteor 1.6

**Comment by fullhdpixel** [comment]
Finally fixed:

1. Change permission on gradle file.

```
chmod 755 /Applications/Android Studio 2.4 Preview.app/Contents/gradle/gradle-3.4.1/bin/gradle
```
2. Make sure gradle file is good

```
/Users/<username>/.gradle/wrapper/dists/gradle-3.3-all/
```

**Comment by Jayuda** [comment]
Thanks @fullhdpixel 
755 not work
`chmod 755 /Applications/Android Studio 2.4 Preview.app/Contents/gradle/gradle-3.4.1/bin/gradle`

777 work well
`chmod 777 /Applications/Android Studio 2.4 Preview.app/Contents/gradle/gradle-3.4.1/bin/gradle`

is it save ? thx

**Comment by esebececerril** [comment]
fullhdpixel thx

**Comment by prasannavsa** [comment]
Thanks you, Its worked for me.

**Comment by trackq** [comment]
sudo chmod -R 777 /Applications/Android\ Studio.app

**Comment by Gudvit** [comment]
it does not work for me 
https://monosnap.com/file/FLe6RWqukU4cuTnLhkWtDUmpM477vd

**Comment by elmagodeozzzo** [comment]
This work for me, thxs Gudvit
sudo chmod -R 777 /Applications/Android\ Studio.app

**Comment by thanhlevu** [comment]
thanks elmagodeozzzo, but i get more error, (MACBOOK)

ANDROID_HOME=/Users/thath/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
Subproject Path: CordovaLib
shell.js: internal error
Error: EACCES: permission denied, open '/Users/thath/Desktop/fixIt/platforms/android/gradle/wrapper/gradle-wrapper.properties'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object._sed (/Users/thath/Desktop/fixIt/platforms/android/cordova/node_modules/shelljs/src/sed.js:39:8)
    at Object.sed (/Users/thath/Desktop/fixIt/platforms/android/cordova/node_modules/shelljs/src/common.js:186:23)
    at /Users/thath/Desktop/fixIt/platforms/android/cordova/lib/builders/GradleBuilder.js:205:15
    at _fulfilled (/Users/thath/Desktop/fixIt/platforms/android/cordova/node_modules/q/q.js:854:54)
    at /Users/thath/Desktop/fixIt/platforms/android/cordova/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/thath/Desktop/fixIt/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/thath/Desktop/fixIt/platforms/android/cordova/node_modules/q/q.js:624:44
    at runSingle (/Users/thath/Desktop/fixIt/platforms/android/cordova/node_modules/q/q.js:137:13)
[ERROR] An error occurred while running subprocess cordova.

        cordova run android exited with exit code 1.

**Comment by crim1991** [comment]
sudo chgrp -R www-data node_modules
sudo chmod -R ug+rwx node_modules
