### ISSUE TITLE
Meteor 1.4.4.3 unable to build fibers

### ISSUE THREAD

**Issue by eroji** [meteor/meteor#9089]
I have 2 build machines, one of which is currently being used and builds the application without issue running on CentOS 6 with node 0.10.42 and npm 1.3.6 (EPEL). The new machine is also CentOS 6 but with the latest node LTS 6.11.3 and npm 3.10.10 (Nodesource). Everything is installed correctly on the new machine from what I can tell and the full suite of Development Tools is also present. However, whenever I attempt to build the application, when it gets to fibers@1.0.8, the build fails on the new machine completely, while it works fine on the old. Both machines are running Meteor 1.4.4.3. Downgrading node/npm on the new machine allows the build to complete, so it seems to be a compatibility issue between newer node and fibers?

Full error below:
```
> fibers@1.0.8 install /tmp/build/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/tmp/build/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from /home/build/.node-gyp/6.11.3/include/node/node.h:42,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/build/.node-gyp/6.11.3/include/node/v8.h:345: error: expected unqualified-id before 'using'
/home/build/.node-gyp/6.11.3/include/node/v8.h: In constructor 'v8::MaybeLocal<T>::MaybeLocal()':
/home/build/.node-gyp/6.11.3/include/node/v8.h:362: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::IsEmpty() const':
/home/build/.node-gyp/6.11.3/include/node/v8.h:369: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: In member function 'bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const':
/home/build/.node-gyp/6.11.3/include/node/v8.h:373: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: In member function 'bool v8::WeakCallbackInfo<T>::IsFirstPass() const':
/home/build/.node-gyp/6.11.3/include/node/v8.h:441: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: At global scope:
/home/build/.node-gyp/6.11.3/include/node/v8.h:481: error: expected unqualified-id before 'using'
/home/build/.node-gyp/6.11.3/include/node/v8.h: In constructor 'v8::Global<T>::Global()':
/home/build/.node-gyp/6.11.3/include/node/v8.h:820: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: In constructor 'v8::Global<T>::Global(v8::Global<T>&&)':
/home/build/.node-gyp/6.11.3/include/node/v8.h:845: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: In member function 'v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)':
/home/build/.node-gyp/6.11.3/include/node/v8.h:857: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: At global scope:
/home/build/.node-gyp/6.11.3/include/node/v8.h:882: error: expected unqualified-id before 'using'
/home/build/.node-gyp/6.11.3/include/node/v8.h:1119: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h:1125: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: In member function 'v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const':
/home/build/.node-gyp/6.11.3/include/node/v8.h:3279: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: At global scope:
/home/build/.node-gyp/6.11.3/include/node/v8.h:4499: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h:4515: error: 'nullptr' was not declared in this scope
/home/build/.node-gyp/6.11.3/include/node/v8.h: In member function 'v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()':
/home/build/.node-gyp/6.11.3/include/node/v8.h:7544: error: 'nullptr' was not declared in this scope
../src/fibers.cc: At global scope:
../src/fibers.cc:40: error: 'Handle' has not been declared
../src/fibers.cc:40: error: expected ',' or '...' before '<' token
../src/fibers.cc: In function 'void uni::Reset(v8::Isolate*, v8::Persistent<T, v8::NonCopyablePersistentTraits<T> >&, int)':
../src/fibers.cc:41: error: 'handle' was not declared in this scope
../src/fibers.cc: At global scope:
../src/fibers.cc:63: error: variable or field 'SetInternalPointer' declared void
../src/fibers.cc:63: error: 'Handle' was not declared in this scope
../src/fibers.cc:63: error: expected primary-expression before '>' token
../src/fibers.cc:63: error: 'handle' was not declared in this scope
../src/fibers.cc:63: error: expected primary-expression before 'int'
../src/fibers.cc:63: error: expected primary-expression before 'void'
../src/fibers.cc:67: error: template declaration of 'void* uni::GetInternalPointer'
../src/fibers.cc:67: error: 'Handle' was not declared in this scope
../src/fibers.cc:67: error: expected primary-expression before '>' token
../src/fibers.cc:67: error: 'handle' was not declared in this scope
../src/fibers.cc:67: error: expected primary-expression before 'int'
../src/fibers.cc:72: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:77: error: variable or field 'Return' declared void
../src/fibers.cc:77: error: 'Handle' was not declared in this scope
../src/fibers.cc:77: error: expected primary-expression before '>' token
../src/fibers.cc:77: error: 'handle' was not declared in this scope
../src/fibers.cc:77: error: expected primary-expression before 'const'
../src/fibers.cc:81: error: variable or field 'Return' declared void
../src/fibers.cc:81: error: 'Handle' was not declared in this scope
../src/fibers.cc:81: error: expected primary-expression before '>' token
../src/fibers.cc:81: error: 'handle' was not declared in this scope
../src/fibers.cc:81: error: expected primary-expression before 'info'
../src/fibers.cc:89: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:93: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:97: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:101: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:105: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:109: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:113: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:117: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:127: error: expected constructor, destructor, or type conversion before '<' token
../src/fibers.cc:309: error: expected ';' before '(' token
../src/fibers.cc:315: error: expected ';' before 'Fiber'
../src/fibers.cc:315: error: expected ')' before '<' token
../src/fibers.cc:581: error: ISO C++ forbids declaration of 'Handle' with no type
../src/fibers.cc:581: error: expected ';' before '<' token
../src/fibers.cc:823: error: expected ';' at end of input
../src/fibers.cc:823: error: expected '}' at end of input
../src/fibers.cc: In static member function 'static void Fiber::DestroyOrphans()':
../src/fibers.cc:396: error: 'Deref' is not a member of 'uni'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::New(const uni::Arguments&)':
../src/fibers.cc:418: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:418: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:418: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:420: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:420: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:420: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:422: error: 'Handle' was not declared in this scope
../src/fibers.cc:422: error: expected primary-expression before '>' token
../src/fibers.cc:422: error: 'argv' was not declared in this scope
../src/fibers.cc:423: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:423: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:426: error: 'Handle' was not declared in this scope
../src/fibers.cc:426: error: expected primary-expression before '>' token
../src/fibers.cc:426: error: 'fn' was not declared in this scope
../src/fibers.cc:426: error: expected primary-expression before '>' token
../src/fibers.cc:426: error: '::Cast' has not been declared
../src/fibers.cc:427: error: 'GetCurrentContext' is not a member of 'uni'
../src/fibers.cc:428: error: no matching function for call to 'Return(v8::Local<v8::Object>, const v8::FunctionCallbackInfo<v8::Value>&)'
../src/fibers.cc:428: error: return-statement with a value, in function returning 'void'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Run(const uni::Arguments&)':
../src/fibers.cc:436: error: 'Unwrap' was not declared in this scope
../src/fibers.cc:442: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:442: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:442: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:444: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:444: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:444: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:452: error: 'RunFiber' was not declared in this scope
../src/fibers.cc:455: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:455: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:455: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:465: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Local<v8::Value>)'
../src/fibers.cc:467: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:471: error: 'class Fiber' has no member named 'ReturnYielded'
../src/fibers.cc:471: error: return-statement with a value, in function returning 'void'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::ThrowInto(const uni::Arguments&)':
../src/fibers.cc:478: error: 'Unwrap' was not declared in this scope
../src/fibers.cc:481: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:481: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:481: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:483: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:485: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Local<v8::Value>)'
../src/fibers.cc:487: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:487: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:487: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:491: error: 'class Fiber' has no member named 'ReturnYielded'
../src/fibers.cc:491: error: return-statement with a value, in function returning 'void'
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::Reset(const uni::Arguments&)':
../src/fibers.cc:499: error: 'Unwrap' was not declared in this scope
../src/fibers.cc:502: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc:502: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:504: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:504: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:504: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:506: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:506: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:506: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:514: error: 'Handle' was not declared in this scope
../src/fibers.cc:514: error: expected primary-expression before '>' token
../src/fibers.cc:514: error: 'val' was not declared in this scope
../src/fibers.cc:514: error: 'Deref' is not a member of 'uni'
../src/fibers.cc:517: error: 'ThrowException' is not a member of 'uni'
../src/fibers.cc:517: error: return-statement with a value, in function returning 'void'
../src/fibers.cc:519: error: return-statement with a value, in function returning 'void'
../src/fibers.cc: In member function 'void Fiber::UnwindStack()':
../src/fibers.cc:536: error: 'Handle' was not declared in this scope
../src/fibers.cc:536: error: expected primary-expression before '>' token
../src/fibers.cc:536: error: 'NewLatin1String' is not a member of 'uni'
../src/fibers.cc:537: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&)'
../src/fibers.cc:538: error: no matching function for call to 'Reset(v8::Isolate*&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&, v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >&)'
../src/fibers.cc:551: error: 'Undefined' is not a member of 'uni'
../src/fibers.cc: At global scope:
../src/fibers.cc:576: error: expected unqualified-id at end of input
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/tmp/build/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 2.6.32-696.3.2.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /tmp/build/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
Build failed
sh: nodejs: command not found
meteor-dev-bundle@0.0.0 /tmp/build/bundle/programs/server
+-- amdefine@1.0.0 
+-- ansi-regex@0.2.1 
+-- ansi-styles@1.1.0 
+-- asap@2.0.3 
+-- escape-string-regexp@1.0.5 
+-- has-ansi@0.1.0 
+-- meteor-promise@0.5.1 
+-- promise@7.0.4 
+-- semver@4.1.0 
+-- source-map@0.1.32 
+-- source-map-support@0.3.2 
+-- strip-ansi@0.3.0 
+-- supports-color@0.2.0 
+-- type-of@2.0.1 
`-- underscore@1.5.2 

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 2.6.32-696.3.2.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.8 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build/bundle/programs/server/npm-debug.log
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
unbuild ansi-regex@0.2.1
unbuild ansi-styles@1.1.0
unbuild escape-string-regexp@1.0.5
unbuild type-of@2.0.1
unbuild has-ansi@0.1.0
unbuild strip-ansi@0.3.0
unbuild supports-color@0.2.0
~
```

**Comment by hwillson** [comment]
Hi @eroji - Meteor 1.4.4.3 should use Node 4.x (ideally Node 4.8.3, the last version it was tested with). It will not work with Node 6. Thanks!
