### ISSUE TITLE
babel-runtime outdated in Meteor 1.6-beta.30

### ISSUE THREAD

**Issue by nacimgoura** [meteor/meteor#9108]
Hello, 
I encounter a bug.
The version of Meteor showing the problem : Meteor 1.6-beta.30
The last version of Meteor where the problem did _not_ occur : Meteor 1.6-beta.27
The operating system you're running Meteor on : Ubuntu 16.04.3

Hi, since I updated meteor to the latest beta version, I have this error when I run the program: 
```
W20170919-09:09:00.537(2)? (STDERR) /home/ngoura/Documents/projet/nacim/.meteor/local/build/programs/server/boot.js:441
W20170919-09:09:00.538(2)? (STDERR) }).run();
W20170919-09:09:00.538(2)? (STDERR)    ^
W20170919-09:09:00.538(2)? (STDERR) 
W20170919-09:09:00.538(2)? (STDERR) Error: The version of babel-runtime installed in your node_modules directory 
W20170919-09:09:00.538(2)? (STDERR) (6.26.0) is out of date. Please upgrade it by running 
W20170919-09:09:00.539(2)? (STDERR) 
W20170919-09:09:00.539(2)? (STDERR)   meteor npm install --save babel-runtime@next
W20170919-09:09:00.539(2)? (STDERR) 
W20170919-09:09:00.539(2)? (STDERR) in your application directory.
W20170919-09:09:00.540(2)? (STDERR) 
W20170919-09:09:00.540(2)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:46:9)
W20170919-09:09:00.540(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170919-09:09:00.540(2)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170919-09:09:00.540(2)? (STDERR)     at packages/babel-runtime.js:155:15
W20170919-09:09:00.541(2)? (STDERR)     at packages/babel-runtime.js:166:3
W20170919-09:09:00.541(2)? (STDERR)     at infos.forEach.info (/home/ngoura/Documents/projet/nacim/.meteor/local/build/programs/server/boot.js:388:13)
W20170919-09:09:00.541(2)? (STDERR)     at Array.forEach (<anonymous>)
W20170919-09:09:00.541(2)? (STDERR)     at /home/ngoura/Documents/projet/nacim/.meteor/local/build/programs/server/boot.js:387:9
W20170919-09:09:00.541(2)? (STDERR)     at /home/ngoura/Documents/projet/nacim/.meteor/local/build/programs/server/boot.js:437:5
W20170919-09:09:00.542(2)? (STDERR)     at Function.run (/home/ngoura/Documents/projet/nacim/.meteor/local/build/programs/server/profile.js:510:12)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```
But in the npm dependencies I already have the latest version of babel-runtime (6.26.0).
I have installed the dependencies again but always the same error.

**Comment by janowsiany** [comment]
`babel-runtime@6.26.0` is not the `next` version. Just follow the instruction in the log and you will find out that the `next` is `7.0.0-beta.0`
