### ISSUE TITLE
Extracted archive X should only contain one entry

### ISSUE THREAD

**Issue by dossorio** [meteor/meteor#9146]
I have been facing this issue since I started working with meteor, in different occasions and always when running commands that altered the installed packages. I am using meteor on Windows as you see in the error trace. The most annoying thing is, and that's why I can't give you steps to reproduce, that it doesn't always happen and sometimes it just vanishes after running the same command several times. I also tried what is suggested here https://github.com/meteor/meteor/issues/7686 without success.

In this occasion, I get it after running `meteor update`:
```
R:\app>meteor update
This project is already at Meteor 1.5.2.1, the latest release.
C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.2_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: Extracted archive '/C/Users/User/AppData/Local/Temp/.tmpzgx7tb' should only contain one entry
    at Object.files.extractTarGz (C:\tools\fs\files.js:762:11)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)
    at C:\tools\packaging\tropohouse.js:505:42
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:502:24
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.2_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:469:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at C:\tools\utils\buildmessage.js:572:21
    at C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.2_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:43:39
 => awaited here:
    at Promise.await (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.5.2_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:604:6)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:609:18)
    at C:\tools\project-context.js:816:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:815:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:814:13)
    at C:\tools\project-context.js:285:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:275:18)
    at C:\tools\project-context.js:267:12
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.js:266:13)
    at C:\tools\cli\commands-packages.js:1818:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:271:29)
    at Command.func (C:\tools\cli\commands-packages.js:1797:8)
    at C:\tools\cli\main.js:1483:23
```

I digged into the code, and the exception is thrown [here](https://github.com/meteor/meteor/blob/971d2b1272bd2b769d6e55cf1fa0efdd4498625b/tools/fs/files.js#L763) when extracting packages to a randomly named temporary folder, which is expected to only contain a file / folder inside. 

Does anyone know why my temp folder can contain more that one thing inside?

**Comment by dossorio** [comment]
Just in case it helps I am getting the same error randomly now when running `meteor remove accounts-password`

**Comment by dossorio** [comment]
I faced this issue again, when running the project with `meteor.bat --settings settings.json` and some dependencies needed to be updated.

I am not sure if this fixed it or it was just a matter of randomness of the function in question but it worked the second time I run:
- `rmdir /s /q "c:\Users\YOUR_USER_HERE\AppData\Local\Temp\"`

**Comment by richnicholls404** [comment]
I think this is to do with the max file location limit in Windows. Very deep nested npm dependencies seem to litter the `c:\Users\YOUR_USER_HERE\AppData\Local\Temp\.meteor` directory, and cannot be removed or updated, so updating meteor can't change meteor's internal dependencies. I think, anyway.

My only solution has been to uninstall Meteor, remove the .meteor directory (which often involves moving some of the nested directories to a shallower location so they can be deleted on Windows - manual process) and then reinstall.

**Comment by dossorio** [comment]
This pr aims to fix this issue https://github.com/meteor/meteor/pull/9344
In short, the exception is thrown because `readdir` returns files that were already successfully deleted after the extraction process with `7z.exe` which are not expected to exist anymore.

This fix aims to mitigate the problem this problem, which is also discussed here https://github.com/nodejs/node/issues/4760#issuecomment-173174694 and https://github.com/nodejs/node-v0.x-archive/issues/7176

**Comment by ehsankhfr** [comment]
@dossorio Thanks for the fix! It really worked well on my windows 10 machine. 

@abernix @dossorio We should push this solution forward!

**Comment by hwillson** [comment]
If anyone is interested in continuing the work that was started to address this (PR https://github.com/meteor/meteor/pull/9344), please post back and let us know. Closing for now since this issue is not that common. Thanks!

**Comment by antoninadert** [comment]
I just got this issue now. 

What should I do? Please re-open

**Comment by antoninadert** [comment]
I got it again. Please help reopen.

**Comment by antoninadert** [comment]
No answer. Bump. Please reopen. Problem persist. 

I will create a new issue by end of day if you don't...

**Comment by DavidRHulme** [comment]
It seems this is due to anti virus scanning software such as McAfee. I suggest people try disabling it on their machines.

**Comment by antoninadert** [comment]
Or try to run the command with powershell which seems to work

**Comment by antoninadert** [comment]
I cannot even do it on Powershell anymore... Seems entirely due to McAffee indeed. At my work we can't disable it..
