### ISSUE TITLE
meteor idle CPU usage has been climbing build to build (1.5.2.2 & 1.6 up by 10-20X compared to 1.4.0.1)

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9175]
I have noticed that my idle CPU was relatively high on v1.6.  Also, #8803 was morphing from high CPU usage during build to high Idle CPU usage.

I thought I could take a look at the idle cpu usage on previous builds and see if I could find anything.  And yes, I found 2 points where it jumped: 1.4.2.7 & 1.5.2.2

### Environment
- Windows 10 1703 (OS Build 15063.608)
- Meteor Multiple versions, See Results

### Repro
1. clone [simple todos](https://github.com/meteor/simple-todos)
2. update to a version
2. build it
3. stick 4 todos into the DB (not sure this matters)
4. observe CPU usage in idle state.

### Results
| Meteor Version | Node Idle CPU Usage |
| ---------- | ---------- |
| 1.4.2.3 and earlier | < 0.5% |
| 1.4.2.7 - 1.5.2 | < 5.0%, varies from 1.5% - 4.5%, typical <3.5% |
|1.5.2.1 | failed build |
| 1.5.2.2 | > 9% |

I did not look closely at 1.6 builds.  But 1.6-rc.3 clocks in at > 7.5%.  I think that Node 8+ may have a little more efficiency than node 4.

### Expected
Maybe a little increase in CPU usage but not 10-20X.  Maybe even better CPU usage on v1.6.

**Comment by benjamn** [comment]
This is probably because we use `fs.watchFile` to watch files on Windows, which uses `fs.stat`-based polling, which means every watched file gets `fs.stat`-ed every 500ms by default. This is more frequent than other platforms, because there's no other file watching mechanism we can reliably use.

Can you try a quick experiment? You can change the polling interval to something longer by setting `METEOR_WATCH_POLLING_INTERVAL_MS` to something greater than 500. It would be useful to know how different values (1000, 2000, ...) affect idle CPU usage.

The big caveat is that you never know where in the interval you are when you first change a file, so it could take up to `METEOR_WATCH_POLLING_INTERVAL_MS` milliseconds to detect the change.

So my question to you is: **How long are you willing to wait for changes to be detected the first time you edit a file, in order to reduce CPU usage by your desired amount?** For example, if setting the interval to 1000ms cuts the CPU usage in half (??), would you be happy waiting a whole second? I suspect there's a sweet spot somewhere along this curve. Bonus points if you feel like plotting a graph and making this decision using data!

**Comment by brucejo75** [comment]
@benjamn, thanks for the quick response.

I did some tests on 1.5.2.2 with varying the Polling interval with METEOR_WATCH_POLLING_INTERVAL_MS.

| Polling Interval | Node Idle CPU Usage |
| ---------- | ---------- |
| 500 ms| >9% peaks at 11-12% |
| 1000 ms | < 6.0%, varies from 5.5% - 6.0%, typical 6.0% |
| 2000 ms |  >1.5% <4%|
| 5000 ms | typical 0%, can peak a little over 2% |

Indeed making changes to the polling interval does affect CPU usage significantly and nearly linearly.

Couple of questions:
1. None of these values is as good as meteor 1.4.0.1.  Did something significant change since that time?
2. For this test project; I think less than 10 files should be getting monitored.  Why is it taking up that much CPU?
3. While I am running the test, I have 4 instances of VS Code running that are monitoring changes in 1000's of files and it is barely registering a blip?  Maybe there is a way other than polling to detect changes?

I found these files in the VSCode watcher, maybe it will provide clues to an event based watcher?
[watcherService.ts](https://github.com/Microsoft/vscode/blob/release/1.17/src/vs/workbench/services/files/node/watcher/win32/watcherService.ts)
[csharpWatcherService.ts](https://github.com/Microsoft/vscode/blob/release/1.17/src/vs/workbench/services/files/node/watcher/win32/csharpWatcherService.ts)

(It would take me a while to grok what is going on in there...)

**Comment by benjamn** [comment]
Thanks for the data, @brucejo75!

After thinking about this some more, I think we can eliminate the idle CPU usage by watching unchanged files at the 5000ms interval. After a file is changed for the first time, we can promote it to a shorter interval (500ms) and attempt to start a native file watcher.

We already do this on Unix platforms in order to conserve file descriptors by not starting unnecessary native file watchers, but I think it could help on Windows too, since by default we poll every file every 500ms on Windows.

**Comment by brettg2** [comment]
@benjamn is there no way to get file system change events or is polling the only solution?

**Comment by benjamn** [comment]
@brettg2 We use both when possible! Note: that's been true all along for Unix platforms, though native file watchers will be enabled for Windows starting with Meteor 1.6 (0679e7a8bf796fdefef2fa8fd13685b8edf40a90).

**Comment by benjamn** [comment]
This should be fixed in the latest 1.6 release candidate(s): `meteor update --release 1.6-rc.6`

Note that you may have to wait a few seconds for changes to be detected the first time you change a file, but subsequent changes should be instantaneous.

**Comment by benjamn** [comment]
@abernix @hwillson Should we back-port this to Meteor 1.5.3?

**Comment by hwillson** [comment]
@benjamn Yes, I think so. Even with the 1.6 release coming soon (🤞), I'm sure there will be several people that can't make the 1.5.x to 1.6 leap for a bit, that would still benefit from seeing this added to 1.5.3.

**Comment by brettg2** [comment]
@benjamn my current build is on ubuntu and poll still pushes cpu to 40% every 2-3 secs? Does native watch do this?

**Comment by brettg2** [comment]
@brucejo75 no, this was our private build with 300+ template, component and library files. Each poll will take half second at 40-50% pulling back to 0% for 2-3 seconds then repeats

**Comment by brucejo75** [comment]
Interesting.  I also see the CPU jump to (~2.5%) then to 0% for my larger project.  Which is fine for me.

@benjamn, do you start all the poll timers at the same time?  Is it possible to skew their start so the poll is more spread out in time?  e.g. skew could be 5000ms/# files.

Maybe this may have the potential to mess up the dependency graph if 2 files change at near the same time?

**Comment by brucejo75** [comment]
sorry, did not mean to close.

**Comment by SnooHD** [comment]
I recently upgraded my CPU to an i5, which on 1.6-rc5 ran between 30-40%.
Now on 1.6-rc6 it runs between 0-10%.
I am very satisfied! :+1:  Thanks a ton!

**Comment by brettg2** [comment]
@benjamn @brucejo75 I am trying to update to 1.6-rc6 but getting some errors:

```
meteor update --release 1.6-rc.6
...\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.6\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: ENOENT: no such file or directory, stat '.\acorn\bin\acorn'
    at Object.fs.statSync (fs.js:955:11)
    at Object.wrapper (C:\tools\fs\files.js:1594:35)
    at Object.files.(anonymous function) [as stat] (C:\tools\fs\files.js:1729:27)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:727:17)
    at optimisticReaddir.forEach.item (C:\tools\isobuild\builder.js:554:11)
    at Array.forEach (<anonymous>)
    at walk (C:\tools\isobuild\builder.js:462:34)
    at optimisticReaddir.forEach.item (C:\tools\isobuild\builder.js:551:11)
    at Array.forEach (<anonymous>)
    at walk (C:\tools\isobuild\builder.js:462:34)
    at Builder.copyDirectory (C:\tools\isobuild\builder.js:589:5)
    at _.each (C:\tools\isobuild\isopack.js:1450:17)
    at Function._.each._.forEach (C:\Users\Dev\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.6\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at Isopack.saveToPath (C:\tools\isobuild\isopack.js:1449:9)
    at exports.Tropohouse._saveIsopack (C:\tools\packaging\tropohouse.js:337:15)
    at buildmessage.enterJob (C:\tools\packaging\tropohouse.js:526:16)
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:613:18
    at enterJobAsync.then (C:\tools\utils\buildmessage.js:572:21)
    at C:\Users\Dev\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.6\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:43:40
 => awaited here:
    at Promise.await (C:\Users\Dev\AppData\Local\.meteor\packages\meteor-tool\1.6.0-rc.6\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at Object.forkJoin (C:\tools\utils\buildmessage.js:567:10)
    at exports.Tropohouse.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:609:18)
    at C:\tools\project-context.js:814:25
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:813:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:812:13)
    at C:\tools\project-context.js:285:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:275:18)
    at Profile.run (C:\tools\project-context.js:267:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:266:13)
    at C:\tools\cli\commands-packages.js:1610:20
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1609:8)
    at Command.func (C:\tools\cli\commands-packages.js:1683:29)
    at C:\tools\cli\main.js:1491:23
```

**Comment by brettg2** [comment]
@benjamn @brucejo75 I tried reinstalling Meteor and updating to rc6 and got these errors:

```
meteor update --release 1.6-rc.6
C:\Users\Dev\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/Dev/AppData/Local/.meteor/packages/meteor-tool/1.6.0-rc.6
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:901:13)
    at C:\tools\packaging\tropohouse.js:521:21
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Dev\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:520:13
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:515:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:427:20)
    at C:\tools\packaging\tropohouse.js:600:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:597:20)
    at C:\tools\cli\main.js:462:30
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at C:\tools\cli\main.js:461:17
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at C:\tools\cli\main.js:459:33
    at Console.withProgressDisplayVisible (C:\tools\console\console.js:619:14)
    at springboard (C:\tools\cli\main.js:458:11)
    at C:\tools\cli\main.js:1126:5
```

... the difference being something about isopack?

**Comment by brucejo75** [comment]
@brettg2,

What OS are you on?

Try these steps:
1.  go to a non-project folder.
2. `meteor --help --release 1.6-rc.6` This will download all the build data for release 1.6-rc.6.
3. Make sure all your editors are closed
4. go to your project folder and run `meteor update --release 1.6-rc.6`

If it does, take a look at [this](https://forums.meteor.com/t/10x-build-speed-improvement/37429).

Let me know if that works.

**Comment by benjamn** [comment]
I think we've solved the CPU issue as much as we can for Meteor 1.6. The CPU spikes @brettg2 is still seeing are consistent with watching _lots_ of files with a 5-second polling interval. Although 50% CPU usage is noticeable, it's not 100%, and the `stat` polling happens asynchronously (not in one huge block), so it shouldn't be blocking other events. Also, just to be clear, file watching is something that only happens in development, so this is not a production problem.

**Comment by brettg2** [comment]
@brucejo75 I am running Windows 7 with Ubuntu VM. The errors above were from compiling on 7 but doing the same on Linux works fine. I had another developer try it on Windows 10 and that looks good, although much slower downloading/extracting meteor-tool and other packages versus Ubuntu/Linux.

**Comment by brucejo75** [comment]
@brettg2,

The slowness of downloads on windows is typically the AntiMalware job.  Look at Task Manager while doing a download.  For every file that meteor brings down, the scanner checks for viruses.  Ubuntu/Linux do not give you that protection by default.

For me, I take the hit on downloads from the web.  But I disable scanning for my development drive.  Meteor produces 1000's of files in a build and none really need to be checked.

Doing the [multi-step update](https://github.com/meteor/meteor/issues/9175#issuecomment-336230792) really helps reduce issues.

**Comment by brettg2** [comment]
@brucejo75 thanks for the tips to get the rc up and running. I am currently running 1.6-rc.18. Here is my current idle cpu and memory load:

![image](https://user-images.githubusercontent.com/6796960/32125667-4f8eeb12-bb2a-11e7-88e3-49925f88d489.png)

**Comment by brucejo75** [comment]
Sorry @brettg2, all my experiences are with stock Windows not using the Linux VM.

**Comment by brettg2** [comment]
@brucejo75 same with me. Stock windows or stock Linux, either way my machine is a space heater with this code running idle.

**Comment by brucejo75** [comment]
I am running Windows 10 without any CPU issues. 

Can you run some experiments just loading the todos app like I did [here](https://github.com/meteor/meteor/issues/9175#issuecomment-335197615)?

Then play with the `METEOR_WATCH_POLLING_INTERVAL_MS`?  This will isolate your issue and make sure you do not have a project specific problem...
