### ISSUE TITLE
Latest version cannot deploy/build due to CoffeeScript error

### ISSUE THREAD

**Issue by TheRealNate** [meteor/meteor#9217]
Trying to deploy to Galaxy. Error:

```
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/coffeescript-compiler/node_modules/source-map/lib/source-map-generator.js:276:15:
original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated
position. If so, pass null for the original mapping instead of an object with empty or null values.
at SourceMapGenerator_validateMapping
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/coffeescript-compiler/node_modules/source-map/lib/source-map-generator.js:276:15)
at SourceMapGenerator_addMapping
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/coffeescript-compiler/node_modules/source-map/lib/source-map-generator.js:110:12)
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/coffeescript-compiler/node_modules/source-map/lib/source-map-generator.js:72:17
at Array.forEach (native)
at SourceMapConsumer_eachMapping
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/coffeescript-compiler/node_modules/source-map/lib/source-map-consumer.js:157:14)
at Function.SourceMapGenerator_fromSourceMap
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/coffeescript-compiler/node_modules/source-map/lib/source-map-generator.js:48:24)
at CoffeeScriptCompiler.compileOneFile (packages/coffeescript-compiler/coffeescript-compiler.js:92:40)
at CachedCoffeeScriptCompiler.compileOneFile (packages/compile-coffeescript/compile-coffeescript.js:31:38)
at packages/caching-compiler/caching-compiler.js:299:32
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
at packages/caching-compiler/caching-compiler.js:316:9
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
at Object.async.forEachLimit.async.eachLimit
(/home/ubuntu/.meteor/packages/coffeescript/.1.12.7_2.6mk04s++os+web.browser+web.cordova/plugin.compile-coffeescript.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
at CachedCoffeeScriptCompiler.processFilesForTarget (packages/caching-compiler/caching-compiler.js:284:11)
```

I tried to fix it by doing:
`sudo rm -rf node_modules/`
`sudo rm -rf ~/.meteor/packages/coffeescript`
`sudo rm -rf ~/.meteor/packages/caching-compiler`
`meteor reset`
`meteor update`
`meteor update coffeescript`
`meteor npm update`
`meteor npm install`
`meteor npm i -g npm`

**Comment by benjamn** [comment]
A [small reproduction](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor) would be helpful!

**Comment by TheRealNate** [comment]
Sure, I'll get a reproduction ready. Just an update, **not** updating my app appears to fix it, so it seems to be something released within the last day or two since I have recently deployed.

**Comment by benjamn** [comment]
Yes, there was a new version of `coffeescript` released today.

**Comment by benjamn** [comment]
@GeoffreyBooth We might be able to go back to `source-map@0.5.7`, since I think this validation is a new thing in `source-map@6.x`. Alternatively, if we can get a repro, we can just fix the problem directly.

**Comment by TheRealNate** [comment]
@benjamn then It was definitely the new coffeescript version, as you can see by the log it was definitely linked to coffescript.

**Comment by GeoffreyBooth** [comment]
Sure, please roll it back. 

I've been struggling with the same error in updating to 2.0.0, but I hadn't seen it in 1.12.7. I'm thinking the 2 version should use the `inputSourceMap` option in Babel rather than this custom source map merging.

**Comment by TheRealNate** [comment]
Reproduction done. Just try to build/deploy it and you'll see the error. https://github.com/TheRealNate/meteor-9217

**Comment by benjamn** [comment]
If you run `meteor update coffeescript` you should get version 1.12.7_3, which contains a fix for this problem.

**Comment by TheRealNate** [comment]
Can confirm, is resolved.

**Comment by GeoffreyBooth** [comment]
How was this not caught by the tests? They just didn’t happen to generate any source maps that failed `source-map`‘s validation?

**Comment by benjamn** [comment]
I think that’s right. For what it may be worth, Babel’s test suite fails with `source-map@6.x` in the same way.
