### ISSUE TITLE
1.6-rc.12 Cannot find module 'meteor-promise' while updating

### ISSUE THREAD

**Issue by zvictor** [meteor/meteor#9238]
The problem occurs when updating meteor to rc12.
It does not happen for rc11.

Captured in OSX 10.12.5

```js
⚡ meteor update --release 1.6-rc.12
module.js:529
    throw err;
    ^

Error: Cannot find module 'meteor-promise'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at makeCompatible (/Users/zvictor/.meteor/packages/meteor-tool/.1.6.0-rc.12.8kghc2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/install-promise.js:6:3)
    at Object.<anonymous> (/Users/zvictor/.meteor/packages/meteor-tool/.1.6.0-rc.12.8kghc2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/tool-env/install-promise.js:9:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

I tried cleaning `~/.meteor`, `project/.meteor/local` and also `project/node_modules`. None helped. Manually adding `meteor-promise` to my project also didn't help.

Searching my codebase for `meteor-promise` didn't find anything other than a reference to it as dependency of [chimp](https://chimp.readme.io/).

**Comment by benjamn** [comment]
This should be fixed if you run `meteor update 1.6-rc.13`. Sorry for the annoyance!
