### ISSUE TITLE
[1.6-rc.14] meteor npm install crashing on meteor/readable-stream

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor#9243]
Something happened in the last couple of hours.. This error is very reproducible.

### Repro
1. `git clone https://github.com/meteor/simple-todos`
2. `meteor update --release 1.6-rc.14`
3. `cd simple-todos`
4. `meteor npm install`

CRASH!  See log file below.

Reinstalling rc.14 did not help

### 2017-10-18T16_39_39_322Z-debug.log
```javascript
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Bruce\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.14\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Bruce\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.14\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.4.2
3 info using node@v8.7.0
4 verbose npm-session 9a3f88966a767902
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall simple-todos@
7 info lifecycle simple-todos@~preinstall: simple-todos@
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly fetchPackageMetaData error for readable-stream@git+https://github.com/meteor/readable-stream.git#2e9112d7d31a2af6e0682db0e18679b1e5fd4694 Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
13 silly fetchPackageMetaData C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
14 verbose stack Error: Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
14 verbose stack C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
14 verbose stack
14 verbose stack     at ChildProcess.exithandler (child_process.js:271:12)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:927:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose cwd E:\temp\simple-todos-16-rc14
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Users\\Bruce\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.14\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Bruce\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0-rc.14\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install"
18 verbose node v8.7.0
19 verbose npm  v5.4.2
20 error code 1
21 error Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
21 error C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
22 verbose exit [ 1, true ]
```

**Comment by benjamn** [comment]
https://github.com/meteor/node-stubs/issues/10

**Comment by brucejo75** [comment]
@benjamn. I see you updated [meteor/node-stubs v0.3.0](https://github.com/meteor/node-stubs/releases/tag/v0.3.0)

I changed the version in my package.json, but I still get the same error.
Do I need a new build of meteor for it to stop failing?

**Comment by brucejo75** [comment]
Note: for anyone reading this.  There is a workaround to get past this.

Instead of `meteor npm install` try `npm install` it seems to get past the error.  From there on out `meteor npm install seems to work`

**Comment by benjamn** [comment]
That's probably due to `npm` being an older version that doesn't use https://github.com/zkat/pacote. What do you get when you run `npm version`?

**Comment by brucejo75** [comment]
`npm --version`: 5.4.2

**Comment by benjamn** [comment]
Finally found a way to do this without involving `git.exe` (see https://github.com/meteor/node-stubs/commit/982f17fa5b4a2f84fc8455d13adbe5492ebe6ed5)!

**Comment by benjamn** [comment]
Well, that didn't work. Apparently you can't use `file:` in the `package.json` dependencies of published packages. Trying a totally different approach in 3…2…1…

**Comment by brucejo75** [comment]
Did the `npm install` workaround work for you?

**Comment by lmachens** [comment]
Removing the package-lock.json helped for me.

**Comment by anantonton** [comment]
> Removing the package-lock.json helped for me.

this helped for me too.

**Comment by lowesilvan** [comment]
> Removing the package-lock.json helped for me.

This worked for me as well
