### ISSUE TITLE
[1.6] Cannot find module '/Users/xxx/nfc-meteor/node_modules/google-batch/transport.js'

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#9265]
I simply updated to 1.6 and got this error when starting meteor. 1.5.2.2 works fine.

```
W20171027-16:51:44.359(-7)? (STDERR) /Users/xxx/.meteor/packages/meteor-tool/.1.6.0.1jz93gr++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171027-16:51:44.379(-7)? (STDERR)                                            throw(ex);
W20171027-16:51:44.379(-7)? (STDERR)                                            ^
W20171027-16:51:44.380(-7)? (STDERR) 
W20171027-16:51:44.380(-7)? (STDERR) Error: Cannot find module '/Users/xxx/nfc-meteor/node_modules/google-batch/transport.js'
W20171027-16:51:44.380(-7)? (STDERR)     at Function.Module._resolveFilename (module.js:513:15)
W20171027-16:51:44.380(-7)? (STDERR)     at Function.Module._load (module.js:463:25)
W20171027-16:51:44.380(-7)? (STDERR)     at Module.require (module.js:556:17)
W20171027-16:51:44.380(-7)? (STDERR)     at require (internal/module.js:11:18)
W20171027-16:51:44.380(-7)? (STDERR)     at Object.<anonymous> (/Users/xxx/nfc-meteor/node_modules/googleapis/lib/transporters.js:1:18)
W20171027-16:51:44.381(-7)? (STDERR)     at Module._compile (module.js:612:30)
W20171027-16:51:44.384(-7)? (STDERR)     at Object.Module._extensions..js (module.js:623:10)
W20171027-16:51:44.384(-7)? (STDERR)     at Module.load (module.js:531:32)
W20171027-16:51:44.384(-7)? (STDERR)     at tryModuleLoad (module.js:494:12)
W20171027-16:51:44.385(-7)? (STDERR)     at Function.Module._load (module.js:486:3)
W20171027-16:51:44.385(-7)? (STDERR)     at Module.require (module.js:556:17)
W20171027-16:51:44.385(-7)? (STDERR)     at require (internal/module.js:11:18)
W20171027-16:51:44.385(-7)? (STDERR)     at Object.<anonymous> (/Users/xxx/nfc-meteor/node_modules/googleapis/lib/generator_utils.js:54:30)
W20171027-16:51:44.385(-7)? (STDERR)     at Module._compile (module.js:612:30)
W20171027-16:51:44.386(-7)? (STDERR)     at Object.Module._extensions..js (module.js:623:10)
W20171027-16:51:44.386(-7)? (STDERR)     at Module.load (module.js:531:32)
=> Exited with code: 1
```

**Comment by WayneUong** [comment]
nvm. my mistake.
