### ISSUE TITLE
Errors while updating to Meteor 1.6 from Meteor 1.5.2.2

### ISSUE THREAD

**Issue by MartiniHenry1988** [meteor/meteor#9277]
I just updated Meteor from 1.5.2.2 to 1.6 and I am facing these errors:

```
martinihenry@martinihenry-001:~/myMeteorApp$ meteor update
This project is already at Meteor 1.6, the latest release.
npm-container: updating npm dependencies -- qr-image, gcm, bcrypt, nodemailer, nodemailer-smtp-transport, apn, esendex...
=> Errors while upgrading packages:           
                                              
While building package npm-container:
error: couldn't install npm packages from npm-shrinkwrap: Command failed:
/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install
In file included from ../node_modules/nan/nan.h:184:0,
from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../node_modules/nan/nan_maybe_43_inl.h:221:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated (declared at
/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3501): Cloning is not supported.
[-Wdeprecated-declarations]
return array->CloneElementAt(GetCurrentContext(), index);
^
In file included from ../node_modules/nan/nan_new.h:189:0,
from ../node_modules/nan/nan.h:190,
from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated (declared at
/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:4793): Pass an isolate [-Wdeprecated-declarations]
return v8::BooleanObject::New(value).As<v8::BooleanObject>();
^
In file included from ../src/bcrypt_node.cc:1:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:592:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
v8::Isolate::GCEpilogueCallback callback
^
../node_modules/nan/nan.h:592:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCEpilogueCallback callback
^
../node_modules/nan/nan.h:593:18: error: expected primary-expression before ‘gc_type_filter’
, v8::GCType gc_type_filter = v8::kGCTypeAll) {
^
../node_modules/nan/nan.h:598:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
v8::Isolate::GCEpilogueCallback callback) {
^
../node_modules/nan/nan.h:598:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCEpilogueCallback callback) {
^
../node_modules/nan/nan.h:603:20: error: variable or field ‘AddGCPrologueCallback’ declared void
v8::Isolate::GCPrologueCallback callback
^
../node_modules/nan/nan.h:603:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCPrologueCallback callback
^
../node_modules/nan/nan.h:604:18: error: expected primary-expression before ‘gc_type_filter’
, v8::GCType gc_type_filter = v8::kGCTypeAll) {
^
../node_modules/nan/nan.h:609:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
v8::Isolate::GCPrologueCallback callback) {
^
../node_modules/nan/nan.h:609:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCPrologueCallback callback) {
^
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl,
v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1939:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl,
v8::PropertyAttribute)’ is deprecated (declared at /home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3171):
Use maybe version [-Wdeprecated-declarations]
, attribute);
^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-55-generic
gyp ERR! command "/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/martinihenry/myMeteorApp/packages/npm-container/.npm/package-new-y3zuvo.k4vis/node_modules/bcrypt
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
In file included from ../node_modules/nan/nan.h:184:0,
from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../node_modules/nan/nan_maybe_43_inl.h:221:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated (declared at
/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3501): Cloning is not supported.
[-Wdeprecated-declarations]
return array->CloneElementAt(GetCurrentContext(), index);
^
In file included from ../node_modules/nan/nan_new.h:189:0,
from ../node_modules/nan/nan.h:190,
from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated (declared at
/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:4793): Pass an isolate [-Wdeprecated-declarations]
return v8::BooleanObject::New(value).As<v8::BooleanObject>();
^
In file included from ../src/bcrypt_node.cc:1:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:592:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
v8::Isolate::GCEpilogueCallback callback
^
../node_modules/nan/nan.h:592:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCEpilogueCallback callback
^
../node_modules/nan/nan.h:593:18: error: expected primary-expression before ‘gc_type_filter’
, v8::GCType gc_type_filter = v8::kGCTypeAll) {
^
../node_modules/nan/nan.h:598:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
v8::Isolate::GCEpilogueCallback callback) {
^
../node_modules/nan/nan.h:598:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCEpilogueCallback callback) {
^
../node_modules/nan/nan.h:603:20: error: variable or field ‘AddGCPrologueCallback’ declared void
v8::Isolate::GCPrologueCallback callback
^
../node_modules/nan/nan.h:603:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCPrologueCallback callback
^
../node_modules/nan/nan.h:604:18: error: expected primary-expression before ‘gc_type_filter’
, v8::GCType gc_type_filter = v8::kGCTypeAll) {
^
../node_modules/nan/nan.h:609:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
v8::Isolate::GCPrologueCallback callback) {
^
../node_modules/nan/nan.h:609:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCPrologueCallback callback) {
^
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl,
v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1939:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl,
v8::PropertyAttribute)’ is deprecated (declared at /home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:3171):
Use maybe version [-Wdeprecated-declarations]
, attribute);
^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-55-generic
gyp ERR! command "/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/martinihenry/.meteor/packages/meteor-tool/.1.6.0.1qnhime++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/martinihenry/myMeteorApp/packages/npm-container/.npm/package-new-y3zuvo.k4vis/node_modules/bcrypt
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.       

```

Is there any workaround to these errors?

**Comment by benjamn** [comment]
If I had to guess, `bcrypt@0.8.5` no longer compiles cleanly with Node 8 (V8 6.1). The latest version of [`bcrypt`](https://www.npmjs.com/package/bcrypt) appears to be 1.0.3, so maybe try using that version in `packages/npm-container/package.js`? That package has a pretty stable API, so I bet everything will still work exactly as before, despite the major version bump.

**Comment by MartiniHenry1988** [comment]
Thanks @benjamn  Updating `bcrypt` from `0.8.5` to `1.0.3` fixed it for me.
