### ISSUE TITLE
Meteor 1.6 fails to start with an error "Cannot find module '.../mini-files'"

### ISSUE THREAD

**Issue by MaximKhlobystov** [meteor/meteor#9317]
After updating Meteor to version 1.6, it fails to start. I run `meteor update` and `meteor update --all-packages`, then I start getting the following error:

```sh
W20171107-16:28:21.351(0)? (STDERR) /home/firstuser/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/boot.js:467
W20171107-16:28:21.413(0)? (STDERR) }).run();
W20171107-16:28:21.413(0)? (STDERR)    ^
W20171107-16:28:21.414(0)? (STDERR) 
W20171107-16:28:21.414(0)? (STDERR) Error: Cannot find module '/home/firstuser/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/node_modules/mini-files'
W20171107-16:28:21.415(0)? (STDERR)     at Function.Module._resolveFilename (module.js:513:15)
W20171107-16:28:21.415(0)? (STDERR)     at Function.Module._load (module.js:463:25)
W20171107-16:28:21.416(0)? (STDERR)     at Module.require (module.js:556:17)
W20171107-16:28:21.416(0)? (STDERR)     at require (internal/module.js:11:18)
W20171107-16:28:21.417(0)? (STDERR)     at Object.require (/home/firstuser/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/boot.js:283:20)
W20171107-16:28:21.417(0)? (STDERR)     at packages/4commerce_env-settings.js:30:17
W20171107-16:28:21.418(0)? (STDERR)     at packages/4commerce_env-settings.js:185:4
W20171107-16:28:21.418(0)? (STDERR)     at packages/4commerce_env-settings.js:189:4
W20171107-16:28:21.419(0)? (STDERR)     at packages/4commerce_env-settings.js:196:3
W20171107-16:28:21.419(0)? (STDERR)     at infos.forEach.info (/home/firstuser/dev/bigbluebutton/bigbluebutton-html5/.meteor/local/build/programs/server/boot.js:414:13)
=> Exited with code: 1
```

OS: Ubuntu
Node version: 8.8.1
NPM version: 5.4.2

**Comment by hwillson** [comment]
Hi @MaximKhlobystov - this is caused by the `4commerce:env-settings` package. It's [requiring `mini-files`](https://github.com/4commerce-technologies-AG/meteor-package-env-settings/blob/11b6ee152a2350c41eea97107d83f913bb6bcee9/env-settings.js#L4) like:

```js
var files = Npm.require("./mini-files");
```

To get this to work with Meteor 1.6, this line would need to be changed to:

```js
var files = Npm.require('../../mini-files.js'); 
```

That being said, relying on internal Meteor files like this is very brittle (as we can see). I wouldn't recommend doing this. You might want to open an issue in the https://github.com/4commerce-technologies-AG/meteor-package-env-settings repo about this. Thanks!
