### ISSUE TITLE
Meteor fails to run since 1.6 update on Arch (x64) (undefined:1 t)

### ISSUE THREAD

**Issue by badmark** [meteor/meteor#9336]
Updated from Meteor 1.5.2 to 1.6.0 since then cannot run a single Meteor command (create/build/etc.).

Installed via pacaur (pacaur -S meteor-js)
`meteor --version && meteor npm --version && uname -a
`
returns:

```
meteor --version && meteor npm --version && uname -a
undefined:1                                   
t
 

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/tools/fs/safe-watcher.js:15:30)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
```

Have attempted to remove local meteor folder (~/.meteor), uninstalled, reinstalled. Regardless issue still exists.

Also tried on Arch Linux workstation and ran the command 'meteor update' and received the exact same error.

(uname:  Linux PC-ARCH 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux)

**Comment by abernix** [comment]
Does the same problem occur if you install using the official installer, instead of through `pacaur`'s [`meteor-js` package](https://aur.archlinux.org/packages/meteor-js/), which is not maintained in any way by MDG?  The official installation is:

    curl https://install.meteor.com/ | sh

At first glance, that Pacaur package doesn't seem to add much value, so I'd be curious in knowing why you've decided to use that rather than our installer.  The comments on the package are rather discouraging!

**Comment by badmark** [comment]
Removed the AUR package and ran the install script, exact same error on both Arch installs. any meteor command returns this error.

**Comment by badmark** [comment]
I've removed every trace of meteor I could find, but regardless I still receive the same error.

**Comment by badmark** [comment]
So I decided to try meteor in zsh rather than bash. Meteor works. although paths are the same, something between the two broke somewhere along the way. Appears to be a pth issue as far as I can determine.

**Comment by noahsw** [comment]
Same issue here: https://circleci.com/gh/winsleague/winsleague/1002

Haven't changed a thing and all of the sudden my build fails...

**Comment by noahsw** [comment]
Even after upgrading to Meteor 1.6: https://circleci.com/gh/winsleague/winsleague/1011

**Comment by noahsw** [comment]
This is the log output:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
1 verbose cli   '/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test-app' ]
2 info using npm@5.4.2
3 info using node@v8.8.1
4 verbose run-script [ 'pretest-app', 'test-app', 'posttest-app' ]
5 info lifecycle winsleague@2.0.0~pretest-app: winsleague@2.0.0
6 info lifecycle winsleague@2.0.0~test-app: winsleague@2.0.0
7 verbose lifecycle winsleague@2.0.0~test-app: unsafe-perm in lifecycle true
8 verbose lifecycle winsleague@2.0.0~test-app: PATH: /home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/winsleague/app/node_modules/.bin:/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/.bin:/home/ubuntu/.yarn/bin:/opt/circleci/nodejs/v8.8.1/bin:/opt/google-cloud-sdk/bin:/home/ubuntu/.local/bin:/opt/ghc/8.0.2/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:/home/ubuntu/.composer/vendor/bin:/opt/circleci/.phpenv/shims:/opt/circleci/.phpenv/bin:/opt/circleci/.rvm/gems/ruby-2.2.6/bin:/opt/circleci/.rvm/gems/ruby-2.2.6@global/bin:/opt/circleci/.rvm/rubies/ruby-2.2.6/bin:/home/ubuntu/.go_workspace/bin:/usr/local/go/bin:/opt/circleci/nodejs/v8.8.1/bin:/opt/circleci/.pyenv/shims:/opt/circleci/.pyenv/bin:/opt/google-cloud-sdk/bin:/usr/local/android-sdk-linux/platform-tools:/usr/local/android-sdk-linux/tools:/usr/local/apache-maven/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/gradle-1.10/bin:/opt/circleci/.rvm/bin:/home/ubuntu/winsleague/node_modules/.bin:/opt/circleci/.rvm/bin
9 verbose lifecycle winsleague@2.0.0~test-app: CWD: /home/ubuntu/winsleague/app
10 silly lifecycle winsleague@2.0.0~test-app: Args: [ '-c',
10 silly lifecycle   'TEST_BROWSER_DRIVER=chrome meteor test --full-app --once --driver-package dispatch:mocha --port 3100' ]
11 silly lifecycle winsleague@2.0.0~test-app: Returned: code: 1  signal: null
12 info lifecycle winsleague@2.0.0~test-app: Failed to exec test-app script
13 verbose stack Error: winsleague@2.0.0 test-app: `TEST_BROWSER_DRIVER=chrome meteor test --full-app --once --driver-package dispatch:mocha --port 3100`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid winsleague@2.0.0
15 verbose cwd /home/ubuntu/winsleague/app
16 verbose Linux 3.13.0-129-generic
17 verbose argv "/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "run" "test-app"
18 verbose node v8.8.1
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error winsleague@2.0.0 test-app: `TEST_BROWSER_DRIVER=chrome meteor test --full-app --once --driver-package dispatch:mocha --port 3100`
22 error Exit status 1
23 error Failed at the winsleague@2.0.0 test-app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
