### ISSUE TITLE
1.6 breaks app that ran fine with 1.4.4.1: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by noahsw** [meteor/meteor#9348]
My master build passed just fine several weeks ago on 1.4.4.1: https://circleci.com/gh/winsleague/winsleague/1001

Last night I noticed a simple pull request wouldn't pass CI. I realized it was using the 1.6 build tool, so I tried running my master build again, without any code changes. Now that fails too: https://circleci.com/gh/winsleague/winsleague/1005

The only thing that's changed is Meteor 1.6 has shipped.

I tried upgrading my app to 1.6 but I get the same problem: https://circleci.com/gh/winsleague/winsleague/1012

This is all on Trusty 14.04. Repo: https://github.com/winsleague/winsleague

Here's the output from CircleCI:
```
TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package dispatch:mocha --port 3100

undefined:1
t
 

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/tools/fs/safe-watcher.js:15:30)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! winsleague@2.0.0 test: `TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package dispatch:mocha --port 3100`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the winsleague@2.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Output of `/home/ubuntu/winsleague/app/node_cache/_logs/2017-11-11T06_24_41_532Z-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
1 verbose cli   '/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test-app' ]
2 info using npm@5.4.2
3 info using node@v8.8.1
4 verbose run-script [ 'pretest-app', 'test-app', 'posttest-app' ]
5 info lifecycle winsleague@2.0.0~pretest-app: winsleague@2.0.0
6 info lifecycle winsleague@2.0.0~test-app: winsleague@2.0.0
7 verbose lifecycle winsleague@2.0.0~test-app: unsafe-perm in lifecycle true
8 verbose lifecycle winsleague@2.0.0~test-app: PATH: /home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/winsleague/app/node_modules/.bin:/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/.bin:/home/ubuntu/.yarn/bin:/opt/circleci/nodejs/v8.8.1/bin:/opt/google-cloud-sdk/bin:/home/ubuntu/.local/bin:/opt/ghc/8.0.2/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:/home/ubuntu/.composer/vendor/bin:/opt/circleci/.phpenv/shims:/opt/circleci/.phpenv/bin:/opt/circleci/.rvm/gems/ruby-2.2.6/bin:/opt/circleci/.rvm/gems/ruby-2.2.6@global/bin:/opt/circleci/.rvm/rubies/ruby-2.2.6/bin:/home/ubuntu/.go_workspace/bin:/usr/local/go/bin:/opt/circleci/nodejs/v8.8.1/bin:/opt/circleci/.pyenv/shims:/opt/circleci/.pyenv/bin:/opt/google-cloud-sdk/bin:/usr/local/android-sdk-linux/platform-tools:/usr/local/android-sdk-linux/tools:/usr/local/apache-maven/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/gradle-1.10/bin:/opt/circleci/.rvm/bin:/home/ubuntu/winsleague/node_modules/.bin:/opt/circleci/.rvm/bin
9 verbose lifecycle winsleague@2.0.0~test-app: CWD: /home/ubuntu/winsleague/app
10 silly lifecycle winsleague@2.0.0~test-app: Args: [ '-c',
10 silly lifecycle   'TEST_BROWSER_DRIVER=chrome meteor test --full-app --once --driver-package dispatch:mocha --port 3100' ]
11 silly lifecycle winsleague@2.0.0~test-app: Returned: code: 1  signal: null
12 info lifecycle winsleague@2.0.0~test-app: Failed to exec test-app script
13 verbose stack Error: winsleague@2.0.0 test-app: `TEST_BROWSER_DRIVER=chrome meteor test --full-app --once --driver-package dispatch:mocha --port 3100`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid winsleague@2.0.0
15 verbose cwd /home/ubuntu/winsleague/app
16 verbose Linux 3.13.0-129-generic
17 verbose argv "/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/ubuntu/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "run" "test-app"
18 verbose node v8.8.1
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error winsleague@2.0.0 test-app: `TEST_BROWSER_DRIVER=chrome meteor test --full-app --once --driver-package dispatch:mocha --port 3100`
22 error Exit status 1
23 error Failed at the winsleague@2.0.0 test-app script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Seems related to https://github.com/meteor/meteor/issues/9336

**Comment by abernix** [comment]
Any luck by switching to [`meteortesting:mocha`](https://github.com/meteortesting/meteor-mocha), its successor with a new name?

**Comment by noahsw** [comment]
Unfortunately not. And it's super weird that I can't repro this locally. It only fails in CI.

https://github.com/winsleague/winsleague/pull/406/commits/2f23c3137b35dd319645178bf0670813a30a915d

https://circleci.com/gh/winsleague/winsleague/1013

**Comment by abernix** [comment]
Closing in favor of #9395.
