### ISSUE TITLE
[1.6] Windows 10 After upgrading meteor chimp doesn`t want to work (even downgrading meteor version does not work)

### ISSUE THREAD

**Issue by claudiutraistaru** [meteor/meteor#9358]
Hello,

I am posting here , maybe someone got this working or maybe someone else has seen this:

List of installed packages:
```
accounts-base            1.4.0  A user account system
accounts-facebook        1.3.0  Login service for Facebook accounts
accounts-github          1.4.0  Login service for Github accounts

accounts-google          1.3.0  Login service for Google accounts
accounts-password        1.5.0  Password support for accounts
alanning:roles           1.2.16  Authorization package for Meteor
aldeed:collection2-core  2.0.1* Core package for aldeed:collection2
audit-argument-checks    1.0.7  Try to detect inadequate input sanitization
ddp-rate-limiter         1.0.7  The DDPRateLimiter allows users to add rate limits to DDP methods and subscriptions.
dynamic-import           0.2.0* Runtime support for Meteor 1.5 dynamic import(...) syntax
ecmascript               0.9.0  Compiler plugin that supports ES2015+ in all .js files
es5-shim                 4.6.15  Shims and polyfills to improve ECMAScript 5 support
fortawesome:fontawesome  4.7.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
fourseven:scss           4.5.4  Style with attitude. Sass and SCSS support for Meteor.js.
meteor-base              1.2.0  Packages that every Meteor app needs
mobile-experience        1.0.5  Packages for a great mobile user experience
mongo                    1.3.0  Adaptor for using MongoDB and Minimongo over DDP
msavin:mongol            4.0.1  In-App MongoDB Editor.. now with improved third party package compatibility.
react-meteor-data        0.2.15  React higher-order component for reactively tracking Meteor data
reactive-var             1.0.11  Reactive variable
service-configuration    1.0.11  Manage the configuration for third-party services
shell-server             0.3.0  Server-side component of the `meteor shell` command.
standard-minifier-css    1.3.5  Standard css minifier used with Meteor apps by default.
standard-minifier-js     2.2.0* Standard javascript minifiers used with Meteor apps by default.
static-html              1.2.2  Define static page content in .html files
themeteorchef:bert       2.1.3  A client side, multi-style alerts system for Meteor.
tracker                  1.1.3  Dependency tracker to allow reactive callbacks
twbs:bootstrap           3.3.6  The most popular front-end framework for developing responsive, mobile first projects on the web.
xolvio:backdoor          0.2.1  Runs arbitrary code on server
xolvio:cleaner           0.3.1  Gives you methods to clear your Mongo database and collections for testing purposes
```
The problem is after running:
meteor 
I run the specific chimp command:
chimp --debug --ddp=http://localhost:3000 --mocha --path=tests
This is the ouptut I am seeing:
chimp  --debug --ddp=http://localhost:3000 --mocha --path=tests
```
(node:27176) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu

Chimp version:  0.50.2
ChromeDriver version:  ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f)
Java version:  java version "1.8.0_141", Java(TM) SE Runtime Environment (build 1.8.0_141-b15), Java HotSpot(TM) Client VM (build 25.141-b15, mixed mode, sharing)
Selenium version:  3.0.1
Selenium drivers version:  chrome: 2.28, ie: 3.0.0, firefox: 0.13.0
OS version:  Windows_NT 10.0.15063
Node version:  v9.1.0
Browser version:  chrome 61.0.3163.100


[chimp] Running...


[16:35:32]  COMMAND     GET      "/wd/hub/status"
[16:35:32]  DATA                {}
[16:35:32]  RESULT              {"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Windows NT","version":"10.0.15063"}}
[16:35:32]  COMMAND     POST     "/wd/hub/session"
[16:35:32]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","platform":"ANY","name
":"","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.9.8","name":"webdriverio"}}}
[16:35:34]  INFO        SET SESSION ID c027156f227977930e1dca015aba0c6a
[16:35:34]  RESULT              {"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.33.506120 (e3e53
437346286c0bc2d2dc9aa4915ba81d9023f)","userDataDir":"C:\\Users\\<User>\\AppData\\Local\\Temp\\scoped_dir42052_28934"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasT
ouchScreen":false,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platform
":"Windows NT","rotatable":false,"setWindowRect":true,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"61.0.3163.100","webStorageEnabled":true}
  Main
    1) clean database


  0 passing (2s)
  1 failing

  1) Main clean database:
     Uncaught Error: [chimp] You need to install xolvio:backdoor in your meteor app before you can use server.execute()
      at Object.ddpInstance.execute (C:\Users\<User>\AppData\Roaming\npm\node_modules\chimp\dist\lib\chimp-helper.js:209:19)
      at Context.<anonymous> (D:/work/app/tests/!runfirst.js:11:10)
      at C:\Users\<User>\AppData\Roaming\npm\node_modules\chimp\dist\lib\utils\fiberize.js:29:22



Mocha failed
```
On my windows machine deleting and uninstalling any reinstalling latest node and meteor did not solved anything. I got the same error on windows:
    Uncaught Error: [chimp] You need to install xolvio:backdoor in your meteor app before you can use server.execute()
but clearely the package is installed.

Thank you and let me know if you need something else or other details and most important if you can replicate this issue (I will pot to chimp Issue tracker if needed )

**Comment by claudiutraistaru** [comment]
Hi,

I have isolated the issue as it seems in the directory .meteor/local/build/programs/server/packages the below files are missing and never get built when running meteor on windows.

 xolvio_backdoor.js
xolvio_backdoor.js.map
xolvio_cleaner.js
xolvio_cleaner.js.map
Can anybody help me understand why those packages are not built ? If someone can point me to the right direction I would appreciate it.

On the same machine , using bash for linux with meteor installed , just running meteor gets the packages./iles built and I can run after this on cmd meteor , everything is ok after this , but I want to find out why those files are missing when I run meteor on cmd only , not bash.

Thank you

**Comment by abernix** [comment]
What happens if you remove the entire `.meteor/local/build` directory within your application and try running again?  How about if you try removing and adding the `xolvio:backdoor` package again?  Any messages?

    meteor remove xolvio:backdoor
    meteor add xolvio:backdoor

Those packages are quite old, but I was able to install them into a Meteor 1.6 application on a Windows Server 2012 box.

**Comment by claudiutraistaru** [comment]
Hi abernix,

Already tried that :).
I am on the right path now by using : pushplaybang:backdoor-testonly  and starting meteor with 
``` meteor test --full-app --driver-package tmeasday:acceptance-test-driver ```
The issue seem to dissapear  and chimp runs ok , I am still searching for a way to reset database with xolvio cleaner as my first test gave an error that it can be ran only in development mode.
