### ISSUE TITLE
[1.6] - Ubuntu - meteor build giving different results

### ISSUE THREAD

**Issue by Batistleman** [meteor/meteor#9363]
This might be a duplicate of #9269 

When deploying to an Ubuntu installation I get the following error: 

```
3601 verbose lifecycle fibers@2.0.0~install: unsafe-perm in lifecycle false
3602 verbose lifecycle fibers@2.0.0~install: PATH: /opt/nodejs/lib/node_modules/npm/bin/node-gyp-bin:/opt/azumuta/tmp/bundle/programs/server/node_modules/fibers/node_modules/.bin:/opt/azumuta/tmp/bundle/programs/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
3603 verbose lifecycle fibers@2.0.0~install: CWD: /opt/azumuta/tmp/bundle/programs/server/node_modules/fibers
3604 silly lifecycle fibers@2.0.0~install: Args: [ '-c', 'node build.js || nodejs build.js' ]
3605 info lifecycle fibers@2.0.0~install: Failed to exec install script
3606 verbose unlock done using /home/antobase/.npm/_locks/staging-797d83c2a7937db9.lock for /opt/azumuta/tmp/bundle/programs/server/node_modules/.staging
3607 warn meteor-dev-bundle@0.0.0 No description
3608 warn meteor-dev-bundle@0.0.0 No repository field.
3609 warn meteor-dev-bundle@0.0.0 No license field.
3610 verbose stack Error: fibers@2.0.0 install: `node build.js || nodejs build.js`
3610 verbose stack spawn ENOENT
3610 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
3610 verbose stack     at emitTwo (events.js:125:13)
3610 verbose stack     at ChildProcess.emit (events.js:213:7)
3610 verbose stack     at maybeClose (internal/child_process.js:927:16)
3610 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3611 verbose pkgid fibers@2.0.0
3612 verbose cwd /opt/azumuta/tmp/bundle/programs/server
3613 verbose Linux 3.13.0-43-generic
3614 verbose argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install"
3615 verbose node v8.8.1
3616 verbose npm  v5.5.1
3617 error file sh
3618 error code ELIFECYCLE
3619 error errno ENOENT
3620 error syscall spawn
3621 error fibers@2.0.0 install: `node build.js || nodejs build.js`
3621 error spawn ENOENT
3622 error Failed at the fibers@2.0.0 install script.
3622 error This is probably not a problem with npm. There is likely additional logging output above.
3623 verbose exit [ 1, true ]
```

The install script outputs: 

```
e you are using a supported platform and node version. If you
	would like to compile fibers on this machine please make sure you have setup your
	build environment--
	Windows + OS X instructions here: https://github.com/nodejs/node-gyp
	Ubuntu users please run: `sudo apt-get install g++ build-essential`
	Alpine users please run: `sudo apk add python make g++`
	sh: 1: nodejs: not found
	npm WARN meteor-dev-bundle@0.0.0 No description
	npm WARN meteor-dev-bundle@0.0.0 No repository field.
	npm WARN meteor-dev-bundle@0.0.0 No license field.

	npm ERR! file sh
	npm ERR! code ELIFECYCLE
	npm ERR! errno ENOENT
	npm ERR! syscall spawn
	npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
	npm ERR! spawn ENOENT
	npm ERR!
	npm ERR! Failed at the fibers@2.0.0 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/antobase/.npm/_logs/2017-11-14T07_20_07_724Z-debug.log

```

But _sudo apt-get install g++ build-essential_ does not solve the problem (already installed)

Any ideas on how I can debug this further?

**Comment by Batistleman** [comment]
Installing it manually doesn't give any problems: 

```
~> npm install -g fibers

> fibers@2.0.0 install /opt/nodejs/lib/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
make: Entering directory `/opt/nodejs/lib/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/opt/nodejs/lib/node_modules/fibers/build'
Installed in `/opt/nodejs/lib/node_modules/fibers/bin/linux-x64-57/fibers.node`
+ fibers@2.0.0
added 1 package in 3.235s
```

**Comment by Batistleman** [comment]
This might be related to: https://github.com/peerlibrary/node-fiber-utils/issues/3

**Comment by Batistleman** [comment]
Ok, this seems like an access problem: 

```
sudo npm install -g fibers 

> fibers@2.0.0 install /opt/nodejs/lib/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/nodejs/lib/node_modules/fibers/build'
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /opt/nodejs/lib/node_modules/fibers
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/nodejs/lib/node_modules/fibers/build'
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /opt/nodejs/lib/node_modules/fibers
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@2.0.0 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

Using the _--unsafe-perm_ flag seems to work, but I'm unsure how to integrate it in the scripts. 

(Forgot to mention, I'm using mup https://github.com/M4v3R/meteor-up )

**Comment by Batistleman** [comment]
I found the _fibers_ package to be referenced in the server/package.json file. Is this correct?

> If you're trying to get meteor running and you ended up at this page you're probably doing something wrong." ... https://github.com/laverdet/node-fibers/issues/352

**Comment by Batistleman** [comment]
The fiber issue seems to be solved by doing: 

     npm config set unsafe-perm=true

(https://github.com/Microsoft/WSL/issues/14)
And by following the permissions guidelines here: https://docs.npmjs.com/getting-started/fixing-npm-permissions 

Now the next error I get is this one: 

```
> meteor-dev-bundle@0.0.0 install /opt/azumuta/tmp/bundle/programs/server
> node npm-rebuild.js

npm ERR! Invalid version: "https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/antobase/.npm/_logs/2017-11-14T13_24_29_909Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by Batistleman** [comment]
It might be related to this: https://github.com/npm/npm/issues/18722

**Comment by Batistleman** [comment]
This might actually be a problem with npm5 : https://github.com/npm/npm/issues/19006

> NPM 5 wrongly copies this version specifier into "version" field of the package.json file that is written into the node_modules folder.

**Comment by Batistleman** [comment]
After removing the npm-shrinkwrap.json file, and removing the npm/node_modules and node_modules folders I can compile locally.

```
rm npm-shrinkwrap.json`
rm -rf node_modules/*
rm -rf npm/node_modules/*
npm i
```

But I'm confused with shrinkwrap vs package-lock, and I'm not sure how I can fix the problem in the install scripts... possibly here: https://github.com/meteor/meteor/blob/4a97d0551fbbc9827ddd101b162322dc03c5905d/scripts/generate-dev-bundle.sh ?

**Comment by Batistleman** [comment]
Ok, I pinned it down to the following command giving different bundles, depending on the directory they are run in: 

     meteor build --directory ../backups/build_test --server http://localhost:3000

When I run it in one folder _A_:

    ../bundle/programs/server/npm/node_modules/babel-messages/node_modules/core-js/package.json

contains: 
```

    "type": "git",
    "url": "git+https://github.com/zloirock/core-js.git"
  },
  "scripts": {
    "grunt": "grunt",
    "lint": "eslint es5 es6 es7 stage web core fn modules",
    "observables-tests": "node tests/observables/adapter && node tests/observables/adapter-library",
    "promises-tests": "promises-aplus-tests tests/promises-aplus/adapter",
    "test": "npm run lint && npm run grunt livescript client karma:default && npm run grunt library karma:library && npm run promises-tests && npm run observables-tests && lsc tests/commonjs"
  },
  "version": "https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz"
}

```

In folder _B_ the same command results in:

    ../bundle/programs/server/npm/node_modules/babel-messages/node_modules/core-js/package.json

contains 

```
  "repository": {
    "type": "git",
    "url": "git+https://github.com/zloirock/core-js.git"
  },
  "scripts": {
    "grunt": "grunt",
    "lint": "eslint es5 es6 es7 stage web core fn modules",
    "observables-tests": "node tests/observables/adapter && node tests/observables/adapter-library",
    "promises-tests": "promises-aplus-tests tests/promises-aplus/adapter",
    "test": "npm run lint && npm run grunt livescript client karma:default && npm run grunt library karma:library && npm run promises-tests && npm run observables-tests && lsc tests/commonjs"
  },
  "version": "2.4.1"
}

```

Is there a folder I should clear?

**Comment by Batistleman** [comment]
Ok, I tracked the same files down to the _node_modules_ folders. I removed _node_modules_, did a _npm install_ and the issue is gone.

I'm going to leave this issue open, for the moderators to close, in case some warnings should be added. 
(For me, all is good now.)

**Comment by hwillson** [comment]
Thanks @Batistleman - I'll close this off. If you have any concrete ideas about what/where warnings would have been helpful, please consider opening a new feature request over in http://github.com/meteor/meteor-feature-requests.
