### ISSUE TITLE
[1.6] - Linux Mint - underscore is unstable

### ISSUE THREAD

**Issue by wemiced** [meteor/meteor#9367]
Hi,
Since update to Meteor 1.6 sometime i have an errors with underscore, it seems to not be defined on server side

when i call this Meteor method :
```
Meteor.methods({
  test: function() {
    console.log("underscore", _.find([1, 2, 3, 4, 5, 6], function(num){ return num % 2 == 0; }));
  }
})
```

i have this exception :  
```
Exception while invoking method 'test' TypeError: Cannot read property 'find' of undefined
    at DDPCommon.MethodInvocation.test (server/methods/test/test.js:3:33)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

Any idea for this issue ?

**Comment by abernix** [comment]
Do you have `underscore` as an explicitly defined package in your `.meteor/packages` file?  Are you using `meteor shell`?

**Comment by wemiced** [comment]
Yes i do, underscore is explicitly defined in the `.meteor/package` and yes i'm using `meteor shell`. underscore have a tendency to crash when i'm using `meteor shell`

**Comment by abernix** [comment]
Would you agree this is a duplicate of https://github.com/meteor/meteor/issues/9276?  If so, do you mind closing this issue? :smile:

**Comment by wemiced** [comment]
yes this is a duplicate of #9276. Thx you @abernix
