### ISSUE TITLE
How to solve out meteor-tool@1.6.0 miss err

### ISSUE THREAD

**Issue by pjhcx1992** [meteor/meteor#9377]
When I update my meteor form 1.5.1 to 1.6,then the following error occurred：
C:\Users\hcx\AppData\Local\.meteor\packages\meteor-tool\1.5.1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: missing tool for os.windows.x86_32 in meteor-tool@1.6.0
    at Error (native)
    at springboard (C:\tools\cli\main.js:491:11)
    at C:\tools\cli\main.js:1501:7

**Comment by abernix** [comment]
Can you clarify how you've done the Meteor update? Did you simply run `meteor update`? Have you used the new Chocolatey installer? http://meteor.com/install

**Comment by pjhcx1992** [comment]
I've reloaded the computer before,then I used the new Chocolatey installer to install meteor 1.6,but in my project，the meteor version was 1.5.1,so I used meteor update command, And then there's the error.

**Comment by atfera** [comment]
Using the command `meteor update --release 1.6` solved the same problem for me. Try this.

**Comment by hwillson** [comment]
@pjhcx1992 Let us know if the suggestion in https://github.com/meteor/meteor/issues/9377#issuecomment-345192462 helped. Closing for now - thanks!

**Comment by rwdietrich** [comment]
I had the same error message when updating from 1.5.1 to 1.6.1. The latter was installed by choco as an admin. So I tried the --release approach and got the following error messages:
```
>meteor update --release 1.6
=> Errors while initializing project:

While loading package angular2-compilers@0.6.6:
error: Command failed: C:\WINDOWS\system32\cmd.exe /c
C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd rebuild --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
gyp verb cli
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.8.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable
"C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe
C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp verb check python version `C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe -c
"import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir compiling against specified --nodedir dev files:
C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle
gyp verb build dir attempting to create "build" dir:
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created?
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file:
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file:
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file:
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp info spawn args [
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\.temp-y1zcfo.qwkpe\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle',
gyp info spawn args
'-Dnode_gyp_dir=C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args
'-Dmodule_root_dir=C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\.temp-y1zcfo.qwkpe\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\.temp-y1zcfo.qwkpe\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bob\AppData\Roaming\npm-cache\_logs\2017-12-27T08_30_58_105Z-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe',
gyp verb cli
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.8.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable
"C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe" in the PATH
gyp verb `which` succeeded C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe
C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp verb check python version `C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe -c
"import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir compiling against specified --nodedir dev files:
C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle
gyp verb build dir attempting to create "build" dir:
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created?
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file:
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file:
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file:
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\python\python.exe
gyp info spawn args [
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\.temp-y1zcfo.qwkpe\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle',
gyp info spawn args
'-Dnode_gyp_dir=C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args
'-Dmodule_root_dir=C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\.temp-y1zcfo.qwkpe\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args
'C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\.temp-y1zcfo.qwkpe\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Bob\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit
(C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.6.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Bob\\AppData\\Local\\.meteor\\packages\\angular2-compilers\\0.6.6\\plugin.Angular2_Compilers.os\\npm\\node_modules\\meteor\\barbatus_scss-compiler\\node_modules\\node-gyp\\bin\\node-gyp.js"
"rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
C:\Users\Bob\AppData\Local\.meteor\packages\angular2-compilers\0.6.6\plugin.Angular2_Compilers.os\npm\node_modules\meteor\barbatus_scss-compiler\node_modules\.temp-y1zcfo.qwkpe\node_modules\node-sass
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bob\AppData\Roaming\npm-cache\_logs\2017-12-27T08_30_58_105Z-debug.log
```
The process is hung (no response to ^C). Log attached.
[2017-12-27T08_30_58_105Z-debug.log](https://github.com/meteor/meteor/files/1588695/2017-12-27T08_30_58_105Z-debug.log)

**Comment by pjhcx1992** [comment]
@rwdietrich You can try to find meteor-tool@1.6.0 and delete it, then get into /.meteor/local, delete all files, and restart your meteor project, it can auto download meteor-tool@1.6.0 , if it is not useful, you may reinstall your meteor

**Comment by pjhcx1992** [comment]
@hwillson It's useful , thanks

**Comment by rwdietrich** [comment]
@pjhcx1992 I tried your suggestions to force a download of 1.6.0. It didn't seem to have any impact on the 404 for node-sass. I'll try some other approaches, but I'm not expecting success.

**Comment by abernix** [comment]
@rwdietrich The error you're receiving seems to be due to the fact that pre-compiled Node bindings to the native C/C++ Sass library haven't been published by the Node Sass project (and thus downloaded by [`node-pre-gyp`](https://github.com/mapbox/node-pre-gyp)) for Node 8 (which Meteor 1.6 uses), and your computer doesn't have the necessary toolchain to compile it on its own (which is done through the [`node-gyp` project](https://github.com/nodejs/node-gyp)).

If you install the Microsoft C++ Build Tools with the "Default" option (as per the instructions [here](http://landinghub.visualstudio.com/visual-cpp-build-tools)), you should have success in compiling them on your own machine, rather than relying on the pre-compiled binary to be downloaded by `node-pre-gyp`.

**Comment by lpatmo** [comment]
@rwdietrich Did you ever figure it out? I am getting the same error message on a Windows machine. 

```$ meteor update --release 1.6
{ Error: EPERM: operation not permitted, unlink 'C:\Users\julia\AppData\Local\Temp\mt-vy780z.07hq\npm\node_modules'
 errno: -4048,
 code: 'EPERM',
 syscall: 'unlink',
 path: 'C:\\Users\\julia\\AppData\\Local\\Temp\\mt-vy780z.07hq\\npm\\node_modules' }
=> Errors while initializing project:

While loading package fourseven:scss@3.13.0:
error: Command failed: C:\WINDOWS\system32\cmd.exe /c
C:\Users\julia\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd
rebuild --update-binary
Cannot download
"https://github.com/sass/node-sass/releases/download/v3.13.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
try setting a proxy via HTTP_PROXY, e.g.

export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

npm config set proxy http://example.com:8080```

**Comment by atfera** [comment]
@lpatmo Like @abernix  suggested , did u install the MS Build Tools ? For Windows user, u can install it via [chocolatey ](https://chocolatey.org/packages/visualstudio2017buildtools) or the link given in the previous comment.

**Comment by danilo-favoratti** [comment]
@lpatmo, I removed and added the package and it worked.

```
meteor remove  fourseven:scss
meteor add fourseven:scss
```
