### ISSUE TITLE
First run of meteor run ios-device and android-device crashes after update to Meteor 1.6

### ISSUE THREAD

**Issue by derwaldgeist** [meteor/meteor#9378]
I just updated my 1.5 app to 1.6. Have to say it went very smoothly this time, which was great. The webapp started without any issues. Never experienced such a smooth update before.

Yet, when I tried to `meteor run android-device ios-device`, the meteor tool crashed when trying to update Cordova. It's somehow related to a node module called "boom".

The second run went through successfully.

```
/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Error: couldn't install npm package cordova-common@1.5.1: Command failed: /Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm install cordova-common@1.5.1
npm WARN enoent ENOENT: no such file or directory, open '/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/package.json'
npm WARN lib No description
npm WARN lib No repository field.
npm WARN lib No README data
npm WARN lib No license field.

npm ERR! path /Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom' -> '/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waldgeist/.npm/_logs/2017-11-16T10_23_56_318Z-debug.log
npm WARN enoent ENOENT: no such file or directory, open '/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/package.json'
npm WARN lib No description
npm WARN lib No repository field.
npm WARN lib No README data
npm WARN lib No license field.

npm ERR! path /Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom' -> '/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.0.1584upa++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/node_modules/cryptiles/node_modules/boom'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waldgeist/.npm/_logs/2017-11-16T10_23_56_318Z-debug.log

    at Object.error (/tools/utils/buildmessage.js:430:11)
    at meteorNpm.installNpmModule (/tools/isobuild/meteor-npm.js:1047:20)
    at Object.keys.forEach.dep (/tools/cli/dev-bundle-helpers.js:19:21)
    at Array.forEach (<anonymous>)
    at Object.ensureDependencies (/tools/cli/dev-bundle-helpers.js:19:6)
    at buildmessage.enterJob (/tools/cordova/index.js:33:10)
    at /tools/utils/buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ensureDevBundleDependencies (/tools/cordova/index.js:27:16)
    at Command.doRunCommand [as func] (/tools/cli/commands.js:407:5)
    at /tools/cli/main.js:1522:15
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TravelGuzz@0.0.1 start: `meteor run --settings settings.json --port $npm_package_config_port --mobile-server $npm_package_config_ipaddress:$npm_package_config_port "ios-device" "android-device"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TravelGuzz@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waldgeist/.npm/_logs/2017-11-16T10_23_56_454Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by derwaldgeist** [comment]
FYI: This also happens when I updated from 1.6 to 1.6 beta 8 and did a meteor reset first.

Second run on 1.6 beta 8 failed, too, with another error:

```
/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.1-beta.8.6t0v0y.du994++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at relative (path.js:1267:5)
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:662:24)
    at ImportScanner._checkSourceAndTargetPaths (/tools/isobuild/import-scanner.js:304:31)
    at files.forEach.file (/tools/isobuild/import-scanner.js:225:12)
    at Array.forEach (<anonymous>)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:224:11)
    at sourceBatches.forEach.batch (/tools/isobuild/compiler-plugin.js:1041:15)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1012:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1057:8)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:828:12)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:819:18)
    at /tools/isobuild/bundler.js:2927:14
    at /tools/isobuild/bundler.js:3016:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/Users/waldgeist/.meteor/packages/meteor-tool/.1.6.1-beta.8.6t0v0y.du994++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:3015:7
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2908:31)
    at files.withCache (/tools/isobuild/bundler.js:2855:32)
    at Object.withCache (/tools/fs/files.js:1658:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2855:16)
    at Profile.run (/tools/runners/run-app.js:579:36)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:578:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TravelGuzz@0.0.1 start: `meteor run --settings settings.json --port $npm_package_config_port --mobile-server $npm_package_config_ipaddress:$npm_package_config_port "ios-device"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TravelGuzz@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/waldgeist/.npm/_logs/2017-11-22T13_04_00_143Z-debug.log
```

**Comment by derwaldgeist** [comment]
[2017-11-22T13_04_00_143Z-debug.log](https://github.com/meteor/meteor/files/1496037/2017-11-22T13_04_00_143Z-debug.log)

**Comment by abernix** [comment]
Is this still occurring for you with the official release of Meteor 1.6.1?

**Comment by brendonlamb** [comment]
It appears that this is  still happening in 1.6.1 - at least something similar

`Error: Error: couldn't install npm package cordova-common@2.1.1: Command failed: C:\WINDOWS\system32\cmd.exe /c C:\Users\solid\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd install cordova-common@2.1.1
npm ERR! path C:\Users\solid\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\ansistyles
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\solid\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\ansistyles' -> 'C:\Users\solid\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.`

**Comment by KoenLav** [comment]
I believe this is the same issue: https://github.com/meteor/meteor/issues/9560

Somehow Cordova common isn't properly installed on the first run.

**Comment by hwillson** [comment]
We haven't heard back regarding whether this was fixed with Meteor 1.6.1 or not, so we'll assume it was (let us know otherwise!). As for the `cordova-common` issue, let's track that in #9560. Thanks!

**Comment by brendonlamb** [comment]
:(

https://github.com/meteor/meteor/issues/9378#issuecomment-363365315

?

**Comment by hwillson** [comment]
@brendonlamb Sorry if I wasn't clear:

> As for the `cordova-common` issue, let's track that in #9560.

Let's track your issue in #9560 since it appears to be the same issue. Thanks!

**Comment by brendonlamb** [comment]
My bad, didn't see #9560 thanks!
