### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by boxxa** [meteor/meteor#9391]
Ran Meteor upgrade in a 1.5 project and now nothing starts with the error below. 

Tried meteor reset and shows the same error and even tried to remove .meteor from the project folder.
```
/Users/boxxa/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: SQLITE_BUSY: database is locked
 => awaited here:
    at Promise.await (/Users/boxxa/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at Db._execute (/tools/packaging/catalog/catalog-remote.js:341:15)
    at Txn.begin (/tools/packaging/catalog/catalog-remote.js:97:13)
    at /tools/packaging/catalog/catalog-remote.js:208:11
    at Db._serialize (/tools/packaging/catalog/catalog-remote.js:177:14)
    at Db.runInTransaction (/tools/packaging/catalog/catalog-remote.js:240:21)
    at RemoteCatalog.initialize (/tools/packaging/catalog/catalog-remote.js:722:20)
    at /tools/cli/main.js:869:20
```

**Comment by abernix** [comment]
SQLite is used for the local package cache and is shared by all running `meteor` instances.  I'd suggest making sure you don't have any other running `meteor` processes which might have a lock on the database by checking your system's process list (`ps wwax | grep meteor`, for example).

If you find nothing, perhaps try rebooting.  If there is in fact a stale lockfile for it, it will be located in your home directory in the `~/.meteor/package-metadata/v2.0.1` directory.  Maybe take a look there and report back?

**Comment by hwillson** [comment]
@boxxa If the comments in https://github.com/meteor/meteor/issues/9391#issuecomment-345666527 don't help, let us know. Closing for now - thanks!

**Comment by jmallott** [comment]
I am having the exact same problem, and I am completely flummoxed.
