### ISSUE TITLE
Chocolatey's package (v0.0.2) throws errors when creating an app on Windows 10 1607.

### ISSUE THREAD

**Issue by suazithustra** [meteor/meteor#9414]
Installed meteor's chocolatey package v0.0.2 (meteor v1.6) on Windows 10 version 1607 (build 14393.953) using "choco install meteor", install runs fine.

Getting this after using `meteor create myapp` to create an app:

```
C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property 'length' of undefined
    at new PV (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:101:23)
    at Function.PV.parse (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:111:10)
    at Function.PV.getValidServerVersion (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:291:13)
    at parseSimpleConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:278:8)
    at C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:311:14
    at Array.map (<anonymous>)
    at new PV.VersionConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:306:26)
    at Function.PV.parseVersionConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:320:10)
    at new PV.PackageConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:364:28)
    at Function.PV.parsePackageConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\packages\package-version-parser\package-version-parser.js:390:10)
    at Object.exports.parsePackageConstraint (C:\tools\utils\utils.js:242:33)
    at C:\tools\project-context.js:953:37
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at exports.ProjectConstraintsFile._readFile (C:\tools\project-context.js:930:7)
    at new exports.ProjectConstraintsFile (C:\tools\project-context.js:896:8)
    at C:\tools\project-context.js:326:37
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._readProjectMetadata (C:\tools\project-context.js:311:18)
    at C:\tools\project-context.js:285:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:275:18)
    at ProjectContext.readProjectMetadata (C:\tools\project-context.js:236:10)
    at C:\tools\cli\commands.js:768:20
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:274:29)
    at Command.func (C:\tools\cli\commands.js:767:8)
    at C:\tools\cli\main.js:1522:15
```

The app appears but when i cd into and run it with `meteor` I of course get this:

```
Problem! This project does not have a .meteor/release file. The file should either contain the release of Meteor
that you want to use, or the word 'none' if you will only use the project with unreleased checkouts of Meteor.
Please edit the .meteor/release file in the project and change it to a valid Meteor release or 'none'.
```

Meteor isn't creating the release file but it is happening after I add it manually. Tried this with and without admin privileges, makes no difference, here's the app for recreating the issue, not sure if you will be able to reproduce this but I thought this was worth sharing.

[myapp.zip](https://github.com/meteor/meteor/files/1501773/myapp.zip)

**Comment by abernix** [comment]
I don't believe this has anything to do with Chocolatey.

You said the `.meteor/release` file doesn't exist – but do any files exist in the `.meteor` directory?  From the Zipfile you've provided, it appears that there is _no_ `.meteor` directory at all, which is definitely bizarre.  Was `myapp` an already existing directory, by chance?

**Comment by suazithustra** [comment]
It was not an existing directory, I've been creating apps with different names over and over again trying to get meteor to work on windows.

I just downloaded myapp.zip from this link on a separate machine and it contains a .meteor directory with files inside, here's a screenshot.

![screenshot from 2017-11-24 22-34-00](https://user-images.githubusercontent.com/33040041/33221248-9cf7404a-d167-11e7-883e-c2e03d12d821.png)

**Comment by abernix** [comment]
Ah, you're right, `.meteor` is totally there. I was doing something funny (read: wrong) with the .zip extraction.  Sorry for the misinformation!

**Comment by suazithustra** [comment]
Just tried with `meteor create test --release 1.3` and got a release file.

But it won't run, and throws this:
```
C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.3.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:116                                       Preparing project                         -
      throw error; desktop
            ^
TypeError: Object [object Object] has no method 'createProxyServer'                                                Prepa
    at Proxy.start (C:\tools\runners\run-proxy.js:40:28)
    at Runner.start (C:\tools\runners\run-all.js:114:16)
    at Object.exports.run (C:\tools\runners\run-all.js:317:10)
```
[test.zip](https://github.com/meteor/meteor/files/1505366/test.zip)

**Comment by abernix** [comment]
Could you try Meteor 1.5.4?  Can you also try disabling any anti-virus software?  These failures seem quite unmethodical, and these versions have definitely worked, on Windows, with Meteor in the past.  Though I'd suggest trying the most recent versions of those past branches instead of their initial releases, for example:

* 1.3.5.1
* 1.4.4.4
* 1.5.4

Though realistically, 1.3.5.1 is a couple years old now and thus not actively maintained in any way.

**Comment by suazithustra** [comment]
There aren't any anti-virus applications on this machine, but I forgot to consider the fact that it is part of a network in an office and has some of its permissions/features are regulated through it. I'm sorry I didn't mention this earlier.

I will try those versions and post the results.

**Comment by suazithustra** [comment]
choco install meteor --release 1.4.4.4 -y
![2017120114160902](https://user-images.githubusercontent.com/33040041/33491115-b1436d7e-d6d2-11e7-89a9-e5bd4a2b3ec4.png)
Does this with all those versions, how can I install them using the repositories on github?

**Comment by abernix** [comment]
The way you're passing `--version` to `choco install meteor` is not the correct way since the Chocolatey version is the version of the installer, not the version of Meteor.  For more information on how to install a different version of Meteor itself, you can see [this section of the docs](https://github.com/meteor/meteor-chocolatey-installer#installing-a-specific-version-of-meteor).

With that said though, it shouldn't be necessary for you to install a different version.  You can simply create different test apps with different versions by passing the `--release` flag to `meteor create`.  For example: `meteor create --release 1.4.4.4`, and then going into the directory, running `meteor npm install`, and then `meteor`.

**Comment by suazithustra** [comment]
```
C:\Users\ZarehP\Desktop>meteor create myapp --release 1.5.4
C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property 'length' of undefined
    at new PV (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:101:22)
    at Function.PV.parse (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:111:10)
    at Function.PV.getValidServerVersion (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:291:13)
    at parseSimpleConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:278:8)
    at C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:311:14
    at Array.map (native)
    at new PV.VersionConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:306:26)
    at Function.PV.parseVersionConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:320:10)
    at new PV.PackageConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:364:28)
    at Function.PV.parsePackageConstraint (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\packages\package-version-parser\package-version-parser.js:390:10)
    at Object.exports.parsePackageConstraint (C:\tools\utils\utils.js:234:33)
    at C:\tools\project-context.js:955:37
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.5.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at [object Object]._.extend._readFile (C:\tools\project-context.js:932:7)
    at new exports.ProjectConstraintsFile (C:\tools\project-context.js:898:8)
    at C:\tools\project-context.js:326:37
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._readProjectMetadata (C:\tools\project-context.js:311:18)
    at C:\tools\project-context.js:285:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:275:18)
    at ProjectContext._.extend.readProjectMetadata (C:\tools\project-context.js:236:10)
    at C:\tools\cli\commands.js:723:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:273:29)
    at Command.func (C:\tools\cli\commands.js:722:8)
    at C:\tools\cli\main.js:1484:15
```

**Comment by suazithustra** [comment]
```
C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.4.4_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190All rights reserved.
      throw error;                                                     Preparing project                         -
      ^ows\system32>cd C:\users\zarehp

TypeError: httpProxy.createProxyServer is not a function                                                           Prepa
    at [object Object]._.extend.start (C:\tools\runners\run-proxy.js:40:28)
    at Runner.start (C:\tools\runners\run-all.js:119:16)
    at Object.exports.run (C:\tools\runners\run-all.js:322:10)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:360:17)
    at C:\tools\cli\main.js:1483:23
```

**Comment by suazithustra** [comment]
`meteor npm install` is working fine

**Comment by suazithustra** [comment]
`--release 1.3.5.1`
```
C:\Users\ZarehP\AppData\Local\.meteor\packages\meteor-tool\1.3.5_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error; dekstop\myapp                                       Preparing project                         -
            ^nnot find the path specified.
TypeError: Object [object Object] has no method 'createProxyServer'
    at Proxy.start (C:\tools\runners\run-proxy.js:40:28)                                                           Prepa
    at Runner.start (C:\tools\runners\run-all.js:117:16)
    at Object.exports.run (C:\tools\runners\run-all.js:320:10)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:351:17)
    at C:\tools\cli\main.js:1402:23
```

**Comment by suazithustra** [comment]
`choco install meteor --params="'/RELEASE 1.5.4'" -y`
```
Chocolatey v0.10.8
Installing the following packages:
meteor
By installing you accept licenses for the packages.
Progress: Downloading meteor 0.0.2... 100%

meteor v0.0.2 [Approved]
meteor package files install completed. Performing other installation steps.
Attempt to get headers for https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64&release=True failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64&release=True'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
Downloading meteor 64 bit
  from 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64&release=True'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://packages.meteor.com/bootstrap-link?arch=os.windows.x86_64&release=True'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
The install of meteor was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - meteor (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\meteor\tools\chocolateyinstall.ps1'.
 See log for details.
```
arrrrrggg

**Comment by abernix** [comment]
There was a typo in the document that I linked you to, but I've corrected it.  The flag to install a specific release should be `--params="'/RELEASE:1.5.4'"`.

This isn't a problem with the install though.  Based on the different samples you're providing, I'm convinced that this problem exists because of a conflicting Node module in some global `node_modules` directory.  Please see https://github.com/meteor/meteor/issues/8069 for a similar issue.

What's the output of the following command?:

    meteor node -p 'module.paths'

Do any of those directories returned by that command exist?  Do any of them include a `http-proxy` module?  Do you have a `node_modules` directory in your home directory or in the root of your hard drive? (i.e. `C:\node_modules\`).  If you move those directories out of the way (for example, to `node_modules.old`) does the problem go away?

**Comment by suazithustra** [comment]
`module.paths`

**Comment by suazithustra** [comment]
when i uninstall meteor, the .meteor directory disappears from `%LOCALAPPDATA%`, but after reinstalling, the directory reappears with an oooooooold date under the 'date modified' column, does that mean its going in and out of the recycle bin?????

**Comment by abernix** [comment]
It seems you might be using `cmd.exe` (Command Prompt) rather than PowerShell, thus (now I know) `meteor node -p 'module.paths'` behaves differently.  Can you try it with double quotes instead? i.e.

     meteor node -p "module.paths"

That should return a list of search paths for `node_modules`.  I'm also curious if you have anything in `%AppData%\npm`?  (Though I expect that to be included in the previous list of directories from the output of that command.)

> does that mean its going in and out of the recycle bin or is it just another silly quirk of windows?????

Must be a quirk.  The Meteor installer is certainly not smart enough to recover itself from the Recycle Bin.

**Comment by suazithustra** [comment]
```
PS C:\users\zarehp\desktop> meteor node -p 'module.paths'
[ 'C:\\users\\zarehp\\desktop\\node_modules',
  'C:\\users\\zarehp\\node_modules',
  'C:\\users\\node_modules',
  'C:\\node_modules' ]
```

`C:\Users\ZarehP\node_modules` is the only one that exists, and it does contain an `http-proxy` module.

**Comment by abernix** [comment]
You said that the steps from #8069 didn't work, but you also say that `node_modules/http-proxy` still exists.

Have you tried moving the entire `C:\Users\ZarehP\node_modules` out of the way (even temporarily) to `node_modules.old`, or completely removing the `http-proxy` folder from inside it?

**Comment by suazithustra** [comment]
Forgive me, work is frying my brains.

Deleting `http-proxy` had no effect, but renaming `node_modules` resolved everything. I appreciate your help.
