### ISSUE TITLE
[bundle-visualizer] React + Apollo + SSR: TypeError: warning is not a function

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor#9495]
I'm working on a server-side rendered react app and noticed that my page loads are very slow. I assume this is because my bundle size is way too big. I am trying to investigate with the `bundle-visualizer` package:

```
meteor --extra-packages bundle-visualizer --production
```

However, when I start up meteor using the above command, I get the following error:

```
E20171223-06:39:18.199(-5) (webapp_server.js:798) Error running template: TypeError: warning is not a function
    at new <anonymous> (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/create-react-class/factory.js:765:9)
    at walkTree (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react-apollo/react-apollo.umd.js:679:30)
    at walkTree (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react-apollo/react-apollo.umd.js:712:17)
    at walkTree (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react-apollo/react-apollo.umd.js:712:17)
    at /Users/joncursi/Sites/joncursi/redbird-web/node_modules/react-apollo/react-apollo.umd.js:723:21
    at R (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react/cjs/react.production.min.js:17:311)
    at P (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react/cjs/react.production.min.js:16:236)
    at P (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react/cjs/react.production.min.js:16:361)
    at Object.forEach (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react/cjs/react.production.min.js:19:165)
    at walkTree (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react-apollo/react-apollo.umd.js:721:28)
```

My app uses `server-render` for server-side rendering, and it looks like this error is thrown on the server side of Meteor. Any suggestions on how to overcome this? I've been scratching my head on this one for a while. Thanks!

EDIT: I'm using

```
METEOR@1.6.0.1
```

```
accounts-base@1.4.1
accounts-facebook@1.3.0
accounts-google@1.3.0
accounts-oauth@1.1.15
accounts-password@1.5.0
alanning:roles@1.2.16
aldeed:collection2-core@2.1.0
aldeed:schema-index@2.1.1
allow-deny@1.1.0
apollo@1.0.0
audit-argument-checks@1.0.7
autoupdate@1.3.12
babel-compiler@6.24.7
babel-runtime@1.1.1
base64@1.0.10
binary-heap@1.0.10
blaze-tools@1.0.10
boilerplate-generator@1.3.1
browser-policy@1.1.0
browser-policy-common@1.0.11
browser-policy-content@1.1.0
browser-policy-framing@1.1.0
bundle-visualizer@1.1.2
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
ddp@1.4.0
ddp-client@2.2.0
ddp-common@1.3.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.1
deps@1.0.12
diff-sequence@1.0.7
doctorpangloss:method-hooks@2.0.3
dynamic-import@0.2.1
ecmascript@0.9.0
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.5.0
ecmascript-runtime-server@0.5.0
ejson@1.1.0
email@1.2.3
es5-shim@4.6.15
facebook-oauth@1.4.0
gadicohen:robots-txt@0.0.10
gadicohen:sitemaps@0.0.26
geojson-utils@1.0.10
google-oauth@1.2.5
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.3.0
id-map@1.0.9
livedata@1.0.18
localstorage@1.2.0
logging@1.1.19
matb33:collection-hooks@0.8.4
meteor@1.8.2
meteor-base@1.2.0
meteorhacks:aggregate@1.3.0
meteorhacks:collection-utils@1.2.0
minifier-js@2.2.2
minimongo@1.4.3
modules@0.11.2
modules-runtime@0.9.1
mongo@1.3.1
mongo-dev-server@1.1.0
mongo-id@1.0.6
mongo-livedata@1.0.12
mys:fonts@0.0.2
nicolaslopezj:apollo-accounts@3.2.2
npm-bcrypt@0.9.3
npm-mongo@2.2.33
oauth@1.2.1
oauth2@1.2.0
ordered-dict@1.0.9
orionsoft:graphql-compiler@0.0.4
percolate:migrations@1.0.2
percolate:synced-cron@1.3.2
promise@0.10.0
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.8
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
server-render@0.2.0
service-configuration@1.0.11
sha@1.0.9
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-js@2.2.1
static-html@1.2.2
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.1
tracker@1.1.3
underscore@1.0.10
url@1.1.0
webapp@1.4.0
webapp-hashing@1.0.9
```

**Comment by joncursi** [comment]
If I turn off SSR and use `ReactDOM.render()` instead of `ReactDOM.hydrate()`, this works. So it's SSR that's the problem!

**Comment by klaussner** [comment]
Could you put together a small runnable reproduction? That would make debugging a lot easier! :smile:

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction, so I'll close this for now. I'm happy to re-open this if you're able to provide a small runnable reproduction that clearly demonstrates this issue. Thanks!
