### ISSUE TITLE
1.6.1 break packages

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor#9497]
METEOR@1.6.1-beta.21

https://github.com/rclai/meteor-collection-extensions
https://github.com/matb33/meteor-collection-hooks

```
TypeError: Class constructor Collection cannot be invoked without 'new'
W20171223-20:48:09.967(8)? (STDERR)     at new ns.Collection (packages/lai_collection-extensions.js:107:27)
W20171223-20:48:09.967(8)? (STDERR)     at autoupdate_server.js (packages/autoupdate/autoupdate_server.js:39:18)
W20171223-20:48:09.967(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20171223-20:48:09.967(8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20171223-20:48:09.968(8)? (STDERR)     at /Users/monsterstep/dev/meteor-react-router-test/.meteor/local/build/programs/server/packages/autoupdate.js:226:1
W20171223-20:48:09.968(8)? (STDERR)     at /Users/monsterstep/dev/meteor-react-router-test/.meteor/local/build/programs/server/packages/autoupdate.js:233:3
W20171223-20:48:09.968(8)? (STDERR)     at infos.forEach.info (/Users/monsterstep/dev/meteor-react-router-test/.meteor/local/build/programs/server/boot.js:415:13)
W20171223-20:48:09.968(8)? (STDERR)     at Array.forEach (<anonymous>)
W20171223-20:48:09.968(8)? (STDERR)     at /Users/monsterstep/dev/meteor-react-router-test/.meteor/local/build/programs/server/boot.js:414:9
W20171223-20:48:09.968(8)? (STDERR)     at /Users/monsterstep/dev/meteor-react-router-test/.meteor/local/build/programs/server/boot.js:468:5
W20171223-20:48:09.969(8)? (STDERR)     at Function.run (/Users/monsterstep/dev/meteor-react-router-test/.meteor/local/build/programs/server/profile.js:510:12)
W20171223-20:48:09.969(8)? (STDERR)     at /Users/monsterstep/dev/meteor-react-router-test/.meteor/local/build/programs/server/boot.js:467:11
```

https://github.com/aldeed/meteor-simple-schema

**Comment by klaussner** [comment]
This issue is already tracked in #9383. :slightly_smiling_face:
