### ISSUE TITLE
Meteor patch 1.6.0.1 breaking bug: can no longer run or add-platform android

### ISSUE THREAD

**Issue by cdcv** [meteor/meteor#9505]
In summary, (at least on my environment) if I create a new 
meteor testapp on release 1.6 everything is fine.  If I upgrade to patch 1.6.0.1, then meteor add-platform android no longer works.  

- [ ] The last version of Meteor where the problem did _not_ occur, if applicable.
1.6
- [ ] The operating system you're running Meteor on.
Mac 10.12.6
- [ ] The expected behavior.
meteor add-platform android works
- [ ] The actual behavior.
meteor add-platform android gives error.  Also, running for android-device gives error.
- [ ] A **simple** reproduction!
The steps below show the error.  See console record below.  There are a couple of extra steps (eg meteor reset) just to further clarify things.

```
➜ examples meteor create testapp --release 1.6  
Created a new Meteor app in 'testapp'.        

To run your new app:                          
  cd testapp                                  
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials            
                                              
meteor create --bare to create an empty app.  
meteor create --full to create a scaffolded app.
                                              
➜  examples cd testapp
➜  testapp meteor add-platform android
Subproject Path: CordovaLib                  |
android: added platform                       
➜  testapp meteor remove-platform android
android: removed platform                     
➜  testapp meteor reset
Project reset.                                
➜  testapp meteor add-platform android
Subproject Path: CordovaLib                  \
android: added platform                       
➜  testapp meteor update
testapp: updated to Meteor 1.6.0.1.           
Your top-level dependencies are at their latest compatible versions.
➜  testapp meteor remove-platform android
android: removed platform                     
➜  testapp meteor reset
Project reset.
➜  testapp meteor add-platform android
Subproject Path: CordovaLib                  /
=> Errors executing Cordova commands:         
                                              
While adding platform Android to Cordova project:
TypeError: cordovaProject.projectConfig.getFileResources is not a function
at updateFileResources (/Users/cdc/code/examples/testapp/.meteor/local/cordova-build/platforms/android/cordova/lib/prepare.js:408:46)
at /Users/cdc/code/examples/testapp/.meteor/local/cordova-build/platforms/android/cordova/lib/prepare.js:51:9
at _fulfilled (/Users/cdc/code/examples/testapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:854:54)
at self.promiseDispatch.done (/Users/cdc/code/examples/testapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:883:30)
at Promise.promise.promiseDispatch (/Users/cdc/code/examples/testapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:816:13)
at /Users/cdc/code/examples/testapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:624:44
at runSingle (/Users/cdc/code/examples/testapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:137:13)
at flush (/Users/cdc/code/examples/testapp/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:125:13)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)
=> awaited here:
at Function.Promise.await
(/Users/cdc/.meteor/packages/meteor-tool/.1.6.0_1.5vn9fx.pikri++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
at Promise.asyncApply (/tools/cordova/project.js:384:7)
at
/Users/cdc/.meteor/packages/meteor-tool/.1.6.0_1.5vn9fx.pikri++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
=> awaited here:
at Function.Promise.await
(/Users/cdc/.meteor/packages/meteor-tool/.1.6.0_1.5vn9fx.pikri++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
at CordovaProject.runCommands (/tools/cordova/project.js:725:14)
at CordovaProject.addPlatform (/tools/cordova/project.js:380:10)
at CordovaProject.ensurePlatformsAreSynchronized (/tools/cordova/project.js:411:12)
at main.captureAndExit (/tools/cli/commands-cordova.js:54:20)
at /tools/utils/buildmessage.js:271:13
at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:264:29
at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:262:18
at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:253:23
at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.capture (/tools/utils/buildmessage.js:252:19)
at Object.main.captureAndExit (/tools/cli/main.js:272:29)
at doAddPlatform (/tools/cli/commands-cordova.js:36:8)
at Command.func (/tools/cli/commands-cordova.js:125:3)
at /tools/cli/main.js:1522:15
```

**Comment by hwillson** [comment]
Hi @cdcv - I tried your reproduction steps and had no problem running `meteor add-platform android` with Meteor 1.6.0.1. Maybe try a Meteor re-install (`curl https://install.meteor.com/ | sh`) to cleanup your installation directory, and give things another try.

**Comment by cdcv** [comment]
Confirmed.  A meteor uninstall/reinstall restored meteor add-platform android to functioning. Not sure why this was required, but glad it's working.  Perhaps this will help some others as well. 
 Thanks.
