### ISSUE TITLE
Meteor 1.6.0.1 , meteor run with error 

### ISSUE THREAD

**Issue by andrew4alive** [meteor/meteor#9519]
OS window 10(32 bits)

fail to start meteor server with following error:

D:\desktop\meteorp\book>meteor  --port 8081
[[[[[ ~\D\desktop\meteorp\book ]]]]]

=> Started proxy.
C:\Users\Andre\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EISDIR: illegal operation on a directory, symlink 'C:\Users\Andre\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules' -> 'D:\desktop\meteorp\book\.meteor\local\.build824711.build\programs\.build45554.server\node_modules'
    at Object.fs.symlinkSync (fs.js:1014:18)
    at Object.wrapper (C:\tools\fs\files.js:1558:35)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:757:13)
    at Builder.write (C:\tools\isobuild\builder.js:265:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2471:15)
    at C:\tools\isobuild\bundler.js:2608:30
    at Object.keys.forEach.name (C:\tools\isobuild\bundler.js:2743:9)
    at Array.forEach (<anonymous>)
    at C:\tools\isobuild\bundler.js:2733:26
    at C:\tools\isobuild\bundler.js:3074:22
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2907:31)
    at files.withCache (C:\tools\isobuild\bundler.js:2854:32)
    at Object.withCache (C:\tools\fs\files.js:1658:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2854:16)
    at Profile.run (C:\tools\runners\run-app.js:579:36)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:578:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:622:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12

i try using cmd(admin) power shell, happen same error.

already re-install meteor, still have same issues.

Any ideal to solve this ?

**Comment by andrew4alive** [comment]
i able to solve this issues. 

as i understand **symlink**  cannot run on difference drive .

my installation is on c drive while my project is on d drive.

so i create my project on c drive then problem solve.

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:8081/
   Type Control-C twice to stop.

**Comment by hwillson** [comment]
Yes, symbolic links across drives can be a pain with Windows. Definitely best to avoid them when using the Meteor Tool. Thanks!
