### ISSUE TITLE
EPERM: operation not permitted on local package addition

### ISSUE THREAD

**Issue by ghost** [meteor/meteor#9540]
OS: Windows 10 64 bit

I've been trying to add a local package to my project for over a day now and I keep getting this permission denied error.
I tried everything I could google on this problem, only thing that works is a full reinstallation of Meteor, but the error comes back after a while and I have to reinstall again....
```
C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EPERM: operation not permitted, lstat 'C:\Users\Theonepotato\workspace\MeteorJS\kalender\packages\persist-collection\.npm\package-new-8xiw61.wc4s\node_modules'
    at Object.fs.lstatSync (fs.js:941:11)
    at Object.lstatSync (C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\npm\node_modules\graceful-fs\polyfills.js:297:22)
    at rimrafSync (C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\rimraf\rimraf.js:290:24)
    at C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\rimraf\rimraf.js:341:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\rimraf\rimraf.js:340:26)
    at rmdirSync (C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\rimraf\rimraf.js:333:7)
    at fixWinEPERMSync (C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\rimraf\rimraf.js:208:5)
    at Function.rimrafSync [as sync] (C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\rimraf\rimraf.js:310:28)
    at Object.files.rm_recursive.path [as rm_recursive] (C:\tools\fs\files.js:307:12)
    at Object.meteorNpm.updateDependencies (C:\tools\isobuild\meteor-npm.js:131:13)
    at Object.compile (C:\tools\isobuild\compiler.js:126:19)
    at C:\tools\isobuild\isopack-cache.js:362:30
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (C:\tools\isobuild\isopack-cache.js:317:18)
    at Profile.time (C:\tools\isobuild\isopack-cache.js:251:16)
    at Function.time (C:\tools\tool-env\profile.js:305:10)
    at C:\tools\isobuild\isopack-cache.js:250:17
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (C:\tools\isobuild\isopack-cache.js:241:20)
    at C:\tools\isobuild\isopack-cache.js:77:14
    at C:\tools\packaging\package-map.js:57:7
    at Function._.each._.forEach (C:\Users\Theonepotato\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at exports.PackageMap.eachPackage (C:\tools\packaging\package-map.js:49:7)
    at IsopackCache.buildLocalPackages (C:\tools\isobuild\isopack-cache.js:76:24)
    at C:\tools\project-context.js:847:25
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (C:\tools\project-context.js:846:18)
    at C:\tools\project-context.js:285:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:275:18)
    at Profile.run (C:\tools\project-context.js:267:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:266:13)
    at C:\tools\cli\commands-packages.js:2155:20
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Command.func (C:\tools\cli\commands-packages.js:2154:27)
    at C:\tools\cli\main.js:1522:15
```

**Comment by stumpss** [comment]
Is this guaranteed to be fixed next release? I basically can't do anything involving packages anymore, even after reinstalling Meteor now somehow.

**Comment by stumpss** [comment]
@benjamn I installed 1.6.1-rc.8, how can I use the meteor package commands using this version? It still uses 1.6.0_1.

**Comment by stumpss** [comment]
I've reregistered, that is me above just to let you know.

**Comment by stumpss** [comment]
@benjamn I've resolved my problem. My package's npm dependencies involved Github urls but I forgot to add the branch specifier at the end of the urls. Adding them stopped the error from happening.
I was stuck for a lot of time because of this error, it would be nice if Meteor checked the links for a branch specifier and gave errors relating to any missing because I would have never figured this out if I hadn't noticed this in the docs just now.

**Comment by benjamn** [comment]
Unfortunately, @ghost's stack trace confirms that my change https://github.com/meteor/meteor/commit/9e60539f113af2f6dea5b2fed5323bd27114c4ac isn't solving this problem completely, though it may be giving the `files.rm_recursive` operation a better chance of succeeding (whatever that may be worth).

@stumpss Glad to hear you found a way around your problems, anyway!

@ghost What's in the `Npm.depends` of your `kalender\packages\meteor-persist-collection\package.js` file?

**Comment by stumpss** [comment]
@benjamn I forgot to tell you that @ghost is actually me, I've reregistered. Thought you'd figure by my comment. Sorry for that.

**Comment by benjamn** [comment]
There are lots of ways to provide a URL for npm packages, and it's not always easy to tell which ones are OK and which ones won't work, just looking at the URL from the perspective of `Npm.depends`. Sorry for the trouble this has caused you, anyway!

For what it's worth, I would recommend using a tarball URL for this, so that the commit ref doesn't change depending on when you resolve it. In this case, the `master` revision would be
```
https://github.com/localForage/localForage/tarball/fc7e8e66cd02f2052f4176a60d61d5ffacfeba44
```

**Comment by hwillson** [comment]
Dropping an issue link here - this issue and https://github.com/meteor/meteor/issues/9287 are related.

**Comment by abernix** [comment]
Closing as this seems to be resolved.  Thanks, 👻 	!
