### ISSUE TITLE
Error running package tests in non-interactive mode

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#9552]
I'm trying to run package tests in my Jenkins pipeline. It runs inside a container, but I get an error like this:

```
Error: ENOENT: no such file or directory, open '/projects/edu/node_modules/@uirouter/.meteor-last-rebuild-version.json'
ERROR: Service 'barco-edu-blue' failed to build: The command '/bin/sh -c cd /projects/edu  && meteor test-packages --driver-package meteortesting:mocha' returned a non-zero code: 1
Makefile:16: recipe for target 'test' failed
make: *** [test] Error 1
```

However, If I manually log in into the container and run the same command, everything works fine. So it seems related to not running in interactive mode.

Meteor build command does work, so I'm kinda puzzled on this one.

**Comment by benjamn** [comment]
I suspect [this code](https://github.com/meteor/meteor/blob/c2845baff7b5210dbcd57f84c0111bde49a4f652/tools/isobuild/meteor-npm.js#L286) is not adequately aware of @-scoped packages like `@uirouter/actual-package`, and is instead treating `@uirouter/` as if it was a package directory.

**Comment by benjamn** [comment]
@sebakerckhof By any chance does `1.6.1-rc.9` resolve this problem for you?

**Comment by sebakerckhof** [comment]
@benjamn actually I still got the error with 1.6.1 (although now in the correct directory), but now I did have a full stack trace. And it turns out the ENOENT error is coming from the `renameDirAlmostAtomically` call here: https://github.com/meteor/meteor/blob/devel/tools/isobuild/meteor-npm.js#L395

This one falls back to a recursive copy in docker and I think I'm hitting some unionfs race condition. I had the `meteor npm install` and the `test-packages` call on different layers. If I do it on the same layer I'm not seeing this problem. Don't know if there's anything Meteor can do about it. I restructured my build now to avoid it.

```
Error: ENOENT: no such file or directory, open '/projects/edu/node_modules/@uirouter/core/.meteor-last-rebuild-version.json'
 => awaited here:
    at Promise.await (/root/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at copyFileHelper (/tools/fs/files.js:609:3)
    at Object.files.cp_r (/tools/fs/files.js:515:7)
    at files.readdir.forEach.f (/tools/fs/files.js:485:13)
    at Array.forEach (<anonymous>)
    at Object.files.cp_r (/tools/fs/files.js:472:25)
    at Object.files.renameDirAlmostAtomically.Profile [as renameDirAlmostAtomically] (/tools/fs/files.js:1006:13)
    at /tools/isobuild/meteor-npm.js:401:11
    at Array.forEach (<anonymous>)
    at Object.rebuildIfNonPortable (/tools/isobuild/meteor-npm.js:376:17)
    at NodeModulesDirectory.rebuildIfNonPortable (/tools/isobuild/bundler.js:273:22)
    at _.each.nmd (/tools/isobuild/compiler.js:654:13)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at /tools/isobuild/compiler.js:647:7
    at files.withCache (/tools/isobuild/compiler.js:181:28)
    at Object.withCache (/tools/fs/files.js:1664:12)
    at /tools/isobuild/compiler.js:180:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:175:5)
    at /tools/isobuild/bundler.js:2967:24
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2910:31)
    at files.withCache (/tools/isobuild/bundler.js:2857:32)
    at Object.withCache (/tools/fs/files.js:1664:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2857:16)
    at Profile.run (/tools/runners/run-app.js:579:36)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:578:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12
```

**Comment by NexusLee** [comment]
How to solve it? I also get this issue in docker container.

**Comment by sebakerckhof** [comment]
@NexusLee IIRC, this seemed like a race condition with unionfs and the recursive copy happening by `renameDirAlmostAtomically`. Where unionfs can't find files that are present (but it can if I added a sleep). I ended up changing our build to have `meteor npm install` and `test-packages` on the same layer.

**Comment by NexusLee** [comment]
@sebakerckhof thx for your answer. The different problem I got is when I tar meteor.tar.gz file，meteor change the name of directory and when I exec meteor command It still call the “.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova” symlink path
