### ISSUE TITLE
[1.6.1] Updating from 1.6.0.1 to 1.6.1 causes "ClassyTestCase is not defined" in peerlibrary_computed-field.js

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#9588]
```
W20180127-14:06:53.007(-8)? (STDERR) /Users/wayneuong/.meteor/packages/meteor-tool/.1.6.1.1itjirn.2v7kh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180127-14:06:53.032(-8)? (STDERR)                                            throw(ex);
W20180127-14:06:53.032(-8)? (STDERR)                                            ^
W20180127-14:06:53.032(-8)? (STDERR) 
W20180127-14:06:53.033(-8)? (STDERR) ReferenceError: ClassyTestCase is not defined
W20180127-14:06:53.033(-8)? (STDERR)     at packages/peerlibrary_computed-field.js:258:4
W20180127-14:06:53.033(-8)? (STDERR)     at packages/peerlibrary_computed-field.js:264:4
W20180127-14:06:53.033(-8)? (STDERR)     at packages/peerlibrary_computed-field.js:408:3
W20180127-14:06:53.033(-8)? (STDERR)     at /Users/wayneuong/nfc-meteor/.meteor/local/build/programs/server/boot.js:411:36
W20180127-14:06:53.033(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20180127-14:06:53.034(-8)? (STDERR)     at /Users/wayneuong/nfc-meteor/.meteor/local/build/programs/server/boot.js:220:19
W20180127-14:06:53.034(-8)? (STDERR)     at /Users/wayneuong/nfc-meteor/.meteor/local/build/programs/server/boot.js:471:5
W20180127-14:06:53.034(-8)? (STDERR)     at Function.run (/Users/wayneuong/nfc-meteor/.meteor/local/build/programs/server/profile.js:510:12)
W20180127-14:06:53.034(-8)? (STDERR)     at /Users/wayneuong/nfc-meteor/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
```

**Comment by hwillson** [comment]
This is being tracked in the `peerlibrary:computed-field` repo: https://github.com/peerlibrary/meteor-computed-field/issues/13

Until this issue has first been ruled out as not being something that needs to change on the package side, let's keep the discussion in that issue. Thanks!
