### ISSUE TITLE
Upgraded to 1.6.1 and now am getting babel related issues

### ISSUE THREAD

**Issue by ch-luke** [meteor/meteor#9597]
After the 1.6.1 update I started getting breaking errors and tried a number of babel runtime / dev settings to fix it, but it now really does not like my async/await coding style and says it doesn't understand the term "import". Any suggestions ?

```js
/Users/luke/WebstormProjects/gp-vue-master/.meteor/local/build/programs/server/app/app.js:702
  } = await import('meteor/meteor');
            ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at /Users/luke/WebstormProjects/gp-vue-master/.meteor/local/build/programs/server/boot.js:393:30
    at Array.forEach (<anonymous>)
    at /Users/luke/WebstormProjects/gp-vue-master/.meteor/local/build/programs/server/boot.js:220:19
    at /Users/luke/WebstormProjects/gp-vue-master/.meteor/local/build/programs/server/boot.js:471:5
    at Function.run (/Users/luke/WebstormProjects/gp-vue-master/.meteor/local/build/programs/server/profile.js:510:12)
    at /Users/luke/WebstormProjects/gp-vue-master/.meteor/local/build/programs/server/boot.js:470:11
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by benjamn** [comment]
Are you using a custom `.babelrc` file?

**Comment by ch-luke** [comment]
Hi, no custom .babelrc. But you can close this one - thanks for the response anyway. 

Was testing in dev mode and so could easily "meteor reset" and manually  rebuild the ".meteor/local/build/programs/server/app/app.js"- fixed it.
