### ISSUE TITLE
collection.find gives "Cannot read property 'index' of undefined"

### ISSUE THREAD

**Issue by ChuckIrvine** [meteor/meteor#9668]
Meteor: 1.6.1
Problem did not occur in 1.6.0.1 (that I know of)
Mac OS 10.13.3
 
When I invoke a find in a server method:

`Topics.find({ subjectId: topic.subjectId, _id: { $ne: topic._id } }).fetch();`

```
"TypeError: Cannot read property 'index' of undefined
    at Tarjan.strongconnect (imports/api/Topics/tarjan.js:119:13)
    at Tarjan.run (imports/api/Topics/tarjan.js:103:14)
    at findPrereqLoop (imports/api/Topics/methods.js:57:22)
    at MethodInvocation.topicsUpdate (imports/api/Topics/methods.js:112:29)
    at packages/check/match.js:108:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43"
```
I have no idea how to reproduce it with a simple test case at this point. I hoping this looks familar to someone that knows a lot more than me.

Any ideas?

**Comment by klaussner** [comment]
The error doesn't seem to be related to `Collection#find` (or Meteor in general) because it is thrown in your application code (in the `imports/api/Topics/tarjan.js` file).

**Comment by ChuckIrvine** [comment]
Agreed. I actually borrowed that code from somewhere quite a long time ago so it didn't look familiar. My bad.
