### ISSUE TITLE
ejson.stringify(moment()) TypeError

### ISSUE THREAD

**Issue by niklas-dahl** [meteor/meteor#9669]
as describe in https://github.com/primus/ejson/issues/15 the following code will throw a TypeError:

```js
λ node
> let ejson = require('ejson')
undefined
> let moment = require('moment')
undefined
> moment()
moment("2018-02-15T11:29:17.264")
> ejson.stringify(moment())
TypeError: config._d.getTime is not a function
    at new Moment (<project path>\node_modules\moment\moment.js:238:54)
    at Moment.clone (<project path>\node_modules\moment\moment.js:3138:12)
    at Moment.toISOString (<project path>\node_modules\moment\moment.js:3266:18)
    at Moment.toJSON (<project path>\node_modules\moment\moment.js:3459:34)
    at JSON.stringify (<anonymous>)
    at Object.module.exports.EJSON.stringify (<project path>\node_modules\ejson\index.js:493:17)
    at repl:1:7
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
>
```

I know ejson is not designed to correctly serialize/deserialize moment objects but this still feels strange.

**Comment by sebakerckhof** [comment]
This happens because `moment` provides their own `toJSON` function, but it doesn't get what it expects because the ejson library already converted to moment object. So maybe `EJSON.toJSONValue` should respect if an object already has a `toJSON` function.

**Comment by hwillson** [comment]
While we think resolving this issue would be a great addition to the Meteor project, we're going to close it for now due to inactivity. If anyone comes across this issue in the future, and is interested in working on resolving it, please let us know by posting here and we'll consider re-opening this issue. Thanks!
