### ISSUE TITLE
2 node_modules folders in published package, resulting in broken app startup

### ISSUE THREAD

**Issue by sebakerckhof** [meteor/meteor#9738]
I tried to publish a new version of https://github.com/Urigo/meteor-static-html-compiler that is compatible with meteor 1.6.1. I only upgraded the dependencies, but now when I publish it I get the following error when using it:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at relative (path.js:1262:5)
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:669:5)
    at each (/tools/isobuild/import-scanner.js:638:9)
    at _.each._.forEach (/home/seba/.meteor/packages/meteor-tool/.1.6.1.blw62s.u2x7r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._resolve (/tools/isobuild/import-scanner.js:622:9)
    at each (/tools/isobuild/import-scanner.js:730:9)
    at _.each._.forEach (/home/seba/.meteor/packages/meteor-tool/.1.6.1.blw62s.u2x7r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:722:7)
    at each (/tools/isobuild/import-scanner.js:814:4)
    at _.each._.forEach (/home/seba/.meteor/packages/meteor-tool/.1.6.1.blw62s.u2x7r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:722:7)
    at each (/tools/isobuild/import-scanner.js:814:4)
    at _.each._.forEach (/home/seba/.meteor/packages/meteor-tool/.1.6.1.blw62s.u2x7r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:722:7)
    at each (/tools/isobuild/import-scanner.js:814:4)
    at _.each._.forEach (/home/seba/.meteor/packages/meteor-tool/.1.6.1.blw62s.u2x7r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:722:7)
    at each (/tools/isobuild/import-scanner.js:814:4)
    at _.each._.forEach (/home/seba/.meteor/packages/meteor-tool/.1.6.1.blw62s.u2x7r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:722:7)
...
```

I looked a bit into it and it seems to be caused by the published package having 2 node_modules folders (called `node_modules` and `node_modules1`).

When I include the package locally, I don't have this problem.

**Comment by sebakerckhof** [comment]
Update: I worked around the issue by doing `npm prune --production` before doing `meteor publish`, but that wouldn't have worked if the package was in `dependencies` instead of `devDepencies`. Why are dev dependencies included in the published meteor package anyway?

**Comment by SimonSimCity** [comment]
@sebakerckhof You mentioned that you were able to work around this. How did you do it? I'm asking because I receive the same error message when trying to import [lmieulet:meteor-coverage](https://github.com/serut/meteor-coverage). I pretty much don't know how to proceed with this ... See https://github.com/serut/meteor-coverage/issues/54#issuecomment-371058172 for some details.

**Comment by sebakerckhof** [comment]
I just removed the node_modules folder before publishing. I only needed them for typescript compilation.

**Comment by copleykj** [comment]
I would really really REALLY love to see this fixed. Any projects that symlink to my local packages that have node_modules folders will not run until I remove the folder. If I then reinstall my dev dependencies, the app starts crashing again.. This is especially annoying for packages that also support being published to NPM :slightly_frowning_face: .
