### ISSUE TITLE
[1.6.1] After upgrade , meteohacks:kadira and mdg:meteor-apm-agent are not working anymore

### ISSUE THREAD

**Issue by claudiutraistaru** [meteor/meteor#9744]
- [x] The version of Meteor showing the problem.
1.6.1
- [x] The last version of Meteor where the problem did _not_ occur, if applicable.
before 1.6.0
- [x] The operating system you're running Meteor on.
Windows 10, also has this error on Linux
- [x] The expected behavior.
No errors
- [x] The actual behavior.
Throws the below errors
- [x] A **simple** reproduction!
install latest meteorhacks-kadira on mdg-apm agent packages

The error I get is the one below:

```
I20180314-14:20:31.073(2)? Exception from sub id undefined TypeError: Promise.await is not a function
I20180314-14:20:31.074(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1186:25)
I20180314-14:20:31.075(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20180314-14:20:31.076(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20180314-14:20:31.076(2)?     at packages/ddp-server/livedata_server.js:413:12
I20180314-14:20:31.077(2)?     at Array.forEach (<anonymous>)
I20180314-14:20:31.077(2)?     at Function._.each._.forEach (packages\underscore.js:139:11)
I20180314-14:20:31.078(2)?     at Session.startUniversalSubs (packages/ddp-server/livedata_server.js:412:7)
I20180314-14:20:31.078(2)?     at packages/ddp-server/livedata_server.js:301:10
W20180314-14:20:31.079(2)? (STDERR) C:\Users\[User]\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\server-lib\node_mo
dules\fibers\future.js:280
W20180314-14:20:31.080(2)? (STDERR)                                             throw(ex);
W20180314-14:20:31.081(2)? (STDERR)                                             ^
W20180314-14:20:31.082(2)? (STDERR) 
W20180314-14:20:31.094(2)? (STDERR) TypeError: Cannot read property 'constructor' of undefined
W20180314-14:20:31.095(2)? (STDERR)     at exposeSubscription (packages\meteorhacks_meteorx.js:61:41)
W20180314-14:20:31.096(2)? (STDERR)     at exposeLivedata (packages\meteorhacks_meteorx.js:31:5)
W20180314-14:20:31.096(2)? (STDERR)     at packages\meteorhacks_meteorx.js:175:1
W20180314-14:20:31.096(2)? (STDERR)     at packages\meteorhacks_meteorx.js:200:4
W20180314-14:20:31.097(2)? (STDERR)     at packages\meteorhacks_meteorx.js:208:3
W20180314-14:20:31.098(2)? (STDERR)     at D:\project\web\.meteor\local\build\programs\server\boot.js:411:36
W20180314-14:20:31.098(2)? (STDERR)     at Array.forEach (<anonymous>)
W20180314-14:20:31.099(2)? (STDERR)     at D:\project\web\.meteor\local\build\programs\server\boot.js:220:19
W20180314-14:20:31.099(2)? (STDERR)     at D:\project\web\.meteor\local\build\programs\server\boot.js:471:5
W20180314-14:20:31.100(2)? (STDERR)     at Function.run (D:\project\web\.meteor\local\build\programs\server\profile.js:510:12)
W20180314-14:20:31.100(2)? (STDERR)     at D:\project\web\.meteor\local\build\programs\server\boot.js:470:11
I20180314-14:20:31.101(2)? Exception from sub __dummy_pub_8zoMikPwnwnWCuHCM id WJXsbRicDABn3sTzT TypeError: Promise.await is not a function
I20180314-14:20:31.101(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages\meteor.js:1186:25)
I20180314-14:20:31.104(2)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20180314-14:20:31.104(2)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20180314-14:20:31.105(2)?     at exposeSubscription (packages\meteorhacks_meteorx.js:59:11)
I20180314-14:20:31.105(2)?     at exposeLivedata (packages\meteorhacks_meteorx.js:31:5)
I20180314-14:20:31.106(2)?     at packages\meteorhacks_meteorx.js:175:1
I20180314-14:20:31.106(2)?     at packages\meteorhacks_meteorx.js:200:4
I20180314-14:20:31.106(2)?     at packages\meteorhacks_meteorx.js:208:3
I20180314-14:20:31.107(2)?     at D:\project\web\.meteor\local\build\programs\server\boot.js:411:36
I20180314-14:20:31.108(2)?     at Array.forEach (<anonymous>)
I20180314-14:20:31.109(2)?     at D:\project\web\.meteor\local\build\programs\server\boot.js:220:19
I20180314-14:20:31.109(2)?     at D:\project\web\.meteor\local\build\programs\server\boot.js:471:5
I20180314-14:20:31.109(2)?     at Function.run (D:\project\web\.meteor\local\build\programs\server\profile.js:510:12)
I20180314-14:20:31.110(2)?     at D:\project\web\.meteor\local\build\programs\server\boot.js:470:11

```

My content for meteor packages file is:
```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.3.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.4.2                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.4.0   # CSS minifier run for production mode
standard-minifier-js@2.3.1    # JS minifier run for production mode
es5-shim@4.7.0                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.10.0              # Enable ECMAScript2015+ syntax in app code

msavin:mongol
themeteorchef:jquery-validation
aldeed:simple-schema
aldeed:collection2
mdg:validated-method
accounts-password@1.5.0
tmeasday:publish-counts
http@1.4.0
gadicohen:headers
alanning:roles
yasaricli:slugify
session@1.1.7
sacha:spin
miguelalarcos:flow-router-pagination
miguelalarcos:flow-router-pagination-reverse
percolate:find-from-publication
check@1.3.0
react-meteor-data
ostrio:logger
ostrio:loggerconsole
shell-server@0.3.1
kadira:dochead
thereactivestack:blazetoreact
mrt:nprogress
fortawesome:fontawesome
abpetkov:switchery
accounts-base@1.4.2
webdeb:app-loader
ajduke:bootstrap-tokenfield
natestrauser:select2
anti:i18n
universe:cookie-info
dferber:prerender
pmteor:dropdown
meteorhacks:picker
xmlbuilder@2.5.15
service-configuration@1.0.11
jcbernack:reactive-aggregate
mrt:jquery-ui-sortable
benjaminrh:jquery-cookie
matb33:bootstrap-dropdowns
twbs:bootstrap
universe:react-bootstrap
pushplaybang:backdoor-testonly
dynamic-import@0.3.0
ostrio:flow-router-extra
blaze
templating
themeteorchef:bert
xolvio:backdoor
xolvio:cleaner
#this package is needed to have filesave work on windows
ostrio:meteor-root
gwendall:remote-ddp
promise
mdg:meteor-apm-agent
```

and the versions:

```
abpetkov:switchery@0.1.0
accounts-base@1.4.2
accounts-password@1.5.0
ajduke:bootstrap-tokenfield@0.5.0
alanning:roles@1.2.16
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.4
allow-deny@1.1.0
anti:i18n@0.4.3
autoupdate@1.4.0
babel-compiler@7.0.5
babel-runtime@1.2.2
base64@1.0.11
benjaminrh:jquery-cookie@0.1.0
binary-heap@1.0.10
blaze@2.3.2
blaze-html-templates@1.1.2
blaze-tools@1.0.10
boilerplate-generator@1.4.0
caching-compiler@1.1.11
caching-html-compiler@1.1.2
callback-hook@1.1.0
check@1.3.1
coffeescript@1.0.17
cosmos:browserify@0.10.0
ddp@1.4.0
ddp-client@2.3.2
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.2
deps@1.0.12
dferber:prerender@2.2.2_3
diff-sequence@1.1.0
dynamic-import@0.3.0
ecmascript@0.10.5
ecmascript-runtime@0.5.0
ecmascript-runtime-client@0.6.2
ecmascript-runtime-server@0.5.0
ejson@1.1.0
email@1.2.3
es5-shim@4.7.3
fortawesome:fontawesome@4.7.0
fourseven:scss@4.5.4
gadicohen:headers@0.0.31
geojson-utils@1.0.10
gwendall:remote-ddp@0.1.0
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.0
id-map@1.1.0
jcbernack:reactive-aggregate@0.7.0
jquery@1.11.11
jsx@0.2.4
kadira:dochead@1.5.0
launch-screen@1.1.1
less@2.7.12
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
matb33:bootstrap-base@10.0.0
matb33:bootstrap-dropdowns@10.0.0
mdg:meteor-apm-agent@3.1.1
mdg:validated-method@1.1.0
mdg:validation-error@0.5.1
meteor@1.8.4
meteor-base@1.3.0
meteorhacks:aggregate@1.3.0
meteorhacks:collection-utils@1.2.0
meteorhacks:inject-initial@1.0.4
meteorhacks:meteorx@1.4.1
meteorhacks:picker@1.0.3
meteortoys:toykit@3.0.4
miguelalarcos:flow-router-pagination@0.1.6
miguelalarcos:flow-router-pagination-reverse@0.1.6
minifier-css@1.3.1
minifier-js@2.3.3
minimongo@1.4.3
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modules@0.11.5
modules-runtime@0.9.2
mongo@1.4.5
mongo-dev-server@1.1.0
mongo-id@1.0.7
mongo-livedata@1.0.12
mrt:jquery-ui-sortable@1.10.3
mrt:nprogress@0.2.0
msavin:mongol@2.0.1
natestrauser:animate-css@3.5.1
natestrauser:select2@4.0.3
npm-bcrypt@0.9.3
npm-mongo@2.2.34
observe-sequence@1.0.16
ordered-dict@1.1.0
ostrio:flow-router-extra@3.4.6
ostrio:logger@1.1.2
ostrio:loggerconsole@1.2.1
ostrio:meteor-root@1.0.7
percolate:find-from-publication@0.1.0
pmteor:dropdown@0.0.1
promise@0.10.2
pushplaybang:backdoor-testonly@0.2.1
raix:eventemitter@0.1.3
random@1.1.0
rate-limit@1.0.9
react-meteor-data@0.2.16
reactive-dict@1.2.0
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
routepolicy@1.0.13
sacha:spin@2.3.1
server-render@0.3.0
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.3.1
shim-common@0.1.0
socket-stream-client@0.1.0
spacebars@1.0.15
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-css@1.4.1
standard-minifier-js@2.3.2
templating@1.3.2
templating-compiler@1.3.3
templating-runtime@1.3.2
templating-tools@1.1.2
themeteorchef:bert@2.1.3
themeteorchef:jquery-validation@1.14.0
thereactivestack:blazetoreact@1.0.2
tmeasday:check-npm-versions@0.3.2
tmeasday:publish-counts@0.8.0
tracker@1.1.3
twbs:bootstrap@3.3.6
ui@1.0.13
underscore@1.0.10
universe:cookie-info@0.0.3
universe:modules@0.1.0
universe:react-bootstrap@0.23.7
unofficial:babel-compiler@5.4.7
url@1.2.0
webapp@1.5.0
webapp-hashing@1.0.9
webdeb:app-loader@0.0.1
xmlbuilder@2.5.15
xolvio:backdoor@0.2.1
xolvio:cleaner@0.3.3
yasaricli:slugify@0.0.7
```

I am struggeling with this and I do not know if I am the only one with this issue.
If I remove the kadira or meteor-apm-agents packages everything is ok 

Platform is windows but from what I saw in linux it gives the same error

**Comment by hwillson** [comment]
Are you using any babel plugins or npm packages that might be overriding Meteor's server side Promise implementation? The `Promise.await is not a function` exception points towards this being the problem.

**Comment by claudiutraistaru** [comment]
Hi Willson,
This is the content of package.json 👍 
    "@babel/runtime": "^7.0.0-beta.42",
    "bcrypt": "^1.0.3",
    "bcryptjs": "^2.4.3",
    "core-js": "^2.5.3",
    "ecmascript": "^1.0.0",
    "fibers": "^2.0.0",
    "fs": "0.0.1-security",
    "fs-path": "0.0.22",
    "handlebars": "^4.0.10",
    "index.js": "0.0.3",
    "is_js": "^0.9.0",
    "juice": "^4.2.3",
    "meteor-node-stubs": "^0.2.11",
    "npm-git-install": "^0.3.0",
    "randomstring": "^1.1.5",
    "react": "^15.6.2",
    "react-addons-create-fragment": "^15.3.0",
    "react-addons-css-transition-group": "^15.3.0",
    "react-addons-linked-state-mixin": "^15.3.0",
    "react-addons-perf": "^15.3.0",
    "react-addons-pure-render-mixin": "^15.4.2",
    "react-addons-test-utils": "^15.3.0",
    "react-addons-transition-group": "^15.3.0",
    "react-addons-update": "^15.3.0",
    "react-bootstrap": "^0.31.5",
    "react-burger-menu": "^2.3.0",
    "react-color": "^2.14.0",
    "react-dom": "^15.6.1",
    "react-mounter": "^1.2.0",
    "react-switchery": "^1.2.2",
    "tracker-component": "^1.3.21"

Maybe one package from here is the problem....

**Comment by hwillson** [comment]
Right off the bat I'd remove `core-js` (since it's already a dependency of `@babel/runtime`) and `ecmascript` (since it isn't a valid npm package - it's a Meteor package, and shouldn't be in your `package.json`).

**Comment by hwillson** [comment]
Any chance you can provide a small runnable reproduction that shows this happening?

**Comment by claudiutraistaru** [comment]
Ok , it reealy seems that creating a new application with the same packages (npm and meteor) does not end with the same error, I ill have to debug my project more as I cannot just recrate it . Thank you for your help.

**Comment by claudiutraistaru** [comment]
Hi , I managed to reproduse it by trying again and installed exactly the same packages from meteor and from npm and managed to isolate the issue when this package is installed: universe:react-bootstrap.
Removing it removed the following dependencies:
Changes to your project's package version selections:

cosmos:browserify          removed from your project
universe:modules           removed from your project
universe:react-bootstrap   removed from your project
unofficial:babel-compiler  removed from your project

and I sopose the issue is unofficial:babel-compiler.  Maybe this can help you.
