### ISSUE TITLE
[1.6.1] TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by micktaiwan** [meteor/meteor#9755]
Meteor 1.6.1 / Ubuntu 16.04

Everytime I change a file in my IDE while app is running I receive this error

internal/process/next_tick.js:131
      callback();
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at relative (path.js:1262:5)
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:662:24)

**Comment by ddaydd** [comment]
Same problem here,

I don't think it is .1.6.1 dependant and i am under windows...

**Comment by crsssl** [comment]
+1 Same problem under MacOS and upgrading to any version above 1.6.0.1.

**Comment by hwillson** [comment]
Hi all - this should be fixed by  https://github.com/meteor/meteor/commit/bd26ce3d1e50f37fa4228923f7c11b164fedc0fb, and will be included in the next Meteor release.

**Comment by hwillson** [comment]
I'll close this for now since the fix was merged (and the next release will be coming soon). Thanks!

**Comment by abdagli** [comment]
Issue is not closed for `1.7-beta.23`

```bash
~/D/p/b/pass  meteor --settings=settings.json                                                                                                                                                                                                1387ms  Sat Apr 21 08:27:36 2018
[[[[[ ~/Dropbox/projects/bordoio/pass ]]]]]

=> Started proxy.

Changes to your project's package version selections:

abdagli:pass               added, version 0.0.1
abdagli:pass-accounts      added, version 0.0.1
abdagli:pass-head          added, version 0.0.1
abdagli:pass-layout        added, version 0.0.1
abdagli:pass-navbar        added, version 0.0.1
abdagli:pass-organizer     added, version 0.0.1
abdagli:pass-toast         added, version 0.0.1
accounts-base              added, version 1.4.2
aldeed:simple-schema       added, version 1.3.3
allow-deny                 added, version 1.1.0
autoupdate                 added, version 1.4.0
babel-compiler             added, version 7.1.0-beta17.23
babel-runtime              added, version 1.2.2
base64                     added, version 1.0.11
binary-heap                added, version 1.0.10
blaze                      added, version 2.3.2
blaze-html-templates       added, version 1.1.2
blaze-tools                added, version 1.0.10
boilerplate-generator      added, version 1.5.0-beta17.23
caching-compiler           added, version 1.1.11
caching-html-compiler      added, version 1.1.2
callback-hook              added, version 1.1.0
cfs:http-methods           added, version 0.0.32
check                      added, version 1.3.1
coffeescript               added, version 1.0.17
ddp                        added, version 1.4.0
ddp-client                 added, version 2.3.2
ddp-common                 added, version 1.4.0
ddp-rate-limiter           added, version 1.0.7
ddp-server                 added, version 2.1.2
deps                       added, version 1.0.12
diff-sequence              added, version 1.1.0
dynamic-import             added, version 0.4.0-beta17.23
ecmascript                 added, version 0.11.0-beta17.23
ecmascript-runtime         added, version 0.7.0-beta17.23
ecmascript-runtime-client  added, version 0.7.0-beta17.23
ecmascript-runtime-server  added, version 0.7.0-beta17.23
ejson                      added, version 1.1.0
email                      added, version 1.2.3
erasaur:meteor-lodash      added, version 0.1.0
es5-shim                   added, version 4.8.0-beta17.23
fourseven:scss             added, version 4.5.4
geojson-utils              added, version 1.0.10
hot-code-push              added, version 1.0.4
html-tools                 added, version 1.0.11
htmljs                     added, version 1.0.11
http                       added, version 1.4.1
id-map                     added, version 1.1.0
jquery                     added, version 1.11.11
kadira:blaze-layout        added, version 2.3.0
kadira:flow-router         added, version 2.12.1
launch-screen              added, version 1.1.1
less                       added, version 2.7.12
livedata                   added, version 1.0.18
localstorage               added, version 1.2.0
logging                    added, version 1.1.20
materialize:materialize    added, version 0.100.2
meteor                     added, version 1.9.0-beta17.23
meteor-base                added, version 1.4.0-beta17.23
meteorspark:util           added, version 0.2.0
minifier-css               added, version 1.3.1
minifier-js                added, version 2.3.4
minimongo                  added, version 1.4.4
mobile-experience          added, version 1.0.5
mobile-status-bar          added, version 1.0.14
modern-browsers            added, version 0.1.0-beta17.23
modules                    added, version 0.11.6
modules-runtime            added, version 0.10.0-beta17.23
mongo                      added, version 1.5.0-beta17.23
mongo-dev-server           added, version 1.1.0
mongo-id                   added, version 1.0.7
npm-bcrypt                 added, version 0.9.3
npm-mongo                  added, version 2.2.34
observe-sequence           added, version 1.0.16
okland:accounts-phone      added, version 0.0.21
ordered-dict               added, version 1.1.0
promise                    added, version 0.11.0-beta17.23
raix:eventemitter          added, version 0.1.3
random                     added, version 1.1.0
rate-limit                 added, version 1.0.9
reactive-dict              added, version 1.2.0
reactive-var               added, version 1.0.11
reload                     added, version 1.2.0
retry                      added, version 1.1.0
routepolicy                added, version 1.0.13
service-configuration      added, version 1.0.11
session                    added, version 1.1.7
sha                        added, version 1.0.9
shell-server               added, version 0.3.1
socket-stream-client       added, version 0.2.0-beta17.23
spacebars                  added, version 1.0.15
spacebars-compiler         added, version 1.1.3
srp                        added, version 1.0.10
standard-minifier-css      added, version 1.4.1
standard-minifier-js       added, version 2.3.3
tap:i18n                   added, version 1.8.2
templating                 added, version 1.3.2
templating-compiler        added, version 1.3.3
templating-runtime         added, version 1.3.2
templating-tools           added, version 1.1.2
tracker                    added, version 1.2.0-beta17.23
ui                         added, version 1.0.13
underscore                 added, version 1.0.10
url                        added, version 1.2.0
webapp                     added, version 1.6.0-beta17.23
webapp-hashing             added, version 1.0.9

/Users/abdagli/.meteor/packages/coffeescript/.1.0.17.eilhok.tuw9m++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at relative (path.js:1252:5)
    at ImportScanner._getRelativeImportId (/tools/isobuild/import-scanner.js:796:24)
    at ImportScanner._checkSourceAndTargetPaths (/tools/isobuild/import-scanner.js:400:31)
    at files.forEach.file (/tools/isobuild/import-scanner.js:244:12)
    at Array.forEach (<anonymous>)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:243:11)
    at sourceBatches.forEach.batch (/tools/isobuild/compiler-plugin.js:1095:15)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1066:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1070:8)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:841:12)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:832:18)
    at /tools/isobuild/bundler.js:2951:14
    at /tools/isobuild/bundler.js:3040:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/Users/abdagli/.meteor/packages/meteor-tool/.1.7.0-beta.23.186gvtv.5oicj++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:3039:7
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2932:31)
    at files.withCache (/tools/isobuild/bundler.js:2879:32)
    at Object.withCache (/tools/fs/files.js:1700:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2879:16)
    at Profile.run (/tools/runners/run-app.js:579:36)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:578:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12
```

**Comment by Doun92** [comment]
I had this error too.
I uninstalled meteor, turned off and on my comupter, created a second github folder by cloning my github project and installed again meteor.

With all this manipulations, it worked.

**Comment by derwaldgeist** [comment]
Same problem after updating to 1.7.1

**Comment by macrozone** [comment]
i tried to update an ancient app to meteor 1.7 (and eventually to 1.8) but i also ran into this issue.

was anyone able to solve this?

**Comment by micktaiwan** [comment]
Why is this issue closed as it is clearly not resolved ?

**Comment by macrozone** [comment]
ok in my case i could solve it. My ancient app still used bower (https://github.com/mquandalle/meteor-bower) and this caused this issue. :ugly:
