### ISSUE TITLE
CircleCI Android build 1.6.1

### ISSUE THREAD

**Issue by KoenLav** [meteor/meteor#9787]
When building for Android on CircleCI with docker image circleci/android:api-26-node8-alpha we receive exit code 1. Any pointers as to where to look for the error?

We already limited the amount of memory by setting GRADLE_OPTS: -Xmx512m in the environment.

In addition: it would be really nice if some people could share their build scripts for CircleCI and other CI providers (or if these could even be added to the docs).

Also interesting: https://github.com/johnthepink/meteor-launch

```
....
Subproject Path: CordovaLib
ANDROID_HOME=/opt/android/sdk
JAVA_HOME=/docker-java-home
Starting a Gradle Daemon (subsequent builds will be faster)
:wrapper

BUILD SUCCESSFUL

Total time: 4.054 secs
Subproject Path: CordovaLib
Downloading https://services.gradle.org/distributions/gradle-4.1-all.zip
Unzipping /home/circleci/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1-all.zip to /home/circleci/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew
Set executable permissions for: /home/circleci/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
=> Errors executing Cordova commands:

   While building Cordova app for platform Android:
   Error:
   /home/circleci/app/.meteor/local/cordova-build/platforms/android/gradlew:
   Command failed with exit code null
   at ChildProcess.whenDone
   (/home/circleci/app/.meteor/local/cordova-build/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
   at emitTwo (events.js:126:13)
   at ChildProcess.emit (events.js:214:7)
   at maybeClose (internal/child_process.js:925:16)
   at Socket.stream.socket.on (internal/child_process.js:346:11)
   at emitOne (events.js:116:13)
   at Socket.emit (events.js:211:7)
   at Pipe._handle.close [as _onclose] (net.js:554:12)
Exited with code 1
```

**Comment by abernix** [comment]
Not sure if it's helpful, but for our CircleCI test runs on Meteor core we [use a custom Docker image](https://github.com/meteor/meteor/blob/782d774b43801ecab8c784954879c9e7e125c9da/.circleci/config.yml#L64) based on `circleci/android:api-26-node8-alpha` that also installs `gradle` from APT.  That `Dockerfile` is here:

https://github.com/meteor/circleci/blob/master/Dockerfile
