### ISSUE TITLE
CLI throw weird error, only `meteor run` works

### ISSUE THREAD

**Issue by myste1tainn** [meteor/meteor#9812]
**The problem:**
I run `meteor add` and some other commands and got this error:
```
Myste1tainn at api => feature/registration
$ meteor add alanning:roles

/Users/Myste1tainn/.meteor/packages/meteor-tool/.1.6.0-rc.7.4zgzx0.q3p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^
Error: Internal server error [500]
    at Connection._livedata_result (packages/ddp-client/livedata_connection.js:1629:23)
    at onMessage (packages/ddp-client/livedata_connection.js:278:12)
    at runWithEnvironment (packages/meteor.js:1188:24)
    at packages/meteor.js:1201:14
    at packages/ddp-client/stream_client_nodejs.js:200:9
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at packages/ddp-client/stream_client_nodejs.js:199:9
    at packages/ddp-client/stream_client_nodejs.js:175:11
    at runWithEnvironment (packages/meteor.js:1188:24)
 => awaited here:
    at Promise.await (/Users/Myste1tainn/.meteor/packages/meteor-tool/.1.6.0-rc.7.4zgzx0.q3p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:60:12)
    at ServiceConnection.apply (/tools/meteor-services/service-connection.js:132:12)
    at ServiceConnection.call (/tools/meteor-services/service-connection.js:104:17)
    at loadRemotePackageData (/tools/packaging/package-client.js:105:15)
    at getSomeData (/tools/packaging/package-client.js:176:22)
    at _updateServerPackageData (/tools/packaging/package-client.js:223:7)
    at /tools/packaging/package-client.js:129:12
    at /tools/utils/buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.exports.updateServerPackageData (/tools/packaging/package-client.js:128:23)
    at /tools/packaging/catalog/catalog-remote.js:777:36
    at /tools/utils/buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at RemoteCatalog.refresh (/tools/packaging/catalog/catalog-remote.js:776:18)
    at Object.catalog.refreshOrWarn (/tools/packaging/catalog/catalog.js:48:22)
    at catalog.Refresh.OnceAtStart.beforeCommand (/tools/packaging/catalog/catalog.js:21:16)
    at /tools/cli/main.js:1487:32
    at /tools/utils/buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/cli/main.js:1486:20
```

Nothing works so far except `meteor run`

**Expectation**
The package should be installed

**What happened instead**
The error thrown as above

**What is meteor version?**
I ran into this error previously in version **1.5.0** or something
then I tried to upgrade, now in version **1.6-rc.7**, stills not working
`meteor update` also throw the same error

**Environment**
MacOS High Sierra 10.13.4
Project: Ionic2 Meteor Project setup (with Ionic CLI)

**Comment by Grisu118** [comment]
meteor run will also not work if you have a fresh meteor install without packages. 
See also:
https://forums.meteor.com/t/meteor-update-meteor-add-500-internal-server-error/43200

**Comment by evangelos-ch** [comment]
Facing the exact same issue on my end at the moment.

I started working on a new project yesterday and I could add packages fine, then today about two hours ago when I wanted to install a package from atmosphere it started happening. `meteor add <valid package>` just does not work for any package, `meteor remove` works, `meteor run` also works. But adding packages simply does not.

I am going to assume this is a problem on meteor's servers' end.

**Comment by dixicoin** [comment]
Same here, nothing works except `meteor run, meteor`, MacOS

**Comment by hwillson** [comment]
Hi all - this is related to https://github.com/meteor/meteor/issues/9813. The root cause is being investigated.

**Comment by abernix** [comment]
This problem is now resolved and the package server should be operating normally again.

Thanks for your patience while we ensured everything was working properly.

**Comment by myste1tainn** [comment]
@abernix 
Thank you! I'm having the need to deliver some work.
