### ISSUE TITLE
1.6.2 Beta 20 _interopRequireDefault is not a function

### ISSUE THREAD

**Issue by stolinski** [meteor/meteor#9824]
Getting 

```
W20180418-10:47:59.137(-6)? (STDERR) TypeError: _interopRequireDefault is not a function
W20180418-10:47:59.137(-6)? (STDERR)     at livedata_connection.js (/Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/packages/ddp-client.js:148:22)
W20180418-10:47:59.137(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180418-10:47:59.137(-6)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180418-10:47:59.137(-6)? (STDERR)     at namespace.js (packages/ddp-client/common/namespace.js:1:300)
W20180418-10:47:59.143(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180418-10:47:59.143(-6)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180418-10:47:59.143(-6)? (STDERR)     at server.js (packages/ddp-client/server/server.js:1:14)
W20180418-10:47:59.144(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180418-10:47:59.144(-6)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180418-10:47:59.144(-6)? (STDERR)     at /Users/scotttolinski/Sites/levelup/.meteor/local/build/programs/server/packages/ddp-client.js:2073:15
```

after updating to Beta20

Here are my versions

```
accounts-base@1.4.2
accounts-password@1.5.1
aldeed:collection2-core@2.1.2
allow-deny@1.1.0
apollo@2.0.0
autoupdate@1.4.0
babel-compiler@7.1.0-beta162.20
babel-runtime@1.2.2
base64@1.0.11
binary-heap@1.0.10
blaze-tools@1.0.10
boilerplate-generator@1.5.0-beta162.20
caching-compiler@1.1.11
caching-html-compiler@1.1.2
callback-hook@1.1.0
check@1.3.1
ddp@1.4.0
ddp-client@2.3.2
ddp-common@1.4.0
ddp-rate-limiter@1.0.7
ddp-server@2.1.2
deps@1.0.12
didericis:callpromise-mixin@0.0.1
diff-sequence@1.1.0
dynamic-import@0.4.0-beta162.20
ecmascript@0.11.0-beta162.20
ecmascript-runtime@0.7.0-beta162.20
ecmascript-runtime-client@0.7.0-beta162.20
ecmascript-runtime-server@0.7.0-beta162.20
ejson@1.1.0
email@1.2.3
es5-shim@4.8.0-beta162.20
gadicohen:robots-txt@0.0.10
gadicohen:sitemaps@0.0.26
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.4.0
id-map@1.1.0
juliancwirko:postcss@1.2.0
launch-screen@1.1.1
livedata@1.0.18
localstorage@1.2.0
logging@1.1.20
mdg:validated-method@1.1.0
meteor@1.9.0-beta162.20
meteor-base@1.4.0-beta162.20
meteortesting:browser-tests@0.1.2
meteortesting:mocha@0.5.0
minifier-css@1.3.1
minifier-js@2.3.4
minimongo@1.4.4
mobile-experience@1.0.5
mobile-status-bar@1.0.14
modern-browsers@0.1.0-beta162.20
modules@0.11.6
modules-runtime@0.10.0-beta162.20
mongo@1.4.7
mongo-dev-server@1.1.0
mongo-id@1.0.7
npm-bcrypt@0.9.3
npm-mongo@2.2.34
ordered-dict@1.1.0
practicalmeteor:mocha-core@1.0.1
promise@0.11.0-beta162.20
raix:eventemitter@0.1.3
random@1.1.0
rate-limit@1.0.9
reactive-var@1.0.11
reload@1.2.0
retry@1.1.0
routepolicy@1.0.13
server-render@0.3.0
service-configuration@1.0.11
sha@1.0.9
socket-stream-client@0.2.0-beta162.20
spacebars-compiler@1.1.3
srp@1.0.10
standard-minifier-js@2.3.3
static-html@1.2.2
stylus@2.513.13
swydo:graphql@0.4.0
templating-tools@1.1.2
tmeasday:check-npm-versions@0.3.2
tracker@1.2.0-beta162.20
underscore@1.0.10
url@1.2.0
webapp@1.6.0-beta162.20
webapp-hashing@1.0.9
```

**Comment by stolinski** [comment]
Also seeing this in 1.7-beta.23

**Comment by benjamn** [comment]
What version of `@babel/runtime` do you have in your `package.json` file?

**Comment by stolinski** [comment]
`"@babel/runtime": "^7.0.0-beta.44",`

**Comment by stolinski** [comment]
Just a heads up, seeing this in the latest beta (1.7 beta-27) with an updated @babel/runtime of `"@babel/runtime": "^7.0.0-beta.46",`

**Comment by benjamn** [comment]
Hmm, can you put together a small-ish reproduction, or at least share your `package.json` dependencies?

**Comment by stolinski** [comment]
I'll see if I can. In the meantime here are the deps

```
  "dependencies": {
    "@babel/helper-plugin-utils": "^7.0.0-beta.40",
    "apollo-cache-inmemory": "^1.1.12",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.2.8",
    "apollo-engine": "^1.0.4",
    "apollo-link": "^1.2.1",
    "apollo-link-http": "^1.5.3",
    "apollo-link-schema": "^1.0.6",
    "apollo-link-state": "^0.4.1",
    "apollo-server-express": "^1.3.4",
    "apollo-test-utils": "^0.3.2",
    "aws-sdk": "^2.217.1",
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "bcrypt": "^1.0.3",
    "body-parser": "^1.18.2",
    "braintree": "^2.8.0",
    "braintree-web": "^3.31.0",
    "chai-as-promised": "^7.1.1",
    "classnames": "^2.2.5",
    "date-fns": "^1.29.0",
    "eazy-ease": "^1.0.2",
    "eslint-plugin-graphql": "^1.5.0",
    "express": "^4.16.3",
    "faker": "^4.1.0",
    "fibers": "^2.0.2",
    "formik": "^0.11.11",
    "fs": "0.0.2",
    "graphql": "^0.13.2",
    "graphql-date": "^1.0.3",
    "graphql-mock": "^0.4.0",
    "graphql-server-express": "^1.3.4",
    "graphql-tag": "^2.8.0",
    "graphql-tools": "^2.23.1",
    "highlight.js": "^9.12.0",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.2.0",
    "load-script": "^1.0.0",
    "lodash": "^4.17.5",
    "markdown-to-jsx": "^6.6.0",
    "md5": "^2.2.1",
    "meteor-node-stubs": "^0.3.3",
    "mustache": "^2.3.0",
    "paypal-rest-sdk": "^2.0.0-rc.1",
    "picturefill": "^3.0.2",
    "prerender": "^5.3.1",
    "prerender-node": "^3.1.1",
    "prop-types": "^15.6.1",
    "raven": "^2.4.2",
    "raven-js": "^3.24.0",
    "react": "^16.3.0",
    "react-addons-create-fragment": "^15.6.2",
    "react-addons-css-transition-group": "^15.6.2",
    "react-addons-linked-state-mixin": "^15.6.2",
    "react-addons-perf": "^15.4.2",
    "react-addons-test-utils": "^15.6.2",
    "react-addons-transition-group": "^15.6.2",
    "react-addons-update": "^15.6.2",
    "react-adsense": "^0.0.5",
    "react-apollo": "^2.1.1",
    "react-async-script-loader": "^0.3.0",
    "react-braintree-fields": "^1.0.0",
    "react-day-picker": "^7.1.4",
    "react-dom": "^16.3.0",
    "react-dropzone": "^4.2.9",
    "react-flexifit": "^1.0.1",
    "react-flip-move": "^3.0.1",
    "react-gravatar": "^2.6.3",
    "react-helmet": "^5.2.0",
    "react-inlinesvg": "^0.8.1",
    "react-lazyload": "^2.3.0",
    "react-loadable": "^5.3.1",
    "react-marked-markdown": "^1.4.6",
    "react-overdrive": "0.0.9",
    "react-pose": "^1.5.2",
    "react-powerplug": "^0.1.5",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-prop-types": "1.0.2",
    "react-router-test-context": "^0.1.0",
    "react-table": "^6.8.0",
    "react-tagsinput": "^3.19.0",
    "react-toggle": "^4.0.2",
    "react-toggle-switch": "^3.0.4",
    "react-transition-group": "^2.3.0",
    "react-tweet-embed": "^1.1.0",
    "react-vertical-rhythm-overlay": "^1.0.5",
    "react-waypoint": "^8.0.1",
    "react-youtube-player": "^2.0.1",
    "simpl-schema": "^1.4.2",
    "sinon": "^4.5.0",
    "speakingurl": "^14.0.1",
    "stream-collect": "^2.1.0",
    "stripe": "^5.6.1",
    "styled-components": "^3.2.5",
    "styled-components-modifiers": "^1.0.1",
    "styled-transition-group": "^1.0.0",
    "url-search-params-polyfill": "^3.0.0",
    "victory": "^0.25.7"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.40",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.40",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.40",
    "@babel/plugin-transform-runtime": "7.0.0-beta.40",
    "@babel/preset-env": "7.0.0-beta.40",
    "@babel/preset-es2015": "7.0.0-beta.40",
    "@babel/preset-react": "7.0.0-beta.40",
    "@babel/runtime": "^7.0.0-beta.44",
    "autoprefixer": "^8.2.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.2.2",
    "babel-jest": "^23.0.0-alpha.0",
    "babel-plugin-inline-import": "^2.0.6",
    "babel-plugin-inline-import-graphql-ast": "^2.3.5",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-styled-components": "^1.5.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "chai": "^4.1.2",
    "chromedriver": "^2.37.0",
    "core-js": "^2.5.4",
    "cypress": "^2.1.0",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-import-resolver-meteor": "^0.4.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.10.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-meteor": "^4.2.0",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.7.0",
    "jest": "^23.0.0-alpha.0",
    "mocha": "^5.0.5",
    "prettier": "^1.11.1",
    "react-test-renderer": "^16.3.0",
    "regenerator-runtime": "^0.11.1",
    "why-did-you-update": "^0.1.1"
  }
```

**Comment by benjamn** [comment]
I was finally able to reproduce this in another app, and your `package.json` confirms that you likely have the same problem.

You should move `@babel/runtime` from the `devDependencies` section of your `package.json` file to the `dependencies` section, so that it will be available to your application code at runtime.

Packages in `devDependencies` can be used for things like Babel compilation and development workflow stuff (e.g. `prettier`, ESLint, etc.), but we don't copy those packages into the final `.meteor/local/build/programs/server/npm/`, because development tools can be extremely large, and bundling them in production may be inappropriate for other reasons.

Since `devDependencies` are not bundled in production, Meteor doesn't bundle them in development either, since we don't want you to depend on them accidentally in development and then have no idea why your app fails in production.

The relevant logic for this behavior lives [here](https://github.com/meteor/meteor/blob/715b96bed8593e1e48a8b4590957b22343a6c364/tools/isobuild/bundler.js#L2222) and [here](https://github.com/meteor/meteor/blob/715b96bed8593e1e48a8b4590957b22343a6c364/tools/isobuild/bundler.js#L461).

**Comment by stolinski** [comment]
Thanks @benjamn ! Can confirm this fixes.

**Comment by fgm** [comment]
Having this problem with Meteor 1.7.0.3. @babel/runtime is in dependencies, not devDependencies.
