### ISSUE TITLE
[1.7.0-beta.25] TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by fshafique** [meteor/meteor#9841]
Issue #9755 is still not resolved!
I've updated to `1.7-beta.25`, and I'm trying to run the [sample app](https://github.com/xcv58/meteor-auth0/tree/master/examples/sample-app) in the [xcv58/meteor-auth0](https://github.com/xcv58/meteor-auth0) project, but I keep getting this TypeError in Windows 10. 

I tried running under Linux (Ubuntu Server 17.10.1), and no issues.

This is the stacktrace from Windows:
```
C:\Development\Meteor Projects\meteor-auth0\examples\sample-app>meteor --settings production.settings.json
[[[[[ C:\Development\Meteor Projects\meteor-auth0\examples\sample-app ]]]]]

=> Started proxy.
C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at relative (path.js:1252:5)
    at ImportScanner._getRelativeImportId (C:\tools\isobuild\import-scanner.js:796:24)
    at each (C:\tools\isobuild\import-scanner.js:766:33)
    at _.each._.forEach (C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._resolve (C:\tools\isobuild\import-scanner.js:755:7)
    at each (C:\tools\isobuild\import-scanner.js:862:29)
    at _.each._.forEach (C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:853:5)
    at each (C:\tools\isobuild\import-scanner.js:903:12)
    at _.each._.forEach (C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:853:5)
    at each (C:\tools\isobuild\import-scanner.js:903:12)
    at _.each._.forEach (C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:853:5)
    at each (C:\tools\isobuild\import-scanner.js:903:12)
    at _.each._.forEach (C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:853:5)
    at each (C:\tools\isobuild\import-scanner.js:903:12)
    at _.each._.forEach (C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:853:5)
    at each (C:\tools\isobuild\import-scanner.js:903:12)
    at _.each._.forEach (C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at ImportScanner._scanFile (C:\tools\isobuild\import-scanner.js:853:5)
    at outputFiles.forEach.file (C:\tools\isobuild\import-scanner.js:510:14)
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (C:\tools\isobuild\import-scanner.js:508:22)
    at sourceBatches.forEach.batch (C:\tools\isobuild\compiler-plugin.js:1098:17)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (C:\tools\isobuild\compiler-plugin.js:1066:19)
    at ClientTarget._emitResources (C:\tools\isobuild\bundler.js:1070:8)
    at buildmessage.enterJob (C:\tools\isobuild\bundler.js:841:12)
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:832:18)
    at C:\tools\isobuild\bundler.js:2951:14
    at C:\tools\isobuild\bundler.js:3040:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:3039:7
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2932:31)
    at files.withCache (C:\tools\isobuild\bundler.js:2879:32)
    at Object.withCache (C:\tools\fs\files.js:1700:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2879:16)
    at Profile.run (C:\tools\runners\run-app.js:579:36)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:578:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:622:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12

```

Any help would be appreciated. Thanks.

**Comment by crapthings** [comment]
osx 

https://github.com/xcv58/meteor-auth0/tree/master/examples/sample-app

meteor 1.6.1 works
meteor 1.6.1.1 works after moving @babel/runtime from "devDependencies" to "dependencies"
1.7b25 works

**Comment by fshafique** [comment]
I'm in the middle of tracing through everything. I'm a bit of a newcomer to Node and Meteor, so I'm not familiar with any debugging tools.

So, I wanted to trace through `ImportScanner.scanImports()`  _(mentioned in the stack trace)_ and I found it in the following file:
`C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\tools\isobuild\import-scanner.js`

I just added a console.log() -- I found the properties through JSON.stringify():
```
  scanImports() {
    this.outputFiles.forEach(file => {
      console.log("file: " + file.servePath + "; "+file.absModuleId+";");
      if (!file.lazy) {
        this._scanFile(file);
      }
    });
    return this;
  }
```

So I've discovered that it chokes around the xcv58:auth0-lock package:
```
file: /packages/accounts-base/url_client.js; /node_modules/meteor/accounts-base/url_client.js;
file: /packages/accounts-base/url_server.js; /node_modules/meteor/accounts-base/url_server.js;
file: /packages/xcv58_auth0-lock/auth0-lock-client.js; /node_modules/meteor/xcv58:auth0-lock/auth0-lock-client.js;
C:\Users\fshafique\AppData\Local\.meteor\packages\meteor-tool\1.7.0-beta.25\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^
```

I suspect the only reason it fails on Windows is because of the semi-colon, which I believe Linux or OSX doesn't have a problem with. Though I'm still not sure if xcv58 or meteor-tool needs to fix this.

**Comment by crapthings** [comment]
woops stuck forever

choco install meteor then

![image](https://user-images.githubusercontent.com/1147704/39291083-62b7a5f8-4964-11e8-98d1-f1206904ce63.png)
