### ISSUE TITLE
Issue with Meteor while installing reaction swag shop

### ISSUE THREAD

**Issue by abarnasankar** [meteor/meteor#9850]
I am trying to run Reaction swag shop and it keep throwing this error

=> Started MongoDB.
C:\Users\ShankarAnand\AppData\Local\.meteor\packages\meteor-tool\1.6.1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
                                                throw(ex);
                                                ^

Error: Cannot find module '../../../../../core/collections'
    at makeMissingError (packages\modules-runtime.js:231:12)
    at require (packages\modules-runtime.js:241:19)
    at tags.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/tags.js:1:29)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/index.js:1:14)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-swag-shop/server/index.js:1:14)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at plugins.js (server/plugins.js:1:3419)
    at fileEvaluate (packages\modules-runtime.js:343:9)
    at require (packages\modules-runtime.js:238:16)
    at C:\Users\ShankarAnand\Documents\abarna csuf\reactionproject\reaction\.meteor\local\build\programs\server\app\app.js:110232:1
    at C:\Users\ShankarAnand\Documents\abarna csuf\reactionproject\reaction\.meteor\local\build\programs\server\boot.js:411:36
    at Array.forEach (<anonymous>)
    at C:\Users\ShankarAnand\Documents\abarna csuf\reactionproject\reaction\.meteor\local\build\programs\server\boot.js:220:19
    at C:\Users\ShankarAnand\Documents\abarna csuf\reactionproject\reaction\.meteor\local\build\programs\server\boot.js:471:5
    at Function.run (C:\Users\ShankarAnand\Documents\abarna csuf\reactionproject\reaction\.meteor\local\build\programs\server\profile.js:510:12)
    at C:\Users\ShankarAnand\Documents\abarna csuf\reactionproject\reaction\.meteor\local\build\programs\server\boot.js:470:11
=> Exited with code: 1

Anyone can help me solve this?

**Comment by 1337cookie** [comment]
Probably better to start at the project's github page. https://github.com/reactioncommerce/reaction-swag-shop

**Comment by hwillson** [comment]
As @1337cookie mentioned, please open an issue for this in https://github.com/reactioncommerce/reaction-swag-shop/issues.
