### ISSUE TITLE
run android-device error ：  Function.Promise.await

### ISSUE THREAD

**Issue by FindFreeFire** [meteor/meteor#9851]
=> awaited here:
    at Function.Promise.await (/Users/hang/.meteor/packages/meteor-tool/.1.6.1_1.o8hqcq.5zvm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (/tools/cordova/run-targets.js:112:5)

info
meteor version 1.6.1_1 
run in android-device

**Comment by hwillson** [comment]
You haven't given us much to go on here:

- Is this happening with a brand new application? 
- Did it just start happening? 
- Was this application working with other versions of Meteor? 
- Is it working when you `meteor run android` or `meteor run ios-device`?
- etc.

Any additional details you can provide will greatly help with troubleshooting. If you can provide a small runnable reproduction that demonstrates this happening, that would be even better.

**Comment by klaussner** [comment]
Closing due to inactivity. Feel free to reopen this issue if you can share a runnable reproduction.
