### ISSUE TITLE
[1.7.rc-1] final argument to `executeOperation` must be a callback

### ISSUE THREAD

**Issue by rj-david** [meteor/meteor#9858]
Problematic version: 1.7-rc.1
Last version without problem: 1.6.1.1

Here is the complete error trace:
```
TypeError: final argument to `executeOperation` must be a callback
    at executeOperation (/home/rj/.meteor/packages/npm-mongo/.3.0.7-rc17.1.1o8eute.0bf3++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:429:11)
    at Cursor.explain (/home/rj/.meteor/packages/npm-mongo/.3.0.7-rc17.1.1o8eute.0bf3++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/cursor.js:1118:10)
    at insertExplainPlan (imports/api/libraries/MongoDBHook.js:55:71)
    at MongoConnection.MongoDBHook.js.MongoInternals.Connection.find (imports/api/libraries/MongoDBHook.js:87:9)
    at extension.find (packages/mongo/collection.js:329:29)
    at extension.find (packages/cultofcoders:redis-oplog/lib/mongo/extendMongoCollection.js:21:41)
    at extension.update (packages/cultofcoders:redis-oplog/lib/mongo/Mutator.js:106:27)
    at extension.update (packages/cultofcoders:redis-oplog/lib/mongo/extendMongoCollection.js:45:35)
    at extension.Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2-core/collection2.js:213:19)
    at extension.upsert (packages/mongo/collection.js:650:17)
    at savePushNotification (imports/api/collections/PushNotificationUsers.js:35:31)
    at MethodInvocation.run (imports/api/methods/login.js:194:29)
    at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:93:12)
    at MethodInvocation.login.verify.code (packages/mdg:validated-method/validated-method.js:54:23)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
```

I am using a mongodb hook for the purpose of collecting queries so that we can add index later.

Here was line 55 of MongoDBHook.js:
```
let collection = this.rawCollection(collectionName);
let explainPromise = collection.find(cleanedSelector).explain('executionStats');

```

**Comment by sebakerckhof** [comment]
That's because `explain('executionStats')` is invalid. It also was invalid in 2.2, but it happened to not fail.

You can give a callback or nothing if you want a promise. So it should just be `explain()`

**Comment by rj-david** [comment]
Thanks, @sebakerckhof 

I've confirmed through further searching that it was previously being ignored by the driver if the parameter was not a function. Not sure what changed that it is now being reported as an error but it was good that I found out it wasn't working as expected.
