### ISSUE TITLE
accounts-password - Exception while invoking method 'login' Error

### ISSUE THREAD

**Issue by jeroenhoebe** [meteor/meteor#9893]
Recently I'm getting these errors in my server logs:

```
Exception while invoking method 'login' Error
   at check (packages/check/match.js:36:17)
   at MethodInvocation.<anonymous> (packages/accounts-password/password_server.js:290:3)
   at packages/accounts-base/accounts_server.js:483:32
   at tryLoginMethod (packages/accounts-base/accounts_server.js:259:14)
   at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:480:18)
   at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:543:27)
   at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
   at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
   at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
   at Promise (packages/ddp-server/livedata_server.js:715:46)
   at Promise (<anonymous>)
   at Session.method (packages/ddp-server/livedata_server.js:689:23)
   at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Match failed [400]
```
I don't get a lot of them. Also haven't found a way to recreate the Error.

Meteor 1.6.1.1
accounts-base@1.4.2
accounts-password@1.5.1

Running it on a DigitalOcean droplet and uploaded with meteor-up.

**Comment by od1k** [comment]
I think this happens when you don't pass email/username or password into `Meteor.loginWithPassword`.

**Comment by jeroenhoebe** [comment]
Thanks for the suggestion, I'm going to check if that's the case.
