### ISSUE TITLE
[1.7-rc.11] wrong decorators compiling

### ISSUE THREAD

**Issue by Deadly0** [meteor/meteor#9895]
Trying to update meteor to 1.7 from 1.6.1.
I use babel config as described here https://github.com/meteor/meteor/issues/9628#issuecomment-362861507

Without  `{ "legacy": true }` `@babel/plugin-proposal-decorators` throws error `The new decorators proposal is not supported yet. You must pass the
   "legacy": true option to @babel/plugin-proposal-decorators (While
   processing: "base$0$1")
` so `{ "legacy": true }` was added to the config

.babelrc

```
{
	"plugins": [
		["@babel/plugin-proposal-class-properties", { "loose" : true }],
		["@babel/plugin-proposal-decorators", { "legacy": true }]
	]
}
```

Sourse code:

```
export default
@connect(null, {
    showHideReport,
    showHideAddEditDriverModal,
    showHideTransactionDriverModal,
    deleteDriverRequest,
    sendDriverRequest,
})
class DriverItem extends React.Component {}
```

Compiled by meteor code

`let DriverItem = connect(_class = class DriverItem extends React.Component {})`

This code is not correct, arguments for `connect` were dropped, class shoudn't be an argument of `connect` Error in browser console as well 
![download](https://user-images.githubusercontent.com/4887213/40382160-5e011ac4-5e06-11e8-90a2-44915827b7dc.png)

Probably, i'm doing something wrong, any help really appreciated

**Comment by dagatsoin** [comment]
Can you try to inverse the order of plugins:

```
"plugins": [
		["@babel/plugin-proposal-decorators", { "legacy": true }],
		["@babel/plugin-proposal-class-properties", { "loose" : true }]
	]
```

**Comment by Deadly0** [comment]
@dagatsoin 

Error on meteor start
```
=> Started proxy.
=> Errors prevented startup:
   
   While processing files with ecmascript (for target web.browser):

   C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\modification.js:55:11:
   We don't know what to do with this node type. We were previously a
   Statement but we can't fit in here?
   at NodePath.insertBefore
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\modification.js:55:11)
   at PluginPass.Class
   (C:\Projects\dooglys\coordinator\node_modules\@babel\plugin-proposal-class-properties\lib\index.js:257:14)
   at newFn
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\visitors.js:237:21)
   at NodePath._call
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:65:20)
   at NodePath.call
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:40:17)
   at NodePath.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:100:12)
   at TraversalContext.visitQueue
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:142:16)
   at TraversalContext.visitSingle
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:102:19)
   at TraversalContext.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:182:19)
   at Function.traverse.node
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:106:17)
   at NodePath.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:107:18)
   at TraversalContext.visitQueue
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:142:16)
   at TraversalContext.visitMultiple
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:97:17)
   at TraversalContext.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:180:19)
   at Function.traverse.node
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:106:17)
   at NodePath.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:107:18)
   at TraversalContext.visitQueue
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:142:16)
   at TraversalContext.visitSingle
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:102:19)
   at TraversalContext.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:182:19)
   at Function.traverse.node
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:106:17)
   at traverse
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:76:12)
   at transformFile
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transformation\index.js:116:29)
   at runSync
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transformation\index.js:45:3)
   at transformFromAstSync
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transform-ast-sync.js:18:38)
   at Object.transformFromAst
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transform-ast.js:22:68)
   at transform
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:106:30)
   at compile
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:117:14)
   at Cache.Cp.get
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\cache.js:101:26)
   at Object.exports.compile
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:51:7)
   at Object.compile (packages/babel-compiler.js:50:29)
   at packages/babel-compiler.js:204:22
   at Function.time (C:\tools\tool-env\profile.js:305:10)
   at profile (packages/babel-compiler.js:252:20)
   at BabelCompiler.BCp.processOneFileForTarget
   (packages/babel-compiler.js:203:20)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:121:26)
   at Array.forEach (<anonymous>)
   at BabelCompiler.BCp.processFilesForTarget
   (packages/babel-compiler.js:120:14)
   
   
   While processing files with ecmascript (for target web.browser.legacy):

   C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\modification.js:55:11:
   We don't know what to do with this node type. We were previously a
   Statement but we can't fit in here?
   at NodePath.insertBefore
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\modification.js:55:11)
   at PluginPass.Class
   (C:\Projects\dooglys\coordinator\node_modules\@babel\plugin-proposal-class-properties\lib\index.js:257:14)
   at newFn
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\visitors.js:237:21)
   at NodePath._call
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:65:20)
   at NodePath.call
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:40:17)
   at NodePath.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:100:12)
   at TraversalContext.visitQueue
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:142:16)
   at TraversalContext.visitSingle
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:102:19)
   at TraversalContext.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:182:19)
   at Function.traverse.node
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:106:17)
   at NodePath.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:107:18)
   at TraversalContext.visitQueue
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:142:16)
   at TraversalContext.visitMultiple
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:97:17)
   at TraversalContext.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:180:19)
   at Function.traverse.node
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:106:17)
   at NodePath.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\path\context.js:107:18)
   at TraversalContext.visitQueue
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:142:16)
   at TraversalContext.visitSingle
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:102:19)
   at TraversalContext.visit
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\context.js:182:19)
   at Function.traverse.node
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:106:17)
   at traverse
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\traverse\lib\index.js:76:12)
   at transformFile
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transformation\index.js:116:29)
   at runSync
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transformation\index.js:45:3)
   at transformFromAstSync
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transform-ast-sync.js:18:38)
   at Object.transformFromAst
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\@babel\core\lib\transform-ast.js:22:68)
   at transform
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:106:30)
   at compile
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:117:14)
   at Cache.Cp.get
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\cache.js:101:26)
   at Object.exports.compile
   (C:\Users\Deadly\AppData\Local\.meteor\packages\ecmascript\0.11.0-rc17.11\plugin.compile-ecmascript.os\npm\node_modules\meteor\babel-compiler\node_modules\meteor-babel\index.js:51:7)
   at Object.compile (packages/babel-compiler.js:50:29)
   at packages/babel-compiler.js:204:22
   at Function.time (C:\tools\tool-env\profile.js:305:10)
   at profile (packages/babel-compiler.js:252:20)
   at BabelCompiler.BCp.processOneFileForTarget
   (packages/babel-compiler.js:203:20)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:121:26)
   at Array.forEach (<anonymous>)
   at BabelCompiler.BCp.processFilesForTarget
   (packages/babel-compiler.js:120:14)
```

**Comment by benjamn** [comment]
You shouldn't need to put `@babel/plugin-transform-class-properties` in `.babelrc`, since it's automatically [included by `meteor-babel`](https://github.com/meteor/babel/blob/0da4b9ec08fb37f30d0b2f531554de1f30bd8b4a/options.js#L85-L87). Try removing it?

**Comment by Deadly0** [comment]
@benjamn the same results with and without `@babel/plugin-transform-class-properties`: compiled code is incorrect.

**Comment by Deadly0** [comment]
I have create simple reproduction app https://github.com/Deadly0/docorators-bug-example

@benjamn please, pay attention on it. If there is no way to use decorators in 1.7 it may break alot of react app.

**Comment by benjamn** [comment]
So it sounds like the correct output should be
```js
connect(null, {
    showHideReport,
    showHideAddEditDriverModal,
    showHideTransactionDriverModal,
    deleteDriverRequest,
    sendDriverRequest,
})(_class = class DriverItem extends React.Component {})
```
Note the `)(` separating the argument lists. Does that sound right?

**Comment by benjamn** [comment]
This will be fixed once the next version of `@babel/plugin-proposal-decorators` is released with [this PR](https://github.com/babel/babel/pull/8021) included. Since it's a problem with a custom Babel plugin, it's not a blocker for Meteor 1.7, but I appreciate the bug report, because I agree there are likely to be many affected developers.

**Comment by benjamn** [comment]
Update: this should actually be fixed by https://github.com/meteor/babel/commit/b3a92723c6c3d94ac5646eef91a81ce0892450b8 (tests [here](https://github.com/meteor/babel/commit/6e016d396a9e46b4e2e118112e84789ace0fd2ac)), since the comments in https://github.com/babel/babel/pull/8021 revealed we could fix this on the `meteor-babel` side, rather than waiting for Babel.

**Comment by Deadly0** [comment]
@benjamn thank you, decorators now working again! Just for notice, decorators like `@someDecorator` without `()` not working well, but i don't care much about it.

Correct .babelrc for decorators if someone wants to use it:

```
{
	"plugins": [
		["@babel/plugin-proposal-decorators", { "legacy": true }]
	]
}
```

**Comment by bmanturner** [comment]
@Deadly0 @benjamn Any idea what to do for decorators without ```()```? I'm receiving this error:

```
Error: Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode. To use proposal-class-properties in spec mode with decorators, wait for the next major version of decorators in stage 2.
```

My babelrc looks like this:
```
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}
```

I'm on 1.7.0.1, the latest ```babel-compiler``` (7.1.1), and ```@babel/runtime``` is at 7.0.0-beta.51

**Comment by benjamn** [comment]
You might have to include `["@babel/plugin-proposal-class-properties", { "loose": true }]` in the `plugins` of your `.babelrc`, though 🤞that doesn't cause other problems.

**Comment by bmanturner** [comment]
@benjamn 

Unfortunately it does. Won't even compile.

(```@autobind``` comes from ```autobind-decorator```)

```
While processing files with ecmascript (for target web.browser.legacy):

   /Users/brendanturner/.meteor/packages/ecmascript/.0.11.1.jjf4nv.vaag++os+web.browser+web.browser.legacy+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transformation/file/file.js:231:12:
   /Users/brendanturner/dev/genesis/imports/ui/components/<FOLDERNAME>/Panels/<COMPONENTNAME>.jsx:
   Decorators transform is necessary.
     67 |   }
     68 |
   > 69 |   @autobind
   viewEnrollmentDetails(selectedEnrollment) {
        |   ^
     70 |     this.setState({
   selectedEnrollment, showDetailsModal: true
   });
     71 |   }
     72 |
```

**Comment by bmanturner** [comment]
Looks like I had the order backwards. The following worked:

```
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose" : true }]
  ]
}
```
