### ISSUE TITLE
Error on Meteor 1.6.1.1 MongoError: '$set' is empty

### ISSUE THREAD

**Issue by Jayuda** [meteor/meteor#9902]
Hello guys,
i was use 
Meteor 1.6.1.1
show error : 
```
20180524-16:56:39.105(7)? (STDERR)           
W20180524-16:56:39.148(7)? (STDERR) /home/jayuda/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20180524-16:56:39.148(7)? (STDERR)                                             throw(ex);
W20180524-16:56:39.149(7)? (STDERR)                                             ^
W20180524-16:56:39.149(7)? (STDERR) MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
W20180524-16:56:39.149(7)? (STDERR)     at Function.MongoError.create (/home/jayuda/.meteor/packages/npm-mongo/.2.2.34.1y5gwto.vnah++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
W20180524-16:56:39.150(7)? (STDERR)     at toError (/home/jayuda/.meteor/packages/npm-mongo/.2.2.34.1y5gwto.vnah++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/utils.js:139:22)
W20180524-16:56:39.150(7)? (STDERR)     at /home/jayuda/.meteor/packages/npm-mongo/.2.2.34.1y5gwto.vnah++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/collection.js:1059:67
W20180524-16:56:39.150(7)? (STDERR)     at /home/jayuda/.meteor/packages/npm-mongo/.2.2.34.1y5gwto.vnah++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:469:18
W20180524-16:56:39.151(7)? (STDERR)     at _combinedTickCallback (internal/process/next_tick.js:131:7)
W20180524-16:56:39.151(7)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

* After i am dowgrade to 1.6.0.1 , all work well *

**Comment by Brouilles** [comment]
Same problem for Meteor 1.6.1.1 and 1.7.0.3 ... Any solution ?

```
/Users/dezeiraud/.meteor/packages/promise/.0.11.1.1ka2059.vem3++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20180702-10:28:18.715(2)? (STDERR)       throw error;
W20180702-10:28:18.715(2)? (STDERR)       ^
W20180702-10:28:18.715(2)? (STDERR) MongoError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
W20180702-10:28:18.715(2)? (STDERR)     at Function.MongoError.create (/Users/dezeiraud/.meteor/packages/npm-mongo/.3.0.7.obb8dp.a7q8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:45:10)
W20180702-10:28:18.715(2)? (STDERR)     at toError (/Users/dezeiraud/.meteor/packages/npm-mongo/.3.0.7.obb8dp.a7q8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:149:22)
W20180702-10:28:18.715(2)? (STDERR)     at /Users/dezeiraud/.meteor/packages/npm-mongo/.3.0.7.obb8dp.a7q8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:1029:39
W20180702-10:28:18.715(2)? (STDERR)     at /Users/dezeiraud/.meteor/packages/npm-mongo/.3.0.7.obb8dp.a7q8++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:544:18
W20180702-10:28:18.716(2)? (STDERR)     at _combinedTickCallback (internal/process/next_tick.js:131:7)
W20180702-10:28:18.716(2)? (STDERR)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
