### ISSUE TITLE
Babel beta.48 crash: You gave us a visitor for the node type PrivateName but it's not a valid type

### ISSUE THREAD

**Issue by Floriferous** [meteor/meteor#9906]
Babel just released their 48th beta, which I automatically upgraded to. But my app crashed on launch, with the following error, on a random `.jsx` file: `You gave us a visitor for the node type PrivateName but it's not a valid type`.

Fixing `@babel/runtime`, `@babel/core`, `@babel/plugin-proposal-class-properties` and `babel-preset-meteor` to `"7.0.0-beta.47"` solves the issue.

Using Meteor 1.6.1.1.

Here's the stack trace:

```sh
=> Started proxy.
=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):
   /Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:163:13: [BABEL] /Users/Florian/dev/epotek/microservices/admin/imports/ui/pages/SingleLoanPage/LoanTabs/OverviewTab/LoanValidation/BorrowerIssues.jsx: You gave us a visitor for the node type PrivateName but it's not
   a valid type
   at verify (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:163:13)
   at Function.explode (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:64:3)
   at /Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:219:42
   at cachedFunction (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/caching.js:42:17)
   at loadPluginDescriptor (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:207:10)
   at /Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:64:16
   at Array.map (<anonymous>)
   at recurseDescriptors (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:63:36)
   at recurseDescriptors (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:97:26)
   at loadFullConfig (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:112:6)
   at transformFromAstSync (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast-sync.js:15:36)
   at Object.transformFromAst (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast.js:22:68)
   at transform (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:71:30)
   at compile (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:82:14)
   at Cache.Cp.get (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:101:26)
   at Object.compile (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:46:23)
   at Object.compile (packages/babel-compiler.js:51:29)
   at packages/babel-compiler.js:184:22
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/babel-compiler.js:232:20)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:183:20)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:111:26)
   at Array.forEach (<anonymous>)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:110:14)


   While processing files with ecmascript (for target os.osx.x86_64):
   /Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:163:13: [BABEL] /Users/Florian/dev/epotek/microservices/admin/imports/ui/pages/SingleLoanPage/LoanTabs/OverviewTab/LoanValidation/BorrowerIssues.jsx: You gave us a visitor for the node type PrivateName but it's not
   a valid type
   at verify (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:163:13)
   at Function.explode (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/traverse/lib/visitors.js:64:3)
   at /Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:219:42
   at cachedFunction (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/caching.js:42:17)
   at loadPluginDescriptor (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:207:10)
   at /Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:64:16
   at Array.map (<anonymous>)
   at recurseDescriptors (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:63:36)
   at recurseDescriptors (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:97:26)
   at loadFullConfig (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/config/full.js:112:6)
   at transformFromAstSync (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast-sync.js:15:36)
   at Object.transformFromAst (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/@babel/core/lib/transform-ast.js:22:68)
   at transform (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:71:30)
   at compile (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:82:14)
   at Cache.Cp.get (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:101:26)
   at Object.compile (/Users/Florian/.meteor/packages/ecmascript/.0.10.7.1nb1165.m0ko++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:46:23)
   at Object.compile (packages/babel-compiler.js:51:29)
   at packages/babel-compiler.js:184:22
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/babel-compiler.js:232:20)
   at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:183:20)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:111:26)
   at Array.forEach (<anonymous>)
   at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:110:14)


=> Your application has errors. Waiting for file change.
=> Started MongoDB.
```

**Comment by nickmarlou** [comment]
I face the same issue while trying to setup react-styleguidist on the create-next-app project

**Comment by junlouiegonzales** [comment]
+1 encountering the same problem after updating meteor 1.6.0.1 to 1.6.1.1.

**Comment by Floriferous** [comment]
This shouldn't be an issue anymore if you don't have overlapping babel@6, babel@7.beta and babel@7 packages.
