### ISSUE TITLE
Default `test` folder on 1.7.0.1 `meteor create` in legacy mode breaks the app

### ISSUE THREAD

**Issue by robfallows** [meteor/meteor#9961]
## Reproduction

`meteor create test-app`

Edit `package.json` to remove the `meteor` stanza. This restores legacy eager loading.

```
meteor npm i
meteor run

=> Started proxy.
=> Started MongoDB.
W20180607-11:11:12.808(1)? (STDERR) C:\Users\rfallows\AppData\Local\.meteor\packages\meteor-tool\1.7.0_1\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20180607-11:11:12.877(1)? (STDERR)                                             throw(ex);
W20180607-11:11:12.878(1)? (STDERR)                                             ^
W20180607-11:11:12.878(1)? (STDERR)
W20180607-11:11:12.879(1)? (STDERR) ReferenceError: describe is not defined
W20180607-11:11:12.879(1)? (STDERR)     at main.js (test/main.js:3:1)
W20180607-11:11:12.880(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:339:7)
W20180607-11:11:12.880(1)? (STDERR)     at require (packages\modules-runtime.js:238:16)
W20180607-11:11:12.880(1)? (STDERR)     at C:\Users\rfallows\meteor\mytest\.meteor\local\build\programs\server\app\app.js:91:1
W20180607-11:11:12.881(1)? (STDERR)     at C:\Users\rfallows\meteor\mytest\.meteor\local\build\programs\server\boot.js:411:36
W20180607-11:11:12.881(1)? (STDERR)     at Array.forEach (<anonymous>)
W20180607-11:11:12.881(1)? (STDERR)     at C:\Users\rfallows\meteor\mytest\.meteor\local\build\programs\server\boot.js:220:19
W20180607-11:11:12.882(1)? (STDERR)     at C:\Users\rfallows\meteor\mytest\.meteor\local\build\programs\server\boot.js:471:5
W20180607-11:11:12.882(1)? (STDERR)     at Function.run (C:\Users\rfallows\meteor\mytest\.meteor\local\build\programs\server\profile.js:510:12)
W20180607-11:11:12.882(1)? (STDERR)     at C:\Users\rfallows\meteor\mytest\.meteor\local\build\programs\server\boot.js:470:11
=> Exited with code: 1
```

Kill the process and rename folder `test/` to `tests/` and re-run:

```
mv test tests
meteor

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.
```

**Comment by benjamn** [comment]
That said, if anyone has time to submit a PR to rename the `test/` directory to `tests/` for [the default app](https://github.com/meteor/meteor/tree/devel/tools/static-assets/skel) and [the `--minimal` app](https://github.com/meteor/meteor/tree/devel/tools/static-assets/skel-minimal), I would happily merge it. Just be sure to update the `meteor.testModule` section in `package.json` accordingly.
