### ISSUE TITLE
Changed import behavior - devDependencies no longer usable in 1.7

### ISSUE THREAD

**Issue by dobesv** [meteor/meteor#9966]
We have this module that works fine in 1.6 but fails on startup in 1.7.0.1:

```
import bunyan from 'bunyan';
import os from 'os';
import PrettyStream from 'bunyan-prettystream';

const streams = [
  {
    level: 'debug',
    name: 'formative',
    stream: process.stdout,
  },
];

if (['development', 'test', 'mocha'].includes(process.env.NODE_ENV)) {
  try {
    const prettyStdOut = new PrettyStream({ mode: 'dev' });
    prettyStdOut.pipe(process.stdout);
    streams[0].stream = prettyStdOut;
  } catch (e) {
    // eslint-disable-next-line no-console
    console.warn(e);
  }
}

const log = bunyan.createLogger({
  hostname: process.env.GALAXY_CONTAINER_ID
    ? process.env.GALAXY_CONTAINER_ID.slice(-5)
    : os.hostname(),
  name: 'formative',
  streams,
  serializers: {
    err: err => ({
      code: err.code,
      data: err.data,
      message: err.message,
      name: err.name,
      stack: err.stack,
    }),
  },
});

process.on('unhandledRejection', error => {
  log.error('Unhandled promise rejection', { error });
});

export default log;
```

Error trace:

```
W20180607-11:59:31.366(-7)? (STDERR) TypeError: PrettyStream is not a constructor
W20180607-11:59:31.366(-7)? (STDERR)     at log.js (imports/lib/server/logger/log.js:15:26)
W20180607-11:59:31.366(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180607-11:59:31.366(-7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180607-11:59:31.366(-7)? (STDERR)     at profileWrapper (/home/ubuntu/app/.meteor/local/build/programs/server/profile.js:288:16)
W20180607-11:59:31.367(-7)? (STDERR)     at metrics.js (imports/startup/server/metrics.js:1:340)
W20180607-11:59:31.367(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180607-11:59:31.367(-7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180607-11:59:31.367(-7)? (STDERR)     at profileWrapper (/home/ubuntu/app/.meteor/local/build/programs/server/profile.js:288:16)
W20180607-11:59:31.367(-7)? (STDERR)     at gracefulShutdown.js (imports/startup/server/gracefulShutdown.js:1:315)
W20180607-11:59:31.367(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180607-11:59:31.367(-7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180607-11:59:31.367(-7)? (STDERR)     at profileWrapper (/home/ubuntu/app/.meteor/local/build/programs/server/profile.js:288:16)
W20180607-11:59:31.368(-7)? (STDERR)     at index.js (imports/startup/server/index.js:1:14)
W20180607-11:59:31.368(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180607-11:59:31.368(-7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180607-11:59:31.368(-7)? (STDERR)     at profileWrapper (/home/ubuntu/app/.meteor/local/build/programs/server/profile.js:288:16)
```

**Comment by benjamn** [comment]
A reproduction would be helpful here, since I don't know of anything that changed that should have affected this behavior.

**Comment by dobesv** [comment]
Hmm I tried creating a new project and running this code in it, and it worked.  Strange.

**Comment by dobesv** [comment]
Actually, the problem seems to be that `bunyan-prettystream` was in `devDependencies`.  I guess in meteor 1.6 the `devDependencies` are available to the server app, but not in `1.7`.  Not a big deal, I guess, but it would be nice if it were documented in https://guide.meteor.com/1.7-migration.html

**Comment by dobesv** [comment]
It would also be great if the import would fail instead of returning a useless object.

**Comment by dobesv** [comment]
Here's a reproduction:

https://github.com/dobesv/meteor-bunyan-import-issue
