### ISSUE TITLE
Maximum call stack size exceeded using methods in 1.7

### ISSUE THREAD

**Issue by jasongrishkoff** [meteor/meteor#9972]
Just updated to Meteor 1.7, and I'm encountering the following issue when fetching data via methods.  Is this possibly because I'm using mongod 3.4.4?  Would upgrading to 3.6 solve this?

From the client side, I call the method as such:
```
componentWillMount() {
  Meteor.call('countRefunds',function(err,res) {
    if (!err) this.setState({refunds:res})
  }.bind(this))
}
```

On the server side, I publish the following method:
```
countRefunds() {
  return Refunds.count()
}
```

It results in the following error: 
```
Exception while invoking method 'countRefunds' { stack: 'RangeError: Maximum call stack size exceeded\n    at replaceTypes (packages/mongo/mongo_driver.js:102:20)\n    at packages/mongo/mongo_driver.js:112:23\n    at Function._.each._.forEach (packages/underscore.js:147:22)\n    at replaceTypes (packages/mongo/mongo_driver.js:111:5)\n    at packages/mongo/mongo_driver.js:112:23\n    at Function._.each._.forEach (packages/underscore.js:147:22)\n    at replaceTypes (packages/mongo/mongo_driver.js:111:5)\n    at packages/mongo/mongo_driver.js:112:23\n    at Function._.each._.forEach (packages/underscore.js:147:22)\n    at replaceTypes (packages/mongo/mongo_driver.js:111:5)\n    at packages/mongo/mongo_driver.js:112:23\n    at Function._.each._.forEach (packages/underscore.js:147:22)\n    at replaceTypes (packages/mongo/mongo_driver.js:111:5)\n    at packages/mongo/mongo_driver.js:112:23\n    at Function._.each._.forEach (packages/underscore.js:147:22)\n    at replaceTypes (packages/mongo/mongo_driver.js:111:5)'
```

**Comment by preyasha2810** [comment]
@durjoy28 hello have you solved?
throw error;
^

RangeError: Maximum call stack size exceeded
