### ISSUE TITLE
[1.6.0.1] Servers silently hang and crash

### ISSUE THREAD

**Issue by WayneUong** [meteor/meteor#9993]
Our meteor servers hang for a short time and indefinitely at random time of the days. No errors were logged at the time of the freeze. We guess that some operations are taking place that block all others. The only errors we found after are these.

```
[xx.xx.xx.xx]Exception in callback of async function: RangeError: Maximum call stack size exceeded
[xx.xx.xx.xx]    at replaceMeteorAtomWithMongo (packages/mongo/mongo_driver.js:77:34)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:106:30)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]Exception in callback of async function: RangeError: Maximum call stack size exceeded
[xx.xx.xx.xx]    at replaceMeteorAtomWithMongo (packages/mongo/mongo_driver.js:77:34)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:106:30)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)


[xx.xx.xx.xx]Exception in callback of async function: RangeError: Maximum call stack size exceeded
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:111:20
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]Exception in callback of async function: RangeError: Maximum call stack size exceeded
[xx.xx.xx.xx]    at replaceMeteorAtomWithMongo (packages/mongo/mongo_driver.js:77:34)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:106:30)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)


[xx.xx.xx.xx]Exception in callback of async function: RangeError: Maximum call stack size exceeded
[xx.xx.xx.xx]    at looksLikeArray (packages/underscore.js:127:33)
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:140:16)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]Exception in callback of async function: RangeError: Maximum call stack size exceeded
[xx.xx.xx.xx]    at replaceMeteorAtomWithMongo (packages/mongo/mongo_driver.js:77:34)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:106:30)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
[xx.xx.xx.xx]    at replaceTypes (packages/mongo/mongo_driver.js:111:5)
[xx.xx.xx.xx]    at packages/mongo/mongo_driver.js:112:23
[xx.xx.xx.xx]    at Function._.each._.forEach (packages/underscore.js:147:22)
```

**Comment by maxfi** [comment]
I had what I believe to be the same issue when I upgraded from Meteor 1.6.0.1 to 1.7.0.1. 

Removing `meteorhacks:aggregate` package and refactoring the relevant aggregation code resolved the issue.

Meteor 1.6.0.1 was still [using the `mongodb@2.2.33` driver](https://github.com/meteor/meteor/blob/02cfd0fab1cdf11cc9582017556b0362416d53e6/packages/npm-mongo/package.js#L11). As of Meteor 1.6.2 the driver was [updated to `mongodb@3.0.5`](https://github.com/meteor/meteor/blob/0d5de210017bb0bc547e20fe1661afd86efe19bf/packages/npm-mongo/package.js#L11). The updated driver [returns a `cursor` instead of the results array](https://github.com/mongodb/node-mongodb-native/blob/c699603371e4f0ded705fb9714684cfcd85045c1/CHANGES_3.0.0.md) which I assumes breaks `meteorhacks:aggregate`.

You can refactor your existing code like so:

```
// meteorhacks:aggregate code
const result = SomeCollection.aggregate(pipeline)

// use the mongodb driver directly
const result = await SomeCollection.rawCollection().aggregate(pipeline).toArray()
```

**Comment by wavto** [comment]
The simplest solution is to replace the Meteor package `meteorhacks:aggregate` with `sakulstra:aggregate` since it fixes the issue and seams to be the "official" working fork of the first package. It's was not my idea, see https://github.com/meteorhacks/meteor-aggregate/issues/48#issuecomment-396610701 for details.

I created this pull request to update the Meteor documentation to use the working fork of the package https://github.com/meteor/galaxy-docs/pull/166
