### ISSUE TITLE
[1.7 ] meteor build tool doesn't start, SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by devagrawal09** [meteor/meteor#9995]
When trying to run `meteor`, the server doesn't start, and it crashes with this error - 
```
C:\Users\lenovo\AppData\Local\.meteor\packages\meteor-tool\1.7.0_1\mt-
os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected token
```

I recently updated the meteor version from 1.6 to 1.7, and since then this problem is happening.
I checked this file `promise-server.js` in the npm package `meteor-promise` package, and my best guess is that node doesn't recognise the keyword `throw` anymore.
There's not a lot of recipe to reproduce the bug, I have no idea where this comes from. Maybe it's the new version.
Please suggest a solution soon.

**Comment by pagesrichie** [comment]
Same:, running the 1.7.1-beta.2:

 /Users/macpc/.meteor/packages/static-html/.1.2.2.wp43cd.99etr++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at CssOutputResource._get (/tools/isobuild/compiler-plugin.js:923:23)
    at CssOutputResource.get data [as data] (/tools/isobuild/compiler-plugin.js:901:28)
    at resources.forEach.resource (/tools/isobuild/bundler.js:1164:28)
    at Array.forEach (<anonymous>)
    at sourceBatches.forEach.sourceBatch (/tools/isobuild/bundler.js:1137:17)
    at Array.forEach (<anonymous>)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1072:19)
    at ClientTarget.profileWrapper (/tools/tool-env/profile.js:283:16)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:837:12)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:828:18)
    at ClientTarget.profileWrapper (/tools/tool-env/profile.js:283:16)
    at /tools/isobuild/bundler.js:3019:14
    at profileWrapper (/tools/tool-env/profile.js:283:16)
    at /tools/isobuild/bundler.js:3108:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/Users/macpc/.meteor/packages/meteor-tool/.1.7.1-beta.2.1k5yg1e.6mxx++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:3107:7
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:3000:31)
    at files.withCache (/tools/isobuild/bundler.js:2947:32)
    at Object.<anonymous> (/tools/fs/files.js:1710:12)
    at Object.profileWrapper [as withCache] (/tools/tool-env/profile.js:283:16)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2947:16)
    at Profile.run (/tools/runners/run-app.js:579:36)
    at profileWrapper (/tools/tool-env/profile.js:283:16)
    at time (/tools/tool-env/profile.js:305:10)
    at Function.run (/tools/tool-env/profile.js:501:14)
    at bundleApp (/tools/runners/run-app.js:578:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by devagrawal09** [comment]
@abernix Yes that is the entire message that shows up in the terminal.

**Comment by GaetanRouzies** [comment]
Same here:
```
C:\Users\xShogo\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

SyntaxError: Unexpected token } in JSON at position 243
```

**Comment by mfechner** [comment]
Same problem here with Meteor 1.7.0.3 on Windows 10.

Get:
```
meteor run
...
=> Started proxy.
C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EPERM: operation not permitted, stat 'C:\git\idefix.fechner.net\timetracker\api\node_modules'
    at Object.fs.statSync (fs.js:948:11)
    at Object.wrapper (C:\tools\fs\files.js:1607:35)
    at Object.files.(anonymous function) [as stat] (C:\tools\fs\files.js:1745:27)
    at statOrNull (C:\tools\fs\files.js:291:15)
    at Object.files.statOrNull (C:\tools\fs\files.js:284:10)
    at C:\tools\fs\watch.js:288:24
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at readDirectory (C:\tools\fs\watch.js:285:5)
    at Object.readAndWatchDirectory (C:\tools\fs\watch.js:709:18)
    at PackageSource._readAndWatchDirectory (C:\tools\isobuild\package-source.js:828:18)
    at find (C:\tools\isobuild\package-source.js:1232:14)
    at files.withCache (C:\tools\isobuild\package-source.js:1288:34)
    at Object.withCache (C:\tools\fs\files.js:1710:12)
    at PackageSource._findSources (C:\tools\isobuild\package-source.js:1288:18)
    at SourceArch.getFiles (C:\tools\isobuild\package-source.js:900:32)
    at C:\tools\isobuild\compiler.js:406:23
    at files.withCache (C:\tools\isobuild\compiler.js:186:28)
    at Object.withCache (C:\tools\fs\files.js:1710:12)
    at C:\tools\isobuild\compiler.js:185:11
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (C:\Users\idefix\AppData\Local\.meteor\packages\meteor-tool\1.7.0_3\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Object.compile (C:\tools\isobuild\compiler.js:180:5)
    at C:\tools\isobuild\bundler.js:3057:24
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:3000:31)
    at files.withCache (C:\tools\isobuild\bundler.js:2947:32)
    at Object.withCache (C:\tools\fs\files.js:1710:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2947:16)
    at Profile.run (C:\tools\runners\run-app.js:579:36)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at bundleApp (C:\tools\runners\run-app.js:578:34)
    at AppRunner._runOnce (C:\tools\runners\run-app.js:622:35)
    at AppRunner._fiber (C:\tools\runners\run-app.js:880:28)
    at C:\tools\runners\run-app.js:408:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! timetracker@0.0.0 api: `cd api && meteor run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the timetracker@0.0.0 api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\idefix\AppData\Roaming\npm-cache\_logs\2018-07-12T14_45_06_163Z-debug.log
```
Tried already to deinstall meteor, deleted complete `AppData\Local\.meteor` and reinstalled it with `choco` but the error message does not go away.

**Comment by jlmbaka** [comment]
I'm facing the same problem. Still no solutions ?

**Comment by abernix** [comment]
Each error reported in this issue has exhibited a different actual error message.

Issue participants: Please take care when relating/identifying with an issue and correlate them on something other than the filename in which the error seemingly occurred since `promise_server.js` can be a bit of a catch-all for errors which occur within Meteor's Fiber-aware `Promise` implementation.

That said, if anyone can come up with a reliable reproduction in the form of a Git repository, we'd be happy to take a look at it but given the current issues, it's looking like there are a lot of unrelated issues here that are manifesting themselves as (seemingly) the same problem.

**Comment by HLODev01** [comment]
I checked my code for this, and I found that there was a `const` I defined but did not use. When I removed the `const`, the build tool was working fine.
If anyone comes up with a similar issue, just check your code for unused constants.
