### ISSUE TITLE
Upgrading from 1.6 -> 1.7: Mongo 'Password contains an illegal unescaped character'

### ISSUE THREAD

**Issue by bmanturner** [meteor/meteor#9996]
My company uses ```MongoInternals.RemoteCollectionDriver(mongoUrl);``` to connect to our various databases. Some of our passwords contain a '$', which is an 'illegal unescaped character'. I checked and the RemoteCollectionDriver doesn't allow for passing credentials alongside the mongo url. I've also attempted putting a ```'\'``` before the offending character but it made no difference.

Please advise. Thanks in advance.

**Comment by abernix** [comment]
You should URL-encode the values, so `$` would become `%24`.  It should not be escaped with a backslash.

**Comment by bmanturner** [comment]
Should I close this or leave it open to explore adding more options to RemoteCollectionDriver?

**Comment by abernix** [comment]
What option would you propose be added?  The [Mongo connection string](https://docs.mongodb.com/manual/reference/connection-string/) is designed to be in the [URI format](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax).  Whether that URI schema is `mongo`, `https`, `ftp`, or otherwise, it needs to be URI-encoded in order to be valid.

In other words, an option to URI-encode it for you wouldn't be entirely appropriate.

**Comment by tonymckendry** [comment]
@abernix This has started happening on one of our projects since updating it from 1.6 to 1.7 - does this mean that all of our users' existing passwords (across any project that gets updated) are going to be invalid and need to be re-encoded somehow?

**Comment by tonymckendry** [comment]
Ive attempted to re-encode all of our passwords, and even went so far as to wipe all of our users out of our db and deploy a fresh version of the app to a new server (just to see if I could get the server to start) - no dice. I am still getting the following error even when I have zero users in my database: 

```
/app/bundle/programs/server/node_modules/fibers/future.js:280
	throw(ex);
	^

Error: Password contains an illegal unescaped character
 at parseConnectionString (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:297:13)
 at parseHandler (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:129:14)
 at module.exports (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:25:12)
 at connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:878:3)
 at connectOp (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:268:3)
 at executeOperation (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:420:24)
 at MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:259:10)
 at Function.MongoClient.connect (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:480:22)
 at new MongoConnection (packages/mongo/mongo_driver.js:169:11)
 at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
 at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
 at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
 at new Collection (packages/mongo/collection.js:97:40)
 at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
 at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
 at server_main.js (packages/accounts-base/server_main.js:9:12)
```

**Comment by hkstsony** [comment]
I'm having the same issue even though the user collection is empty

**Comment by glasser** [comment]
This is about how you put your MongoDB password into MONGO_URL and/or MONGO_OPLOG_URL, not anything related to users of your apps. It sounds like the newer mongo client is stricter about encoding characters in password URLs. You'll want to convert interesting characters to their %-encoded alternative; a simple way to do that is to run it through the browser encodeURIComponent function.

**Comment by sushannnt** [comment]
Error: Username contains an illegal unescaped character
